### ISSUE TITLE
TIKV seems to automatically restart everyday.

### ISSUE THREAD

**Issue by whyliyu** [pingcap/tidb#10198]
**problem:**
Last night at 22:32 clients warned exception like this:
```
Exception: java.lang.RuntimeException
Message: java.sql.SQLException: Information schema is out of date.
Stack: 
java.lang.RuntimeException: java.sql.SQLException: Information schema is out of date.
at com.netease.mail.holmes.KafkaSource$MySQLRecords.put(KafkaSource.java:217)
at com.netease.mail.holmes.KafkaSource$MySQLRecords.access$200(KafkaSource.java:186)
at com.netease.mail.holmes.KafkaSource.commit(KafkaSource.java:126)
at com.netease.mail.holmes.Pipeline.start(Pipeline.java:58)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Information schema is out of date.
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444)
at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
at com.netease.mail.holmes.KafkaSource$MySQLRecords.put(KafkaSource.java:215)
... 4 more

```
I checked tidb log and it showed it could not connect to tikv at that moment, which lasted about 1 minutes:
```
2019/04/18 22:32:54.990 region_cache.go:482: [info] drop regions that on the store 1(10.200.168.193:20172) due to send request fail, err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.200.168.193:20172: connect: connection refused"
2019/04/18 22:32:54.996 region_cache.go:482: [info] drop regions that on the store 1(10.200.168.193:20172) due to send request fail, err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 10.200.168.193:20172: connect: connection refused"
2019/04/18 22:32:55.083 session.go:367: [warning] con:0 finished txn:Txn{state=invalid}, [domain:1]Information schema is out of date.
2019/04/18 22:32:55.083 adapter.go:379: [warning] [SLOW_QUERY] [INTERNAL] cost_time:5.002992006s  succ:false con:0 user:<nil> txn_start_ts:407790674265767938 database: sql:commit
2019/04/18 22:32:55.083 session.go:766: [warning] con:0 schema_ver:3942 session error:
[domain:1]Information schema is out of date.
github.com/pingcap/errors.AddStack
        /home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/errors.Trace
        /home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).checkSchemaValid
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:646
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).execute
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:612
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).executeAndWriteFinishBinlog
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:551
github.com/pingcap/tidb/store/tikv.(*tikvTxn).Commit
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/store/tikv/txn.go:192
github.com/pingcap/tidb/session.(*TxnState).Commit
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/txn.go:159
github.com/pingcap/tidb/session.(*session).doCommit
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:314
github.com/pingcap/tidb/session.(*session).doCommitWithRetry
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:325
github.com/pingcap/tidb/session.(*session).CommitTxn
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:385
github.com/pingcap/tidb/session.runStmt
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/tidb.go:168
github.com/pingcap/tidb/session.(*session).executeStatement
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:763
github.com/pingcap/tidb/session.(*session).execute
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:827
github.com/pingcap/tidb/session.(*session).Execute
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:780
github.com/pingcap/tidb/statistics.finishTransaction
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/statistics/ddl.go:147
github.com/pingcap/tidb/statistics.(*Handle).dumpTableStatCountToKV.func1
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/statistics/update.go:326
github.com/pingcap/tidb/statistics.(*Handle).dumpTableStatCountToKV
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/statistics/update.go:339
github.com/pingcap/tidb/statistics.(*Handle).DumpStatsDeltaToKV
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/statistics/update.go:291
github.com/pingcap/tidb/domain.(*Domain).updateStatsWorker
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/domain/domain.go:885
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
{
  "currDBName": "",
  "id": 0,
  "status": 2,
  "strictMode": true,
  "user": null
}
...
```

And the tikv logs it might have a restart at that time:
```
2019/04/18 22:32:43.021 INFO mod.rs:26: Welcome to TiKV. 
Release Version:   2.1.1
Git Commit Hash:   b48f3317c162fb69a1589e48c83452c2b89efb9d
Git Commit Branch: release-2.1
UTC Build Time:    2018-12-12 10:56:04
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)
2019/04/18 22:32:43.025 INFO tikv-server.rs:405: using config: {
  "log-level": "info",
  "log-file": "/disk1/pingcap/log/tikv.log",
  "log-rotation-timespan": "24h",
  "readpool": {
    "storage": {
      "high-concurrency": 8,
      "normal-concurrency": 8,
      "low-concurrency": 8,
      "max-tasks-per-worker-high": 2000,
      "max-tasks-per-worker-normal": 2000,
      "max-tasks-per-worker-low": 2000,
      "stack-size": "10MB"
    },
    "coprocessor": {
      "high-concurrency": 32,
      "normal-concurrency": 32,
      "low-concurrency": 32,
      "max-tasks-per-worker-high": 2000,
      "max-tasks-per-worker-normal": 2000,
      "max-tasks-per-worker-low": 2000,
      "stack-size": "10MB"
    }
...
```

When I checked throw the entire log, I found the TIKV seemed to restart everyday:
![image](https://user-images.githubusercontent.com/17723541/56403570-75a5e900-6294-11e9-93c7-878ce831ef73.png)

Can someone help clarify this?

```
version:2.1
deployment:
machine1: tidb,tikv * 2,pd；ssd2T * 2
machine2: tidb,tikv * 2；ssd2T * 2
machine3: tikv * 2；ssd2T * 2
```

**Comment by shenli** [comment]
@whyliyu Thanks for your feedback!
Is there any OOM message in dmesg or any error message in tikv's log?

**Comment by whyliyu** [comment]
> @whyliyu Thanks for your feedback!
> Is there any OOM message in dmesg or any error message in tikv's log?

In tikv log, before the 'Welcome to TiKV' statements exists a large quantity of logs with the same format:
```
2019/04/18 22:31:40.043 INFO apply.rs:902: [region 195636] 329454 execute admin command cmd_type: CompactLog compact_log {compact_index: 1262805 compact_term: 86} at [term: 86, index: 1262807]
2019/04/18 22:31:40.044 INFO apply.rs:902: [region 298112] 310325 execute admin command cmd_type: CompactLog compact_log {compact_index: 85389 compact_term: 11} at [term: 11, index: 85391]
2019/04/18 22:31:44.102 INFO apply.rs:902: [region 153556] 344035 execute admin command cmd_type: CompactLog compact_log {compact_index: 754345 compact_term: 36} at [term: 36, index: 754347]
2019/04/18 22:31:45.669 INFO apply.rs:902: [region 243187] 243190 execute admin command cmd_type: CompactLog compact_log {compact_index: 129054 compact_term: 18} at [term: 18, index: 129056]
2019/04/18 22:31:45.669 INFO apply.rs:902: [region 243360] 283284 execute admin command cmd_type: CompactLog compact_log {compact_index: 3158886 compact_term: 29} at [term: 29, index: 3158888]
2019/04/18 22:31:47.668 INFO apply.rs:902: [region 176548] 328001 execute admin command cmd_type: CompactLog compact_log {compact_index: 7958176 compact_term: 43} at [term: 43, index: 7958178]
2019/04/18 22:31:50.213 INFO apply.rs:902: [region 130245] 335813 execute admin command cmd_type: CompactLog compact_log {compact_index: 669567 compact_term: 36} at [term: 36, index: 669569]
2019/04/18 22:31:52.604 INFO apply.rs:902: [region 241182] 338407 execute admin command cmd_type: CompactLog compact_log {compact_index: 970601 compact_term: 17} at [term: 17, index: 970603]
2019/04/18 22:31:55.771 INFO apply.rs:902: [region 241142] 336675 execute admin command cmd_type: CompactLog compact_log {compact_index: 6162546 compact_term: 32} at [term: 32, index: 6162548]
2019/04/18 22:31:55.771 INFO apply.rs:902: [region 241122] 241322 execute admin command cmd_type: CompactLog compact_log {compact_index: 5926567 compact_term: 25} at [term: 25, index: 5926569]
2019/04/18 22:31:55.771 INFO apply.rs:902: [region 243360] 283284 execute admin command cmd_type: CompactLog compact_log {compact_index: 3159255 compact_term: 29} at [term: 29, index: 3159257]
2019/04/18 22:31:55.771 INFO apply.rs:902: [region 129044] 335226 execute admin command cmd_type: CompactLog compact_log {compact_index: 28842419 compact_term: 246} at [term: 246, index: 28842421]
2019/04/18 22:31:57.664 INFO apply.rs:902: [region 176548] 328001 execute admin command cmd_type: CompactLog compact_log {compact_index: 7958243 compact_term: 43} at [term: 43, index: 7958245]
2019/04/18 22:31:57.932 INFO apply.rs:902: [region 129076] 343767 execute admin command cmd_type: CompactLog compact_log {compact_index: 4183901 compact_term: 1123} at [term: 1123, index: 4183903]
2019/04/18 22:31:58.892 INFO apply.rs:902: [region 241098] 244007 execute admin command cmd_type: CompactLog compact_log {compact_index: 9267537 compact_term: 33} at [term: 33, index: 9267539]
2019/04/18 22:31:59.051 INFO apply.rs:902: [region 242305] 301313 execute admin command cmd_type: CompactLog compact_log {compact_index: 116012 compact_term: 28} at [term: 28, index: 116014]
2019/04/18 22:31:59.249 INFO apply.rs:902: [region 243336] 332882 execute admin command cmd_type: CompactLog compact_log {compact_index: 7851337 compact_term: 33} at [term: 33, index: 7851340]
2019/04/18 22:31:59.808 INFO apply.rs:902: [region 213787] 334357 execute admin command cmd_type: CompactLog compact_log {compact_index: 2587606 compact_term: 31} at [term: 31, index: 2587608]
2019/04/18 22:32:05.874 INFO apply.rs:902: [region 241142] 336675 execute admin command cmd_type: CompactLog compact_log {compact_index: 6162777 compact_term: 32} at [term: 32, index: 6162779]
2019/04/18 22:32:05.874 INFO apply.rs:902: [region 228766] 290801 execute admin command cmd_type: CompactLog compact_log {compact_index: 823116 compact_term: 22} at [term: 22, index: 823118]
2019/04/18 22:32:07.833 ERRO endpoint.rs:468: Locked(primary_lock: "t\200\000\000\000\000\000\004b_r\200\000\000\000\000\000\000\006" lock_version: 407790661564891138 key: "t\200\000\000\000\000\000\004b_r\200\000\000\000\000'$\364" lock_ttl: 20226)
2019/04/18 22:32:07.936 INFO apply.rs:902: [region 243384] 266188 execute admin command cmd_type: CompactLog compact_log {compact_index: 1760495 compact_term: 26} at [term: 26, index: 1760497]
2019/04/18 22:32:07.943 ERRO endpoint.rs:468: Locked(primary_lock: "t\200\000\000\000\000\000\004b_r\200\000\000\000\000\000\000\006" lock_version: 407790661564891138 key: "t\200\000\000\000\000\000\004b_r\200\000\000\000\000+\004\304" lock_ttl: 20226)
2019/04/18 22:32:08.058 ERRO endpoint.rs:468: Locked(primary_lock: "t\200\000\000\000\000\000\004b_r\200\000\000\000\000\000\000\006" lock_version: 407790661564891138 key: "t\200\000\000\000\000\000\004b_r\200\000\000\000\000J1\t" lock_ttl: 20226)
2019/04/18 22:32:08.956 INFO apply.rs:902: [region 266171] 300647 execute admin command cmd_type: CompactLog compact_log {compact_index: 391923 compact_term: 14} at [term: 14, index: 391925]
2019/04/18 22:32:10.202 INFO size.rs:173: [region 241198] approximate size 177060824 >= 150994944, need to do split check
2019/04/18 22:32:10.216 INFO apply.rs:902: [region 129202] 311940 execute admin command cmd_type: CompactLog compact_log {compact_index: 1129688 compact_term: 41} at [term: 41, index: 1129690]
2019/04/18 22:32:10.216 INFO apply.rs:902: [region 243048] 243051 execute admin command cmd_type: CompactLog compact_log {compact_index: 178204 compact_term: 21} at [term: 21, index: 178206]
2019/04/18 22:32:13.523 INFO apply.rs:902: [region 129056] 320529 execute admin command cmd_type: CompactLog compact_log {compact_index: 648208 compact_term: 80} at [term: 80, index: 648210]
2019/04/18 22:32:13.526 INFO apply.rs:902: [region 277657] 277660 execute admin command cmd_type: CompactLog compact_log {compact_index: 1352004 compact_term: 15} at [term: 15, index: 1352006]
2019/04/18 22:32:14.402 INFO apply.rs:902: [region 129235] 296773 execute admin command cmd_type: CompactLog compact_log {compact_index: 1097202 compact_term: 48} at [term: 48, index: 1097204]
2019/04/18 22:32:16.001 INFO apply.rs:902: [region 241122] 241322 execute admin command cmd_type: CompactLog compact_log {compact_index: 5926640 compact_term: 25} at [term: 25, index: 5926642]
2019/04/18 22:32:16.001 INFO apply.rs:902: [region 129080] 318379 execute admin command cmd_type: CompactLog compact_log {compact_index: 2093963 compact_term: 59} at [term: 59, index: 2093965]
2019/04/18 22:32:16.001 INFO apply.rs:902: [region 129044] 335226 execute admin command cmd_type: CompactLog compact_log {compact_index: 28842492 compact_term: 246} at [term: 246, index: 28842494]
2019/04/18 22:32:16.001 INFO apply.rs:902: [region 241142] 336675 execute admin command cmd_type: CompactLog compact_log {compact_index: 6162842 compact_term: 32} at [term: 32, index: 6162844]
2019/04/18 22:32:16.001 INFO apply.rs:902: [region 241198] 340414 execute admin command cmd_type: CompactLog compact_log {compact_index: 2767670 compact_term: 1048} at [term: 1048, index: 2767672]
2019/04/18 22:32:17.847 INFO apply.rs:902: [region 241206] 312003 execute admin command cmd_type: CompactLog compact_log {compact_index: 242310 compact_term: 28} at [term: 28, index: 242312]
2019/04/18 22:32:17.847 INFO apply.rs:902: [region 176548] 328001 execute admin command cmd_type: CompactLog compact_log {compact_index: 7958352 compact_term: 43} at [term: 43, index: 7958354]

```
Among thoes logs exist several ERRO log like this:
```
2019/04/18 22:32:07.833 ERRO endpoint.rs:468: Locked(primary_lock: "t\200\000\000\000\000\000\004b_r\200\000\000\000\000\000\000\006" lock_version: 407790661564891138 key: "t\200\000\000\000\000\000\004b_r\200\000\000\000\000'$\364" lock_ttl: 20226)

```



I'm not sure whether there was a OOM. There are some monitor graph, maybe it would help
![1](https://user-images.githubusercontent.com/17723541/56404311-89534e80-6298-11e9-8475-08f250000ac8.JPG)

![捕获](https://user-images.githubusercontent.com/17723541/56404314-8ce6d580-6298-11e9-98da-b8210b6ec2c1.JPG)


![3](https://user-images.githubusercontent.com/17723541/56404315-8eb09900-6298-11e9-9d3c-8f25f1bd5ffc.JPG)


![4](https://user-images.githubusercontent.com/17723541/56404317-907a5c80-6298-11e9-9dfc-8c72d183839e.JPG)

**Comment by zhangjinpeng1987** [comment]
@whyliyu Can you provide system dmesg log?

**Comment by whyliyu** [comment]
> @whyliyu Can you provide system dmesg log?
> The logs you provide seems is normal.

@zhangjinpeng1987  @shenli  dmesg log was overriged by new info, but I found somthing in /var/log/syslog, which showed the tikv was kill by tidb:
```
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981660] tidb-server invoked oom-killer: gfp_mask=0x201da, order=0, oom_score_adj=0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981664] tidb-server cpuset=/ mems_allowed=0-1
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981666] CPU: 24 PID: 97893 Comm: tidb-server Not tainted 3.10.0-693.el7.x86_64 #1
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981667] Hardware name: Dell Inc. PowerEdge R630/02C2CP, BIOS 2.5.5 08/16/2017
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981668]  ffff881890c69fa0 00000000da1af915 ffff8818b267f920 ffffffff816a3d91
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981671]  ffff8818b267f9b0 ffffffff8169f186 ffffffff810e939c 0000000000000001
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981673]  000000000001788c ffff8818b267fa08 ffffffff81a2b5e0 0000000000000001
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981675] Call Trace:
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981683]  [<ffffffff816a3d91>] dump_stack+0x19/0x1b
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981685]  [<ffffffff8169f186>] dump_header+0x90/0x229
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981689]  [<ffffffff810e939c>] ? ktime_get_ts64+0x4c/0xf0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981694]  [<ffffffff81186394>] oom_kill_process+0x254/0x3d0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981696]  [<ffffffff81185e3d>] ? oom_unkillable_task+0xcd/0x120
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981698]  [<ffffffff81185ee6>] ? find_lock_task_mm+0x56/0xc0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981700]  [<ffffffff81186bd6>] out_of_memory+0x4b6/0x4f0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981702]  [<ffffffff8169fc8a>] __alloc_pages_slowpath+0x5d6/0x724
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981705]  [<ffffffff8118cd85>] __alloc_pages_nodemask+0x405/0x420
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981711]  [<ffffffff811d1108>] alloc_pages_current+0x98/0x110
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981714]  [<ffffffff81182917>] __page_cache_alloc+0x97/0xb0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981731]  [<ffffffff81184eb0>] filemap_fault+0x170/0x410
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981755]  [<ffffffffc02db156>] ext4_filemap_fault+0x36/0x50 [ext4]
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981761]  [<ffffffff811ad162>] __do_fault+0x52/0xe0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981763]  [<ffffffff811ad60b>] do_read_fault.isra.44+0x4b/0x130
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981765]  [<ffffffff811b1f11>] handle_mm_fault+0x691/0xfa0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981770]  [<ffffffff816affb4>] __do_page_fault+0x154/0x450
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981773]  [<ffffffff816b02e5>] do_page_fault+0x35/0x90
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981776]  [<ffffffff816ac508>] page_fault+0x28/0x30
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981777] Mem-Info:
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981783] active_anon:48032850 inactive_anon:461450 isolated_anon:0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981783]  active_file:38 inactive_file:0 isolated_file:0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981783]  unevictable:0 dirty:122 writeback:0 unstable:0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981783]  slab_reclaimable:289984 slab_unreclaimable:42098
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981783]  mapped:3012 shmem:1052113 pagetables:130914 bounce:0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981783]  free:122174 free_pcp:546 free_cma:0
...
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981962] Out of memory: Kill process 73889 (tikv-server) score 394 or sacrifice child
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.983492] Killed process 73889 (tikv-server) total-vm:112828160kB, anon-rss:77804048kB, file-rss:40kB, shmem-rss:0kB
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987867] tidb-server invoked oom-killer: gfp_mask=0x280da, order=0, oom_score_adj=0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987870] tidb-server cpuset=/ mems_allowed=0-1
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987872] CPU: 32 PID: 97917 Comm: tidb-server Not tainted 3.10.0-693.el7.x86_64 #1
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987873] Hardware name: Dell Inc. PowerEdge R630/02C2CP, BIOS 2.5.5 08/16/2017
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987875]  ffff88189bcc2f70 000000003157afe7 ffff8812c11d3a70 ffffffff816a3d91
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987878]  ffff8812c11d3b00 ffffffff8169f186 ffffffff810e939c ffff8812c11d3b10
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987880]  ffff880117b57e68 ffff8812c11d3b58 000000000001788c 0000000000000001
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987882] Call Trace:
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987886]  [<ffffffff816a3d91>] dump_stack+0x19/0x1b
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987888]  [<ffffffff8169f186>] dump_header+0x90/0x229
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987891]  [<ffffffff810e939c>] ? ktime_get_ts64+0x4c/0xf0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987893]  [<ffffffff81186394>] oom_kill_process+0x254/0x3d0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987896]  [<ffffffff81185e3d>] ? oom_unkillable_task+0xcd/0x120
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987898]  [<ffffffff81185ee6>] ? find_lock_task_mm+0x56/0xc0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987900]  [<ffffffff81186bd6>] out_of_memory+0x4b6/0x4f0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987902]  [<ffffffff8169fc8a>] __alloc_pages_slowpath+0x5d6/0x724
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987904]  [<ffffffff8118cd85>] __alloc_pages_nodemask+0x405/0x420
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987907]  [<ffffffff811d412f>] alloc_pages_vma+0xaf/0x1f0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987909]  [<ffffffff811b23e0>] handle_mm_fault+0xb60/0xfa0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987912]  [<ffffffff816affb4>] __do_page_fault+0x154/0x450
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987914]  [<ffffffff816b02e5>] do_page_fault+0x35/0x90
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987916]  [<ffffffff816ac508>] page_fault+0x28/0x30
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987917] Mem-Info:
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987922] active_anon:48033560 inactive_anon:461450 isolated_anon:0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987922]  active_file:0 inactive_file:0 isolated_file:0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987922]  unevictable:0 dirty:122 writeback:0 unstable:0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987922]  slab_reclaimable:289984 slab_unreclaimable:42098
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987922]  mapped:3116 shmem:1052113 pagetables:130914 bounce:0
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.987922]  free:121242 free_pcp:1198 free_cma:0

```
Note these 2 lines:
```
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981660] tidb-server invoked oom-killer: gfp_mask=0x201da, order=0, oom_score_adj=0
...
Apr 18 22:32:18 holmes-db-1 kernel: [11098769.981962] Out of memory: Kill process 73889 (tikv-server) score 394 or sacrifice child 
```
Tidb invoked oom-killer at first and then tikv was killed

**Comment by whyliyu** [comment]
I found the reason - tikv took too much memory and was kill by os. And it seems that tikv could be restarted by some script (or other service?) when it was killed by accident. But I didn't found who did this.

**Comment by whyliyu** [comment]
Now it's clear, automatically restarting is done by os service framework. Becuase tikv was started by sysclt, In which manner it will be restarted when it crash by accident.
