### ISSUE TITLE
Got panic when running tispark test

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#10280]
## Bug Report

1. What did you do?

Run [tispark integration test](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tispark_ghpr_integration_test/detail/tispark_ghpr_integration_test/231/pipeline)

2. What did you expect to see?

The test can [pass](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tispark_ghpr_integration_test/detail/tispark_ghpr_integration_test/232/pipeline) when using older version of tidb, however failed with master version of tidb.

3. What did you see instead?

The test got stucked.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

c2b975b217ebade4d2e8bcf29a1deecaf9a6889e

---
 Here is the log:
```
[2019/04/26 20:08:38.280 +08:00] [ERROR] [conn.go:599] ["connection running loop panic"] [conn=1] [lastCmd="analyze table tispark_test.full_data_type_table_idx"] [err="\"slice bounds out of range\""] [stack="goroutine 4325 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x2156700, 0xc00b525bf0, 0xc00ad87200)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:597 +0xee\npanic(0x1cb7860, 0x3040a30)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/pingcap/tidb/statistics.MoveToHistory(0xc046bde7e0)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/statistics/analyze_jobs.go:68 +0x1b5\ngithub.com/pingcap/tidb/executor.(*AnalyzeExec).Next(0xc046bde750, 0x2156640, 0xc046d649c0, 0xc046d52188, 0x218e340, 0xc00a5b9770)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/analyze.go:124 +0xa92\ngithub.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc046a77700, 0x2156640, 0xc046d649c0, 0x218e340, 0xc00a5b9770, 0x2165960, 0xc046bde750, 0x0, 0x0, 0x0, ...)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:306 +0x1f3\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc046a77700, 0x2156640, 0xc046d649c0, 0x0, 0x0, 0x0, 0x0)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:251 +0x5ad\ngithub.com/pingcap/tidb/session.runStmt(0x2156640, 0xc046d649c0, 0x218e340, 0xc00a5b9770, 0x215c500, 0xc046a77700, 0x0, 0x0, 0x0, 0x0)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/tidb.go:213 +0x100\ngithub.com/pingcap/tidb/session.(*session).executeStatement(0xc00a5b9770, 0x2156640, 0xc046d649c0, 0x1, 0x215b900, 0xc046d5f6c0, 0x215c500, 0xc046a77700, 0x0, 0x0, ...)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:940 +0x1cb\ngithub.com/pingcap/tidb/session.(*session).execute(0xc00a5b9770, 0x2156640, 0xc046d649c0, 0xc046d04a81, 0x33, 0x1, 0x21761a0, 0x338c210, 0x4000, 0x4000)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:1026 +0x733\ngithub.com/pingcap/tidb/session.(*session).Execute(0xc00a5b9770, 0x2156640, 0xc046d649c0, 0xc046d04a81, 0x33, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:967 +0xc4\ngithub.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc00b2cb740, 0x2156640, 0xc046d649c0, 0xc046d04a81, 0x33, 0xc00be44d80, 0xc03b657180, 0x16, 0x0, 0x0)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/driver_tidb.go:246 +0x7c\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc00ad87200, 0x2156640, 0xc046d649c0, 0xc046d04a81, 0x33, 0x0, 0x0)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1164 +0x8e\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc00ad87200, 0x2156700, 0xc00b525bf0, 0xc046d04a81, 0x34, 0x34, 0x0, 0x0)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:891 +0x675\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc00ad87200, 0x2156700, 0xc00b525bf0)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:650 +0x258\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc00b5e0620, 0xc00ad87200)\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/server.go:438 +0x450\ncreated by github.com/pingcap/tidb/server.(*Server).Run\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/server.go:358 +0x83d\n"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:599\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:522\nruntime.panicslice\n\t/usr/local/go/src/runtime/panic.go:54\ngithub.com/pingcap/tidb/statistics.MoveToHistory\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/statistics/analyze_jobs.go:68\ngithub.com/pingcap/tidb/executor.(*AnalyzeExec).Next\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/analyze.go:124\ngithub.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:306\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:251\ngithub.com/pingcap/tidb/session.runStmt\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/tidb.go:213\ngithub.com/pingcap/tidb/session.(*session).executeStatement\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:940\ngithub.com/pingcap/tidb/session.(*session).execute\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:1026\ngithub.com/pingcap/tidb/session.(*session).Execute\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:967\ngithub.com/pingcap/tidb/server.(*TiDBContext).Execute\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/driver_tidb.go:246\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1164\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:891\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:650\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/server.go:438"]
[2019/04/26 20:08:38.280 +08:00] [INFO] [server.go:417] ["connection closed"] [conn=1]
[2019/04/26 20:08:39.322 +08:00] [WARN] [conn.go:436] ["parse attrs failed"] [conn=2] [error=EOF]
```
and got panic at
https://github.com/pingcap/tidb/blob/a28d8779c18d0fae4362b99928511711584d7eb9/statistics/analyze_jobs.go#L68

**Comment by zz-jason** [comment]
@lzmhhh123 PTAL
