### ISSUE TITLE
Build join plan Panic

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1031]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.5.1

2. What operating system and processor architecture are you using (`go env`)?
Linux

3. What did you do?
Run SQL:
CREATE TABLE b (id INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY (id))ENGINE=MyISAM;

CREATE TABLE a (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	bid INTEGER, 
	type VARCHAR(30), 
	PRIMARY KEY (id), 
	FOREIGN KEY(bid) REFERENCES b (id)
)ENGINE=MyISAM;

CREATE TABLE asub (
	id INTEGER NOT NULL, 
	data VARCHAR(30), 
	PRIMARY KEY (id), 
	FOREIGN KEY(id) REFERENCES a (id)
)ENGINE=MyISAM;

INSERT INTO asub (id, data) VALUES 
(1, 'a1'),
(2, 'a2'),
(3, 'a3');

INSERT INTO b () VALUES ();
INSERT INTO a (bid, type) VALUES (1, 'asub');

SELECT anon_1.a_id AS anon_1_a_id, anon_1.a_bid AS anon_1_a_bid, anon_1.a_type AS anon_1_a_type, anon_1.asub_id AS anon_1_asub_id, anon_1.asub_data AS anon_1_asub_data, anon_2.b_id AS anon_2_b_id FROM (SELECT b.id AS b_id FROM b) AS anon_2 INNER JOIN (SELECT a.id AS a_id, a.bid AS a_bid, a.type AS a_type, asub.id AS asub_id, asub.data AS asub_data FROM a LEFT OUTER JOIN asub ON a.id = asub.id) AS anon_1 ON anon_2.b_id = anon_1.a_bid ORDER BY anon_2.b_id;

4. What did you expect to see?
Run SQL successfully.

5. What did you see instead?
2016/03/31 14:13:54 tidb.go:129: [0;36m[debug] compiling SELECT anon_1.a_id AS anon_1_a_id, anon_1.a_bid AS anon_1_a_bid, anon_1.a_type AS anon_1_a_type, anon_1.asub_id AS anon_1_asub_id, anon_1.asub_data AS anon_1_asub_data, anon_2.b_id AS anon_2_b_id 
FROM (SELECT b.id AS b_id 
FROM b) AS anon_2 INNER JOIN (SELECT a.id AS a_id, a.bid AS a_bid, a.type AS a_type, asub.id AS asub_id, asub.data AS asub_data 
FROM a LEFT OUTER JOIN asub ON a.id = asub.id) AS anon_1 ON anon_2.b_id = anon_1.a_bid ORDER BY anon_2.b_id [0m
2016/03/31 14:13:54 conn.go:222: [0;31m[error] lastCmd SELECT anon_1.a_id AS anon_1_a_id, anon_1.a_bid AS anon_1_a_bid, anon_1.a_type AS anon_1_a_type, anon_1.asub_id AS anon_1_asub_id, anon_1.asub_data AS anon_1_asub_data, anon_2.b_id AS anon_2_b_id 
FROM (SELECT b.id AS b_id 
FROM b) AS anon_2 INNER JOIN (SELECT a.id AS a_id, a.bid AS a_bid, a.type AS a_type, asub.id AS asub_id, asub.data AS asub_data 
FROM a LEFT OUTER JOIN asub ON a.id = asub.id) AS anon_1 ON anon_2.b_id = anon_1.a_bid ORDER BY anon_2.b_id, runtime error: invalid memory address or nil pointer dereference, goroutine 1071 [running]:
github.com/pingcap/tidb/tidb-server/server.(*clientConn).Run.func1(0xc8200ee790)
	/home/shenli/go/src/github.com/pingcap/tidb/tidb-server/server/conn.go:221 +0xb5
github.com/pingcap/tidb/optimizer/plan.(*joinPath).attachEqualCond(0x0, 0xc820dbde00, 0xc82077d8d0, 0x1, 0x1, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder_join.go:241 +0x47
github.com/pingcap/tidb/optimizer/plan.(*joinPath).attachEqualCond(0xc8206fc620, 0xc820dbde00, 0xc82077d8d0, 0x1, 0x1, 0x1)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder_join.go:276 +0x441
github.com/pingcap/tidb/optimizer/plan.(*joinPath).reattach(0xc8206fc7e0, 0xc820bb0300, 0xc82077d8d0, 0x1, 0x1)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder_join.go:488 +0x3f4
github.com/pingcap/tidb/optimizer/plan.(*joinPath).optimizeJoinOrder(0xc8206fc7e0, 0xc82077d8d0, 0x1, 0x1)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder_join.go:459 +0x51d
github.com/pingcap/tidb/optimizer/plan.(*planBuilder).buildJoin(0xc820c75c40, 0xc820294280, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder_join.go:610 +0x498
github.com/pingcap/tidb/optimizer/plan.(*planBuilder).buildFrom(0xc820c75c40, 0xc820294280, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder.go:274 +0x70
github.com/pingcap/tidb/optimizer/plan.(*planBuilder).buildSelect(0xc820c75c40, 0xc820294280, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder.go:216 +0x150
github.com/pingcap/tidb/optimizer/plan.(*planBuilder).build(0xc820c75c40, 0x7f7ffc2748e8, 0xc820294280, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder.go:87 +0x824
github.com/pingcap/tidb/optimizer/plan.BuildPlan(0x7f7ffc2748e8, 0xc820294280, 0x7f7ffc2744b0, 0xc820853500, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder.go:43 +0xd4
github.com/pingcap/tidb/optimizer.Optimize(0x7f7ffcab94a8, 0xc821456080, 0x7f7ffc2748e8, 0xc820294280, 0x7f7ffc2744b0, 0xc820853500, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/optimizer.go:36 +0x184
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc8203a38e0, 0x7f7ffcab94a8, 0xc821456080, 0x7f7ffc2748a8, 0xc820294280, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/executor/compiler.go:46 +0x370
github.com/pingcap/tidb.Compile(0x7f7ffcab94a8, 0xc821456080, 0x7f7ffc2748a8, 0xc820294280, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/tidb.go:142 +0x79
github.com/pingcap/tidb.(*session).Execute(0xc821456080, 0xc820dce001, 0x1cc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/session.go:372 +0x22d
github.com/pingcap/tidb/tidb-server/server.(*TiDBContext).Execute(0xc8202823f0, 0xc820dce001, 0x1cc, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/tidb-server/server/driver_tidb.go:157 +0x83
github.com/pingcap/tidb/tidb-server/server.(*clientConn).handleQuery(0xc8200ee790, 0xc820dce001, 0x1cc, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/tidb-server/server/conn.go:366 +0x6d
github.com/pingcap/tidb/tidb-server/server.(*clientConn).dispatch(0xc8200ee790, 0xc820dce001, 0x1cc, 0x1cc, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/tidb-server/server/conn.go:265 +0x748
github.com/pingcap/tidb/tidb-server/server.(*clientConn).Run(0xc8200ee790)
	/home/shenli/go/src/github.com/pingcap/tidb/tidb-server/server/conn.go:237 +0x238
github.com/pingcap/tidb/tidb-server/server.(*Server).onConn(0xc82010a680, 0x7f7ffd3392b0, 0xc820ce17c0)
	/home/shenli/go/src/github.com/pingcap/tidb/tidb-server/server/server.go:163 +0x39a
created by github.com/pingcap/tidb/tidb-server/server.(*Server).Run
	/home/shenli/go/src/github.com/pingcap/tidb/tidb-server/server/server.go:129 +0x203

**Comment by shenli** [comment]
One more failed case:
CREATE TABLE table1 (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	data VARCHAR(30), 
	PRIMARY KEY (id)
)ENGINE=MyISAM;

CREATE TABLE table2 (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	data VARCHAR(30), 
	t1id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(t1id) REFERENCES table1 (id)
)ENGINE=MyISAM;

SELECT table1.id AS table1_id, table1.data AS table1_data FROM table1 INNER JOIN (SELECT table2.id AS id, table2.data AS ata, table2.t1id AS t1id FROM table2) AS anon_1 ON table1.id = anon_1.t1id;


panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7d10e7]

goroutine 1 [running]:
github.com/pingcap/tidb/optimizer/plan.(*joinPath).attachEqualCond(0x0, 0xc820730340, 0xc820030100, 0x1, 0x1, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder_join.go:241 +0x47
github.com/pingcap/tidb/optimizer/plan.(*joinPath).attachEqualCond(0xc8202868c0, 0xc820730340, 0xc820030100, 0x1, 0x1, 0x1)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder_join.go:276 +0x441
github.com/pingcap/tidb/optimizer/plan.(*joinPath).reattach(0xc8202869a0, 0xc8203e8960, 0xc820030100, 0x1, 0x1)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder_join.go:488 +0x3f4
github.com/pingcap/tidb/optimizer/plan.(*joinPath).optimizeJoinOrder(0xc8202869a0, 0xc820030100, 0x1, 0x1)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder_join.go:459 +0x51d
github.com/pingcap/tidb/optimizer/plan.(*planBuilder).buildJoin(0xc820472180, 0xc82025ed00, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder_join.go:610 +0x498
github.com/pingcap/tidb/optimizer/plan.(*planBuilder).buildFrom(0xc820472180, 0xc82025ed00, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder.go:274 +0x70
github.com/pingcap/tidb/optimizer/plan.(*planBuilder).buildSelect(0xc820472180, 0xc82025ed00, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder.go:216 +0x150
github.com/pingcap/tidb/optimizer/plan.(*planBuilder).build(0xc820472180, 0x7f4fac1f9158, 0xc82025ed00, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder.go:87 +0x824
github.com/pingcap/tidb/optimizer/plan.BuildPlan(0x7f4fac1f9158, 0xc82025ed00, 0x7f4fac1f8d20, 0xc82058d850, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/plan/planbuilder.go:43 +0xd4
github.com/pingcap/tidb/optimizer.Optimize(0x7f4fac1f88b8, 0xc82025e080, 0x7f4fac1f9158, 0xc82025ed00, 0x7f4fac1f8d20, 0xc82058d850, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/optimizer/optimizer.go:36 +0x184
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc820627520, 0x7f4fac1f88b8, 0xc82025e080, 0x7f4fac1f9118, 0xc82025ed00, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/executor/compiler.go:46 +0x370
github.com/pingcap/tidb.Compile(0x7f4fac1f88b8, 0xc82025e080, 0x7f4fac1f9118, 0xc82025ed00, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/tidb.go:142 +0x79
github.com/pingcap/tidb.(*session).Execute(0xc82025e080, 0xc820066c30, 0xc5, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/session.go:372 +0x22d
github.com/pingcap/tidb.(*driverConn).driverQuery(0xc820507d70, 0xc820066c30, 0xc5, 0x18c8c58, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/driver.go:370 +0xa0
github.com/pingcap/tidb.(*driverConn).Query(0xc820507d70, 0xc820066c30, 0xc5, 0x18c8c58, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/driver.go:365 +0x7e
database/sql.(*DB).queryConn(0xc8201d32c0, 0xc82053b5c0, 0x12c9768, 0xc820066c30, 0xc5, 0x0, 0x0, 0x0, 0xff94e0, 0x0, ...)
	/usr/local/go/src/database/sql/sql.go:977 +0x1fd
database/sql.(*Tx).Query(0xc8206ce500, 0xc820066c30, 0xc5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:1295 +0x104
main.executeLine(0xc8206ce500, 0xc820066c30, 0xc5, 0x0, 0x0)
	/home/shenli/go/src/github.com/pingcap/tidb/interpreter/main.go:62 +0xd4
main.main()
	/home/shenli/go/src/github.com/pingcap/tidb/interpreter/main.go:234 +0x5ed
