### ISSUE TITLE
TiDB panicked with "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tidb#10740]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
CI running TiSpark integration test with TiDB fails.

2. What did you expect to see?

3. What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b4ba26]



goroutine 1329 [running]:

github.com/pingcap/tidb/server.(*Server).ShowProcessList(0xc00bc53500, 0xc01ce4def0)

	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/server.go:494 +0x126

github.com/pingcap/tidb/util/expensivequery.(*Handle).Run(0xc00a3391a0, 0x220d300, 0xc00bc53500)

	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/util/expensivequery/expensivequery.go:53 +0x12c

created by main.createServer

	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/tidb-server/main.go:519 +0x13a
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

1d252261a84e8405eb86bdaa2b147dfa7c3c5b4d

**Comment by SunRunAway** [comment]
It's fixed in #10799
