### ISSUE TITLE
TiDB panicked when loading data

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#10852]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I'm loading TPC-H's dataset using `LOAD DATA LOCAL INFILE`.

2. What did you expect to see?

All data is loaded successfully.

3. What did you see instead?

Some connection panicked.
The following is the error stack:
```
[2019/06/18 20:40:32.421 +08:00] [ERROR] [conn.go:460] ["connection running loop panic"] [conn=2805] [lastCmd="load data local infile './data/tpch50/lineitem.tbl.75' into table lineitem fields terminated by '|' lines terminated by '|\
'"] [err="\"invalid memory address or nil pointer dereference\""] [stack="goroutine 5524412 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x1e47f80, 0xc020530750, 0xc01e2aa480, 0xc013cbda1f)
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:458 +0x114
panic(0x1a269a0, 0x2bd7640)
\t/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/pingcap/tidb/session.(*TxnState).SetOption(0xc02552a1d0, 0xa, 0x19a5b80, 0x2c38c41)
\t<autogenerated>:1 +0x2e
github.com/pingcap/tidb/server.(*clientConn).handleLoadData(0xc01e2aa480, 0x1e47ec0, 0xc01f0da380, 0xc00befe150, 0x1df7db0, 0x0)
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:872 +0x5af
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc01e2aa480, 0x1e47ec0, 0xc01f0da380, 0xc014ad0881, 0x7d, 0x0, 0x0)
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:936 +0x6dd
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc01e2aa480, 0x1e47f80, 0xc020530750, 0xc014ad0881, 0x7e, 0x7e, 0x0, 0x0)
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:658 +0x4f4
github.com/pingcap/tidb/server.(*clientConn).Run(0xc01e2aa480, 0x1e47f80, 0xc020530750)
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:506 +0x1f6
github.com/pingcap/tidb/server.(*Server).onConn(0xc000c69ec0, 0xc01e2aa480)
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/server.go:384 +0x450
created by github.com/pingcap/tidb/server.(*Server).Run
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/server.go:311 +0x83d
"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:460
runtime.gopanic
\t/usr/local/go/src/runtime/panic.go:522
runtime.panicmem
\t/usr/local/go/src/runtime/panic.go:82
runtime.sigpanic
\t/usr/local/go/src/runtime/signal_unix.go:390
github.com/pingcap/tidb/session.(*TxnState).SetOption
\t<autogenerated>:1
github.com/pingcap/tidb/server.(*clientConn).handleLoadData
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:872
github.com/pingcap/tidb/server.(*clientConn).handleQuery
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:936
github.com/pingcap/tidb/server.(*clientConn).dispatch
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:658
github.com/pingcap/tidb/server.(*clientConn).Run
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:506
github.com/pingcap/tidb/server.(*Server).onConn
\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/server.go:384"]
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

release 2.11

**Comment by winoros** [comment]
@winkyao @jackysp PTAL

**Comment by jackysp** [comment]
I think https://github.com/pingcap/tidb/pull/9444 may fix it.

**Comment by nullnotnil** [comment]
I am going to close this issue, as it appears to have been fixed. Please feel free to re-open it if you have any additional questions. Thanks!
