### ISSUE TITLE
Update operator makes indexWorker in IndexLookupExecutor panicked

### ISSUE THREAD

**Issue by aeoluswing** [pingcap/tidb#10939]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Make some update opearator SQL.

2. What did you expect to see?

IndexLookupExecutor works well.

3. What did you see instead?

Update SQL makes lots of panic below:
```
[2019/06/25 10:24:39.296 +08:00] [ERROR] [distsql.go:617] ["indexWorker in IndexLookupExecutor panicked"] [conn=1287] [stack="goroutine 1942808 [running]:
github.com/pingcap/tidb/executor.(*indexWorker).fetchHandles.func1(0x1e47ec0, 0xc001692280, 0xc05a90b9c0, 0xc03ed8dea0)
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/distsql.go:615 +0xb8
panic(0x1a269a0, 0x2bd7690)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/pingcap/tidb/tablecodec.CutIndexPrefix(...)
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/tablecodec/tablecodec.go:503
github.com/pingcap/tidb/statistics.(*QueryFeedback).Update(0xc0348667d0, 0x0, 0x0, 0x0, 0xc0552ab728, 0x1, 0x1)
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/statistics/feedback.go:212 +0x2f0
github.com/pingcap/tidb/distsql.(*streamResult).readDataFromResponse(0xc041874f60, 0x1e47ec0, 0xc001692280, 0x1e2be40, 0xc037b892d0, 0xc038a3a550, 0xc000b8b7a0, 0x0, 0x0)
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/distsql/stream.go:90 +0x2eb
github.com/pingcap/tidb/distsql.(*streamResult).readDataIfNecessary(0xc041874f60, 0x1e47ec0, 0xc001692280, 0x0, 0x0)
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/distsql/stream.go:102 +0x8c
github.com/pingcap/tidb/distsql.(*streamResult).Next(0xc041874f60, 0x1e47ec0, 0xc001692280, 0xc052064390, 0x100, 0x4000)
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/distsql/stream.go:48 +0x97
github.com/pingcap/tidb/executor.(*indexWorker).extractTaskHandles(0xc05a90b9c0, 0x1e47ec0, 0xc001692280, 0xc052064390, 0x1e48f00, 0xc041874f60, 0xc000950d48, 0xab0c75, 0xc05e353f38, 0xc000950e20, ...)
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/distsql.go:659 +0x19f
github.com/pingcap/tidb/executor.(*indexWorker).fetchHandles(0xc05a90b9c0, 0x1e47ec0, 0xc001692280, 0x1e48f00, 0xc041874f60, 0x0, 0x0)
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/distsql.go:631 +0x1ff
github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startIndexWorker.func1(0x1e47ec0, 0xc04553a800, 0xc05a90b9c0, 0x1e48f00, 0xc041874f60, 0xc000313a40, 0xc041874d20)
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/distsql.go:462 +0x9a
created by github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startIndexWorker
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/distsql.go:460 +0x3fd
"] [stack="github.com/pingcap/tidb/executor.(*indexWorker).fetchHandles.func1
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/distsql.go:617
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:522
runtime.panicslice
	/usr/local/go/src/runtime/panic.go:54
github.com/pingcap/tidb/tablecodec.CutIndexPrefix
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/tablecodec/tablecodec.go:503
github.com/pingcap/tidb/statistics.(*QueryFeedback).Update
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/statistics/feedback.go:212
github.com/pingcap/tidb/distsql.(*streamResult).readDataFromResponse
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/distsql/stream.go:90
github.com/pingcap/tidb/distsql.(*streamResult).readDataIfNecessary
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/distsql/stream.go:102
github.com/pingcap/tidb/distsql.(*streamResult).Next
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/distsql/stream.go:48
github.com/pingcap/tidb/executor.(*indexWorker).extractTaskHandles
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/distsql.go:659
github.com/pingcap/tidb/executor.(*indexWorker).fetchHandles
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/distsql.go:631
github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startIndexWorker.func1
	/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/distsql.go:462"]
```

I'm not sure what does this panic mean.Is there any suggestion?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
version: 2.1.11

**Comment by shenli** [comment]
@aeoluswing Thanks for your feedback! We will investigate it.

**Comment by zz-jason** [comment]
@aeoluswing Do you enabled streaming by setting config `enable-streaming` to `true`?

**Comment by lamxTyler** [comment]
@aeoluswing Could you provide the failed SQL and related schemas?

**Comment by lamxTyler** [comment]
@aeoluswing Do you meet panics if the streaming is disabled?

**Comment by qw4990** [comment]
Close due to no update for a long time.
