### ISSUE TITLE
Spurious "nil pointer dereference" from (*delRange).start

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb#11763]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

In [an "integration test" of the parser repository](https://circleci.com/gh/pingcap/parser/3104), a certain test in the `github.com/pingcap/tidb/server` package crashed with the following stack trace:

<details>

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x143598c]

goroutine 6506 [running]:
github.com/pingcap/goleveldb/leveldb.(*DB).newRawIterator(0xc00501ad80, 0x0, 0x0, 0x0, 0x0, 0xc013874030, 0x0, 0x1, 0xc0138649f0)
	/go/pkg/mod/github.com/pingcap/goleveldb@v0.0.0-20171020122428-b9ff6c35079e/leveldb/db_iter.go:54 +0x29c
github.com/pingcap/goleveldb/leveldb.(*DB).newIterator(0xc00501ad80, 0x0, 0x0, 0x0, 0x0, 0x3621, 0xc00a7f3c00, 0x0, 0x40)
	/go/pkg/mod/github.com/pingcap/goleveldb@v0.0.0-20171020122428-b9ff6c35079e/leveldb/db_iter.go:79 +0x99
github.com/pingcap/goleveldb/leveldb.(*DB).NewIterator(0xc00501ad80, 0xc00a7f3c00, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/pingcap/goleveldb@v0.0.0-20171020122428-b9ff6c35079e/leveldb/db.go:884 +0x146
github.com/pingcap/tidb/store/mockstore/mocktikv.newIterator(0xc00501ad80, 0xc00a7f3c00, 0xfdb)
	/go/src/github.com/pingcap/tidb/store/mockstore/mocktikv/mvcc_leveldb.go:146 +0x42
github.com/pingcap/tidb/store/mockstore/mocktikv.commitKey(0xc00501ad80, 0xc013872140, 0xc013867025, 0x13, 0xfdb, 0x5b2766832600002, 0x5b2766832600003, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/store/mockstore/mocktikv/mvcc_leveldb.go:756 +0xe9
github.com/pingcap/tidb/store/mockstore/mocktikv.(*MVCCLevelDB).Commit(0xc001165650, 0xc013853ec0, 0x2, 0x2, 0x5b2766832600002, 0x5b2766832600003, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/store/mockstore/mocktikv/mvcc_leveldb.go:746 +0x110
github.com/pingcap/tidb/store/mockstore/mocktikv.(*rpcHandler).handleKvCommit(0xc013862a20, 0xc0138499a0, 0x5a)
	/go/src/github.com/pingcap/tidb/store/mockstore/mocktikv/rpc.go:347 +0x100
github.com/pingcap/tidb/store/mockstore/mocktikv.(*RPCClient).SendRequest(0xc001165680, 0x2316e00, 0xc013853bc0, 0xc0069e6378, 0x6, 0xc013861c70, 0x4a817c800, 0x1e0a260, 0xc013859001, 0xc0091c3240)
	/go/src/github.com/pingcap/tidb/store/mockstore/mocktikv/rpc.go:744 +0x9f4
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).sendReqToRegion(0xc00a7f4678, 0xc013856ba0, 0xc0138499f0, 0xc013861c70, 0x4a817c800, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/store/tikv/region_request.go:150 +0xb4
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReqCtx(0xc00a7f4678, 0xc013856ba0, 0xc013861c70, 0x3, 0x0, 0x0, 0x4a817c800, 0x70, 0x1f88f00, 0xf40201, ...)
	/go/src/github.com/pingcap/tidb/store/tikv/region_request.go:121 +0x33f
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReq(0xc00a7f4678, 0xc013856ba0, 0xc013861c70, 0x3, 0x0, 0x0, 0x4a817c800, 0xc1d8c3, 0x1ea4ca0, 0x20164a0)
	/go/src/github.com/pingcap/tidb/store/tikv/region_request.go:72 +0x77
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).commitSingleBatch(0xc0138687e0, 0xc013856ba0, 0x3, 0x0, 0x0, 0xc013853ec0, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:706 +0x26a
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).commitSingleBatch-fm(0xc013856ba0, 0x3, 0x0, 0x0, 0xc013853ec0, 0x2, 0x2, 0x186cd24, 0xc013867000)
	/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:379 +0x55
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).doActionOnBatches(0xc0138687e0, 0xc013856ba0, 0x2, 0xc013853ef0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:388 +0xd80
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).doActionOnKeys(0xc0138687e0, 0xc013856ba0, 0x2, 0xc013853c50, 0x2, 0x2, 0x7f3de1cd46c0, 0x0)
	/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:341 +0x5ba
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).commitKeys(0xc0138687e0, 0xc013856ba0, 0xc013853c50, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:818 +0xb4
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).execute(0xc0138687e0, 0x2316e00, 0xc013853bc0, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:929 +0x12d0
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).executeAndWriteFinishBinlog(0xc0138687e0, 0x2316e00, 0xc013853bc0, 0xc013853bc0, 0xc0138687e0)
	/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:834 +0x43
github.com/pingcap/tidb/store/tikv.(*tikvTxn).Commit(0xc01382adc0, 0x2316e00, 0xc013853bc0, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/store/tikv/txn.go:325 +0x33c
github.com/pingcap/tidb/session.(*TxnState).Commit(0xc006ba1210, 0x2316e00, 0xc013853bc0, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/session/txn.go:197 +0x77e
github.com/pingcap/tidb/session.(*session).doCommit(0xc006ba1200, 0x2316e00, 0xc013853b60, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/session/session.go:440 +0x447
github.com/pingcap/tidb/session.(*session).doCommitWithRetry(0xc006ba1200, 0x2316e00, 0xc013853b60, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/session/session.go:455 +0xfe
github.com/pingcap/tidb/session.(*session).CommitTxn(0xc006ba1200, 0x2316d80, 0xc0000400e8, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/session/session.go:515 +0x114
github.com/pingcap/tidb/session.finishStmt(0x2316d80, 0xc0000400e8, 0x2349240, 0xc006ba1200, 0xc006ba1200, 0xc0069d0000, 0x0, 0x0, 0x1, 0x0)
	/go/src/github.com/pingcap/tidb/session/tidb.go:176 +0x371
github.com/pingcap/tidb/session.runStmt(0x2316d80, 0xc0000400e8, 0x2349240, 0xc006ba1200, 0x231c280, 0xc013870380, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/session/tidb.go:247 +0x27d
github.com/pingcap/tidb/session.(*session).executeStatement(0xc006ba1200, 0x2316d80, 0xc0000400e8, 0x0, 0x231b5c0, 0xc013860f50, 0x231c280, 0xc013870380, 0x0, 0x0, ...)
	/go/src/github.com/pingcap/tidb/session/session.go:1003 +0x1eb
github.com/pingcap/tidb/session.(*session).execute(0xc006ba1200, 0x2316d80, 0xc0000400e8, 0xc00949fe00, 0x49, 0x46, 0xc012abe680, 0xc00a7f7538, 0xc00a7f7538, 0xc1c15b)
	/go/src/github.com/pingcap/tidb/session/session.go:1114 +0x91a
github.com/pingcap/tidb/session.(*session).Execute(0xc006ba1200, 0x2316d80, 0xc0000400e8, 0xc00949fe00, 0x49, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/session/session.go:1042 +0xc4
github.com/pingcap/tidb/ddl/util.RemoveFromGCDeleteRange(0x2349240, 0xc006ba1200, 0xa4, 0xa0, 0x79, 0x0)
	/go/src/github.com/pingcap/tidb/ddl/util/util.go:118 +0x151
github.com/pingcap/tidb/ddl/util.CompleteDeleteRange(0x2349240, 0xc006ba1200, 0xa4, 0xa0, 0xc009167620, 0x9, 0x20, 0xc009167640, 0x9, 0x20, ...)
	/go/src/github.com/pingcap/tidb/ddl/util/util.go:112 +0x1d0
github.com/pingcap/tidb/ddl.(*delRange).doTask(0xc006ea8f00, 0x2349240, 0xc006ba1200, 0xa4, 0xa0, 0xc009167620, 0x9, 0x20, 0xc009167640, 0x9, ...)
	/go/src/github.com/pingcap/tidb/ddl/delete_range.go:223 +0x532
github.com/pingcap/tidb/ddl.(*delRange).doDelRangeWork(0xc006ea8f00, 0x0, 0x0)
	/go/src/github.com/pingcap/tidb/ddl/delete_range.go:177 +0x734
github.com/pingcap/tidb/ddl.(*delRange).startEmulator(0xc006ea8f00)
	/go/src/github.com/pingcap/tidb/ddl/delete_range.go:141 +0x133
created by github.com/pingcap/tidb/ddl.(*delRange).start
	/go/src/github.com/pingcap/tidb/ddl/delete_range.go:117 +0x6f
```

</details>

2. What did you expect to see?

Not crash.

3. What did you see instead?

Crash.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master at 2019-08-17T11:25:40+0800, likely just 2009741d57c5591c10f837166264c78cac1261f5.

**Comment by qw4990** [comment]
Close since it is no update for a long time. We can open it if this issue occurs again.
