### ISSUE TITLE
select for update cause tidb panic

### ISSUE THREAD

**Issue by XSHui** [pingcap/tidb#12255]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select id from t1 where id=1 for update
```

2. What did you expect to see?
sql exec correct

3. What did you see instead?
```
Lost Connection to mysql server during query
```

tidb log:

```
{"log":"[2019/09/18 15:57:26.103 +08:00] [INFO] [region_cache.go:528] [\"invalidate region cache due to cannot find peer when updating leader\"] [regionID=51417] [currIdx=2] [leaderStoreID=6]\n","stream":"stdout","time":"2019-09-18T07:57:26.103418697Z"}
{"log":"[2019/09/18 15:57:26.135 +08:00] [INFO] [region_cache.go:534] [\"switch region leader to specific leader due to kv return NotLeader\"] [regionID=41387] [currIdx=1] [leaderStoreID=4]\n","stream":"stdout","time":"2019-09-18T07:57:26.135610277Z"}
{"log":"[2019/09/18 15:57:26.136 +08:00] [INFO] [region_cache.go:534] [\"switch region leader to specific leader due to kv return NotLeader\"] [regionID=41387] [currIdx=1] [leaderStoreID=4]\n","stream":"stdout","time":"2019-09-18T07:57:26.136158425Z"}
{"log":"[2019/09/18 15:57:26.174 +08:00] [INFO] [region_cache.go:534] [\"switch region leader to specific leader due to kv return NotLeader\"] [regionID=52250] [currIdx=0] [leaderStoreID=6]\n","stream":"stdout","time":"2019-09-18T07:57:26.174415436Z"}
{"log":"[2019/09/18 15:57:26.182 +08:00] [INFO] [region_cache.go:534] [\"switch region leader to specific leader due to kv return NotLeader\"] [regionID=52258] [currIdx=0] [leaderStoreID=6]\n","stream":"stdout","time":"2019-09-18T07:57:26.182907909Z"}
{"log":"[2019/09/18 15:57:26.200 +08:00] [INFO] [range_task.go:199] [\"range task finished\"] [name=resolve-locks-runner] [startKey=] [endKey=] [\"cost time\"=3.02195471s] [\"completed regions\"=3793]\n","stream":"stdout","time":"2019-09-18T07:57:26.200953915Z"}
{"log":"[2019/09/18 15:57:26.200 +08:00] [INFO] [gc_worker.go:794] [\"[gc worker] finish resolve locks\"] [uuid=5b373f2baa00017] [safePoint=411249631061082112] [regions=3793]\n","stream":"stdout","time":"2019-09-18T07:57:26.200980167Z"}
{"log":"[2019/09/18 15:57:34.942 +08:00] [INFO] [server.go:413] [\"new connection\"] [conn=86845] [remoteAddr=**.**.**.**:39917]\n","stream":"stdout","time":"2019-09-18T07:57:34.942566598Z"}
{"log":"[2019/09/18 15:57:34.943 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86845]\n","stream":"stdout","time":"2019-09-18T07:57:34.943475245Z"}
{"log":"[2019/09/18 15:58:00.524 +08:00] [INFO] [server.go:413] [\"new connection\"] [conn=86846] [remoteAddr=**.**.**.**:57969]\n","stream":"stdout","time":"2019-09-18T07:58:00.524742034Z"}
{"log":"[2019/09/18 15:58:00.525 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86846]\n","stream":"stdout","time":"2019-09-18T07:58:00.525861669Z"}
{"log":"[2019/09/18 15:58:06.700 +08:00] [INFO] [server.go:413] [\"new connection\"] [conn=86847] [remoteAddr=**.**.**.**:33253]\n","stream":"stdout","time":"2019-09-18T07:58:06.700918298Z"}
{"log":"[2019/09/18 15:58:06.702 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86847]\n","stream":"stdout","time":"2019-09-18T07:58:06.702306413Z"}
{"log":"[2019/09/18 15:58:22.354 +08:00] [INFO] [server.go:413] [\"new connection\"] [conn=86848] [remoteAddr=**.**.**.**:58131]\n","stream":"stdout","time":"2019-09-18T07:58:22.35436248Z"}
{"log":"[2019/09/18 15:58:22.380 +08:00] [ERROR] [conn.go:600] [\"connection running loop panic\"] [conn=86848] [lastCmd=\"EXPLAIN analyze select id from t1 where id=1 for update\"] [err=\"\\\"invalid memory address or nil pointer dereference\\\"\"] [stack=\"goroutine 57316983 [running]:\\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x22a1e00, 0xc16cee43f0, 0xc0f72c4a90)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:598 +0xee\\npanic(0x1dd2d80, 0x2fec9b0)\\n\\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset.func1(0x0, 0x22b3d80, 0xc12eb14e10, 0xc00a033738, 0x22a1e00, 0xc16cee43f0, 0xc0f72c4a90)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1261 +0x5a9\\npanic(0x1dd2d80, 0x2fec9b0)\\n\\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\\ngithub.com/pingcap/tidb/session.(*TxnState).LockKeys(0xc12f05a100, 0x22a1e00, 0xc16cee43f0, 0x5b50d848a30000c, 0xc063eefdc0, 0x1, 0x1, 0x0, 0x0)\\n\\t\u003cautogenerated\u003e:1 +0x36\\ngithub.com/pingcap/tidb/executor.(*PointGetExecutor).lockKeyIfNeeded(0xc1030ef680, 0x22a1e00, 0xc16cee43f0, 0xc078e3c060, 0x13, 0x13, 0x8, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/executor/point_get.go:152 +0x144\\ngithub.com/pingcap/tidb/executor.(*PointGetExecutor).Next(0xc1030ef680, 0x22a1e00, 0xc16cee43f0, 0xc003551d70, 0x1f00d40, 0xc00004f401)\\n\\t/go/src/github.com/pingcap/tidb/executor/point_get.go:132 +0x1d7\\ngithub.com/pingcap/tidb/executor.(*ExplainExec).generateExplainInfo(0xc12790f290, 0x22a1e00, 0xc16cee43f0, 0xc00b3b8a80, 0x7f40364476d0, 0x0, 0xc131241b30, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/executor/explain.go:77 +0x154\\ngithub.com/pingcap/tidb/executor.(*ExplainExec).Next(0xc12790f290, 0x22a1e00, 0xc16cee43f0, 0xc003551d10, 0x0, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/executor/explain.go:52 +0x42e\\ngithub.com/pingcap/tidb/executor.Next(0x22a1e00, 0xc16cee43f0, 0x22a8380, 0xc12790f290, 0xc003551d10, 0xc003551d10, 0xc0e463e3cc)\\n\\t/go/src/github.com/pingcap/tidb/executor/executor.go:191 +0xbd\\ngithub.com/pingcap/tidb/executor.(*recordSet).Next(0xc12eb14dc0, 0x22a1e00, 0xc16cee43f0, 0xc003551d10, 0x0, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/executor/adapter.go:109 +0xc4\\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc12eb14e10, 0x22a1e00, 0xc16cee43f0, 0xc003551d10, 0x4, 0x400)\\n\\t/go/src/github.com/pingcap/tidb/server/driver_tidb.go:365 +0x51\\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc0f72c4a90, 0x22a1e00, 0xc16cee43f0, 0x22b3d80, 0xc12eb14e10, 0xc000003700, 0x22a1e00, 0xc16cee43f0)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1308 +0x319\\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc0f72c4a90, 0x22a1e00, 0xc16cee43f0, 0x22b3d80, 0xc12eb14e10, 0xc000007f00, 0x0, 0x0, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1274 +0x1a1\\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc0f72c4a90, 0x22a1e00, 0xc16cee43f0, 0xc0f0d1e081, 0x37, 0x0, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1191 +0x212\\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc0f72c4a90, 0x22a1e00, 0xc16cee43f0, 0xc0f0d1e081, 0x38, 0x38, 0x0, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:897 +0x5c6\\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc0f72c4a90, 0x22a1e00, 0xc16cee43f0)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:652 +0x258\\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc00b7ede00, 0xc0f72c4a90)\\n\\t/go/src/github.com/pingcap/tidb/server/server.go:440 +0x481\\ncreated by github.com/pingcap/tidb/server.(*Server).Run\\n\\t/go/src/github.com/pingcap/tidb/server/server.go:357 +0x83d\\n\"] [stack=\"github.com/pingcap/tidb/server.(*clientConn).Run.func1\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:600\\nruntime.gopanic\\n\\t/usr/local/go/src/runtime/panic.go:522\\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset.func1\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1261\\nruntime.gopanic\\n\\t/usr/local/go/src/runtime/panic.go:522\\nruntime.panicmem\\n\\t/usr/local/go/src/runtime/panic.go:82\\nruntime.sigpanic\\n\\t/usr/local/go/src/runtime/signal_unix.go:390\\ngithub.com/pingcap/tidb/session.(*TxnState).LockKeys\\n\\t\u003cautogenerated\u003e:1\\ngithub.com/pingcap/tidb/executor.(*PointGetExecutor).lockKeyIfNeeded\\n\\t/go/src/github.com/pingcap/tidb/executor/point_get.go:152\\ngithub.com/pingcap/tidb/executor.(*PointGetExecutor).Next\\n\\t/go/src/github.com/pingcap/tidb/executor/point_get.go:132\\ngithub.com/pingcap/tidb/executor.(*ExplainExec).generateExplainInfo\\n\\t/go/src/github.com/pingcap/tidb/executor/explain.go:77\\ngithub.com/pingcap/tidb/executor.(*ExplainExec).Next\\n\\t/go/src/github.com/pingcap/tidb/executor/explain.go:52\\ngithub.com/pingcap/tidb/executor.Next\\n\\t/go/src/github.com/pingcap/tidb/executor/executor.go:191\\ngithub.com/pingcap/tidb/executor.(*recordSet).Next\\n\\t/go/src/github.com/pingcap/tidb/executor/adapter.go:109\\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Next\\n\\t/go/src/github.com/pingcap/tidb/server/driver_tidb.go:365\\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1308\\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1274\\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1191\\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:897\\ngithub.com/pingcap/tidb/server.(*clientConn).Run\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:652\\ngithub.com/pingcap/tidb/server.(*Server).onConn\\n\\t/go/src/github.com/pingcap/tidb/server/server.go:440\"]\n","stream":"stdout","time":"2019-09-18T07:58:22.381347942Z"}
{"log":"[2019/09/18 15:58:22.388 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86849]\n","stream":"stdout","time":"2019-09-18T07:58:22.388834684Z"}
{"log":"[2019/09/18 15:58:23.137 +08:00] [INFO] [gc_worker.go:246] [\"[gc worker] there's already a gc job running, skipped\"] [\"leaderTick on\"=5b373f2baa00017]\n","stream":"stdout","time":"2019-09-18T07:58:23.137980052Z"}
{"log":"[2019/09/18 15:58:35.064 +08:00] [INFO] [server.go:413] [\"new connection\"] [conn=86850] [remoteAddr=**.**.**.**:40034]\n","stream":"stdout","time":"2019-09-18T07:58:35.064426011Z"}
{"log":"[2019/09/18 15:58:35.065 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86850]\n","stream":"stdout","time":"2019-09-18T07:58:35.065429194Z"}
{"log":"[2019/09/18 15:58:41.397 +08:00] [INFO] [region_cache.go:534] [\"switch region leader to specific leader due to kv return NotLeader\"] [regionID=35] [currIdx=1] [leaderStoreID=4]\n","stream":"stdout","time":"2019-09-18T07:58:41.397973062Z"}
{"log":"[2019/09/18 15:58:45.679 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86844]\n","stream":"stdout","time":"2019-09-18T07:58:45.679238207Z"}
{"log":"[2019/09/18 15:59:00.617 +08:00] [INFO] [server.go:413] [\"new connection\"] [conn=86851] [remoteAddr=**.**.**.**:58209]\n","stream":"stdout","time":"2019-09-18T07:59:00.618031136Z"}
{"log":"[2019/09/18 15:59:00.619 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86851]\n","stream":"stdout","time":"2019-09-18T07:59:00.61918728Z"}
{"log":"[2019/09/18 15:59:05.815 +08:00] [INFO] [server.go:413] [\"new connection\"] [conn=86852] [remoteAddr=**.**.**.**:33367]\n","stream":"stdout","time":"2019-09-18T07:59:05.815912829Z"}
{"log":"[2019/09/18 15:59:05.817 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86852]\n","stream":"stdout","time":"2019-09-18T07:59:05.817244715Z"}
{"log":"[2019/09/18 15:59:06.212 +08:00] [INFO] [gc_worker.go:582] [\"[gc worker] start delete\"] [uuid=5b373f2baa00017] [ranges=0]\n","stream":"stdout","time":"2019-09-18T07:59:06.213082333Z"}
{"log":"[2019/09/18 15:59:06.213 +08:00] [INFO] [gc_worker.go:601] [\"[gc worker] finish delete ranges\"] [uuid=5b373f2baa00017] [\"num of ranges\"=0] [\"cost time\"=414ns]\n","stream":"stdout","time":"2019-09-18T07:59:06.213097476Z"}
{"log":"[2019/09/18 15:59:06.216 +08:00] [INFO] [gc_worker.go:624] [\"[gc worker] start redo-delete ranges\"] [uuid=5b373f2baa00017] [\"num of ranges\"=0]\n","stream":"stdout","time":"2019-09-18T07:59:06.216445336Z"}
{"log":"[2019/09/18 15:59:06.216 +08:00] [INFO] [gc_worker.go:643] [\"[gc worker] finish redo-delete ranges\"] [uuid=5b373f2baa00017] [\"num of ranges\"=0] [\"cost time\"=408ns]\n","stream":"stdout","time":"2019-09-18T07:59:06.216458078Z"}
{"log":"[2019/09/18 15:59:06.224 +08:00] [INFO] [gc_worker.go:921] [\"[gc worker] sent safe point to PD\"] [uuid=5b373f2baa00017] [\"safe point\"=411249631061082112]\n","stream":"stdout","time":"2019-09-18T07:59:06.224686231Z"}
{"log":"[2019/09/18 15:59:34.272 +08:00] [INFO] [server.go:413] [\"new connection\"] [conn=86853] [remoteAddr=**.**.**.**:40399]\n","stream":"stdout","time":"2019-09-18T07:59:34.273082971Z"}
{"log":"[2019/09/18 15:59:34.274 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86853]\n","stream":"stdout","time":"2019-09-18T07:59:34.274140714Z"}
{"log":"[2019/09/18 16:00:00.475 +08:00] [INFO] [server.go:413] [\"new connection\"] [conn=86854] [remoteAddr=**.**.**.**:58322]\n","stream":"stdout","time":"2019-09-18T08:00:00.475349143Z"}
{"log":"[2019/09/18 16:00:00.476 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86854]\n","stream":"stdout","time":"2019-09-18T08:00:00.47666416Z"}
{"log":"[2019/09/18 16:00:07.180 +08:00] [INFO] [server.go:413] [\"new connection\"] [conn=86855] [remoteAddr=**.**.**.**:35019]\n","stream":"stdout","time":"2019-09-18T08:00:07.18064424Z"}
{"log":"[2019/09/18 16:00:07.181 +08:00] [INFO] [server.go:416] [\"connection closed\"] [conn=86855]\n","stream":"stdout","time":"2019-09-18T08:00:07.181966812Z"}
{"log":"[2019/09/18 16:00:20.070 +08:00] [INFO] [region_cache.go:528] [\"invalidate region cache due to cannot find peer when updating leader\"] [regionID=31] [currIdx=0] [leaderStoreID=4]\n","stream":"stdout","time":"2019-09-18T08:00:20.070270715Z"}
{"log":"[2019/09/18 16:00:27.015 +08:00] [INFO] [client_batch.go:525] [\"recycle idle connection\"] [target=**.**.**.**:10094]\n","stream":"stdout","time":"2019-09-18T08:00:27.01587455Z"}
{"log":"[2019/09/18 16:00:27.015 +08:00] [ERROR] [client_batch.go:278] [\"batchRecvLoop error when receive\"] [target=**.**.**.**:10094] [error=\"rpc error: code = Canceled desc = grpc: the client connection is closing\"] [stack=\"github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\\n\\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:278\"]\n","stream":"stdout","time":"2019-09-18T08:00:27.01603171Z"}
{"log":"[2019/09/18 16:00:27.015 +08:00] [INFO] [client_batch.go:525] [\"recycle idle connection\"] [target=**.**.**.**:10088]\n","stream":"stdout","time":"2019-09-18T08:00:27.016044868Z"}
{"log":"[2019/09/18 16:00:27.015 +08:00] [ERROR] [client_batch.go:278] [\"batchRecvLoop error when receive\"] [target=**.**.**.**:10094] [error=\"rpc error: code = Unavailable desc = transport is closing\"] [stack=\"github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\\n\\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:278\"]\n","stream":"stdout","time":"2019-09-18T08:00:27.016048911Z"}
{"log":"[2019/09/18 16:00:27.015 +08:00] [ERROR] [client_batch.go:278] [\"batchRecvLoop error when receive\"] [target=**.**.**.**:10094] [error=\"rpc error: code = Canceled desc = grpc: the client connection is closing\"] [stack=\"github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\\n\\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:278\"]\n","stream":"stdout","time":"2019-09-18T08:00:27.016058859Z"}
{"log":"[2019/09/18 16:00:27.015 +08:00] [ERROR] [client_batch.go:278] [\"batchRecvLoop error when receive\"] [target=**.**.**.**:10094] [error=\"rpc error: code = Unavailable desc = transport is closing\"] [stack=\"github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\\n\\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:278\"]\n","stream":"stdout","time":"2019-09-18T08:00:27.016068943Z"}
{"log":"[2019/09/18 16:00:27.016 +08:00] [ERROR] [client_batch.go:278] [\"batchRecvLoop error when receive\"] [target=**.**.**.**:10094] [error=\"rpc error: code = Canceled desc = grpc: the client connection is closing\"] [stack=\"github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\\n\\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:278\"]\n","stream":"stdout","time":"2019-09-18T08:00:27.016075057Z"}
{"log":"[2019/09/18 16:00:27.016 +08:00] [ERROR] [client_batch.go:278] [\"batchRecvLoop error when receive\"] [target=**.**.**.**:10094] [error=\"rpc error: code = Canceled desc = grpc: the client connection is closing\"] [stack=\"github.com/pingcap/tidb/store/tikv.(*batchCommandsClient).batchRecvLoop\\n\\t/go/src/github.com/pingcap/tidb/store/tikv/client_batch.go:278\"]\n","stream":"stdout","time":"2019-09-18T08:00:27.016080729Z"}
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

tidb-server-v3.0.2

**Comment by XSHui** [comment]
```
{"log":"[2019/09/18 15:58:22.380 +08:00] [ERROR] [conn.go:600] [\"connection running loop panic\"] [conn=86848] [lastCmd=\"EXPLAIN analyze select id from t1 where id=1 for update\"] [err=\"\\\"invalid memory address or nil pointer dereference\\\"\"] [stack=\"goroutine 57316983 [running]:\\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x22a1e00, 0xc16cee43f0, 0xc0f72c4a90)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:598 +0xee\\npanic(0x1dd2d80, 0x2fec9b0)\\n\\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset.func1(0x0, 0x22b3d80, 0xc12eb14e10, 0xc00a033738, 0x22a1e00, 0xc16cee43f0, 0xc0f72c4a90)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1261 +0x5a9\\npanic(0x1dd2d80, 0x2fec9b0)\\n\\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\\ngithub.com/pingcap/tidb/session.(*TxnState).LockKeys(0xc12f05a100, 0x22a1e00, 0xc16cee43f0, 0x5b50d848a30000c, 0xc063eefdc0, 0x1, 0x1, 0x0, 0x0)\\n\\t\u003cautogenerated\u003e:1 +0x36\\ngithub.com/pingcap/tidb/executor.(*PointGetExecutor).lockKeyIfNeeded(0xc1030ef680, 0x22a1e00, 0xc16cee43f0, 0xc078e3c060, 0x13, 0x13, 0x8, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/executor/point_get.go:152 +0x144\\ngithub.com/pingcap/tidb/executor.(*PointGetExecutor).Next(0xc1030ef680, 0x22a1e00, 0xc16cee43f0, 0xc003551d70, 0x1f00d40, 0xc00004f401)\\n\\t/go/src/github.com/pingcap/tidb/executor/point_get.go:132 +0x1d7\\ngithub.com/pingcap/tidb/executor.(*ExplainExec).generateExplainInfo(0xc12790f290, 0x22a1e00, 0xc16cee43f0, 0xc00b3b8a80, 0x7f40364476d0, 0x0, 0xc131241b30, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/executor/explain.go:77 +0x154\\ngithub.com/pingcap/tidb/executor.(*ExplainExec).Next(0xc12790f290, 0x22a1e00, 0xc16cee43f0, 0xc003551d10, 0x0, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/executor/explain.go:52 +0x42e\\ngithub.com/pingcap/tidb/executor.Next(0x22a1e00, 0xc16cee43f0, 0x22a8380, 0xc12790f290, 0xc003551d10, 0xc003551d10, 0xc0e463e3cc)\\n\\t/go/src/github.com/pingcap/tidb/executor/executor.go:191 +0xbd\\ngithub.com/pingcap/tidb/executor.(*recordSet).Next(0xc12eb14dc0, 0x22a1e00, 0xc16cee43f0, 0xc003551d10, 0x0, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/executor/adapter.go:109 +0xc4\\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc12eb14e10, 0x22a1e00, 0xc16cee43f0, 0xc003551d10, 0x4, 0x400)\\n\\t/go/src/github.com/pingcap/tidb/server/driver_tidb.go:365 +0x51\\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc0f72c4a90, 0x22a1e00, 0xc16cee43f0, 0x22b3d80, 0xc12eb14e10, 0xc000003700, 0x22a1e00, 0xc16cee43f0)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1308 +0x319\\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc0f72c4a90, 0x22a1e00, 0xc16cee43f0, 0x22b3d80, 0xc12eb14e10, 0xc000007f00, 0x0, 0x0, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1274 +0x1a1\\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc0f72c4a90, 0x22a1e00, 0xc16cee43f0, 0xc0f0d1e081, 0x37, 0x0, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1191 +0x212\\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc0f72c4a90, 0x22a1e00, 0xc16cee43f0, 0xc0f0d1e081, 0x38, 0x38, 0x0, 0x0)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:897 +0x5c6\\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc0f72c4a90, 0x22a1e00, 0xc16cee43f0)\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:652 +0x258\\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc00b7ede00, 0xc0f72c4a90)\\n\\t/go/src/github.com/pingcap/tidb/server/server.go:440 +0x481\\ncreated by github.com/pingcap/tidb/server.(*Server).Run\\n\\t/go/src/github.com/pingcap/tidb/server/server.go:357 +0x83d\\n\"] [stack=\"github.com/pingcap/tidb/server.(*clientConn).Run.func1\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:600\\nruntime.gopanic\\n\\t/usr/local/go/src/runtime/panic.go:522\\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset.func1\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1261\\nruntime.gopanic\\n\\t/usr/local/go/src/runtime/panic.go:522\\nruntime.panicmem\\n\\t/usr/local/go/src/runtime/panic.go:82\\nruntime.sigpanic\\n\\t/usr/local/go/src/runtime/signal_unix.go:390\\ngithub.com/pingcap/tidb/session.(*TxnState).LockKeys\\n\\t\u003cautogenerated\u003e:1\\ngithub.com/pingcap/tidb/executor.(*PointGetExecutor).lockKeyIfNeeded\\n\\t/go/src/github.com/pingcap/tidb/executor/point_get.go:152\\ngithub.com/pingcap/tidb/executor.(*PointGetExecutor).Next\\n\\t/go/src/github.com/pingcap/tidb/executor/point_get.go:132\\ngithub.com/pingcap/tidb/executor.(*ExplainExec).generateExplainInfo\\n\\t/go/src/github.com/pingcap/tidb/executor/explain.go:77\\ngithub.com/pingcap/tidb/executor.(*ExplainExec).Next\\n\\t/go/src/github.com/pingcap/tidb/executor/explain.go:52\\ngithub.com/pingcap/tidb/executor.Next\\n\\t/go/src/github.com/pingcap/tidb/executor/executor.go:191\\ngithub.com/pingcap/tidb/executor.(*recordSet).Next\\n\\t/go/src/github.com/pingcap/tidb/executor/adapter.go:109\\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Next\\n\\t/go/src/github.com/pingcap/tidb/server/driver_tidb.go:365\\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1308\\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1274\\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:1191\\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:897\\ngithub.com/pingcap/tidb/server.(*clientConn).Run\\n\\t/go/src/github.com/pingcap/tidb/server/conn.go:652\\ngithub.com/pingcap/tidb/server.(*Server).onConn\\n\\t/go/src/github.com/pingcap/tidb/server/server.go:440\"]\n","stream":"stdout","time":"2019-09-18T07:58:22.381347942Z"}
```

**Comment by XSHui** [comment]
https://github.com/pingcap/tidb/pull/11771
