### ISSUE TITLE
panic when there is a subquery and a outer condition like `c0 or WEEKOFYEAR(c1)`

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#13019]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t (
    degree decimal(20, 10),
    date_str varchar(30)
);

select * from (
    select sin(degree) as c0, date_str as c1 from t
) t where c0 or WEEKOFYEAR(c1);
```

2. What did you expect to see?
In MySQL:
```
mysql> select * from (
    ->     select sin(degree) as c0, date_str as c1 from t
    -> ) t where c0 or WEEKOFYEAR(c1);
Empty set (0.01 sec)
```

3. What did you see instead?
In TiDB:
```
mysql> select * from (
    ->     select sin(degree) as c0, date_str as c1 from t
    -> ) t where c0 or WEEKOFYEAR(c1);
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

```
["connection running loop panic"] [conn=2] [lastSQL="select * from (\n    select sin(degree) as c0, date_str as c1 from t\n) t where c0 or WEEKOFYEAR(c1)"] [err="\"invalid memory address or nil pointer dereference\""] [stack="goroutine 7382 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x590b1e0, 0xc0013c84b0, 0xc0002db6c0)\n\tgithub.com/pingcap/tidb@/server/conn.go:617 +0xee\npanic(0x53bfd00, 0x6a68050)\n\truntime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/expression.wrapWithIsTrue(0x5952500, 0xc001560000, 0x1, 0x0, 0x0, 0x0, 0xc001331220, 0xc0006a03e0, 0x400ec36)\n\tgithub.com/pingcap/tidb@/expression/expression.go:680 +0x37\ngithub.com/pingcap/tidb/expression.(*logicOrFunctionClass).getFunction(0xc0002fc400, 0x5952500, 0xc001560000, 0xc000edb460, 0x2, 0x2, 0x2, 0x2, 0x5953700, 0xc001331220)\n\tgithub.com/pingcap/tidb@/expression/builtin_op.go:120 +0xcc\ngithub.com/pingcap/tidb/expression.newFunctionImpl(0x5952500, 0xc001560000, 0xc0000a4401, 0x561cff7, 0x2, 0xc000ed9740, 0xc000edb440, 0x2, 0x2, 0xc0014983b0, ...)\n\tgithub.com/pingcap/tidb@/expression/scalar_function.go:137 +0x21d\ngithub.com/pingcap/tidb/expression.NewFunction(...)\n\tgithub.com/pingcap/tidb@/expression/scalar_function.go:157\ngithub.com/pingcap/tidb/expression.NewFunctionInternal(0x5952500, 0xc001560000, 0x561cff7, 0x2, 0xc000ed9740, 0xc000edb440, 0x2, 0x2, 0xc001331220, 0x555d780)\n\tgithub.com/pingcap/tidb@/expression/scalar_function.go:167 +0x92\ngithub.com/pingcap/tidb/expression.ColumnSubstituteImpl(0x5953700, 0xc001331130, 0xc0014dc0c0, 0xc000edb280, 0x2, 0x2, 0xc000edb330, 0xc0006a0760, 0x4f57b57)\n\tgithub.com/pingcap/tidb@/expression/util.go:214 +0x2b7\ngithub.com/pingcap/tidb/expression.ColumnSubstitute(...)\n\tgithub.com/pingcap/tidb@/expression/util.go:178\ngithub.com/pingcap/tidb/planner/core.(*LogicalProjection).PredicatePushDown(0xc0010e9ef0, 0xc001498490, 0x1, 0x1, 0x6aeaa20, 0x0, 0x0, 0x0, 0x1)\n\tgithub.com/pingcap/tidb@/planner/core/rule_predicate_push_down.go:371 +0x1a0\ngithub.com/pingcap/tidb/planner/core.(*LogicalSelection).PredicatePushDown(0xc001004240, 0x6aeaa20, 0x0, 0x0, 0x4048e4c, 0x0, 0x555d780, 0x5953401, 0x6aeaa20)\n\tgithub.com/pingcap/tidb@/planner/core/rule_predicate_push_down.go:76 +0x166\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).PredicatePushDown(0xc001010180, 0x6aeaa20, 0x0, 0x0, 0xc001010180, 0xc001498460, 0x1, 0x1, 0x1)\n\tgithub.com/pingcap/tidb@/planner/core/rule_predicate_push_down.go:55 +0xa6\ngithub.com/pingcap/tidb/planner/core.(*LogicalProjection).PredicatePushDown(0xc001010160, 0x0, 0x0, 0x0, 0x6aebd20, 0xc0014dc300, 0xc000156cf0, 0x5430f40, 0xc000156cf0)\n\tgithub.com/pingcap/tidb@/planner/core/rule_predicate_push_down.go:378 +0x278\ngithub.com/pingcap/tidb/planner/core.(*ppdSolver).optimize(0x6aea600, 0x590b1e0, 0xc0013c84b0, 0x59516c0, 0xc001010160, 0x59516c0, 0xc001010160, 0x0, 0x0)\n\tgithub.com/pingcap/tidb@/planner/core/rule_predicate_push_down.go:28 +0x42\ngithub.com/pingcap/tidb/planner/core.logicalOptimize(0x590b1e0, 0xc0013c84b0, 0x51, 0x59516c0, 0xc001010160, 0x552e340, 0x55f1300, 0x58d2e01, 0x59516c0)\n\tgithub.com/pingcap/tidb@/planner/core/optimizer.go:149 +0x116\ngithub.com/pingcap/tidb/planner/core.DoOptimize(0x590b1e0, 0xc0013c84b0, 0x51, 0x59516c0, 0xc001010160, 0x1, 0x1, 0x0, 0x0)\n\tgithub.com/pingcap/tidb@/planner/core/optimizer.go:119 +0x57\ngithub.com/pingcap/tidb/planner.optimize(0x590b1e0, 0xc0013c84b0, 0x5952500, 0xc001560000, 0x590cce0, 0xc0015bc6c0, 0x592dae0, 0xc0005b7f20, 0x6aeaa20, 0xc0006a0cb8, ...)\n\tgithub.com/pingcap/tidb@/planner/optimize.go:116 +0x553\ngithub.com/pingcap/tidb/planner.Optimize(0x590b1e0, 0xc0013c84b0, 0x5952500, 0xc001560000, 0x590cce0, 0xc0015bc6c0, 0x592dae0, 0xc0005b7f20, 0x0, 0x0, ...)\n\tgithub.com/pingcap/tidb@/planner/optimize.go:55 +0x244\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile(0xc0006a0fa8, 0x590b1e0, 0xc0013c84b0, 0x59116a0, 0xc0015bc6c0, 0x0, 0x0, 0x0)\n\tgithub.com/pingcap/tidb@/executor/compiler.go:62 +0x253\ngithub.com/pingcap/tidb/session.(*session).execute(0xc001560000, 0x590b1e0, 0xc0013c84b0, 0xc00072a231, 0x62, 0xc0006a1267, 0x0, 0xc001087080, 0xc0006a12b8, 0x403b280)\n\tgithub.com/pingcap/tidb@/session/session.go:1103 +0x5e7\ngithub.com/pingcap/tidb/session.(*session).Execute(0xc001560000, 0x590b1e0, 0xc0013c84b0, 0xc00072a231, 0x62, 0x0, 0x0, 0x0, 0x0, 0x0)\n"]
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by nullnotnil** [comment]
Confirming that this has been fixed in master:
```sql
mysql> select * from (
    ->     select sin(degree) as c0, date_str as c1 from t
    -> ) t where c0 or WEEKOFYEAR(c1);
Empty set (0.00 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-782-gb72e47e6d
Edition: Community
Git Commit Hash: b72e47e6db8863c08e47714391cf937b0f1c3269
Git Branch: master
UTC Build Time: 2020-07-15 01:26:06
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue now. Thanks!
