### ISSUE TITLE
tidb panic

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tidb#13053]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
run sysbench

2. What did you expect to see?
load data success

3. What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x19b8bf6]

goroutine 3955 [running]:
github.com/pingcap/tidb/store/tikv/tikvrpc.(*Response).GetRegionError(0x0, 0xc0011d8bd0, 0xc0013f2730, 0xc002b15d40)
	github.com/pingcap/tidb@/store/tikv/tikvrpc/tikvrpc.go:669 +0x26
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReqCtx(0xc0009f37f0, 0xc0011d8bd0, 0xc002b15d40, 0x145f8, 0x8, 0x7, 0x4a817c800, 0xc0004f2000, 0xc0005c8e20, 0x0, ...)
	github.com/pingcap/tidb@/store/tikv/region_request.go:149 +0x291
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReq(...)
	github.com/pingcap/tidb@/store/tikv/region_request.go:73
github.com/pingcap/tidb/store/tikv.(*tikvStore).SendReq(0xc0004100f0, 0xc0011d8bd0, 0xc002b15d40, 0x145f8, 0x8, 0x7, 0x4a817c800, 0x0, 0x0, 0x0)
	github.com/pingcap/tidb@/store/tikv/kv.go:383 +0xea
github.com/pingcap/tidb/store/tikv.(*LockResolver).getTxnStatus(0xc0002e68c0, 0xc0011d8bd0, 0x5b881c1b7240006, 0xc000ae7820, 0x1b, 0x20, 0x5b881c1b7240005, 0x5b881c1f4dc0001, 0x39c5380, 0x0, ...)
	github.com/pingcap/tidb@/store/tikv/lock_resolver.go:409 +0x205
github.com/pingcap/tidb/store/tikv.(*LockResolver).getTxnStatusFromLock(0xc0002e68c0, 0xc0011d8bd0, 0xc0013f2690, 0x5b881c1b7240005, 0x1, 0xc00135e318, 0x0, 0x1)
	github.com/pingcap/tidb@/store/tikv/lock_resolver.go:387 +0x89
github.com/pingcap/tidb/store/tikv.(*LockResolver).ResolveLocks(0xc0002e68c0, 0xc0011d8bd0, 0x5b881c1b7240005, 0xc00135e310, 0x1, 0x1, 0x0, 0x1, 0x0)
	github.com/pingcap/tidb@/store/tikv/lock_resolver.go:294 +0x2be
github.com/pingcap/tidb/store/tikv.actionPrewrite.handleSingleBatch(0xc000b06c30, 0xc0011d8bd0, 0x145f8, 0x8, 0x7, 0xc002ea56e0, 0x1, 0x1, 0xc002733080, 0xc0010c3530)
	github.com/pingcap/tidb@/store/tikv/2pc.go:557 +0x6b1
github.com/pingcap/tidb/store/tikv.(*batchExecutor).startWorker.func1(0xc002732f40, 0xc0016ca540, 0x145f8, 0x8, 0x7, 0xc002ea56e0, 0x1, 0x1)
	github.com/pingcap/tidb@/store/tikv/2pc.go:1220 +0x180
created by github.com/pingcap/tidb/store/tikv.(*batchExecutor).startWorker
	github.com/pingcap/tidb@/store/tikv/2pc.go:1202 +0x1c8
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v4.0.0-alpha-664-g7bfa8967e
Git Commit Hash: 7bfa8967e174642e270677e1348781a7c0e8dad2
Git Branch: master
UTC Build Time: 2019-10-31 03:45:44
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by salarali** [comment]
I am getting this error for a Get command.

How to mitigate this error or when will the fix be released?

**Comment by shenli** [comment]
@salarali thanks for your feedback! Could you show me the result of `select tidb_version();`

**Comment by shenli** [comment]
The panic may be caused by the version mismatch between TiDB and TiKV. Could you show me the result of `tidb-server -V` and `tikv-server -V`?

**Comment by salarali** [comment]
It turns out I was using the wrong library. I am only using tikv, not tidb. I am now using the proper client for tikv `https://github.com/tikv/client-go` and the error has gone away.

Tikv version for reference: 
```TiKV
Release Version:   3.0.7
Git Commit Hash:   ac6f02648a8c6ccb7ccafca20287e1b27007e4a0
Git Commit Branch: HEAD
UTC Build Time:    2019-12-04 10:06:20
Rust Version:      rustc 1.37.0-nightly (0e4a56b4b 2019-06-13)
```

Thanks for the quick reply.

**Comment by shenli** [comment]
Glad to hear that :)

**Comment by jackysp** [comment]
related to https://github.com/pingcap/tidb/issues/11902

**Comment by tiancaiamao** [comment]
This panic is caused by using different (incompatible) TiDB and TiKV version binary.
