### ISSUE TITLE
builtin function panic

### ISSUE THREAD

**Issue by you06** [pingcap/tidb#13422]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
SELECT truncate(json_object(), version());
```

2. What did you expect to see?

* MySQL

```
mysql> SELECT truncate(json_object(), version());
+------------------------------------+
| truncate(json_object(), version()) |
+------------------------------------+
|                         0.00000000 |
+------------------------------------+
1 row in set, 3 warnings (0.00 sec)
```

3. What did you see instead?

* TiDB

```
mysql> SELECT truncate(json_object(), version());
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

* log
```
[2019/11/13 14:31:01.417 +08:00] [ERROR] [conn.go:619] ["connection running loop panic"] [conn=19] [lastSQL="SELECT truncate(json_object(), version())"] [err="runtime error: invalid memory address or nil pointer dereference"] [stack="goroutine 91470 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x26e71c0, 0xc0013b9290, 0xc002c095f0)
github.com/pingcap/tidb@/server/conn.go:617 +0xee
panic(0x217a2a0, 0x36b1ae0)
runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/expression.newFunctionImpl(0x27300c0, 0xc001d8a800, 0x324c1001, 0xc0030522a8, 0x8, 0xc0020fa0c0, 0xc002dea200, 0x2, 0x2, 0x1, ...)
github.com/pingcap/tidb@/expression/scalar_function.go:141 +0x247
github.com/pingcap/tidb/expression.NewFunction(...)
github.com/pingcap/tidb@/expression/scalar_function.go:157
github.com/pingcap/tidb/planner/core.(*expressionRewriter).newFunction(0xc001319ee0, 0xc0030522a8, 0x8, 0xc0020fa0c0, 0xc002dea200, 0x2, 0x2, 0x0, 0xe, 0xc0020ecee0, ...)
github.com/pingcap/tidb@/planner/core/expression_rewriter.go:999 +0x14b
github.com/pingcap/tidb/planner/core.(*expressionRewriter).funcCallToExpression(0xc001319ee0, 0xc0020fa0b0)
github.com/pingcap/tidb@/planner/core/expression_rewriter.go:1489 +0x22d
github.com/pingcap/tidb/planner/core.(*expressionRewriter).Leave(0xc001319ee0, 0x26e80c0, 0xc0020fa0b0, 0x2702260, 0xc0020fa000, 0xc001a8e301)
github.com/pingcap/tidb@/planner/core/expression_rewriter.go:920 +0x10f3
github.com/pingcap/parser/ast.(*FuncCallExpr).Accept(0xc0020fa0b0, 0x26c7a40, 0xc001319ee0, 0xc001d51680, 0xc00066e398, 0x0)
github.com/pingcap/parser@v0.0.0-20191112053614-3b43b46331d5/ast/functions.go:474 +0x182
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode(0xc001fedc00, 0xc001319ee0, 0x2702260, 0xc0020fa0b0, 0xc001d51601, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
github.com/pingcap/tidb@/planner/core/expression_rewriter.go:167 +0x8e
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteWithPreprocess(0xc001fedc00, 0x26e71c0, 0xc0013b9290, 0x2702260, 0xc0020fa0b0, 0x272f6e0, 0xc001d51680, 0x0, 0x0, 0x1, ...)
github.com/pingcap/tidb@/planner/core/expression_rewriter.go:116 +0x163
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildProjection(0xc001fedc00, 0x26e71c0, 0xc0013b9290, 0x272f6e0, 0xc001d51680, 0xc0006482b0, 0x1, 0x1, 0x0, 0x0, ...)
github.com/pingcap/tidb@/planner/core/logical_plan_builder.go:852 +0x6b4
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect(0xc001fedc00, 0x26e71c0, 0xc0013b9290, 0xc001c6d140, 0x272f6e0, 0xc001d51680, 0x0, 0x0)
github.com/pingcap/tidb@/planner/core/logical_plan_builder.go:2281 +0x506
github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build(0xc001fedc00, 0x26e71c0, 0xc0013b9290, 0x26e8bc0, 0xc001c6d140, 0xc001fedc00, 0x22adae0, 0x26e71c0, 0x7f2493080f18)
github.com/pingcap/tidb@/planner/core/planbuilder.go:379 +0xc0a
github.com/pingcap/tidb/planner.optimize(0x26e71c0, 0xc0013b9290, 0x27300c0, 0xc001d8a800, 0x26e8bc0, 0xc001c6d140, 0x270b4a0, 0xc000c4b8f0, 0x146f80b, 0xc003ca7cc0, ...)
github.com/pingcap/tidb@/planner/optimize.go:107 +0x17f
github.com/pingcap/tidb/planner.Optimize(0x26e71c0, 0xc0013b9290, 0x27300c0, 0xc001d8a800, 0x26e8bc0, 0xc001c6d140, 0x270b4a0, 0xc000c4b8f0, 0x0, 0x0, ...)
github.com/pingcap/tidb@/planner/optimize.go:49 +0x211
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc00066ef80, 0x26e71c0, 0xc0013b9290, 0x26ed5c0, 0xc001c6d140, 0x0, 0x0, 0x0)
github.com/pingcap/tidb@/executor/compiler.go:62 +0x253
github.com/pingcap/tidb/session.(*session).execute(0xc001d8a800, 0x26e71c0, 0xc0013b9290, 0xc0030522a1, 0x29, 0xc001496000, 0x18f, 0x8, 0x18f, 0xc00066f2a8)
github.com/pingcap/tidb@/session/session.go:1103 +0x5e7
github.com/pingcap/tidb/session.(*session).Execute(0xc001d8a800, 0x26e71c0, 0xc0013b9290, 0xc0030522a1, 0x29, 0x0, 0x0, 0x0, 0x0, 0x0)
github.com/pingcap/tidb@/session/session.go:1056 +0xdb
github.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc0013b9a10, 0x26e71c0, 0xc0013b9290, 0xc0030522a1, 0x29, 0xc000f80460, 0x8, 0x8, 0xc00066f430, 0xde1ac8)
github.com/pingcap/tidb@/server/driver_tidb.go:248 +0x7c
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc002c095f0, 0x26e71c0, 0xc0013b9290, 0xc0030522a1, 0x29, 0x0, 0x0)
github.com/pingcap/tidb@/server/conn.go:1152 +0x91
github.com/pingcap/tidb/server.(*clientC"]
[2019/11/13 14:31:01.418 +08:00] [INFO] [server.go:414] ["connection closed"] [conn=19]
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v4.0.0-alpha-845-g343bb640a
Git Commit Hash: 343bb640a0c2fa9019ba4f1b2ddfa897ba0a46eb
Git Branch: master
UTC Build Time: 2019-11-13 04:33:29
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by you06** [comment]
```
mysql> SELECT truncate(json_array(), last_insert_id());
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

And this also result in panic.

```
[2019/11/15 16:02:27.238 +08:00] [ERROR] [conn.go:619] ["connection running loop panic"] [conn=3270] [lastSQL="SELECT truncate(json_array(), last_insert_id())"] [err="runtime error: invalid memory address or nil pointer dereference"] [stack="goroutine 19708402 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x26f6a40, 0xc030ff9590, 0xc01df0c5b0)
github.com/pingcap/tidb@/server/conn.go:617 +0xee
panic(0x2187800, 0x36c6ae0)
runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/expression.newFunctionImpl(0x273ff60, 0xc00b337300, 0xc0c1801, 0xc02d188488, 0x8, 0xc0022067a0, 0xc00ad830e0, 0x2, 0x2, 0x1, ...)
github.com/pingcap/tidb@/expression/scalar_function.go:141 +0x247
github.com/pingcap/tidb/expression.NewFunction(...)
github.com/pingcap/tidb@/expression/scalar_function.go:157
github.com/pingcap/tidb/planner/core.(*expressionRewriter).newFunction(0xc008b23450, 0xc02d188488, 0x8, 0xc0022067a0, 0xc00ad830e0, 0x2, 0x2, 0xc00003a000, 0x12f9a51, 0xc020fd8460, ...)
github.com/pingcap/tidb@/planner/core/expression_rewriter.go:999 +0x14b
github.com/pingcap/tidb/planner/core.(*expressionRewriter).funcCallToExpression(0xc008b23450, 0xc002206790)
github.com/pingcap/tidb@/planner/core/expression_rewriter.go:1489 +0x22d
github.com/pingcap/tidb/planner/core.(*expressionRewriter).Leave(0xc008b23450, 0x26f7940, 0xc002206790, 0x2711d20, 0xc0022066e0, 0xc006c86b01)
github.com/pingcap/tidb@/planner/core/expression_rewriter.go:920 +0x10f3
github.com/pingcap/parser/ast.(*FuncCallExpr).Accept(0xc002206790, 0x26d7240, 0xc008b23450, 0xc0022121e0, 0xc00003a390, 0x0)
github.com/pingcap/parser@v0.0.0-20191112053614-3b43b46331d5/ast/functions.go:474 +0x182
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode(0xc00acc4a00, 0xc008b23450, 0x2711d20, 0xc002206790, 0xc002212101, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
github.com/pingcap/tidb@/planner/core/expression_rewriter.go:167 +0x8e
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteWithPreprocess(0xc00acc4a00, 0x26f6a40, 0xc030ff9590, 0x2711d20, 0xc002206790, 0x273f580, 0xc0022121e0, 0x0, 0x0, 0x1, ...)
github.com/pingcap/tidb@/planner/core/expression_rewriter.go:116 +0x163
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildProjection(0xc00acc4a00, 0x26f6a40, 0xc030ff9590, 0x273f580, 0xc0022121e0, 0xc008a2fea0, 0x1, 0x1, 0x0, 0x0, ...)
github.com/pingcap/tidb@/planner/core/logical_plan_builder.go:866 +0x6b4
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect(0xc00acc4a00, 0x26f6a40, 0xc030ff9590, 0xc00799ce40, 0x273f580, 0xc0022121e0, 0x0, 0x0)
github.com/pingcap/tidb@/planner/core/logical_plan_builder.go:2305 +0x506
github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build(0xc00acc4a00, 0x26f6a40, 0xc030ff9590, 0x26f8440, 0xc00799ce40, 0xc00acc4a00, 0xc00030e000, 0x26f6a40, 0x22d08e0)
github.com/pingcap/tidb@/planner/core/planbuilder.go:393 +0xc0a
github.com/pingcap/tidb/planner.optimize(0x26f6a40, 0xc030ff9590, 0x273ff60, 0xc00b337300, 0x26f8440, 0xc00799ce40, 0x271b1e0, 0xc00c1383c0, 0x22db3c0, 0x1470fbb, ...)
github.com/pingcap/tidb@/planner/optimize.go:118 +0x17f
github.com/pingcap/tidb/planner.Optimize(0x26f6a40, 0xc030ff9590, 0x273ff60, 0xc00b337300, 0x26f8440, 0xc00799ce40, 0x271b1e0, 0xc00c1383c0, 0x0, 0x0, ...)
github.com/pingcap/tidb@/planner/optimize.go:53 +0x211
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc00003af80, 0x26f6a40, 0xc030ff9590, 0x26fce40, 0xc00799ce40, 0x0, 0x0, 0x0)
github.com/pingcap/tidb@/executor/compiler.go:62 +0x253
github.com/pingcap/tidb/session.(*session).execute(0xc00b337300, 0x26f6a40, 0xc030ff9590, 0xc02d188481, 0x2f, 0xc00b8e2000, 0x12c, 0x8, 0x12c, 0xc00003b2a8)
github.com/pingcap/tidb@/session/session.go:1103 +0x5e7
github.com/pingcap/tidb/session.(*session).Execute(0xc00b337300, 0x26f6a40, 0xc030ff9590, 0xc02d188481, 0x2f, 0x0, 0x0, 0x0, 0x0, 0x0)
github.com/pingcap/tidb@/session/session.go:1056 +0xdb
github.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc014eb7e30, 0x26f6a40, 0xc030ff9590, 0xc02d188481, 0x2f, 0xc000edbb28, 0x8, 0x8, 0xc00003b430, 0xde3278)
github.com/pingcap/tidb@/server/driver_tidb.go:248 +0x7c
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc01df0c5b0, 0x26f6a40, 0xc030ff9590, 0xc02d188481, 0x2f, 0x0, 0x0)
github.com/pingcap/tidb@/server/conn.go:1152 +0x91
github.com/pingcap/tidb/serv"]
```

**Comment by zz-jason** [comment]
@fzhedu PTAL

**Comment by nullnotnil** [comment]
I checked this against master - while it could be considered a compatibility issue, I think the main issue here is fixed - there is no panic:
```sql
mysql> select truncate(json_object(), '8.0.21');
+-----------------------------------+
| truncate(json_object(), '8.0.21') |
+-----------------------------------+
|                        0.00000000 |
+-----------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------------------------------------+
| Level   | Code | Message                                     |
+---------+------+---------------------------------------------+
| Warning | 1292 | Truncated incorrect INTEGER value: '8.0.21' |
+---------+------+---------------------------------------------+
1 row in set (0.00 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-782-gb72e47e6d
Edition: Community
Git Commit Hash: b72e47e6db8863c08e47714391cf937b0f1c3269
Git Branch: master
UTC Build Time: 2020-07-15 01:26:06
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

mysql> SELECT truncate(json_array(), last_insert_id());
+------------------------------------------+
| truncate(json_array(), last_insert_id()) |
+------------------------------------------+
|                                      0.0 |
+------------------------------------------+
1 row in set (0.01 sec)

mysql> SELECT truncate(json_object(), version());
+------------------------------------+
| truncate(json_object(), version()) |
+------------------------------------+
|                            0.00000 |
+------------------------------------+
1 row in set, 1 warning (0.00 sec)
```

I am going to go ahead and close this issue.
