### ISSUE TITLE
unit test in executor package timeout.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#13751]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

release-3.0
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/16844/pipeline/78

release-2.1 #13681
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/17286/pipeline

```panic: test timed out after 7m0s```

wierd goroutines:
```
[2019-11-21T05:34:52.388Z] goroutine 43474 [select, 4 minutes]:

[2019-11-21T05:34:52.388Z] github.com/pingcap/tidb/executor.readProjectionInput(0xc002368d20, 0xc0022cccc0, 0xc00188f420)

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:381 +0xe0

[2019-11-21T05:34:52.388Z] github.com/pingcap/tidb/executor.(*projectionWorker).run(0xc00234d5c0, 0x2b386a0, 0xc000120010)

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:351 +0x128

[2019-11-21T05:34:52.388Z] created by github.com/pingcap/tidb/executor.(*ProjectionExec).prepare

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:245 +0xd17

[2019-11-21T05:34:52.388Z] 

[2019-11-21T05:34:52.388Z] goroutine 43475 [select, 4 minutes]:

[2019-11-21T05:34:52.388Z] github.com/pingcap/tidb/executor.readProjectionInput(0xc002368e40, 0xc0022cccc0, 0x60)

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:381 +0xe0

[2019-11-21T05:34:52.388Z] github.com/pingcap/tidb/executor.(*projectionWorker).run(0xc00234d600, 0x2b386a0, 0xc000120010)

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:351 +0x128

[2019-11-21T05:34:52.388Z] created by github.com/pingcap/tidb/executor.(*ProjectionExec).prepare

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:245 +0xd17

[2019-11-21T05:34:52.388Z] 

[2019-11-21T05:34:52.388Z] goroutine 43477 [select, 4 minutes]:

[2019-11-21T05:34:52.388Z] github.com/pingcap/tidb/executor.readProjectionInput(0xc002369080, 0xc0022cccc0, 0x0)

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:381 +0xe0

[2019-11-21T05:34:52.388Z] github.com/pingcap/tidb/executor.(*projectionWorker).run(0xc00234d680, 0x2b386a0, 0xc000120010)

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:351 +0x128

[2019-11-21T05:34:52.388Z] created by github.com/pingcap/tidb/executor.(*ProjectionExec).prepare

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:245 +0xd17

[2019-11-21T05:34:52.388Z] 

[2019-11-21T05:34:52.388Z] goroutine 43476 [select, 4 minutes]:

[2019-11-21T05:34:52.388Z] github.com/pingcap/tidb/executor.readProjectionInput(0xc002368f60, 0xc0022cccc0, 0xbd8399)

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:381 +0xe0

[2019-11-21T05:34:52.388Z] github.com/pingcap/tidb/executor.(*projectionWorker).run(0xc00234d640, 0x2b386a0, 0xc000120010)

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:351 +0x128

[2019-11-21T05:34:52.388Z] created by github.com/pingcap/tidb/executor.(*ProjectionExec).prepare

[2019-11-21T05:34:52.388Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/projection.go:245 +0xd17
```

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

release-2.1 & release-3.0

**Comment by zimulala** [comment]
This problem occurred 4 times in this PR（#14162） stable.
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/20290/pipeline
