### ISSUE TITLE
planner: panic when join on primary keys

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tidb#13794]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
mysql> create table s (a int primary key, b int);
Query OK, 0 rows affected (0.01 sec)

mysql> create table t (a int primary key, b int);
Query OK, 0 rows affected (0.00 sec)

mysql> alter table t add index (a);
Query OK, 0 rows affected (0.02 sec)

mysql> alter table s add index (a);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t values (0,1),(32,0);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> insert into s values (0,1),(2,0);
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> select * from s join t on t.a=s.a;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
2. What did you expect to see?
running correctly.

3. What did you see instead?
```
[2019/11/28 10:52:06.264 +08:00] [ERROR] [conn.go:619] ["connection running loop panic"] [conn=2] [lastSQL="select * from s join t on t.a=s.a"] [err="runtime error: makeslice: cap out of range"] [stack="goroutine 430 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x5a60d60, 0xc00103ede0, 0xc00018b450)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:617 +0xee\npanic(0x54d6420, 0x5a07c00)\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/planner/core.(*LogicalJoin).moveEqualToOtherConditions(0xc000152c40, 0xc00154b920, 0x2, 0x2, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/exhaust_physical_plans.go:88 +0x116\ngithub.com/pingcap/tidb/planner/core.(*LogicalJoin).getMergeJoin(0xc000152c40, 0xc001377810, 0x20, 0x20, 0xc0008980e0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/exhaust_physical_plans.go:153 +0x6c1\ngithub.com/pingcap/tidb/planner/core.(*LogicalJoin).exhaustPhysicalPlans(0xc000152c40, 0xc001377810, 0x2, 0xc0008980e0, 0x6d1a620)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/exhaust_physical_plans.go:1308 +0x4d\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask(0xc000152c60, 0xc001377810, 0x0, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:145 +0x23b\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask(0xc0013736d0, 0xc0013777c0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:152 +0x5bd\ngithub.com/pingcap/tidb/planner/core.physicalOptimize(0x5aaa800, 0xc0013736b0, 0x851, 0x5aaa800, 0xc0013736b0, 0x5aaa800, 0xc0013736b0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:174 +0xb2\ngithub.com/pingcap/tidb/planner/core.DoOptimize(0x5a60d60, 0xc00103ede0, 0x851, 0x5aaa800, 0xc0013736b0, 0x1, 0x2, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:126 +0xa4\ngithub.com/pingcap/tidb/planner.optimize(0x5a60d60, 0xc00103ede0, 0x5aab740, 0xc0007b7e00, 0x5a62760, 0xc00111e9c0, 0x5a867c0, 0xc001368f90, 0x562e820, 0x4778f01, ...)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/optimize.go:157 +0x574\ngithub.com/pingcap/tidb/planner.Optimize(0x5a60d60, 0xc00103ede0, 0x5aab740, 0xc0007b7e00, 0x5a62760, 0xc00111e9c0, 0x5a867c0, 0xc001368f90, 0x0, 0x0, ...)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/optimize.go:53 +0x211\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile(0xc0004cef80, 0x5a60d60, 0xc00103ede0, 0x5a673e0, 0xc00111e9c0, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/executor/compiler.go:63 +0x253\ngithub.com/pingcap/tidb/session.(*session).execute(0xc0007b7e00, 0x5a60d60, 0xc00103ede0, 0xc0012bac31, 0x21, 0x5594000, 0x403abcb, 0xc0004cf268, 0x10000000404ff8e, 0x405ef60)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/session/session.go:1116 +0x5e7\ngithub.com/pingcap/tidb/session.(*session).Execute(0xc0007b7e00, 0x5a60d60, 0xc00103ede0, 0xc0012bac31, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/session/session.go:1069 +0xdb\ngithub.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc00103f110, 0x5a60d60, 0xc00103ede0, 0xc0012bac31, 0x21, 0xc00088c0f0, 0x8, 0x8, 0xc0004cf430, 0x40c5c28)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/driver_tidb.go:248 +0x7c\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc00018b450, 0x5a60d60, 0xc00103ede0, 0xc0012bac31, 0x21, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:1152 +0x91\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc00018b450, 0x5a60d60, 0xc00103ede0, 0xc0012bac31, 0x22, 0x21, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:850 +0x5b3\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc00018b450, 0x5a60d60, 0xc00103ede0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:672 +0x273\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc000809680, 0xc00018b450)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/server.go:442 +0x49f\ncreated by github.com/pingcap/tidb/server.(*Server).Run\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/server.go:355 +0x759\n"]
[2019/11/28 10:52:06.265 +08:00] [INFO] [server.go:418] ["connection closed"] [conn=2]
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

+------------------------------------------+
| version()                                |
+------------------------------------------+
| 5.7.25-TiDB-v4.0.0-alpha-1020-g0b9059162 |
+------------------------------------------+
1 row in set (0.01 sec)

**Comment by parthibd** [comment]
```
[2019/11/28 10:52:06.264 +08:00] [ERROR] [conn.go:619] ["connection running loop panic"] [conn=2] [lastSQL="select * from s join t on t.a=s.a"] [err="runtime error: makeslice: cap out of range"] [stack="goroutine 430 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x5a60d60, 0xc00103ede0, 0xc00018b450)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:617 +0xee\npanic(0x54d6420, 0x5a07c00)\n\t/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/planner/core.(*LogicalJoin).moveEqualToOtherConditions(0xc000152c40, 0xc00154b920, 0x2, 0x2, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/exhaust_physical_plans.go:88 +0x116\ngithub.com/pingcap/tidb/planner/core.(*LogicalJoin).getMergeJoin(0xc000152c40, 0xc001377810, 0x20, 0x20, 0xc0008980e0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/exhaust_physical_plans.go:153 +0x6c1\ngithub.com/pingcap/tidb/planner/core.(*LogicalJoin).exhaustPhysicalPlans(0xc000152c40, 0xc001377810, 0x2, 0xc0008980e0, 0x6d1a620)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/exhaust_physical_plans.go:1308 +0x4d\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask(0xc000152c60, 0xc001377810, 0x0, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:145 +0x23b\ngithub.com/pingcap/tidb/planner/core.(*baseLogicalPlan).findBestTask(0xc0013736d0, 0xc0013777c0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/find_best_task.go:152 +0x5bd\ngithub.com/pingcap/tidb/planner/core.physicalOptimize(0x5aaa800, 0xc0013736b0, 0x851, 0x5aaa800, 0xc0013736b0, 0x5aaa800, 0xc0013736b0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:174 +0xb2\ngithub.com/pingcap/tidb/planner/core.DoOptimize(0x5a60d60, 0xc00103ede0, 0x851, 0x5aaa800, 0xc0013736b0, 0x1, 0x2, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/core/optimizer.go:126 +0xa4\ngithub.com/pingcap/tidb/planner.optimize(0x5a60d60, 0xc00103ede0, 0x5aab740, 0xc0007b7e00, 0x5a62760, 0xc00111e9c0, 0x5a867c0, 0xc001368f90, 0x562e820, 0x4778f01, ...)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/optimize.go:157 +0x574\ngithub.com/pingcap/tidb/planner.Optimize(0x5a60d60, 0xc00103ede0, 0x5aab740, 0xc0007b7e00, 0x5a62760, 0xc00111e9c0, 0x5a867c0, 0xc001368f90, 0x0, 0x0, ...)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/planner/optimize.go:53 +0x211\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile(0xc0004cef80, 0x5a60d60, 0xc00103ede0, 0x5a673e0, 0xc00111e9c0, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/executor/compiler.go:63 +0x253\ngithub.com/pingcap/tidb/session.(*session).execute(0xc0007b7e00, 0x5a60d60, 0xc00103ede0, 0xc0012bac31, 0x21, 0x5594000, 0x403abcb, 0xc0004cf268, 0x10000000404ff8e, 0x405ef60)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/session/session.go:1116 +0x5e7\ngithub.com/pingcap/tidb/session.(*session).Execute(0xc0007b7e00, 0x5a60d60, 0xc00103ede0, 0xc0012bac31, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/session/session.go:1069 +0xdb\ngithub.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc00103f110, 0x5a60d60, 0xc00103ede0, 0xc0012bac31, 0x21, 0xc00088c0f0, 0x8, 0x8, 0xc0004cf430, 0x40c5c28)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/driver_tidb.go:248 +0x7c\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc00018b450, 0x5a60d60, 0xc00103ede0, 0xc0012bac31, 0x21, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:1152 +0x91\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc00018b450, 0x5a60d60, 0xc00103ede0, 0xc0012bac31, 0x22, 0x21, 0x0, 0x0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:850 +0x5b3\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc00018b450, 0x5a60d60, 0xc00103ede0)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/conn.go:672 +0x273\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc000809680, 0xc00018b450)\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/server.go:442 +0x49f\ncreated by github.com/pingcap/tidb/server.(*Server).Run\n\t/Users/fzh/go/src/github.com/pingcap/tidb/server/server.go:355 +0x759\n"]
[2019/11/28 10:52:06.265 +08:00] [INFO] [server.go:418] ["connection closed"] [conn=2]
```

**Comment by parthibd** [comment]
Formatted it a little bit.

**Comment by nullnotnil** [comment]
Confirming this has been fixed in master:
```sql
DROP TABLE IF EXISTS s, t;
create table s (a int primary key, b int);
create table t (a int primary key, b int);
alter table t add index (a);
alter table s add index (a);
insert into t values (0,1),(32,0);
insert into s values (0,1),(2,0);
select * from s join t on t.a=s.a;

select tidb_version()\G

..

mysql> select * from s join t on t.a=s.a;
+---+------+---+------+
| a | b    | a | b    |
+---+------+---+------+
| 0 |    1 | 0 |    1 |
+---+------+---+------+
1 row in set (0.00 sec)

mysql> 
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-771-gca41972fb
Edition: Community
Git Commit Hash: ca41972fbac068c8a5de107d9075f09ac68842ac
Git Branch: master
UTC Build Time: 2020-07-14 02:41:21
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue now.
