### ISSUE TITLE
tikv.(*RegionRequestSender).SendReqCtx panic at GetRegionError

### ISSUE THREAD

**Issue by overvenus** [pingcap/tidb#14058]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

Not panic

3. What did you see instead?

```
[2019-12-13T12:19:58.016Z] [2019/12/13 20:19:57.760 +08:00] [ERROR] [domain.go:1118] ["recover in domain failed"] [funcName=loadSchemaInLoop] [error="runtime error: invalid memory address or nil pointer dereference"] [buffer="goroutine 128 [running]:
github.com/pingcap/tidb/util.GetStack(...)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/util/misc.go:60
github.com/pingcap/tidb/domain.recoverInDomain(0x29bdcd4, 0x10, 0x44f7901)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:1117 +0xb0
panic(0x26cab00, 0x401be90)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/store/tikv/tikvrpc.(*Response).GetRegionError(0x0, 0xc00056a600, 0xc000896f50, 0xc000768280)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/tikvrpc/tikvrpc.go:676 +0x26
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReqCtx(0xc00041abb0, 0xc00056a600, 0xc000768280, 0x7b, 0x2, 0xa, 0x4a817c800, 0xc000808000, 0xc000a28360, 0x0, ...)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/region_request.go:156 +0x2ab
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReq(...)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/region_request.go:75
github.com/pingcap/tidb/store/tikv.(*tikvStore).SendReq(0xc00051a000, 0xc00056a600, 0xc000768280, 0x7b, 0x2, 0xa, 0x4a817c800, 0x0, 0xc000ab00e0, 0x3f3d7bb797979cfb)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/kv.go:383 +0xea
github.com/pingcap/tidb/store/tikv.(*LockResolver).getTxnStatus(0xc00051c000, 0xc00056a600, 0x5bbfcce22380003, 0xc0008d62e0, 0x12, 0x20, 0x5bbfcce22380007, 0x5bbfcce22380007, 0xbf74fe5b6d414b00, 0x15bb4b502, ...)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:470 +0x214
github.com/pingcap/tidb/store/tikv.(*LockResolver).getTxnStatusFromLock(0xc00051c000, 0xc00056a600, 0xc000896eb0, 0x5bbfcce22380007, 0xc000896e60, 0x1, 0x203000, 0x1, 0xc0007cc300)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:403 +0x11b
github.com/pingcap/tidb/store/tikv.(*LockResolver).ResolveLocks(0xc00051c000, 0xc00056a600, 0x5bbfcce22380007, 0xc00041b210, 0x1, 0x1, 0x5bbfcce22380003, 0xbbb, 0x3, 0xc000058720, ...)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:295 +0x184
github.com/pingcap/tidb/store/tikv.(*clientHelper).ResolveLocks(0xc00041b228, 0xc00056a600, 0x5bbfcce22380007, 0xc00041b210, 0x1, 0x1, 0x4a817c800, 0x0, 0x0)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/coprocessor.go:792 +0x70
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).get(0xc000896be0, 0xc00056a600, 0xc0000586c0, 0x24, 0x29, 0xc00086e270, 0x2dfc5a0, 0xc000af6570, 0xc00041b438, 0xf2085c)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/snapshot.go:351 +0x46d
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).Get(0xc000896be0, 0x2dfc520, 0xc00012a018, 0xc0000586c0, 0x24, 0x29, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/snapshot.go:282 +0x1c1
github.com/pingcap/tidb/structure.(*TxStructure).Get(0xc000846800, 0x407cab0, 0x10, 0x10, 0xc00041b5a0, 0xee6708, 0x30, 0x27c3180, 0xc000896b01)
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1"] [stack="github.com/pingcap/tidb/domain.recoverInDomain
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:1118
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:679
runtime.panicmem
	/usr/local/go/src/runtime/panic.go:199
runtime.sigpanic
	/usr/local/go/src/runtime/signal_unix.go:394
github.com/pingcap/tidb/store/tikv/tikvrpc.(*Response).GetRegionError
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/tikvrpc/tikvrpc.go:676
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReqCtx
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/region_request.go:156
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReq
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/region_request.go:75
github.com/pingcap/tidb/store/tikv.(*tikvStore).SendReq
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/kv.go:383
github.com/pingcap/tidb/store/tikv.(*LockResolver).getTxnStatus
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:470
github.com/pingcap/tidb/store/tikv.(*LockResolver).getTxnStatusFromLock
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:403
github.com/pingcap/tidb/store/tikv.(*LockResolver).ResolveLocks
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/lock_resolver.go:295
github.com/pingcap/tidb/store/tikv.(*clientHelper).ResolveLocks
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/coprocessor.go:792
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).get
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/snapshot.go:351
github.com/pingcap/tidb/store/tikv.(*tikvSnapshot).Get
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/store/tikv/snapshot.go:282
github.com/pingcap/tidb/structure.(*TxStructure).Get
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/structure/string.go:36
github.com/pingcap/tidb/structure.(*TxStructure).GetInt64
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/structure/string.go:45
github.com/pingcap/tidb/meta.(*Meta).GetSchemaVersion
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/meta/meta.go:186
github.com/pingcap/tidb/domain.(*Domain).loadInfoSchema
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:91
github.com/pingcap/tidb/domain.(*Domain).Reload
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:359
github.com/pingcap/tidb/domain.(*Domain).loadSchemaInLoop
	/home/jenkins/agent/workspace/br_ghpr_integration_test_3.1/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20191213040028-9009da737834/domain/domain.go:476"]
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master branch @https://github.com/pingcap/tidb/commit/9009da737834fbe8fb9eee2541133ae92905e7a5

See more https://github.com/pingcap/br/pull/112

**Comment by coocood** [comment]
@overvenus 
From the  panic stack we can see the panic method is `getTxnStatus` which send `CheckTxnStatus` request that is not supported by TiKV 3.1
