### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhongzc** [pingcap/tidb#16595]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

CI task `integration-copr-test` failed
data: https://github.com/tikv/copr-test/blob/master/push-down-test/prepare/0_data.sql

### 2. What did you expect to see?

Test pass

### 3. What did you see instead?
```
[2020-04-20T03:59:25.522Z] Test case: sql/randgen-topn/3_compare_2.sql
[2020-04-20T03:59:25.522Z] Statement: #1502 -  SELECT GREATEST( ( ( ( `col_tinyint_unsigned` > ( STRCMP( `col_char_2`, ( `col_enum` LIKE `col_decimal_key` ) ) ) ) <> `col_float_unsigned_key` ) IS FALSE ), `col_decimal_unsigned`, ( `col_set_key` <=> `col_enum_key` ), `col_text`, '1977-08-12' ) AS field1, `col_smallint_unsigned` NOT LIKE ( LEAST( `col_set`, `col_date`, `col_char_2` ) ) AS field2 FROM `table20_int_autoinc` WHERE ISNULL( ( STRCMP( ( `col_binary_8` != ( NULL != 0 ) ), ( LEAST( `col_datetime_key`, `col_int`, 'z', 0, `col_set` ) ) ) ) ) ORDER BY field1, field2 LIMIT 5 /* QNO 1504 CON_ID 196 */ ;
[2020-04-20T03:59:25.522Z] NoPushDown Output: 
[2020-04-20T03:59:25.522Z] Error 1105: runtime error: invalid memory address or nil pointer dereference
[2020-04-20T03:59:25.522Z] 
[2020-04-20T03:59:25.522Z] WithPushDown Output: 
[2020-04-20T03:59:25.522Z] field1	field2
[2020-04-20T03:59:25.522Z] NULL	1
[2020-04-20T03:59:25.522Z] NULL	1
[2020-04-20T03:59:25.522Z] NULL	1
[2020-04-20T03:59:25.522Z] NULL	1
[2020-04-20T03:59:25.522Z] NULL	1
```
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
master

**Comment by crazycs520** [comment]
@XuHuaiyu PTAL

**Comment by SunRunAway** [comment]
```
goroutine 231820 [running]:
github.com/pingcap/tidb/util.GetStack(...)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/util/misc.go:72
github.com/pingcap/tidb/executor.recoveryProjection(0xc006caa460, 0x26efb20, 0x406fcd0)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/executor/projection.go:442 +0x90
github.com/pingcap/tidb/executor.(*projectionWorker).run.func1(0xc002cb3f88, 0xc004abf180)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/executor/projection.go:409 +0x70
panic(0x26efb20, 0x406fcd0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/util/collate.(*binPattern).Compile(0x0, 0x0, 0x0, 0x5c)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/util/collate/bin.go:64 +0x65
github.com/pingcap/tidb/expression.(*builtinLikeSig).vecEvalInt(0xc000d6fa40, 0xc004728000, 0xc0023b9960, 0x0, 0x0)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/expression/builtin_like_vec.go:67 +0x620
github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalInt(0xc003c24c80, 0x2db97a0, 0xc0003a8d00, 0xc004728000, 0xc0023b9960, 0xc002c65710, 0x5)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/expression/scalar_function.go:51 +0x4b
github.com/pingcap/tidb/expression.(*builtinUnaryNotIntSig).vecEvalInt(0xc002b46f20, 0xc004728000, 0xc0023b9960, 0x0, 0x0)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/expression/builtin_op_vec.go:565 +0x84
github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalInt(0xc003c24cd0, 0x2db97a0, 0xc0003a8d00, 0xc004728000, 0xc0023b9960, 0x0, 0x0)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/expression/scalar_function.go:51 +0x4b
github.com/pingcap/tidb/expression.evalOneVec(0x2db97a0, 0xc0003a8d00, 0x2de8780, 0xc003c24cd0, 0xc004728000, 0xc004728050, 0x10, 0x0, 0x0)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/expression/chunk_executor.go:123 +0x459
github.com/pingcap/tidb/expression.(*defaultEvaluator).run(0xc004abef80, 0x2db97a0, 0xc0003a8d00, 0xc004728000, 0xc004728050, 0x0, 0x0)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/expression/evaluator.go:51 +0x3be
github.com/pingcap/tidb/expression.(*EvaluatorSuite).Run(0xc006caa270, 0x2db97a0, 0xc0003a8d00, 0xc004728000, 0xc004728050, 0x364, 0xc0047a4fb8)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/expression/evaluator.go:123 +0xc9
github.com/pingcap/tidb/executor.(*projectionWorker).run(0xc004abf180, 0x2d7fea0, 0xc001af5620)
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/executor/projection.go:426 +0x17b
created by github.com/pingcap/tidb/executor.(*ProjectionExec).prepare
	/home/jenkins/agent/workspace/tikv_ghpr_integration-copr-test/tidb/executor/projection.go:267 +0x7ac

```

**Comment by SunRunAway** [comment]
@fzhedu maybe #16600 can fix this?

**Comment by fzhedu** [comment]
> @fzhedu maybe #16600 can fix this?

maybe, but the error are not the same.
