### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [recovered]

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#16597]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
[2020-04-20T04:24:49.469Z] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[2020-04-20T04:24:49.469Z] 	panic: runtime error: invalid memory address or nil pointer dereference
[2020-04-20T04:24:49.469Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1458ba6]
[2020-04-20T04:24:49.469Z] 
[2020-04-20T04:24:49.469Z] goroutine 716 [running]:
[2020-04-20T04:24:49.469Z] github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1(0xc00426ac80, 0xc000f47050, 0x3706220, 0xc000054098)
[2020-04-20T04:24:49.469Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/executor/adapter.go:297 +0x53a
[2020-04-20T04:24:49.469Z] panic(0x28e5c00, 0x4a8f6c0)
[2020-04-20T04:24:49.469Z] 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
[2020-04-20T04:24:49.469Z] github.com/pingcap/tipb/go-tipb.(*Expr).Size(0x0, 0x144dd24)
[2020-04-20T04:24:49.469Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/pkg/mod/github.com/pingcap/tipb@v0.0.0-20200212061130-c4d518eb1d60/go-tipb/expression.pb.go:2152 +0x26
[2020-04-20T04:24:49.469Z] github.com/pingcap/tipb/go-tipb.(*Selection).Size(0xc00375ef50, 0x1)
[2020-04-20T04:24:49.469Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/pkg/mod/github.com/pingcap/tipb@v0.0.0-20200212061130-c4d518eb1d60/go-tipb/executor.pb.go:970 +0x5d
[2020-04-20T04:24:49.469Z] github.com/pingcap/tipb/go-tipb.(*Executor).Size(0xc004a1eba0, 0x1)
[2020-04-20T04:24:49.469Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/pkg/mod/github.com/pingcap/tipb@v0.0.0-20200212061130-c4d518eb1d60/go-tipb/executor.pb.go:902 +0x1d8
[2020-04-20T04:24:49.469Z] github.com/pingcap/tipb/go-tipb.(*DAGRequest).Size(0xc003b9d680, 0xc003b88900)
[2020-04-20T04:24:49.469Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/pkg/mod/github.com/pingcap/tipb@v0.0.0-20200212061130-c4d518eb1d60/go-tipb/select.pb.go:1111 +0x66
[2020-04-20T04:24:49.469Z] github.com/pingcap/tipb/go-tipb.(*DAGRequest).Marshal(0xc003b9d680, 0x1b, 0xc0003467e0, 0x7fbc63aea578, 0xc0003467e0, 0xc003b88901)
[2020-04-20T04:24:49.469Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/pkg/mod/github.com/pingcap/tipb@v0.0.0-20200212061130-c4d518eb1d60/go-tipb/select.pb.go:751 +0x2f
[2020-04-20T04:24:49.469Z] github.com/pingcap/tidb/distsql.(*RequestBuilder).SetDAGRequest(0xc003b88900, 0xc003b9d680, 0x1)
[2020-04-20T04:24:49.469Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/distsql/request_builder.go:81 +0x55
[2020-04-20T04:24:49.469Z] github.com/pingcap/tidb/executor.(*TableReaderExecutor).buildResp(0xc0041f06e0, 0x3706220, 0xc000054098, 0xc005b38808, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0)
[2020-04-20T04:24:49.469Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/executor/table_reader.go:198 +0xa9
[2020-04-20T04:24:49.469Z] github.com/pingcap/tidb/executor.(*TableReaderExecutor).Open(0xc0041f06e0, 0x3706220, 0xc000054098, 0x0, 0x0)
[2020-04-20T04:24:49.469Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/executor/table_reader.go:137 +0x429
[2020-04-20T04:24:49.469Z] github.com/pingcap/tidb/executor.(*baseExecutor).Open(0xc003d1fe60, 0x3706220, 0xc000054098, 0xc00424fd00, 0x36c3880)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/executor/executor.go:141 +0x7a
[2020-04-20T04:24:49.470Z] github.com/pingcap/tidb/executor.(*ProjectionExec).Open(0xc003d1fe60, 0x3706220, 0xc000054098, 0x0, 0x0)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/executor/projection.go:83 +0x45
[2020-04-20T04:24:49.470Z] github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc00426ac80, 0x3706220, 0xc000054098, 0x0, 0x0, 0x0, 0x0)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/executor/adapter.go:330 +0x1a3
[2020-04-20T04:24:49.470Z] github.com/pingcap/tidb/session.runStmt(0x3706220, 0xc000054098, 0x374bb20, 0xc00424fd00, 0x370d9e0, 0xc00426ac80, 0x0, 0x0, 0x0, 0x0)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/session/tidb.go:276 +0x304
[2020-04-20T04:24:49.470Z] github.com/pingcap/tidb/session.(*session).executeStatement(0xc00424fd00, 0x3706220, 0xc000054098, 0x0, 0x370d260, 0xc001012f70, 0x370d9e0, 0xc00426ac80, 0x0, 0x0, ...)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/session/session.go:1040 +0xb5
[2020-04-20T04:24:49.470Z] github.com/pingcap/tidb/session.(*session).execute(0xc00424fd00, 0x3706220, 0xc000054098, 0xc005f41100, 0x75, 0x56, 0xfcc032, 0x5, 0x7fbc63c661f0, 0x0)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/session/session.go:1240 +0x78d
[2020-04-20T04:24:49.470Z] github.com/pingcap/tidb/session.(*session).Execute(0xc00424fd00, 0x3706220, 0xc000054098, 0xc005f41100, 0x75, 0x0, 0x0, 0x0, 0x0, 0x0)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/session/session.go:1083 +0xdb
[2020-04-20T04:24:49.470Z] github.com/pingcap/tidb/ddl/util.loadDeleteRangesFromTable(0x374bb20, 0xc00424fd00, 0x2bc36f2, 0xf, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/ddl/util/util.go:66 +0x197
[2020-04-20T04:24:49.470Z] github.com/pingcap/tidb/ddl/util.LoadDeleteRanges(...)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/ddl/util/util.go:56
[2020-04-20T04:24:49.470Z] github.com/pingcap/tidb/ddl.(*delRange).doDelRangeWork(0xc0034baa00, 0x0, 0x0)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/ddl/delete_range.go:170 +0x36d
[2020-04-20T04:24:49.470Z] github.com/pingcap/tidb/ddl.(*delRange).startEmulator(0xc0034baa00)
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/ddl/delete_range.go:141 +0x146
[2020-04-20T04:24:49.470Z] created by github.com/pingcap/tidb/ddl.(*delRange).start
[2020-04-20T04:24:49.470Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test@2/go/src/github.com/pingcap/tidb/ddl/delete_range.go:117 +0x6a
[2020-04-20T04:24:49.470Z] FAIL	github.com/pingcap/tidb/expression	2.835s
```

https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/33141/nodes/87/log/?start=0

**Comment by SunRunAway** [comment]
@qw4990 Would you like to take a look?

**Comment by qw4990** [comment]
> @qw4990 Would you like to take a look?

I will investigate this problem this afternoon.
