### ISSUE TITLE
txn: pessimistic statement execution panic panicked

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#17006]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

Execute statement `insert into xxx select from`

### 2. What did you expect to see?
Execution results ok

### 3. What did you see instead?
tidb panicked
stack
```
"connection running loop panic"] [conn=1] [lastSQL="insert into sbtest2 select * from sbtest1"] [err="runtime error: index out of range [0] with length 0"] [stack="goroutine 854 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x3667a60, 0xc000e1b470, 0xc000c148f0)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:660 +0xee
panic(0x2f79fe0, 0xc023cd2bc0)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1(0xc000dcdf80, 0xc000e90cc8, 0x3667a60, 0xc000e1b470)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:292 +0x53a
panic(0x2f79fe0, 0xc023cd2bc0)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/store/tikv.preSplitAndScatterIn2PC(0x36679e0, 0xc0000e2000, 0xc000522100, 0x2, 0x1, 0x18, 0x0, 0x0, 0x0, 0xc02f328000, ...)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:474 +0xa15
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).doActionOnMutations(0xc023cda000, 0xc000ec2080, 0x365dfa0, 0xc0003e42a0, 0x0, 0x0, 0x0, 0xc02f328000, 0xf4240, 0xf4240, ...)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:451 +0x51a
github.com/pingcap/tidb/store/tikv.(*twoPhaseCommitter).pessimisticLockMutations(...)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/store/tikv/2pc.go:1200
github.com/pingcap/tidb/store/tikv.(*tikvTxn).LockKeys(0xc000f18630, 0x3667a60, 0xc000e1b470, 0xc0003e42a0, 0xc02dc44000, 0xf4240, 0xf4240, 0x0, 0x0)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/store/tikv/txn.go:388 +0x467
github.com/pingcap/tidb/executor.(*ExecStmt).handlePessimisticDML(0xc000dcdf80, 0x3667a60, 0xc000e1b470, 0x3671260, 0xc000ee4a20, 0x29, 0x5c7b48c92180004)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:552 +0x42a
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc000dcdf80, 0x3667a60, 0xc000e1b470, 0x3671260, 0xc000ee4a20, 0x5120001, 0x3, 0x0, 0xc000e90b58, 0x115ef67, ...)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:387 +0xc7
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc000dcdf80, 0x3667a60, 0xc000e1b470, 0x0, 0x0, 0x0, 0x0)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:357 +0x3c7
github.com/pingcap/tidb/session.runStmt(0x3667a60, 0xc000e1b470, 0x36a9da0, 0xc000c24600, 0x3670f20, 0xc000dcdf80, 0x0, 0x0, 0x0, 0x0)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/session/tidb.go:276 +0x304
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc000c24600, 0x3667a60, 0xc000e1b470, 0x3670460, 0xc000f0fb80, 0x0, 0x0, 0x0, 0x0)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/session/session.go:1163 +0x7e0
github.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt(0xc000e1b770, 0x3667a60, 0xc000e1b470, 0x3670460, 0xc000f0fb80, 0x8, 0x8, 0xc000e91300, 0x11ce7c8)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/server/driver_tidb.go:248 +0x65
github.com/pingcap/tidb/server.(*clientConn).handleStmt(0xc000c148f0, 0x3667a60, 0xc000e1b470, 0x3670460, 0xc000f0fb80, 0xc00118a801, 0x0, 0x0)
/home/jenkins/agent/workspace/tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1294 +0x8e
github.com/pingcap/tidb/server.(*clientConn).handleQuery
```

This is because when doing **pessimistic lock keys**, the `committerMutations` struct has only elements in `keys` array but nothing in `values` array, accessing `values` array leads to panic 

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

nightly with
```
["Git Commit Hash"=d367a0101e4555fda76f8d33258a6d903991741a] ["Git Branch"=master]
```

**Comment by cfzjywxk** [comment]
@coocood @jackysp @tiancaiamao   The `pre-split` logic  seems incompatible with pessimistic locks logic, we need to fix this

**Comment by cfzjywxk** [comment]
@zyguan  I think we need to daily run some large tests and collect results, we could trace the result is ok and the resource usage is expected
