### ISSUE TITLE
index value in RPCContext maybe invalid after sending fail

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#18169]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- send a kv/tiflash request and it take very long time to execute
- before request return, region has change and decrese peer count in region (for example: offline a tiflash learner)
- reqeust return send fail and go to onSendFail

### 2. What did you expect to see? (Required)

detect region info change and no panic

### 3. What did you see instead (Required)

```
panic: runtime error: index out of range [4] with length 4

goroutine 3426550709 [running]:
github.com/pingcap/tidb/store/tikv.(*RegionCache).OnSendFail(0xc0001e57a0, 0xc03ca8bc80, 0xc03973c6e0, 0xc19b650000, 0x36720c0, 0xc07a57e160)
        /home/jenkins/agent/workspace/tidb_v4.0.0/go/src/github.com/pingcap/tidb/store/tikv/region_cache.go:523 +0x8ad
github.com/pingcap/tidb/store/tikv.(*RegionBatchRequestSender).onSendFail(0xc085d4bcc0, 0xc03ca8bc80, 0xc03973c6e0, 0x36720c0, 0xc07a57e160, 0x0, 0x0)
        /home/jenkins/agent/workspace/tidb_v4.0.0/go/src/github.com/pingcap/tidb/store/tikv/region_request.go:105 +0x19b
github.com/pingcap/tidb/store/tikv.(*RegionBatchRequestSender).sendReqToAddr(0xc085d4bcc0, 0xc03ca8bc80, 0xc07f1c0000, 0x101, 0x200, 0xc079bc0500, 0x34630b8a000, 0x200, 0x0, 0x1145cc6, ...)
        /home/jenkins/agent/workspace/tidb_v4.0.0/go/src/github.com/pingcap/tidb/store/tikv/region_request.go:85 +0x179
github.com/pingcap/tidb/store/tikv.(*batchCopIterator).handleTaskOnce(0xc158f18000, 0x36c5420, 0xc38dfcff20, 0xc03ca8bc80, 0xc01eb939e0, 0x0, 0xc003f19fb8, 0x1ffe454, 0x0, 0x1163ac1)
        /home/jenkins/agent/workspace/tidb_v4.0.0/go/src/github.com/pingcap/tidb/store/tikv/batch_coprocessor.go:339 +0x78c
github.com/pingcap/tidb/store/tikv.(*batchCopIterator).handleTask(0xc158f18000, 0x36c5420, 0xc38dfcff20, 0xc03ca8bc80, 0xc01eb939e0)
        /home/jenkins/agent/workspace/tidb_v4.0.0/go/src/github.com/pingcap/tidb/store/tikv/batch_coprocessor.go:283 +0x16c
created by github.com/pingcap/tidb/store/tikv.(*batchCopIterator).run
        /home/jenkins/agent/workspace/tidb_v4.0.0/go/src/github.com/pingcap/tidb/store/tikv/batch_coprocessor.go:223 +0x72
```

### 4. Affected version (Required)

v3.0.0, v4.0.0

### 5. Root Cause Analysis

handle send fail with index cache in context.

but region real store info can be changed after sending request but before receive sending fail

**Comment by lysu** [comment]
this is false alert...

it never happened, because  regionID is  id + confver + ver, so
https://github.com/pingcap/tidb/pull/18170/files#diff-708f6242b27e2b7bcf0e905e9b0eacf2L555 
will get history version region and store and never out of index...maybe some other question lead that..
