### ISSUE TITLE
VALUES statement panics

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb#21486]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Execute the [VALUES statement](https://dev.mysql.com/doc/refman/8.0/en/values.html)

```sql
values row(1);
```

### 2. What did you expect to see? (Required)

```
mysql> values row(1);
+----------+
| column_0 |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

The connection thread panics.

```
mysql> values row(1);
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
```

```
[2020/12/04 01:29:52.427 +08:00] [ERROR] [conn.go:733] ["connection running loop panic"] [conn=2199023255555] [lastSQL="values row(1)"] [err="runtime error: invalid memory address or nil pointer dereference"] [stack="goroutine 607 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x3721180, 0xc0100e0960, 0xc00ffa9000)
	~/tidb/server/conn.go:731 +0xf5
panic(0x2c62d40, 0x2906660)
	c:/go/src/runtime/panic.go:969 +0x174
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect(0xc0100c7760, 0x3721180, 0xc0103b91d0, 0xc0104a4400, 0x3770b80, 0xc0100fda00, 0x0, 0x0)
	~/tidb/planner/core/logical_plan_builder.go:2836 +0x25d
github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build(0xc0100c7760, 0x3721180, 0xc0103b91d0, 0x373e600, 0xc0104a4400, 0xc0100c7760, 0xc0002db1d0, 0x2, 0x2)
	~/tidb/planner/core/planbuilder.go:605 +0xb77
github.com/pingcap/tidb/planner.optimize(0x3721180, 0xc0103b91d0, 0x3771680, 0xc00ffa9100, 0x373e600, 0xc0104a4400, 0x3767500, 0xc00f875470, 0x0, 0x0, ...)
	~/tidb/planner/optimize.go:229 +0x1f0
github.com/pingcap/tidb/planner.Optimize(0x3721180, 0xc0103b91d0, 0x3771680, 0xc00ffa9100, 0x373e600, 0xc0104a4400, 0x3767500, 0xc00f875470, 0x0, 0x0, ...)
	~/tidb/planner/optimize.go:122 +0x498
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc01048edd8, 0x3721180, 0xc0103b91d0, 0x3746700, 0xc0104a4400, 0x0, 0x0, 0x0)
	~/tidb/executor/compiler.go:62 +0x304
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc00ffa9100, 0x3721180, 0xc0103b9020, 0x3746700, 0xc0104a4400, 0x0, 0x0, 0x0, 0x0)
	~/tidb/session/session.go:1243 +0x29c
github.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt(0xc0100e0e10, 0x3721180, 0xc0103b9020, 0x3746700, 0xc0104a4400, 0xc0101a61e0, 0x3721180, 0xc0103b9020, 0x4e9a610)
	~/tidb/server/driver_tidb.go:212 +0x6f
github.com/pingcap/tidb/server.(*clientConn).handleStmt(0xc00ffa9000, 0x3721180, 0xc0103b9020, 0x3746700, 0xc0104a4400, 0x4e9a610, 0x0, 0x0, 0x1, 0x0, ...)
	~/tidb/server/conn.go:1559 +0x140
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc00ffa9000, 0x37210c0, 0xc01045c780, 0xc0105972b1, 0xd, 0x0, 0x0)
	~/tidb/server/conn.go:1451 +0x4a2
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc00ffa9000, 0x37210c0, 0xc01045c780, 0xc0105972b0, 0xe, 0xd, 0x0, 0x0)
	~/tidb/server/conn.go:1027 +0x69d
github.com/pingcap/tidb/server.(*clientConn).Run(0xc00ffa9000, 0x3721180, 0xc0100e0960)
	~/tidb/server/conn.go:792 +0x2a3
github.com/pingcap/tidb/server.(*Server).onConn(0xc0005f84e0, 0xc00ffa9000)
	~/tidb/server/server.go:459 +0xa9e
created by github.com/pingcap/tidb/server.(*Server).Run
	~/tidb/server/server.go:362 +0x89b
"]
```

### 4. What is your TiDB version? (Required)

e33b37789c616d7b7c997748cdd7eac6d6ec835c

```
Release Version: v4.0.0-beta.2-1722-ge33b37789
Edition: Community
Git Commit Hash: e33b37789c616d7b7c997748cdd7eac6d6ec835c
Git Branch: master
UTC Build Time: 2020-12-03 17:27:39
GoVersion: go1.14.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by tisonkun** [comment]
on master d05b6f4c711664fae2df842fac557ede45e6cbfd the stack changes to

```
[planner:1051]Unknown table ''
github.com/pingcap/errors.AddStack
	/Users/tison/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/errors.go:174
github.com/pingcap/errors.(*Error).GenWithStackByArgs
	/Users/tison/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/normalize.go:159
github.com/pingcap/tidb/planner/core.(*PlanBuilder).unfoldWildStar
	/Users/tison/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:3115
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect
	/Users/tison/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:3443
github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build
	/Users/tison/go/src/github.com/pingcap/tidb/planner/core/planbuilder.go:657
github.com/pingcap/tidb/planner.optimize
	/Users/tison/go/src/github.com/pingcap/tidb/planner/optimize.go:234
github.com/pingcap/tidb/planner.Optimize
	/Users/tison/go/src/github.com/pingcap/tidb/planner/optimize.go:124
github.com/pingcap/tidb/executor.(*Compiler).Compile
	/Users/tison/go/src/github.com/pingcap/tidb/executor/compiler.go:63
github.com/pingcap/tidb/session.(*session).ExecuteStmt
	/Users/tison/go/src/github.com/pingcap/tidb/session/session.go:1601
github.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt
	/Users/tison/go/src/github.com/pingcap/tidb/server/driver_tidb.go:218
github.com/pingcap/tidb/server.(*clientConn).handleStmt
	/Users/tison/go/src/github.com/pingcap/tidb/server/conn.go:1809
github.com/pingcap/tidb/server.(*clientConn).handleQuery
	/Users/tison/go/src/github.com/pingcap/tidb/server/conn.go:1681
github.com/pingcap/tidb/server.(*clientConn).dispatch
	/Users/tison/go/src/github.com/pingcap/tidb/server/conn.go:1215
github.com/pingcap/tidb/server.(*clientConn).Run
	/Users/tison/go/src/github.com/pingcap/tidb/server/conn.go:978
github.com/pingcap/tidb/server.(*Server).onConn
	/Users/tison/go/src/github.com/pingcap/tidb/server/server.go:482
runtime.goexit
	/usr/local/Cellar/go/1.16/libexec/src/runtime/asm_amd64.s:1371
```

**Comment by SunRunAway** [comment]
I try to use `values` to find the max value of a row, but it seems  not work on MySQL 8.
@dveeden do you know if it is a bug?

```
mysql> select * from mytable;
+----+----+----+----+
| ID | a  | b  | c  |
+----+----+----+----+
|  1 | a1 | b1 | c1 |
|  2 | a2 | b2 | c2 |
+----+----+----+----+
2 rows in set (0.00 sec)

mysql> select ID, (select max(col1)    from (values row(a), row(b), row(c)) as x(col1)) as max from mytable;
+----+------+
| ID | max  |
+----+------+
|  1 | c1   |
|  2 | NULL |
+----+------+
2 rows in set (0.00 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.31    |
+-----------+
1 row in set (0.00 sec)
```

**Comment by dveeden** [comment]
This works:
```
sql> SELECT *, MAX(column_0) OVER () FROM (VALUES ROW(1,2,3),ROW(10,20,30)) a;
+----------+----------+----------+-----------------------+
| column_0 | column_1 | column_2 | MAX(column_0) OVER () |
+----------+----------+----------+-----------------------+
|        1 |        2 |        3 |                    10 |
|       10 |       20 |       30 |                    10 |
+----------+----------+----------+-----------------------+
2 rows in set (0.0005 sec)
```

**Comment by dveeden** [comment]
```
sql> select ID, (select max(col1)    from (values row(a), row(b), row(c)) as x(col1)) as max from mytable;
+----+------+
| ID | max  |
+----+------+
|  1 | c1   |
|  2 | NULL |
+----+------+
2 rows in set (0.0016 sec)

sql> select ID, (select GROUP_CONCAT(col1)    from (values row(a), row(b), row(c)) as x(col1)) as max from mytable;
+----+----------+
| ID | max      |
+----+----------+
|  1 | a1,b1,c1 |
|  2 | NULL     |
+----+----------+
2 rows in set (0.0015 sec)
```

So the `MAX()` of `['a1','b1','c1']` is indeed c1.

**Comment by dveeden** [comment]
Note also this:
```
sql> select ID, (select GROUP_CONCAT(col1)    from (values row(a), row(b), row(c)) as x(col1)) as max from mytable WHERE ID=2;
+----+----------+
| ID | max      |
+----+----------+
|  2 | a2,b2,c2 |
+----+----------+
1 row in set (0.0005 sec)
```

This is a bit of a weird dependent subquery, not sure it makes much sense to me.

**Comment by SunRunAway** [comment]
> ```
> sql> select ID, (select max(col1)    from (values row(a), row(b), row(c)) as x(col1)) as max from mytable;
> +----+------+
> | ID | max  |
> +----+------+
> |  1 | c1   |
> |  2 | NULL |
> +----+------+
> 2 rows in set (0.0016 sec)
> 
> sql> select ID, (select GROUP_CONCAT(col1)    from (values row(a), row(b), row(c)) as x(col1)) as max from mytable;
> +----+----------+
> | ID | max      |
> +----+----------+
> |  1 | a1,b1,c1 |
> |  2 | NULL     |
> +----+----------+
> 2 rows in set (0.0015 sec)
> ```
> 
> So the `MAX()` of `['a1','b1','c1']` is indeed c1.

I do not get why the second row of 'max' is NULL. 
Postgres seems do it right: https://dbfiddle.uk/nbpDA-Tc

**Comment by SunRunAway** [comment]
I sent a bug to MySQL team and it is verified: https://bugs.mysql.com/bug.php?id=110076

**Comment by dveeden** [comment]
Another small difference with MySQL:

MySQL:
```
sql> CREATE TABLE t1(id INT PRIMARY KEY AUTO_INCREMENT);
Query OK, 0 rows affected (0.0535 sec)

sql> INSERT INTO t1 VALUES ROW();
Query OK, 1 row affected (0.0199 sec)

sql> SELECT VERSION();
+-----------+
| VERSION() |
+-----------+
| 8.1.0     |
+-----------+
1 row in set (0.0006 sec)
```

TiDB:
```
sql> CREATE TABLE t1(id INT PRIMARY KEY AUTO_INCREMENT);
Query OK, 0 rows affected (0.1716 sec)

sql> INSERT INTO t1 VALUES ROW();
ERROR: 1051 (42S02): Unknown table ''

sql> SELECT VERSION();
+--------------------+
| VERSION()          |
+--------------------+
| 5.7.25-TiDB-v7.2.0 |
+--------------------+
1 row in set (0.0012 sec)
```

**Comment by kennytm** [comment]
`TABLE t` seems to work fine on TiDB v8.1 (but perhaps needs more tests to verify), and `VALUES` no longer crash just returns an error.

Updated the description to reflect the current development.

**Comment by dveeden** [comment]
```
mysql-9.2.0> WITH t(v) AS (VALUES ROW('foo'), ROW('bar')) SELECT * FROM t;
+-----+
| v   |
+-----+
| foo |
| bar |
+-----+
2 rows in set (0.00 sec)

mysql-9.2.0> VALUES ROW('foo'), ROW('bar');
+----------+
| column_0 |
+----------+
| foo      |
| bar      |
+----------+
2 rows in set (0.00 sec)
```

```
mysql-8.0.11-TiDB-v8.5.0> WITH t(v) AS (VALUES ROW('foo'), ROW('bar')) SELECT * FROM t;
ERROR 1051 (42S02): Unknown table ''
mysql-8.0.11-TiDB-v8.5.0> VALUES ROW('foo'), ROW('bar');
ERROR 1051 (42S02): Unknown table ''
```
