### ISSUE TITLE
schema() Function schema is not implemented.

### ISSUE THREAD

**Issue by hyj0** [pingcap/tidb#2172]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
SELECT schema()

2. What did you expect to see?
test

3. What did you see instead?
[HY000][1105] Function schema is not implemented.

4. What version of Go are you using (`go version`)?
go version go1.7.1 windows/amd64

**Comment by shenli** [comment]
@hyj0 Thanks for your feedback. It will be fixed soon.

**Comment by shenli** [comment]
@hyj0 Please try the latest master code. It is already fixed.

**Comment by hyj0** [comment]
use msyql client 
$ ./bin/mysql --version
  Ver 14.14 Distrib 5.6.28, for Win32 (AMD64)
mysql> SELECT  schema();
+----------+
| schema() |
+----------+
|     test |
+----------+
that's ok
but,  DataGrid 2016.2.1 with Jdbc-5.1.35
SELECT  schema();
<failed to load>
java.sql.SQLException: Bad format for BigDecimal 'test' in column 1.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
	at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:4505)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.tryGetObject(RemoteResultSetImpl.java:1271)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.getObject(RemoteResultSetImpl.java:1249)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.getCurrentRow(RemoteResultSetImpl.java:1233)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.getObjects(RemoteResultSetImpl.java:1212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

and in python  with MySQLdb 1.2.3
SELECT  schema();
decimal.InvalidOperation: Invalid literal for Decimal: 'test'

**Comment by shenli** [comment]
@hyj0 We will fix it now.

**Comment by shenli** [comment]
@hyj0 It will be fixed in this PR: https://github.com/pingcap/tidb/pull/2181

**Comment by hyj0** [comment]
well, I use jdbc-5.1.38 test it, it's no wrong,  it seems Datagrid's bug.

**Comment by shenli** [comment]
@hyj0 Please try the latest master code.

**Comment by hyj0** [comment]
all ok,thanks for your quickly fix. it's some thing wrong in  character encode before?

**Comment by shenli** [comment]
@hyj0 It is related to the field type. We return the result of schema() in string but set a wrong field type.   In this [PR](https://github.com/pingcap/tidb/pull/2181), we set it to the right type.

**Comment by shenli** [comment]
@hyj0 If everything is OK, I will close the issue.

**Comment by hyj0** [comment]
yes, all test ok, thanks again
