### ISSUE TITLE
TIDB PD keeps recycling

### ISSUE THREAD

**Issue by itisslizz** [pingcap/tidb#22429]
## Bug Report

Tidb PD pod keeps recycling.

### 1. Minimal reproduce step (Required)

Start tidb pd.

### 2. What did you expect to see? (Required)

tidb pd should start successfull

### 3. What did you see instead (Required)
tidb pd fails to start with the log entries below.

### 4. What is your TiDB version? (Required)
v4.0.4

Logs:

Name:      tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc
Address 1: 10.240.19.181 tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc.cluster.local
nslookup domain tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc.svc success
starting pd-server ...
/pd-server --data-dir=/var/lib/pd --name=tidb-pd-0 --peer-urls=http://0.0.0.0:2380 --advertise-peer-urls=http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2380 --client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2379 --config=/etc/pd/pd.toml 
[2021/01/18 14:14:30.344 +00:00] [INFO] [util.go:41] ["Welcome to Placement Driver (PD)"]
[2021/01/18 14:14:30.344 +00:00] [INFO] [util.go:42] [PD] [release-version=v4.0.4]
[2021/01/18 14:14:30.344 +00:00] [INFO] [util.go:43] [PD] [edition=Community]
[2021/01/18 14:14:30.344 +00:00] [INFO] [util.go:44] [PD] [git-hash=096ab27038530fcf674a9f9d872609ec2656ee73]
[2021/01/18 14:14:30.344 +00:00] [INFO] [util.go:45] [PD] [git-branch=heads/refs/tags/v4.0.4]
[2021/01/18 14:14:30.344 +00:00] [INFO] [util.go:46] [PD] [utc-build-time="2020-07-29 03:13:19"]
[2021/01/18 14:14:30.344 +00:00] [INFO] [metricutil.go:81] ["disable Prometheus push client"]
[2021/01/18 14:14:30.344 +00:00] [INFO] [server.go:211] ["PD Config"] [config="{\"client-urls\":\"http://0.0.0.0:2379\",\"peer-urls\":\"http://0.0.0.0:2380\",\"advertise-client-urls\":\"http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2379\",\"advertise-peer-urls\":\"http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2380\",\"name\":\"tidb-pd-0\",\"data-dir\":\"/var/lib/pd\",\"force-new-cluster\":false,\"enable-grpc-gateway\":true,\"initial-cluster\":\"tidb-pd-0=http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2380\",\"initial-cluster-state\":\"new\",\"join\":\"\",\"lease\":3,\"log\":{\"level\":\"info\",\"format\":\"text\",\"disable-timestamp\":false,\"file\":{\"filename\":\"\",\"max-size\":0,\"max-days\":0,\"max-backups\":0},\"development\":false,\"disable-caller\":false,\"disable-stacktrace\":false,\"disable-error-verbose\":true,\"sampling\":null},\"tso-save-interval\":\"3s\",\"metric\":{\"job\":\"tidb-pd-0\",\"address\":\"\",\"interval\":\"15s\"},\"schedule\":{\"max-snapshot-count\":3,\"max-pending-peer-count\":16,\"max-merge-region-size\":20,\"max-merge-region-keys\":200000,\"split-merge-interval\":\"1h0m0s\",\"enable-one-way-merge\":\"false\",\"enable-cross-table-merge\":\"false\",\"patrol-region-interval\":\"100ms\",\"max-store-down-time\":\"30m0s\",\"leader-schedule-limit\":4,\"leader-schedule-policy\":\"count\",\"region-schedule-limit\":2048,\"replica-schedule-limit\":64,\"merge-schedule-limit\":8,\"hot-region-schedule-limit\":4,\"hot-region-cache-hits-threshold\":3,\"store-limit\":null,\"tolerant-size-ratio\":0,\"low-space-ratio\":0.8,\"high-space-ratio\":0.7,\"scheduler-max-waiting-operator\":5,\"enable-remove-down-replica\":\"true\",\"enable-replace-offline-replica\":\"true\",\"enable-make-up-replica\":\"true\",\"enable-remove-extra-replica\":\"true\",\"enable-location-replacement\":\"true\",\"enable-debug-metrics\":\"false\",\"schedulers-v2\":[{\"type\":\"balance-region\",\"args\":null,\"disable\":false,\"args-payload\":\"\"},{\"type\":\"balance-leader\",\"args\":null,\"disable\":false,\"args-payload\":\"\"},{\"type\":\"hot-region\",\"args\":null,\"disable\":false,\"args-payload\":\"\"},{\"type\":\"label\",\"args\":null,\"disable\":false,\"args-payload\":\"\"}],\"schedulers-payload\":null,\"store-limit-mode\":\"manual\"},\"replication\":{\"max-replicas\":3,\"location-labels\":\"region,zone,rack,host\",\"strictly-match-label\":\"false\",\"enable-placement-rules\":\"false\"},\"pd-server\":{\"use-region-storage\":\"true\",\"max-gap-reset-ts\":\"24h0m0s\",\"key-type\":\"table\",\"runtime-services\":\"\",\"metric-storage\":\"\",\"dashboard-address\":\"auto\"},\"cluster-version\":\"0.0.0\",\"quota-backend-bytes\":\"8GiB\",\"auto-compaction-mode\":\"periodic\",\"auto-compaction-retention-v2\":\"1h\",\"TickInterval\":\"500ms\",\"ElectionInterval\":\"3s\",\"PreVote\":true,\"security\":{\"cacert-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"cert-allowed-cn\":null},\"label-property\":null,\"WarningMsgs\":null,\"DisableStrictReconfigCheck\":false,\"HeartbeatStreamBindInterval\":\"1m0s\",\"LeaderPriorityCheckInterval\":\"1m0s\",\"dashboard\":{\"tidb-cacert-path\":\"\",\"tidb-cert-path\":\"\",\"tidb-key-path\":\"\",\"public-path-prefix\":\"\",\"internal-proxy\":false,\"enable-telemetry\":true},\"replication-mode\":{\"replication-mode\":\"majority\",\"dr-auto-sync\":{\"label-key\":\"\",\"primary\":\"\",\"dr\":\"\",\"primary-replicas\":0,\"dr-replicas\":0,\"wait-store-timeout\":\"1m0s\",\"wait-sync-timeout\":\"1m0s\"}}}"]
[2021/01/18 14:14:30.347 +00:00] [INFO] [server.go:184] ["register REST path"] [path=/pd/api/v1]
[2021/01/18 14:14:30.347 +00:00] [INFO] [server.go:184] ["register REST path"] [path=/swagger/]
[2021/01/18 14:14:30.348 +00:00] [INFO] [server.go:184] ["register REST path"] [path=/dashboard/api/]
[2021/01/18 14:14:30.348 +00:00] [INFO] [server.go:184] ["register REST path"] [path=/dashboard/]
[2021/01/18 14:14:30.348 +00:00] [INFO] [etcd.go:117] ["configuring peer listeners"] [listen-peer-urls="[http://0.0.0.0:2380]"]
[2021/01/18 14:14:30.348 +00:00] [INFO] [etcd.go:127] ["configuring client listeners"] [listen-client-urls="[http://0.0.0.0:2379]"]
[2021/01/18 14:14:30.348 +00:00] [INFO] [etcd.go:602] ["pprof is enabled"] [path=/debug/pprof]
[2021/01/18 14:14:30.349 +00:00] [INFO] [etcd.go:299] ["starting an etcd server"] [etcd-version=3.4.3] [git-sha="Not provided (use ./build instead of go build)"] [go-version=go1.13] [go-os=linux] [go-arch=amd64] [max-cpu-set=4] [max-cpu-available=4] [member-initialized=true] [name=tidb-pd-0] [data-dir=/var/lib/pd] [wal-dir=] [wal-dir-dedicated=] [member-dir=/var/lib/pd/member] [force-new-cluster=false] [heartbeat-interval=500ms] [election-timeout=3s] [initial-election-tick-advance=true] [snapshot-count=100000] [snapshot-catchup-entries=5000] [initial-advertise-peer-urls="[http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2380]"] [listen-peer-urls="[http://0.0.0.0:2380]"] [advertise-client-urls="[http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2379]"] [listen-client-urls="[http://0.0.0.0:2379]"] [listen-metrics-urls="[]"] [cors="[*]"] [host-whitelist="[*]"] [initial-cluster=] [initial-cluster-state=new] [initial-cluster-token=] [quota-size-bytes=8589934592] [pre-vote=true] [initial-corrupt-check=false] [corrupt-check-time-interval=0s] [auto-compaction-mode=periodic] [auto-compaction-retention=1h0m0s] [auto-compaction-interval=1h0m0s] [discovery-url=] [discovery-proxy=]
[2021/01/18 14:14:30.352 +00:00] [INFO] [backend.go:79] ["opened backend db"] [path=/var/lib/pd/member/snap/db] [took=2.81941ms]
[2021/01/18 14:14:30.354 +00:00] [INFO] [systime_mon.go:26] ["start system time monitor"]
[2021/01/18 14:14:30.361 +00:00] [INFO] [server.go:443] ["recovered v2 store from snapshot"] [snapshot-index=8400366] [snapshot-size="361 kB"]
[2021/01/18 14:14:30.365 +00:00] [INFO] [kvstore.go:378] ["restored last compact revision"] [meta-bucket-name=meta] [meta-bucket-name-key=finishedCompactRev] [restored-compact-revision=6794750]
[2021/01/18 14:14:30.370 +00:00] [INFO] [server.go:461] ["recovered v3 backend from snapshot"] [backend-size-bytes=1028096] [backend-size="1.0 MB"] [backend-size-in-use-bytes=401408] [backend-size-in-use="401 kB"]
[2021/01/18 14:14:30.433 +00:00] [INFO] [raft.go:506] ["restarting local member"] [cluster-id=ca5510595ab27560] [local-member-id=372e81b2617f9f6b] [commit-index=8436981]
[2021/01/18 14:14:30.437 +00:00] [INFO] [raft.go:1530] ["372e81b2617f9f6b switched to configuration voters=(2213057695153662569 3976258124154642283 7702022707500416731)"]
[2021/01/18 14:14:30.437 +00:00] [INFO] [raft.go:700] ["372e81b2617f9f6b became follower at term 24"]
[2021/01/18 14:14:30.437 +00:00] [INFO] [raft.go:383] ["newRaft 372e81b2617f9f6b [peers: [1eb65c3f9b142a69,372e81b2617f9f6b,6ae314d86c8dfedb], term: 24, commit: 8436981, applied: 8400366, lastindex: 8436982, lastterm: 24]"]
[2021/01/18 14:14:30.437 +00:00] [INFO] [capability.go:76] ["enabled capabilities for version"] [cluster-version=3.4]
[2021/01/18 14:14:30.437 +00:00] [INFO] [cluster.go:256] ["recovered/added member from store"] [cluster-id=ca5510595ab27560] [local-member-id=372e81b2617f9f6b] [recovered-remote-peer-id=1eb65c3f9b142a69] [recovered-remote-peer-urls="[http://tidb-pd-2.tidb-pd-peer.nimbus-preprod.svc:2380]"]
[2021/01/18 14:14:30.437 +00:00] [INFO] [cluster.go:256] ["recovered/added member from store"] [cluster-id=ca5510595ab27560] [local-member-id=372e81b2617f9f6b] [recovered-remote-peer-id=372e81b2617f9f6b] [recovered-remote-peer-urls="[http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2380]"]
[2021/01/18 14:14:30.437 +00:00] [INFO] [cluster.go:256] ["recovered/added member from store"] [cluster-id=ca5510595ab27560] [local-member-id=372e81b2617f9f6b] [recovered-remote-peer-id=6ae314d86c8dfedb] [recovered-remote-peer-urls="[http://tidb-pd-1.tidb-pd-peer.nimbus-preprod.svc:2380]"]
[2021/01/18 14:14:30.437 +00:00] [INFO] [cluster.go:269] ["set cluster version from store"] [cluster-version=3.4]
[2021/01/18 14:14:30.444 +00:00] [INFO] [kvstore.go:378] ["restored last compact revision"] [meta-bucket-name=meta] [meta-bucket-name-key=finishedCompactRev] [restored-compact-revision=6794750]
[2021/01/18 14:14:30.446 +00:00] [WARN] [store.go:1317] ["simple token is not cryptographically signed"]
[2021/01/18 14:14:30.448 +00:00] [INFO] [quota.go:126] ["enabled backend quota"] [quota-name=v3-applier] [quota-size-bytes=8589934592] [quota-size="8.6 GB"]
[2021/01/18 14:14:30.449 +00:00] [INFO] [peer.go:128] ["starting remote peer"] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.449 +00:00] [INFO] [pipeline.go:71] ["started HTTP pipelining with remote peer"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.450 +00:00] [INFO] [stream.go:166] ["started stream writer with remote peer"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.451 +00:00] [INFO] [stream.go:166] ["started stream writer with remote peer"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.451 +00:00] [INFO] [peer.go:134] ["started remote peer"] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.451 +00:00] [INFO] [transport.go:327] ["added remote peer"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=1eb65c3f9b142a69] [remote-peer-urls="[http://tidb-pd-2.tidb-pd-peer.nimbus-preprod.svc:2380]"]
[2021/01/18 14:14:30.451 +00:00] [INFO] [peer.go:128] ["starting remote peer"] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.451 +00:00] [INFO] [stream.go:406] ["started stream reader with remote peer"] [stream-reader-type="stream Message"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.451 +00:00] [INFO] [pipeline.go:71] ["started HTTP pipelining with remote peer"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.451 +00:00] [INFO] [stream.go:406] ["started stream reader with remote peer"] [stream-reader-type="stream MsgApp v2"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.452 +00:00] [INFO] [stream.go:166] ["started stream writer with remote peer"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.452 +00:00] [INFO] [stream.go:166] ["started stream writer with remote peer"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.452 +00:00] [INFO] [peer.go:134] ["started remote peer"] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.452 +00:00] [INFO] [transport.go:327] ["added remote peer"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=6ae314d86c8dfedb] [remote-peer-urls="[http://tidb-pd-1.tidb-pd-peer.nimbus-preprod.svc:2380]"]
[2021/01/18 14:14:30.452 +00:00] [INFO] [stream.go:406] ["started stream reader with remote peer"] [stream-reader-type="stream MsgApp v2"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.452 +00:00] [INFO] [server.go:779] ["starting etcd server"] [local-member-id=372e81b2617f9f6b] [local-server-version=3.4.3] [cluster-id=ca5510595ab27560] [cluster-version=3.4]
[2021/01/18 14:14:30.453 +00:00] [INFO] [server.go:680] ["starting initial election tick advance"] [election-ticks=6]
[2021/01/18 14:14:30.453 +00:00] [INFO] [stream.go:406] ["started stream reader with remote peer"] [stream-reader-type="stream Message"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.455 +00:00] [INFO] [etcd.go:576] ["serving peer traffic"] [address="[::]:2380"]
[2021/01/18 14:14:30.456 +00:00] [INFO] [etcd.go:241] ["now serving peer/client/metrics"] [local-member-id=372e81b2617f9f6b] [initial-advertise-peer-urls="[http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2380]"] [listen-peer-urls="[http://0.0.0.0:2380]"] [advertise-client-urls="[http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2379]"] [listen-client-urls="[http://0.0.0.0:2379]"] [listen-metrics-urls="[]"]
[2021/01/18 14:14:30.458 +00:00] [INFO] [stream.go:250] ["set message encoder"] [from=372e81b2617f9f6b] [to=372e81b2617f9f6b] [stream-type="stream Message"]
[2021/01/18 14:14:30.459 +00:00] [INFO] [peer_status.go:51] ["peer became active"] [peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.459 +00:00] [WARN] [stream.go:277] ["established TCP streaming connection with remote peer"] [stream-writer-type="stream Message"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.458 +00:00] [INFO] [stream.go:250] ["set message encoder"] [from=372e81b2617f9f6b] [to=372e81b2617f9f6b] [stream-type="stream MsgApp v2"]
[2021/01/18 14:14:30.459 +00:00] [INFO] [peer_status.go:51] ["peer became active"] [peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.459 +00:00] [WARN] [stream.go:277] ["established TCP streaming connection with remote peer"] [stream-writer-type="stream MsgApp v2"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.458 +00:00] [INFO] [stream.go:250] ["set message encoder"] [from=372e81b2617f9f6b] [to=372e81b2617f9f6b] [stream-type="stream MsgApp v2"]
[2021/01/18 14:14:30.459 +00:00] [WARN] [stream.go:277] ["established TCP streaming connection with remote peer"] [stream-writer-type="stream MsgApp v2"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.459 +00:00] [INFO] [stream.go:250] ["set message encoder"] [from=372e81b2617f9f6b] [to=372e81b2617f9f6b] [stream-type="stream Message"]
[2021/01/18 14:14:30.459 +00:00] [WARN] [stream.go:277] ["established TCP streaming connection with remote peer"] [stream-writer-type="stream Message"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.459 +00:00] [INFO] [node.go:325] ["raft.node: 372e81b2617f9f6b elected leader 1eb65c3f9b142a69 at term 24"]
[2021/01/18 14:14:30.470 +00:00] [INFO] [stream.go:425] ["established TCP streaming connection with remote peer"] [stream-reader-type="stream MsgApp v2"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.470 +00:00] [INFO] [stream.go:425] ["established TCP streaming connection with remote peer"] [stream-reader-type="stream MsgApp v2"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.470 +00:00] [INFO] [stream.go:425] ["established TCP streaming connection with remote peer"] [stream-reader-type="stream Message"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=6ae314d86c8dfedb]
[2021/01/18 14:14:30.471 +00:00] [INFO] [stream.go:425] ["established TCP streaming connection with remote peer"] [stream-reader-type="stream Message"] [local-member-id=372e81b2617f9f6b] [remote-peer-id=1eb65c3f9b142a69]
[2021/01/18 14:14:30.503 +00:00] [INFO] [server.go:705] ["initialized peer connections; fast-forwarding election ticks"] [local-member-id=372e81b2617f9f6b] [forward-ticks=4] [forward-duration=2s] [election-ticks=6] [election-timeout=3s] [active-remote-members=2]
[2021/01/18 14:14:30.536 +00:00] [INFO] [server.go:2016] ["published local member to cluster through raft"] [local-member-id=372e81b2617f9f6b] [local-member-attributes="{Name:tidb-pd-0 ClientURLs:[http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2379]}"] [request-path=/0/members/372e81b2617f9f6b/attributes] [cluster-id=ca5510595ab27560] [publish-timeout=11s]
[2021/01/18 14:14:30.536 +00:00] [INFO] [server.go:286] ["create etcd v3 client"] [endpoints="[http://tidb-pd-0.tidb-pd-peer.nimbus-preprod.svc:2379]"] [cert="{\"cacert-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"cert-allowed-cn\":null}"]
[2021/01/18 14:14:30.537 +00:00] [INFO] [serve.go:139] ["serving client traffic insecurely; this is strongly discouraged!"] [address="[::]:2379"]
[2021/01/18 14:14:30.547 +00:00] [INFO] [server.go:338] ["init cluster id"] [cluster-id=6867986950444874420]
[2021/01/18 14:14:30.646 +00:00] [INFO] [history_buffer.go:146] ["start from history index"] [start-index=3212543]
[2021/01/18 14:14:30.651 +00:00] [INFO] [server.go:1186] ["server enable region storage"]
[2021/01/18 14:14:30.651 +00:00] [INFO] [server.go:1068] ["start watch leader"] [leader="name:\"tidb-pd-2\" member_id:2213057695153662569 peer_urls:\"http://tidb-pd-2.tidb-pd-peer.nimbus-preprod.svc:2380\" client_urls:\"http://tidb-pd-2.tidb-pd-peer.nimbus-preprod.svc:2379\" "]
[2021/01/18 14:14:30.747 +00:00] [WARN] [leader.go:471] ["required revision has been compacted, use the compact revision"] [required-revision=6727044] [compact-revision=6794750]
[2021/01/18 14:14:30.947 +00:00] [INFO] [client.go:167] ["server starts to synchronize with leader"] [server=tidb-pd-0] [leader=tidb-pd-2] [request-index=3212543]
[2021/01/18 14:14:31.652 +00:00] [INFO] [dbstore.go:44] ["Dashboard initializing local storage file"] [path=/var/lib/pd/dashboard.sqlite.db]
[2021/01/18 14:14:31.659 +00:00] [INFO] [version.go:41] ["TiDB Dashboard started"] [internal-version=2020.07.15.1] [standalone=No] [pd-version=v4.0.4] [build-time="2020-07-29 03:13:19"] [build-git-hash=47f5de8a6992]
[2021/01/18 14:14:31.659 +00:00] [INFO] [manager.go:200] ["Dashboard server is started"]
[2021/01/18 14:14:31.659 +00:00] [INFO] [proxy.go:199] ["start serve requests to remotes"] [endpoint=127.0.0.1:45067] [remotes="[]"]
[2021/01/18 14:14:31.660 +00:00] [INFO] [proxy.go:199] ["start serve requests to remotes"] [endpoint=127.0.0.1:38025] [remotes="[]"]
[2021/01/18 14:14:31.664 +00:00] [INFO] [dynamic_config_manager.go:176] ["Load dynamic config from etcd"] [json="{\"keyvisual\":{\"auto_collection_disabled\":false,\"policy\":\"db\",\"policy_kv_separator\":\"\"},\"profiling\":{\"auto_collection_targets\":null,\"auto_collection_duration_secs\":0,\"auto_collection_interval_secs\":0}}"]
[2021/01/18 14:14:31.677 +00:00] [INFO] [dynamic_config_manager.go:197] ["Save dynamic config to etcd"] [json="{\"keyvisual\":{\"auto_collection_disabled\":false,\"policy\":\"db\",\"policy_kv_separator\":\"\"},\"profiling\":{\"auto_collection_targets\":null,\"auto_collection_duration_secs\":0,\"auto_collection_interval_secs\":0}}"]
[2021/01/18 14:14:31.802 +00:00] [INFO] [manager.go:85] ["Key visual service is started"]
panic: runtime error: index out of range [1] with length 1

goroutine 477 [running]:
github.com/pingcap-incubator/tidb-dashboard/pkg/keyvisual/matrix.(*chunk).Reduce(0xc0088d7900, 0xc009600000, 0x2, 0xc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build_pd_multi_branch_v4.0.4/go/pkg/mod/github.com/pingcap-incubator/tidb-dashboard@v0.0.0-20200715070228-47f5de8a6992/pkg/keyvisual/matrix/axis.go:188 +0x44d
github.com/pingcap-incubator/tidb-dashboard/pkg/keyvisual/matrix.(*Axis).Divide(0xc0088d7a68, 0x2c5b9a0, 0xc00659abe0, 0xc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build_pd_multi_branch_v4.0.4/go/pkg/mod/github.com/pingcap-incubator/tidb-dashboard@v0.0.0-20200715070228-47f5de8a6992/pkg/keyvisual/matrix/axis.go:111 +0x2b9
github.com/pingcap-incubator/tidb-dashboard/pkg/keyvisual/storage.IntoStorageAxis(0xc0090b0000, 0x5bb9, 0x5bb9, 0xc009030a00, 0x5, 0x5, 0x2c5b9a0, 0xc00659abe0, 0x0, 0x0, ...)
	/home/jenkins/agent/workspace/build_pd_multi_branch_v4.0.4/go/pkg/mod/github.com/pingcap-incubator/tidb-dashboard@v0.0.0-20200715070228-47f5de8a6992/pkg/keyvisual/storage/region.go:57 +0x7e
github.com/pingcap-incubator/tidb-dashboard/pkg/keyvisual/storage.CreateStorageAxis(0x2c412e0, 0xc008e8d5e0, 0x2c5b9a0, 0xc00659abe0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build_pd_multi_branch_v4.0.4/go/pkg/mod/github.com/pingcap-incubator/tidb-dashboard@v0.0.0-20200715070228-47f5de8a6992/pkg/keyvisual/storage/region.go:49 +0x271
github.com/pingcap-incubator/tidb-dashboard/pkg/keyvisual/storage.(*Stat).Append(0xc0051c6090, 0x2c412e0, 0xc008e8d5e0, 0xbff983e0f03e2a87, 0xe548211ad, 0x4454860)
	/home/jenkins/agent/workspace/build_pd_multi_branch_v4.0.4/go/pkg/mod/github.com/pingcap-incubator/tidb-dashboard@v0.0.0-20200715070228-47f5de8a6992/pkg/keyvisual/storage/stat.go:256 +0x8d
github.com/pingcap-incubator/tidb-dashboard/pkg/keyvisual/input.(*periodicInput).Background(0xc00588a110, 0x2c47c60, 0xc00650d640, 0xc0051c6090)
	/home/jenkins/agent/workspace/build_pd_multi_branch_v4.0.4/go/pkg/mod/github.com/pingcap-incubator/tidb-dashboard@v0.0.0-20200715070228-47f5de8a6992/pkg/keyvisual/input/periodic.go:55 +0x385
github.com/pingcap-incubator/tidb-dashboard/pkg/keyvisual.newStat.func1.1(0xc0002f57f0, 0x2c22460, 0xc00588a110, 0x2c47c60, 0xc00650d640, 0xc0051c6090)
	/home/jenkins/agent/workspace/build_pd_multi_branch_v4.0.4/go/pkg/mod/github.com/pingcap-incubator/tidb-dashboard@v0.0.0-20200715070228-47f5de8a6992/pkg/keyvisual/service.go:333 +0x8c
created by github.com/pingcap-incubator/tidb-dashboard/pkg/keyvisual.newStat.func1
	/home/jenkins/agent/workspace/build_pd_multi_branch_v4.0.4/go/pkg/mod/github.com/pingcap-incubator/tidb-dashboard@v0.0.0-20200715070228-47f5de8a6992/pkg/keyvisual/service.go:331 +0xab

**Comment by zyguan** [comment]
@breeswish could you please take a look?

**Comment by breeswish** [comment]
Hi, this is a bug that will cause panic when traffic is low. It is fixed in https://github.com/pingcap/tidb-dashboard/pull/773 (v4.0.8). Could you try with this version?

**Comment by itisslizz** [comment]
Hey, we use operator version 1.1.4
which version of the operator would use the 4.0.8 ?
or should we set that manually somewhere in the config?

**Comment by zyguan** [comment]
Hi, @itisslizz , you can upgrade the tidb cluster according to [this doc](https://docs.pingcap.com/tidb-in-kubernetes/stable/upgrade-a-tidb-cluster).

**Comment by breeswish** [comment]
Hi, I'm going to close this issue. Feel free to leave updates if there are still problems. Thanks!
