### ISSUE TITLE
BenchmarkWindowFunctionsWithSlidingWindow failed on master branch

### ISSUE THREAD

**Issue by Tjianke** [pingcap/tidb#22627]
## Development Task

Function `BenchmarkWindowFunctionsWithSlidingWindow` in `executor/benchmark_test.go` failed on master branch.

```
go test -v -benchmem -bench=BenchmarkWindowFunctionsWithSlidingWindow  -run=BenchmarkWindowFunctionsWithSlidingWindow

goos: darwin
goarch: amd64
pkg: github.com/pingcap/tidb/executor
BenchmarkWindowFunctionsWithSlidingWindow
BenchmarkWindowFunctionsWithSlidingWindow/(func:sum,_aggColType:float,_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)
BenchmarkWindowFunctionsWithSlidingWindow/(func:sum,_aggColType:float,_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)-8                151           7390369 ns/op         7475284 B/op       6535 allocs/op
BenchmarkWindowFunctionsWithSlidingWindow/(func:sum,_aggColType:decimal(10,0),_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)
BenchmarkWindowFunctionsWithSlidingWindow/(func:sum,_aggColType:decimal(10,0),_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)-8         87          14369208 ns/op         8859247 B/op       4259 allocs/op
BenchmarkWindowFunctionsWithSlidingWindow/(func:count,_aggColType:int(11),_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)
BenchmarkWindowFunctionsWithSlidingWindow/(func:count,_aggColType:int(11),_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)-8            163           7219211 ns/op         7428094 B/op       6532 allocs/op
BenchmarkWindowFunctionsWithSlidingWindow/(func:avg,_aggColType:float,_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)
BenchmarkWindowFunctionsWithSlidingWindow/(func:avg,_aggColType:float,_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)-8                163           7376047 ns/op         7516243 B/op       6537 allocs/op
BenchmarkWindowFunctionsWithSlidingWindow/(func:avg,_aggColType:decimal(10,0),_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)
BenchmarkWindowFunctionsWithSlidingWindow/(func:avg,_aggColType:decimal(10,0),_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)-8         34          34557702 ns/op        11887266 B/op     103938 allocs/op
BenchmarkWindowFunctionsWithSlidingWindow/(func:bit_xor,_aggColType:int(11),_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)
BenchmarkWindowFunctionsWithSlidingWindow/(func:bit_xor,_aggColType:int(11),_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)-8          165           7357622 ns/op         7571454 B/op       6537 allocs/op
BenchmarkWindowFunctionsWithSlidingWindow/(func:max,_aggColType:int(11),_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)
BenchmarkWindowFunctionsWithSlidingWindow/(func:max,_aggColType:int(11),_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)-8               24          48646361 ns/op        20222958 B/op     211876 allocs/op
BenchmarkWindowFunctionsWithSlidingWindow/(func:max,_aggColType:float,_numFunc:1,_ndv:100,_rows:100000,_sorted:true,_concurrency:1)
panic: remove a not exist value

goroutine 215 [running]:
github.com/pingcap/tidb/executor/aggfuncs.(*maxMinHeap).Remove(...)
        /Users/damn/go/tidb/executor/aggfuncs/func_max_min.go:79
github.com/pingcap/tidb/executor/aggfuncs.(*maxMin4Float32Sliding).Slide(0xc00012a480, 0x6cd6540, 0xc000464ae0, 0xc001fb6000, 0x3fe, 0x400, 0x36, 0x4b, 0x1, 0x1, ...)
        /Users/damn/go/tidb/executor/aggfuncs/func_max_min.go:594 +0x4f1
github.com/pingcap/tidb/executor.(*rowFrameWindowProcessor).appendResult2Chunk(0xc0004219a0, 0x6cd6540, 0xc000464ae0, 0xc001fb6000, 0x3fe, 0x400, 0xc00070a230, 0x3bd, 0x400, 0x0, ...)
        /Users/damn/go/tidb/executor/window.go:338 +0x60f
github.com/pingcap/tidb/executor.(*WindowExec).consumeGroupRows(0xc00016b790, 0xc001fb6000, 0x3fe, 0x400, 0x201, 0xc001fb6000)
        /Users/damn/go/tidb/executor/window.go:140 +0x1e3
github.com/pingcap/tidb/executor.(*WindowExec).consumeOneGroup(0xc00016b790, 0x6c89140, 0xc0001a0008, 0x1, 0xc0010b8b60)
        /Users/damn/go/tidb/executor/window.go:120 +0x4d9
github.com/pingcap/tidb/executor.(*WindowExec).Next(0xc00016b790, 0x6c89140, 0xc0001a0008, 0xc0004219f0, 0x0, 0xc00038c060)
        /Users/damn/go/tidb/executor/window.go:56 +0xa5
github.com/pingcap/tidb/executor.benchmarkWindowExecWithCase(0xc000457d40, 0xc0007b2c00)
        /Users/damn/go/tidb/executor/benchmark_test.go:640 +0x37d
github.com/pingcap/tidb/executor.baseBenchmarkWindowFunctionsWithSlidingWindow.func1(0xc000457d40)
        /Users/damn/go/tidb/executor/benchmark_test.go:793 +0x34
testing.(*B).runN(0xc000457d40, 0x1)
        /usr/local/Cellar/go/1.15.5/libexec/src/testing/benchmark.go:191 +0xeb
testing.(*B).run1.func1(0xc000457d40)
        /usr/local/Cellar/go/1.15.5/libexec/src/testing/benchmark.go:231 +0x57
created by testing.(*B).run1
        /usr/local/Cellar/go/1.15.5/libexec/src/testing/benchmark.go:224 +0x7f
exit status 2
FAIL    github.com/pingcap/tidb/executor        14.431s

```

**Comment by Tjianke** [comment]
`BenchmarkWindowFunctionsWithSlidingWindow` failed due to `maxMinHeap`, which will be removed in #22628, benchmark works fine under #22628.

**Comment by Yisaer** [comment]
@Tjianke  I found the error was not caused by the `heap` but caused by data generating, I think you can try to use https://github.com/pingcap/tidb/issues/22627 to check your benchmark result.
