### ISSUE TITLE
v4.0.5 upgrade to 5.0.0, report "indexWorker in IndexLookupExecutor panicked" error

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#23934]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tiup deploy v4.0.5 version
upgrade to 5.0.0
run bank workload

### 2. What did you expect to see? (Required)
workload run normally, no error in tidb

### 3. What did you see instead (Required)
find the following errors in tidb.log file:
[2021/04/09 18:05:36.326 +08:00] [ERROR] [distsql.go:698] ["indexWorker in IndexLookupExecutor panicked"] [conn=75] [stack="goroutine 814 [running]:\ngithub.com/pingcap/tidb/executor.(*indexWorker).fetchHandles.func1(0x3ff5fa0, 0xc001efd300, 0xc0027036d0, 0xc002542e68)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/distsql.go:696 +0xb8\npanic(0x378df20, 0xc001c7eca0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/statistics.(*QueryFeedback).Update(0xc002703360, 0xc0020fa680, 0x1c, 0x1c, 0xc00203af80, 0x1, 0x1, 0x0, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/feedback.go:314 +0x35c\ngithub.com/pingcap/tidb/distsql.(*selectResult).fetchResp(0xc001cf4a80, 0x3ff5fa0, 0xc001efd300, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/distsql/select_result.go:185 +0x4dd\ngithub.com/pingcap/tidb/distsql.(*selectResult).Next(0xc001cf4a80, 0x3ff5fa0, 0xc001efd300, 0xc0028eb4a0, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/distsql/select_result.go:208 +0x64\ngithub.com/pingcap/tidb/executor.(*indexWorker).extractTaskHandles(0xc0027036d0, 0x3ff5fa0, 0xc001efd300, 0xc0028eb4a0, 0x3ff6560, 0xc001cf4a80, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/distsql.go:781 +0x5e1\ngithub.com/pingcap/tidb/executor.(*indexWorker).fetchHandles(0xc0027036d0, 0x3ff5fa0, 0xc001efd300, 0x3ff6560, 0xc001cf4a80, 0x0, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/distsql.go:720 +0x22a\ngithub.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startIndexWorker.func1(0x3ff6060, 0xc00211dad0, 0xc0027036d0, 0x3ff6560, 0xc001cf4a80, 0xc0026b63c0, 0xc001b4aba0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/distsql.go:509 +0x103\ncreated by github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startIndexWorker\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/distsql.go:506 +0x570\n"]
[2021/04/09 18:05:36.328 +08:00] [INFO] [conn.go:812] ["command dispatched failed"] [conn=75] [connInfo="id:75, addr:10.0.2.222:33866 status:11, collation:utf8mb4_general_ci, user:root"] [command=Execute] [status="inTxn:1, autocommit:1"] [sql="SELECT * FROM `employee` WHERE `employee`.`uid` = ? AND `employee`.`status` = ? [arguments: (1000000798, 0)]"] [txn_mode=PESSIMISTIC] [err="runtime error: index out of range [0] with length 0\ngithub.com/pingcap/tidb/executor.(*indexWorker).fetchHandles.func1\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/e

### 4. What is your TiDB version? (Required)

| Release Version: v5.0.0
Edition: Community
Git Commit Hash: bdac0885cd11bdf571aad9353bfc24e13554b91c
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time: 2021-04-06 16:36:29
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

**Comment by ichn-hu** [comment]
The log matches https://github.com/pingcap/tidb/issues/23567, @eurekaka would you please help verify?

**Comment by winoros** [comment]
They are the same problem.

**Comment by ichn-hu** [comment]
can we close this issue?

**Comment by ichn-hu** [comment]
@seiya-annie
