### ISSUE TITLE
"runtime error: index out of range [7] with length 7"] when split region

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#24262]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

[2021/04/23 18:38:00.674 +08:00] [INFO] [split_region.go:160] ["batch split regions complete"] ["batch region ID"=3] ["first at"=7480000000000006fe] ["first new region left"="{Id:3709 StartKey:7480000000000006fffd00000000000000f8 EndKey:7480000000000006fffe00000000000000f8 RegionEpoch:{ConfVer:5 Version:718} Peers:[id:3710 store_id:1  id:3711 store_id:7  id:3712 store_id:2 ] EncryptionMeta:<nil>}"] ["new region count"=1]
[2021/04/23 18:38:00.674 +08:00] [INFO] [split_region.go:204] ["split regions complete"] ["region count"=1] ["region IDs"="[3709]"]
[2021/04/23 18:38:00.675 +08:00] [WARN] [2pc.go:1406] ["schemaLeaseChecker is not set for this transaction"] [conn=409] [sessionID=409] [startTS=424456822626451473] [commitTS=424456822626451475]
[2021/04/23 18:38:00.992 +08:00] [INFO] [conn.go:812] ["command dispatched failed"] [conn=409] [connInfo="id:409, addr:172.16.5.197:42688 status:11, collation:utf8mb4_general_ci, user:root"] [command=Query] [status="inTxn:1, autocommit:1"] [sql="insert into t1 values (4, 'compassionate villani', '2020-02-05 02:45:03', '2020-04-05 14:19:54', 53.531129, 3.543), (9, 'tender moser', '2020-06-10 10:35:26', '2020-03-10 11:56:24', 61.880568, 8.926), (11, 'stoic sinoussi', '2020-01-28 15:09:04', '2020-06-18 15:40:31', 66.396837, 6.269) on duplicate key update c_int = c_int + 1, c_str = concat(c_int, ':', c_str)"] [txn_mode=PESSIMISTIC] [err="[kv:1062]Duplicate entry '5' for key 'c_int'"]
[2021/04/23 18:38:01.009 +08:00] [WARN] [client_batch.go:768] ["wait response is cancelled"] [to=172.16.5.101:20260] [cause="context canceled"]
[2021/04/23 18:38:01.009 +08:00] [WARN] [client_batch.go:768] ["wait response is cancelled"] [to=172.16.5.101:20260] [cause="context canceled"]
[2021/04/23 18:38:01.213 +08:00] [INFO] [domain.go:161] ["full load InfoSchema success"] [usedSchemaVersion=0] [neededSchemaVersion=1154] ["start time"=19.189146ms]
[2021/04/23 18:38:01.214 +08:00] [INFO] [infoschema.go:401] ["use snapshot schema"] [conn=0] [schemaVersion=1154]
[2021/04/23 18:38:01.214 +08:00] [INFO] [infoschema.go:401] ["use snapshot schema"] [conn=0] [schemaVersion=1154]
[2021/04/23 18:38:01.214 +08:00] [INFO] [infoschema.go:401] ["use snapshot schema"] [conn=0] [schemaVersion=1154]
[2021/04/23 18:38:01.235 +08:00] [INFO] [domain.go:161] ["full load InfoSchema success"] [usedSchemaVersion=0] [neededSchemaVersion=1154] ["start time"=19.154587ms]
.
.
.
[2021/04/23 18:38:01.746 +08:00] [WARN] [client_batch.go:768] ["wait response is cancelled"] [to=172.16.5.101:20260] [cause="context canceled"]
[2021/04/23 18:38:01.775 +08:00] [ERROR] [projection.go:448] ["projection executor panicked"] [error="runtime error: index out of range [7] with length 7"] [stack="goroutine 629361 [running]:\ngithub.com/pingcap/tidb/util.GetStack(...)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/misc.go:74\ngithub.com/pingcap/tidb/executor.recoveryProjection(0xc002ade440, 0x3799c40, 0xc003851da0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/projection.go:447 +0x90\ngithub.com/pingcap/tidb/executor.(*projectionInputFetcher).run.func1(0xc000a87f80, 0xc0039822c0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/projection.go:349 +0x82\npanic(0x3799c40, 0xc003851da0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/util/chunk.MutRow.SetDatum(0xc00340f270, 0x0, 0x7, 0x1, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/chunk/mutrow.go:287 +0x750\ngithub.com/pingcap/tidb/util/chunk.MutRow.SetDatums(0xc00340f270, 0x0, 0xc0017ae000, 0xe, 0xe)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/chunk/mutrow.go:281 +0x14b\ngithub.com/pingcap/tidb/table/tables.(*partitionedTable).locateRangePartition(0xc00013fe40, 0x405e0c0, 0xc001799540, 0xc00286d5e0, 0xc0017ae000, 0xe, 0xe, 0x0, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/table/tables/partition.go:919 +0x4cc\ngithub.com/pingcap/tidb/table/tables.(*partitionedTable).locatePartition(0xc00013fe40, 0x405e0c0, 0xc001799540, 0xc00286d5e0, 0xc0017ae000, 0xe, 0xe, 0x0, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/table/tables/partition.go:836 +0x9a\ngithub.com/pingcap/tidb/table/tables.(*partitionedTable).GetPartitionByRow(0xc00013fe40, 0x405e0c0, 0xc001799540, 0xc0017ae000, 0xe, 0xe, 0xe, 0xe, 0x0, 0xc00260a460)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/table/tables/partition.go:1009 +0x8d\ngithub.com/pingcap/tidb/executor.(*SelectLockExec).Next(0xc002e1af20, 0x4004aa0, 0xc0018472f0, 0xc002c10f50, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/executor.go:930 +0x460\ngithub.com/pingcap/tidb/executor.Next(0x4004aa0, 0xc0018472f0, 0x400d060, 0xc002e1af20, 0xc002c10f50, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/executor.go:277 +0x225\ngithub.com/pingcap/tidb/executor.(*projectionInputFetcher).run(0xc0039822c0, 0x4004aa0, 0xc0018472f0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/projection.go:373 +0x283\ncreated by github.com/pingcap/tidb/executor.(*ProjectionExec).prepare\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/projection.go:265 +0x753\n"]

### 2. What did you expect to see? (Required)
no panic
### 3. What did you see instead (Required)
report panic error

### 4. What is your TiDB version? (Required)

["Release Version"=v5.0.0-nightly] [Edition=Community] ["Git Commit Hash"=41871e0c8e5e4b0601dd94d09342bc0317cbb8cb] ["Git Branch"=heads/refs/tags/v5.0.0-nightly] ["UTC Build Time"="2021-04-20 14:49:18"] [GoVersion=go1.13] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]

**Comment by seiya-annie** [comment]
sql statement and result during this time is:
[out-of-index.log](https://github.com/pingcap/tidb/files/6371445/out-of-index.log)

**Comment by lzmhhh123** [comment]
@seiya-annie Could you help provide simpler reproduction steps?

**Comment by lzmhhh123** [comment]
I just made it clear. The PR cloud be fixed by https://github.com/pingcap/tidb/pull/21148.
