### ISSUE TITLE
insert clustered index value shorter than prefix index length and primary key duplicate，tidb panic

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#25428]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

CREATE TABLE `t` (   `c_int` int(11) DEFAULT NULL,   `c_str` varbinary(40) NOT NULL,   PRIMARY KEY (`c_str`(39)) clustered ,   KEY `c_str_2` (`c_str`(4)) );
insert into t (c_int, c_str) values (36, 'nervous elbakyan');
insert into t (c_int, c_str) values (36, 'nervous elbakyan');---check result

### 2. What did you expect to see? (Required)

return error as follow:
mysql> insert into t1 (c_int, c_str) values (36, 'nervous elbakyan');
ERROR 1062 (23000): Duplicate entry 'nervous elbakyan' for key 'PRIMARY'

### 3. What did you see instead (Required)

panic:
mysql> insert into t1 (c_int, c_str) values (36, 'nervous elbakyan');
ERROR 1105 (HY000): runtime error: slice bounds out of range [:17] with length 16

tidb log:
[2021/06/15 08:28:51.316 +00:00] [ERROR] [conn.go:801] ["connection running loop panic"] [conn=11] [lastSQL="insert into t1 (c_int, c_str) values (36, 'nervous elbakyan')"] [err="runtime error: slice bounds out of range [:17] with length 16"] [stack="goroutine 8338 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x3be5c18, 0xc001ca6120, 0xc001850b00)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/server/conn.go:799 +0xf5\npanic(0x3527840, 0xc0018e4c48)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/store/driver/txn.extractKeyExistsErrFromHandle(0xc0008e6c30, 0x27, 0x30, 0xc000eee000, 0x1d, 0x1d, 0xc000df4f00, 0x1d, 0x0)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/store/driver/txn/error.go:98 +0xd89\ngithub.com/pingcap/tidb/store/driver/txn.(*tikvTxn).extractKeyExistsErr(0xc000da4620, 0xc0008e6c30, 0x27, 0x30, 0x270489e, 0x365d700)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/store/driver/txn/txn_driver.go:227 +0x193\ngithub.com/pingcap/tidb/store/driver/txn.(*tikvTxn).extractKeyErr(0xc000da4620, 0x3b9abe0, 0xc00196f050, 0x3b9abe0, 0xc00196f050)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/store/driver/txn/txn_driver.go:206 +0x7f\ngithub.com/pingcap/tidb/store/driver/txn.(*tikvTxn).Commit(0xc000da4620, 0x3be5c18, 0xc0013b3e30, 0x34ff440, 0x3bc5500)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/store/driver/txn/txn_driver.go:67 +0x67\ngithub.com/pingcap/tidb/session.(*LazyTxn).Commit(0xc000ddeb50, 0x3be5c18, 0xc0013b3e30, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/session/txn.go:366 +0x50b\ngithub.com/pingcap/tidb/session.(*session).doCommit(0xc000ddeb40, 0x3be5c18, 0xc0013b3d70, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/session/session.go:539 +0x6da\ngithub.com/pingcap/tidb/session.(*session).doCommitWithRetry(0xc000ddeb40, 0x3be5c18, 0xc0013b3d70, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/session/session.go:603 +0x157\ngithub.com/pingcap/tidb/session.(*session).CommitTxn(0xc000ddeb40, 0x3be5c18, 0xc00151cdb0, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/session/session.go:665 +0x145\ngithub.com/pingcap/tidb/session.autoCommitAfterStmt(0x3be5c18, 0xc00151cdb0, 0xc000ddeb40, 0x0, 0x0, 0x3bfbb58, 0xc001900480, 0x1, 0xc00149aad8)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/session/tidb.go:254 +0x42e\ngithub.com/pingcap/tidb/session.finishStmt(0x3be5c18, 0xc00151cdb0, 0xc000ddeb40, 0x0, 0x0, 0x3bfbb58, 0xc001900480, 0x11997d8, 0x2)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/session/tidb.go:220 +0xcc\ngithub.com/pingcap/tidb/session.runStmt(0x3be5c18, 0xc00151cdb0, 0xc000ddeb40, 0x3bfbb58, 0xc001900480, 0x0, 0x0, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/session/session.go:1664 +0x57a\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc000ddeb40, 0x3be5c18, 0xc00151cdb0, 0x3bffc78, 0xc002050680, 0x0, 0x0, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/session/session.go:1548 +0xaab\ngithub.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt(0xc001ca65a0, 0x3be5c18, 0xc00151cdb0, 0x3bffc78, 0xc002050680, 0xc002005200, 0x3be5c18, 0xc00151cdb0, 0x688)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/server/driver_tidb.go:218 +0x68\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt(0xc001850b00, 0x3be5b70, 0xc00151cdb0, 0x3bffc78, 0xc002050680, 0x57af8a0, 0x0, 0x0, 0x1, 0x0, ...)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/go/src/github.com/pingcap/tidb/server/conn.go:1691 +0x1bb\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc001850b00, 0x3be5b70, 0xc002254e40, 0xc001376241, 0x3d, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/ld_tidb_multi_branch_release-5.1/"]

### 4. What is your TiDB version? (Required)

v5.1 and master

Release Version: v5.1.0-alpha-196-g685d4c8d7
Edition: Community
Git Commit Hash: 685d4c8d79b68453c96321b6a20573913b74841f
Git Branch: release-5.1
UTC Build Time: 2021-06-15 06:51:45
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by aytrack** [comment]
duplicate with #25377
