### ISSUE TITLE
Test session with tikv hang more then 10 minutes

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tidb#25894]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```
2021-07-01T13:45:57.146Z] PASS: session_test.go:3360: testSessionSerialSuite.TestSetTxnScope	0.675s
[2021-07-01T13:45:57.146Z] [2021/07/01 21:45:57.118 +08:00] [ERROR] [privileges.go:226] ["get user privilege record fail"] [user=user_not_exist] [host=]
[2021-07-01T13:45:57.146Z] [2021/07/01 21:45:57.119 +08:00] [ERROR] [privileges.go:226] ["get user privilege record fail"] [user=user_not_exist] [host=]
[2021-07-01T13:45:59.038Z] PASS: session_test.go:1008: testSessionSerialSuite.TestSkipWithGrant	0.987s
[2021-07-01T13:46:00.409Z] PASS: session_test.go:2569: testSessionSerialSuite.TestStatementCountLimit	0.502s
[2021-07-01T13:46:03.686Z] PASS: session_test.go:4125: testSessionSerialSuite.TestTiKVSystemVars	3.081s
[2021-07-01T13:46:04.616Z] PASS: session_test.go:2827: testSessionSerialSuite.TestTxnRetryErrMsg	0.631s
[2021-07-01T13:46:22.681Z] panic: test timed out after 10m0s
[2021-07-01T13:46:22.681Z] 
[2021-07-01T13:46:22.681Z] goroutine 31483 [running]:
[2021-07-01T13:46:22.681Z] testing.(*M).startAlarm.func1()
[2021-07-01T13:46:22.681Z] 	/usr/local/go/src/testing/testing.go:1700 +0xe5
[2021-07-01T13:46:22.681Z] created by time.goFunc
[2021-07-01T13:46:22.681Z] 	/usr/local/go/src/time/sleep.go:180 +0x45
[2021-07-01T13:46:22.681Z] 
[2021-07-01T13:46:22.681Z] goroutine 1 [chan receive, 10 minutes]:
[2021-07-01T13:46:22.681Z] testing.(*T).Run(0xc00090a780, 0x372ba31, 0x5, 0x38409f8, 0x113ec01)
[2021-07-01T13:46:22.681Z] 	/usr/local/go/src/testing/testing.go:1239 +0x2da
[2021-07-01T13:46:22.681Z] testing.runTests.func1(0xc00090a480)
[2021-07-01T13:46:22.681Z] 	/usr/local/go/src/testing/testing.go:1511 +0x78
[2021-07-01T13:46:22.681Z] testing.tRunner(0xc00090a480, 0xc000bbfde0)
[2021-07-01T13:46:22.681Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-07-01T13:46:22.681Z] testing.runTests(0xc00016f368, 0x511a420, 0x2, 0x2, 0xc02f8fab9715b246, 0x8bb55bfba4, 0x579f540, 0x3740a57)
[2021-07-01T13:46:22.681Z] 	/usr/local/go/src/testing/testing.go:1509 +0x2fe
[2021-07-01T13:46:22.681Z] testing.(*M).Run(0xc0004fe280, 0x0)
[2021-07-01T13:46:22.681Z] 	/usr/local/go/src/testing/testing.go:1417 +0x1eb
[2021-07-01T13:46:22.681Z] main.main()
[2021-07-01T13:46:22.681Z] 	_testmain.go:89 +0x138
```

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_check_2/runs/13643/nodes/55/steps/92/log/?start=0

### 4. What is your TiDB version? (Required)
master

**Comment by zhouqiang-cl** [comment]
another https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/13646/pipeline

**Comment by zhouqiang-cl** [comment]
another https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/13661/pipeline

**Comment by bb7133** [comment]
PTAL @djshow832

**Comment by bb7133** [comment]
Close this issue since it does not appear for a long time(probably fixed).
