### ISSUE TITLE
CI check2 hang more then 10 minutes

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tidb#25895]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```
[2021-07-01T15:15:19.610Z] [2021/07/01 23:06:51.058 +08:00] [INFO] [db.go:617] ["ResourceManager finished"]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:06:51.058 +08:00] [INFO] [db.go:623] ["Waiting for closer"]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:06:51.946 +08:00] [WARN] [grpclogger.go:89] ["grpc: addrConn.createTransport failed to connect to {test  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp: address test: missing port in address\". Reconnecting..."] [system=grpc] [grpc_log=true]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:07:05.077 +08:00] [WARN] [data_window.go:112] ["querySQLMetric got error"]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:07:18.463 +08:00] [WARN] [grpclogger.go:89] ["grpc: addrConn.createTransport failed to connect to {test  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp: address test: missing port in address\". Reconnecting..."] [system=grpc] [grpc_log=true]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:08:02.434 +08:00] [WARN] [grpclogger.go:89] ["grpc: addrConn.createTransport failed to connect to {test  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp: address test: missing port in address\". Reconnecting..."] [system=grpc] [grpc_log=true]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:08:05.581 +08:00] [WARN] [data_window.go:112] ["querySQLMetric got error"]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:09:00.983 +08:00] [WARN] [grpclogger.go:89] ["grpc: addrConn.createTransport failed to connect to {test  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp: address test: missing port in address\". Reconnecting..."] [system=grpc] [grpc_log=true]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:09:06.085 +08:00] [WARN] [data_window.go:112] ["querySQLMetric got error"]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:10:06.589 +08:00] [WARN] [data_window.go:112] ["querySQLMetric got error"]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:10:33.163 +08:00] [WARN] [grpclogger.go:89] ["grpc: addrConn.createTransport failed to connect to {test  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp: address test: missing port in address\". Reconnecting..."] [system=grpc] [grpc_log=true]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:11:07.091 +08:00] [WARN] [data_window.go:112] ["querySQLMetric got error"]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:12:07.595 +08:00] [WARN] [data_window.go:112] ["querySQLMetric got error"]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:12:54.120 +08:00] [WARN] [grpclogger.go:89] ["grpc: addrConn.createTransport failed to connect to {test  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp: address test: missing port in address\". Reconnecting..."] [system=grpc] [grpc_log=true]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:13:08.097 +08:00] [WARN] [data_window.go:112] ["querySQLMetric got error"]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:14:08.602 +08:00] [WARN] [data_window.go:112] ["querySQLMetric got error"]

[2021-07-01T15:15:19.611Z] [2021/07/01 23:14:57.463 +08:00] [WARN] [grpclogger.go:89] ["grpc: addrConn.createTransport failed to connect to {test  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp: address test: missing port in address\". Reconnecting..."] [system=grpc] [grpc_log=true]

[2021-07-01T15:15:19.611Z] coverage: 76.3% of statements

[2021-07-01T15:15:19.611Z] panic: test timed out after 9m0s

[2021-07-01T15:15:19.611Z] 

[2021-07-01T15:15:19.611Z] goroutine 78609 [running]:

[2021-07-01T15:15:19.611Z] testing.(*M).startAlarm.func1()

[2021-07-01T15:15:19.611Z] 	/usr/local/go/src/testing/testing.go:1700 +0xe5

[2021-07-01T15:15:19.611Z] created by time.goFunc

[2021-07-01T15:15:19.611Z] 	/usr/local/go/src/time/sleep.go:180 +0x45

[2021-07-01T15:15:19.611Z] 

[2021-07-01T15:15:19.611Z] goroutine 1 [chan receive, 9 minutes]:
```

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/13658/pipeline

### 4. What is your TiDB version? (Required)
master

**Comment by bb7133** [comment]
PTAL @djshow832

**Comment by zhouqiang-cl** [comment]
happend again https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/17118/pipeline

**Comment by tisonkun** [comment]
@zhouqiang-cl could you elaborate which package hangs? Otherwise I tend to close this one as unclear report.

**Comment by tisonkun** [comment]
CI report cannot be reached. Closed as unclear. You can open another issue with necessary information.
