### ISSUE TITLE
TiDB 5.0.2 Panic 

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tidb#26689]
## General Question

Error encountered while executing SQL in online environment

```
[err="runtime error: index out of range [9] with length 9"] [stack="goroutine 2580623304 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x3a37478, 0xc1c9190c90, 0xc0c4e59100)
	/opt/436/tidb/server/conn.go:734 +0xf5
panic(0x3396480, 0xc263599230)
	/usr/lib/golang/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb/planner/core.(*joinReOrderSolver).optimizeRecursive(0x5546040, 0x3a749b8, 0xc135091e00, 0x3a72d30, 0xc247ce2e00, 0x0, 0x0, 0x0, 0x0)
	/opt/436/tidb/planner/core/rule_join_reorder.go:95 +0xa46
github.com/pingcap/tidb/planner/core.(*joinReOrderSolver).optimizeRecursive(0x5546040, 0x3a749b8, 0xc135091e00, 0x3a72a30, 0xc262a55900, 0x0, 0x0, 0x0, 0x0)
	/opt/436/tidb/planner/core/rule_join_reorder.go:112 +0x885
github.com/pingcap/tidb/planner/core.(*joinReOrderSolver).optimizeRecursive(0x5546040, 0x3a749b8, 0xc135091e00, 0x3a73330, 0xc27dba4000, 0x5548960, 0x0, 0x32e8ce0, 0xc001b92300)
	/opt/436/tidb/planner/core/rule_join_reorder.go:112 +0x885
github.com/pingcap/tidb/planner/core.(*joinReOrderSolver).optimize(0x5546040, 0x3a37478, 0xc0b4ad20c0, 0x3a73330, 0xc27dba4000, 0x3a73330, 0xc27dba4000, 0x0, 0x0)
	/opt/436/tidb/planner/core/rule_join_reorder.go:58 +0x5a
github.com/pingcap/tidb/planner/core.logicalOptimize(0x3a37478, 0xc0b4ad20c0, 0x3df6, 0x3a73330, 0xc27dba4000, 0x2af96e732f300330, 0x6100ebe9, 0xc276e999b0, 0x1099966)
	/opt/436/tidb/planner/core/optimizer.go:198 +0x11b
github.com/pingcap/tidb/planner/core.DoOptimize(0x3a37478, 0xc0b4ad20c0, 0x3a749b8, 0xc135091e00, 0x1df6, 0x3a73330, 0xc27dba4000, 0x0, 0x0, 0x0, ...)
	/opt/436/tidb/planner/core/optimizer.go:132 +0x77
github.com/pingcap/tidb/planner.optimize(0x3a37478, 0xc0b4ad20c0, 0x3a749b8, 0xc135091e00, 0x3a4c4f8, 0xc249ab1300, 0x3a6cae8, 0xc08b2d2c80, 0x0, 0x0, ...)
	/opt/436/tidb/planner/optimize.go:288 +0x7b3
github.com/pingcap/tidb/planner.Optimize(0x3a37478, 0xc0b4ad20c0, 0x3a749b8, 0xc135091e00, 0x3a4c4f8, 0xc249ab1300, 0x3a6cae8, 0xc08b2d2c80, 0x0, 0x0, ...)
	/opt/436/tidb/planner/optimize.go:124 +0x511
github.com/pingcap/tidb/planner/core.(*Execute).getPhysicalPlan(0xc273066410, 0x3a37478, 0xc0b4ad20c0, 0x3a749b8, 0xc135091e00, 0x3a6cae8, 0xc08b2d2c80, 0xc267211d40, 0x756ea1fcc05171, 0xc95abee52fc48a8b)
	/opt/436/tidb/planner/core/common_plans.go:367 +0x356
github.com/pingcap/tidb/planner/core.(*Execute).OptimizePreparedPlan(0xc273066410, 0x3a37478, 0xc0b4ad20c0, 0x3a749b8, 0xc135091e00, 0x3a6cae8, 0xc08b2d2c80, 0x0, 0x0)
	/opt/436/tidb/planner/core/common_plans.go:252 +0x512
github.com/pingcap/tidb/planner.optimize(0x3a37478, 0xc0b4ad20c0, 0x3a749b8, 0xc135091e00, 0x3a4b460, 0xc1163fcae0, 0x3a6cae8, 0xc08b2d2c80, 0x0, 0x0, ...)
	/opt/436/tidb/planner/optimize.go:269 +0x59d
github.com/pingcap/tidb/planner.Optimize(0x3a37478, 0xc0b4ad20c0, 0x3a749b8, 0xc135091e00, 0x3a4b460, 0xc1163fcae0, 0x3a6cae8, 0xc08b2d2c80, 0x0, 0x0, ...)
	/opt/436/tidb/planner/optimize.go:124 +0x511
github.com/pingcap/tidb/executor.CompileExecutePreparedStmt(0x3a37478, 0xc0b4ad20c0, 0x3a749b8, 0xc135091e00, 0x17, 0x55467f0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/436/tidb/executor/prepared.go:324 +0x22d
github.com/pingcap/tidb/session.(*session).preparedStmtExec(0xc135091e00, 0x3a37478, 0xc0b4ad20c0, 0xc200000017, 0xc267211d40, 0x55467f0, 0x0, 0x0, 0x7fad2a0298b8, 0x107f965, ...)
	/opt/436/tidb/session/session.go:1619 +0x98
github.com/pingcap/tidb/session.(*session).ExecutePreparedStmt(0xc135091e00, 0x3a37478, 0xc0b4ad20c0, 0x17, 0x55467f0, 0x0, 0x0, 0xaa, 0x40, 0x3f, ...)
	/opt/436/tidb/session/session.go:1775 +0x2a5
github.com/pingcap/tidb/server.(*TiDBStatement).Execute(0xc2f1bd1110, 0x3a37478, 0xc0b4ad20c0, 0x55467f0, 0x0, 0x0, 0x7fad209660b8, 0xc000700000, 0x0, 0xc276e9b048)
	/opt/436/tidb/server/driver_tidb.go:73 +0x93
github.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult(0xc0c4e59100, 0x3a37478, 0xc0b4ad20c0, 0x3a62478, 0xc2f1bd1110, 0x55467f0, 0x0, 0x0, 0x101000000, 0x0, ...)
	/opt/436/tidb/server/conn_stmt.go:217 +0xad
github.com/pingcap/tidb/server.(*clientConn).handleStmtExecute(0xc0c4e59100, 0x3a373d0, 0xc0b4ad20c0, 0xc27304e891, 0x9, 0x9, 0x0, 0x0)
	/opt/437/tidb/server/conn_stmt.go:197 +0x5c"]

```

TiDB version

```
 ./tidb-server -V
Release Version: v4.0.0-beta.2-2487-g70f7884
Edition: Community
Git Commit Hash: 70f78847f463d9f1f4f6a8f329749762a71033ed
Git Branch: release-5.0-734084fa2bf2
UTC Build Time: 2021-05-10 14:50:14
GoVersion: go1.16
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by lucklove** [comment]
Any update?

**Comment by Defined2014** [comment]
No update for long time and v5.0.2 is too older now, so close this issue. If you still have questions, please feel free to reopen it.
