### ISSUE TITLE
signal SIGSEGV: segmentation violation 

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#26950]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I don't know how to reproduce

maybe need to set tidb_partition_prune_mode=true

### 3. What did you see instead (Required)
```
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc3c4000000 pc=0x10c8ff0]

goroutine 1651278827 [running]:
runtime.throw(0x37301e0, 0x5)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc1165b4090 sp=0xc1165b4060 pc=0x10fff72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:741 +0x268 fp=0xc1165b40c8 sp=0xc1165b4090 pc=0x1117a68
countbody(0xc097fdf020, 0xc097fdf200, 0xc1165b4160, 0x11c4645, 0xc131f94110, 0x38401a0, 0xc1165b41d0, 0x11dd07c, 0xc097fdf020, 0xc097fdf200, ...)
	/usr/local/go/src/internal/bytealg/count_amd64.s:160 +0x110 fp=0xc1165b40d0 sp=0xc1165b40c8 pc=0x10c8ff0
strings.Count(0xc097fdf020, 0xc097fdf200, 0x372d5f7, 0x1, 0x38401a0)
	/usr/local/go/src/strings/strings.go:47 +0xf7 fp=0xc1165b4110 sp=0xc1165b40d0 pc=0x11d97d7
strings.Replace(0xc097fdf020, 0xc097fdf200, 0x372d5f7, 0x1, 0x372d876, 0x2, 0xffffffffffffffff, 0x1146b65, 0x12)
	/usr/local/go/src/strings/strings.go:930 +0xbc fp=0xc1165b41e0 sp=0xc1165b4110 pc=0x11dd07c
github.com/pingcap/parser/format.(*RestoreCtx).WriteName(0xc1165b45e8, 0xc097fdf020, 0xc097fdf200)
	/nfs/cache/mod/github.com/pingcap/parser@v0.0.0-20210618053735-57843e8185c4/format/format.go:350 +0x1be fp=0xc1165b4278 sp=0xc1165b41e0 pc=0x1479e3e
github.com/pingcap/parser/ast.(*HintTable).Restore(0xc1165b4448, 0xc1165b45e8)
	/nfs/cache/mod/github.com/pingcap/parser@v0.0.0-20210618053735-57843e8185c4/ast/misc.go:3157 +0x30b fp=0xc1165b4300 sp=0xc1165b4278 pc=0x191f16b
github.com/pingcap/parser/ast.(*TableOptimizerHint).Restore(0xc04406fcc0, 0xc1165b45e8, 0x0, 0x57e8de0)
	/nfs/cache/mod/github.com/pingcap/parser@v0.0.0-20210618053735-57843e8185c4/ast/misc.go:3208 +0x29a fp=0xc1165b44d0 sp=0xc1165b4300 pc=0x191f45a
github.com/pingcap/tidb/util/hint.RestoreTableOptimizerHint(0xc04406fcc0, 0xc1165b46b8, 0xc047cb2a40)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/hint/hint_processor.go:149 +0xe6 fp=0xc1165b4638 sp=0xc1165b44d0 pc=0x1e1f166
github.com/pingcap/tidb/util/hint.RestoreOptimizerHints(0xc045a98700, 0x8, 0x8, 0xc1b7282068, 0x1)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/hint/hint_processor.go:135 +0x155 fp=0xc1165b4788 sp=0xc1165b4638 pc=0x1e1eef5
github.com/pingcap/tidb/executor.getEncodedPlan(0x3c52b10, 0xc062bed540, 0x3c3e228, 0xc0427e7340, 0x1, 0x3c2d7e8, 0xc0049f8000, 0xc047cae6f0, 0xc1165b4938, 0x1df70ff, ...)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:1101 +0x1a9 fp=0xc1165b4868 sp=0xc1165b4788 pc=0x2c97229
github.com/pingcap/tidb/executor.(*ExecStmt).SummaryStmt.func1(0xd8, 0x10, 0x0, 0x0)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:1146 +0x71 fp=0xc1165b48d0 sp=0xc1165b4868 pc=0x2e3cd71
github.com/pingcap/tidb/util/stmtsummary.newStmtSummaryByDigestElement(0xc1a0ef7340, 0x6109df88, 0x708, 0x708)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:637 +0x32 fp=0xc1165b4948 sp=0xc1165b48d0 pc=0x1df7b32
github.com/pingcap/tidb/util/stmtsummary.(*stmtSummaryByDigest).add.func1(0xc0e7125300, 0xc1a0ef7340, 0x6109df88, 0x708, 0x18, 0x0, 0x3845d00)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:559 +0x1ca fp=0xc1165b49b8 sp=0xc1165b4948 pc=0x1dfceaa
github.com/pingcap/tidb/util/stmtsummary.(*stmtSummaryByDigest).add(0xc0e7125300, 0xc1a0ef7340, 0x6109df88, 0x708, 0x18)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:570 +0x53 fp=0xc1165b4a00 sp=0xc1165b49b8 pc=0x1df73b3
github.com/pingcap/tidb/util/stmtsummary.(*stmtSummaryByDigestMap).AddStatement(0xc000379c80, 0xc1a0ef7340)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:308 +0x1cd fp=0xc1165b4a68 sp=0xc1165b4a00 pc=0x1df584d
github.com/pingcap/tidb/executor.(*ExecStmt).SummaryStmt(0xc101372680, 0x5ec3a9f58e40001)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:1212 +0x9b9 fp=0xc1165b4c90 sp=0xc1165b4a68 pc=0x2c97eb9
github.com/pingcap/tidb/executor.(*ExecStmt).FinishExecuteStmt(0xc101372680, 0x5ec3a9f58e40020, 0x0, 0x0, 0xc0462d8a00)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:893 +0x150 fp=0xc1165b4db0 sp=0xc1165b4c90 pc=0x2c95350
github.com/pingcap/tidb/executor.(*ExecStmt).CloseRecordSet(0xc101372680, 0x5ec3a9f58e40020, 0x0, 0x0)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:917 +0x52 fp=0xc1165b4df0 sp=0xc1165b4db0 pc=0x2c95812
github.com/pingcap/tidb/executor.(*recordSet).Close(0xc07e2ed7c0, 0x0, 0x0)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:170 +0x79 fp=0xc1165b4e30 sp=0xc1165b4df0 pc=0x2c8f279
github.com/pingcap/tidb/session.(*execStmtResult).Close(0xc0462d89c0, 0x7, 0xc1165b4ee8)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/session/session.go:1685 +0x64 fp=0xc1165b4e90 sp=0xc1165b4e30 pc=0x2e8e6a4
github.com/pingcap/tidb/server.(*tidbResultSet).Close(0xc07e2ed810, 0x106b, 0x4000)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/driver_tidb.go:322 +0x4a fp=0xc1165b4eb8 sp=0xc1165b4e90 pc=0x30a898a
github.com/pingcap/tidb/server.ResultSet.Close-fm(0x0, 0xc1165b4f48)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/driver.go:73 +0x38 fp=0xc1165b4ee0 sp=0xc1165b4eb8 pc=0x30db678
github.com/pingcap/parser/terror.Call(0xc1165b5108)
	/nfs/cache/mod/github.com/pingcap/parser@v0.0.0-20210618053735-57843e8185c4/terror/terror.go:282 +0x3f fp=0xc1165b5060 sp=0xc1165b4ee0 pc=0x14a661f
github.com/pingcap/tidb/server.(*clientConn).handleStmt(0xc02d283b00, 0x3c13070, 0xc0427b6270, 0x3c2d7e8, 0xc0049f8000, 0x57e8de0, 0x0, 0x0, 0x1, 0x0, ...)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1733 +0x48c fp=0xc1165b5140 sp=0xc1165b5060 pc=0x309cfac
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc02d283b00, 0x3c13070, 0xc0427c0080, 0xc0e0b7c001, 0xc1, 0x0, 0x0)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1563 +0x492 fp=0xc1165b5280 sp=0xc1165b5140 pc=0x309af72
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc02d283b00, 0x3c13070, 0xc0427c0080, 0xc0e0b7c000, 0xc2, 0xc1, 0x0, 0x0)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1097 +0xafd fp=0xc1165b5628 sp=0xc1165b5280 pc=0x30962dd
github.com/pingcap/tidb/server.(*clientConn).Run(0xc02d283b00, 0x3c13118, 0xc063ed27b0)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:860 +0x296 fp=0xc1165b5e10 sp=0xc1165b5628 pc=0x30930f6
github.com/pingcap/tidb/server.(*Server).onConn(0xc00b269790, 0xc02d283b00)
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/server.go:485 +0xa7e fp=0xc1165b5fd0 sp=0xc1165b5e10 pc=0x30c66be
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc1165b5fd8 sp=0xc1165b5fd0 pc=0x113b221
created by github.com/pingcap/tidb/server.(*Server).Run
	/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/server.go:388 +0x8d5

```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.1
Edition: Community
Git Commit Hash: 797bddd25310ed42f0791c8eccb78be8cce2f502
Git Branch: heads/refs/tags/v5.1.1
UTC Build Time: 2021-07-28 11:00:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by qw4990** [comment]
This issue is hard to reproduce so that it's not easy to fix it.
I change its severity to moderate temporarily and I'll investigate it more detailedly next Sprint.
