### ISSUE TITLE
tableWorker in IndexLookUpExecutor panicked

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tidb#27090]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Error SQL is not seen in the log

`[distsql.go:988] ["tableWorker in IndexLookUpExecutor panicked"] [stack="goroutine 600103146 [running]:\ngithub.com/pingcap/tidb/executor.(*tableWorker).pickAndExecTask.func1(0x3c13070, 0xc042ec1680, 0xc02097bee0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/distsql.go:986 +0xbd\npanic(0x3282020, 0xc0638ca070)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action(0xc0211bcb70, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/memory/action.go:128 +0x198\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc053878d20, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0459759a0, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc031f92280, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc066ff6460, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc05888d450, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc04a3ed450, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc059cefae0, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc04809ff90, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc067df1ae0, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0482705f0, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc03c991680, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc054c9cd20, 0xc051d24f60)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1111 +0x112\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume(0xc057943b00, 0x1919018)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/memory/tracker.go:284 +0x14e\ngithub.com/pingcap/tidb/executor.(*tableWorker).executeTask(0xc03c9913b0, 0x3c13070, 0xc042ec1680, 0xc08988e000, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/distsql.go:1210 +0x3fc\ngithub.com/pingcap/tidb/executor.(*tableWorker).pickAndExecTask(0xc03c9913b0, 0x3c13070, 0xc042ec1680)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/distsql.go:1004 +0x18d\ngithub.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startTableWorker.func1(0x3c13070, 0xc042ec1680, 0xc03c9913b0, 0xc0039bd8c0, 0xc06b09b170)\n\t/home/jenkins/agent/"]`

### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.1
Edition: Community
Git Commit Hash: 797bddd25310ed42f0791c8eccb78be8cce2f502
Git Branch: heads/refs/tags/v5.1.1
UTC Build Time: 2021-07-28 11:00:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by jingshanglu** [comment]
@buggithubs plz add reproduce step.

**Comment by buggithubs** [comment]
I don't know why it happened

**Comment by wshwsh12** [comment]
Seems the sql use too much memory(higher than tidb_mem_quota_query, default 1GB) and be canceled by tidb. 
Please check https://docs.pingcap.com/zh/tidb/v5.0/system-variables#tidb_mem_quota_query, and set it to a suitable value if your sql will take up much memory.
