### ISSUE TITLE
set @@tidb_partition_prune_mode=dynamic; select on partition table occur：runtime error: index out of range [0] with length 0 

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#27138]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

```
tidb config：
new_collations_enabled_on_first_bootstrap: true
set @@tidb_partition_prune_mode=dynamic;

run case in test-store occasionally return runtime error，as example：
CREATE TABLE `tbl_57` (
  `col_421` int(10) unsigned NOT NULL DEFAULT '3758639830',
  `col_422` int(10) unsigned NOT NULL DEFAULT '3826861647',
  `col_423` tinyint(4) NOT NULL,
  `col_424` tinyint(1) DEFAULT '0',
  `col_425` mediumint(9) NOT NULL DEFAULT '4240187',
  `col_426` int(10) unsigned NOT NULL,
  PRIMARY KEY (`col_422`,`col_426`,`col_425`,`col_421`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `idx_153` (`col_425`,`col_422`,`col_426`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
PARTITION BY HASH( `col_426` )
PARTITIONS 6;

CREATE TABLE `tbl_6` (
  `col_60` bigint(20) NOT NULL DEFAULT '834857796083807900',
  `col_61` smallint(5) unsigned NOT NULL DEFAULT '54069',
  `col_62` tinyint(3) unsigned NOT NULL,
  `col_63` bigint(20) NOT NULL,
  PRIMARY KEY (`col_62`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_19` (`col_62`,`col_61`,`col_60`),
  UNIQUE KEY `idx_20` (`col_63`,`col_62`),
  UNIQUE KEY `idx_21` (`col_63`,`col_62`,`col_61`,`col_60`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY HASH( `col_62` )
PARTITIONS 4;

insert into tbl_6 values ( 5551131486488570493,30714,103,-3160924813791937135),
(  834857796083807900,54069,187, 7647064312752039910),
( 6490106460859994955,42954, 34, 6484496461754423263),
(-2025171219354699152,52610, 38, 8831712119229395973),
(   23049488252359670,20988, 46, 4993276021486800075),
(-5128741755203520498,54069, 86, 7157750022842014053),
( 4770612375500449232,19380,142, -436660579505771855),
(-4852522173008091817,21453,166,-4232305433215219525),
(-7842401711942922600,59764,206,-8191187360583069427),
(-4889281912548052276,46205,250, 2291777552629534554),
( 4725765248967897637,27003,124, 8832634197475791516),
(-7551864394026606715,65068,144, 7882224546356980182),
(-8305698872135230017,54069,180, 3210884386958065851),
(-1498862229213519351,61420, 17,-5675613122362797954),
(  834857796083807900,54069,105,-6091071206654813289),
( 2948856671717068268,30949,205, 2012640567897558196);

insert into tbl_57 values(1672191104, 291817299, -98,1,-5118292, 788846071),
(1351857708,1055340024,  46,1, 8328854,2882724529),
(4202703953,3125061462,  66,0,-8279103,2941583149),
(1582149383,4121533114,-111,0, 5383648,4080040483);

select  /*+ inl_join( tbl_57 , tbl_6 ) */ tbl_57.col_421, tbl_57.col_422, tbl_57.col_425, tbl_57.col_426 from tbl_57 where col_422 in ( select col_60 from tbl_6 where tbl_6.col_63 not in ( -8963729051841910951 , 5975997232963835503 , 5914794599953600479 , -1808364948456215574 , -4675517698310554586 ) ) order by tbl_57.col_421,tbl_57.col_422,tbl_57.col_423,tbl_57.col_424,tbl_57.col_425,tbl_57.col_426 limit 27;
```

### 2. What did you expect to see? (Required)
`
select return sucess`

### 3. What did you see instead (Required)

```
mysql> select  /*+ inl_join( tbl_57 , tbl_6 ) */ tbl_57.col_421, tbl_57.col_422, tbl_57.col_425, tbl_57.col_426 from tbl_57 where col_422 in ( select col_60 from tbl_6 where tbl_6.col_63 not in ( -8963729051841910951 , 5975997232963835503 , 5914794599953600479 , -1808364948456215574 , -4675517698310554586 ) ) order by tbl_57.col_421,tbl_57.col_422,tbl_57.col_423,tbl_57.col_424,tbl_57.col_425,tbl_57.col_426 limit 27;
ERROR 1105 (HY000): runtime error: index out of range [0] with length 0

tidb log as follow:
[2021/08/10 16:13:59.424 +00:00] [ERROR] [index_lookup_join.go:453] ["innerWorker panicked"] [conn=113] [stack="goroutine 148518 [running]:\ngithub.com/pingcap/tidb/executor.(*innerWorker).run.func1(0x4041048, 0xc0035b1e00, 0xc001bb5f30, 0xc00155d370)\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:451 +0xd7\npanic(0x3910240, 0xc00183ed38)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildTableReaderForIndexJoin(0xc00138a900, 0x4041048, 0xc0035b1e00, 0xc001b24fc0, 0xc002d29b00, 0x0, 0xf, 0xc001036638, 0x1, 0x1, ...)\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/builder.go:3580 +0x1b8f\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoinInternal(0xc00138a900, 0x4041048, 0xc0035b1e00, 0x40710f8, 0xc001b24fc0, 0xc002d29b00, 0x0, 0xf, 0xc001036638, 0x1, ...)\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/builder.go:3504 +0x43d\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoin(...)\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/builder.go:3497\ngithub.com/pingcap/tidb/executor.(*innerWorker).fetchInnerResults(0xc004458580, 0x4041048, 0xc0035b1e00, 0xc004088280, 0xc002d29b00, 0x0, 0xf, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:651 +0x145\ngithub.com/pingcap/tidb/executor.(*innerWorker).handleTask(0xc004458580, 0x4041048, 0xc0035b1e00, 0xc004088280, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:493 +0x155\ngithub.com/pingcap/tidb/executor.(*innerWorker).run(0xc004458580, 0x4041048, 0xc0035b1e00, 0xc00155d370)\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:470 +0x145\ncreated by github.com/pingcap/tidb/executor.(*IndexLookUpJoin).startWorkers\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:183 +0x205\n"]
[2021/08/10 16:13:59.425 +00:00] [INFO] [conn.go:995] ["command dispatched failed"] [conn=113] [connInfo="id:113, addr:172.18.136.5:46856 status:10, collation:utf8mb4_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="select  /*+ inl_join( tbl_57 , tbl_6 ) */ tbl_57.col_421, tbl_57.col_422, tbl_57.col_425, tbl_57.col_426 from tbl_57 where col_422 in ( select col_60 from tbl_6 where tbl_6.col_63 not in ( -8963729051841910951 , 5975997232963835503 , 5914794599953600479 , -1808364948456215574 , -4675517698310554586 ) ) order by tbl_57.col_421,tbl_57.col_422,tbl_57.col_423,tbl_57.col_424,tbl_57.col_425,tbl_57.col_426 limit 27"] [txn_mode=PESSIMISTIC] [err="runtime error: index out of range [0] with length 0\ngithub.com/pingcap/tidb/executor.(*innerWorker).run.func1\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:455\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:965\nruntime.goPanicIndex\n\t/usr/local/go/src/runtime/panic.go:88\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildTableReaderForIndexJoin\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/builder.go:3580\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoinInternal\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/builder.go:3504\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoin\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/builder.go:3497\ngithub.com/pingcap/tidb/executor.(*innerWorker).fetchInnerResults\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:651\ngithub.com/pingcap/tidb/executor.(*innerWorker).handleTask\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:493\ngithub.com/pingcap/tidb/executor.(*innerWorker).run\n\t/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:470\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"]
[2021/08/10 16:14:15.870 +00:00] [INFO] [grpclogger.go:69] ["ccResolverWrapper: sending new addresses to cc: [{http://clustered-a-piccpkia-pd-0.clustered-a-piccpkia-pd-peer.test-store.svc:2379  <nil> 0 <nil>}]"] [system=grpc] [grpc_log=true]
[2021/08/10 16:14:15.870 +00:00] [INFO] [grpclogger.go:69] ["Resolver state updated: {Addresses:[{Addr:http://clustered-a-piccpkia-pd-0.clustered-a-piccpkia-pd-peer.test-store.svc:2379 ServerName: Attributes:<nil> Type:0 Metadata:<nil>}] ServiceConfig:<nil> Attributes:<nil>} ()"] [system=grpc] [grpc_log=true]
```

### 4. What is your TiDB version? (Required)

```
 Release Version: v5.2.0-alpha-594-g542cce59b
Edition: Community
Git Commit Hash: 542cce59be58620af4ed5cd7369f7b901877a41f
Git Branch: HEAD
UTC Build Time: 2021-08-11 18:41:36
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by jingshanglu** [comment]
I can`t reproduce it, can you check it repeat?

**Comment by vivid392845427** [comment]
> I can`t reproduce it, can you check it repeat?

i can‘t reproduce it too，but the auto test case failed frequently on test-store

**Comment by vivid392845427** [comment]
> I can`t reproduce it, can you check it repeat?

i can reproduce it  after i execute set @@tidb_partition_prune_mode=dynamic;

**Comment by mjonss** [comment]
Still reproducable on master (a96deabe7e46385722cf96f7fc254de86fd5bd1a):
```
[2021/11/03 16:35:49.283 +01:00] [ERROR] [index_lookup_join.go:454] ["innerWorker panicked"] [conn=5] [stack="goroutine 5419 [running]:\ngithub.com/pingcap/tidb/executor.(*innerWorker).run.func1(0x4e1ff48, 0xc018221a00, 0xc000941f30, 0xc018206f50)\n\t/home/user/repos/tidb/executor/index_lookup_join.go:452 +0xd3\npanic(0x48214a0, 0xc0180922e8)\n\t/usr/lib/go-1.16/src/runtime/panic.go:971 +0x4c7\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildTableReaderForIndexJoin(0xc017a7f440, 0x4e1ff48, 0xc018221a00, 0xc018212d80, 0xc01794db00, 0x0, 0xf, 0xc018202870, 0x1, 0x1, ...)\n\t/home/user/repos/tidb/executor/builder.go:3665 +0x2e2c\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoinInternal(0xc017a7f440, 0x4e1ff48, 0xc018221a00, 0x4e46ef8, 0xc018212d80, 0xc01794db00, 0x0, 0xf, 0xc018202870, 0x1, ...)\n\t/home/user/repos/tidb/executor/builder.go:3589 +0x626\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoin(0xc017a7f440, 0x4e1ff48, 0xc018221a00, 0xc01794db00, 0x0, 0xf, 0xc018202870, 0x1, 0x1, 0xc018206d38, ...)\n\t/home/user/repos/tidb/executor/builder.go:3582 +0x165\ngithub.com/pingcap/tidb/executor.(*innerWorker).fetchInnerResults(0xc017a0ef20, 0x4e1ff48, 0xc018221a00, 0xc017fe4500, 0xc01794db00, 0x0, 0xf, 0x0, 0x0)\n\t/home/user/repos/tidb/executor/index_lookup_join.go:652 +0x254\ngithub.com/pingcap/tidb/executor.(*innerWorker).handleTask(0xc017a0ef20, 0x4e1ff48, 0xc018221a00, 0xc017fe4500, 0x0, 0x0)\n\t/home/user/repos/tidb/executor/index_lookup_join.go:494 +0x265\ngithub.com/pingcap/tidb/executor.(*innerWorker).run(0xc017a0ef20, 0x4e1ff48, 0xc018221a00, 0xc018206f50)\n\t/home/user/repos/tidb/executor/index_lookup_join.go:471 +0x2cd\ncreated by github.com/pingcap/tidb/executor.(*IndexLookUpJoin).startWorkers\n\t/home/user/repos/tidb/executor/index_lookup_join.go:184 +0x335\n"]
[2021/11/03 16:35:49.283 +01:00] [INFO] [conn.go:1058] ["command dispatched failed"] [conn=5] [connInfo="id:5, addr:127.0.0.1:57838 status:10, collation:utf8mb4_0900_ai_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="select  /*+ inl_join( tbl_57 , tbl_6 ) */ tbl_57.col_421, tbl_57.col_422, tbl_57.col_425, tbl_57.col_426 from tbl_57 where col_422 in ( select col_60 from tbl_6 where tbl_6.col_63 not in ( -8963729051841910951 , 5975997232963835503 , 5914794599953600479 , -1808364948456215574 , -4675517698310554586 ) ) order by tbl_57.col_421,tbl_57.col_422,tbl_57.col_423,tbl_57.col_424,tbl_57.col_425,tbl_57.col_426 limit 27"] [txn_mode=OPTIMISTIC] [err="runtime error: index out of range [0] with length 0\ngithub.com/pingcap/tidb/executor.(*innerWorker).run.func1\n\t/home/user/repos/tidb/executor/index_lookup_join.go:456\nruntime.gopanic\n\t/usr/lib/go-1.16/src/runtime/panic.go:971\nruntime.goPanicIndex\n\t/usr/lib/go-1.16/src/runtime/panic.go:88\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildTableReaderForIndexJoin\n\t/home/user/repos/tidb/executor/builder.go:3665\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoinInternal\n\t/home/user/repos/tidb/executor/builder.go:3589\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoin\n\t/home/user/repos/tidb/executor/builder.go:3582\ngithub.com/pingcap/tidb/executor.(*innerWorker).fetchInnerResults\n\t/home/user/repos/tidb/executor/index_lookup_join.go:652\ngithub.com/pingcap/tidb/executor.(*innerWorker).handleTask\n\t/home/user/repos/tidb/executor/index_lookup_join.go:494\ngithub.com/pingcap/tidb/executor.(*innerWorker).run\n\t/home/user/repos/tidb/executor/index_lookup_join.go:471\nruntime.goexit\n\t/usr/lib/go-1.16/src/runtime/asm_amd64.s:1371"]
```
