### ISSUE TITLE
v4.0.2 upgrade to v5.2.0 success, but report "panic in the recoverable goroutine" in log

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#27166]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

upgrade from v4.0.2 to v5.2.0, found following issue in tidb.log
```2021/08/12 19:59:53.128 +08:00] [ERROR] [misc.go:117] ["panic in the recoverable goroutine"] [label=domain] [funcInfo=updateStatsWorker] [r={}] [stack="goroutine 934 [running]:\ngithub.com/pingcap/tidb/util.GetStack(...)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/misc.go:78\ngithub.com/pingcap/tidb/util.Recover(0x39076b3, 0x6, 0x392788f, 0x11, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/misc.go:121 +0x2d5\npanic(0x3719220, 0xc002ac2090)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/statistics.decodeFeedbackForIndex(0xc000b8b6a0, 0xc002c2a000, 0xc002bb8900, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/feedback.go:908 +0x6ca\ngithub.com/pingcap/tidb/statistics.DecodeFeedback(0xc0040b0000, 0xf3, 0x3c000, 0xc000b8b6a0, 0xc002bb8900, 0x0, 0xc00141d200, 0x2400, 0x12000)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/feedback.go:991 +0x10d\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).handleSingleHistogramUpdate(0xc0010bd320, 0x3e45508, 0xc0015a9590, 0xc0040ec000, 0x520, 0x6a8, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/handle/update.go:802 +0x453\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).HandleUpdateStats.func1(0xc003c6d9e0, 0xc0010bd320, 0x3e45508, 0xc0015a9590, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/handle/update.go:710 +0x7e5\ngithub.com/pingcap/tidb/statistics/handle.(*Handle).HandleUpdateStats(0xc0010bd320, 0x3e45508, 0xc0015a9590, 0x0, 0x6)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/statistics/handle/update.go:731 +0x126\ngithub.com/pingcap/tidb/domain.(*Domain).updateStatsWorker(0xc001608f00, 0x3e4fd98, 0xc0000f2e00, 0x3e28f18, 0xc0010bd3b0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/domain/domain.go:1316 +0x925\ncreated by github.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/domain/domain.go:1181 +0x1d6\n"]```

cluster config:
            pd: |-
              replication.location-labels: ["zone", "host"] 
              enable-placement-rules: true
              enable-redact-log: true
              schedule.low-space-ratio: 0.9 
            tidb: |-
              oom-use-tmp-storage: false
              tmp-storage-quota: 8000000
              repair-mode: true
              new_collations_enabled_on_first_bootstrap: true
              tikv-client.enable-chunk-rpc: false
              tikv-client.store-liveness-timeout: "2s"
              stmt-summary.enable-internal-query: true
              prepared-plan-cache.enabled: true
              oom-action: cancel
              performance.max-memory: 5000
              performance.max-txn-ttl: 600000
              performance.query-feedback-limit: 1024
              tikv-client.copr-cache.admission-min-process-ms: 5
              alter-primary-key: true
              enable-streaming: true
            tikv: |-
              gc.enable-compaction-filter: false
              raftstore.early-apply: true
              rocksdb.rate-bytes-per-sec: 10GiB
              storage.block-cache.capacity: 24GiB

### 2. What did you expect to see? (Required)
no panic
### 3. What did you see instead (Required)
panic info

### 4. What is your TiDB version? (Required)

[2021/08/12 19:58:39.892 +08:00] [INFO] [printer.go:33] ["Welcome to TiDB."] ["Release Version"=v5.2.0] [Edition=Community] ["Git Commit Hash"=30cf15a59db11c34ffe05fc926152a43327eaa61] ["Git Branch"=heads/refs/tags/v5.2.0] ["UTC Build Time"="2021-08-09 12:01:42"] [GoVersion=go1.16.4] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]

**Comment by seiya-annie** [comment]
[tidb.log.gz](https://github.com/pingcap/tidb/files/6975631/tidb.log.gz)

**Comment by winoros** [comment]
We are going to refactor and re-test the feedback part. Thus move down the severity for now.
