### ISSUE TITLE
mycli connection error

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [pingcap/tidb#2770]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
mycli -u root -P 4000
```

2. What did you expect to see?
wish to see connect ok

3. What did you see instead?
```
Version: 1.7.1
Chat: https://gitter.im/dbcli/mycli
Mail: https://groups.google.com/forum/#!forum/mycli-users
Home: http://mycli.net
Thanks to the contributor - Tech Blue Software
Traceback (most recent call last):
  File "/Users/mmc/dev/python/python2/bin/mycli", line 11, in <module>
    sys.exit(cli())
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/mycli/main.py", line 767, in cli
    mycli.run_cli()
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/mycli/main.py", line 476, in run_cli
    document = self.cli.run(reset_current_buffer=True)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 399, in run
    self._redraw()
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 346, in _redraw
    self.renderer.render(self, self.layout, is_done=self.is_done)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/renderer.py", line 429, in render
    extended_height=size.rows,
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 142, in write_to_screen
    sizes = self._divide_heigths(cli, write_position)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 177, in _divide_heigths
    dimensions = [get_dimension_for_child(c, index) for index, c in enumerate(self.children)]
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 175, in get_dimension_for_child
    return c.preferred_height(cli, write_position.width, write_position.extended_height)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 395, in preferred_height
    return self.content.preferred_height(cli, width, max_available_height)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 128, in preferred_height
    dimensions = [c.preferred_height(cli, width, max_available_height) for c in self.children]
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/layout/containers.py", line 1649, in preferred_height
    if self.filter(cli):
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/filters/base.py", line 229, in __call__
    return self.func(*a, **kw)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/prompt_toolkit/shortcuts.py", line 150, in has_before_tokens
    for token, char in get_prompt_tokens(cli):
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/mycli/main.py", line 436, in prompt_tokens
    return [(Token.Prompt, self.get_prompt(self.prompt_format))]
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/mycli/main.py", line 676, in get_prompt
    string = string.replace('\\t', sqlexecute.server_type()[0] or 'mycli')
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/mycli/sqlexecute.py", line 200, in server_type
    cur.execute(self.version_query)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/Users/mmc/dev/python/python2/lib/python2.7/site-packages/pymysql/connections.py", line 970, in _read_packet
    (packet_number, self._next_seq_id))
pymysql.err.InternalError: Packet sequence number wrong - got 3 expected 1
```

here is the tidb error log
```
017/03/01 20:32:12 server.go:116: [info] [14] new connection [::1]:50080
2017/03/01 20:32:12 server.go:116: [info] [15] new connection [::1]:50081
2017/03/01 20:32:12 conn.go:356: [warning] [15] dispatch error:
id:15, addr:[::1]:50081 status:2, collation:utf8_general_ci, user:root
SHOW TABLES
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/executor/show.go:180: Can not find DB:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/executor/show.go:71:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/executor/adapter.go:64:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/server/driver_tidb.go:290:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/server/conn.go:714:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/server/conn.go:679:
2017/03/01 20:32:12 session.go:537: [warning] [15] compile error:
[schema:1146]Table 'INFORMATION_SCHEMA.ROUTINES' doesn't exist
SELECT ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES
    WHERE ROUTINE_TYPE="FUNCTION" AND ROUTINE_SCHEMA = "None"
2017/03/01 20:32:12 conn.go:356: [warning] [15] dispatch error:
id:15, addr:[::1]:50081 status:2, collation:utf8_general_ci, user:root
SELECT ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES
    WHERE ROUTINE_TYPE="FUNCTION" AND ROUTINE_SCHEMA = "None"
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/infoschema/infoschema.go:172: [schema:1146]Table 'INFORMATION_SCHEMA.ROUTINES' doesn't exist
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/plan/resolver.go:367:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/plan/resolver.go:35:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/plan/preprocess.go:26:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/executor/compiler.go:35:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/tidb.go:168:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/session.go:539:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/server/conn.go:661:
2017/03/01 20:32:12 server.go:193: [info] [15] close connection
2017/03/01 20:32:12 server.go:193: [info] [14] close connection
```

i use tidb-server rc2

4. What version of Go are you using (`go version`)?
```
go version go1.8 darwin/amd64
```

**Comment by coocood** [comment]
Thank you for your report!
We will take a look at it.

**Comment by breeswish** [comment]
Tested with latest mycli (v1.10.0) and works well. Except that an unknown error will be thrown in TiDB (which doesn't break mycli): https://github.com/pingcap/tidb/issues/3641

Could you try with latest mycli to see if it works for you?

**Comment by ziyouchutuwenwu** [comment]
yes, 1.11.0 fixed.
