### ISSUE TITLE
rails active record db:migrate error

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [pingcap/tidb#2771]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
create a rails orm model
```
rails g model Book name:string
```
then run
```
rake db:migrate
```

2. What did you expect to see?
wish the table automaticlly to be created.

3. What did you see instead?
rails console error and tidb-server error log
```
== 20170301132943 CreateBooks: migrating ======================================
-- create_table(:books)
   -> 0.0024s
== 20170301132943 CreateBooks: migrated (0.0025s) =============================

rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: line 8 column 6 near " (constraint_schema, constraint_name)
WHERE fk.referenced_column_name IS NOT NULL
  AND fk.table_schema = 'demo_development'
  AND fk.table_name = 'books'
" (total length 500): SELECT fk.referenced_table_name AS 'to_table',
       fk.referenced_column_name AS 'primary_key',
       fk.column_name AS 'column',
       fk.constraint_name AS 'name',
       rc.update_rule AS 'on_update',
       rc.delete_rule AS 'on_delete'
FROM information_schema.key_column_usage fk
JOIN information_schema.referential_constraints rc
USING (constraint_schema, constraint_name)
WHERE fk.referenced_column_name IS NOT NULL
  AND fk.table_schema = 'demo_development'
  AND fk.table_name = 'books'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/mysql/database_statements.rb:36:in `exec_query'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/mysql/database_statements.rb:10:in `select_all'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:520:in `foreign_keys'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:225:in `foreign_keys'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:97:in `block in tables'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:96:in `each'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:96:in `tables'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:37:in `dump'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:21:in `dump'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:253:in `block (4 levels) in <top (required)>'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:252:in `open'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:66:in `block (2 levels) in <top (required)>'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:59:in `block (2 levels) in <top (required)>'
/Users/mmc/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Mysql2::Error: line 8 column 6 near " (constraint_schema, constraint_name)
WHERE fk.referenced_column_name IS NOT NULL
  AND fk.table_schema = 'demo_development'
  AND fk.table_name = 'books'
" (total length 500)
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/mysql/database_statements.rb:36:in `exec_query'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/mysql/database_statements.rb:10:in `select_all'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:520:in `foreign_keys'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:225:in `foreign_keys'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:97:in `block in tables'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:96:in `each'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:96:in `tables'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:37:in `dump'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/schema_dumper.rb:21:in `dump'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:253:in `block (4 levels) in <top (required)>'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:252:in `open'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:66:in `block (2 levels) in <top (required)>'
/Users/mmc/.rvm/gems/ruby-2.4.0/gems/activerecord-5.0.1/lib/active_record/railties/databases.rake:59:in `block (2 levels) in <top (required)>'
/Users/mmc/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)
```

after i execute
```
rails g model Book name:string
```
20170301132943_create_books.rb
```
class CreateBooks < ActiveRecord::Migration[5.0]
  def change
    create_table :books do |t|
      t.string :name

      t.timestamps
    end
  end
end
```

then i execute
```
rake db:migrate
```
error info appeared

here is the tidb-server log
```
2017/03/01 21:31:03 metrics.go:322: [warning] [EXPENSIVE_QUERY] SELECT `schema_migrations`.* FROM `schema_migrations`
2017/03/01 21:31:03 session.go:523: [warning] [8] parse error:
line 8 column 6 near " (constraint_schema, constraint_name)
WHERE fk.referenced_column_name IS NOT NULL
  AND fk.table_schema = 'demo_development'
  AND fk.table_name = 'books'
" (total length 500)
SELECT fk.referenced_table_name AS 'to_table',
       fk.referenced_column_name AS 'primary_key',
       fk.column_name AS 'column',
       fk.constraint_name AS 'name',
       rc.update_rule AS 'on_update',
       rc.delete_rule AS 'on_delete'
FROM information_schema.key_column_usage fk
JOIN information_schema.referential_constraints rc
USING (constraint_schema, constraint_name)
WHERE fk.referenced_column_name IS NOT NULL
  AND fk.table_schema = 'demo_development'
  AND fk.table_name = 'books'

2017/03/01 21:31:03 conn.go:356: [warning] [8] dispatch error:
id:8, addr:127.0.0.1:49317 status:2, collation:utf8_general_ci, user:root
SELECT fk.referenced_table_name AS 'to_table',
       fk.referenced_column_name AS 'primary_key',
       fk.column_name AS 'column',
       fk.constraint_name AS 'name',
       rc.update_rule AS 'on_update',
       rc.delete_rule AS 'on_delete'
FROM information_schema.key_column_usage fk
JOIN information_schema.referential_constraints rc
USING (constraint_schema, constraint_name)
WHERE fk.referenced_column_name IS NOT NULL
  AND fk.table_schema = 'demo_development'
  AND fk.table_name = 'books'

line 8 column 6 near " (constraint_schema, constraint_name)
WHERE fk.referenced_column_name IS NOT NULL
  AND fk.table_schema = 'demo_development'
  AND fk.table_name = 'books'
" (total length 500)
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/parser/yy_parser.go:96:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/session.go:524:
/Users/mmc/dev/golang/3rdLibs/src/github.com/pingcap/tidb/server/conn.go:661:
2017/03/01 21:31:03 server.go:193: [info] [8] close connection
```

my tidb version is tidb-server rc2

4. What version of Go are you using (`go version`)?
```
go version go1.8 darwin/amd64
```

**Comment by shenli** [comment]
@ziyouchutuwenwu Thanks for your feedback!
"USING (constraint_schema, constraint_name)" is not supported now. We will work on it.

**Comment by morgo** [comment]
This syntax has been added to TiDB.  A minimal testcase:
```
CREATE TABLE t1 (id1 INT NOT NULL, id2 INT NOT NULL, PRIMARY KEY(id1,id2));
CREATE TABLE t2 (id1 INT NOT NULL, id2 INT NOT NULL, PRIMARY KEY(id1,id2));
INSERT INTO t1 VALUES (1,1),(2,2),(3,3);
INSERT INTO t2 VALUES (1,2),(2,2),(3,4);
SELECT t1.* FROM t1 INNER JOIN t2 USING (id1,id2);
```
Output:
```
mysql> CREATE TABLE t1 (id1 INT NOT NULL, id2 INT NOT NULL, PRIMARY KEY(id1,id2));
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE t2 (id1 INT NOT NULL, id2 INT NOT NULL, PRIMARY KEY(id1,id2));
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO t1 VALUES (1,1),(2,2),(3,3);
Query OK, 3 rows affected (0.00 sec)

mysql> INSERT INTO t2 VALUES (1,2),(2,2),(3,4);
Query OK, 3 rows affected (0.00 sec)

mysql> SELECT t1.* FROM t1 INNER JOIN t2 USING (id1,id2);
+-----+-----+
| id1 | id2 |
+-----+-----+
|   2 |   2 |
+-----+-----+
1 row in set (0.00 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-rc.3-219-g1e0876fe8-dirty
Git Commit Hash: 1e0876fe810a832721aac52275dd2b7792fd2892
Git Branch: flush
UTC Build Time: 2018-11-24 01:12:47
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by morgo** [comment]
I am going to close this issue for now, but please feel free to re-open if you have any questions.  Thanks!
