### ISSUE TITLE
Concurrent access to hash map SysVar.systems

### ISSUE THREAD

**Issue by dragonly** [pingcap/tidb#28026]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/33096/pipeline

```
...
[2021-09-13T13:41:20.535Z] goroutine 92 [running]:
[2021-09-13T13:41:20.535Z] runtime.throw(0x11c326e, 0x15)
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0001185c8 sp=0xc000118598 pc=0x43a5d2
[2021-09-13T13:41:20.535Z] runtime.mapassign_faststr(0x1046ea0, 0xc0005a1800, 0x11c84d5, 0x18, 0x0)
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc000118630 sp=0xc0001185c8 pc=0x4168b1
[2021-09-13T13:41:20.535Z] github.com/pingcap/tidb/sessionctx/variable.(*SysVar).SetSessionFromHook(0x1b43020, 0xc0005d4000, 0x11ab01e, 0x2, 0x0, 0x1ba1270)
[2021-09-13T13:41:20.535Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/sysvar.go:192 +0x78 fp=0xc000118688 sp=0xc000118630 pc=0xf371b8
[2021-09-13T13:41:20.535Z] github.com/pingcap/tidb/sessionctx/variable.(*SessionVars).SetSystemVar(0xc0005d4000, 0x11c84d5, 0x18, 0x11ab01e, 0x2, 0x11ab01e, 0x2)
[2021-09-13T13:41:20.535Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/session.go:1546 +0x6b fp=0xc0001186c8 sp=0xc000118688 pc=0xf3092b
[2021-09-13T13:41:20.535Z] github.com/pingcap/tidb/sessionctx/variable.SetSessionSystemVar(0xc0005d4000, 0x11c84d5, 0x18, 0x11aaeb0, 0x1, 0x498a86, 0x613f5415)
[2021-09-13T13:41:20.535Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/varsutil.go:214 +0x105 fp=0xc000118728 sp=0xc0001186c8 pc=0xf3c805
[2021-09-13T13:41:20.535Z] github.com/pingcap/tidb/sessionctx/variable_test.TestSetSystemVariable.func1(0xc0005bed80)
[2021-09-13T13:41:20.535Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/session_test.go:59 +0x7b fp=0xc000118780 sp=0xc000118728 pc=0xf6823b
[2021-09-13T13:41:20.535Z] testing.tRunner(0xc0005bed80, 0xc0005a8738)
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef fp=0xc0001187d0 sp=0xc000118780 pc=0x521c8f
[2021-09-13T13:41:20.535Z] runtime.goexit()
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0001187d8 sp=0xc0001187d0 pc=0x473a01
[2021-09-13T13:41:20.535Z] created by testing.(*T).Run
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.535Z] 
[2021-09-13T13:41:20.535Z] goroutine 1 [chan receive]:
[2021-09-13T13:41:20.535Z] testing.(*T).Run(0xc0005be480, 0x11c2f7a, 0x15, 0x121e528, 0x498a01)
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/testing/testing.go:1239 +0x2da
[2021-09-13T13:41:20.535Z] testing.runTests.func1(0xc0000ff380)
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/testing/testing.go:1511 +0x78
[2021-09-13T13:41:20.535Z] testing.tRunner(0xc0000ff380, 0xc000917cb0)
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-09-13T13:41:20.535Z] testing.runTests(0xc00000ee58, 0x1b4a880, 0x2a, 0x2a, 0xc047f36c71365921, 0x7dbc0bbc23, 0x1b71780, 0x1044b00)
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/testing/testing.go:1509 +0x2fe
[2021-09-13T13:41:20.535Z] testing.(*M).Run(0xc0008b4f80, 0x0)
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/testing/testing.go:1417 +0x1eb
[2021-09-13T13:41:20.535Z] go.uber.org/goleak.VerifyTestMain(0x134b8e0, 0xc0008b4f80, 0x0, 0x0, 0x0)
[2021-09-13T13:41:20.535Z] 	/nfs/cache/mod/go.uber.org/goleak@v1.1.10/testmain.go:53 +0x38
[2021-09-13T13:41:20.535Z] github.com/pingcap/tidb/sessionctx/variable.TestMain(0xc0008b4f80)
[2021-09-13T13:41:20.535Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/main_test.go:26 +0x50
[2021-09-13T13:41:20.535Z] main.main()
[2021-09-13T13:41:20.535Z] 	_testmain.go:193 +0x1f6
[2021-09-13T13:41:20.535Z] 
[2021-09-13T13:41:20.535Z] goroutine 86 [runnable]:
[2021-09-13T13:41:20.535Z] testing.tRunner.func1(0xc0005be480)
[2021-09-13T13:41:20.535Z] 	/usr/local/go/src/testing/testing.go:1159 +0x2bc
[2021-09-13T13:41:20.536Z] testing.tRunner(0xc0005be480, 0x121e528)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1197 +0x125
[2021-09-13T13:41:20.536Z] created by testing.(*T).Run
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.536Z] 
[2021-09-13T13:41:20.536Z] goroutine 90 [chan send]:
[2021-09-13T13:41:20.536Z] testing.tRunner.func1.1(0xc00090bed5, 0x0, 0x0, 0xc0005bea80, 0xc0005c7e01)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1123 +0x59
[2021-09-13T13:41:20.536Z] testing.tRunner.func1(0xc0005bea80)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1184 +0x405
[2021-09-13T13:41:20.536Z] testing.tRunner(0xc0005bea80, 0xc0005a8708)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1197 +0x125
[2021-09-13T13:41:20.536Z] created by testing.(*T).Run
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.536Z] 
[2021-09-13T13:41:20.536Z] goroutine 259 [runnable]:
[2021-09-13T13:41:20.536Z] sync.runtime_SemacquireMutex(0xc0005be484, 0x47f000, 0x1)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/runtime/sema.go:71 +0x47
[2021-09-13T13:41:20.536Z] sync.(*Mutex).lockSlow(0xc0005be480)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/sync/mutex.go:138 +0x105
[2021-09-13T13:41:20.536Z] sync.(*Mutex).Lock(...)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/sync/mutex.go:81
[2021-09-13T13:41:20.536Z] sync.(*RWMutex).Lock(0xc0005be480)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/sync/rwmutex.go:111 +0x90
[2021-09-13T13:41:20.536Z] testing.(*common).flushToParent(0xc0005bf800, 0xc0005d21b0, 0x2e, 0x11ba8d4, 0x10, 0xc00044de60, 0x3, 0x3)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:570 +0x65
[2021-09-13T13:41:20.536Z] testing.(*T).report(0xc0005bf800)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1446 +0x299
[2021-09-13T13:41:20.536Z] testing.tRunner.func1(0xc0005bf800)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1176 +0x39f
[2021-09-13T13:41:20.536Z] testing.tRunner(0xc0005bf800, 0xc0005a87e0)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1197 +0x125
[2021-09-13T13:41:20.536Z] created by testing.(*T).Run
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.536Z] 
[2021-09-13T13:41:20.536Z] goroutine 97 [chan send]:
[2021-09-13T13:41:20.536Z] testing.tRunner.func1.1(0xc00082eed5, 0x0, 0x0, 0xc0005bf500, 0xc0005c3601)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1123 +0x59
[2021-09-13T13:41:20.536Z] testing.tRunner.func1(0xc0005bf500)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1184 +0x405
[2021-09-13T13:41:20.536Z] testing.tRunner(0xc0005bf500, 0xc0005a87b0)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1197 +0x125
[2021-09-13T13:41:20.536Z] created by testing.(*T).Run
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.536Z] 
[2021-09-13T13:41:20.536Z] goroutine 96 [runnable]:
[2021-09-13T13:41:20.536Z] testing.(*T).Parallel(0xc0005bf380)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1059 +0x119
[2021-09-13T13:41:20.536Z] github.com/pingcap/tidb/sessionctx/variable_test.TestSetSystemVariable.func1(0xc0005bf380)
[2021-09-13T13:41:20.536Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/session_test.go:58 +0x45
[2021-09-13T13:41:20.536Z] testing.tRunner(0xc0005bf380, 0xc0005a8798)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-09-13T13:41:20.536Z] created by testing.(*T).Run
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.536Z] 
[2021-09-13T13:41:20.536Z] goroutine 95 [runnable]:
[2021-09-13T13:41:20.536Z] testing.(*T).Parallel(0xc0005bf200)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1059 +0x119
[2021-09-13T13:41:20.536Z] github.com/pingcap/tidb/sessionctx/variable_test.TestSetSystemVariable.func1(0xc0005bf200)
[2021-09-13T13:41:20.536Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/session_test.go:58 +0x45
[2021-09-13T13:41:20.536Z] testing.tRunner(0xc0005bf200, 0xc0005a8780)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-09-13T13:41:20.536Z] created by testing.(*T).Run
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.536Z] 
[2021-09-13T13:41:20.536Z] goroutine 258 [runnable]:
[2021-09-13T13:41:20.536Z] fmt.(*fmt).fmtFloat(0xc0001d4040, 0x3edd075dfe741ff4, 0x40, 0xc000000066, 0x6)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/fmt/format.go:490 +0x9ab
[2021-09-13T13:41:20.536Z] fmt.(*pp).fmtFloat(0xc0001d4000, 0x3edd075dfe741ff4, 0x40, 0xc000000066)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/fmt/print.go:408 +0x73
[2021-09-13T13:41:20.536Z] fmt.(*pp).printArg(0xc0001d4000, 0xff1ca0, 0xc0001d6130, 0x66)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/fmt/print.go:666 +0x351
[2021-09-13T13:41:20.536Z] fmt.(*pp).doPrintf(0xc0001d4000, 0x11ac0dd, 0x5, 0xc000451df0, 0x1, 0x1)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/fmt/print.go:1122 +0x3fc
[2021-09-13T13:41:20.536Z] fmt.Sprintf(0x11ac0dd, 0x5, 0xc0005c3df0, 0x1, 0x1, 0x100000000000030, 0x7f327b829868)
[2021-09-13T13:41:20.536Z] 	/usr/local/go/src/fmt/print.go:219 +0x66
[2021-09-13T13:41:20.536Z] testing.fmtDuration(0x1b09, 0xc0005c3e28, 0x0)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:625 +0xc8
[2021-09-13T13:41:20.537Z] testing.(*T).report(0xc0005bf680)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1438 +0x56
[2021-09-13T13:41:20.537Z] testing.tRunner.func1(0xc0005bf680)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1176 +0x39f
[2021-09-13T13:41:20.537Z] testing.tRunner(0xc0005bf680, 0xc0005a87c8)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1197 +0x125
[2021-09-13T13:41:20.537Z] created by testing.(*T).Run
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.537Z] 
[2021-09-13T13:41:20.537Z] goroutine 91 [runnable]:
[2021-09-13T13:41:20.537Z] testing.(*T).Parallel(0xc0005bec00)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1059 +0x119
[2021-09-13T13:41:20.537Z] github.com/pingcap/tidb/sessionctx/variable_test.TestSetSystemVariable.func1(0xc0005bec00)
[2021-09-13T13:41:20.537Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/session_test.go:58 +0x45
[2021-09-13T13:41:20.537Z] testing.tRunner(0xc0005bec00, 0xc0005a8720)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-09-13T13:41:20.537Z] created by testing.(*T).Run
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.537Z] 
[2021-09-13T13:41:20.537Z] goroutine 93 [runnable]:
[2021-09-13T13:41:20.537Z] testing.(*T).Parallel(0xc0005bef00)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1059 +0x119
[2021-09-13T13:41:20.537Z] github.com/pingcap/tidb/sessionctx/variable_test.TestSetSystemVariable.func1(0xc0005bef00)
[2021-09-13T13:41:20.537Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/session_test.go:58 +0x45
[2021-09-13T13:41:20.537Z] testing.tRunner(0xc0005bef00, 0xc0005a8750)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-09-13T13:41:20.537Z] created by testing.(*T).Run
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.537Z] 
[2021-09-13T13:41:20.537Z] goroutine 94 [runnable]:
[2021-09-13T13:41:20.537Z] testing.(*T).Parallel(0xc0005bf080)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1059 +0x119
[2021-09-13T13:41:20.537Z] github.com/pingcap/tidb/sessionctx/variable_test.TestSetSystemVariable.func1(0xc0005bf080)
[2021-09-13T13:41:20.537Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/session_test.go:58 +0x45
[2021-09-13T13:41:20.537Z] testing.tRunner(0xc0005bf080, 0xc0005a8768)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-09-13T13:41:20.537Z] created by testing.(*T).Run
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.537Z] 
[2021-09-13T13:41:20.537Z] goroutine 89 [runnable]:
[2021-09-13T13:41:20.537Z] sync.runtime_SemacquireMutex(0xc0008b68e4, 0xc0005c7600, 0x1)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/runtime/sema.go:71 +0x47
[2021-09-13T13:41:20.537Z] sync.(*Mutex).lockSlow(0xc0008b68e0)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/sync/mutex.go:138 +0x105
[2021-09-13T13:41:20.537Z] sync.(*Mutex).Lock(...)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/sync/mutex.go:81
[2021-09-13T13:41:20.537Z] testing.(*chattyPrinter).Updatef(0xc0008b68d0, 0xc0005d2060, 0x2c, 0x11b6c3b, 0xd, 0xc0005c7708, 0x1, 0x1)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:352 +0x11f
[2021-09-13T13:41:20.537Z] testing.(*T).Parallel(0xc0005be900)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1063 +0x227
[2021-09-13T13:41:20.537Z] github.com/pingcap/tidb/sessionctx/variable_test.TestSetSystemVariable.func1(0xc0005be900)
[2021-09-13T13:41:20.537Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/session_test.go:58 +0x45
[2021-09-13T13:41:20.537Z] testing.tRunner(0xc0005be900, 0xc0005a86f0)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-09-13T13:41:20.537Z] created by testing.(*T).Run
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.537Z] 
[2021-09-13T13:41:20.537Z] goroutine 88 [runnable]:
[2021-09-13T13:41:20.537Z] testing.(*T).Parallel(0xc0005be780)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1059 +0x119
[2021-09-13T13:41:20.537Z] github.com/pingcap/tidb/sessionctx/variable_test.TestSetSystemVariable.func1(0xc0005be780)
[2021-09-13T13:41:20.537Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/sessionctx/variable/session_test.go:58 +0x45
[2021-09-13T13:41:20.537Z] testing.tRunner(0xc0005be780, 0xc0005a86d8)
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-09-13T13:41:20.537Z] created by testing.(*T).Run
[2021-09-13T13:41:20.537Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-09-13T13:41:20.537Z] FAIL	github.com/pingcap/tidb/sessionctx/variable	0.056s
...
```

### 2. What did you expect to see? (Required)
test cases in `github.com/pingcap/tidb/sessionctx/variable` success

### 3. What did you see instead (Required)
they failed

### 4. What is your TiDB version? (Required)
@master

**Comment by dragonly** [comment]
I suspect it's due to the concurrent access to this function
https://github.com/pingcap/tidb/blob/master/sessionctx/variable/sysvar.go#L192

**Comment by tisonkun** [comment]
Duplicate of #27979

**Comment by dragonly** [comment]
In the long term, the code design should speak out loud that "I am (not) thread-safe", instead of guessing and hope it runs well.
