### ISSUE TITLE
pd panic when run sqllogic_test in test-store daily

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#28261]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
run testcase sqllogic_test as follow:

sqllogic_test -p=./test --parallel=64 --dsn="root:@tcp(sqllogic1-v52-1632222000-tidb:4000)/test"
```

### 2. What did you expect to see? (Required)

`testcase run successful`

### 3. What did you see instead (Required)

```
pd panic:
[2021/09/21 16:31:12.781 +00:00] [INFO] [cluster_worker.go:220] ["region batch split, generate new regions"] [region-id=2] [origin="id:16023 start_key:\"748000000000003EFF6C00000000000000F8\" end_key:\"748000000000003EFF7000000000000000F8\" region_epoch:<conf_ver:1 version:3491 > peers:<id:16024 store_id:1 >"] [total=1]
[2021/09/21 16:31:14.621 +00:00] [WARN] [cluster.go:544] ["store does not have enough disk space"] [store-id=1] [capacity=3937852530688] [available=484872437760]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1af4f0a]

goroutine 318 [running]:
github.com/tikv/pd/server.(*Handler).PackHistoryHotReadRegions(0xc0004b54d0, 0x1a93c53, 0xc0001ad920, 0xc000442a50, 0xc00360bea8, 0x1af4e92)
	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/handler.go:915 +0x4a
github.com/tikv/pd/server/core.(*HotRegionStorage).pullHotRegionInfo(0xc0004e0b00, 0xc00360bf01, 0x0)
	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/core/hot_region_storage.go:222 +0x38
github.com/tikv/pd/server/core.(*HotRegionStorage).backgroundFlush(0xc0004e0b00)
	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/core/hot_region_storage.go:182 +0x177
created by github.com/tikv/pd/server/core.NewHotRegionsStorage
	/home/jenkins/agent/workspace/build_pd_multi_branch_master/go/src/github.com/pingcap/pd/server/core/hot_region_storage.go:136 +0x21e
[2021/09/21 16:31:51.815 +00:00] [INFO] [util.go:42] ["Welcome to Placement Driver (PD)"]


cluster complete log：http://172.16.4.180:31714/archived-workflows/test-store/54c940e6-2272-48bd-865f-42dbafcc25ff?nodeId=sqllogic1-1632218400-4058239560
```

### 4. What is your TiDB version? (Required)
```
[2021/09/21 16:31:51.816 +00:00] [INFO] [util.go:43] [PD] [release-version=v5.3.0-alpha-24-gef40841f]
[2021/09/21 16:31:51.816 +00:00] [INFO] [util.go:44] [PD] [edition=Community]
[2021/09/21 16:31:51.816 +00:00] [INFO] [util.go:45] [PD] [git-hash=ef40841fee7f12c89c7562ae149013fb81a3e42b]
[2021/09/21 16:31:51.816 +00:00] [INFO] [util.go:46] [PD] [git-branch=master]
[2021/09/21 16:31:51.816 +00:00] [INFO] [util.go:47] [PD] [utc-build-time="2021-09-15 06:49:50"]
[2021/09/21 16:31:51.816 +00:00] [INFO] [metricutil.go:82] ["disable Prometheus push client"]

```

**Comment by nolouch** [comment]
fixed in https://github.com/tikv/pd/pull/4121.
