### ISSUE TITLE
lightning: "panic: interface conversion: kv.Rows is tidb.tidbRows, not *kv.KvPairs"

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb#28276]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Lightning import tpcc 10 warehouses csv data with tidb backend

### 2. What did you expect to see? (Required)
Import successfully

### 3. What did you see instead (Required)
```
panic: interface conversion: kv.Rows is tidb.tidbRows, not *kv.KvPairs
goroutine 1 [running]:
github.com/pingcap/tidb/br/pkg/lightning/backend/kv.KvPairsFromRows(...)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/kv/sql2kv.go:311
github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).sampleDataFromTable(0xc00052eb40, 0x4401a48, 0xc000cb8fc0, 0xc000f01748, 0x4, 0xc000f2a600, 0xc000f3fe00, 0x0, 0x0)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/check_info.go:836 +0x1a97
github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).estimateSourceData(0xc00052eb40, 0x4401a48, 0xc000cb8fc0, 0x0, 0x0, 0x7f55a0777328)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/check_info.go:410 +0x1c5
github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).preCheckRequirements(0xc00052eb40, 0x4401a48, 0xc000cb8fc0, 0xc000fb2540, 0xc000fb02a0)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/restore.go:1744 +0xba
github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).Run(0xc00052eb40, 0x4401a48, 0xc000cb8fc0, 0x1, 0x1)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/restore.go:419 +0x243
github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).run(0xc000cae580, 0x4401a80, 0xc00012e000, 0xc0007f1c00, 0x44268b0, 0xc000cd6cc0, 0x0, 0x0)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/lightning.go:322 +0xd47
github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).RunOnce(0xc000cae580, 0x4401a80, 0xc00012e000, 0xc0007f1c00, 0x0, 0x0, 0x3eba390, 0x11)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/lightning.go:192 +0xf5
main.main.func2(0xc000cc8000, 0xc000cae580, 0x0, 0xc00053e480)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/tidb-lightning/main.go:86 +0xab
main.main()
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/tidb-lightning/main.go:87 +0x572
```
lightning.log
```
[2021/09/22 16:25:10.648 +00:00] [INFO] [info.go:49] ["Welcome to TiDB-Lightning"] [release-version=v5.2.0-nightly] [git-hash=1e8b9337e3ef3cabba819fb562328fdca273c9ea] [git-branch=heads/refs/tags/v5.2.0-nightly] [go-version=go1.16.4] [utc-build-time="2021-09-22 13:40:30"] [race-enabled=false]
[2021/09/22 16:25:10.648 +00:00] [INFO] [lightning.go:222] [cfg] [cfg="{\"id\":1632327910648200918,\"lightning\":{\"table-concurrency\":28,\"index-concurrency\":28,\"region-concurrency\":28,\"io-concurrency\":5,\"check-requirements\":true,\"meta-schema-name\":\"\"},\"tidb\":{\"host\":\"upstream-tidb.brie-acceptance-f5wbr.svc\",\"port\":4000,\"user\":\"root\",\"status-port\":10080,\"pd-addr\":\"upstream-pd.brie-acceptance-f5wbr.svc:2379\",\"sql-mode\":\"ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER\",\"tls\":\"false\",\"security\":{\"ca-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"redact-info-log\":false},\"max-allowed-packet\":67108864,\"distsql-scan-concurrency\":15,\"build-stats-concurrency\":20,\"index-serial-scan-concurrency\":20,\"checksum-table-concurrency\":2},\"checkpoint\":{\"schema\":\"tidb_lightning_checkpoint\",\"driver\":\"file\",\"enable\":true,\"keep-after-success\":false},\"mydumper\":{\"read-block-size\":65536,\"batch-size\":0,\"batch-import-ratio\":0,\"data-source-dir\":\"s3://tpcc/10-warehouses-csv?access-key=minioadmin\\u0026secret-access-key=minioadmin\\u0026endpoint=http%3a%2f%2fminio.pingcap.net%3a9000\\u0026force-path-style=true\",\"character-set\":\"auto\",\"csv\":{\"separator\":\",\",\"delimiter\":\"\\\"\",\"terminator\":\"\",\"null\":\"\\\\N\",\"header\":false,\"trim-last-separator\":false,\"not-null\":false,\"backslash-escape\":true},\"max-region-size\":268435456,\"filter\":[\"*.*\",\"!mysql.*\",\"!sys.*\",\"!INFORMATION_SCHEMA.*\",\"!PERFORMANCE_SCHEMA.*\",\"!METRICS_SCHEMA.*\",\"!INSPECTION_SCHEMA.*\"],\"files\":null,\"no-schema\":false,\"case-sensitive\":false,\"strict-format\":false,\"default-file-rules\":true,\"ignore-data-columns\":null,\"data-character-set\":\"binary\",\"data-invalid-char-replace\":\"�\"},\"tikv-importer\":{\"addr\":\"\",\"backend\":\"tidb\",\"on-duplicate\":\"replace\",\"max-kv-pairs\":4096,\"send-kv-pairs\":32768,\"region-split-size\":0,\"sorted-kv-dir\":\"/tmp/sorted-kv-dir\",\"disk-quota\":9223372036854775807,\"range-concurrency\":0,\"duplicate-detection\":false,\"engine-mem-cache-size\":536870912,\"local-writer-mem-cache-size\":134217728},\"post-restore\":{\"checksum\":\"off\",\"analyze\":\"off\",\"level-1-compact\":false,\"post-process-at-last\":true,\"compact\":false},\"cron\":{\"switch-mode\":\"5m0s\",\"log-progress\":\"5m0s\",\"check-disk-quota\":\"1m0s\"},\"routes\":null,\"security\":{\"ca-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"redact-info-log\":false},\"black-white-list\":{\"do-tables\":null,\"do-dbs\":null,\"ignore-tables\":null,\"ignore-dbs\":null}}"]
[2021/09/22 16:25:10.660 +00:00] [INFO] [lightning.go:291] ["load data source start"]
[2021/09/22 16:25:10.689 +00:00] [INFO] [lightning.go:294] ["load data source completed"] [takeTime=29.019859ms] []
[2021/09/22 16:25:10.689 +00:00] [INFO] [checkpoints.go:977] ["open checkpoint file failed, going to create a new one"] [path=/tmp/tidb_lightning_checkpoint.pb] [error="open /tmp/tidb_lightning_checkpoint.pb: no such file or directory"]
[2021/09/22 16:25:10.703 +00:00] [INFO] [restore.go:413] ["the whole procedure start"]
[2021/09/22 16:25:10.706 +00:00] [INFO] [restore.go:717] ["restore all schema start"]
[2021/09/22 16:25:12.221 +00:00] [INFO] [restore.go:736] ["restore all schema completed"] [takeTime=1.514917398s] []
[2021/09/22 16:25:12.291 +00:00] [INFO] [tidb.go:337] ["skipping check requirements for tidb backend"]
[2021/09/22 16:25:12.298 +00:00] [INFO] [check_info.go:783] ["sample file start"] [table=customer]

```

### 4. What is your TiDB version? (Required)

```
 # /tidb-lightning -V
Release Version: v5.2.0-nightly
Git Commit Hash: 1e8b9337e3ef3cabba819fb562328fdca273c9ea
Git Branch: heads/refs/tags/v5.2.0-nightly
Go Version: go1.16.4
UTC Build Time: 2021-09-22 13:40:30
Race Enabled: false
```
```
***************************[ 1. row ]***************************
TYPE           | tidb
INSTANCE       | upstream-tidb-0.upstream-tidb-peer.brie-acceptance-f5wbr.svc:4000
STATUS_ADDRESS | upstream-tidb-0.upstream-tidb-peer.brie-acceptance-f5wbr.svc:10080
VERSION        | 5.2.0-nightly
GIT_HASH       | 1e8b9337e3ef3cabba819fb562328fdca273c9ea
START_TIME     | 2021-09-22T16:16:59Z
UPTIME         | 10h23m58.929398158s
SERVER_ID      | 0
***************************[ 2. row ]***************************
TYPE           | pd
INSTANCE       | upstream-pd-0.upstream-pd-peer.brie-acceptance-f5wbr.svc:2379
STATUS_ADDRESS | upstream-pd-0.upstream-pd-peer.brie-acceptance-f5wbr.svc:2379
VERSION        | 5.3.0-alpha
GIT_HASH       | c8014b53590cb8ea9955439a4b2bd4ef659a8224
START_TIME     | 2021-09-22T16:16:04Z
UPTIME         | 10h24m53.929406055s
SERVER_ID      | 0
***************************[ 3. row ]***************************
TYPE           | tikv
INSTANCE       | upstream-tikv-0.upstream-tikv-peer.brie-acceptance-f5wbr.svc:20160
STATUS_ADDRESS | 172.18.136.62:20180
VERSION        | 5.3.0-alpha
GIT_HASH       | ea1499fef40cbb77669fbce0314a7a6e16dcc0fe
START_TIME     | 2021-09-22T16:16:22Z
UPTIME         | 10h24m35.929408863s
SERVER_ID      | 0
```

**Comment by kennytm** [comment]
the offending line:

https://github.com/pingcap/tidb/blob/f2cf4cc7ca0c90f8fc4162d5b83e65a35ab25d98/br/pkg/lightning/restore/check_info.go#L836

how to fix: 

1. Reproduce a test case using a very small configured `SplitRegionSize`.
2. The "IsRowOrdered" and "IndexRatio" fields are useless to the TiDB(SQL) backend. Skip `sampleDataFromTable` if backend is not Local inside `estimateSourceData`.

**Comment by kennytm** [comment]
affects-master only. bug introduced by #27934.
