### ISSUE TITLE
Unstable test store_test.go fatal error: concurrent map writes

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28318]
```
[2021-09-24T16:52:41.182Z] fatal error: concurrent map writes
[2021-09-24T16:52:41.182Z] 
[2021-09-24T16:52:41.182Z] goroutine 1416 [running]:
[2021-09-24T16:52:41.182Z] runtime.throw(0x3bbc016, 0x15)
[2021-09-24T16:52:41.182Z] 	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0067e2678 sp=0xc0067e2648 pc=0x1232e72
[2021-09-24T16:52:41.182Z] runtime.mapassign_faststr(0x3741280, 0xc0003dcd80, 0x3b8de6f, 0x5, 0x5e668e0)
[2021-09-24T16:52:41.182Z] 	/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc0067e26e0 sp=0xc0067e2678 pc=0x120f131
[2021-09-24T16:52:41.182Z] github.com/pingcap/tidb/store.Register(0x3b8de6f, 0x5, 0x40568e0, 0x5e64400, 0x614e01bd, 0xb5a755a)
[2021-09-24T16:52:41.182Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/store.go:38 +0xb6 fp=0xc0067e2738 sp=0xc0067e26e0 pc=0x34d1dd6
[2021-09-24T16:52:41.182Z] github.com/pingcap/tidb/store.TestRegister(0xc005de7980)
[2021-09-24T16:52:41.182Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/store/store_test.go:794 +0x65 fp=0xc0067e2780 sp=0xc0067e2738 pc=0x34dbd05
[2021-09-24T16:52:41.182Z] testing.tRunner(0xc005de7980, 0x3c8f528)
[2021-09-24T16:52:41.182Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef fp=0xc0067e27d0 sp=0xc0067e2780 pc=0x1327e0f
[2021-09-24T16:52:41.182Z] runtime.goexit()
[2021-09-24T16:52:41.182Z] 	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0067e27d8 sp=0xc0067e27d0 pc=0x126da61
[2021-09-24T16:52:41.182Z] created by testing.(*T).Run
[2021-09-24T16:52:41.182Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
```

**Comment by tisonkun** [comment]
should be fixed by #28267
