### ISSUE TITLE
Leak test `pdutil.TestScheduler`

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#28816]
## Bug Report

```
[2021-10-14T07:19:31.756Z] goleak: Errors on successful test run: found unexpected goroutines:
[2021-10-14T07:19:31.756Z] [Goroutine 265 in state chan receive, with github.com/pingcap/tidb/br/pkg/pdutil.TestScheduler.func5 on top of the stack:
[2021-10-14T07:19:31.756Z] goroutine 265 [chan receive]:
[2021-10-14T07:19:31.756Z] github.com/pingcap/tidb/br/pkg/pdutil.TestScheduler.func5(0xc00060e2a0)
[2021-10-14T07:19:31.756Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/br/pkg/pdutil/pd_serial_test.go:74 +0x34
[2021-10-14T07:19:31.756Z] created by github.com/pingcap/tidb/br/pkg/pdutil.TestScheduler
[2021-10-14T07:19:31.756Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/br/pkg/pdutil/pd_serial_test.go:73 +0x825
[2021-10-14T07:19:31.756Z] ]
[2021-10-14T07:19:31.756Z] FAIL	github.com/pingcap/tidb/br/pkg/pdutil	0.674s
```

See https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/38433/pipeline

**Comment by unconsolable** [comment]
https://github.com/pingcap/tidb/blob/ae346a553088c56dc8c17f0e1a50c4008be59bc8/br/pkg/pdutil/pd_serial_test.go#L70-L76
IMHO this goroutine creation should be removed, as `pauseSchedulersAndConfigWith` success, it will create a goroutine and select on it.
https://github.com/pingcap/tidb/blob/ae346a553088c56dc8c17f0e1a50c4008be59bc8/br/pkg/pdutil/pd.go#L448-L450
Also, in (*PdController).Close(), it will close the chan and the `pdClient`. as in this scenario `pdClient` is nill, we can close the channel in defer.
