### ISSUE TITLE
Out of bound read in TiDB MySQL protocol refresh command

### ISSUE THREAD

**Issue by s3nt3** [pingcap/tidb#28949]
### 1. Minimal reproduce step (Required)

This is an out of bound read bug in TiDB MySQL protocol. You can reproduce it by send a malformed refresh command packet after authentication. The details of the malformed packet are as below:

```
+-----------------------+---------------------+------------------+
| body length (3 bytes) | packet seq (1 byte) | command (1 byte) |
+-----------------------+---------------------+------------------+
|       0x000001        |        0x00         |       0x07       | 
+-----------------------+---------------------+------------------+
```

### 2. What did you expect to see? (Required)

an error message but not a panic

### 3. What did you see instead (Required)

```
[2021/10/19 06:42:13.202 +00:00] [ERROR] [conn.go:919] ["connection running loop panic"] [conn=9] [lastSQL=Refresh] [err="runtime error: index out of range [0] with length 0"] [stack="goroutine 2314 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x4030
f90, 0xc0029759b0, 0xc002b70360)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:917 +0xf5\npanic(0x38ffc20, 0xc000857818)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/server.(*c
lientConn).dispatch(0xc002b70360, 0x4030ee8, 0xc002b49740, 0xc0029722f0, 0x1, 0x0, 0x0, 0x0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1220 +0x1a85\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc
002b70360, 0x4030f90, 0xc0029759b0)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:978 +0x296\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc0019be270, 0xc002b70360)\n\t/home/jenkins/agent/workspace/op
timization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/server.go:501 +0xa53\ncreated by github.com/pingcap/tidb/server.(*Server).startNetworkListener\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/se
rver.go:404 +0x8fc\n"]
```

### 4. What is your TiDB version? (Required)

```
MySQL [(none)]> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.2.1
Edition: Community
Git Commit Hash: cd8fb24c5f7ebd9d479ed228bb41848bd5e97445
Git Branch: heads/refs/tags/v5.2.1
UTC Build Time: 2021-09-08 02:32:56
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by bb7133** [comment]
I don't think this is a major bug since it can be reproduced by a 'malformed packet'.
