### ISSUE TITLE
randomly receive signal SIGSEGV in `executor` test 

### ISSUE THREAD

**Issue by unconsolable** [pingcap/tidb#29528]
### 1. Minimal reproduce step (Required)

Randomly in ci `tidb_ghpr_check_2`

### 2. What did you expect to see? (Required)

At least no signal SIGSEGV

### 3. What did you see instead (Required)

Receive signal SIGSEGV

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/43743/pipeline
```
[2021-11-06T12:51:29.308Z] panic: runtime error: invalid memory address or nil pointer dereference
[2021-11-06T12:51:29.308Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x3568d72]
[2021-11-06T12:51:29.308Z] 
[2021-11-06T12:51:29.308Z] goroutine 19551 [running]:
[2021-11-06T12:51:29.308Z] github.com/pingcap/tidb/session.(*LazyTxn).StartTS(0xc08c522a10, 0xc09110a7c8)
[2021-11-06T12:51:29.308Z] 	<autogenerated>:1 +0x32
[2021-11-06T12:51:29.308Z] github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource.func1(0x7f72c00681f8, 0xc090b92f00, 0xc000ab04e0, 0x48a7fe0, 0xc08c522a10)
[2021-11-06T12:51:29.308Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4163 +0x38
[2021-11-06T12:51:29.308Z] created by github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource
[2021-11-06T12:51:29.308Z] /home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4162 +0x2525
[2021-11-06T12:51:29.308Z] FAIL	github.com/pingcap/tidb/executor	4.885s
```
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/43740/pipeline/
```
[2021-11-06T11:25:20.737Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x35685f2]
[2021-11-06T11:25:20.737Z] 
[2021-11-06T11:25:20.737Z] goroutine 18877 [running]:
[2021-11-06T11:25:20.737Z] github.com/pingcap/tidb/session.(*LazyTxn).StartTS(0xc08a3a1810, 0xc07844efc8)
[2021-11-06T11:25:20.737Z] 	<autogenerated>:1 +0x32
[2021-11-06T11:25:20.737Z] github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource.func1(0x7f00bd9a4220, 0xc09352b540, 0xc000530680, 0x48a7c80, 0xc08a3a1810)
[2021-11-06T11:25:20.737Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4163 +0x38
[2021-11-06T11:25:20.737Z] created by github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource
[2021-11-06T11:25:20.737Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4162 +0x2525
[2021-11-06T11:25:20.737Z] FAIL	github.com/pingcap/tidb/executor	4.718s
```
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/43745/pipeline
```
[2021-11-06T13:05:44.124Z] panic: runtime error: invalid memory address or nil pointer dereference
[2021-11-06T13:05:44.124Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x3568d72]
[2021-11-06T13:05:44.124Z] 
[2021-11-06T13:05:44.124Z] goroutine 20594 [running]:
[2021-11-06T13:05:44.124Z] github.com/pingcap/tidb/session.(*LazyTxn).StartTS(0xc00961a210, 0xc004993140)
[2021-11-06T13:05:44.124Z] 	<autogenerated>:1 +0x32
[2021-11-06T13:05:44.124Z] github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource.func1(0x7fd6001aac68, 0xc05a972640, 0xc07ce7a1a0, 0x48a7fe0, 0xc00961a210)
[2021-11-06T13:05:44.124Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4163 +0x38
[2021-11-06T13:05:44.124Z] created by github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource
[2021-11-06T13:05:44.124Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4162 +0x2525
[2021-11-06T13:05:44.124Z] FAIL	github.com/pingcap/tidb/executor	5.559s
```

### 4. What is your TiDB version? (Required)

master, commit e897ba12ad1a080096d3b4af1e90e4177fd1ea9d

**Comment by unconsolable** [comment]
Another occurrence
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/43825/pipeline
```
[2021-11-07T04:44:52.591Z] panic: runtime error: invalid memory address or nil pointer dereference
[2021-11-07T04:44:52.591Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x35782fa]
[2021-11-07T04:44:52.591Z] 
[2021-11-07T04:44:52.591Z] goroutine 19364 [running]:
[2021-11-07T04:44:52.591Z] github.com/pingcap/tidb/session.(*LazyTxn).Iter(0xc0810b6210, 0xc08d8d0000, 0x9, 0x9, 0xc08d8d0020, 0x9, 0x9, 0x0, 0x0, 0xc08e298cc0, ...)
[2021-11-07T04:44:52.591Z] 	<autogenerated>:1 +0x3a
[2021-11-07T04:44:52.591Z] github.com/pingcap/tidb/table/tables.(*cachedTable).loadDataFromOriginalTable(0xc084e04c80, 0x48bffd0, 0xc0810b6200, 0x0, 0x0)
[2021-11-07T04:44:52.591Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/table/tables/cache.go:71 +0x2b3
[2021-11-07T04:44:52.591Z] github.com/pingcap/tidb/table/tables.(*cachedTable).UpdateLockForRead(0xc084e04c80, 0x48bffd0, 0xc0810b6200, 0x5f3e2ccef900002, 0x1331ab6, 0x437c520)
[2021-11-07T04:44:52.591Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/table/tables/cache.go:98 +0x45
[2021-11-07T04:44:52.591Z] github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource.func1(0x7fc038078af8, 0xc084e04c80, 0xc00080a1a0, 0x48b8e40, 0xc0810b6210)
[2021-11-07T04:44:52.591Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4163 +0x6c
[2021-11-07T04:44:52.591Z] created by github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource
[2021-11-07T04:44:52.591Z] 	/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4162 +0x2525
[2021-11-07T04:44:52.591Z] FAIL	github.com/pingcap/tidb/executor	5.460s
```

**Comment by JayL-zxl** [comment]
i already solved in https://github.com/pingcap/tidb/pull/29477. sorry my mistake
