### ISSUE TITLE
jdbc test faild with `runtime error: index out of range`

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#29570]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1.  git clone tidb-test
2. cd jdbc_test
2. start tidb, replace the host and port and run the following command.
```bash
 mvn "-Dcom.mysql.jdbc.testsuite.url=jdbc:mysql://$HOST:$PORT/test?user=root&useSSL=false&useServerPrepStmts=true" '-Dtest=CursorFetchTest' test
```

### 2. What did you expect to see? (Required)
execute successfully 
### 3. What did you see instead (Required)
```
RROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.475 s <<< FAILURE! - in pingcap.tidb.test.regression.CursorFetchTest
[ERROR] testBasicFetch(pingcap.tidb.test.regression.CursorFetchTest)  Time elapsed: 0.383 s  <<< ERROR!
java.sql.SQLException: runtime error: index out of range [0] with length 0
        at pingcap.tidb.test.regression.CursorFetchTest.testBasicFetch(CursorFetchTest.java:42)

[ERROR] testFetchPart(pingcap.tidb.test.regression.CursorFetchTest)  Time elapsed: 0.064 s  <<< ERROR!
java.sql.SQLException: runtime error: index out of range [0] with length 0
        at pingcap.tidb.test.regression.CursorFetchTest.testFetchPart(CursorFetchTest.java:67)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   CursorFetchTest.testBasicFetch:42 » SQL runtime error: index out of range [0] ...
[ERROR]   CursorFetchTest.testFetchPart:67 » SQL runtime error: index out of range [0] w...
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.309 s
[INFO] Finished at: 2021-11-08T18:15:53+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project tidb-jdbc-test: There are test failures.
[ERROR]
```
this maybe introduced by #28969, the test would be pass before this pr
### 4. What is your TiDB version? (Required)
```
╰─$ ./bin/tidb-server -V
Release Version: v5.4.0-alpha-40-gfdfba3e
Edition: Community
Git Commit Hash: fdfba3e4fafee8906d2dde6d737721608035aa6a
Git Branch: HEAD
UTC Build Time: 2021-11-08 10:14:53
GoVersion: go1.16.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by bb7133** [comment]
> cd https://github.com/pingcap/tidb-test/tree/master/jdbc_test

**Comment by aytrack** [comment]
testRowFetch also failed.
```bash
[2021-11-15T01:46:22.272Z] [ERROR] Tests run: 20, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.42 s <<< FAILURE! - in pingcap.tidb.test.simple.StatementsTest

[2021-11-15T01:46:22.272Z] [ERROR] testRowFetch(pingcap.tidb.test.simple.StatementsTest)  Time elapsed: 0.146 s  <<< ERROR!

[2021-11-15T01:46:22.272Z] java.sql.SQLException: runtime error: index out of range [0] with length 0

[2021-11-15T01:46:22.272Z] 	at pingcap.tidb.test.simple.StatementsTest.testRowFetch(StatementsTest.java:1102)


"Release Version"=v5.4.0-alpha-103-g8f7ed1405
```

**Comment by aytrack** [comment]
new faild in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/7450/pipeline/88
```bash
2021-11-22T09:09:04.315Z] Loading JDBC driver 'com.mysql.jdbc.Driver'
[2021-11-22T09:09:04.315Z] Connected to 5.7.25-TiDB-v5.4.0-alpha-176-ge2e6e5561
[2021-11-22T09:09:04.315Z] [ERROR] Tests run: 15, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.407 s <<< FAILURE! - in pingcap.tidb.test.regression.StringRegressionTest
[2021-11-22T09:09:04.315Z] [ERROR] testCodePage1252(pingcap.tidb.test.regression.StringRegressionTest)  Time elapsed: 0.041 s  <<< ERROR!
[2021-11-22T09:09:04.315Z] com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'field1' at row 1
[2021-11-22T09:09:04.315Z] 	at pingcap.tidb.test.regression.StringRegressionTest.testCodePage1252(StringRegressionTest.java:663)
```
