### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#29610]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
panic: send on closed channel [recovered]
        panic: send on closed channel

goroutine 766775274 [running]:
github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).handleHandlesFetcherPanic.func1(0x38f2ac0, 0x420f910)
        /home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:619 +0x205
github.com/pingcap/tidb/util.WithRecovery.func1(0xc2faf42f30)
        /home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/misc.go:92 +0x354
panic(0x38f2ac0, 0x420f910)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb/executor.(*partialTableWorker).syncErr(...)
        /home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:432
github.com/pingcap/tidb/executor.(*partialTableWorker).fetchHandles(0xc02cdabdd0, 0x429f548, 0xc2ec561ec0, 0xc17c86c720, 0xc13bf13320, 0xc13bf13200, 0xc17c86c5a0, 0x42cd6f8, 0xc2eb6c8d20, 0xa, ...)
        /home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:448 +0x678
github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startPartialTableWorker.func1.1()
        /home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:374 +0x5ba
github.com/pingcap/tidb/util.WithRecovery(0xc3295def08, 0xc2faf42f30)
        /home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/misc.go:100 +0x4f
github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startPartialTableWorker.func1(0x429f5f0, 0xc2f818d950, 0xc1e8ad8900, 0xc0ff91f0e0, 0x0, 0xc2f480d540, 0x1, 0x1, 0xc17c86c720, 0xc13bf13320)
        /home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:326 +0x1e5
created by github.com/pingcap/tidb/executor.(*IndexMergeReaderExecutor).startPartialTableWorker
        /home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/index_merge_reader.go:323 +0x238
```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.3.0
Edition: Community
Git Commit Hash: bdc9987370d6d393cb8acae22e238e3350e448b5
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-03 13:20:53
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by ChenPeng2013** [comment]
the default of tidb_enable_index_merge is off,  so the severity is set to major

**Comment by guo-shaoge** [comment]
Is this a failed ci log? Can we reproduce this error? @ChenPeng2013

**Comment by guo-shaoge** [comment]
Why we got the error: the partialIndexWorker go an error and it tries to give this error to the main worker through `resultCh`. But the `resultCh` is already closed(maybe Close() is called already).

Because there is too little log information, it is hard to get a more accurate conclusion. IMO, it's not a big problem.

**Comment by ChenPeng2013** [comment]
> Is this a failed ci log? Can we reproduce this error? @ChenPeng2013

I found it by tidb_error.log and don't have a way to reproduce

**Comment by guo-shaoge** [comment]
> > Is this a failed ci log? Can we reproduce this error? @ChenPeng2013
> 
> I found it by tidb_error.log and don't have a way to reproduce

I will update the pr and verify the fix.

**Comment by zanmato1984** [comment]
Adjusting severity to minor.

**Comment by guo-shaoge** [comment]
https://github.com/pingcap/tidb/pull/41036
this refactor pr can fix this.
