### ISSUE TITLE
br full backup failed

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#30142]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

full backup the dataset as #30135
```
/root/.tiup/components/br/v5.4.0-nightly-20211117/br restore full --pd xxx.xx.xx.xx:2495 --storage s3://xx/xxx/ --s3.endpoint http://xxx.xxx.net:9000 --send-credentials-to-tikv=true
```
### 2. What did you expect to see? (Required)

backup completed successfully

### 3. What did you see instead (Required)
```
Detail BR log in /tmp/br.log.2021-11-24T20.03.31+0800
Full restore <---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------.........Full restore <--------------------------------------------------------------------------------------------Full restore <---------------------------------------------------------------|....................> 75.52%bound pprof to addr [::]:46791
Full restore <---------------------------------------------------------------/....................> 75.52%panic: cannot pass gc safe point check, aborting

goroutine 709 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x401c024000, 0x4021a73000, 0x2, 0x2)
        /root/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x3e0
go.uber.org/zap.(*Logger).Panic(0x402e4a3f20, 0x34bf147, 0x29, 0x4021a73000, 0x2, 0x2)
        /root/go/pkg/mod/go.uber.org/zap@v1.19.1/logger.go:230 +0x74
github.com/pingcap/log.Panic(0x34bf147, 0x29, 0x4021a73000, 0x2, 0x2)
        /root/go/pkg/mod/github.com/pingcap/log@v0.0.0-20210906054005-afc726e70354/global.go:54 +0xd0
github.com/pingcap/tidb/br/pkg/utils.StartServiceSafePointKeeper.func1(0x4016187270, 0x40161872c0, 0x3971d90, 0x4000e20140, 0x39adc10, 0x4000e326c0, 0x4008d5c0f0, 0x27, 0x12c, 0x5f54751b274000a)
        /home/jenkins/workspace/build-linux-arm64-4.0/go/src/github.com/pingcap/br/br/pkg/utils/safe_point.go:129 +0x4d0
created by github.com/pingcap/tidb/br/pkg/utils.StartServiceSafePointKeeper
        /home/jenkins/workspace/build-linux-arm64-4.0/go/src/github.com/pingcap/br/br/pkg/utils/safe_point.go:113 +0x250
```
### 4. What is your TiDB version? (Required)

v5.3.0

**Comment by YuJuncen** [comment]
The Go runtime has been stuck by a `delve` debugger. Then BR found that the service GC safepoint has expired and the checksum may cannot be executed. So it chooses to suicide, as expected.

The behavior is defined by the `StartServiceSafePointKeeper`, which panics if it found that the service safepoint has expired. Maybe at restore side, we can make it softer (that is, not to panic but just fire a warning, also we need to change the checksum logic, when failed to checksum because of GC, only warn our user instead of exit.). cc @IANTHEREAL 

Anyway, the problem wouldn't happen normally, and its behavior is expected for now. I would close it for now, feel free to reopen it if something new need to be discussed.
