### ISSUE TITLE
wrong connect string makes tidb quit

### ISSUE THREAD

**Issue by feitian124** [pingcap/tidb#30198]
## Bug Report

i have below func to return mysql ConnectString.
```go
type Datasource struct {
	UserName string
	Passwd   string
	Host     string
	Port     int
	DBName   string
	Comment  string
}

func (ds *Datasource) ConnectString() string {
	return fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?parseTime=true", ds.UserName, ds.Passwd, ds.Host, ds.Port, ds.DBName)
}
```

when passwd is blank, the ConnectString is like `root:@tcp(127.0.0.1:4000)/testdb?parseTime=true"`,
notice the addtional `:` after `root`, this seems make tidb exit. i can not even connect with other mysql gui client.
the `tiup playground` log outputs:

```shell

tidb quit: exit status 2
[2021/11/28 02:52:58.686 +00:00] [INFO] [conn.go:1007] ["command dispatched failed"] [conn=11] [connInfo="id:11, addr:192.168.135.53:55622 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="/* ApplicationName=IntelliJ IDEA 2021.2.1 */ show create view PERFORMANCE_SCHEMA.pd_profile_block"] [txn_mode=PESSIMISTIC] [err="[executor:1347]'PERFORMANCE_SCHEMA.pd_profile_block' is not VIEW\ngithub.com/pingcap/errors.AddStack\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/normalize.go:159\ngithub.com/pingcap/tidb/executor.(*ShowExec).fetchShowCreateView\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/show.go:1170\ngithub.com/pingcap/tidb/executor.(*ShowExec).fetchAll\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/show.go:144\ngithub.com/pingcap/tidb/executor.(*ShowExec).Next\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/show.go:101\ngithub.com/pingcap/tidb/executor.Next\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/executor.go:285\ngithub.com/pingcap/tidb/executor.(*recordSet).Next\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:145\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Next\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/driver_tidb.go:305\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:2028\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1976\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1856\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1702\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1227\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:990\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/server.go:501\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"]
[2021/11/28 02:52:58.693 +00:00] [INFO] [conn.go:1007] ["command dispatched failed"] [conn=11] [connInfo="id:11, addr:192.168.135.53:55622 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="/* ApplicationName=IntelliJ IDEA 2021.2.1 */ show create view PERFORMANCE_SCHEMA.pd_profile_goroutines"] [txn_mode=PESSIMISTIC] [err="[executor:1347]'PERFORMANCE_SCHEMA.pd_profile_goroutines' is not VIEW\ngithub.com/pingcap/errors.AddStack\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20210425183316-da1aaba5fb63/normalize.go:159\ngithub.com/pingcap/tidb/executor.(*ShowExec).fetchShowCreateView\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/show.go:1170\ngithub.com/pingcap/tidb/executor.(*ShowExec).fetchAll\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/show.go:144\ngithub.com/pingcap/tidb/executor.(*ShowExec).Next\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/show.go:101\ngithub.com/pingcap/tidb/executor.Next\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/executor.go:285\ngithub.com/pingcap/tidb/executor.(*recordSet).Next\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/adapter.go:145\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Next\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/driver_tidb.go:305\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:2028\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1976\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1856\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1702\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1227\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:990\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/server.go:501\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"]
[2021/11/28 02:52:58.895 +00:00] [WARN] [session.go:1668] ["compile SQL failed"] [conn=11] [error="[schema:1146]Table 'mysql.procs_priv' doesn't exist"] [SQL="/* ApplicationName=IntelliJ IDEA 2021.2.1 */ select Host, User, Routine_name, Proc_priv, Routine_type = 'PROCEDURE' as is_proc\n      from mysql.procs_priv where Db = 'PERFORMANCE_SCHEMA';"]
[2021/11/28 02:52:58.895 +00:00] [INFO] [conn.go:1007] ["command dispatched failed"] [conn=11] [connInfo="id:11, addr:192.168.135.53:55622 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="/* ApplicationName=IntelliJ IDEA 2021.2.1 */ select Host, User, Routine_name, Proc_priv, Routine_type = 'PROCEDURE' as is_proc\n      from mysql.procs_priv where Db = 'PERFORMANCE_SCHEMA'; "] [txn_mode=PESSIMISTIC] [err="[schema:1146]Table 'mysql.procs_priv' doesn't exist"]
[2021/11/28 02:52:59.114 +00:00] [WARN] [session.go:1668] ["compile SQL failed"] [conn=11] [error="[schema:1146]Table 'mysql.procs_priv' doesn't exist"] [SQL="/* ApplicationName=IntelliJ IDEA 2021.2.1 */ select Host, User, Routine_name, Proc_priv, Routine_type = 'PROCEDURE' as is_proc\n      from mysql.procs_priv where Db = 'mysql';"]
[2021/11/28 02:52:59.114 +00:00] [INFO] [conn.go:1007] ["command dispatched failed"] [conn=11] [connInfo="id:11, addr:192.168.135.53:55622 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="/* ApplicationName=IntelliJ IDEA 2021.2.1 */ select Host, User, Routine_name, Proc_priv, Routine_type = 'PROCEDURE' as is_proc\n      from mysql.procs_priv where Db = 'mysql'; "] [txn_mode=PESSIMISTIC] [err="[schema:1146]Table 'mysql.procs_priv' doesn't exist"]
[2021/11/28 02:52:59.318 +00:00] [WARN] [session.go:1668] ["compile SQL failed"] [conn=11] [error="[schema:1146]Table 'mysql.procs_priv' doesn't exist"] [SQL="/* ApplicationName=IntelliJ IDEA 2021.2.1 */ select Host, User, Routine_name, Proc_priv, Routine_type = 'PROCEDURE' as is_proc\n      from mysql.procs_priv where Db = 'test';"]
[2021/11/28 02:52:59.318 +00:00] [INFO] [conn.go:1007] ["command dispatched failed"] [conn=11] [connInfo="id:11, addr:192.168.135.53:55622 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="/* ApplicationName=IntelliJ IDEA 2021.2.1 */ select Host, User, Routine_name, Proc_priv, Routine_type = 'PROCEDURE' as is_proc\n      from mysql.procs_priv where Db = 'test'; "] [txn_mode=PESSIMISTIC] [err="[schema:1146]Table 'mysql.procs_priv' doesn't exist"]
[2021/11/28 02:52:59.577 +00:00] [WARN] [session.go:1668] ["compile SQL failed"] [conn=11] [error="[schema:1146]Table 'mysql.procs_priv' doesn't exist"] [SQL="/* ApplicationName=IntelliJ IDEA 2021.2.1 */ select Host, User, Routine_name, Proc_priv, Routine_type = 'PROCEDURE' as is_proc\n      from mysql.procs_priv where Db = 'testdb';"]
[2021/11/28 02:52:59.577 +00:00] [INFO] [conn.go:1007] ["command dispatched failed"] [conn=11] [connInfo="id:11, addr:192.168.135.53:55622 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="/* ApplicationName=IntelliJ IDEA 2021.2.1 */ select Host, User, Routine_name, Proc_priv, Routine_type = 'PROCEDURE' as is_proc\n      from mysql.procs_priv where Db = 'testdb'; "] [txn_mode=PESSIMISTIC] [err="[schema:1146]Table 'mysql.procs_priv' doesn't exist"]
...
check detail log from: /home/ubuntu/.tiup/data/Sq1Vt4g/tidb-0/tidb.log

```

`/home/ubuntu/.tiup/data/Sq1Vt4g/tidb-0/tidb.log` is below:

[tidb.log](https://github.com/pingcap/tidb/files/7612751/tidb.log)

### 1. Minimal reproduce step (Required)

see above. or reproduce as below:
- git clone https://github.com/tigql/tigql.git
- git checkout `e2bb5c6e983e9880ff2296dd798ed8bf207dcc33` (commit msg should be `try test tidb52 but failed`)
- make install
- make test

there are other sqls supported by mysql but not tidb cause errors, but i believe the root case should be connect string.

### 2. What did you expect to see? (Required)

even though connect string is wrong, tidb should not quit.

### 3. What did you see instead (Required)

wrong connect string seems make tidb exit. i can not even connect with other mysql gui client.

### 4. What is your TiDB version? (Required)

tidb 5.2.2 with tiup playground
connect with sqlx v1.3.4 `db, err := sqlx.Open("mysql", ds.ConnectString())`
```shell

ubuntu@ubuntu20server:~$ tiup playground --db.Host 0.0.0.0
Starting component `playground`: /home/ubuntu/.tiup/components/playground/v1.7.0/tiup-playground --db.Host 0.0.0.0
Using the version v5.2.2 for version constraint "".

If you'd like to use a TiDB version other than v5.2.2, cancel and retry with the following arguments:
        Specify version manually:   tiup playground <version>
        Specify version range:      tiup playground ^5
        The nightly version:        tiup playground nightly

```

**Comment by feitian124** [comment]
@tiancaiamao @disksing please have a look, this may related to security.

**Comment by feitian124** [comment]
sorry, checked again with a simpler query `select version();`, it does not quit...
```go
root:@tcp(192.168.135.154:4000)/testdb?parseTime=true
5.7.25-TiDB-v5.2.2
```
it should be other problem.

**Comment by feitian124** [comment]
fatal error: concurrent map writes

```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 3906 [running]:
runtime.throw(0x3b377b0, 0x15)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00143ae30 sp=0xc00143ae00 pc=0x1217fd2
runtime.mapassign_fast64ptr(0x36bfb80, 0xc0013977a0, 0xc001129200, 0xc0028b0100)
	/usr/local/go/src/runtime/map_fast64.go:266 +0x332 fp=0xc00143ae70 sp=0xc00143ae30 pc=0x11f2cf2
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildDataSource(0xc000192ea0, 0x4038470, 0xc001397620, 0xc002f74210, 0xc001c9c078, 0xffffffff0000ff00, 0x1, 0x192, 0x192)
```
