### ISSUE TITLE
 oom-action: cancel, tidb report "outerWorker panicked"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#30498]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

upgrade from v3.0.0 to v4.0.16
run tpch:
 /data-sdb/tools/go-tpc/bin/go-tpc tpch -H 172.16.5.101 -P 4000 -D tpch --sf 1  prepare
 /data-sdb/tools/go-tpc/bin/go-tpc tpch -H 172.16.5.101 -P 4000 -D tpch run --time 600s 
 
config:     
  tidb:
    alter-primary-key: true
    enable-streaming: false
    log.query-log-max-len: 2048
    mem-quota-query: 1000000
    oom-action: cancel
    performance.feedback-probability: 0.05
    performance.max-memory: 0
    performance.query-feedback-limit: 1024
    pessimistic-txn.enable: true
    stmt-summary.enable: false
    store: mocktikv
    tikv-client.grpc-connection-count: 16

occur only when OOM, if Increase the value of "mem-quota-query", will not panic.
but " oom-action" is " cancel", should cancel the query instead of panic, right?

### 2. What did you expect to see? (Required)
no panic

### 3. What did you see instead (Required)
[2021/12/07 21:52:20.210 +08:00] [INFO] [row_container.go:311] ["memory exceeds quota, spill to disk now."] [consumed=70261815] [quota=1000000]
[2021/12/07 21:52:20.215 +08:00] [INFO] [coprocessor.go:1381] ["memory exceeds quota, rateLimitAction delegate to fallback action"] ["total token count"=1]
[2021/12/07 21:52:20.215 +08:00] [INFO] [row_container.go:311] ["memory exceeds quota, spill to disk now."] [consumed=70149971] [quota=1000000]
[2021/12/07 21:52:20.215 +08:00] [INFO] [row_container.go:311] ["memory exceeds quota, spill to disk now."] [consumed=70413707] [quota=1000000]

[2021/12/07 21:52:20.217 +08:00] [ERROR] [index_lookup_join.go:357] ["outerWorker panicked"] [conn=33] [stack="goroutine 154057 [running]:\ngithub.com/pingcap/tidb/executor.(*outerWorker).run.func1(0x39169a0, 0xc001872c40, 0xc00305ac60, 0xc000c93b24)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:355 +0x103\npanic(0x2efb3e0, 0xc009dead90)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action(0xc00378ccf0, 0xc00386bd40)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/memory/action.go:128 +0x198\ngithub.com/pingcap/tidb/util/chunk.(*SpillDiskAction).Action(0xc002e2d080, 0xc00386bd40)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/chunk/row_container.go:337 +0x121\ngithub.com/pingcap/tidb/util/chunk.(*SpillDiskAction).Action(0xc003addf80, 0xc00386bd40)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/chunk/row_container.go:337 +0x121\ngithub.com/pingcap/tidb/util/chunk.(*SpillDiskAction).Action(0xc003add3e0, 0xc00386bd40)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/chunk/row_container.go:337 +0x121\ngithub.com/pingcap/tidb/util/chunk.(*SpillDiskAction).Action(0xc003add1a0, 0xc00386bd40)\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/util/chunk/row_container.go:337 +0x121\ngithub.com/pingcap/tidb/util/chunk.(*SpillDiskAction
[tidb.log.gz](https://github.com/pingcap/tidb/files/7668877/tidb.log.gz)

### 4. What is your TiDB version? (Required)
4.0.16
["Git Commit Hash"=75f81d2d7faae72575c4e471ec0b96756796284a]

**Comment by XuHuaiyu** [comment]
Expected behavior, not a bug.
TiDB uses `(*PanicOnExceed).Action` to make the cancel operation. It will trigger panic but not affect the server.
