### ISSUE TITLE
annoying output of "[grpc_log=true]"

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#30592]
## General Question

In TiDB 5.1.1, I find this log every minute, it's annoying...

```
[2021/12/09 20:39:13.476 +08:00] [INFO] [grpclogger.go:79] ["ccResolverWrapper: sending new addresses to cc: [{http://127.0.0.1:2379  <nil> 0 <nil>}]"] [system=grpc] [grpc_log=true]
```

I googled and find grpclogger.go is in `github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/grpclogger.go` this package.

Then `go mod why` tell me `tidb/util/logutil` introduce this package

```
$ go mod why github.com/grpc-ecosystem/go-grpc-middleware/logging/zap
# github.com/grpc-ecosystem/go-grpc-middleware/logging/zap
github.com/pingcap/tidb/util/logutil
github.com/grpc-ecosystem/go-grpc-middleware/logging/zap
```

And I print the call stack:

```
goroutine 377 [running]:
runtime/debug.Stack(0x7ff3f83d2f70, 0x7ff3f8340f90, 0x10)
        /home/genius/project/go/src/runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        /home/genius/project/go/src/runtime/debug/stack.go:16 +0x25
github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.(*zapGrpcLoggerV2).Infof(0xc00091bb40, 0x37bc4aa, 0x32, 0xc0010a91f0, 0x1, 0x1)
        /home/genius/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/logging/zap/grpclogger.go:78 +0x26
google.golang.org/grpc/grpclog.Infof(...)
        /home/genius/go/pkg/mod/google.golang.org/grpc@v1.27.1/grpclog/grpclog.go:45
google.golang.org/grpc.(*ccResolverWrapper).NewAddress(0xc00080e240, 0xc000e4f280, 0x1, 0x1)
        /home/genius/go/pkg/mod/google.golang.org/grpc@v1.27.1/resolver_conn_wrapper.go:199 +0xf7
go.etcd.io/etcd/clientv3/balancer/resolver/endpoint.(*ResolverGroup).SetEndpoints(0xc00080e060, 0xc0010a91e0, 0x1, 0x1)
        /home/genius/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200824191128-ae9734ed278b/clientv3/balancer/resolver/endpoint/endpoint.go:89 +0xfe
go.etcd.io/etcd/clientv3.(*Client).SetEndpoints(0xc0008ac340, 0xc0010a91e0, 0x1, 0x1)
        /home/genius/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200824191128-ae9734ed278b/clientv3/client.go:166 +0xaf
go.etcd.io/etcd/clientv3.(*Client).Sync(0xc0008ac340, 0x3c143c0, 0xc00143d560, 0x3c143c0, 0xc00143d560)
        /home/genius/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200824191128-ae9734ed278b/clientv3/client.go:179 +0x1d7
go.etcd.io/etcd/clientv3.(*Client).autoSync(0xc0008ac340)
        /home/genius/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200824191128-ae9734ed278b/clientv3/client.go:194 +0x15e
created by go.etcd.io/etcd/clientv3.newClient
        /home/genius/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200824191128-ae9734ed278b/clientv3/client.go:497 +0xce5
```

It's called in etcd client...

**Comment by tiancaiamao** [comment]
It's here... in the grpc package https://github.com/grpc/grpc-go/blame/a10661dd0a44abcdf594ef91224e65d7785dfabe/resolver_conn_wrapper.go#L171

**Comment by tiancaiamao** [comment]
Great, I find it's already done in https://github.com/pingcap/tidb/pull/27238
