### ISSUE TITLE
unstable test TestHashInTopN

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#30676]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2021-12-13T15:03:13.233Z] --- FAIL: TestHashInTopN (9.89s)
[2021-12-13T15:03:13.233Z] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[2021-12-13T15:03:13.233Z] 	panic: runtime error: invalid memory address or nil pointer dereference
[2021-12-13T15:03:13.233Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x37e3c92]
[2021-12-13T15:03:13.233Z] 
[2021-12-13T15:03:13.233Z] goroutine 9580 [running]:
[2021-12-13T15:03:13.233Z] testing.tRunner.func1.2(0x3da1b60, 0x6168660)
[2021-12-13T15:03:13.233Z] 	/usr/local/go/src/testing/testing.go:1143 +0x332
[2021-12-13T15:03:13.233Z] testing.tRunner.func1(0xc006291080)
[2021-12-13T15:03:13.233Z] 	/usr/local/go/src/testing/testing.go:1146 +0x4b6
[2021-12-13T15:03:13.233Z] panic(0x3da1b60, 0x6168660)
[2021-12-13T15:03:13.233Z] 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
[2021-12-13T15:03:13.233Z] github.com/pingcap/tidb/executor_test.TestHashInTopN(0xc006291080)
[2021-12-13T15:03:13.233Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/analyze_test.go:770 +0x5f2
[2021-12-13T15:03:13.233Z] testing.tRunner(0xc006291080, 0x43ed508)
[2021-12-13T15:03:13.233Z] 	/usr/local/go/src/testing/testing.go:1193 +0xef
[2021-12-13T15:03:13.233Z] created by testing.(*T).Run
[2021-12-13T15:03:13.233Z] 	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[2021-12-13T15:03:13.233Z] FAIL	github.com/pingcap/tidb/executor	413.186s
```
https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/24571/nodes/52/log/?start=0

**Comment by yudongusa** [comment]
@XuHuaiyu it seems this is the fail from executor testing, could you confirm? github.com/pingcap/tidb/executor_test.TestHashInTopN

**Comment by Reminiscent** [comment]
Related to https://github.com/pingcap/tidb/pull/30708
We try to disable the parallel for the test to see whether the error still happens.

**Comment by Reminiscent** [comment]
https://github.com/pingcap/tidb/pull/30692 This PR has been already disabled the parallel. Maybe we can close this PR until it happens again.
