### ISSUE TITLE
mysql.ComStmtFetch occurs index out of range

### ISSUE THREAD

**Issue by 7yyo** [pingcap/tidb#30896]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```java
   public static void main(String[] args) throws ClassNotFoundException, SQLException {

        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:4000/test?useServerPrepStmts=true&cachePrepStmts=true&useCursorFetch=true", "root", "");

        conn.setAutoCommit(false);
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, 1);
        ps.setFetchSize(1000);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            System.out.println(rs.getString("id"));
        }
        rs.close();
        ps.close();
        conn.close();
    }
```

```sql
mysql> show create table t;
+-------+------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                               |
+-------+------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select * from t;
+------+
| id   |
+------+
|    1 |
|    2 |
+------+
2 rows in set (0.00 sec)
```

### 2. What did you expect to see? (Required)

`1`

### 3. What did you see instead (Required)

```java
Exception in thread "main" java.sql.SQLException: runtime error: index out of range [0] with length 0
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.result.ResultSetImpl.next(ResultSetImpl.java:1753)
	at prepared.Prepared.main(Prepared.java:18)
```

### 4. What is your TiDB version? (Required)

`Master`

I guess the panic is caused by this line of code:  https://github.com/pingcap/tidb/blob/master/server/conn.go#L2211

**Comment by bb7133** [comment]
Very likely that it is introduced by #30285 , @xhebox PTAL.
