### ISSUE TITLE
v5.4.0/v6.0.0 stability test, one or 4 tidb instance stopped and can not startup

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#31477]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run benchmarksql 1000 warehouses for 7 day to test the stability
plateform: arm64

### 2. What did you expect to see? (Required)
no tidb instance restart

### 3. What did you see instead (Required)
one tidb instance stopped and can not startup
![image](https://user-images.githubusercontent.com/2316425/148639765-615cb150-03dd-449a-8053-08cfda381696.png)

no log in tidb.log and tidb_stderr.log. It's not an oom issue(confirmed with dmesg).
```
[root@tidb-3-0 log]# tail -10 tidb.log
[2022/01/08 17:03:21.800 +08:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=38.616283ms]
[2022/01/08 17:03:21.800 +08:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=32.265853ms]
[2022/01/08 17:03:21.800 +08:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=38.016864ms]
[2022/01/08 17:03:21.800 +08:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=32.461766ms]
[2022/01/08 17:03:21.801 +08:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=32.548927ms]
[2022/01/08 17:03:21.797 +08:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=42.484387ms]
[2022/01/08 17:03:21.801 +08:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=32.03508ms]
[2022/01/08 17:03:21.801 +08:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=31.246459ms]
[2022/01/08 17:03:21.801 +08:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=30.268075ms]
[2022/01/08 17:03:21.800 +08:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=38.107935ms]
```

the tidb seems get stuck in the runtime.gentraceback

```
[root@tidb-3-0 FlameGraph]# ps -ef | grep tidb-server
tidb      1916     1 99 Jan07 ?        10-20:56:54 bin/tidb-server -P 14000 --status=20080 --host=0.0.0.0 --advertise-address=tidb-3-peer --store=tikv --path=pd-peer:12379 --log-slow-query=/tiup/deploy/tidb-14000/log/tidb_slow_query.log --config=conf/tidb.toml --log-file=/tiup/deploy/tidb-14000/log/tidb.log
root      2566  2440  0 17:45 pts/0    00:00:00 grep --color=auto tidb-server
[root@tidb-3-0 FlameGraph]# perf top -p 1916
Samples: 6  of event 'cycles', 4000 Hz, Event count (approx.): 7930 lost: 0/0 drop: 0/0                                                                                                      
Overhead  Shared Obje  Symbol                                                                                                                                                                
  97.59%  tidb-server  [.] runtime.gentraceback
   2.41%  tidb-server  [.] runtime.findfunc
```

### 4. What is your TiDB version? (Required)

v5.4.0

**Comment by qw4990** [comment]
We cannot reproduce this issue now since the environment has already been released. After discussing it with related QA and R&D, we decided to degrade its severity to `moderate`.

**Comment by dbsid** [comment]
this issue happens again duration v6.0.0 stability test, raise the severity to critical
4 tidb instances restarted during the test and tiup/promtheus can not detect the tidb status.

```
[root@tiup-0 ~]# tiup cluster display debug
tiup is checking updates for component cluster ...
Starting component `cluster`: /root/.tiup/components/cluster/v1.9.2/tiup-cluster /root/.tiup/components/cluster/v1.9.2/tiup-cluster display debug
Cluster type:       tidb
Cluster name:       debug
Cluster version:    v6.0.0
Deploy user:        tidb
SSH type:           builtin
Dashboard URL:      http://pd-peer:2379/dashboard
ID                 Role          Host         Ports        OS/Arch        Status   Data Dir                      Deploy Dir
--                 ----          ----         -----        -------        ------   --------                      ----------
tiup-peer:9093     alertmanager  tiup-peer    9093/9094    linux/aarch64  Up       /tiup/data/alertmanager-9093  /tiup/deploy/alertmanager-9093
tiup-peer:3000     grafana       tiup-peer    3000         linux/aarch64  Up       -                             /tiup/deploy/grafana-3000
pd-peer:2379       pd            pd-peer      2379/2380    linux/aarch64  Up|L|UI  /tiup/data/pd-2379            /tiup/deploy/pd-2379
tiup-peer:9090     prometheus    tiup-peer    9090/12020   linux/aarch64  Up       /tiup/data/prometheus-9090    /tiup/deploy/prometheus-9090
tidb-1-peer:4000   tidb          tidb-1-peer  4000/10080   linux/aarch64  Down     -                             /tiup/deploy/tidb-4000
tidb-2-peer:4000   tidb          tidb-2-peer  4000/10080   linux/aarch64  Down     -                             /tiup/deploy/tidb-4000
tidb-3-peer:4000   tidb          tidb-3-peer  4000/10080   linux/aarch64  Down     -                             /tiup/deploy/tidb-4000
tidb-4-peer:4000   tidb          tidb-4-peer  4000/10080   linux/aarch64  Down     -                             /tiup/deploy/tidb-4000
tikv-1-peer:20160  tikv          tikv-1-peer  20160/20180  linux/aarch64  Up       /tiup/data/tikv-20160         /tiup/deploy/tikv-20160
tikv-2-peer:20160  tikv          tikv-2-peer  20160/20180  linux/aarch64  Up       /tiup/data/tikv-20160         /tiup/deploy/tikv-20160
tikv-3-peer:20160  tikv          tikv-3-peer  20160/20180  linux/aarch64  Up       /tiup/data/tikv-20160         /tiup/deploy/tikv-20160
tikv-4-peer:20160  tikv          tikv-4-peer  20160/20180  linux/aarch64  Up       /tiup/data/tikv-20160         /tiup/deploy/tikv-20160
tikv-5-peer:20160  tikv          tikv-5-peer  20160/20180  linux/aarch64  Up       /tiup/data/tikv-20160         /tiup/deploy/tikv-20160
tikv-6-peer:20160  tikv          tikv-6-peer  20160/20180  linux/aarch64  Up       /tiup/data/tikv-20160         /tiup/deploy/tikv-20160
Total nodes: 14
```
![image](https://user-images.githubusercontent.com/2316425/159397481-4853f82c-1bbb-4e2c-a4c7-215a56c6b06b.png)

![image](https://user-images.githubusercontent.com/2316425/159397271-a4538c24-738d-4329-b717-0cf27e443df6.png)

```
[root@172 ~]# pstack 52485
Thread 1 (process 52485):
#0  runtime.futex () at /usr/local/go1.18/src/runtime/sys_linux_arm64.s:596
#1  0x00000000012f69cc in runtime.futexsleep (addr=<optimized out>, val=128, ns=0) at /usr/local/go1.18/src/runtime/os_linux.go:66
#2  0x00000000012cffcc in runtime.notetsleep_internal (n=0x5885520 <runtime.sig>, ns=-1, ~r0=<optimized out>) at /usr/local/go1.18/src/runtime/lock_futex.go:182
#3  0x00000000012d00c4 in runtime.notetsleepg (n=0x5885520 <runtime.sig>, ns=-1, ~r0=<optimized out>) at /usr/local/go1.18/src/runtime/lock_futex.go:236
#4  0x000000000132a974 in os/signal.signal_recv (~r0=<optimized out>) at /usr/local/go1.18/src/runtime/sigqueue.go:151
#5  0x0000000002abda00 in os/signal.loop () at /usr/local/go1.18/src/os/signal/signal_unix.go:23
#6  0x000000000132e654 in runtime.goexit () at /usr/local/go1.18/src/runtime/asm_arm64.s:1259
[root@172 ~]# pstack 52485
Thread 1 (process 52485):
#0  runtime.futex () at /usr/local/go1.18/src/runtime/sys_linux_arm64.s:596
#1  0x00000000012f69cc in runtime.futexsleep (addr=<optimized out>, val=128, ns=0) at /usr/local/go1.18/src/runtime/os_linux.go:66
#2  0x00000000012cffcc in runtime.notetsleep_internal (n=0x5885520 <runtime.sig>, ns=-1, ~r0=<optimized out>) at /usr/local/go1.18/src/runtime/lock_futex.go:182
#3  0x00000000012d00c4 in runtime.notetsleepg (n=0x5885520 <runtime.sig>, ns=-1, ~r0=<optimized out>) at /usr/local/go1.18/src/runtime/lock_futex.go:236
#4  0x000000000132a974 in os/signal.signal_recv (~r0=<optimized out>) at /usr/local/go1.18/src/runtime/sigqueue.go:151
#5  0x0000000002abda00 in os/signal.loop () at /usr/local/go1.18/src/os/signal/signal_unix.go:23
#6  0x000000000132e654 in runtime.goexit () at /usr/local/go1.18/src/runtime/asm_arm64.s:1259
```

**Comment by dbsid** [comment]
capture some perf top output
```
Samples: 6  of event 'cycles', 4000 Hz, Event count (approx.): 11385 lost: 0/0 drop: 0/0
Overhead  Shared Obje  Symbol
  97.67%  tidb-server  [.] runtime.gentraceback
   2.33%  tidb-server  [.] runtime.findfunc

Samples: 6  of event 'cycles', 4000 Hz, Event count (approx.): 32705 lost: 0/0 drop: 0/0
Overhead  Shared Obje  Symbol
  99.94%  tidb-server  [.] runtime.findfunc
   0.06%  tidb-server  [.] runtime.gentraceback

Samples: 6  of event 'cycles', 4000 Hz, Event count (approx.): 2 lost: 0/0 drop: 0/0
Overhead  Shared Obje  Symbol
 100.00%  tidb-server  [.] runtime.pcvalue
```

**Comment by tiancaiamao** [comment]
Confirmed it's a Go runtime bug.
I've filed a Go issue https://github.com/golang/go/issues/52116

**Comment by morgo** [comment]
@tiancaiamao can you confirm this is fixed? The golang issue is closed.
