### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#31734]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run comp test cases

### 3. What did you see instead (Required)
```
goroutine 489619203 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x4512650, 0xc0963e64e0, 0xc3bd1c5900)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1029 +0xf5
panic(0x3af7840, 0x5d1c4c0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1(0xc1e4a7add0, 0xc08471ca18, 0xc08471c9f8)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:362 +0x4d4
panic(0x3af7840, 0x5d1c4c0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tipb/go-tipb.(*Expr).Size(0x0, 0xc09575f630)
	/nfs/cache/mod/github.com/pingcap/tipb@v0.0.0-20220107024056-3b91949a18a7/go-tipb/expression.pb.go:2352 +0x26
github.com/pingcap/tipb/go-tipb.(*Aggregation).Size(0xc29d85ef30, 0x1dc)
	/nfs/cache/mod/github.com/pingcap/tipb@v0.0.0-20220107024056-3b91949a18a7/go-tipb/executor.pb.go:2177 +0x114
github.com/pingcap/tipb/go-tipb.(*Executor).Size(0xc017173500, 0x1e3)
	/nfs/cache/mod/github.com/pingcap/tipb@v0.0.0-20220107024056-3b91949a18a7/go-tipb/executor.pb.go:1887 +0x2f3
github.com/pingcap/tipb/go-tipb.(*DAGRequest).Size(0xc1e4a7aea0, 0x27e5da8)
	/nfs/cache/mod/github.com/pingcap/tipb@v0.0.0-20220107024056-3b91949a18a7/go-tipb/select.pb.go:1190 +0xb5
github.com/pingcap/tipb/go-tipb.(*DAGRequest).Marshal(0xc1e4a7aea0, 0x1, 0x1, 0x0, 0x0, 0x12369)
	/nfs/cache/mod/github.com/pingcap/tipb@v0.0.0-20220107024056-3b91949a18a7/go-tipb/select.pb.go:794 +0x2f
github.com/pingcap/tidb/distsql.(*RequestBuilder).SetDAGRequest(0xc1e8958000, 0xc1e4a7aea0, 0x12369)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/distsql/request_builder.go:154 +0xa6
github.com/pingcap/tidb/executor.(*TableReaderExecutor).buildKVReq(0xc35a10c820, 0x4512650, 0xc1a991b1d0, 0xc30935ed20, 0x1, 0x1, 0x20306a, 0x20306a, 0xc30935eda0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/table_reader.go:364 +0x170
github.com/pingcap/tidb/executor.(*TableReaderExecutor).buildResp(0xc35a10c820, 0x4512650, 0xc1a991b1d0, 0xc30935ed20, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/table_reader.go:299 +0x98
github.com/pingcap/tidb/executor.(*TableReaderExecutor).Open(0xc35a10c820, 0x4512650, 0xc1a991b1d0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/table_reader.go:199 +0x96e
github.com/pingcap/tidb/executor.(*baseExecutor).Open(0xc0519af100, 0x4512650, 0xc1a991b1d0, 0x30, 0xc1a991b1d0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:169 +0x7a
github.com/pingcap/tidb/executor.(*StreamAggExec).Open(0xc0519af100, 0x4512650, 0xc1a991b1d0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/aggregate.go:1241 +0x77
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc1e4a7add0, 0x4512650, 0xc1a991b1d0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:407 +0x3b9
github.com/pingcap/tidb/session.runStmt(0x4512650, 0xc1a991ad20, 0xc37e480200, 0x4529620, 0xc1e4a7add0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1827 +0x37f
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc37e480200, 0x4512650, 0xc1a991ad20, 0x4530b48, 0xc1bf9347e0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1704 +0xb0b
github.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt(0xc09a2612f0, 0x4512650, 0xc1a991ad20, 0x4530b48, 0xc1bf9347e0, 0xc094747d20, 0x4512650, 0xc1a991ad20, 0x0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:219 +0x6b
github.com/pingcap/tidb/server.(*clientConn).handleStmt(0xc3bd1c5900, 0x45125a8, 0xc1a991ad20, 0x4530b48, 0xc1bf9347e0, 0x6480c68, 0x0, 0x0, 0x1, 0x0, ...)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.4.0
Edition: Community
Git Commit Hash: cff64baaa002c47abda69000588e440bc19f9cc1
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-11 13:45:54
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by zanmato1984** [comment]
Can you give a more verbose reproduce step? @ChenPeng2013

**Comment by ChenPeng2013** [comment]
the issue don't happen again in comp test
