### ISSUE TITLE
Block test in the TestDomain

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#31966]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
 panic: test timed out after 20m0s
goroutine 572 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1788 +0xbb
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x4a
goroutine 1 [chan receive, 19 minutes]:
testing.(*T).Run(0xc00062d520, {0x51a0d89, 0xa}, 0x52abb40)
	/usr/local/go/src/testing/testing.go:1307 +0x752
testing.runTests.func1(0x0)
	/usr/local/go/src/testing/testing.go:1598 +0x9a
testing.tRunner(0xc00062d520, 0xc000d3fa90)
	/usr/local/go/src/testing/testing.go:1259 +0x230
testing.runTests(0xc00025c700, {0x7d13080, 0xe, 0xe}, {0xc000d3fb78, 0x131029d, 0x8410ce0})
	/usr/local/go/src/testing/testing.go:1596 +0x7cb
testing.(*M).Run(0xc00025c700)
	/usr/local/go/src/testing/testing.go:1504 +0x9d2
go.uber.org/goleak.VerifyTestMain({0x61fe980, 0xc00025c700}, {0xc00065be70, 0x2, 0x2})
	/home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x5a
github.com/pingcap/tidb/domain_test.TestMain(0x400)
	/go/tidb/domain/main_test.go:30 +0x225
main.main()
	_testmain.go:73 +0x265
goroutine 48 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00013a318)
	/home/prow/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9/pkg/logutil/merge_logger.go:173 +0xb0
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/prow/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9/pkg/logutil/merge_logger.go:91 +0x159
goroutine 163 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00044c228)
	/home/prow/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9/pkg/logutil/merge_logger.go:173 +0xb0
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/prow/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9/pkg/logutil/merge_logger.go:91 +0x159
goroutine 174 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00044c558)
	/home/prow/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9/pkg/logutil/merge_logger.go:173 +0xb0
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
	/home/prow/go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20210512015243-d19fbe541bf9/pkg/logutil/merge_logger.go:91 +0x159
goroutine 215 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00086e900)
	/home/prow/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0x185
created by go.opencensus.io/stats/view.init.0
	/home/prow/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0xf9
goroutine 515 [chan receive, 19 minutes]:
github.com/ngaut/pools.(*ResourcePool).SetCapacity(0xc00527dec0, 0x0)
	/home/prow/go/pkg/mod/github.com/ngaut/pools@v0.0.0-20180318154953-b7bc8c42aac7/resource_pool.go:172 +0x305
github.com/ngaut/pools.(*ResourcePool).Close(...)
	/home/prow/go/pkg/mod/github.com/ngaut/pools@v0.0.0-20180318154953-b7bc8c42aac7/resource_pool.go:73
github.com/pingcap/tidb/ddl.(*sessionPool).close(0xc0052a8810)
	/go/tidb/ddl/session_pool.go:91 +0x158
github.com/pingcap/tidb/ddl.(*ddl).close(0xc0007d4180)
	/go/tidb/ddl/ddl.go:434 +0x28f
github.com/pingcap/tidb/ddl.(*ddl).Stop(0xc0007d4180)
	/go/tidb/ddl/ddl.go:345 +0xb5
github.com/pingcap/tidb/domain.(*Domain).Close(0xc0008ed540)
	/go/tidb/domain/domain.go:695 +0xab
github.com/pingcap/tidb/domain.TestDomain(0x0)
	/go/tidb/domain/domain_test.go:367 +0x2f08
testing.tRunner(0xc000af5520, 0x52abb40)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727
goroutine 566 [select, 19 minutes]:
github.com/pingcap/tidb/domain.(*Domain).renewLease(0xc0008ed540)
	/go/tidb/domain/domain.go:1789 +0x193
created by github.com/pingcap/tidb/domain.(*Domain).Init
	/go/tidb/domain/domain.go:862 +0x149c
goroutine 565 [select]:
github.com/pingcap/tidb/domain.(*Domain).infoSyncerKeeper(0xc0008ed540)
	/go/tidb/domain/domain.go:516 +0x2af
created by github.com/pingcap/tidb/domain.(*Domain).Init
	/go/tidb/domain/domain.go:861 +0x141c
goroutine 564 [select, 11 minutes]:
github.com/pingcap/tidb/domain.(*Domain).topNSlowQueryLoop(0xc0008ed540)
	/go/tidb/domain/domain.go:484 +0x35c
created by github.com/pingcap/tidb/domain.(*Domain).Init
	/go/tidb/domain/domain.go:860 +0x139c
goroutine 563 [select]:
github.com/pingcap/tidb/domain.(*Domain).loadSchemaInLoop(0xc0008ed540, {0x624e9e8, 0xc004a42200}, 0x4c4b400)
	/go/tidb/domain/domain.go:594 +0x349
created by github.com/pingcap/tidb/domain.(*Domain).Init
	/go/tidb/domain/domain.go:857 +0x12fc
goroutine 567 [select, 19 minutes]:
github.com/pingcap/tidb/domain.(*Domain).globalConfigSyncerKeeper(0xc0008ed540)
	/go/tidb/domain/domain.go:539 +0x1b0
created by github.com/pingcap/tidb/domain.(*Domain).Init
	/go/tidb/domain/domain.go:863 +0x151c
goroutine 568 [select]:
github.com/pingcap/tidb/domain.(*Domain).topologySyncerKeeper(0xc0008ed540)
	/go/tidb/domain/domain.go:562 +0x30f
created by github.com/pingcap/tidb/domain.(*Domain).Init
	/go/tidb/domain/domain.go:866 +0x15bd 
```

**Comment by tiancaiamao** [comment]
From the stack information, it should be cause by some of the ddl component that get resource from the pool but forget to return to it, then the resource pool's close operation will block.

This seems to be fix already. It's an old issue and no reproduce found recently, so close it.
