### ISSUE TITLE
UT unstable test testSerialSuite.TestIndexJoin31494

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#32038]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Unstable test `testSerialSuite.TestIndexJoin31494`

```
(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/tracker.go:336\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/tracker.go:344\ngithub.com/pingcap/tidb/distsql.indexRangesToKVWithoutSplit\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/distsql/request_builder.go:702\ngithub.com/pingcap/tidb/distsql.indexRangesToKVRangesForTablesWithInterruptSignal\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/distsql/request_builder.go:592\ngithub.com/pingcap/tidb/distsql.IndexRangesToKVRangesWithInterruptSignal\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/distsql/request_builder.go:580\ngithub.com/pingcap/tidb/executor.buildKvRangesForIndexJoin\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/builder.go:4253\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildIndexLookUpReaderForIndexJoin\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/builder.go:4113\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoinInternal\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/builder.go:3789\ngithub.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoin\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/builder.go:3778\ngithub.com/pingcap/tidb/executor.(*innerWorker).fetchInnerResults\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:684\ngithub.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).fetchInnerResults\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:583\ngithub.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).handleTask\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:633\ngithub.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).run\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:478\ngithub.com/pingcap/tidb/executor.(*IndexNestedLoopHashJoin).startWorkers.func2\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:176\ngithub.com/pingcap/tidb/util.WithRecovery\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:100"]
[2022-01-27T11:49:50.957Z] [2022/01/27 19:49:38.345 +08:00] [ERROR] [index_lookup_join.go:479] ["innerWorker panicked"] [stack="goroutine 2656 [running]:\ngithub.com/pingcap/tidb/executor.(*innerWorker).run.func1(0xc004ded500, 0x4b4f1a8, 0xc00c28dac0, 0xc0005a7f28, 0xc00da12870)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:477 +0x131\npanic(0x3e8abc0, 0xc00386dfd0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action(0xc004c20f00, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/action.go:129 +0x198\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action.func1()\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1239 +0x1ea\nsync.(*Once).doSlow(0xc005a43988, 0xc0005a70c0)\n\t/usr/local/go/src/sync/once.go:68 +0xec\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc005a43950, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1233 +0xcf\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0059b5590, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0059b5400, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0059b5270, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0059b50e0, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0059b4f50, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0056d6eb0, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0056d6d70, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0056d6c30, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0056d6af0, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0056d69b0, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action.func1()\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1239 +0x1ea\nsync.(*Once).doSlow(0xc004ba9168, 0xc0005a7708)\n\t/usr/local/go/src/sync/once.go:68 +0xec\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc004ba9130, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1233 +0xcf\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1(0xc00594f098, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/tracker.go:336 +0x99\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume(0xc00776b600, 0xe000)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util"]
[2022-01-27T11:49:50.958Z] [2022/01/27 19:49:38.452 +08:00] [ERROR] [misc.go:95] ["panic in the recoverable goroutine"] [r="\"Out Of Memory Quota![conn_id=1]\""] ["stack trace"="github.com/pingcap/tidb/util.WithRecovery.func1\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:97\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:965\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/action.go:129\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action.func1\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1239\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1233\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action.func1\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1239\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1233\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action.func1\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1239\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1233\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/tracker.go:336\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/tracker.go:344\ngithub.com/pingcap/tidb/executor.(*innerWorker).constructLookupContent\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:593\ngithub.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).fetchInnerResults\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:579\ngithub.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).handleTask\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:633\ngithub.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).run\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:478\ngithub.com/pingcap/tidb/executor.(*IndexNestedLoopHashJoin).startWorkers.func2\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:176\ngithub.com/pingcap/tidb/util.WithRecovery\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:100"]
[2022-01-27T11:49:50.959Z] [2022/01/27 19:49:38.539 +08:00] [ERROR] [index_lookup_join.go:479] ["innerWorker panicked"] [stack="goroutine 2848 [running]:\ngithub.com/pingcap/tidb/executor.(*innerWorker).run.func1(0xc000eccc40, 0x4b4f1a8, 0xc0075290c0, 0xc0005a7f28, 0xc009bc8770)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:477 +0x131\npanic(0x3e8abc0, 0xc005612690)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action(0xc00ac1a4b0, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/action.go:129 +0x198\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action.func1()\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1239 +0x1ea\nsync.(*Once).doSlow(0xc006cc6c18, 0xc0005a70c0)\n\t/usr/local/go/src/sync/once.go:68 +0xec\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc006cc6be0, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1233 +0xcf\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc006bf6820, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc006bf6690, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc006bf6500, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc006bf6370, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc006bf61e0, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0065bc140, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0065bc000, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0065b9ea0, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0065b9d60, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc0065b9c20, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227 +0x112\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action.func1()\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1239 +0x1ea\nsync.(*Once).doSlow(0xc00739c3a8, 0xc0005a7708)\n\t/usr/local/go/src/sync/once.go:68 +0xec\nsync.(*Once).Do(...)\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action(0xc00739c370, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1233 +0xcf\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1(0xc00594f098, 0xc00594f088)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/tracker.go:336 +0x99\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume(0xc00e014c80, 0xe000)\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util"]
[2022-01-27T11:49:50.959Z] [2022/01/27 19:49:38.641 +08:00] [ERROR] [misc.go:95] ["panic in the recoverable goroutine"] [r="\"Out Of Memory Quota![conn_id=1]\""] ["stack trace"="github.com/pingcap/tidb/util.WithRecovery.func1\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:97\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:965\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/action.go:129\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action.func1\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1239\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1233\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action.func1\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1239\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:68\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:59\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1233\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/store/copr.(*rateLimitAction).Action\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1227\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/tracker.go:336\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/memory/tracker.go:344\ngithub.com/pingcap/tidb/executor.(*innerWorker).constructLookupContent\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:558\ngithub.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).fetchInnerResults\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:579\ngithub.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).handleTask\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:633\ngithub.com/pingcap/tidb/executor.(*indexHashJoinInnerWorker).run\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:478\ngithub.com/pingcap/tidb/executor.(*IndexNestedLoopHashJoin).startWorkers.func2\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/executor/index_lookup_hash_join.go:176\ngithub.com/pingcap/tidb/util.WithRecovery\n\t/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/util/misc.go:100"]
[2022-01-27T11:49:50.960Z] 
[2022-01-27T11:49:50.960Z] ----------------------------------------------------------------------
[2022-01-27T11:49:50.960Z] FAIL: executor_test.go:9799: testSerialSuite.TestIndexJoin31494
[2022-01-27T11:49:50.960Z] 
[2022-01-27T11:49:50.960Z] executor_test.go:9834:
[2022-01-27T11:49:50.960Z]     c.Assert(err.Error(), Matches, "Out Of Memory Quota!.*")
[2022-01-27T11:49:50.960Z] ... value string = "indexHashJoinInnerWorker.doJoinUnordered failed"
[2022-01-27T11:49:50.960Z] ... regex string = "Out Of Memory Quota!.*"
```

### 2. What did you expect to see? (Required)

CI stable

### 3. What did you see instead (Required)

Unstable test function

### 4. What is your TiDB version? (Required)

07b0c7c657f4baf11f755e0ac7baf55bbc4c3bbd

**Comment by tiancaiamao** [comment]
Just affect the test code
