### ISSUE TITLE
Leak memory in the parseSlowLog

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#32646]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
goroutine 221431 [chan send, 9 minutes]:
github.com/pingcap/tidb/executor.(*slowQueryRetriever).parseSlowLog(0xc09392b480, 0x4038470, 0xc09b4dc360, 0x407eb58, 0xc092c7ae00, 0xc13d6ddf50, 0x40)
/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/slow_query.go:451 +0x23e
github.com/pingcap/tidb/executor.(*slowQueryRetriever).parseDataForSlowLog(0xc09392b480, 0x4038470, 0xc09b4dc360, 0x407eb58, 0xc092c7ae00)
/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/slow_query.go:191 +0x1d1
created by github.com/pingcap/tidb/executor.(*slowQueryRetriever).initializeAsyncParsing
/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/executor/slow_query.go:1045 +0x98
```

**Comment by ChenPeng2013** [comment]
duplicated with https://github.com/pingcap/tidb/issues/32656
