### ISSUE TITLE
concurrent map writes

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#33027]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)
set global tidb_partition_prune_mode=dynamic;
```
fatal error: concurrent map writes

goroutine 11463326 [running]:
runtime.throw({0x3981159, 0xc00049d680})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc1432329f8 sp=0xc1432329c8 pc=0x1260bd1
runtime.mapassign_faststr(0x36292c0, 0xc1000000d2, {0x3960d51, 0xb})
	/usr/local/go/src/runtime/map_faststr.go:211 +0x39c fp=0xc143232a60 sp=0xc1432329f8 pc=0x123e19c
github.com/pingcap/tidb/telemetry.BuiltinFunctionsUsage.Inc(...)
	/root/tidb/telemetry/data_window.go:130
github.com/pingcap/tidb/planner/core.(*expressionRewriter).newFunction(0xc16d005450, {0x3950d8e, 0x3505e40}, 0xc002280001, {0xc0fa20de40, 0x2, 0x8})
	/root/tidb/planner/core/expression_rewriter.go:1228 +0x1bd fp=0xc143232b00 sp=0xc143232a60 pc=0x278d33d
github.com/pingcap/tidb/planner/core.(*expressionRewriter).binaryOpToExpression(0xc16d005450, 0xc16d0052b0)
	/root/tidb/planner/core/expression_rewriter.go:1363 +0x2a9 fp=0xc143232b98 sp=0xc143232b00 pc=0x278f4a9
github.com/pingcap/tidb/planner/core.(*expressionRewriter).Leave(0xc16d005450, {0x3ecde50, 0xc16d0052b0})
	/root/tidb/planner/core/expression_rewriter.go:1103 +0x83b fp=0xc143232de0 sp=0xc143232b98 pc=0x278b87b
github.com/pingcap/tidb/parser/ast.(*BinaryOperationExpr).Accept(0xc16d005450, {0x3e721f0, 0xc16d005450})
	/root/tidb/parser/ast/expressions.go:223 +0x151 fp=0xc143232e18 sp=0xc143232de0 pc=0x1cfd5d1
github.com/pingcap/tidb/parser/ast.(*ParenthesesExpr).Accept(0xc16d005380, {0x3e721f0, 0xc16d005450})
	/root/tidb/parser/ast/expressions.go:995 +0x82 fp=0xc143232e50 sp=0xc143232e18 pc=0x1d00e22
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode(0xc044c03d40, 0xc16d005450, {0x3eef9b0, 0xc138017600}, 0x1)
	/root/tidb/planner/core/expression_rewriter.go:200 +0x11a fp=0xc143232f08 sp=0xc143232e50 pc=0x278061a
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteWithPreprocess(0xc044c03d40, {0x3ea7520, 0xc000054088}, {0x3eef9b0, 0xc138017600}, {0x3f1ce10, 0xc16d005380}, 0x0, 0x0, 0x1, ...)
	/root/tidb/planner/core/expression_rewriter.go:146 +0x173 fp=0xc143232f90 sp=0xc143232f08 pc=0x277fe53
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewrite(0x0, {0x3ea7520, 0xc000054088}, {0x3eef9b0, 0xc138017600}, {0x3f1ce10, 0xc16d005380}, 0x0, 0x0)
	/root/tidb/planner/core/expression_rewriter.go:114 +0x53 fp=0xc143232ff8 sp=0xc143232f90 pc=0x277fc53
github.com/pingcap/tidb/planner/core.rewriteAstExpr({0x3f4e560, 0xc188386200}, {0x3eef9b0, 0xc138017600}, 0xc07c2b7f90, {0xc144f7d7a0, 0x5, 0x5})
	/root/tidb/planner/core/expression_rewriter.go:80 +0x33b fp=0xc143233150 sp=0xc143232ff8 pc=0x277f87b
github.com/pingcap/tidb/expression.RewriteSimpleExprWithNames(...)
	/root/tidb/expression/simple_rewriter.go:114
github.com/pingcap/tidb/expression.ParseSimpleExprsWithNames({0x3f4e560, 0xc188386200}, {0xc00c3a60e0, 0x203003}, 0x7f4f7d94b260, {0xc144f7d7a0, 0x5, 0x5})
	/root/tidb/expression/simple_rewriter.go:103 +0x228 fp=0xc143233228 sp=0xc143233150 pc=0x216c628
github.com/pingcap/tidb/planner/core.generateHashPartitionExpr({0x3f4e560, 0xc188386200}, 0xc0009161e0, {0xc144f7d470, 0x5, 0x5}, {0xc144f7d7a0, 0x5, 0x5})
	/root/tidb/planner/core/rule_partition_processor.go:117 +0xd4 fp=0xc143233288 sp=0xc143233228 pc=0x28aa334
github.com/pingcap/tidb/planner/core.(*partitionProcessor).findUsedPartitions(0x7f501a20ef18, {0x3f4e560, 0xc188386200}, {0x3efe6d8, 0xc014ee5b80}, {0x5fd42e8, 0x0, 0x0}, {0x5fd42e8, 0x0, ...}, ...)
	/root/tidb/planner/core/rule_partition_processor.go:128 +0xc6 fp=0xc143233420 sp=0xc143233288 pc=0x28aa4e6
github.com/pingcap/tidb/planner/core.(*partitionProcessor).pruneHashPartition(0xc01fc8d6c8, {0x3f4e560, 0xc188386200}, {0x3efe6d8, 0xc014ee5b80}, {0x5fd42e8, 0x20, 0x400}, {0x5fd42e8, 0x0, ...}, ...)
	/root/tidb/planner/core/rule_partition_processor.go:278 +0xc7 fp=0xc1432334b8 sp=0xc143233420 pc=0x28ab767
github.com/pingcap/tidb/planner/core.PartitionPruning({0x3f4e560, 0xc188386200}, {0x3f07428, 0xc014ee5b80}, {0x5fd42e8, 0x0, 0x0}, {0x5fd42e8, 0x0, 0x0}, ...)
	/root/tidb/planner/core/partition_prune.go:40 +0x253 fp=0xc143233578 sp=0xc1432334b8 pc=0x2811573
github.com/pingcap/tidb/executor.partitionPruning({0x3f4e560, 0xc188386200}, {0x3f07428, 0xc014ee5b80}, {0x5fd42e8, 0x1242917, 0x0}, {0x5fd42e8, 0x0, 0x0}, ...)
	/root/tidb/executor/builder.go:4672 +0xca fp=0xc1432336d8 sp=0xc143233578 pc=0x2f228ca
github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildTableReaderForIndexJoin(0xc02df787e0, {0x3ea74e8, 0xc10e7e30c0}, 0xc145c25400, {0xc055a0e080, 0x7, 0x7}, {0x5fd42e8, 0x0, 0x0}, ...)
	/root/tidb/executor/builder.go:3900 +0x4a5 fp=0xc143233b28 sp=0xc1432336d8 pc=0x2f19905
github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoinInternal(0xc000cf7540, {0x3ea74e8, 0xc10e7e30c0}, {0x3ef2020, 0xc145c25400}, {0xc055a0e080, 0x10000000357a900, 0x40}, {0x5fd42e8, 0x0, ...}, ...)
	/root/tidb/executor/builder.go:3818 +0x265 fp=0xc143233c78 sp=0xc143233b28 pc=0x2f18b85
github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildExecutorForIndexJoin(...)
	/root/tidb/executor/builder.go:3811
github.com/pingcap/tidb/executor.(*innerWorker).fetchInnerResults(0xc11744e8c0, {0x3ea74e8, 0xc10e7e30c0}, 0xc1af0c2700, {0xc055a0e080, 0x7, 0x7})
	/root/tidb/executor/index_lookup_join.go:684 +0x22f fp=0xc143233e10 sp=0xc143233c78 pc=0x2f6154f
github.com/pingcap/tidb/executor.(*innerWorker).handleTask(0xc11744e8c0, {0x3ea74e8, 0xc10e7e30c0}, 0x0)
	/root/tidb/executor/index_lookup_join.go:523 +0x1ae fp=0xc143233ec8 sp=0xc143233e10 pc=0x2f5f62e
github.com/pingcap/tidb/executor.(*innerWorker).run(0xc11744e8c0, {0x3ea74e8, 0xc10e7e30c0}, 0xc0f9e28ae0)
	/root/tidb/executor/index_lookup_join.go:497 +0x157 fp=0xc143233fb0 sp=0xc143233ec8 pc=0x2f5efb7
github.com/pingcap/tidb/executor.(*IndexLookUpJoin).startWorkers·dwrap·52()
	/root/tidb/executor/index_lookup_join.go:195 +0x32 fp=0xc143233fe0 sp=0xc143233fb0 pc=0x2f5cad2
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc143233fe8 sp=0xc143233fe0 pc=0x12951a1
created by github.com/pingcap/tidb/executor.(*IndexLookUpJoin).startWorkers
	/root/tidb/executor/index_lookup_join.go:195 +0x1d3
```
[tidb_stderr.log](https://github.com/pingcap/tidb/files/8241330/tidb_stderr.log)

### 4. What is your TiDB version? (Required)

master

**Comment by qw4990** [comment]
Seems like it's caused by this method `Inc()` is not thread-safe, and this method may be invoked concurrently by `IndexJoin`. I'll try to see if we can fix it by simply making `Inc()` thread-safe:
![middle_img_v2_89f8ad0a-c681-421e-9b4d-65a75c0c08ag](https://user-images.githubusercontent.com/7499936/158114928-0b192649-e0be-407a-9086-4f141916bd57.png)
