### ISSUE TITLE
Encountered CI failure due to `signal: segmentation fault (core dumped)`

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#33238]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/41593/pipeline/
```
[2022-03-18T02:54:55.869Z] [FAIL]  planner/core TestInvalidHint
[2022-03-18T02:54:55.869Z] err=signal: segmentation fault (core dumped)
[2022-03-18T02:54:55.869Z] [2022/03/18 09:00:48.014 +08:00] [WARN] [session.go:1897] ["run statement failed"] [schemaVersion=0] [error="[schema:1049]Unknown database 'mysql'"] [errorVerbose="[schema:1049]Unknown database ..."]
[2022-03-18T02:55:01.326Z] [FAIL]  planner/core TestNaturalJoinUpdateSameTable
[2022-03-18T02:55:01.327Z] err=exit status 2
[2022-03-18T02:55:01.327Z] [2022/03/18 09:01:00.236 +08:00] [WARN] [session.go:1897] ["run statement failed"] [schemaVersion=0] [error="[schema:1049]Unknown database 'mysql'"] [errorVerbose="[schema:1049]Unknown database ..."]
[2022-03-18T02:55:01.327Z] runtime: gp: gp=0xc00018351f, goid=11008, gp->atomicstatus=1024
[2022-03-18T02:55:01.327Z] runtime:  g:  g=0xc000cd69c0, goid=0,  g->atomicstatus=0
[2022-03-18T02:55:01.327Z] fatal error: invalid g status
[2022-03-18T02:55:01.327Z] 
[2022-03-18T02:55:01.327Z] runtime stack:
[2022-03-18T02:55:01.327Z] runtime.throw({0x38bbb90?, 0x0?})
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/panic.go:992 +0x71
[2022-03-18T02:55:01.327Z] runtime.suspendG(0xc00018351f)
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/preempt.go:135 +0x54b
[2022-03-18T02:55:01.327Z] runtime.markroot.func1()
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/mgcmark.go:233 +0x8d
[2022-03-18T02:55:01.327Z] runtime.markroot(0xc00006f238, 0x47, 0x1)
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/mgcmark.go:214 +0x1a5
[2022-03-18T02:55:01.327Z] runtime.gcDrain(0xc00006f238, 0xb)
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/mgcmark.go:1047 +0x39f
[2022-03-18T02:55:01.327Z] runtime.gcBgMarkWorker.func2()
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/mgc.go:1293 +0x85
[2022-03-18T02:55:01.327Z] runtime.systemstack()
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/asm_amd64.s:469 +0x49
[2022-03-18T02:55:01.327Z] 
[2022-03-18T02:55:01.327Z] goroutine 48 [GC worker (idle)]:
[2022-03-18T02:55:01.327Z] runtime.systemstack_switch()
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc000545758 sp=0xc000545750 pc=0x129e7c0
[2022-03-18T02:55:01.327Z] runtime.gcBgMarkWorker()
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/mgc.go:1263 +0x1b1 fp=0xc0005457e0 sp=0xc000545758 pc=0x1251e91
[2022-03-18T02:55:01.327Z] runtime.goexit()
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0005457e8 sp=0xc0005457e0 pc=0x12a09e1
[2022-03-18T02:55:01.327Z] created by runtime.gcBgMarkStartWorkers
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/mgc.go:1131 +0x25
[2022-03-18T02:55:01.327Z] 
[2022-03-18T02:55:01.327Z] goroutine 1 [chan receive]:
[2022-03-18T02:55:01.327Z] testing.(*T).Run(0xc000512340, {0x38f1e71?, 0x135ae85?}, 0x39faf50)
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/testing/testing.go:1487 +0x37a
[2022-03-18T02:55:01.327Z] testing.runTests.func1(0xc000512340?)
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/testing/testing.go:1839 +0x6e
[2022-03-18T02:55:01.327Z] testing.tRunner(0xc000512340, 0xc000e77b88)
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/testing/testing.go:1439 +0x102
[2022-03-18T02:55:01.327Z] testing.runTests(0xc000bac000?, {0x56cc5a0, 0x217, 0x217}, {0xc0005f2e00?, 0x1f?, 0x5db73e0?})
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/testing/testing.go:1837 +0x457
[2022-03-18T02:55:01.327Z] testing.(*M).Run(0xc000bac000)
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/testing/testing.go:1719 +0x5d9
[2022-03-18T02:55:01.327Z] github.com/pingcap/tidb/testkit/testmain.(*testingM).Run(0xc00000eb58)
[2022-03-18T02:55:01.327Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/testkit/testmain/wrapper.go:28 +0x29
[2022-03-18T02:55:01.327Z] go.uber.org/goleak.VerifyTestMain({0x3e44300?, 0xc00000eb58?}, {0xc00542de68, 0x2, 0x2})
[2022-03-18T02:55:01.327Z] 	/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x3d
[2022-03-18T02:55:01.327Z] github.com/pingcap/tidb/planner/core.TestMain(0xc000bac000)
[2022-03-18T02:55:01.327Z] 	/home/jenkins/agent/workspace/tidb_ghpr_unit_test/go/src/github.com/pingcap/tidb/planner/core/main_test.go:63 +0x49c
[2022-03-18T02:55:01.327Z] main.main()
[2022-03-18T02:55:01.327Z] 	_testmain.go:1283 +0x28f
[2022-03-18T02:55:01.327Z] 
[2022-03-18T02:55:01.327Z] goroutine 11008 [???]:
[2022-03-18T02:55:01.327Z] runtime: unknown pc 0x126f4f600
[2022-03-18T02:55:01.327Z] stack: frame={sp:0xc000542f3800, fp:0x0} stack=[0xc00054280000,0xc00054300000)
[2022-03-18T02:55:01.327Z] 0x0000c000542f3700:  fatal error: unexpected signal during runtime execution
[2022-03-18T02:55:01.327Z] panic during panic
[2022-03-18T02:55:01.327Z] [signal SIGSEGV: segmentation violation code=0x0000000000000080 addr=0x0000000000000000 pc=0x000000000126edaa]
[2022-03-18T02:55:01.327Z] 
[2022-03-18T02:55:01.327Z] runtime stack:
[2022-03-18T02:55:01.327Z] runtime.throw({0x0000000003925598?, 0x00007f848a031478?})
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/panic.go:992 +0x0000000000000071
[2022-03-18T02:55:01.327Z] runtime.sigpanic()
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/signal_unix.go:802 +0x00000000000003a9
[2022-03-18T02:55:01.327Z] runtime.hexdumpWords(0x0000c000542f3700, 0x0000c000542f3900, 0x00007f848a031538)
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/print.go:289 +0x000000000000010a
[2022-03-18T02:55:01.327Z] runtime.tracebackHexdump({0x00000000038cb2f5?, 0x000000000572fda0?}, 0x00007f848a031858, 0x0000000000000000)
[2022-03-18T02:55:01.327Z] 	/usr/local/go/src/runtime/traceback.go:1090 +0x0000000000000199
[2022-03-18T02:55:01.327Z] runtime.gentraceback(0x0000000004ca9920?, 0x000000000572fda0?, 0x00007f848a031920?, 0x0000000001293c7e?, 0x0000000000000000, 0x0000000000000000, 0x0000000000000064, 0x0000000000000000, 0x00007f848a031940?, 0x0000000000000000)
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/traceback.go:117 +0x000000000000029a
[2022-03-18T02:55:01.328Z] runtime.traceback1(0x000000c00018351f?, 0x000000000126e200?, 0x0000000000000003?, 0x000000c00018351f, 0x0000000001294e0a?)
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/traceback.go:835 +0x00000000000001b1
[2022-03-18T02:55:01.328Z] runtime.traceback(...)
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/traceback.go:782
[2022-03-18T02:55:01.328Z] runtime.tracebackothers.func1(0x000000c00018351f)
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/traceback.go:1051 +0x00000000000000e5
[2022-03-18T02:55:01.328Z] runtime.forEachGRace(0x00007f848a031b30)
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/proc.go:590 +0x000000000000004d
[2022-03-18T02:55:01.328Z] runtime.tracebackothers(0x000000c000cd69c0?)
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/traceback.go:1037 +0x00000000000000db
[2022-03-18T02:55:01.328Z] runtime.dopanic_m(0x000000c000cd69c0, 0x0000000000000001?, 0x0000000000000001?)
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/panic.go:1192 +0x000000000000027c
[2022-03-18T02:55:01.328Z] runtime.fatalthrow.func1()
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/panic.go:1047 +0x0000000000000048
[2022-03-18T02:55:01.328Z] runtime.fatalthrow()
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/panic.go:1044 +0x0000000000000050
[2022-03-18T02:55:01.328Z] runtime.throw({0x00000000038bbb90?, 0x0000000000000000?})
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/panic.go:992 +0x0000000000000071
[2022-03-18T02:55:01.328Z] runtime.suspendG(0x000000c00018351f)
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/preempt.go:135 +0x000000000000054b
[2022-03-18T02:55:01.328Z] runtime.markroot.func1()
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/mgcmark.go:233 +0x000000000000008d
[2022-03-18T02:55:01.328Z] runtime.markroot(0x000000c00006f238, 0x0000000000000047, 0x0000000000000001)
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/mgcmark.go:214 +0x00000000000001a5
[2022-03-18T02:55:01.328Z] runtime.gcDrain(0x000000c00006f238, 0x000000000000000b)
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/mgcmark.go:1047 +0x000000000000039f
[2022-03-18T02:55:01.328Z] runtime.gcBgMarkWorker.func2()
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/mgc.go:1293 +0x0000000000000085
[2022-03-18T02:55:01.328Z] runtime.systemstack()
[2022-03-18T02:55:01.328Z] 	/usr/local/go/src/runtime/asm_amd64.s:469 +0x0000000000000049
[2022-03-18T02:57:53.441Z] run all tasks takes 4m33.601281166s
[2022-03-18T02:57:53.441Z] make: *** [gotest_in_verify_ci] Error 1
[2022-03-18T02:57:53.453Z] Recording test results
```

### 4. What is your TiDB version? (Required)

CI in PR on the master branch.

**Comment by zimulala** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/32690.
