### ISSUE TITLE
operator env, upgrade from v4.0.16 to v6.0.0 fail 

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#33344]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

operator env
1. install tidb cluster with default config
2. upgrade to v6.0.0

### 2. What did you expect to see? (Required)
upgrade success

### 3. What did you see instead (Required)
upgrade fail
tingli@tings-MBP operator_upgrade % kubectl logs -f -n testbed-operator-upgrade-5wvh6 tc-tidb-3
start tidb-server ...
/tidb-server --store=tikv --advertise-address=tc-tidb-3.tc-tidb-peer.testbed-operator-upgrade-5wvh6.svc --host=0.0.0.0 --path=tc-pd:2379 --config=/etc/tidb/tidb.toml

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/pingcap/tidb/session.mustExecute({0x3df2e60?, 0xc0011cc6c0?}, {0x38f7eb1?, 0xc0011cc6c0?}, {0x0?, 0x1?, 0x0?})
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/bootstrap.go:1964 +0x8a
github.com/pingcap/tidb/session.upgradeToVer63({0x3df2e60, 0xc0011cc6c0}, 0x0?)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/bootstrap.go:1568 +0x9c
github.com/pingcap/tidb/session.upgrade({0x3df2e60?, 0xc0011cc6c0?})
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/bootstrap.go:749 +0xbd
github.com/pingcap/tidb/session.runInBootstrapSession({0x3db6180, 0xc0010e99a0}, 0x3960480)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2944 +0x1ff
github.com/pingcap/tidb/session.BootstrapSession({0x3db6180, 0xc0010e99a0})
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2788 +0x1f8
main.createStoreAndDomain()
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:298 +0x114
main.main()
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:204 +0x4ca
tingli@tings-MBP operator_upgrade

[2022/03/23 06:23:12.530 +00:00] [INFO] [syncer.go:398] ["[ddl] syncer check all versions, someone is not synced, continue checking"] [ddl=/tidb/ddl/all_schema_versions/290
[2022/03/23 06:23:13.601 +00:00] [INFO] [syncer.go:398] ["[ddl] syncer check all versions, someone is not synced, continue checking"] [ddl=/tidb/ddl/all_schema_versions/290
[2022/03/23 06:23:14.672 +00:00] [INFO] [syncer.go:398] ["[ddl] syncer check all versions, someone is not synced, continue checking"] [ddl=/tidb/ddl/all_schema_versions/290
[2022/03/23 06:23:15.743 +00:00] [INFO] [syncer.go:398] ["[ddl] syncer check all versions, someone is not synced, continue checking"] [ddl=/tidb/ddl/all_schema_versions/290
[2022/03/23 06:23:16.823 +00:00] [INFO] [syncer.go:398] ["[ddl] syncer check all versions, someone is not synced, continue checking"] [ddl=/tidb/ddl/all_schema_versions/290
[2022/03/23 06:23:17.895 +00:00] [INFO] [syncer.go:398] ["[ddl] syncer check all versions, someone is not synced, continue checking"] [ddl=/tidb/ddl/all_schema_versions/290
[2022/03/23 06:23:18.972 +00:00] [INFO] [syncer.go:398] ["[ddl] syncer check all versions, someone is not synced, continue checking"] [ddl=/tidb/ddl/all_schema_versions/290
[2022/03/23 06:

### 4. What is your TiDB version? (Required)

v6.0.0

**Comment by seiya-annie** [comment]
![upgrade_fail](https://user-images.githubusercontent.com/53471087/159647461-4dabf545-24d4-4ba6-9161-6a7f0da2cb86.png)

**Comment by you06** [comment]
@seiya-annie  Seems the error is reported from TiKV v4.0.16, can you check it again?

**Comment by seiya-annie** [comment]
not a bug， upgrade order incorrect
