### ISSUE TITLE
connection running loop panic when run sysbench read_write in range partition  

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#33386]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run sysbench read_write in range partition 
[2022/03/23 23:31:12.727 +08:00] [INFO] [cmd.go:124] ["Start remote command"] [cmd="sysbench --mysql-user=root --db-driver=mysql --time=0 --report-interval=10 --mysql-db=partitioninsert_1647963896275 --mysql-host=tc-tidb.endless-oltp-tps-721881-1-634 --mysql-port=4000 --threads=512 --tables=32 --table-size=7000000 --mysql-ignore-errors=2013,1213,1105,8028,9007 --rand-type=pareto oltp_read_write run"] [nodename=benchtoolset]
2、run ddl
for i := 0; i < tableNum; i++ {
			var columeName string
			tableName := tables[i]
			cmd := fmt.Sprintf("select column_name from information_schema.columns where table_schema='%s' and table_name='%s' and column_name='%s';", dbName, tableName, addColumnName)
			ret := db.QueryRow(cmd).Scan(&columeName)
			dropCmd := fmt.Sprintf("alter table %s drop column %s;", tableName, addColumnName)
			addCmd := fmt.Sprintf("alter table %s add column %s int;", tableName, addColumnName)
			if ret == nil {
				err := DbExecContextWithLog(ctx, db, dropCmd)
				if !errors.Is(err, context.DeadlineExceeded) {
					Expect(err).Should(Succeed())
				}
			}
			err := DbExecContextWithLog(ctx, db, addCmd)
			if !errors.Is(err, context.DeadlineExceeded) {
				Expect(err).Should(Succeed())
			}
			err = DbExecContextWithLog(ctx, db, dropCmd)
			if !errors.Is(err, context.DeadlineExceeded) {
				Expect(err).Should(Succeed())
			}
		}

### 2. What did you expect to see? (Required)
no panic error

### 3. What did you see instead (Required)
connection running loop panic

plan：https://tcms.pingcap.net/dashboard/executions/plan/721881
log：http://minio.pingcap.net:42041/buckets/test-infra-testground/browse/YXJjaGl2ZS9lbmRsZXNzLW9sdHAtdHBzLTcyMTg4MS0xLTYzNC8=

[2022/03/23 16:17:26.380 +00:00] [ERROR] [conn.go:1031] ["connection running loop panic"] [conn=2431] [lastSQL="UPDATE sbtest23 SET c=? WHERE id=? [arguments: (\"02551790185-64070546139-64736633522-23974488375-15631789594-75072214832-74524519218-39415174710-16086001576-18797355528\", 7)]"] [err="runtime error: index out of range [4] with length 4"] [stack="goroutine 71445902 [running]:\[ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1()\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1029](http://ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1()/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1029) +0x8f\npanic({0x36483e0, 0xc0427c10c8})\n\t/usr/local/go/src/runtime/panic.go:838 +0x207\[ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:362](http://ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:362) +0x3b3\npanic({0x36483e0, 0xc0427c10c8})\n\t/usr/local/go/src/runtime/panic.go:838 +0x207\[ngithub.com/pingcap/tidb/planner/core.CheckUpdateList](http://ngithub.com/pingcap/tidb/planner/core.CheckUpdateList)({0xc026655d40, 0xc0014c9680?, 0x4}, 0xc00b3a75f0, 0x20?)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4963](http://github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4963) +0x6d1\[ngithub.com/pingcap/tidb/executor.(*executorBuilder).buildUpdate](http://ngithub.com/pingcap/tidb/executor.(*executorBuilder).buildUpdate)(0xc0219ca080, 0xc00b3a75f0)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/executor/builder.go:2074](http://github.com/pingcap/tidb/executor/builder.go:2074) +0x345\[ngithub.com/pingcap/tidb/executor.(*executorBuilder).build](http://ngithub.com/pingcap/tidb/executor.(*executorBuilder).build)(0xc0219ca080, {0x3db7a80?, 0xc00b3a75f0?})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/executor/builder.go:237](http://github.com/pingcap/tidb/executor/builder.go:237) +0xd45\[ngithub.com/pingcap/tidb/executor.(*ExecuteExec).Build](http://ngithub.com/pingcap/tidb/executor.(*ExecuteExec).Build)(0xc0437ef860, 0xc0219ca080)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/executor/prepared.go:302](http://github.com/pingcap/tidb/executor/prepared.go:302) +0xec\[ngithub.com/pingcap/tidb/executor.(*ExecStmt).buildExecutor(0xc00b3a7e10)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:863](http://ngithub.com/pingcap/tidb/executor.(*ExecStmt).buildExecutor(0xc00b3a7e10)/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:863) +0x59e\[ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec](http://ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec)(0xc00b3a7e10, {0x3d9d560, 0xc01d8dc120})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/executor/adapter.go:399](http://github.com/pingcap/tidb/executor/adapter.go:399) +0x44b\[ngithub.com/pingcap/tidb/session.runStmt](http://ngithub.com/pingcap/tidb/session.runStmt)({0x3d9d560, 0xc006e9fbc0}, 0xc0014c9680, {0x3da54a0, 0xc00b3a7e10?})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/session.go:2017](http://github.com/pingcap/tidb/session/session.go:2017) +0x53d\[ngithub.com/pingcap/tidb/session.(*session).preparedStmtExec](http://ngithub.com/pingcap/tidb/session.(*session).preparedStmtExec)(0xc0014c9680, {0x3d9d560, 0xc006e9fbc0}, {0x3dbc470?, 0xc02a553490?}, 0x3d9d560?, 0x164ecae0?, 0xc0022652c0?, {0xc01328dc20, 0x2, ...})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/session.go:2162](http://github.com/pingcap/tidb/session/session.go:2162) +0x21e\[ngithub.com/pingcap/tidb/session.(*session).ExecutePreparedStmt](http://ngithub.com/pingcap/tidb/session.(*session).ExecutePreparedStmt)(0xc0014c9680, {0x3d9d560, 0xc006e9fbc0}, 0xd9, {0xc01328dc20, 0x2, 0x2})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/session.go:2338](http://github.com/pingcap/tidb/session/session.go:2338) +0x54d\[ngithub.com/pingcap/tidb/server.(*TiDBStatement).Execute](http://ngithub.com/pingcap/tidb/server.(*TiDBStatement).Execute)(0xc026a701c0, {0x3d9d560?, 0xc006e9fbc0?}, {0xc01328dc20?, 0x7fe9c69a4a68?, 0x30?})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/driver_tidb.go:75](http://github.com/pingcap/tidb/server/driver_tidb.go:75) +0x5c\[ngithub.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult](http://ngithub.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult)(0xc0022652c0, {0x3d9d560, 0xc006e9fbc0}, {0x3db3938, 0xc026a701c0}, {0xc01328dc20?, 0xc045b665ac?, 0x80?}, 0x0)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/conn_stmt.go:237](http://github.com/pingcap/tidb/server/conn_stmt.go:237) +0x89\[ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtExecute](http://ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtExecute)(0xc0022652c0, {0x3d9d4b8, 0xc02d309380}, {0xc045b665a1, 0x8b, 0x8b})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/conn_stmt.go:209](http://github.com/pingcap/tidb/server/conn_stmt.go:209) +0x70e\[ngithub.com/pingcap/tidb/server.(*clientConn).dispatch](http://ngithub.com/pingcap/tidb/server.(*clientConn).dispatch)(0xc0022652c0, {0x3d9d560?, 0xc008623380?}, {0xc045b665a0, 0x8c, 0x8c})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/conn.go:1367](http://github.com/pingcap/tidb/server/conn.go:1367) +0x12a5\[ngithub.com/pingcap/tidb/server.(*clientConn).Run](http://ngithub.com/pingcap/tidb/server.(*clientConn).Run)(0xc0022652c0, {0x3d9d560, 0xc008623380})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/conn.go:1095](http://github.com/pingcap/tidb/server/conn.go:1095) +0x253\[ngithub.com/pingcap/tidb/server.(*Server).onConn](http://ngithub.com/pingcap/tidb/server.(*Server).onConn)(0xc0016f7930, 0xc0022652c0)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/server.go:551](http://github.com/pingcap/tidb/server/server.go:551) +0x6ad\ncreated by [github.com/pingcap/tidb/server.(*Server).startNetworkListener\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:448](http://github.com/pingcap/tidb/server.(*Server).startNetworkListener/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:448) +0x5ca\n"]
[2022/03/23 16:17:26.817 +00:00] [ERROR] [conn.go:1031] ["connection running loop panic"] [conn=2503] [lastSQL="UPDATE sbtest20 SET c=? WHERE id=? [arguments: (\"01128557831-34039195420-46519135614-75239671681-09405034496-35724770478-11304592662-61790548126-55853276960-60535899351\", 2150)]"] [err="runtime error: index out of range [4] with length 4"] [stack="goroutine 71445914 [running]:\[ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1()\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1029](http://ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1()/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1029) +0x8f\npanic({0x36483e0, 0xc038ae7a70})\n\t/usr/local/go/src/runtime/panic.go:838 +0x207\[ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:362](http://ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:362) +0x3b3\npanic({0x36483e0, 0xc038ae7a70})\n\t/usr/local/go/src/runtime/panic.go:838 +0x207\[ngithub.com/pingcap/tidb/planner/core.CheckUpdateList](http://ngithub.com/pingcap/tidb/planner/core.CheckUpdateList)({0xc01db71940, 0xc035043d40?, 0x4}, 0xc020d435f0, 0x20?)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4963](http://github.com/pingcap/tidb/planner/core/logical_plan_builder.go:4963) +0x6d1\[ngithub.com/pingcap/tidb/executor.(*executorBuilder).buildUpdate](http://ngithub.com/pingcap/tidb/executor.(*executorBuilder).buildUpdate)(0xc01357d000, 0xc020d435f0)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/executor/builder.go:2074](http://github.com/pingcap/tidb/executor/builder.go:2074) +0x345\[ngithub.com/pingcap/tidb/executor.(*executorBuilder).build](http://ngithub.com/pingcap/tidb/executor.(*executorBuilder).build)(0xc01357d000, {0x3db7a80?, 0xc020d435f0?})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/executor/builder.go:237](http://github.com/pingcap/tidb/executor/builder.go:237) +0xd45\[ngithub.com/pingcap/tidb/executor.(*ExecuteExec).Build](http://ngithub.com/pingcap/tidb/executor.(*ExecuteExec).Build)(0xc07663eb40, 0xc01357d000)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/executor/prepared.go:302](http://github.com/pingcap/tidb/executor/prepared.go:302) +0xec\[ngithub.com/pingcap/tidb/executor.(*ExecStmt).buildExecutor(0xc020d43ad0)\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:863](http://ngithub.com/pingcap/tidb/executor.(*ExecStmt).buildExecutor(0xc020d43ad0)/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:863) +0x59e\[ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec](http://ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec)(0xc020d43ad0, {0x3d9d560, 0xc01bfb5290})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/executor/adapter.go:399](http://github.com/pingcap/tidb/executor/adapter.go:399) +0x44b\[ngithub.com/pingcap/tidb/session.runStmt](http://ngithub.com/pingcap/tidb/session.runStmt)({0x3d9d560, 0xc01bfb4e70}, 0xc035043d40, {0x3da54a0, 0xc020d43ad0?})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/session.go:2017](http://github.com/pingcap/tidb/session/session.go:2017) +0x53d\[ngithub.com/pingcap/tidb/session.(*session).preparedStmtExec](http://ngithub.com/pingcap/tidb/session.(*session).preparedStmtExec)(0xc035043d40, {0x3d9d560, 0xc01bfb4e70}, {0x3dbc470?, 0xc0a436e9a0?}, 0x3d9d560?, 0x1ace0000?, 0xc001773b80?, {0xc00446a1b0, 0x2, ...})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/session.go:2162](http://github.com/pingcap/tidb/session/session.go:2162) +0x21e\[ngithub.com/pingcap/tidb/session.(*session).ExecutePreparedStmt](http://ngithub.com/pingcap/tidb/session.(*session).ExecutePreparedStmt)(0xc035043d40, {0x3d9d560, 0xc01bfb4e70}, 0xd6, {0xc00446a1b0, 0x2, 0x2})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/session.go:2338](http://github.com/pingcap/tidb/session/session.go:2338) +0x54d\[ngithub.com/pingcap/tidb/server.(*TiDBStatement).Execute](http://ngithub.com/pingcap/tidb/server.(*TiDBStatement).Execute)(0xc0204c67e0, {0x3d9d560?, 0xc01bfb4e70?}, {0xc00446a1b0?, 0x7fe9c69a4108?, 0x30?})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/driver_tidb.go:75](http://github.com/pingcap/tidb/server/driver_tidb.go:75) +0x5c\[ngithub.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult](http://ngithub.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult)(0xc001773b80, {0x3d9d560, 0xc01bfb4e70}, {0x3db3938, 0xc0204c67e0}, {0xc00446a1b0?, 0xc044d3132c?, 0x80?}, 0x0)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/conn_stmt.go:237](http://github.com/pingcap/tidb/server/conn_stmt.go:237) +0x89\[ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtExecute](http://ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtExecute)(0xc001773b80, {0x3d9d4b8, 0xc015dccc00}, {0xc044d31321, 0x8b, 0x8b})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/conn_stmt.go:209](http://github.com/pingcap/tidb/server/conn_stmt.go:209) +0x70e\[ngithub.com/pingcap/tidb/server.(*clientConn).dispatch](http://ngithub.com/pingcap/tidb/server.(*clientConn).dispatch)(0xc001773b80, {0x3d9d560?, 0xc009a41c80?}, {0xc044d31320, 0x8c, 0x8c})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/conn.go:1367](http://github.com/pingcap/tidb/server/conn.go:1367) +0x12a5\[ngithub.com/pingcap/tidb/server.(*clientConn).Run](http://ngithub.com/pingcap/tidb/server.(*clientConn).Run)(0xc001773b80, {0x3d9d560, 0xc009a41c80})\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/conn.go:1095](http://github.com/pingcap/tidb/server/conn.go:1095) +0x253\[ngithub.com/pingcap/tidb/server.(*Server).onConn](http://ngithub.com/pingcap/tidb/server.(*Server).onConn)(0xc0016f7930, 0xc001773b80)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/server.go:551](http://github.com/pingcap/tidb/server/server.go:551) +0x6ad\ncreated by [github.com/pingcap/tidb/server.(*Server).startNetworkListener\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:448](http://github.com/pingcap/tidb/server.(*Server).startNetworkListener/n/t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:448) +0x5ca\n"]

### 4. What is your TiDB version? (Required)
[root@centos76_vm oltp]# kubectl --kubeconfig kubeconfig.yml -n endless-oltp-tps-721881-1-634 exec -it tc-tidb-0 -- /bin/sh
/ # ./tidb-server -V
Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: b9bacad6dafabf5e2dfafee8e50ac66785e911b6
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-03-23 11:19:26
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

[2022/03/23 23:31:12.458 +08:00] [INFO] [client.go:376] ["Cluster version information"] [type=pd] [version=6.1.0-nightly] [git_hash=1ac0ad691260dabb61a25f30359e996a968ed857]
[2022/03/23 23:31:12.458 +08:00] [INFO] [client.go:376] ["Cluster version information"] [type=tikv] [version=6.0.0-alpha] [git_hash=869b953e798cabf29872fd17d526a7061437aec2]
[2022/03/23 23:31:12.458 +08:00] [INFO] [client.go:376] ["Cluster version information"] [type=tidb] [version=6.1.0-nightly] [git_hash=b9bacad6dafabf5e2dfafee8e50ac66785e911b6]

**Comment by mjonss** [comment]
Looks similar as #32311.

**Comment by bb7133** [comment]
I believe it is not limited to 'table partition' because of #32311, I will mark it as 'duplicated' and close this issue.
