### ISSUE TITLE
lightning panic due to column count mismatch

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tidb#33396]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table with x columns
import csv with lightning with columns > x
### 2. What did you expect to see? (Required)
lightning report error
### 3. What did you see instead (Required)
```
panic: runtime error: index out of range [265] with length 265
goroutine 275 [running]:
github.com/pingcap/tidb/br/pkg/lightning/backend/tidb.(*tidbEncoder).Encode(0xc0000b3d60, 0xc00168c060, 0xc001d0e000, 0xe4ad, 0xe4ad, 0x1, 0xc0002b4000, 0x109, 0x10a, 0xc000066abe, ...)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/tidb/tidb.go:321 +0xfc5
github.com/pingcap/tidb/br/pkg/lightning/restore.(*chunkRestore).encodeLoop(0xc0005a6940, 0x4760048, 0xc0002d1740, 0xc00168c000, 0xc0004db800, 0xc00168c060, 0x4736a58, 0xc0000b3d60, 0xc00005d200, 0xc000991900, ...)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/restore.go:2389 +0x3ad
github.com/pingcap/tidb/br/pkg/lightning/restore.(*chunkRestore).restore(0xc0005a6940, 0x4760048, 0xc0002d1740, 0xc0004db800, 0x0, 0xc0005a6960, 0xc0005a6980, 0xc000991900, 0x0, 0x0)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/restore.go:2484 +0x713
github.com/pingcap/tidb/br/pkg/lightning/restore.(*TableRestore).restoreEngine.func3(0xc000524f40, 0xc000991900, 0x3ff0000000000000, 0x4760048, 0xc0002d1740, 0xc0004db800, 0xc000000000, 0xc0005a6960, 0xc0005a6980, 0xc000524f28, ...)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/table_restore.go:542 +0x17e
created by github.com/pingcap/tidb/br/pkg/lightning/restore.(*TableRestore).restoreEngine
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/table_restore.go:534 +0x9a9
```

**Comment by GMHDBJD** [comment]
cause by https://github.com/pingcap/tidb/pull/27850
We may return a error rather than panic.
