### ISSUE TITLE
[FAIL]  executor TestHashRowContainer

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#33749]

**Comment by tiancaiamao** [comment]
```
[2022/04/07 09:59:19.670 +08:00] [WARN] [action.go:90] ["memory exceeds quota"] [error="[util:8001]%!s(int=-13) holds 1884B memory, exceeds threshold 1B.\n\"-13\"{\n  \"quota\": 1 Bytes\n  \"consumed\": 1.84 KB\n}\n"] [errorVerbose="[util:8001]%!s(int=-13) holds 1884B memory, exceeds threshold 1B.\n\"-13\"{\n  \"quota\": 1 Bytes\n  \"consumed\": 1.84 KB\n}\n\ngithub.com/pingcap/errors.AddStack\n\t/home/genius/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\t/home/genius/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/normalize.go:164\ngithub.com/pingcap/tidb/util/memory.(*LogOnExceed).Action\n\t/home/genius/project/src/github.com/pingcap/tidb/util/memory/action.go:91\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func1\n\t/home/genius/project/src/github.com/pingcap/tidb/util/memory/tracker.go:336\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/genius/project/src/github.com/pingcap/tidb/util/memory/tracker.go:344\ngithub.com/pingcap/tidb/util/chunk.(*List).Add\n\t/home/genius/project/src/github.com/pingcap/tidb/util/chunk/list.go:116\ngithub.com/pingcap/tidb/util/chunk.(*RowContainer).Add\n\t/home/genius/project/src/github.com/pingcap/tidb/util/chunk/row_container.go:226\ngithub.com/pingcap/tidb/executor.(*hashRowContainer).PutChunkSelected\n\t/home/genius/project/src/github.com/pingcap/tidb/executor/hash_table.go:166\ngithub.com/pingcap/tidb/executor.(*hashRowContainer).PutChunk\n\t/home/genius/project/src/github.com/pingcap/tidb/executor/hash_table.go:155\ngithub.com/pingcap/tidb/executor.testHashRowContainer\n\t/home/genius/project/src/github.com/pingcap/tidb/executor/hash_table_test.go:137\ngithub.com/pingcap/tidb/executor.TestHashRowContainer\n\t/home/genius/project/src/github.com/pingcap/tidb/executor/hash_table_test.go:95\ntesting.tRunner\n\t/home/genius/project/go/src/testing/testing.go:1439\nruntime.goexit\n\t/home/genius/project/go/src/runtime/asm_amd64.s:1571"]
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 87 [running]:
runtime.throw({0x5628c86?, 0x284287e?})
        /home/genius/project/go/src/runtime/panic.go:992 +0x71 fp=0xc0005df5a8 sp=0xc0005df578 pc=0x1340051
runtime.checkptrAlignment(0x9?, 0x7f?, 0x8?)
        /home/genius/project/go/src/runtime/checkptr.go:26 +0x6c fp=0xc0005df5c8 sp=0xc0005df5a8 pc=0x131036c
github.com/pingcap/tidb/util/chunk.(*Column).GetInt64(...)
        /home/genius/project/src/github.com/pingcap/tidb/util/chunk/column.go:542
github.com/pingcap/tidb/util/chunk.Row.GetInt64(...)
        /home/genius/project/src/github.com/pingcap/tidb/util/chunk/row.go:53
github.com/pingcap/tidb/util/codec.encodeHashChunkRowIdx(0xc0005e0098?, {0xc00001c780?, 0x0?}, 0xc00082cd80, 0x2)
        /home/genius/project/src/github.com/pingcap/tidb/util/codec/codec.go:307 +0x97f fp=0xc0005df848 sp=0xc0005df5c8 pc=0x283d95f
github.com/pingcap/tidb/util/codec.EqualChunkRow(0x282f8aa?, {0xc00001c780?, 0x10?}, {0xc000be0e70, 0x6, 0xc0005dfa28?}, {0xc0001b9b90, 0x2, 0x282f6f9?}, {0xc00001c730, ...}, ...)
        /home/genius/project/src/github.com/pingcap/tidb/util/codec/codec.go:699 +0x1fe fp=0xc0005df930 sp=0xc0005df848 pc=0x284287e
github.com/pingcap/tidb/executor.(*hashRowContainer).matchJoinKey(0xc0005d6c30, {0xc00001c780?, 0x0?}, {0xc00001c730?, 0x10?}, 0xc0005dfd58)
        /home/genius/project/src/github.com/pingcap/tidb/executor/hash_table.go:140 +0x23b fp=0xc0005dfa60 sp=0xc0005df930 pc=0x443b81b
github.com/pingcap/tidb/executor.(*hashRowContainer).GetMatchedRowsAndPtrs(0xc0005d6c30, 0xc000524ea0?, {0xc00001c730?, 0x0?}, 0x0?)
        /home/genius/project/src/github.com/pingcap/tidb/executor/hash_table.go:124 +0x211 fp=0xc0005dfb40 sp=0xc0005dfa60 pc=0x443b2d1
github.com/pingcap/tidb/executor.testHashRowContainer(0x6870ff0?, 0x57247a0, 0x1)
        /home/genius/project/src/github.com/pingcap/tidb/executor/hash_table_test.go:158 +0x1176 fp=0xc0005dfde0 sp=0xc0005dfb40 pc=0x4621816
github.com/pingcap/tidb/executor.TestHashRowContainer(0x0?)
        /home/genius/project/src/github.com/pingcap/tidb/executor/hash_table_test.go:95 +0x25b fp=0xc0005dfea8 sp=0xc0005dfde0 pc=0x46201db
testing.tRunner(0xc000524ea0, 0x571f7c8)
        /home/genius/project/go/src/testing/testing.go:1439 +0x214 fp=0xc0005dffb0 sp=0xc0005dfea8 pc=0x14c2a14
testing.(*T).Run.func1()
        /home/genius/project/go/src/testing/testing.go:1486 +0x48 fp=0xc0005dffe0 sp=0xc0005dffb0 pc=0x14c41c8
runtime.goexit()
        /home/genius/project/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0005dffe8 sp=0xc0005dffe0 pc=0x1376281
created by testing.(*T).Run
        /home/genius/project/go/src/testing/testing.go:1486 +0x725

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000524d00, {0x5559525, 0x14}, 0x571f7c8)
        /home/genius/project/go/src/testing/testing.go:1487 +0x750
testing.runTests.func1(0x0?)
        /home/genius/project/go/src/testing/testing.go:1839 +0x9a
testing.tRunner(0xc000524d00, 0xc000cbf930)
        /home/genius/project/go/src/testing/testing.go:1439 +0x214
testing.runTests(0xc000a7a0a0?, {0x81bc300, 0x3f7, 0x3f7}, {0xc000cbf9a8?, 0x13105a5?, 0x0?})
        /home/genius/project/go/src/testing/testing.go:1837 +0x7e5
testing.(*M).Run(0xc000a7a0a0)
        /home/genius/project/go/src/testing/testing.go:1719 +0xa72
github.com/pingcap/tidb/testkit/testmain.(*testingM).Run(0xc0001b1158)
        /home/genius/project/src/github.com/pingcap/tidb/testkit/testmain/wrapper.go:28 +0x43
go.uber.org/goleak.VerifyTestMain({0x6862920, 0xc0001b1158}, {0xc000cbfe20, 0x5, 0x5})
        /home/genius/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x5a
github.com/pingcap/tidb/executor_test.TestMain(0xc000a7a0a0)
        /home/genius/project/src/github.com/pingcap/tidb/executor/main_test.go:70 +0xab7
main.main()
        _testmain.go:2123 +0x318

goroutine 12 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
        /home/genius/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
        /home/genius/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x265

goroutine 13 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000a5a680)
        /home/genius/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0x177
created by go.opencensus.io/stats/view.init.0
        /home/genius/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0xf7
err=exit status 1
```


TiDB version 37d86dada8885e4fcaa1bf73c5404b86489be3fe

**Comment by tiancaiamao** [comment]
@wshwsh12

**Comment by tiancaiamao** [comment]
@wshwsh12

**Comment by tiancaiamao** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/30342
