### ISSUE TITLE
[FAIL]  ddl TestStateChange

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#33748]

**Comment by tiancaiamao** [comment]
```
--- FAIL: TestStateChange (31.39s)
    --- FAIL: TestStateChange/TestParallelAlterAddPartition (0.14s)
        suite.go:63: test panicked: should not happened
            goroutine 4055 [running]:
            runtime/debug.Stack()
                /home/genius/project/go/src/runtime/debug/stack.go:24 +0x72
            github.com/stretchr/testify/suite.failOnPanic(0xc006d4d380)
                /home/genius/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:63 +0x45
            panic({0x4c6e600, 0x62b0b10})
                /home/genius/project/go/src/runtime/panic.go:844 +0x258
            github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()
                /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:362 +0x510
            panic({0x4c6e600, 0x62b0b10})
                /home/genius/project/go/src/runtime/panic.go:844 +0x258
            github.com/pingcap/tidb/ddl.checkRangeCntByTableIDs(...)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/sanity_check.go:34
            github.com/pingcap/tidb/ddl.(*ddl).checkDeleteRangeCnt(0xc000a33180, 0xc0046eac60)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/sanity_check.go:105 +0x1c0b
            github.com/pingcap/tidb/ddl.(*ddl).checkHistoryJobInTest(0xc000a33180?, {0x63298d0, 0xc006d5d200}, 0xc0046eac60)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/sanity_check.go:173 +0x215
            github.com/pingcap/tidb/ddl.(*ddl).DoDDLJob(0xc000a33180, {0x63298d0, 0xc006d5d200}, 0xc00067ec60)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/ddl.go:688 +0xf11
            github.com/pingcap/tidb/ddl.(*ddl).DropTable(0x7ff8fc158a20?, {0x63298d0, 0xc006d5d200}, {{{0x519efaf, 0xd}, {0x519efaf, 0xd}}, {{0x51c5fbc, 0x6}, {0x51c5fbc, ...}}})
                /home/genius/project/src/github.com/pingcap/tidb/ddl/ddl_api.go:5227 +0x737
            github.com/pingcap/tidb/executor.(*DDLExec).dropTableObject(0xc00498a280, {0xc006d465e0, 0x1, 0x519efaf?}, 0x0, 0x1)
                /home/genius/project/src/github.com/pingcap/tidb/executor/ddl.go:492 +0x10c8
            github.com/pingcap/tidb/executor.(*DDLExec).executeDropTable(...)
                /home/genius/project/src/github.com/pingcap/tidb/executor/ddl.go:437
            github.com/pingcap/tidb/executor.(*DDLExec).Next(0xc00498a280, {0x62d6ef8, 0xc00057a180}, 0xc004613590?)
                /home/genius/project/src/github.com/pingcap/tidb/executor/ddl.go:161 +0x8c5
            github.com/pingcap/tidb/executor.Next({0x62d6ef8, 0xc00057a180}, {0x62d8ff0, 0xc00498a280}, 0xc004613590)
                /home/genius/project/src/github.com/pingcap/tidb/executor/executor.go:302 +0x53b
            github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc00041e750, {0x62d6ef8, 0xc00057a180}, {0x62d8ff0?, 0xc00498a280})
                /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:635 +0x6a5
            github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc00041e750, {0x62d6ef8, 0xc00057a180}, {0x62d8ff0, 0xc00498a280?}, 0x0)
                /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:490 +0x29d
            github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc00041e750, {0x62d6ef8, 0xc00057a180})
                /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:439 +0xbed
            github.com/pingcap/tidb/session.runStmt({0x62d6e88, 0xc000052108}, 0xc006d5d200, {0x62ded80, 0xc00041e750?})
                /home/genius/project/src/github.com/pingcap/tidb/session/session.go:2017 +0x6cc
            github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc006d5d200, {0x62d6e88, 0xc000052108}, {0x62e73b0, 0xc000488620})
                /home/genius/project/src/github.com/pingcap/tidb/session/session.go:1894 +0xd3b
            github.com/pingcap/tidb/testkit.(*TestKit).Exec(0xc005547480, {0x51c5fa7, 0x1b}, {0x0, 0x0, 0x1?})
                /home/genius/project/src/github.com/pingcap/tidb/testkit/testkit.go:209 +0x6bd
            github.com/pingcap/tidb/testkit.(*TestKit).MustExec(0xc005547480, {0x51c5fa7, 0x1b}, {0x0, 0x0, 0x0})
                /home/genius/project/src/github.com/pingcap/tidb/testkit/testkit.go:88 +0x9a
            github.com/pingcap/tidb/ddl_test.(*stateChangeSuite).testControlParallelExecSQL(0xc0006bda40, {0x0, 0x0}, {0x52764bd, 0x4f}, {0x527650c, 0x4f}, 0xc0069f93f8)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/db_change_test.go:1338 +0x1ed
            github.com/pingcap/tidb/ddl_test.(*stateChangeSuite).TestParallelAlterAddPartition(0xc0006bda40)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/db_change_test.go:1196 +0x65
            reflect.Value.call({0xc0005312c0?, 0xc000a359e0?, 0x12afc8d?}, {0x517873e, 0x4}, {0xc000173db8, 0x1, 0xc000173be8?})
                /home/genius/project/go/src/reflect/value.go:556 +0xd9d
            reflect.Value.Call({0xc0005312c0?, 0xc000a359e0?, 0xc0006bda40?}, {0xc000173db8, 0x1, 0x1})
                /home/genius/project/go/src/reflect/value.go:339 +0xd8
            github.com/stretchr/testify/suite.Run.func1(0xc006d4d380)
                /home/genius/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:158 +0x6dd
            testing.tRunner(0xc006d4d380, 0xc004974510)
                /home/genius/project/go/src/testing/testing.go:1439 +0x214
            created by testing.(*T).Run
                /home/genius/project/go/src/testing/testing.go:1486 +0x725
```


TiDB version 37d86dada8885e4fcaa1bf73c5404b86489be3fe

**Comment by tiancaiamao** [comment]
```
   --- FAIL: TestStateChange/TestParallelAlterSchemaCharsetAndCollate (0.17s)
        suite.go:63: test panicked: should not happened
            goroutine 5878 [running]:
            runtime/debug.Stack()
                /home/genius/project/go/src/runtime/debug/stack.go:24 +0x72
            github.com/stretchr/testify/suite.failOnPanic(0xc0064a4b60)
                /home/genius/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:63 +0x45
            panic({0x4c6e600, 0x62b0b10})
                /home/genius/project/go/src/runtime/panic.go:844 +0x258
            github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()
                /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:362 +0x510
            panic({0x4c6e600, 0x62b0b10})
                /home/genius/project/go/src/runtime/panic.go:844 +0x258
            github.com/pingcap/tidb/ddl.checkRangeCntByTableIDs(...)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/sanity_check.go:34
            github.com/pingcap/tidb/ddl.(*ddl).checkDeleteRangeCnt(0xc000a33180, 0xc006b2f680)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/sanity_check.go:105 +0x1c0b
            github.com/pingcap/tidb/ddl.(*ddl).checkHistoryJobInTest(0xc000a33180?, {0x63298d0, 0xc004689680}, 0xc006b2f680)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/sanity_check.go:173 +0x215
            github.com/pingcap/tidb/ddl.(*ddl).DoDDLJob(0xc000a33180, {0x63298d0, 0xc004689680}, 0xc0067d9e60)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/ddl.go:688 +0xf11
            github.com/pingcap/tidb/ddl.(*ddl).DropTable(0x12da9f3?, {0x63298d0, 0xc004689680}, {{{0x519efaf, 0xd}, {0x519efaf, 0xd}}, {{0x51c5fbc, 0x6}, {0x51c5fbc, ...}}})
                /home/genius/project/src/github.com/pingcap/tidb/ddl/ddl_api.go:5227 +0x737
            github.com/pingcap/tidb/executor.(*DDLExec).dropTableObject(0xc004ac8dc0, {0xc005812868, 0x1, 0x519efaf?}, 0x0, 0x1)
                /home/genius/project/src/github.com/pingcap/tidb/executor/ddl.go:492 +0x10c8
            github.com/pingcap/tidb/executor.(*DDLExec).executeDropTable(...)
                /home/genius/project/src/github.com/pingcap/tidb/executor/ddl.go:437
            github.com/pingcap/tidb/executor.(*DDLExec).Next(0xc004ac8dc0, {0x62d6ef8, 0xc006036ea0}, 0xc004ab1040?)
                /home/genius/project/src/github.com/pingcap/tidb/executor/ddl.go:161 +0x8c5
            github.com/pingcap/tidb/executor.Next({0x62d6ef8, 0xc006036ea0}, {0x62d8ff0, 0xc004ac8dc0}, 0xc004ab1040)
                /home/genius/project/src/github.com/pingcap/tidb/executor/executor.go:302 +0x53b
            github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc004a8b6c0, {0x62d6ef8, 0xc006036ea0}, {0x62d8ff0?, 0xc004ac8dc0})
                /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:635 +0x6a5
            github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc004a8b6c0, {0x62d6ef8, 0xc006036ea0}, {0x62d8ff0, 0xc004ac8dc0?}, 0x0)
                /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:490 +0x29d
            github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc004a8b6c0, {0x62d6ef8, 0xc006036ea0})
                /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:439 +0xbed
            github.com/pingcap/tidb/session.runStmt({0x62d6e88, 0xc000052108}, 0xc004689680, {0x62ded80, 0xc004a8b6c0?})
                /home/genius/project/src/github.com/pingcap/tidb/session/session.go:2017 +0x6cc
            github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc004689680, {0x62d6e88, 0xc000052108}, {0x62e73b0, 0xc006131f10})
                /home/genius/project/src/github.com/pingcap/tidb/session/session.go:1894 +0xd3b
            github.com/pingcap/tidb/testkit.(*TestKit).Exec(0xc005c8a040, {0x51c5fa7, 0x1b}, {0x0, 0x0, 0x1?})
                /home/genius/project/src/github.com/pingcap/tidb/testkit/testkit.go:209 +0x6bd
            github.com/pingcap/tidb/testkit.(*TestKit).MustExec(0xc005c8a040, {0x51c5fa7, 0x1b}, {0x0, 0x0, 0x0})
                /home/genius/project/src/github.com/pingcap/tidb/testkit/testkit.go:88 +0x9a
            github.com/pingcap/tidb/ddl_test.(*stateChangeSuite).testControlParallelExecSQL(0xc0006bda40, {0x0, 0x0}, {0x5267e6f, 0x45}, {0x5267e6f, 0x45}, 0xc004bed3f8)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/db_change_test.go:1338 +0x1ed
            github.com/pingcap/tidb/ddl_test.(*stateChangeSuite).TestParallelAlterSchemaCharsetAndCollate(0xc0006bda40)
                /home/genius/project/src/github.com/pingcap/tidb/ddl/db_change_test.go:1582 +0x69
            reflect.Value.call({0xc0005312c0?, 0xc000a35a70?, 0x12afc8d?}, {0x517873e, 0x4}, {0xc00497fdb8, 0x1, 0xc00497fbe8?})
                /home/genius/project/go/src/reflect/value.go:556 +0xd9d
            reflect.Value.Call({0xc0005312c0?, 0xc000a35a70?, 0xc0006bda40?}, {0xc00497fdb8, 0x1, 0x1})
                /home/genius/project/go/src/reflect/value.go:339 +0xd8
            github.com/stretchr/testify/suite.Run.func1(0xc0064a4b60)
                /home/genius/go/pkg/mod/github.com/stretchr/testify@v1.7.0/suite/suite.go:158 +0x6dd
            testing.tRunner(0xc0064a4b60, 0xc004974900)
                /home/genius/project/go/src/testing/testing.go:1439 +0x214
            created by testing.(*T).Run
                /home/genius/project/go/src/testing/testing.go:1486 +0x725
```

**Comment by tiancaiamao** [comment]
```
==================
WARNING: DATA RACE
Write at 0x00c000b00ce8 by goroutine 62:
  github.com/pingcap/tidb/statistics/handle.(*Handle).UpdateSessionVar()
      /home/genius/project/src/github.com/pingcap/tidb/statistics/handle/handle.go:315 +0x1b4
  github.com/pingcap/tidb/statistics/handle.(*Handle).HandleAutoAnalyze()
      /home/genius/project/src/github.com/pingcap/tidb/statistics/handle/update.go:1013 +0x5a
  github.com/pingcap/tidb/domain.(*Domain).autoAnalyzeWorker()
      /home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:1495 +0x24d
  github.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop.func2()
      /home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:1314 +0x4c
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      /home/genius/project/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:33 +0x73

Previous read at 0x00c000b00ce8 by goroutine 57:
  github.com/pingcap/tidb/statistics/handle.(*Handle).mergePartitionStats2GlobalStats()
      /home/genius/project/src/github.com/pingcap/tidb/statistics/handle/handle.go:448 +0x145a
  github.com/pingcap/tidb/statistics/handle.(*Handle).updateGlobalStats()
      /home/genius/project/src/github.com/pingcap/tidb/statistics/handle/ddl.go:110 +0x5cf
  github.com/pingcap/tidb/statistics/handle.(*Handle).HandleDDLEvent()
      /home/genius/project/src/github.com/pingcap/tidb/statistics/handle/ddl.go:58 +0x196
  github.com/pingcap/tidb/domain.(*Domain).updateStatsWorker()
      /home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:1442 +0x4a8
  github.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop.func1()
      /home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:1312 +0x68
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
      /home/genius/project/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:33 +0x73

Goroutine 62 (running) created at:
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run()
      /home/genius/project/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:31 +0xdc
  github.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop()
      /home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:1314 +0x544
  github.com/pingcap/tidb/domain.(*Domain).LoadAndUpdateStatsLoop()
      /home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:1281 +0x6b
  github.com/pingcap/tidb/session.BootstrapSession()
      /home/genius/project/src/github.com/pingcap/tidb/session/session.go:2870 +0xa69
  github.com/pingcap/tidb/ddl_test.(*stateChangeSuite).SetupSuite()
      /home/genius/project/src/github.com/pingcap/tidb/ddl/db_change_test.go:74 +0xf9
  github.com/stretchr/testify/suite.Run()
      /home/genius/go/pkg/mod/github.com/hawkingrei/testify@v1.7.1-0.20220318075534-088488aa27f2/suite/suite.go:128 +0x597
  github.com/pingcap/tidb/ddl_test.TestStateChange()
      /home/genius/project/src/github.com/pingcap/tidb/ddl/db_change_test.go:64 +0x44
  testing.tRunner()
      /home/genius/project/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /home/genius/project/go/src/testing/testing.go:1486 +0x47

Goroutine 57 (running) created at:
  github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run()
      /home/genius/project/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:31 +0xdc
  github.com/pingcap/tidb/domain.(*Domain).UpdateTableStatsLoop()
      /home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:1312 +0x476
  github.com/pingcap/tidb/domain.(*Domain).LoadAndUpdateStatsLoop()
      /home/genius/project/src/github.com/pingcap/tidb/domain/domain.go:1281 +0x6b
  github.com/pingcap/tidb/session.BootstrapSession()
      /home/genius/project/src/github.com/pingcap/tidb/session/session.go:2870 +0xa69
  github.com/pingcap/tidb/ddl_test.(*stateChangeSuite).SetupSuite()
      /home/genius/project/src/github.com/pingcap/tidb/ddl/db_change_test.go:74 +0xf9
  github.com/stretchr/testify/suite.Run()
      /home/genius/go/pkg/mod/github.com/hawkingrei/testify@v1.7.1-0.20220318075534-088488aa27f2/suite/suite.go:128 +0x597
  github.com/pingcap/tidb/ddl_test.TestStateChange()
      /home/genius/project/src/github.com/pingcap/tidb/ddl/db_change_test.go:64 +0x44
  testing.tRunner()
      /home/genius/project/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /home/genius/project/go/src/testing/testing.go:1486 +0x47
==================
```

TiDB version 14f4888fb3d7fa5bfbc8eb8c3e86d38e724c93e9

**Comment by jebter** [comment]
Please try the latest version. I will close it,if there are any updates, you can reopen it.
