### ISSUE TITLE
[FAIL]  ddl TestCreateTable

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#33746]

**Comment by tiancaiamao** [comment]
make ut X='run ddl TestCreateTable --race'

```
--- FAIL: TestCreateTableWithRangeColumnPartition (0.99s)
panic: should not happened [recovered]
        panic: should not happened [recovered]
        panic: should not happened

goroutine 2747 [running]:
testing.tRunner.func1.2({0x4c6e600, 0x62b0b10})
        /home/genius/project/go/src/testing/testing.go:1389 +0x366
testing.tRunner.func1()
        /home/genius/project/go/src/testing/testing.go:1392 +0x5d2
panic({0x4c6e600, 0x62b0b10})
        /home/genius/project/go/src/runtime/panic.go:844 +0x258
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()
        /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:362 +0x510
panic({0x4c6e600, 0x62b0b10})
        /home/genius/project/go/src/runtime/panic.go:844 +0x258
github.com/pingcap/tidb/ddl.checkRangeCntByTableIDs(...)
        /home/genius/project/src/github.com/pingcap/tidb/ddl/sanity_check.go:34
github.com/pingcap/tidb/ddl.(*ddl).checkDeleteRangeCnt(0xc00149dc80, 0xc000eca120)
        /home/genius/project/src/github.com/pingcap/tidb/ddl/sanity_check.go:105 +0x1c0b
github.com/pingcap/tidb/ddl.(*ddl).checkHistoryJobInTest(0xc00149dc80?, {0x63298d0, 0xc002ba0000}, 0xc000eca120)
        /home/genius/project/src/github.com/pingcap/tidb/ddl/sanity_check.go:173 +0x215
github.com/pingcap/tidb/ddl.(*ddl).DoDDLJob(0xc00149dc80, {0x63298d0, 0xc002ba0000}, 0xc000a14b40)
        /home/genius/project/src/github.com/pingcap/tidb/ddl/ddl.go:688 +0xf11
github.com/pingcap/tidb/ddl.(*ddl).DropTable(0x12da9f3?, {0x63298d0, 0xc002ba0000}, {{{0x5184da6, 0x4}, {0x5184da6, 0x4}}, {{0x51b4214, 0x1}, {0x51b4214, ...}}})
        /home/genius/project/src/github.com/pingcap/tidb/ddl/ddl_api.go:5227 +0x737
github.com/pingcap/tidb/executor.(*DDLExec).dropTableObject(0xc000c60b40, {0xc00192f8b0, 0x1, 0x5184da6?}, 0x0, 0x1)
        /home/genius/project/src/github.com/pingcap/tidb/executor/ddl.go:492 +0x10c8
github.com/pingcap/tidb/executor.(*DDLExec).executeDropTable(...)
        /home/genius/project/src/github.com/pingcap/tidb/executor/ddl.go:437
github.com/pingcap/tidb/executor.(*DDLExec).Next(0xc000c60b40, {0x62d6ef8, 0xc0006162a0}, 0xc001594d70?)
        /home/genius/project/src/github.com/pingcap/tidb/executor/ddl.go:161 +0x8c5
github.com/pingcap/tidb/executor.Next({0x62d6ef8, 0xc0006162a0}, {0x62d8ff0, 0xc000c60b40}, 0xc001594d70)
        /home/genius/project/src/github.com/pingcap/tidb/executor/executor.go:302 +0x53b
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc00126bee0, {0x62d6ef8, 0xc0006162a0}, {0x62d8ff0?, 0xc000c60b40})
        /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:635 +0x6a5
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc00126bee0, {0x62d6ef8, 0xc0006162a0}, {0x62d8ff0, 0xc000c60b40?}, 0x0)
        /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:490 +0x29d
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc00126bee0, {0x62d6ef8, 0xc0006162a0})
        /home/genius/project/src/github.com/pingcap/tidb/executor/adapter.go:439 +0xbed
github.com/pingcap/tidb/session.runStmt({0x62d6e88, 0xc000140008}, 0xc002ba0000, {0x62ded80, 0xc00126bee0?})
        /home/genius/project/src/github.com/pingcap/tidb/session/session.go:2017 +0x6cc
github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc002ba0000, {0x62d6e88, 0xc000140008}, {0x62e73b0, 0xc002a64b60})
        /home/genius/project/src/github.com/pingcap/tidb/session/session.go:1894 +0xd3b
github.com/pingcap/tidb/testkit.(*TestKit).Exec(0xc0029c9580, {0x51b41ff, 0x17}, {0x0, 0x0, 0x1?})
        /home/genius/project/src/github.com/pingcap/tidb/testkit/testkit.go:209 +0x6bd
github.com/pingcap/tidb/testkit.(*TestKit).MustExec(0xc0029c9580, {0x51b41ff, 0x17}, {0x0, 0x0, 0x0})
        /home/genius/project/src/github.com/pingcap/tidb/testkit/testkit.go:88 +0x9a
github.com/pingcap/tidb/ddl_test.TestCreateTableWithRangeColumnPartition(0x0?)
        /home/genius/project/src/github.com/pingcap/tidb/ddl/db_partition_test.go:640 +0x89d
testing.tRunner(0xc002565520, 0x52e9718)
        /home/genius/project/go/src/testing/testing.go:1439 +0x214
created by testing.(*T).Run
        /home/genius/project/go/src/testing/testing.go:1486 +0x725
run all tasks takes 16.348373818s
make: *** [Makefile:121: ut] Error 1
```

TiDB version 37d86dada8885e4fcaa1bf73c5404b86489be3fe

**Comment by tiancaiamao** [comment]
@wjhuang2016  Is this a duplicated issue or having PR already?

**Comment by wjhuang2016** [comment]
I think it's duplicated

**Comment by wjhuang2016** [comment]
Same as https://github.com/pingcap/tidb/issues/33759

**Comment by tiancaiamao** [comment]
OK, I'll close it now
