### ISSUE TITLE
index out of range [0] with length 0 in the bench 

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#34450]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
make bench-daily
```

```
go test github.com/pingcap/tidb/expression -run TestBenchDaily -bench Ignore --outfile bench_daily.json
panic: runtime error: index out of range [0] with length 0

goroutine 112 [running]:
github.com/pingcap/tidb/util/chunk.(*Column).AppendInt64(...)
        /Users/hawkingrei/devel/opensource/tidb/util/chunk/column.go:248
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendInt64(0xc0016c2000, 0x17, 0x0)
        /Users/hawkingrei/devel/opensource/tidb/util/chunk/chunk.go:481 +0x259
github.com/pingcap/tidb/expression.(*benchHelper).init(0xc0000a9eb0)
        /Users/hawkingrei/devel/opensource/tidb/expression/bench_test.go:87 +0x785
github.com/pingcap/tidb/expression.BenchmarkVectorizedExecute(0xc00015cb40)
        /Users/hawkingrei/devel/opensource/tidb/expression/bench_test.go:165 +0x5d
testing.(*B).runN(0xc00015cb40, 0x1)
        /usr/local/Cellar/go/1.18.1/libexec/src/testing/benchmark.go:193 +0x102
testing.(*B).run1.func1()
        /usr/local/Cellar/go/1.18.1/libexec/src/testing/benchmark.go:233 +0x59
created by testing.(*B).run1
        /usr/local/Cellar/go/1.18.1/libexec/src/testing/benchmark.go:226 +0x9c
exit status 2

```

**Comment by zanmato1984** [comment]
Introduced by https://github.com/pingcap/tidb/pull/33569. @BornChanger PTAL.

**Comment by zanmato1984** [comment]
This is a testing issue, changing severity to minor.

**Comment by BornChanger** [comment]
@xhebox Can you please take a look at this issue?
