### ISSUE TITLE
BenchmarkVectorizedExecute() broken after pr/33569

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#34490]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
cd expression;
go test -run TestXXX -bench BenchmarkVectorizedExecute
```

### 2. What did you expect to see? (Required)

Benchmark test run success

### 3. What did you see instead (Required)

```
panic: runtime error: index out of range [0] with length 0

goroutine 130 [running]:
github.com/pingcap/tidb/util/chunk.(*Column).AppendInt64(...)
	/home/genius/project/src/github.com/pingcap/tidb/util/chunk/column.go:248
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendInt64(0xc0003fa000, 0x17, 0x0)
	/home/genius/project/src/github.com/pingcap/tidb/util/chunk/chunk.go:481 +0x259
github.com/pingcap/tidb/expression.(*benchHelper).init(0xc0000a5eb0)
	/home/genius/project/src/github.com/pingcap/tidb/expression/bench_test.go:87 +0x785
github.com/pingcap/tidb/expression.BenchmarkVectorizedExecute(0xc0004f0900)
	/home/genius/project/src/github.com/pingcap/tidb/expression/bench_test.go:165 +0x5d
testing.(*B).runN(0xc0004f0900, 0x1)
	/home/genius/project/go/src/testing/benchmark.go:193 +0x102
testing.(*B).run1.func1()
	/home/genius/project/go/src/testing/benchmark.go:233 +0x59
created by testing.(*B).run1
	/home/genius/project/go/src/testing/benchmark.go:226 +0x9c
exit status 2
FAIL	github.com/pingcap/tidb/expression	0.049s
```

### 4. What is your TiDB version? (Required)

master 71bfde92927eda2b5b3d3588f48e59e5f55100b7

**Comment by tiancaiamao** [comment]
It breaks https://github.com/pingcap/tidb/issues/25754 a few days ago.
