### ISSUE TITLE
segmentation violation in the TestListPartitionView

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#35112]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
make ut
```

```
 [FAIL]  planner/core TestListPartitionView
err=exit status 2
[2022/06/01 19:06:54.274 +08:00] [INFO] [tidb.go:74] ["new domain"] [store=8018ab4d-3005-4883-9026-f139c8d290b4] ["ddl lease"=0s] ["stats lease"=-1ns] ["index usage sync lease"=0s]
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x3949bed]
goroutine 5 [running]:
runtime.throw({0x5885b3b?, 0xc000b631c5?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0008c6430 sp=0xc0008c6400 pc=0x14abd91
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc0008c6480 sp=0xc0008c6430 pc=0x14c4365
github.com/pingcap/tidb/ddl.buildColumnAndConstraint({0x6aeab00, 0xc0007129c0}, 0xc000b631c5?, 0xc00025a8bf, 0x14e42f9?, {0x588afa5, 0x7}, {0x58968cb, 0xb})
	/go/tidb/ddl/ddl_api.go:764 +0xad fp=0xc0008c6600 sp=0xc0008c6480 pc=0x3949bed
github.com/pingcap/tidb/ddl.buildColumnsAndConstraints({0x6aeab00, 0xc0007129c0}, {0xc000b22600, 0x29, 0x14e5ab7?}, {0x0, 0x0, 0x0}, {0x588afa5, 0x7}, ...)
	/go/tidb/ddl/ddl_api.go:650 +0x265 fp=0xc0008c67f8 sp=0xc0008c6600 pc=0x3948b65
github.com/pingcap/tidb/ddl.buildTableInfoWithStmt({0x6aeab00, 0xc0007129c0}, 0xc000b2fc70, {0x588afa5, 0x7}, {0x0, 0x0}, 0x0)
	/go/tidb/ddl/ddl_api.go:2112 +0x24c fp=0xc0008c6a08 sp=0xc0008c67f8 pc=0x395a12c
github.com/pingcap/tidb/ddl.buildTableInfoWithCheck({0x6aeab00, 0xc0007129c0}, 0x3a434cf?, {0x588afa5, 0x7}, {0x0, 0x0}, 0xc000b2a1e0?)
	/go/tidb/ddl/ddl_api.go:2056 +0x95 fp=0xc0008c6a80 sp=0xc0008c6a08 pc=0x39596b5
github.com/pingcap/tidb/ddl.BuildTableInfoFromAST(0x54103c0?)
	/go/tidb/ddl/ddl_api.go:2050 +0x53 fp=0xc0008c6af0 sp=0xc0008c6a80 pc=0x39595d3
github.com/pingcap/tidb/infoschema/perfschema.Init.func1()
	/go/tidb/infoschema/perfschema/init.go:51 +0x137 fp=0xc0008c6c38 sp=0xc0008c6af0 pc=0x3a433b7
sync.(*Once).doSlow(0x96d74b0, 0x5a01480)
	/usr/local/go/src/sync/once.go:68 +0x102 fp=0xc0008c6d08 sp=0xc0008c6c38 pc=0x150a982
sync.(*Once).Do(0x96d74b0, 0x4c7bc65?)
	/usr/local/go/src/sync/once.go:59 +0x47 fp=0xc0008c6d30 sp=0xc0008c6d08 pc=0x150a847
github.com/pingcap/tidb/infoschema/perfschema.Init()
	/go/tidb/infoschema/perfschema/init.go:75 +0x47 fp=0xc0008c6d50 sp=0xc0008c6d30 pc=0x3a43b47
github.com/pingcap/tidb/domain.(*Domain).Init(0xc000aec640, 0x0, 0xc00000e990)
	/go/tidb/domain/domain.go:754 +0xaa fp=0xc0008c7400 sp=0xc0008c6d50 pc=0x3a94d0a
github.com/pingcap/tidb/session.(*domainMap).Get.func1()
	/go/tidb/session/tidb.go:85 +0x665 fp=0xc0008c7688 sp=0xc0008c7400 pc=0x4c7bc65
github.com/pingcap/tidb/util.RunWithRetry(0x1e, 0x1f4, 0xc0008c7770)
	/go/tidb/util/misc.go:65 +0x94 fp=0xc0008c76e0 sp=0xc0008c7688 pc=0x2b49674
github.com/pingcap/tidb/session.(*domainMap).Get(0x8c91220, {0x6ab1460, 0xc000c14ec0})
	/go/tidb/session/tidb.go:73 +0x31a fp=0xc0008c7828 sp=0xc0008c76e0 pc=0x4c7b51a
github.com/pingcap/tidb/session.createSessionWithOpt({0x6ab1460, 0xc000c14ec0}, 0x0)
	/go/tidb/session/session.go:2969 +0x76 fp=0xc0008c79b0 sp=0xc0008c7828 pc=0x4c73df6
github.com/pingcap/tidb/session.createSession(...)
	/go/tidb/session/session.go:2965
github.com/pingcap/tidb/session.runInBootstrapSession({0x6ab1460, 0xc000c14ec0}, 0x5a029a0)
	/go/tidb/session/session.go:2935 +0x65 fp=0xc0008c7a98 sp=0xc0008c79b0 pc=0x4c738e5
github.com/pingcap/tidb/session.BootstrapSession({0x6ab1460, 0xc000c14ec0})
	/go/tidb/session/session.go:2830 +0x1f1 fp=0xc0008c7c08 sp=0xc0008c7a98 pc=0x4c72e51
github.com/pingcap/tidb/testkit.bootstrap({0x6ab4428?, 0xc000b31380}, {0x6ab1460?, 0xc000c14ec0}, 0x0?)
	/go/tidb/testkit/mockstore.go:49 +0x8d fp=0xc0008c7c90 sp=0xc0008c7c08 pc=0x4fca9ed
github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain({0x6ab4428?, 0xc000b31380}, {0x0, 0x0, 0x0})
	/go/tidb/testkit/mockstore.go:42 +0xce fp=0xc0008c7d10 sp=0xc0008c7c90 pc=0x4fca8ee
github.com/pingcap/tidb/testkit.CreateMockStore(...)
	/go/tidb/testkit/mockstore.go:34
github.com/pingcap/tidb/planner/core_test.TestListPartitionView(0x0?)
	/go/tidb/planner/core/integration_partition_test.go:670 +0x59 fp=0xc0008c7ea8 sp=0xc0008c7d10 pc=0x4fff2f9
testing.tRunner(0xc000b31380, 0x5a023b8)
	/usr/local/go/src/testing/testing.go:1439 +0x214 fp=0xc0008c7fb0 sp=0xc0008c7ea8 pc=0x164a254
testing.(*T).Run.func1()
	/usr/local/go/src/testing/testing.go:1486 +0x48 fp=0xc0008c7fe0 sp=0xc0008c7fb0 pc=0x164ba08
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0008c7fe8 sp=0xc0008c7fe0 pc=0x14e2ba1
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x725
goroutine 1 [chan receive]:
testing.(*T).Run(0xc000b311e0, {0x58b8602, 0x15}, 0x5a023b8)
	/usr/local/go/src/testing/testing.go:1487 +0x750
testing.runTests.func1(0x0?)
	/usr/local/go/src/testing/testing.go:1839 +0x9a
testing.tRunner(0xc000b311e0, 0xc00121f950)
	/usr/local/go/src/testing/testing.go:1439 +0x214
testing.runTests(0xc000c20000?, {0x857e960, 0x243, 0x243}, {0xc000c1ab60?, 0xc00121f9d0?, 0x8c92d40?})
	/usr/local/go/src/testing/testing.go:1837 +0x7e5
testing.(*M).Run(0xc000c20000)
	/usr/local/go/src/testing/testing.go:1719 +0xa72
github.com/pingcap/tidb/testkit/testmain.(*testingM).Run(0xc000b18a68)
	/go/tidb/testkit/testmain/wrapper.go:27 +0x43
go.uber.org/goleak.VerifyTestMain({0x6a78360, 0xc000b18a68}, {0xc000535dc8, 0x3, 0x3})
	/home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x5a
github.com/pingcap/tidb/planner/core.TestMain(0xc000c20000)
	/go/tidb/planner/core/main_test.go:66 +0x885
main.main()
	_testmain.go:1373 +0x3f8
goroutine 132 [select]:
github.com/pingcap/tidb/store/mockstore/unistore/tikv.writeLockWorker.run({0xc0005e5560?, 0xc000c14ac0?})
	/go/tidb/store/mockstore/unistore/tikv/write.go:148 +0x1dd
created by github.com/pingcap/tidb/store/mockstore/unistore/tikv.(*dbWriter).Open
	/go/tidb/store/mockstore/unistore/tikv/write.go:206 +0x1e5
goroutine 131 [select]:
github.com/pingcap/tidb/store/mockstore/unistore/tikv.writeDBWorker.run({0xc0005e5500?, 0xc000c14ac0?})
	/go/tidb/store/mockstore/unistore/tikv/write.go:96 +0x185
created by github.com/pingcap/tidb/store/mockstore/unistore/tikv.(*dbWriter).Open
	/go/tidb/store/mockstore/unistore/tikv/write.go:199 +0x10d
goroutine 68 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xc00046b908?)
	/home/prow/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/home/prow/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x265
goroutine 15 [select]:
github.com/pingcap/badger.(*writeWorker).runWriteVLog(0xc000aaa620, 0xc00000e8a0)
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/writer.go:94 +0x21b
created by github.com/pingcap/badger.startWriteWorker
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/writer.go:64 +0x3f7
goroutine 16 [chan receive, locked to thread]:
github.com/pingcap/badger.(*writeWorker).runWriteLSM(0xc000aaa620, 0xc00000e8a0)
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/writer.go:141 +0x21e
created by github.com/pingcap/badger.startWriteWorker
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/writer.go:65 +0x49b
goroutine 140 [runnable]:
github.com/dgraph-io/ristretto.NewCache.func7()
	/home/prow/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1-0.20220403145359-8e850b710d6d/cache.go:213
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1
created by github.com/dgraph-io/ristretto.NewCache
	/home/prow/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1-0.20220403145359-8e850b710d6d/cache.go:213 +0x1136
goroutine 130 [runnable]:
github.com/pingcap/badger.(*writeWorker).runMergeLSM(0xc000aaa620, 0xc00000e8a0)
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/writer.go:154 +0xf8
created by github.com/pingcap/badger.startWriteWorker
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/writer.go:66 +0x53b
goroutine 89 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001a5880)
	/home/prow/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0x177
created by go.opencensus.io/stats/view.init.0
	/home/prow/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0xf7
goroutine 11 [chan receive]:
github.com/pingcap/badger.(*DB).runFlushMemTable(0xc000036480, 0xc00000eee8)
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/db.go:920 +0x149
created by github.com/pingcap/badger.Open
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/db.go:361 +0x2127
goroutine 139 [runnable]:
github.com/dgraph-io/ristretto.newPolicy.func1()
	/home/prow/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1-0.20220403145359-8e850b710d6d/policy.go:51
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1
created by github.com/dgraph-io/ristretto.newPolicy
	/home/prow/go/pkg/mod/github.com/dgraph-io/ristretto@v0.1.1-0.20220403145359-8e850b710d6d/policy.go:51 +0x2d7
goroutine 10 [select]:
github.com/pingcap/badger.(*levelsController).runWorker(0xc0004a9ce0, 0xc00000e798, 0x0)
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/levels.go:212 +0x2e9
created by github.com/pingcap/badger.(*levelsController).startCompact
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/levels.go:180 +0xa9
goroutine 138 [runnable]:
github.com/tikv/client-go/v2/tikv.NewKVStore.func2()
	/home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220531081749-2807409d4968/tikv/kv.go:190
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1
created by github.com/tikv/client-go/v2/tikv.NewKVStore
	/home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220531081749-2807409d4968/tikv/kv.go:190 +0x6ef
goroutine 9 [select]:
github.com/pingcap/badger.(*blobGCHandler).run(0xc000c14980, 0xc00000e768)
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/blob.go:468 +0x174
created by github.com/pingcap/badger.(*blobManager).Open
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/blob.go:292 +0xa73
goroutine 137 [runnable]:
github.com/tikv/client-go/v2/tikv.NewKVStore.func1()
	/home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220531081749-2807409d4968/tikv/kv.go:189
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1
created by github.com/tikv/client-go/v2/tikv.NewKVStore
	/home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220531081749-2807409d4968/tikv/kv.go:189 +0x685
goroutine 8 [select]:
github.com/pingcap/badger.Open.func4()
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/db.go:342 +0x2f8
created by github.com/pingcap/badger.Open
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/db.go:339 +0x1c7c
goroutine 136 [runnable]:
github.com/tikv/client-go/v2/internal/locate.NewRegionCache.func1()
	/home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220531081749-2807409d4968/internal/locate/region_cache.go:407
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1
created by github.com/tikv/client-go/v2/internal/locate.NewRegionCache
	/home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220531081749-2807409d4968/internal/locate/region_cache.go:407 +0x5df
goroutine 7 [select]:
github.com/pingcap/badger/epoch.(*ResourceManager).collectLoop(0x7f7297c10008?, 0xc00000e900)
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/epoch/manager.go:101 +0x175
created by github.com/pingcap/badger/epoch.NewResourceManager
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/epoch/manager.go:79 +0x197
goroutine 135 [runnable]:
github.com/tikv/client-go/v2/oracle/oracles.NewPdOracle.func1()
	/home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220531081749-2807409d4968/oracle/oracles/pd.go:77
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1
created by github.com/tikv/client-go/v2/oracle/oracles.NewPdOracle
	/home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220531081749-2807409d4968/oracle/oracles/pd.go:77 +0x21b
goroutine 6 [select]:
github.com/pingcap/badger.(*DB).updateSize(0x7f7297c10008?, 0xc00000e8d0)
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/db.go:1039 +0x1d6
created by github.com/pingcap/badger.Open
	/home/prow/go/pkg/mod/github.com/pingcap/badger@v1.5.1-0.20220314162537-ab58fbf40580/db.go:328 +0x1706
goroutine 134 [select]:
github.com/pingcap/tidb/store/mockstore/unistore/tikv.(*MVCCStore).StartDeadlockDetection.func1()
	/go/tidb/store/mockstore/unistore/tikv/mvcc.go:1378 +0x111
created by github.com/pingcap/tidb/store/mockstore/unistore/tikv.(*MVCCStore).StartDeadlockDetection
	/go/tidb/store/mockstore/unistore/tikv/mvcc.go:1376 +0x137
goroutine 133 [select]:
github.com/pingcap/tidb/store/mockstore/unistore/tikv.(*MVCCStore).runUpdateSafePointLoop(0xc000af3b80)
	/go/tidb/store/mockstore/unistore/tikv/mvcc.go:1705 +0x2d9
created by github.com/pingcap/tidb/store/mockstore/unistore/tikv.NewMVCCStore
	/go/tidb/store/mockstore/unistore/tikv/mvcc.go:86 +0x6ef 
```

**Comment by tiancaiamao** [comment]
```
make ut
```

is stable enough now.

@Defined2014 take a lot effort on it recently.
