### ISSUE TITLE
Can not use `caching_sha2_password` login

### ISSUE THREAD

**Issue by Icemap** [pingcap/tidb#35400]
## Bug Report

I used `CREATE USER 'username' IDENTIFIED WITH  caching_sha2_password` statement to create a user. 
MySQL can use this user login, but TiDB would not.

### 1. Minimal reproduce step (Required)

1. Install TiDB
2. Install MySQL (and load `caching_sha2_password` AuthPlugin)
3. Clone this [code](https://github.com/Icemap/tidb-java-gitpod/tree/sha2-password)
4. Point [JDBC URL](https://github.com/Icemap/tidb-java-gitpod/blob/sha2-password/src/main/java/com/pingcap/App.java#L17-L18) to TiDB host
5. Run `mvn clean package && java -jar target/tidb-java-gitpod-0.0.1-jar-with-dependencies.jar`
6. Point `JDBC URL` to MySQL host
7. Run `mvn clean package && java -jar target/tidb-java-gitpod-0.0.1-jar-with-dependencies.jar`
8. TiDB can not login by `caching_sha2_password` user

### 2. What did you expect to see? (Required)

Java code gets the connection and output result of `SELECT CURRENT_USER()` when linked MySQL: 

```
1. create user with caching_sha2_password by no password
sha2user@%
2. create user with caching_sha2_password by password exists
sha2user@%
```

### 3. What did you see instead (Required)

Java code can not get the connection and print error stack when linked TiDB: 

```
1. create user with caching_sha2_password by no password
java.sql.SQLException: Access denied for user 'sha2user'@'127.0.0.1' (using password: YES)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
        at com.pingcap.App.testCachingSHA2Password(App.java:52)
        at com.pingcap.App.main(App.java:23)
2. create user with caching_sha2_password by password exists
java.sql.SQLException: Access denied for user 'sha2user'@'127.0.0.1' (using password: YES)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
        at com.pingcap.App.testCachingSHA2Password(App.java:52)
        at com.pingcap.App.main(App.java:25)
```

### 4. What is your TiDB version? (Required)

```sql
+-----------------------------------------+
| version()                               |
+-----------------------------------------+
| 5.7.25-TiDB-v6.2.0-alpha-101-gb91bdd087 |
+-----------------------------------------+
```

**Comment by jebter** [comment]
@leobeijing2000 @lastincisor PTAL

**Comment by lastincisor** [comment]
在mysql中使用 caching_sha2_password 创建用户及登陆，可以正常使用
`CREATE USER 'song1'@'%' IDENTIFIED WITH caching_sha2_password BY '123456';`
用户创建正常，使用mysql cli登陆正常。
` mysql -usong1 -p`


再tidb中使用 caching_sha2_password 创建用户及登陆
`CREATE USER 'song1'@'%' IDENTIFIED WITH caching_sha2_password BY '123456';`
创建用户正常
使用mysql cli登陆 
`mysql -usong1 -hxxx.xxx.xxx.xxx -Pxxxx -p`
登陆过程报如下错误
`ERROR 2061 (HY000): Authentication plugin 'caching_sha2_password' reported error: Authentication requires secure connection.`
过程中没有涉及到JDBC的方式，账号也存在问题

**Comment by bb7133** [comment]
> error info
> ERROR 2061 (HY000): Authentication plugin 'caching_sha2_password' reported error: Authentication requires secure >connection.

@lastincisor @Icemap 
Did you have the 'SSL' enabled for TiDB? According to the [manual](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html), the connection should be encrypted for `caching_sha2_password` authentication, you could verify it by using:

```
select @@have_ssl;
```

**Comment by dveeden** [comment]
Note that MySQL does caching. So after the connection succeeds once over a secure connection subsequent connections can be established over insecure connections. The cache is only in memory so after a MySQL restart it will require a secure connection again. TiDB currently always requires a secure connection.

**Comment by dveeden** [comment]
> Note that MySQL does caching. So after the connection succeeds once over a secure connection subsequent connections can be established over insecure connections. The cache is only in memory so after a MySQL restart it will require a secure connection again. TiDB currently always requires a secure connection.
> 
> I think we could:
> 
>     1. Close this as not-a-bug.
> 
>     2. Change this to a feature request for the caching part of `caching_sha2_password`.

With https://github.com/pingcap/tidb/issues/56747 I think we should go for option 1.

**Comment by Icemap** [comment]
Got it. Thanks for helping.
