### ISSUE TITLE
goleak in the sessiontxn/isolation

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#36212]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[2022-07-14T07:03:55.154Z] coverage: 14.7% of statements
[2022-07-14T07:03:55.154Z] goleak: Errors on successful test run: found unexpected goroutines:
[2022-07-14T07:03:55.154Z] [Goroutine 2508 in state select, 1 minutes, with github.com/pingcap/tidb/store/copr.(*copIteratorWorker).sendToRespCh on top of the stack:
[2022-07-14T07:03:55.154Z] goroutine 2508 [select, 1 minutes]:
[2022-07-14T07:03:55.154Z] github.com/pingcap/tidb/store/copr.(*copIteratorWorker).sendToRespCh(0xc0027209b0?, 0x45aaf38?, 0xc008c485a0?, 0x14?)
[2022-07-14T07:03:55.154Z] 	store/copr/coprocessor.go:542 +0x1b5
[2022-07-14T07:03:55.154Z] github.com/pingcap/tidb/store/copr.(*copIteratorWorker).run(0xc0027209b0, {0x45aaf38, 0xc008c485a0})
[2022-07-14T07:03:55.154Z] 	store/copr/coprocessor.go:409 +0x12d
[2022-07-14T07:03:55.154Z] created by github.com/pingcap/tidb/store/copr.(*copIterator).open
[2022-07-14T07:03:55.154Z] 	store/copr/coprocessor.go:437 +0x9f
[2022-07-14T07:03:55.154Z] 
[2022-07-14T07:03:55.154Z]  Goroutine 2509 in state semacquire, 1 minutes, with sync.runtime_Semacquire on top of the stack:
[2022-07-14T07:03:55.154Z] goroutine 2509 [semacquire, 1 minutes]:
[2022-07-14T07:03:55.154Z] sync.runtime_Semacquire(0xc000735750?)
[2022-07-14T07:03:55.154Z] 	GOROOT/src/runtime/sema.go:56 +0x25
[2022-07-14T07:03:55.154Z] sync.(*WaitGroup).Wait(0xc003550d20?)
[2022-07-14T07:03:55.154Z] 	GOROOT/src/sync/waitgroup.go:136 +0x52
[2022-07-14T07:03:55.154Z] github.com/pingcap/tidb/store/copr.(*copIteratorTaskSender).run(0xc002d1b0c0)
[2022-07-14T07:03:55.154Z] 	store/copr/coprocessor.go:477 +0xec
[2022-07-14T07:03:55.154Z] created by github.com/pingcap/tidb/store/copr.(*copIterator).open
[2022-07-14T07:03:55.154Z] 	store/copr/coprocessor.go:454 +0x4ce
[2022-07-14T07:03:55.154Z] ]
[2022-07-14T07:03:55.154Z] --
[2022-07-14T07:03:55.154Z] Coverage runner: Not collecting coverage for failed test.
[2022-07-14T07:03:55.154Z] The following commands failed with status 1
[2022-07-14T07:03:55.154Z] /home/jenkins/.tidb/tmp/b7c8fa3cc70b7c7023fdc4f79d50df0e/sandbox/processwrapper-sandbox/4323/execroot/__main__/bazel-out/k8-fastbuild/bin/sessiontxn/isolation/isolation_test_/isolation_test.runfiles/__main__/sessiontxn/isolation/isolation_test_/isolation_test
```

**Comment by hawkingrei** [comment]
https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tidb_ghpr_unit_test/runs/59245/nodes/59/steps/64/log/?start=0
