### ISSUE TITLE
unsupported flag 128 with Connector/Python and prepared statements

### ISSUE THREAD

**Issue by dveeden** [pingcap/tidb#36731]
### 1. Minimal reproduce step (Required)

```python3
#!/bin/python3
import argparse
import mysql.connector

parser = argparse.ArgumentParser()
parser.add_argument('--host', type=str, default='127.0.0.1')
parser.add_argument('--port', type=int, default=4000)
parser.add_argument('--user', type=str, default='root')
parser.add_argument('--password', type=str, default='')
args = parser.parse_args()
c = mysql.connector.connect(host=args.host, port=args.port, user=args.user, password=args.password)
cur = c.cursor(prepared=True)
cur.execute('DO ?', (1, ))
cur.close()
c.close()
print('OK')
```

### 2. What did you expect to see? (Required)

With MySQL 8.0.30:
```
$ ./prepared.py --port 8030 --user test --password test
OK
```

### 3. What did you see instead (Required)

With TiDB:
```
$ ./prepared.py
Traceback (most recent call last):
  File "/tmp/./prepared.py", line 13, in <module>
    cur.execute('DO ?', (1, ))
  File "/usr/lib/python3.11/site-packages/mysql/connector/cursor.py", line 1213, in execute
    res = self._connection.cmd_stmt_execute(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mysql/connector/connection.py", line 1100, in cmd_stmt_execute
    result = self._handle_binary_result(packet)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mysql/connector/connection.py", line 1025, in _handle_binary_result
    raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1105 (HY000): ERROR 1105 (HY000): unsupported flag 128
```

And in the logs:
```
[2022/07/29 16:03:44.416 +02:00] [INFO] [conn.go:1170] ["command dispatched failed"] [conn=2199023255961] [connInfo="id:2199023255961, addr:127.0.0.1:34430 status:0, collation:utf8mb4_general_ci, user:root"] [command=Execute] [status="inTxn:0, autocommit:0"] [sql="DO ?"] [txn_mode=PESSIMISTIC] [timestamp=0] [err="ERROR 1105 (HY000): unsupported flag 128"]
```

### 4. What is your TiDB version? (Required)

```
sql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.2.0-alpha-560-ge5c900c8c
Edition: Community
Git Commit Hash: e5c900c8cd4cea6da2af02768c28cad10a8b1d13
Git Branch: master
UTC Build Time: 2022-07-29 13:51:19
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
1 row in set (0.0001 sec)
```

**Comment by dveeden** [comment]
This is coming from this code:
https://github.com/pingcap/tidb/blob/e5c900c8cd4cea6da2af02768c28cad10a8b1d13/server/conn_stmt.go#L154

**Comment by dveeden** [comment]
https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_stmt_execute.html says this:
"the type as in [enum_field_types](https://dev.mysql.com/doc/dev/mysql-server/latest/field__types_8h.html#a69e798807026a0f7e12b1d6c72374854)
    a flag byte which has the highest bit set if the type is unsigned [80]"

Note that 0x80 (hex) == 128 (decimal) == 10000000 (binary) so this has the unsigned bit set, but none of the flags.

**Comment by dveeden** [comment]
This results in flag value of 0x80:
```python3
cur.execute('DO ?', (1, ))
```

This results in a flag value of 0x0:
```python3
cur.execute('DO ?', ("1", ))
```
