### ISSUE TITLE
BenchmarkCompileExecutePreparedStmt break by pr/36781

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#36959]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
make bench-daily TO=/tmp/2022-08-08.json
```

### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)

```
[2022/08/08 11:35:53.365 +08:00] [WARN] [sysvar_cache.go:53] ["sysvar cache is empty, triggering rebuild"]
panic: interface conversion: interface {} is []types.Datum, not []expression.Expression

goroutine 1013494 [running]:
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildExecute(0xc002f15388?, {0x4445d48, 0xc0000560f0}, 0xc004c861b0)
	/home/genius/project/src/github.com/pingcap/tidb/planner/core/planbuilder.go:807 +0x186
github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build(0xc00187c1a0, {0x4445d48, 0xc0000560f0}, {0x4454830?, 0xc004c861b0?})
	/home/genius/project/src/github.com/pingcap/tidb/planner/core/planbuilder.go:716 +0x9f0
github.com/pingcap/tidb/planner.optimize({0x4445d48, 0xc0000560f0}, {0x449ea78, 0xc002e51b00}, {0x4454830, 0xc004c861b0?}, {0x446b378, 0xc002564a80})
	/home/genius/project/src/github.com/pingcap/tidb/planner/optimize.go:326 +0x4ed
github.com/pingcap/tidb/planner.Optimize({0x4445d48, 0xc0000560f0}, {0x449ea78, 0xc002e51b00}, {0x4454830, 0xc004c861b0}, {0x446b378, 0xc002564a80})
	/home/genius/project/src/github.com/pingcap/tidb/planner/optimize.go:199 +0xcb7
github.com/pingcap/tidb/executor.CompileExecutePreparedStmt({0x4445d48?, 0xc0000560f0}, {0x449ea78?, 0xc002e51b00}, 0xc004c861b0, {0x446b378?, 0xc002564a80})
	/home/genius/project/src/github.com/pingcap/tidb/executor/prepared.go:327 +0x150
github.com/pingcap/tidb/session.BenchmarkCompileExecutePreparedStmt(0xc0024af680)
	/home/genius/project/src/github.com/pingcap/tidb/session/bench_test.go:1819 +0x34f
testing.(*B).runN(0xc0024af680, 0x1)
	/home/genius/project/go/src/testing/benchmark.go:193 +0x102
testing.(*B).run1.func1()
	/home/genius/project/go/src/testing/benchmark.go:233 +0x59
created by testing.(*B).run1
	/home/genius/project/go/src/testing/benchmark.go:226 +0x9c
exit status 2
FAIL	github.com/pingcap/tidb/session	162.902s
FAIL
make: *** [Makefile:250: bench-daily] Error 1
```
### 4. What is your TiDB version? (Required)

master 77cb60ef280ece994ef598ef548f79c2c16ca71d

**Comment by tiancaiamao** [comment]
Ref https://github.com/pingcap/tidb/issues/25754
