### ISSUE TITLE
currency access to the  information_shcema.table raise fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#37603]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

there are some dbs and tables
currency execute `select TABLE_NAME from information_schema.TABLES where TABLE_SCHEMA='%s'`
### 2. What did you expect to see? (Required)
successfully
### 3. What did you see instead (Required)
there is no rlock protect the map https://github.com/pingcap/tidb/blob/331707cfdc83d6bf856c675294a29718728b80c4/executor/infoschema_reader.go#L306-L307 , for example https://github.com/pingcap/tidb/blob/331707cfdc83d6bf856c675294a29718728b80c4/executor/infoschema_reader.go#L665-L666
tidb down and the log is
```
fatal error: concurrent map read and map write

goroutine 127816163 [running]:
runtime.throw({0x3fac2c5?, 0xc006530bb0?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00196d568 sp=0xc00196d538 pc=0x152b551
runtime.mapaccess1_fast64(0x0?, 0x0?, 0x4000000000005009)
	/usr/local/go/src/runtime/map_fast64.go:22 +0x172 fp=0xc00196d588 sp=0xc00196d568 pc=0x15034b2
github.com/pingcap/tidb/executor.(*memtableRetriever).setDataFromTables(0xc06b305500, {0x4540f10?, 0xc03258b7d0?}, {0x459b0d8, 0xc01f951d40?}, {0xc011aec500, 0xf, 0x4091ac8?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:662 +0x909 fp=0xc00196d9a0 sp=0xc00196d588 pc=0x3563089
github.com/pingcap/tidb/executor.(*memtableRetriever).retrieve(0xc06b305500, {0x4540f10, 0xc03258b7d0}, {0x459b0d8, 0xc01f951d40})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:111 +0x265 fp=0xc00196da78 sp=0xc00196d9a0 pc=0x355d9c5
github.com/pingcap/tidb/executor.(*MemTableReaderExec).Next(0xc001bf3050, {0x4540f10, 0xc03258b7d0}, 0xc0282d3450)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/memtable_reader.go:118 +0x29b fp=0xc00196dbe0 sp=0xc00196da78 pc=0x35c0d3b
github.com/pingcap/tidb/executor.Next({0x4540f10, 0xc03258b7d0}, {0x4544520, 0xc001bf3050}, 0xc0282d3450)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:323 +0x4f2 fp=0xc00196dd20 sp=0xc00196dbe0 pc=0x35293f2
github.com/pingcap/tidb/executor.(*SelectionExec).Next(0xc00507ac30, {0x4540f10, 0xc03258b7d0}, 0xc0282d38b0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:1559 +0xf9 fp=0xc00196ddb0 sp=0xc00196dd20 pc=0x3531779
github.com/pingcap/tidb/executor.Next({0x4540f10, 0xc03258b7d0}, {0x45449a0, 0xc00507ac30}, 0xc0282d38b0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:323 +0x4f2 fp=0xc00196def0 sp=0xc00196ddb0 pc=0x35293f2
github.com/pingcap/tidb/executor.(*projectionInputFetcher).run(0xc02f415ca0, {0x4540f10, 0xc03258b7d0})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/projection.go:381 +0x20c fp=0xc00196dfb8 sp=0xc00196def0 pc=0x35e59ac
github.com/pingcap/tidb/executor.(*ProjectionExec).prepare.func1()
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/projection.go:270 +0x2e fp=0xc00196dfe0 sp=0xc00196dfb8 pc=0x35e52ee
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00196dfe8 sp=0xc00196dfe0 pc=0x1560441
created by github.com/pingcap/tidb/executor.(*ProjectionExec).prepare
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/projection.go:270 +0x67e

goroutine 1 [chan receive, 200 minutes]:
github.com/pingcap/tidb/server.(*Server).Run(0xc002487500)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:371 +0x1f0
main.main()
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:224 +0x3a5
```
### 4. What is your TiDB version? (Required)

master

**Comment by hawkingrei** [comment]
Have you a way to reproduce this problem.
