### ISSUE TITLE
Lightning: restore data will panic if tidb's Release Version is none

### ISSUE THREAD

**Issue by River2000i** [pingcap/tidb#37905]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
[ec2-user@ip-192-168-54-107 ~]$ .tiup/bin/tiup tidb-lightning -config tidb-lightning.toml
tiup is checking updates for component tidb-lightning ...
Starting component `tidb-lightning`: /home/ec2-user/.tiup/components/tidb-lightning/v6.2.0/tidb-lightning -config tidb-lightning.toml
Verbose debug logs will be written to tidb-lightning.log

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x34f9bee]

goroutine 1 [running]:
[github.com/pingcap/tidb/br/pkg/lightning/backend/tidb.(*targetInfoGetter).FetchRemoteTableModels.func1](http://github.com/pingcap/tidb/br/pkg/lightning/backend/tidb.(*targetInfoGetter).FetchRemoteTableModels.func1)({0x30?, 0x4699fc8?}, 0xc000156e80?)
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/lightning/backend/tidb/tidb.go:204](http://github.com/pingcap/br/br/pkg/lightning/backend/tidb/tidb.go:204) +0x80e
[github.com/pingcap/tidb/br/pkg/lightning/common.SQLWithRetry.Transact.func1()](http://github.com/pingcap/tidb/br/pkg/lightning/common.SQLWithRetry.Transact.func1())
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/lightning/common/util.go:205](http://github.com/pingcap/br/br/pkg/lightning/common/util.go:205) +0x94
[github.com/pingcap/tidb/br/pkg/lightning/common.Retry](http://github.com/pingcap/tidb/br/pkg/lightning/common.Retry)({0x40c0150, 0x13}, {0xc000a3edc8?}, 0xc000a3ec20)
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/lightning/common/util.go:167](http://github.com/pingcap/br/br/pkg/lightning/common/util.go:167) +0x1ff
[github.com/pingcap/tidb/br/pkg/lightning/common.SQLWithRetry.perform(...)](http://github.com/pingcap/tidb/br/pkg/lightning/common.SQLWithRetry.perform(...))
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/lightning/common/util.go:152](http://github.com/pingcap/br/br/pkg/lightning/common/util.go:152)
[github.com/pingcap/tidb/br/pkg/lightning/common.SQLWithRetry.Transact](http://github.com/pingcap/tidb/br/pkg/lightning/common.SQLWithRetry.Transact)({{0x469a188?, 0xc000ab3040?}, {0xc00056af60?}, 0x0?}, {0x4699fc8?, 0xc000156e80?}, {0x40c0150?, 0xc00055cf90?}, 0x0?)
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/lightning/common/util.go:199](http://github.com/pingcap/br/br/pkg/lightning/common/util.go:199) +0xbb
[github.com/pingcap/tidb/br/pkg/lightning/backend/tidb.(*targetInfoGetter).FetchRemoteTableModels](http://github.com/pingcap/tidb/br/pkg/lightning/backend/tidb.(*targetInfoGetter).FetchRemoteTableModels)(0xc0001345e0, {0x4699fc8, 0xc000156e80}, {0xc0008b4500, 0x6})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/lightning/backend/tidb/tidb.go:140](http://github.com/pingcap/br/br/pkg/lightning/backend/tidb/tidb.go:140) +0x145
[github.com/pingcap/tidb/br/pkg/lightning/backend/tidb.(*tidbBackend).FetchRemoteTableModels](http://github.com/pingcap/tidb/br/pkg/lightning/backend/tidb.(*tidbBackend).FetchRemoteTableModels)(0x15476f1?, {0x4699fc8?, 0xc000156e80?}, {0xc0008b4500?, 0xc0000021a0?})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/lightning/backend/tidb/tidb.go:739](http://github.com/pingcap/br/br/pkg/lightning/backend/tidb/tidb.go:739) +0x31
[github.com/pingcap/tidb/br/pkg/lightning/backend.Backend.FetchRemoteTableModels(...)](http://github.com/pingcap/tidb/br/pkg/lightning/backend.Backend.FetchRemoteTableModels(...))
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/lightning/backend/backend.go:282](http://github.com/pingcap/br/br/pkg/lightning/backend/backend.go:282)
[github.com/pingcap/tidb/br/pkg/lightning/restore.(*TargetInfoGetterImpl).FetchRemoteTableModels](http://github.com/pingcap/tidb/br/pkg/lightning/restore.(*TargetInfoGetterImpl).FetchRemoteTableModels)(0xc000159f50, {0x4699fc8, 0xc000156e80}, {0xc0008b4500, 0x6})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/lightning/restore/get_pre_info.go:167](http://github.com/pingcap/br/br/pkg/lightning/restore/get_pre_info.go:167) +0x6d
[github.com/pingcap/tidb/br/pkg/lightning/restore.(*PreRestoreInfoGetterImpl).FetchRemoteTableModels](http://github.com/pingcap/tidb/br/pkg/lightning/restore.(*PreRestoreInfoGetterImpl).FetchRemoteTableModels)(0x0?, {0x4699fc8?, 0xc000156e80?}, {0xc0008b4500?, 0xc000a3ee00?})
	/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/lightning/restore/get_pre_info.go:782](http://github.com/pingcap/br/br/pkg/lightning/restore/get_pre_info.go:782) +0x31
[github.com/pingcap/tidb/br/pkg/lightning/restore.(*restoreSchemaWorker).makeJobs](http://github.com/pingcap/tidb/br/pkg/lightning/restore.(*restoreSchemaWorker).makeJobs)(0xc0000a5f80, {0xc00055cd30, 0x2, 0x12?}, 0xc000a3f0d8)
[2022/09/16 10:26:43.482 +00:00] [WARN] [config.go:797] ["currently only per-task configuration can be applied, global configuration changes can only be made on startup"] ["global config changes"="[lightning.level,lightning.file]"]


[2022/09/16 10:32:56.451 +00:00] [INFO] [lightning.go:472] ["load data source start"]
[2022/09/16 10:32:56.451 +00:00] [INFO] [lightning.go:475] ["load data source completed"] [takeTime=207.35µs] []
[2022/09/16 10:32:56.451 +00:00] [INFO] [checkpoints.go:998] ["open checkpoint file failed, going to create a new one"] [path=/tmp/tidb_lightning_checkpoint.pb] []
[2022/09/16 10:32:56.451 +00:00] [INFO] [restore.go:438] ["the whole procedure start"]
[2022/09/16 10:32:56.451 +00:00] [INFO] [restore.go:722] ["restore all schema start"]
[2022/09/16 10:32:57.013 +00:00] [WARN] [version.go:390] ["fail to parse version"] [version=]
[2022/09/16 10:32:57.013 +00:00] [INFO] [version.go:397] ["detect server version"] [type=TiDB] [version=]
```

**Release Version is none:
[2022/09/16 10:32:57.013 +00:00] [INFO] [version.go:397] ["detect server version"] [type=TiDB] [version=]**

### 2. What did you expect to see? (Required)
lighting should not panic, but log warning

### 3. What did you see instead (Required)
lighting should not panic

### 4. What is your TiDB version? (Required)

Release Version: none
Edition: Community
Git Commit Hash: 1d1128338412e9755f78c859a379ad0b0de9830d
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time: 2022-09-15 11:10:26
GoVersion: go1.19
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by niubell** [comment]
It was fixed in this pr [#37090](https://github.com/pingcap/tidb/pull/37090) and will be released in v6.3.0, you can use release-6.3/master to check it.
