### ISSUE TITLE
 invalid memory address or nil pointer dereference in the TestCollectDMLRuntimeStats

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#37902]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2e81196]
goroutine 3911502 [running]:
testing.tRunner.func1.2({0x63959e0, 0x9d609e0})
	GOROOT/src/testing/testing.go:1396 +0x372
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1399 +0x5f0
panic({0x63959e0, 0x9d609e0})
	GOROOT/src/runtime/panic.go:890 +0x262
github.com/pingcap/tidb/util/execdetails.(*RuntimeStatsColl).GetRootStats(0x0, 0xc002c5b860?)
	util/execdetails/execdetails.go:695 +0x56
github.com/pingcap/tidb/executor_test.TestCollectDMLRuntimeStats.func1()
	executor/executor_test.go:4032 +0x188
github.com/pingcap/tidb/executor_test.TestCollectDMLRuntimeStats(0xc002c5b860)
	executor/executor_test.go:4037 +0x272
testing.tRunner(0xc002c5b860, 0x6a94850)
	GOROOT/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:1493 +0x75e 
```

**Comment by jebter** [comment]
Please try the latest version. I will close it,if there are any updates, you can reopen it.
