### ISSUE TITLE
make bench-daily broken after pr/37908

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#37957]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

```
make benchdaily TO='/tmp/2022-09-19.json'
```

or 

```
go test github.com/pingcap/tidb/distsql -run TestBenchDaily -bench Ignore --outfile bench_daily.json
```

Success, no error

### 3. What did you see instead (Required)

```
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 67 in state select, with go.opencensus.io/stats/view.(*worker).start on top of the stack:
goroutine 67 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0005fcf00)
	/home/genius/go/pkg/mod/go.opencensus.io@v0.23.1-0.20220331163232-052120675fac/stats/view/worker.go:292 +0xad
created by go.opencensus.io/stats/view.init.0
	/home/genius/go/pkg/mod/go.opencensus.io@v0.23.1-0.20220331163232-052120675fac/stats/view/worker.go:34 +0x8d
]
exit status 1
FAIL	github.com/pingcap/tidb/distsql	3.225s
FAIL
```

### 4. What is your TiDB version? (Required)

master b5ed6740df266b909fcae78df782fce41bd29808

**Comment by tiancaiamao** [comment]
Introduced after https://github.com/pingcap/tidb/pull/37908

**Comment by MimeLyc** [comment]
refresh

**Comment by MimeLyc** [comment]
refresh

**Comment by MimeLyc** [comment]
refresh
