### ISSUE TITLE
Crash in (*Buffer).AllocBytes

### ISSUE THREAD

**Issue by secsys-go** [pingcap/tidb#39020]
## Bug Report

We used the Fuzz engine to modify some Test(TestBufferIsolation) data, and then the following crash appeared. We hope to get the help of the developer to confirm whether it is a real bug.

### 1. Minimal reproduce step (Required)

Simplified Test Code

```go
	var1 := 3512579220296446143  //transstruct.GetInt(1024)
	var2 := -4670179215877816528 //transstruct.GetInt(16)

	pool := NewPool(WithBlockSize(var1))
	defer pool.Destroy()
	bytesBuf := pool.NewBuffer()
	defer bytesBuf.Destroy()

	b1 := bytesBuf.AllocBytes(var2)
```

### 2. What did you expect to see? (Required)

Test Passed

### 3. What did you see instead (Required)

Crash Log

```go
panic: runtime error: slice bounds out of range [::-4670179215877816528] [recovered]
	panic: runtime error: slice bounds out of range [::-4670179215877816528]

goroutine 6 [running]:
testing.tRunner.func1.2({0x5d8ec0, 0xc00001a330})
	/home/gogen/.local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/home/gogen/.local/go/src/testing/testing.go:1212 +0x218
panic({0x5d8ec0, 0xc00001a330})
	/home/gogen/.local/go/src/runtime/panic.go:1038 +0x215
github.com/pingcap/tidb/br/pkg/membuf.(*Buffer).AllocBytes(0xc0000e5eb0, 0xbf3030bf3030bf30)
	/home/gogen/workspace/gowork/src/topproj/tidb/br/pkg/membuf/buffer.go:184 +0xbc
github.com/pingcap/tidb/br/pkg/membuf.FuzzTestBufferIsolation({0xc00017e000, 0x3, 0x200})
	/home/gogen/workspace/gowork/src/topproj/tidb/br/pkg/membuf/buffer_test.go_TestBufferIsolation_test.go:35 +0x1ef
```

### 4. What is your TiDB version? (Required)

commit 9c4f94dd70010806710153d27fd5b734f99c4cb1 (HEAD)

**Comment by lichunzhu** [comment]
Will never happen. Functions that use `AllocBytes` will always use a non-negetive value.
