### ISSUE TITLE
Crash in (*tidbEncoder).Encode

### ISSUE THREAD

**Issue by secsys-go** [pingcap/tidb#39022]
## Bug Report

We used the Fuzz engine to modify some Test(TestEncodeRowForRecord) data, and then the following crash appeared. We hope to get the help of the developer to confirm whether it is a real bug.

### 1. Minimal reproduce step (Required)

Simplified Test Code

```go
	s := createMysqlSuite(t)
	row := tidb.EncodeRowForRecord(s.tbl, mysql.ModeStrictTransTables, []types.Datum{
		types.NewIntDatum(5),
		types.NewStringDatum("test test"),
		types.NewBinaryLiteralDatum(types.NewBinaryLiteralFromUint(0xabcdef, 6)),
	}, []int{1407374883553283, -1, -1, -1, -1, -1, -1, -1, 1, 2, -1, -1, -1, -1})
```

### 2. What did you expect to see? (Required)

Test Passed

### 3. What did you see instead (Required)

Crash Log

```go
panic: runtime error: index out of range [1407374883553283] with length 14 [recovered]
	panic: runtime error: index out of range [1407374883553283] with length 14

goroutine 187 [running]:
testing.tRunner.func1.2({0x1e4cd20, 0xc0000575f0})
	/home/gogen/.local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/home/gogen/.local/go/src/testing/testing.go:1212 +0x218
panic({0x1e4cd20, 0xc0000575f0})
	/home/gogen/.local/go/src/runtime/panic.go:1038 +0x215
github.com/pingcap/tidb/br/pkg/lightning/backend/tidb.(*tidbEncoder).Encode(0xc000b90ca8, {0x20}, {0xc000491dc0, 0x40f9b4, 0x3}, 0xe0, {0xc0000625b0, 0x7f4b7d604108, 0xe}, {0x0, ...}, ...)
	/home/gogen/workspace/gowork/src/topproj/tidb/br/pkg/lightning/backend/tidb/tidb.go:297 +0xd53
github.com/pingcap/tidb/br/pkg/lightning/backend/tidb.EncodeRowForRecord({0x23b5d20, 0xc0001dfd40}, 0x9, {0xc000491dc0, 0x3, 0x3}, {0xc0000625b0, 0xc000b71560, 0x46731d})
	/home/gogen/workspace/gowork/src/topproj/tidb/br/pkg/lightning/backend/tidb/tidb.go:352 +0xd8
github.com/pingcap/tidb/br/pkg/lightning/backend/tidb_test.FuzzTestEncodeRowForRecord({0xc000408e00, 0x68, 0x200})
	/home/gogen/workspace/gowork/src/topproj/tidb/br/pkg/lightning/backend/tidb/tidb_test.go_TestEncodeRowForRecord_test.go:40 +0x3dc
```

### 4. What is your TiDB version? (Required)

9c4f94dd70010806710153d27fd5b734f99c4cb1

**Comment by lichunzhu** [comment]
I think we don't need to fix this problem. For TiDB-Lightning generated columnPermunations will always be less than columns length.
