### ISSUE TITLE
Crash in (*Batcher).drainRanges

### ISSUE THREAD

**Issue by secsys-go** [pingcap/tidb#39033]
## Bug Report

We used the Fuzz engine to modify some Test(TestBatcherLen) data, and then the following crash appeared. We hope to get the help of the developer to confirm whether it is a real bug.

### 1. Minimal reproduce step (Required)

Simplified Test Code

```go
	ctx := context.Background()
	errCh := make(chan error, 8)
	sender := newDrySender()
	manager := newMockManager()
	batcher, _ := restore.NewBatcher(ctx, sender, manager, errCh)
	batcher.SetThreshold(-12094627905548)

	simpleTable := fakeTableWithRange(1, []rtree.Range{
		fakeRange("caa", "cab"), fakeRange("cac", "cad"),
		fakeRange("cae", "caf"), fakeRange("cag", "cai"),
		fakeRange("caj", "cak"), fakeRange("cal", "cam"),
		fakeRange("can", "cao"), fakeRange("cap", "caq"),
	})

	simpleTable2 := fakeTableWithRange(2, []rtree.Range{
		fakeRange("caa", "cab"), fakeRange("cac", "cad"),
		fakeRange("cae", "caf"), fakeRange("cag", "cai"),
		fakeRange("caj", "cak"), fakeRange("cal", "cam"),
		fakeRange("can", "cao"), fakeRange("cap", "caq"),
	})

	batcher.Add(simpleTable)
	waitForSend()
```

### 2. What did you expect to see? (Required)

Test Passed

### 3. What did you see instead (Required)

Crash Log

```go
panic: runtime error: slice bounds out of range [:-12094627905548]

goroutine 524 [running]:
github.com/pingcap/tidb/br/pkg/restore.(*Batcher).drainRanges(0xc005b0fb80)
	/home/gogen/workspace/gowork/src/topproj/tidb/br/pkg/restore/batcher.go:282 +0x101a
github.com/pingcap/tidb/br/pkg/restore.(*Batcher).Send(0xc005b0fb80, {0x3ff1120, 0xc0001bc000})
	/home/gogen/workspace/gowork/src/topproj/tidb/br/pkg/restore/batcher.go:322 +0x1f8
github.com/pingcap/tidb/br/pkg/restore.(*Batcher).sendWorker.func1(...)
	/home/gogen/workspace/gowork/src/topproj/tidb/br/pkg/restore/batcher.go:169
github.com/pingcap/tidb/br/pkg/restore.(*Batcher).sendWorker(0xc005b0fb80, {0x3ff1120, 0xc0001bc000}, 0x3ba8df0)
	/home/gogen/workspace/gowork/src/topproj/tidb/br/pkg/restore/batcher.go:176 +0x10e
created by github.com/pingcap/tidb/br/pkg/restore.NewBatcher
	/home/gogen/workspace/gowork/src/topproj/tidb/br/pkg/restore/batcher.go:120 +0x26f
```

### 4. What is your TiDB version? (Required)

9c4f94dd70010806710153d27fd5b734f99c4cb1

**Comment by 3pointer** [comment]
I don't think this is an issue.
batchSize must be positive since we have a check
`batchSize := mathutil.Clamp(int(cfg.Concurrency), defaultRestoreConcurrency, maxRestoreBatchSizeLimit)`. 
so -12094627905548 won't happen.
