### ISSUE TITLE
tidb: `fatal error: concurrent map read and map write`

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#39076]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. run ch workload
2. run cc workload

### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
```
fatal error: concurrent map read and map write
goroutine 2775 [running]:
github.com/pingcap/tidb/util/execdetails.(*RuntimeStatsColl).GetOrCreateCopStats(0xc002381ed8, 0x7000102?, {0x46f4b07, 0x4})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/execdetails/execdetails.go:720 +0xbd
github.com/pingcap/tidb/util/execdetails.(*RuntimeStatsColl).RecordScanDetail(0xc0023ac060?, 0xc013b38510?, {0x46f4b07?, 0x16e7b87?}, 0xc013b32660)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/execdetails/execdetails.go:756 +0x27
github.com/pingcap/tidb/distsql.(*selectResult).updateCopRuntimeStats(0xc0001491d0, {0x4e4aab0, 0xc0061edf20}, 0xc013b38510, 0xc01198a5e8?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/distsql/select_result.go:373 +0x3a8
github.com/pingcap/tidb/distsql.(*selectResult).fetchResp(0xc0001491d0, {0x4e4aab0, 0xc0061edf20})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/distsql/select_result.go:241 +0x391
github.com/pingcap/tidb/distsql.(*selectResult).Next(0xc0001491d0, {0x4e4aab0, 0xc0061edf20}, 0xc0062629b0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/distsql/select_result.go:256 +0x86
github.com/pingcap/tidb/executor.(*tableResultHandler).nextChunk(0x4e4aab0?, {0x4e4aab0?, 0xc0061edf20?}, 0x1f?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/table_reader.go:509 +0xa2
github.com/pingcap/tidb/executor.(*TableReaderExecutor).Next(0xc00622e340, {0x4e4aab0, 0xc0061edf20}, 0xc0062629b0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/table_reader.go:254 +0x1c8
github.com/pingcap/tidb/executor.Next({0x4e4aab0, 0xc0061edf20}, {0x4e4fc20, 0xc00622e340}, 0xc0062629b0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:325 +0x4f3
github.com/pingcap/tidb/executor.(*projectionInputFetcher).run(0xc00622ce00, {0x4e4aab0, 0xc0061edf20})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/projection.go:384 +0x2f7
created by github.com/pingcap/tidb/executor.(*ProjectionExec).prepare
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/projection.go:273 +0x69e
```
[tidb3err-1111.log](https://github.com/pingcap/tidb/files/9984937/tidb3err-1111.log)

### 4. What is your TiDB version? (Required)
6.4.0

**Comment by crazycs520** [comment]
Could you provide the TiDB git hash, since the stack information doesn't match v6.4.0

**Comment by AkiraXie** [comment]
@crazycs520 hash: 00b99ec17ec4345db07849327cc16295e75235e4

**Comment by crazycs520** [comment]
I can't find out the reason of `concurrent map read and map write` from the stack. I'm not sure if the logs are incomplete, I will wait for the next reproduce.
