### ISSUE TITLE
tidb-server panic with invalid memory  access

### ISSUE THREAD

**Issue by lddlww** [pingcap/tidb#39096]
## Bug Report

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x228 pc=0x1eb8de9]

goroutine 730568558 [running]:
google.golang.org/grpc.(*ClientConn).GetState(...)
        /nfs/cache/mod/google.golang.org/grpc@v1.29.1/clientconn.go:514
github.com/tikv/client-go/v2/internal/client.(*RPCClient).SendRequest(0xc00015a300, 0x42b48c8, 0xc0007ee900, 0xc0024a7038, 0x12, 0xc028bb8480, 0x6fc23ac00, 0x0, 0x0, 0x0)
        /nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/client/client.go:408 +0x269
github.com/tikv/client-go/v2/internal/client.reqCollapse.SendRequest(0x4291120, 0xc00015a300, 0x42b48c8, 0xc0007ee900, 0xc0024a7038, 0x12, 0xc028bb8480, 0x6fc23ac00, 0x3be61c0, 0xc00ab4ed01, ...)
        /nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/internal/client/client_collapse.go:74 +0x12a
github.com/tikv/client-go/v2/tikv.(*KVStore).updateSafeTS.func1(0x4291148, 0xc000512d00, 0xc000554120, 0x42b48c8, 0xc0007ee900, 0xc0809c23f0, 0x45784f, 0xc0024a7038, 0x12)
        /nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/tikv/kv.go:563 +0x165
created by github.com/tikv/client-go/v2/tikv.(*KVStore).updateSafeTS
        /nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211029104011-2fd3841894de/tikv/kv.go:561 +0x145
config file conf/tidb.toml contained invalid configuration options: experimental.allow-auto-random; check TiDB manual to make sure this option has not been deprecated and removed from your TiDB version if the option does not appear to be a typo
```

### 1. Minimal reproduce step (Required)
i don't know how reproduce 

### 2. What did you expect to see? (Required)
more detail log or something else

### 3. What did you see instead (Required)
panic: invalid memory access

### 4. What is your TiDB version? (Required)
v5.3.0

**Comment by seiya-annie** [comment]
please upload tidb log

**Comment by lddlww** [comment]
[tidb_log.tar.gz](https://github.com/pingcap/tidb/files/10000622/tidb_log.tar.gz)

**Comment by zyguan** [comment]
The issue has been fixed by https://github.com/tikv/client-go/pull/465 , you may need to upgrade tidb to v5.3.4 , which will be released soon.

**Comment by lddlww** [comment]
thanks，i will try upgrade to v5.3.4 sooner
