### ISSUE TITLE
panic in `plan.dagPhysicalOptimize`

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#3926]
## 1. What did you do?

start tidb-server with mocktikv
```
./bin/tidb-server --store=mocktikv --path=""
```

use MySQLWorkBench to execute a query
use `mysql` client connect to `tidb-server`

then a panic happens

## 3. What did you see instead?

```
2017/07/28 10:28:48 conn.go:341: [error] lastCmd tblA, runtime error: invalid memory address or nil pointer dereference, goroutine 5624 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc420da7ce0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:339 +0xcd
panic(0x1c1bd60, 0x2791600)
        /Users/jianzhang.zj/opt/go-1.8.1/src/runtime/panic.go:489 +0x2cf
github.com/pingcap/tidb/plan.dagPhysicalOptimize(0x2497720, 0xc4203fb940, 0xc4203fb901, 0x2484ae0, 0xc420da7ef0, 0xc42027dda0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/optimizer.go:164 +0x10a
github.com/pingcap/tidb/plan.doOptimize(0x43, 0x2497720, 0xc4203fb940, 0x2484ae0, 0xc420da7ef0, 0xc42027dda0, 0x1, 0xc4203a7720, 0xc4200bf7b8, 0x190c601)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/optimizer.go:128 +0xdd
github.com/pingcap/tidb/plan.Optimize(0x2484ae0, 0xc420da7ef0, 0x247b400, 0xc4202d9900, 0x2b33590, 0xc420a8e570, 0x0, 0x0, 0x2a93960, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/optimizer.go:85 +0x27f
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc4200bf8a8, 0x2484ae0, 0xc420da7ef0, 0x2b33a10, 0xc4202d9900, 0x1059ca5, 0x1086c02, 0xc420d02f20, 0xc4203fb340)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/compiler.go:41 +0x1ae
github.com/pingcap/tidb.Compile(0x2484ae0, 0xc420da7ef0, 0x2b33a10, 0xc4202d9900, 0x0, 0x0, 0x0, 0xc4202398a0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/tidb.go:149 +0x57
github.com/pingcap/tidb.(*session).Execute(0xc420da7ef0, 0xc4203a75e0, 0x1c, 0x0, 0x3, 0xc4203a75e0, 0xc4203a75f3, 0xc4200bfbf8)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/session.go:609 +0x515
github.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc420706a20, 0xc4203a75e0, 0x1c, 0xc42027dbb1, 0x4, 0x1d84a56, 0x9, 0xc4203a75e0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/driver_tidb.go:187 +0x62
github.com/pingcap/tidb/server.(*TiDBContext).FieldList(0xc420706a20, 0xc42027dbb1, 0x4, 0x1, 0xc4203a75a0, 0x2, 0x2, 0xc42067dd98)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/driver_tidb.go:226 +0x8e
github.com/pingcap/tidb/server.(*clientConn).handleFieldList(0xc420da7ce0, 0xc42027dbb1, 0x5, 0x2803f78, 0x6)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:706 +0xa6
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc420da7ce0, 0xc42027dbb1, 0x6, 0x5, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:476 +0x52f
github.com/pingcap/tidb/server.(*clientConn).Run(0xc420da7ce0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:358 +0x123
github.com/pingcap/tidb/server.(*Server).onConn(0xc42076aeb0, 0x24836c0, 0xc420b336f0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/server.go:228 +0x148
created by github.com/pingcap/tidb/server.(*Server).Run
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/server.go:177 +0xc5
```

## 4. What version of TiDB are you using (`tidb-server -V`)?

e94996addf821b09f93974a1187463d719ccf2fc

**Comment by zz-jason** [comment]
a simple query:
```sql
use test;
drop table if exists t;
create table t(a bigint);
insert into t values (12);
select * from t;
```

**Comment by zz-jason** [comment]
can be reproduced after a `mysql` client started:
```sql
use test;
drop table if exists t;
create table t(a bigint);
insert into t values (12);
select * from t limit 0;
```

**Comment by zz-jason** [comment]
when statistics is not ready, table count is 0, and `func (t *Table) Selectivity(ctx context.Context, exprs []expression.Expression) (float64, error)` returns 0,  which cause `func (p *DataSource) convertToTableScan(prop *requiredProp) (task task, err error)`  return a task with nil plan or plan with cost equals to `math.MaxFloat64`, which cause further physical plan optimization returns a nil plan and cause the panic this issue records.
