### ISSUE TITLE
several panic using go-fuzz to test

### ISSUE THREAD

**Issue by choleraehyq** [pingcap/tidb#3949]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
use go-fuzz to fuzz test parser.

2. What did you expect to see?
no crash.

3. What did you see instead?
Several crashes.

(1)
input: `/*!SET;SET;*/`
Panic message:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/pingcap/tidb/parser.(*Scanner).stmtText(0xc420062ba8, 0x8a6c40, 0xc420062ba8)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/lexer.go:104 +0x189
github.com/pingcap/tidb/parser.yyParse(0x8a6c40, 0xc420062ba8, 0xc420062b60, 0xc4200e9e30)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/parser.go:14182 +0x5d415
github.com/pingcap/tidb/parser.(*Parser).Parse(0xc420062b60, 0xc420016280, 0xd, 0x0, 0x0, 0x0, 0x0, 0xc4200e9e60, 0x43faf9, 0xc420016280, ...)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:96 +0x226
github.com/pingcap/tidb/parser.(*Parser).ParseOneStmt(0xc420062b60, 0xc420016280, 0xd, 0x0, 0x0, 0x0, 0x0, 0x14267e1c, 0x14267e1c00000000, 0x597d947d, ...)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:110 +0x95
github.com/pingcap/tidb/fuzztest/sqlparser.Fuzz(0x7fd2803ee000, 0xd, 0x200000, 0xc4200e9f70)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/fuzztest/sqlparser/fuzz.go:11 +0x161
go-fuzz-dep.Main(0x783488)
    /tmp/go-fuzz-build334939343/goroot/src/go-fuzz-dep/main.go:49 +0xad
main.main()
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/fuzztest/sqlparser/go.fuzz.main/main.go:10 +0x2d
exit status 2
```
(2)
input: `/*!SELECT 0*/`
panic message:
```
panic: runtime error: index out of range 

goroutine 1 [running]:
github.com/pingcap/tidb/parser.(*Scanner).stmtText(0xc420062ba8, 0x8a6c40, 0xc420062ba8)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/lexer.go:104 +0x189
github.com/pingcap/tidb/parser.yyParse(0x8a6c40, 0xc420062ba8, 0xc420062b60, 0xc4200e9e30)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/parser.go:14182 +0x5d415
github.com/pingcap/tidb/parser.(*Parser).Parse(0xc420062b60, 0xc420016280, 0xd, 0x0, 0x0, 0x0, 0x0, 0xc4200e9e60, 0x43faf9, 0xc420016280, ...)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:96 +0x226
github.com/pingcap/tidb/parser.(*Parser).ParseOneStmt(0xc420062b60, 0xc420016280, 0xd, 0x0, 0x0, 0x0, 0x0, 0x14267e1c, 0x14267e1c00000000, 0x597d947d, ...)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:110 +0x95
github.com/pingcap/tidb/fuzztest/sqlparser.Fuzz(0x7fd2803ee000, 0xd, 0x200000, 0xc4200e9f70)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/fuzztest/sqlparser/fuzz.go:11 +0x161
go-fuzz-dep.Main(0x783488)
    /tmp/go-fuzz-build334939343/goroot/src/go-fuzz-dep/main.go:49 +0xad
main.main()
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/fuzztest/sqlparser/go.fuzz.main/main.go:10 +0x2d
exit status 2
```
(3)
input: `/*!sELECT (0)*/`
panic message: 
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/pingcap/tidb/parser.(*Parser).endOffset.func1(0xc420062b60, 0xc4200e9d38, 0x3ee61466)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:142 +0x78
github.com/pingcap/tidb/parser.(*Parser).endOffset(0xc420062b60, 0xc42016c0f0, 0xe000)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:142 +0x90
github.com/pingcap/tidb/parser.yyParse(0x8a6c40, 0xc420062ba8, 0xc420062b60, 0xc4200ebe30)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/parser.go:11551 +0x17f73
github.com/pingcap/tidb/parser.(*Parser).Parse(0xc420062b60, 0xc420016280, 0xf, 0x0, 0x0, 0x0, 0x0, 0xc4200ebe60, 0x43faf9, 0xc420016280, ...)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:96 +0x226
github.com/pingcap/tidb/parser.(*Parser).ParseOneStmt(0xc420062b60, 0xc420016280, 0xf, 0x0, 0x0, 0x0, 0x0, 0x168287f4, 0x168287f400000000, 0x597d9485, ...)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:110 +0x95
github.com/pingcap/tidb/fuzztest/sqlparser.Fuzz(0x7f4baf045000, 0xf, 0x200000, 0xc4200ebf70)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/fuzztest/sqlparser/fuzz.go:11 +0x161
go-fuzz-dep.Main(0x783488)
    /tmp/go-fuzz-build334939343/goroot/src/go-fuzz-dep/main.go:49 +0xad
main.main()
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/fuzztest/sqlparser/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

(4)
input: `'\\`
panic message: 
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/pingcap/tidb/parser.(*reader).inc(...)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/lexer.go:712
github.com/pingcap/tidb/parser.(*Scanner).scanString(0xc420077088, 0x7fee7f412260, 0x40000000000, 0x10, 0x10, 0xc42000e7b0, 0x7fee7f412260)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/lexer.go:518 +0x778
github.com/pingcap/tidb/parser.startString(0xc420077088, 0x0, 0x0, 0x0, 0x0, 0xc42000e7b0, 0x0)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/lexer.go:454 +0x68
github.com/pingcap/tidb/parser.(*Scanner).scan(0xc420077088, 0x0, 0x0, 0x0, 0x0, 0xc4200fbd40, 0x584614)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/lexer.go:225 +0x3e2
github.com/pingcap/tidb/parser.(*Scanner).Lex(0xc420077088, 0xc420077170, 0x2300000001)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/lexer.go:132 +0x45
github.com/pingcap/tidb/parser.yylex1(0x8a6c40, 0xc420077088, 0xc420077170, 0x0)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/parser.go:10100 +0x6e
github.com/pingcap/tidb/parser.yyParse(0x8a6c40, 0xc420077088, 0xc420077040, 0xc4200fde30)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/parser.go:10155 +0x6d07f
github.com/pingcap/tidb/parser.(*Parser).Parse(0xc420077040, 0xc4200162c0, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc4200fde60, 0x43faf9, 0xc4200162c0, ...)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:96 +0x226
github.com/pingcap/tidb/parser.(*Parser).ParseOneStmt(0xc420077040, 0xc4200162c0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x344e579e, 0x344e579e00000000, 0x597d83b2, ...)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:110 +0x95
github.com/pingcap/tidb/fuzztest/sqlparser.Fuzz(0x7fee7f1ee000, 0x2, 0x200000, 0x3)
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/fuzztest/sqlparser/fuzz.go:11 +0x161
go-fuzz-dep.Main(0x783488)
    /tmp/go-fuzz-build334939343/goroot/src/go-fuzz-dep/main.go:49 +0xad
main.main()
    /tmp/go-fuzz-build334939343/gopath/src/github.com/pingcap/tidb/fuzztest/sqlparser/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

I've already send a pr to fix 4) https://github.com/pingcap/tidb/pull/3948

about 1), there must be some mistakes in lexer, because the following code:
```
        l := NewScanner("/*!SELECT 0*/")
	for {
		var v yySymType
		t := l.Lex(&v)
		fmt.Printf("%#v\n", v)
		if t == 0 || t == unicode.ReplacementChar {
			break
		}
	}
```
will print 
```
parser.yySymType{yys:0, offset:10, item:interface {}(nil), ident:"SELECT"}
parser.yySymType{yys:0, offset:17, item:0, ident:"0"}
parser.yySymType{yys:0, offset:13, item:interface {}(nil), ident:""}
```
obviously offset 17 doesn't exist. But currently I don't know how to fix it.

4. What version of TiDB are you using (`tidb-server -V`)?
```
[cholerae@x240s parser]$ git rev-parse master
764e2d43e59bd2f4df0d823e01e43707f5b62697
```

**Comment by zz-jason** [comment]
@tiancaiamao PTAL

**Comment by nullnotnil** [comment]
I can verify that this issue is now fixed. Since the MySQL CLI does some parsing + strips comments, I wrote a small go program:
```
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
)

func main() {

	db, err := sql.Open("mysql", "root@(localhost:4000)/test")
	if err != nil {
		fmt.Printf("Could not connect to MySQL: %s.", err)
	}

	_, err = db.Exec("/*!SET;SET;*/")
	if err != nil {
		fmt.Printf("error: %s\n", err)
	}

	_, err = db.Exec("/*!SELECT 0*/")
	if err != nil {
		fmt.Printf("error: %s\n", err)
	}

	_, err = db.Exec("/*!sELECT (0)*/")
	if err != nil {
		fmt.Printf("error: %s\n", err)
	}

	_, err = db.Exec("'\\")
	if err != nil {
		fmt.Printf("error: %s\n", err)
	}

}
```

The output:
```bash
$ go run test.go 
error: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 7 near ";SET;*/" 
error: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 2 near "'\" 
```

The TiDB server did not panic.
