### ISSUE TITLE
after tiup upgrade from v4.0.46 to v6.5.0, cdc task return error:"\"code\": \"CDC:ErrMySQLWorkerPanic\"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#39827]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. install tidb cluster with 4.0.16 
2. start CDC task
3. upgrade to 6.5.0
4. check CDC job status

### 2. What did you expect to see? (Required)
CDC task work normal

### 3. What did you see instead (Required)
[result="[\n  {\n    \"id\": \"simple
-cdc-task\",\n    \"namespace\": \"default\",\n    \"summary\": {\n      \"state\": \"error\",\n      \"tso\": 43799
1879732101144,\n      \"checkpoint\": \"2022-12-12 08:53:45.980\",\n      \"error\": {\n        \"addr\": \"cdc-peer
:8300\",\n        \"code\": \"CDC:ErrMySQLWorkerPanic\",\n        \"message\": \"[CDC:ErrMySQLWorkerPanic]Transactio
n sink worker panics, stack: goroutine 10099 [running]:\\ngithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn.(*worke
r).runBackgroundLoop.func1.2()\\n\\tgithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn/worker.go:127 +0x7b\\npanic({
0x3297be0, 0x6ed1470})\\n\\truntime/panic.go:884 +0x212\\ngithub.com/pingcap/tiflow/cdc/model.BuildTiDBTableInfo({0x
c008a86ae0, 0x3, 0xc003fd2c80?}, {0xc006084c60, 0x2, 0xc0036692e8?})\\n\\tgithub.com/pingcap/tiflow/cdc/model/sink.g
o:512 +0x515\\ngithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn/mysql.(*mysqlBackend).prepareDMLs(0xc0065aae80)\\n
\\tgithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn/mysql/mysql.go:419 +0x130b\\ngithub.com/pingcap/tiflow/cdc/sin
kv2/eventsink/txn/mysql.(*mysqlBackend).Flush(0xc0065aae80, {0x4120af0, 0xc004d1ed50})\\n\\tgithub.com/pingcap/tiflo
w/cdc/sinkv2/eventsink/txn/mysql/mysql.go:153 +0xca\\ngithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn.(*worker).d
oFlush(0xc006600ea0, 0xc003669c58)\\n\\tgithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn/worker.go:209 +0xfd\\ngit
hub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn.(*worker).runBackgroundLoop.func1()\\n\\tgithub.com/pingcap/tiflow/c
dc/sinkv2/eventsink/txn/worker.go:163 +0x4df\\ncreated by github.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn.(*worke
r).runBackgroundLoop\\n\\tgithub.com/pingcap/tiflow/cdc/sinkv2/eventsink/txn/worker.go:111 +0x6a\\n\"\n      }\n
}\n  }\n]"]
### 4. What is your TiDB version? (Required)

[2022/12/12 08:25:12.196 +08:00] [INFO] [version.go:47] ["Welcome to Change Data Capture (CDC)"] [release-version=v4.0.16] [git-hash=af41784fc3f69fc808b799b845ec99804fa00973] [git-branch=heads/refs/tags/v4.0.16] [utc-build-time="2021-12-16 11:21:30"] [go-version="go version go1.13 linux/amd64"] [failpoint-build=false]

**Comment by seiya-annie** [comment]
[cdc.log](https://github.com/pingcap/tidb/files/10205210/cdc.log)

**Comment by lance6716** [comment]
Can you post the table structure of related tables? @seiya-annie

**Comment by seiya-annie** [comment]
```sql
  | CREATE TABLE `t1` (
  `a` int(11) NOT NULL,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`) /*T![clustered_index] CLUSTERED */,
  KEY `b` (`b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

**Comment by seiya-annie** [comment]
```code
[2022/12/12 19:45:25.263 +08:00] [INFO] [sink.go:513] [fields] [event="{\"start-ts\":437997661617651737,\"commit-ts\":437997661630758913,\"row-id\":0,\"table\":{\"db-name\":\"test\",\"tbl-name\":\"t1\",\"tbl-id\":370,\"is-partition\":false},\"column-infos\":[{\"ID\":1,\"IsPKHandle\":false,\"VirtualGenCol\":false,\"Ft\":{\"Tp\":15,\"Flag\":4099,\"Flen\":255,\"Decimal\":0,\"Charset\":\"utf8mb4\",\"Collate\":\"utf8mb4_bin\",\"Elems\":null,\"ElemsIsBinaryLit\":null}},{\"ID\":2,\"IsPKHandle\":false,\"VirtualGenCol\":false,\"Ft\":{\"Tp\":15,\"Flag\":4,\"Flen\":255,\"Decimal\":0,\"Charset\":\"utf8mb4\",\"Collate\":\"utf8mb4_bin\",\"Elems\":null,\"ElemsIsBinaryLit\":null}},{\"ID\":3,\"IsPKHandle\":false,\"VirtualGenCol\":false,\"Ft\":{\"Tp\":3,\"Flag\":0,\"Flen\":11,\"Decimal\":0,\"Charset\":\"binary\",\"Collate\":\"binary\",\"Elems\":null,\"ElemsIsBinaryLit\":null}}],\"columns\":null,\"pre-columns\":[{\"name\":\"a\",\"type\":15,\"charset\":\"utf8mb4\",\"flag\":26,\"value\":\"YmJjc2E=\",\"default\":null},null,null]}"] [columns="[{\"name\":\"a\",\"type\":15,\"charset\":\"utf8mb4\",\"flag\":26,\"value\":\"YmJjc2E=\",\"default\":null},null,null]"] [index="[[0],[1]]"]
```
