### ISSUE TITLE
panic while cast timestamp as int

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#3986]
## 1. What did you do?

```sql
SET SQL_MODE='NO_ENGINE_SUBSTITUTION';
SET TIME_ZONE="+03:00";

DROP TABLE IF EXISTS t;
CREATE TABLE t (ix TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

INSERT INTO t VALUES (0), (20030101010160), (20030101016001), (20030101240101), (20030132010101), (20031301010101), (20031200000000), (20030000000000);
SELECT CAST(ix AS SIGNED) FROM t;
```

## 2. What did you expect to see?

```
+--------------------+
| CAST(ix AS SIGNED) |
+--------------------+
|                  0 |
|                  0 |
|                  0 |
|                  0 |
|                  0 |
|                  0 |
|                  0 |
|                  0 |
+--------------------+
8 rows in set (0.00 sec)
```

## 3. What did you see instead?

```
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

the panic is:
```
2017/08/02 14:06:25 metrics.go:339: [warning] [EXPENSIVE_QUERY] SELECT CAST(ix AS SIGNED) FROM t
2017/08/02 14:06:25 conn.go:341: [error] lastCmd SELECT CAST(ix AS SIGNED) FROM t, time: missing Location in call to Date, goroutine 132 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc4207e2000)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:339 +0xcd
panic(0x1bcfb40, 0xc42000f350)
        /Users/jianzhang.zj/opt/go-1.8.1/src/runtime/panic.go:489 +0x2cf
time.Date(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x28, 0x28, ...)
        /Users/jianzhang.zj/opt/go-1.8.1/src/time/time.go:1053 +0x65b
github.com/pingcap/tidb/util/types.mysqlTime.GoTime(0x0, 0xc400000000, 0x0, 0xffffffffffffffff, 0x0, 0x2498d20, 0xc42000f330, 0x7)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/util/types/mytime.go:93 +0x185
github.com/pingcap/tidb/util/types.(*mysqlTime).GoTime(0xc42000f330, 0x0, 0x0, 0x0, 0x0, 0xd, 0x0)
        <autogenerated>:70 +0x60
github.com/pingcap/tidb/util/types.Time.RoundFrac(0x2498d20, 0xc42000f330, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/util/types/time.go:355 +0x100
github.com/pingcap/tidb/expression.(*builtinCastTimeAsIntSig).evalInt(0xc42032a120, 0xc42040e700, 0x1, 0x1, 0x0, 0xc420417800, 0x100fe18, 0xc420417918)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/expression/builtin_cast.go:810 +0x184
github.com/pingcap/tidb/expression.(*baseIntBuiltinFunc).eval(0xc42032a120, 0xc42040e700, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/expression/builtin.go:262 +0x7e
github.com/pingcap/tidb/expression.(*ScalarFunction).Eval(0xc420347b00, 0xc42040e700, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/expression/scalar_function.go:167 +0x6b9
github.com/pingcap/tidb/executor.(*ProjectionExec).Next(0xc420cff450, 0xc420cff4a0, 0x2494600, 0xc420093590)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/executor.go:379 +0x19e
github.com/pingcap/tidb/executor.(*recordSet).Next(0xc420cff4a0, 0xc420417a90, 0xc420417a88, 0xc42084d5e0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/adapter.go:63 +0x38
github.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc4202b3100, 0x248fce0, 0xc4202b3100, 0x10, 0x10, 0x1c63420)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/driver_tidb.go:288 +0x37
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc4207e2000, 0x248fcc0, 0xc4202b3100, 0xc4202b0000, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:735 +0xbb
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc4207e2000, 0xc42036aed1, 0x20, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:688 +0xfb
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc4207e2000, 0xc42036aed1, 0x21, 0x20, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:470 +0x42e
github.com/pingcap/tidb/server.(*clientConn).Run(0xc4207e2000)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:361 +0x13c
github.com/pingcap/tidb/server.(*Server).onConn(0xc4202459f0, 0x2497780, 0xc42000c118)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/server.go:229 +0x148
created by github.com/pingcap/tidb/server.(*Server).Run
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/server.go:178 +0xc5
```

## 4. What version of TiDB are you using (`tidb-server -V`)?

1baee60037fb9b8c2a060a38250f617fbf91fe09

**Comment by zz-jason** [comment]
timestamp is zero, while `unflatten`(in file: `tablecodec/tablecodec.go`), it fails the `if ft.Tp == mysql.TypeTimestamp && !t.IsZero()` check and time zone is not set

according to @tiancaiamao zero time stamp should have no time zone
