### ISSUE TITLE
tidb panic when `getSession` in TTL

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#39864]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create a new interval session
2. Execute "commit" as the first sql

If commit spent a long time that triggers a slow log record, the tidb will panic. 

### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x593a81b]
goroutine 50454 [running]:
[github.com/pingcap/tidb/executor.(*ExecStmt).LogSlowQuery](http://github.com/pingcap/tidb/executor.(*ExecStmt).LogSlowQuery)(0xc0129af4a0, 0x0, 0x1, 0x0)
	executor/adapter.go:1542 +0xedb
[github.com/pingcap/tidb/executor.(*ExecStmt).FinishExecuteStmt](http://github.com/pingcap/tidb/executor.(*ExecStmt).FinishExecuteStmt)(0xc0129af4a0, 0xc012e14840?, {0x0, 0x0}, 0x0?)
	executor/adapter.go:1387 +0x6ec
[github.com/pingcap/tidb/session.runStmt](http://github.com/pingcap/tidb/session.runStmt)({0x8186c90, 0xc012e14840}, 0xc022c38500, {0x81988e0, 0xc0129af4a0?})
	session/session.go:2374 +0xb65
[github.com/pingcap/tidb/session.(*session).ExecuteStmt](http://github.com/pingcap/tidb/session.(*session).ExecuteStmt)(0xc022c38500, {0x8186c90, 0xc012e14840}, {0x819f020?, 0xc0075e9180?})
	session/session.go:2211 +0x1026
[github.com/pingcap/tidb/session.(*session).ExecuteInternal](http://github.com/pingcap/tidb/session.(*session).ExecuteInternal)(0xc022c38500, {0x8186c90, 0xc012e14840}, {0x695639d, 0x6}, {0x0, 0x0, 0x0})
	session/session.go:1674 +0x472
[github.com/pingcap/tidb/ttl/session.(*session).ExecuteSQL](http://github.com/pingcap/tidb/ttl/session.(*session).ExecuteSQL)(0xc012e14810, {0x8186c20, 0xc00013c008}, {0x695639d, 0x6}, {0x0, 0x0, 0x0})
	ttl/session/session.go:79 +0x16b
[github.com/pingcap/tidb/ttl/ttlworker.getSession](http://github.com/pingcap/tidb/ttl/ttlworker.getSession)({0x816b2c8, 0xc00649a7e0})
	ttl/ttlworker/session.go:63 +0x2c5
[github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop(0xc011a91d80)](http://github.com/pingcap/tidb/ttl/ttlworker.(*ttlDeleteWorker).loop(0xc011a91d80))
	ttl/ttlworker/del.go:246 +0x72
[github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc011a91d80)](http://github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc011a91d80))
	ttl/ttlworker/worker.go:123 +0xa4
[github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()](http://github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1())
	util/wait_group_wrapper.go:33 +0x74
created by [github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run](http://github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run)
	util/wait_group_wrapper.go:31 +0xe5
```

### 4. What is your TiDB version? (Required)

master

**Comment by lcwangchao** [comment]
This bug happens here:

https://github.com/pingcap/tidb/blob/2dea8dda283d98a0780179e7483fdb523bdad14c/executor/adapter.go#L1541 

It did not check whether `sessVars.PrevStmt` is nil
