### ISSUE TITLE
TiDB panic in github.com/pingcap/tidb/table/tables.(*TableCommon).RemoveRecord

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#40021]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

add/drop column ddl and sysbench workload
```
[2022/12/17 20:03:03.595 +08:00] [ERROR] [conn.go:801] ["connection running loop panic"] [conn=1859] [lastSQL="DELETE FROM sbtest5 WHERE id=? [arguments: 5282414]"] [err="runtime error: index out of range [4] with length 4"] [stack="goroutine 172802934 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x3c73f38, 0xc005a7e030, 0xc001b64500)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:799 +0xf5
panic(0x358d520, 0xc0014a34a0)
\t/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1(0xc002aea680, 0xc000b8ec40, 0xc000b8ec20)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:332 +0x4d4
panic(0x358d520, 0xc0014a34a0)
\t/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/pingcap/tidb/table/tables.(*TableCommon).RemoveRecord(0xc0011f3200, 0x3cb3750, 0xc001a02000, 0x3ca0208, 0xc00513d720, 0xc00480d8c0, 0x4, 0x4, 0x0, 0x0)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/table/tables/tables.go:1091 +0x1826
github.com/pingcap/tidb/executor.(*DeleteExec).removeRow(0xc003067b80, 0x3cb3750, 0xc001a02000, 0x3ca4e80, 0xc0011f3200, 0x3ca0208, 0xc00513d720, 0xc00480d8c0, 0x4, 0x4, ...)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/delete.go:210 +0xf5
github.com/pingcap/tidb/executor.(*DeleteExec).deleteOneRow(0xc003067b80, 0x3ca4e80, 0xc0011f3200, 0x3c9bf18, 0xc0025fd680, 0xc00480d800, 0xc00480d8c0, 0x4, 0x4, 0xc000b8e700, ...)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/delete.go:62 +0x105
github.com/pingcap/tidb/executor.(*DeleteExec).deleteSingleTableByChunk(0xc003067b80, 0x3c73f38, 0xc0019f0810, 0x0, 0x202e71319ff700)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/delete.go:112 +0x3c5
github.com/pingcap/tidb/executor.(*DeleteExec).Next(0xc003067b80, 0x3c73f38, 0xc0019f0810, 0xc002afafa0, 0x0, 0xc000b8e850)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/delete.go:50 +0x92
github.com/pingcap/tidb/executor.Next(0x3c73f38, 0xc0019f0810, 0x3c77cd8, 0xc003067b80, 0xc002afafa0, 0x0, 0x0)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:286 +0x2de
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc002aea680, 0x3c73f38, 0xc0019f0810, 0x3c77cd8, 0xc003067b80, 0x0, 0x0, 0x0, 0x0)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:589 +0x2e7
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc002aea680, 0x3c73f38, 0xc0019f0810, 0x3c77cd8, 0xc003067b80, 0x5821000, 0x3c73f01, 0x0, 0x0, 0x0, ...)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:470 +0x1e5
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc002aea680, 0x3c73f38, 0xc0019f0810, 0x0, 0x0, 0x0, 0x0)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:419 +0x707
github.com/pingcap/tidb/session.runStmt(0x3c73f38, 0xc001ebfe30, 0xc001a02000, 0x3c89e58, 0xc002aea680, 0x0, 0x0, 0x0, 0x0)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1637 +0x37f
github.com/pingcap/tidb/session.(*session).preparedStmtExec(0xc001a02000, 0x3c73f38, 0xc001ebfe30, 0x3caa5e8, 0xc006b1b130, 0x0, 0x5, 0xc001caf980, 0xc00216d9a0, 0x1, ...)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1774 +0x299
github.com/pingcap/tidb/session.(*session).ExecutePreparedStmt(0xc001a02000, 0x3c73f38, 0xc001ebfe30, 0x5, 0xc00216d9a0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1935 +0x458
github.com/pingcap/tidb/server.(*TiDBStatement).Execute(0xc002bc9dc0, 0x3c73f38, 0xc001ebfe30, 0xc00216d9a0, 0x1, 0x1, 0x7f5504436c00, 0xc000101000, 0x0, 0xc000b8eff0)
\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:73 +0x93
github.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult(0xc001b64500, 0x3c73f38, 0xc001ebfe30, 0x3c9ff68, 0xc002bc9dc0, 0xc00216d9a0, 0x1, 0x1, 0x0, 0x0, ...)
\t/home/jenkins/agent/wor"]
```
### 4. What is your TiDB version? (Required)

5.1
 Release Version: v5.1.5
Edition: Community
Git Commit Hash: 5a7a495770178f39f867ddeb46abdec7eeb5efb4
Git Branch: heads/refs/tags/v5.1.5
UTC Build Time: 2022-12-16 09:29:51
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by you06** [comment]
Can you help verify if #40046 solves this issue?

**Comment by lilinghai** [comment]
> Can you help verify if #40046 solves this issue?

@you06 I test it for 3 times and all tests are successful
