### ISSUE TITLE
sql `explain` Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#4010]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
create table `t1` (`a` int);
explain select 1 from t1, t1 as t2 where t1.a > all((select a from t1) union (select a));
```

2. What did you expect to see?

```
mysql> explain select 1 from t1, t1 as t2 where t1.a > all((select a from t1) union (select a));
ERROR 1052 (23000): Column 'a' in field list is ambiguous
```

3. What did you see instead?

```
mysql> explain select 1 from t1, t1 as t2 where t1.a > all((select a from t1) union (select a));
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
TiDB log:

```
2017/08/03 03:54:31 conn.go:341: [error] lastCmd explain select 1 from t1, t1 as t2 where t1.a > all((select a from t1) union (select a)), runtime error: invalid memory address or nil pointer dereference, goroutine 6712 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc42087c9a0)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/server/conn.go:339 +0xcd                                                                                                  panic(0x101a800, 0x1b8bed0)
  /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/pingcap/tidb/plan.(*planBuilder).buildUnion(0xc4209b2370, 0xc4202833b0, 0xc420f24e88, 0x440fa0)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/logical_plan_builder.go:500 +0x267
github.com/pingcap/tidb/plan.(*planBuilder).buildResultSetNode(0xc4209b2370, 0x1877f20, 0xc4202833b0, 0x0, 0x1)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/logical_plan_builder.go:143 +0x716
github.com/pingcap/tidb/plan.(*expressionRewriter).buildSubquery(0xc420c0e460, 0xc42094a820, 0xc420c0e460, 0x18722a0)                                                               /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/expression_rewriter.go:213 +0xb5
github.com/pingcap/tidb/plan.(*expressionRewriter).handleCompareSubquery(0xc420c0e460, 0xc420a987e0, 0x30, 0x70, 0x70)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/expression_rewriter.go:289 +0x1e0
github.com/pingcap/tidb/plan.(*expressionRewriter).Enter(0xc420c0e460, 0x18723a0, 0xc420a987e0, 0x70, 0x1126a20, 0xc420f25101)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/expression_rewriter.go:242 +0x7db
github.com/pingcap/tidb/ast.(*CompareSubqueryExpr).Accept(0xc420a987e0, 0x186a7e0, 0xc420c0e460, 0x408285, 0x95e2375, 0xc42096c210)                                                 /home/wink/machome/go_dir/src/github.com/pingcap/tidb/ast/expressions.go:300 +0x4b                                                                                              github.com/pingcap/tidb/plan.(*planBuilder).rewriteWithPreprocess(0xc4209b2370, 0x7f5be467ce30, 0xc420a987e0, 0x188f3e0, 0xc420743c20, 0x0, 0xc420a2ee00, 0x0, 0xc42096c210, 0xc42096c1e0, ...)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/expression_rewriter.go:83 +0x120
github.com/pingcap/tidb/plan.(*planBuilder).rewrite(0xc4209b2370, 0x7f5be467ce30, 0xc420a987e0, 0x188f3e0, 0xc420743c20, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/expression_rewriter.go:64 +0x88
github.com/pingcap/tidb/plan.(*planBuilder).buildSelection(0xc4209b2370, 0x188f3e0, 0xc420743c20, 0x7f5be467ce30, 0xc420a987e0, 0x0, 0xc42000d360, 0x1)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/logical_plan_builder.go:392 +0x1d8
github.com/pingcap/tidb/plan.(*planBuilder).buildSelect(0xc4209b2370, 0xc4208ea280, 0x0, 0x0)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/logical_plan_builder.go:1047 +0xc66
github.com/pingcap/tidb/plan.(*planBuilder).build(0xc4209b2370, 0x18730e0, 0xc4208ea280, 0x0, 0xc42096c030)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/planbuilder.go:152 +0x675
github.com/pingcap/tidb/plan.Optimize(0x187c700, 0xc42087cbb0, 0x18730e0, 0xc4208ea280, 0x7f5be46158f0, 0xc4208e84b0, 0x0, 0xc420f256d8, 0x40f722, 0xc420955fb0)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/optimizer.go:71 +0x1a7
github.com/pingcap/tidb/plan.(*planBuilder).buildExplain(0xc4209b22c0, 0xc4209b5180, 0x5d230a7b, 0xc420955fb0)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/planbuilder.go:901 +0xeb
github.com/pingcap/tidb/plan.(*planBuilder).build(0xc4209b22c0, 0x1872820, 0xc4209b5180, 0x0, 0xc420955fb0)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/planbuilder.go:144 +0x7fa
github.com/pingcap/tidb/plan.Optimize(0x187c700, 0xc42087cbb0, 0x1872820, 0xc4209b5180, 0x7f5be46158f0, 0xc4208e84b0, 0x0, 0x0, 0x1ba1a40, 0x7f5be46af000)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/plan/optimizer.go:71 +0x1a7
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc420f258f0, 0x187c700, 0xc42087cbb0, 0x7f5be467b7a8, 0xc4209b5180, 0xc420f258f0, 0x486452, 0xc42093c9a0, 0xc4209e76c0)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/executor/compiler.go:41 +0x1b7
github.com/pingcap/tidb.Compile(0x187c700, 0xc42087cbb0, 0x7f5be467b7a8, 0xc4209b5180, 0x0, 0x0, 0x0, 0xc420957420)
  /home/wink/machome/go_dir/src/github.com/pingcap/tidb/tidb.go:149 +0x57
github.com/pingcap/tidb.(*session).Execute(0xc42087cbb0, 0xc420a2ec61, 0x58, 0xc420f25bb8, 0x410
2017/08/03 03:54:31 server.go:212: [info] [2] close connection
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by zz-jason** [comment]
panic during `plan.(*planBuilder).buildUnion`, @hanfei1991 PTAL

**Comment by zz-jason** [comment]
```
select 1 from t1, t1 as t2 where t1.a > all((select a from t1) union (select a));
```

ignore the `explain`, this sql panics, too
