### ISSUE TITLE
fast reorg test case fails with unexpected goroutines

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#40183]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

When writing a test and running `alter table t add index(a)` with `tidb_ddl_enable_fast_reorg = ON` the test will succeed, but fail on goleak.

### 1. Minimal reproduce step (Required)

Create a go test file with this:
```golang
        store := testkit.CreateMockStore(t)
        tk := testkit.NewTestKit(t, store)
        tk.MustExec("use test")

        tk.MustExec("set global tidb_ddl_enable_fast_reorg = ON")
        tk.MustExec("create table t (a int)")
        tk.MustExec("alter table t add index(a)")
```

### 2. What did you expect to see? (Required)
Test passing, including goleak

### 3. What did you see instead (Required)
```
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 11497 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
goroutine 11497 [IO wait]:
internal/poll.runtime_pollWait(0x1331b6958, 0x72)
	/usr/local/go/src/runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0x14007e83e00?, 0x14008d7e000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x14007e83e00, {0x14008d7e000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x1e0
net.(*netFD).Read(0x14007e83e00, {0x14008d7e000?, 0x1400704ec58?, 0x104be70a4?})
	/usr/local/go/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x14007276490, {0x14008d7e000?, 0x0?, 0x14007f50f00?})
	/usr/local/go/src/net/net.go:183 +0x34
net/http.(*persistConn).Read(0x140067ba360, {0x14008d7e000?, 0x104be7150?, 0x140007305a0?})
	/usr/local/go/src/net/http/transport.go:1929 +0x50
bufio.(*Reader).fill(0x1400543e360)
	/usr/local/go/src/bufio/bufio.go:106 +0xfc
bufio.(*Reader).Peek(0x1400543e360, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x60
net/http.(*persistConn).readLoop(0x140067ba360)
	/usr/local/go/src/net/http/transport.go:2093 +0x144
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1751 +0x11c8

 Goroutine 11498 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
goroutine 11498 [select]:
net/http.(*persistConn).writeLoop(0x140067ba360)
	/usr/local/go/src/net/http/transport.go:2392 +0xa0
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1752 +0x1214
]
exit status 1
FAIL	github.com/pingcap/tidb/ddl	5.573s
```

### 4. What is your TiDB version? (Required)

Current master.
```
tidb_version(): Release Version: v6.6.0-alpha-81-g79ab2b92a0
Edition: Community
Git Commit Hash: 79ab2b92a046bba03f957c4bf421eb9fb55bc053
Git Branch: master
UTC Build Time: 2022-12-27 00:00:34
GoVersion: go1.19.4
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
```

**Comment by mjonss** [comment]
Also notice that tidb_ddl_enable_fast_reorg changed the default in 9784615566d565a36e5a2401d48c84f1c82dca9d from OFF to ON.

**Comment by tangenta** [comment]
I think this is not a bug. If `tidb_ddl_enable_fast_reorg ` is enabled, adding index will check if log backup is used(for now ingest mode is not compatible with log backup), which in turn executes the `SHOW CONFIG` statement:

```
executor.fetchClusterConfig (memtable_reader.go:193) github.com/pingcap/tidb/executor
executor.(*ShowExec).fetchShowClusterConfigs (show.go:1321) github.com/pingcap/tidb/executor
executor.(*ShowExec).fetchAll (show.go:171) github.com/pingcap/tidb/executor
executor.(*ShowExec).Next (show.go:118) github.com/pingcap/tidb/executor
executor.Next (executor.go:328) github.com/pingcap/tidb/executor
executor.(*SelectionExec).Next (executor.go:1584) github.com/pingcap/tidb/executor
executor.Next (executor.go:328) github.com/pingcap/tidb/executor
executor.(*ExecStmt).next (adapter.go:1142) github.com/pingcap/tidb/executor
executor.(*recordSet).Next (adapter.go:153) github.com/pingcap/tidb/executor
<autogenerated>:2
session.drainRecordSet (session.go:1408) github.com/pingcap/tidb/session
session.(*session).ExecRestrictedSQL.func1 (session.go:2107) github.com/pingcap/tidb/session
session.(*session).withRestrictedSQLExecutor (session.go:2080) github.com/pingcap/tidb/session
session.(*session).ExecRestrictedSQL (session.go:2084) github.com/pingcap/tidb/session
utils.IsLogBackupEnabled (db.go:81) github.com/pingcap/tidb/br/pkg/utils
utils.CheckLogBackupEnabled (db.go:63) github.com/pingcap/tidb/br/pkg/utils
utils.IsLogBackupInUse (db.go:156) github.com/pingcap/tidb/br/pkg/utils
ddl.canUseIngest (index.go:741) github.com/pingcap/tidb/ddl
ddl.pickBackfillType (index.go:706) github.com/pingcap/tidb/ddl
ddl.(*worker).onCreateIndex (index.go:617) github.com/pingcap/tidb/ddl
ddl.(*worker).runDDLJob (ddl_worker.go:1233) github.com/pingcap/tidb/ddl
ddl.(*worker).HandleDDLJobTable (ddl_worker.go:839) github.com/pingcap/tidb/ddl
ddl.(*ddl).delivery2worker.func1 (job_table.go:271) github.com/pingcap/tidb/ddl
util.(*WaitGroupWrapper).Run.func1 (wait_group_wrapper.go:33) github.com/pingcap/tidb/util
runtime.goexit (asm_arm64.s:1165) runtime
 - Async Stack Trace
util.(*WaitGroupWrapper).Run (wait_group_wrapper.go:31) github.com/pingcap/tidb/util
```

Then TiDB sends HTTP requests to different nodes through a internal client:

https://github.com/pingcap/tidb/blob/20bb0464ef9eaae3c1fc5afd3f44cf015e65b976/executor/memtable_reader.go#L214

```
http.(*Transport).queueForDial (transport.go:1416) net/http
http.(*Transport).getConn (transport.go:1373) net/http
http.(*Transport).roundTrip (transport.go:582) net/http
http.(*Transport).RoundTrip (roundtrip.go:17) net/http
http.send (client.go:251) net/http
http.(*Client).send (client.go:175) net/http
http.(*Client).do (client.go:715) net/http
http.(*Client).Do (client.go:581) net/http
executor.fetchClusterConfig.func2.1 (memtable_reader.go:214) github.com/pingcap/tidb/executor
util.WithRecovery (misc.go:96) github.com/pingcap/tidb/util
executor.fetchClusterConfig.func2 (memtable_reader.go:195) github.com/pingcap/tidb/executor
executor.fetchClusterConfig.func4 (memtable_reader.go:267) github.com/pingcap/tidb/executor
runtime.goexit (asm_arm64.s:1165) runtime
 - Async Stack Trace
executor.fetchClusterConfig (memtable_reader.go:194) github.com/pingcap/tidb/executor
```

The "leaked" goroutine comes from this internal client, because neither `IdleConnTimeout` nor `DisableKeepAlives = true` is set.

https://github.com/pingcap/tidb/blob/20bb0464ef9eaae3c1fc5afd3f44cf015e65b976/util/misc.go#L588-L590

Actually, we have a lot of leak-tests ignoring it:

```go
goleak.IgnoreTopFunction("net/http.(*persistConn).writeLoop"),
```
