### ISSUE TITLE
flashback to transaction begin fail for "Duplicate entry '30004' for key 'GLOBAL_VARIABLES.PRIMARY'"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#40477]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

'CREATE TABLE t (a INT);'
'alter table t set tiflash replica 1'
'do sleep(10)'
'insert into t values(1),(1),(2);'
-----flashback target timestamp
'begin;'
'do sleep(4)'
'update t set a=111 where a=1;'
'commit;'
flashback cluster to timestamp '2023-01-10 21:41:13' --before "begin"
'do sleep(3)'
flashback cluster to timestamp '2023-01-10 21:41:13'

### 2. What did you expect to see? (Required)
flashback success

### 3. What did you see instead (Required)
(IntegrityError(1062, "Duplicate entry '30004' for key 'GLOBAL_VARIABLES.PRIMARY'")

### 4. What is your TiDB version? (Required)
[tidb@101 ~]$ /home/tidb/deploy/tidb-4000/bin/tidb-server -V
Release Version: v6.6.0-alpha
Edition: Community
Git Commit Hash: 7e64d04f734667e20125ec7885495cb228987ad0
Git Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time: 2023-01-05 14:32:46
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
[tidb@101 ~]$

**Comment by seiya-annie** [comment]
[tidb.log](https://github.com/pingcap/tidb/files/10383303/tidb.log)

**Comment by seiya-annie** [comment]
[TC_flashback_func_035.py.gz](https://github.com/pingcap/tidb/files/10383327/TC_flashback_func_035.py.gz)
[__init__.py.gz](https://github.com/pingcap/tidb/files/10383350/__init__.py.gz)

**Comment by seiya-annie** [comment]
another case reported "Duplicate entry '60002' for key 'tidb.PRIMARY'"
-tps-1331395-1-257.svc, port: 4000, username: root, password: , database: 0000__Flashback_func_005_JJLVDN
2023-01-09 16:23:39,758 ERROR [0000__Flashback-func-005][default.py:102] - test failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/utf/scheduler/default.py", line 90, in run
    c.execute()
  File "/usr/local/lib/python3.8/site-packages/utf/core/__init__.py", line 155, in execute
    raise error
utf.core.StagedCase.Error: (IntegrityError(1062, "Duplicate entry '60002' for key 'tidb.PRIMARY'"), 'run')
