### ISSUE TITLE
TiDB crash by nil pointer dereference

### ISSUE THREAD

**Issue by blacktear23** [pingcap/tidb#4057]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Run TiDB rc4 on my laptop, then sleep my laptop for two days then open my laptop see running TiDB crashed.

below is crash log.

```
2017/08/05 03:29:08 schema_validator.go:158: [info] the schema validator's latest schema version 0 is expired
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1872bfc]

goroutine 214 [running]:
github.com/pingcap/tidb/domain.(*schemaValidator).Update(0xc420072280, 0x576bae42b140003, 0xd, 0xd, 0x0, 0x0, 0x0)
	/Users/rainli/goprojs/src/github.com/pingcap/tidb/domain/schema_validator.go:111 +0x56c
github.com/pingcap/tidb/domain.(*Domain).Reload(0xc420366480, 0x0, 0x0)
	/Users/rainli/goprojs/src/github.com/pingcap/tidb/domain/domain.go:299 +0x318
github.com/pingcap/tidb/domain.(*Domain).loadSchemaInLoop(0xc420366480, 0x2540be400)
	/Users/rainli/goprojs/src/github.com/pingcap/tidb/domain/domain.go:321 +0x192
created by github.com/pingcap/tidb/domain.NewDomain
	/Users/rainli/goprojs/src/github.com/pingcap/tidb/domain/domain.go:443 +0x4aa
```

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V`)?

```
Git Commit Hash: 6e0ff81269d49ffec39066d5110ee28f7fe67f2f
UTC Build Time:  2017-08-04 03:47:00
```

**Comment by zimulala** [comment]
@blacktear23 Thanks for your report and PR.
Can you give me more of the log before `2017/08/05 03:29:08 schema_validator.go:158`？

**Comment by blacktear23** [comment]
Except time not same all message after time is same.

**Comment by blacktear23** [comment]
```
2017/08/05 00:18:23 printer.go:31: [info] Welcome to TiDB.
2017/08/05 00:18:23 printer.go:32: [info] Version:
2017/08/05 00:18:23 printer.go:33: [info] Git Commit Hash: 6e0ff81269d49ffec39066d5110ee28f7fe67f2f
2017/08/05 00:18:23 printer.go:34: [info] UTC Build Time:  2017-08-04 03:47:00
INFO[0000] [pd] create pd client with endpoints [127.0.0.1:2379]
INFO[0000] [pd] leader switches to: http://127.0.0.1:2379, previous:
INFO[0000] [pd] init cluster id 6447791843226322487
2017/08/05 00:18:23 gc_worker.go:107: [info] [gc worker] 576b82997040002 start.
2017/08/05 00:18:23 tidb.go:69: [info] store tikv-6447791843226322487 new domain, ddl lease 10s, stats lease 3000000000
2017/08/05 00:18:23 ddl.go:286: [info] start DDL:e7d02de7-b1c7-4906-87e2-bef430fb7c60
2017/08/05 00:18:23 owner_manager.go:251: [info] [ddl] /tidb/ddl/fg/owner ownerManager is e7d02de7-b1c7-4906-87e2-bef430fb7c60, owner is e7d02de7-b1c7-4906-87e2-bef430fb7c60
2017/08/05 00:18:23 owner_manager.go:251: [info] [ddl] /tidb/ddl/bg/owner ownerManager is e7d02de7-b1c7-4906-87e2-bef430fb7c60, owner is e7d02de7-b1c7-4906-87e2-bef430fb7c60
2017/08/05 00:18:23 domain.go:107: [info] [ddl] full load InfoSchema from version 0 to 13, in 6.149289ms
2017/08/05 00:18:23 server.go:160: [info] Server run MySQL Protocol Listen at [0.0.0.0:4000]
2017/08/05 00:18:23 main.go:215: [info] disable Prometheus push client
2017/08/05 00:18:23 systime_mon.go:11: [info] start system time monitor
2017/08/05 00:18:23 http_status.go:57: [info] Listening on :10080 for status and metrics report.
2017/08/05 00:18:27 server.go:118: [info] [1] new connection 127.0.0.1:61550
^C2017/08/05 00:19:07 main.go:170: [info] Got signal [2] to exit.
2017/08/05 00:19:07 owner_manager.go:180: [info] [ddl] /tidb/ddl/bg/owner ownerManager e7d02de7-b1c7-4906-87e2-bef430fb7c60 etcd session is done, creates a new one
2017/08/05 00:19:07 owner_manager.go:145: [warning] [ddl] /tidb/ddl/bg/owner ownerManager e7d02de7-b1c7-4906-87e2-bef430fb7c60 failed to new session, err context canceled
2017/08/05 00:19:07 owner_manager.go:183: [info] [ddl] /tidb/ddl/bg/owner ownerManager e7d02de7-b1c7-4906-87e2-bef430fb7c60 break campaign loop, err context canceled
2017/08/05 00:19:07 owner_manager.go:193: [info] [ddl] /tidb/ddl/fg/owner ownerManager e7d02de7-b1c7-4906-87e2-bef430fb7c60 break campaign loop err <nil>
2017/08/05 00:19:07 ddl.go:328: [info] close DDL:e7d02de7-b1c7-4906-87e2-bef430fb7c60
2017/08/05 00:19:07 ddl.go:296: [info] stop DDL:e7d02de7-b1c7-4906-87e2-bef430fb7c60
➜  ~GOPATH/src/github.com/pingcap/tidb/bin git:(master) $ ./tidb-server
2017/08/05 00:19:08 printer.go:31: [info] Welcome to TiDB.
2017/08/05 00:19:08 printer.go:32: [info] Version:
2017/08/05 00:19:08 printer.go:33: [info] Git Commit Hash: 6e0ff81269d49ffec39066d5110ee28f7fe67f2f
2017/08/05 00:19:08 printer.go:34: [info] UTC Build Time:  2017-08-04 03:47:00
2017/08/05 00:19:08 kv.go:299: [info] [kv] New store /tmp/tidb
2017/08/05 00:19:08 tidb.go:69: [info] store e06c79b2-5fb4-4277-b4fa-50a7e4d218cd new domain, ddl lease 0s, stats lease 0
2017/08/05 00:19:08 ddl.go:286: [info] start DDL:15ea3a59-90d6-4ed2-8688-104eb7ea5676
2017/08/05 00:19:09 domain.go:107: [info] [ddl] full load InfoSchema from version 0 to 1890, in 24.96357ms
2017/08/05 00:19:09 server.go:160: [info] Server run MySQL Protocol Listen at [0.0.0.0:4000]
2017/08/05 00:19:09 main.go:215: [info] disable Prometheus push client
2017/08/05 00:19:09 systime_mon.go:11: [info] start system time monitor
2017/08/05 00:19:09 http_status.go:57: [info] Listening on :10080 for status and metrics report.
2017/08/05 00:19:11 server.go:118: [info] [1] new connection 127.0.0.1:61555
^C2017/08/05 00:19:17 main.go:170: [info] Got signal [2] to exit.
2017/08/05 00:19:17 ddl.go:328: [info] close DDL:15ea3a59-90d6-4ed2-8688-104eb7ea5676
2017/08/05 00:19:17 ddl.go:296: [info] stop DDL:15ea3a59-90d6-4ed2-8688-104eb7ea5676
➜  ~GOPATH/src/github.com/pingcap/tidb/bin git:(master) $ ./tidb-server --store=tikv --path="127.0.0.1:2379"
2017/08/05 00:19:18 printer.go:31: [info] Welcome to TiDB.
2017/08/05 00:19:18 printer.go:32: [info] Version:
2017/08/05 00:19:18 printer.go:33: [info] Git Commit Hash: 6e0ff81269d49ffec39066d5110ee28f7fe67f2f
2017/08/05 00:19:18 printer.go:34: [info] UTC Build Time:  2017-08-04 03:47:00
INFO[0000] [pd] create pd client with endpoints [127.0.0.1:2379]
INFO[0000] [pd] leader switches to: http://127.0.0.1:2379, previous:
INFO[0000] [pd] init cluster id 6447791843226322487
2017/08/05 00:19:18 gc_worker.go:107: [info] [gc worker] 576b82cf9700002 start.
2017/08/05 00:19:18 tidb.go:69: [info] store tikv-6447791843226322487 new domain, ddl lease 10s, stats lease 3000000000
2017/08/05 00:19:18 ddl.go:286: [info] start DDL:70fcedb3-c1d9-417e-881c-92f2dd5dde38
2017/08/05 00:19:18 owner_manager.go:251: [info] [ddl] /tidb/ddl/fg/owner ownerManager is 70fcedb3-c1d9-417e-881c-92f2dd5dde38, owner is 70fcedb3-c1d9-417e-881c-92f2dd5dde38
2017/08/05 00:19:18 domain.go:107: [info] [ddl] full load InfoSchema from version 0 to 13, in 6.246248ms
2017/08/05 00:19:18 server.go:160: [info] Server run MySQL Protocol Listen at [0.0.0.0:4000]
2017/08/05 00:19:18 main.go:215: [info] disable Prometheus push client
2017/08/05 00:19:18 systime_mon.go:11: [info] start system time monitor
2017/08/05 00:19:18 http_status.go:57: [info] Listening on :10080 for status and metrics report.
2017/08/05 00:19:20 server.go:118: [info] [1] new connection 127.0.0.1:61576
2017/08/05 00:20:04 owner_manager.go:251: [info] [ddl] /tidb/ddl/bg/owner ownerManager is 70fcedb3-c1d9-417e-881c-92f2dd5dde38, owner is 70fcedb3-c1d9-417e-881c-92f2dd5dde38
2017/08/05 03:29:04 owner_manager.go:180: [info] [ddl] /tidb/ddl/fg/owner ownerManager 70fcedb3-c1d9-417e-881c-92f2dd5dde38 etcd session is done, creates a new one
2017/08/05 03:29:04 owner_manager.go:180: [info] [ddl] /tidb/ddl/bg/owner ownerManager 70fcedb3-c1d9-417e-881c-92f2dd5dde38 etcd session is done, creates a new one
2017/08/05 03:29:04 domain.go:332: [info] [ddl] reload schema in loop, schema syncer need restart
2017/08/05 03:29:04 schema_validator.go:70: [info] the schema validator stops
2017/08/05 03:29:04 coprocessor.go:323: [info] [TIME_COP_TASK] 518.00294ms region(2 1 1) ranges(1) store(127.0.0.1:20160)
2017/08/05 03:29:04 adapter.go:237: [warning] [0][TIME_QUERY] 518.182236ms select Host,DB,User,Table_name,Grantor,Timestamp,Table_priv,Column_priv from mysql.tables_priv
2017/08/05 03:29:04 schema_validator.go:185: [info] the schema validator stopped before checking
2017/08/05 03:29:04 schema_validator.go:154: [info] the schema validator stopped before judging
2017/08/05 03:29:04 domain.go:495: [info] [domain] reload privilege success.
ERRO[11385] [pd] failed updateLeader: failed to get leader from [http://127.0.0.1:2379]
2017/08/05 03:29:04 schema_validator.go:80: [info] the schema validator restarts
ERRO[11386] [pd] getTS error: rpc error: code = Unknown desc = rpc error: code = Unavailable desc = not leader
2017/08/05 03:29:04 pd.go:124: [error] updateTS error: rpc error: code = Unknown desc = rpc error: code = Unavailable desc = not leader
ERRO[11386] [pd] getTS error: rpc error: code = Unknown desc = rpc error: code = Unavailable desc = not leader
2017/08/05 03:29:04 owner_manager.go:251: [info] [ddl] /tidb/ddl/fg/owner ownerManager is 70fcedb3-c1d9-417e-881c-92f2dd5dde38, owner is 70fcedb3-c1d9-417e-881c-92f2dd5dde38
2017/08/05 03:29:04 owner_manager.go:251: [info] [ddl] /tidb/ddl/bg/owner ownerManager is 70fcedb3-c1d9-417e-881c-92f2dd5dde38, owner is 70fcedb3-c1d9-417e-881c-92f2dd5dde38
2017/08/05 03:29:05 schema_validator.go:158: [info] the schema validator's latest schema version 0 is expired
2017/08/05 03:29:05 schema_validator.go:158: [info] the schema validator's latest schema version 0 is expired
2017/08/05 03:29:06 schema_validator.go:158: [info] the schema validator's latest schema version 0 is expired
2017/08/05 03:29:06 schema_validator.go:158: [info] the schema validator's latest schema version 0 is expired
2017/08/05 03:29:07 schema_validator.go:158: [info] the schema validator's latest schema version 0 is expired
2017/08/05 03:29:07 schema_validator.go:158: [info] the schema validator's latest schema version 0 is expired
2017/08/05 03:29:08 schema_validator.go:158: [info] the schema validator's latest schema version 0 is expired
2017/08/05 03:29:08 schema_validator.go:158: [info] the schema validator's latest schema version 0 is expired
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1872bfc]

goroutine 214 [running]:
github.com/pingcap/tidb/domain.(*schemaValidator).Update(0xc420072280, 0x576bae42b140003, 0xd, 0xd, 0x0, 0x0, 0x0)
	/Users/rainli/goprojs/src/github.com/pingcap/tidb/domain/schema_validator.go:111 +0x56c
github.com/pingcap/tidb/domain.(*Domain).Reload(0xc420366480, 0x0, 0x0)
	/Users/rainli/goprojs/src/github.com/pingcap/tidb/domain/domain.go:299 +0x318
github.com/pingcap/tidb/domain.(*Domain).loadSchemaInLoop(0xc420366480, 0x2540be400)
	/Users/rainli/goprojs/src/github.com/pingcap/tidb/domain/domain.go:321 +0x192
created by github.com/pingcap/tidb/domain.NewDomain
	/Users/rainli/goprojs/src/github.com/pingcap/tidb/domain/domain.go:443 +0x4aa
```

**Comment by shenli** [comment]
@zimulala Any progress about this issue?

**Comment by blacktear23** [comment]
@shenli my PR is merged. Just add a nil check for cache item update.

**Comment by tiancaiamao** [comment]
Make a reference to the PR and this issue, so when it's merged, we can close this issue. @blacktear23
