### ISSUE TITLE
GC was blocked when doing network chaos on TiKV

### ISSUE THREAD

**Issue by shuke987** [pingcap/tidb#40643]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. start an instance
2. do a network chaos on TiKV
3. GC blocked until tikv network chaos were removed

root cause：
1. TiDB will get all tikv's confige through internalClient
2. internalClient will keepalive when once called TiKV
3. When tikv host's iptable was changed ( to do a network chaos ), request data was dropped.
4. TiDB blocks at https://github.com/pingcap/tidb/blob/2d755a818c8802cf8fb9f2516ae20c9da3b84fdb/executor/memtable_reader.go#L206

sugest fix:
1. add a timeout to internalClient, maybe 2 minute. ( due to the way we simulate network chaos is rarely appearing at customer's env )

### 2. What did you expect to see? (Required)
GC goes on

### 3. What did you see instead (Required)
no

### 4. What is your TiDB version? (Required)
v6.5.0

**Comment by King-Dylan** [comment]
Find the same symptom from the other customer.
```
goroutine 8559417287 [chan receive, 2472 minutes]:
github.com/pingcap/tidb/pkg/executor.(*ProjectionExec).parallelExecute(0xc01c52d800, {0x67aa028?, 0xc001243170?}, 0xc0ca899270)
	/mnt/tidb/sql/pkg/executor/projection.go:223 +0x92
github.com/pingcap/tidb/pkg/executor.(*ProjectionExec).Next(0xc01c52d800, {0x67aa028, 0xc001243170}, 0x1?)
	/mnt/tidb/sql/pkg/executor/projection.go:187 +0x71
github.com/pingcap/tidb/pkg/executor/internal/exec.Next({0x67aa028, 0xc001243170}, {0x67d2d20, 0xc01c52d800}, 0xc0ca899270)
	/mnt/tidb/sql/pkg/executor/internal/exec/executor.go:403 +0x2c3
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next(0xc089c082d0, {0x67aa028, 0xc001243170}, {0x67d2d20, 0xc01c52d800}, 0x1?)
	/mnt/tidb/sql/pkg/executor/adapter.go:1209 +0x6e
github.com/pingcap/tidb/pkg/executor.(*recordSet).Next(0xc0f1060000, {0x67aa028?, 0xc001243170?}, 0xc0ca899270)
	/mnt/tidb/sql/pkg/executor/adapter.go:158 +0xbb
github.com/pingcap/tidb/pkg/util/sqlexec.DrainRecordSet({0x67aa028, 0xc001243170}, {0x67aaa18, 0xc032191440}, 0x66?)
	/mnt/tidb/sql/pkg/util/sqlexec/restricted_sql_executor.go:221 +0xc3
github.com/pingcap/tidb/pkg/ddl/util.IsRaftKv2({0x67aa028, 0xc001243170}, {0x6826138, 0xc37939f8c0})
	/mnt/tidb/sql/pkg/ddl/util/util.go:395 +0x150
github.com/pingcap/tidb/pkg/store/gcworker.(*GCWorker).deleteRanges(0xc000b96d80, {0x67aa028, 0xc001243170}, 0x657bbde03e80000?, 0x73)
	/mnt/tidb/sql/pkg/store/gcworker/gc_worker.go:815 +0x1cd
github.com/pingcap/tidb/pkg/store/gcworker.(*GCWorker).runGCJob(0xc000b96d80, {0x67aa028, 0xc001243170}, 0x400?, 0x0?)
	/mnt/tidb/sql/pkg/store/gcworker/gc_worker.go:763 +0x7e5
github.com/pingcap/tidb/pkg/store/gcworker.(*GCWorker).leaderTick.func1()
	/mnt/tidb/sql/pkg/store/gcworker/gc_worker.go:420 +0x2c
created by github.com/pingcap/tidb/pkg/store/gcworker.(*GCWorker).leaderTick in goroutine 746
	/mnt/tidb/sql/pkg/store/gcworker/gc_worker.go:419 +0xb6d
```

**Comment by xhebox** [comment]
The stack can prove it is indeed a bug. `IsRaftKv2` will invoke `memtable_reader` eventually. And the internal HTTP client has no timeout at all, which blocked the parallel executor.

I'll give a fix. Adding a reasonable timeout is better than waiting `2472 minutes`.
