### ISSUE TITLE
br: br debug encode panic

### ISSUE THREAD

**Issue by MoCuishle28** [pingcap/tidb#40878]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- br backup full
- br debug decode
- br debug encode
- panic

### 2. What did you expect to see? (Required)
Successfully encode and generate file `backupmeta_from_json` in target bucket.

### 3. What did you see instead (Required)
panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2bf863b]

goroutine 1 [running]:
github.com/pingcap/tidb/br/pkg/utils.fromJSONSchema(0xc000fb4990)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/utils/json.go:118 +0x3b
github.com/pingcap/tidb/br/pkg/utils.fromJSONBackupMeta(0xc000dbea80)
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/utils/json.go:167 +0x88
github.com/pingcap/tidb/br/pkg/utils.UnmarshalBackupMeta({0xc0010ca000, 0x3200b, 0x36000})
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/utils/json.go:28 +0x78
main.encodeBackupMetaCommand.func1(0xc0003bd900?, {0xc000a106c0?, 0x4?, 0x4?})
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/debug.go:342 +0x132
github.com/spf13/cobra.(*Command).execute(0xc0003bd900, {0xc00004e0a0, 0x4, 0x4})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003bca00)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/main.go:57 +0x325
```

### 4. What is your TiDB version? (Required)

v6.1.0

**Comment by MoCuishle28** [comment]
/affects-6.1

**Comment by MoCuishle28** [comment]
affects-6.1
