### ISSUE TITLE
WaitGroupEnhancedWrapper received duplicated source process

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#40870]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
panic: WaitGroupEnhancedWrapper received duplicated source process [recovered]

	panic: WaitGroupEnhancedWrapper received duplicated source process


goroutine 5548 [running]:

testing.tRunner.func1.2({0x62c0220, 0xc00107f730})

	GOROOT/src/testing/testing.go:1396 +0x372

testing.tRunner.func1()

	GOROOT/src/testing/testing.go:1399 +0x5f0

panic({0x62c0220, 0xc00107f730})

	GOROOT/src/runtime/panic.go:890 +0x262

go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0xc005df0b60, {0xad33c14?, 0x40?, 0xc005e48380?})

	external/org_uber_go_zap/zapcore/entry.go:198 +0xa8

go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc005df0b60, {0xc0057d7780, 0x2, 0x2})

	external/org_uber_go_zap/zapcore/entry.go:264 +0x586

go.uber.org/zap.(*Logger).Panic(0xd05ce00?, {0x6a5b781, 0x3b}, {0xc0057d7780, 0x2, 0x2})

	external/org_uber_go_zap/logger.go:258 +0x6e

github.com/pingcap/tidb/util.(*WaitGroupEnhancedWrapper).onStart(0xc00061f590, {0x69cc6fc, 0x1a})

	util/wait_group_wrapper.go:125 +0x2a8

github.com/pingcap/tidb/util.(*WaitGroupEnhancedWrapper).Run(0xc00061f590, 0xc005f143e0, {0x69cc6fc, 0x1a})

	util/wait_group_wrapper.go:89 +0x4a

github.com/pingcap/tidb/domain.(*Domain).globalBindHandleWorkerLoop(0xc000315500, {0x81d2b68?, 0xc005f18960})

	domain/domain.go:1529 +0x113

github.com/pingcap/tidb/domain.(*Domain).LoadBindInfoLoop(0xc000315500, {0x82254e0, 0xc005ed2280}, {0x82254e0, 0xc005ed2500})

	domain/domain.go:1523 +0x205

github.com/pingcap/tidb/session.BootstrapSession({0x81e2380, 0xc0004e4660})

	session/session.go:3324 +0x5a9

github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndDomainAndSetup(0xc0061201a0, {0x0, 0x0, 0x0})

	tests/realtikvtest/testkit.go:105 +0x17a

github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndSetup(...)

	tests/realtikvtest/testkit.go:81

tests/realtikvtest/txntest/txntest_test.TestP1DirtyRead(0x0?)

	tests/realtikvtest/txntest/isolation_test.go:89 +0x4a

testing.tRunner(0xc0061201a0, 0x6adddd8)

	GOROOT/src/testing/testing.go:1446 +0x217

created by testing.(*T).Run

	GOROOT/src/testing/testing.go:1493 +0x75e

```

**Comment by zimulala** [comment]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/20818/pipeline/274/

**Comment by D3Hunter** [comment]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/7147/pipeline/408
```
        	Error Trace:	pkg/testkit/testkit.go:139
        	            				pkg/testkit/testkit.go:132
        	            				tests/realtikvtest/testkit.go:141
        	            				tests/realtikvtest/testkit.go:99
        	            				tests/realtikvtest/txntest/isolation_test.go:47
        	Error:      	Received unexpected error:
        	            	[schema:1051]Unknown table 'test.t'
        	            	github.com/pingcap/errors.AddStack
        	            		external/com_github_pingcap_errors/errors.go:178
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext
        	            		pkg/testkit/testkit.go:383
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExecWithContext
        	            		pkg/testkit/testkit.go:137
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExec
        	            		pkg/testkit/testkit.go:132
        	            	github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndDomainAndSetup
        	            		tests/realtikvtest/testkit.go:141
        	            	github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndSetup
        	            		tests/realtikvtest/testkit.go:99
        	            	tests/realtikvtest/txntest/txntest_test.TestP0DirtyWrite
        	            		tests/realtikvtest/txntest/isolation_test.go:47
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1595
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1650
        	Test:       	TestP0DirtyWrite
        	Messages:   	sql:drop table `t`, [], error stack [schema:1051]Unknown table 'test.t'
        	            	github.com/pingcap/errors.AddStack
        	            		external/com_github_pingcap_errors/errors.go:178
        	            	github.com/pingcap/errors.Trace
        	            		external/com_github_pingcap_errors/juju_adaptor.go:15
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).ExecWithContext
        	            		pkg/testkit/testkit.go:383
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExecWithContext
        	            		pkg/testkit/testkit.go:137
        	            	github.com/pingcap/tidb/pkg/testkit.(*TestKit).MustExec
        	            		pkg/testkit/testkit.go:132
        	            	github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndDomainAndSetup
        	            		tests/realtikvtest/testkit.go:141
        	            	github.com/pingcap/tidb/tests/realtikvtest.CreateMockStoreAndSetup
        	            		tests/realtikvtest/testkit.go:99
        	            	tests/realtikvtest/txntest/txntest_test.TestP0DirtyWrite
        	            		tests/realtikvtest/txntest/isolation_test.go:47
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1595
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1650
```
