### ISSUE TITLE
Lightning panic when split regions

### ISSUE THREAD

**Issue by gozssky** [pingcap/tidb#40934]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Use tidb-lightning to import a table whose primary key is not an integer. The size of the table is hundreds of GB, and the data is sorted according to the primary key.

### 2. What did you expect to see? (Required)
Import successfully.

### 3. What did you see instead (Required)
```
2023-01-31 16:26:26 | /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/table_restore.go:322 +0xfaa
2023-01-31 16:26:26 | created by github.com/pingcap/tidb/br/pkg/lightning/restore.(*TableRestore).restoreEngines
2023-01-31 16:26:26 | /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/table_restore.go:331 +0x2db
2023-01-31 16:26:26 | github.com/pingcap/tidb/br/pkg/lightning/restore.(*TableRestore).restoreEngines.func3(0x1868776?, 0x4, 0xc001078180)
2023-01-31 16:26:26 | /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/table_restore.go:698 +0x45
2023-01-31 16:26:26 | github.com/pingcap/tidb/br/pkg/lightning/restore.(*TableRestore).importEngine(0xc0011dbe60?, {0x4cfa588?, 0xc001f8c440}, 0x0?, 0xc000bd51e0, 0x0?, 0x0?)
2023-01-31 16:26:26 | /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/restore/table_restore.go:997 +0x1d9
2023-01-31 16:26:26 | github.com/pingcap/tidb/br/pkg/lightning/restore.(*TableRestore).importKV(0xc0012d8c80, {0x4cfa588, 0xc001f8c440}, 0xc0820f7a70, 0xc000bd51e0, 0x72dd020?)
2023-01-31 16:26:26 | /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/backend.go:477 +0x21e
2023-01-31 16:26:26 | github.com/pingcap/tidb/br/pkg/lightning/backend.(*ClosedEngine).Import(0xc0820f7a70, {0x4cfa588, 0xc001f8c440}, 0xc00ef8bfe0?, 0x173f439?)
2023-01-31 16:26:26 | /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/local.go:1619 +0x1414
2023-01-31 16:26:26 | github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*local).ImportEngine(0xc0005f9b80, {0x4cfa588, 0xc001f8c440}, {0xc3, 0x23, 0xfe, 0xb5, 0x7b, 0xe2, 0x55, ...}, ...)
2023-01-31 16:26:26 | /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/localhelper.go:79 +0x105
2023-01-31 16:26:26 | github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*local).SplitAndScatterRegionInBatches(0x4606d3e?, {0x4cfa588, 0xc001f8c440}, {0xc00eb14000, 0x4c3, 0x4da}, 0xc08a139530?, 0x2d?, 0x0?, 0x1000)
2023-01-31 16:26:26 | /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/localhelper.go:327 +0x1d7a
2023-01-31 16:26:26 | github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*local).SplitAndScatterRegionByRanges(0xc0005f9b80, {0x4cfa588?, 0xc001f8c440}, {0xc00eb14000, 0x4c3, 0x5462093?}, 0xc00145d4d0, 0x1, 0x6000000)
2023-01-31 16:26:26 | /home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/lightning/backend/local/local.go:2009 +0x77
2023-01-31 16:26:26 | github.com/pingcap/tidb/br/pkg/lightning/backend/local.nextKey({0xc039401d40, 0x0?, 0x100763?})
2023-01-31 16:26:26 | goroutine 986 [running]:
2023-01-31 16:26:26 |  
2023-01-31 16:26:26 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x3315ef7]
2023-01-31 16:26:26 | panic: runtime error: invalid memory address or nil pointer dereference

```

### 4. What is your TiDB version? (Required)

v6.5.0

**Comment by gozssky** [comment]
This is related to https://github.com/pingcap/br/issues/1213#issuecomment-865168482. The root cause is lightning call `nextKey` on a key that is already the result of `nextKey`. 
https://github.com/pingcap/tidb/blob/d6302c1144a1ef68c83d731eea332455af18d9a1/br/pkg/lightning/backend/local/localhelper.go#L327
