### ISSUE TITLE
flaky test TestGlobalMemoryControl

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#41474]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
--- FAIL: TestGlobalMemoryControl (6.17s)
panic: interface conversion: interface {} is nil, not string [recovered]
	panic: interface conversion: interface {} is nil, not string

goroutine 131854 [running]:
testing.tRunner.func1.2({0x4c5e3a0, 0xc0005dee40})
	GOROOT/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1399 +0x39f
panic({0x4c5e3a0, 0xc0005dee40})
	GOROOT/src/runtime/panic.go:884 +0x212
github.com/pingcap/tidb/executor_test.TestGlobalMemoryControl.func4({0x0?, 0x0?})
	executor/executor_test.go:6284 +0x86
github.com/pingcap/tidb/util.WithRecovery.func1()
	util/misc.go:88 +0x6c
github.com/pingcap/tidb/util.WithRecovery(0x1dcd6500?, 0xc0435ab900?)
	util/misc.go:97 +0x7a
github.com/pingcap/tidb/executor_test.TestGlobalMemoryControl(0xc028e60ea0)
	executor/executor_test.go:6280 +0x712
testing.tRunner(0xc028e60ea0, 0x53ce8c0)
	GOROOT/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:1493 +0x35f
--
Coverage runner: Not collecting coverage for failed test.
The following commands failed with status 2
```

**Comment by yinsustart** [comment]
Close it because it has not been reproduced for more than 1 month.
