### ISSUE TITLE
`fatal error: concurrent map writes` during graceful shutdown

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#41754]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Fatal error occurred during graceful shutdown
``` shell
fatal error: concurrent map writes

goroutine 8944 [running]:
github.com/pingcap/tidb/server.(*TiDBStatement).Close(0xc0325067e0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:185 +0x26f
github.com/pingcap/tidb/parser/terror.Call(0xc005689a98?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:306 +0x31
github.com/pingcap/tidb/server.(*TiDBContext).Close(0xc08cc73d10)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:265 +0x90
github.com/pingcap/tidb/server.closeConn(0xc0274d5800, 0xc000f8ae70?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:357 +0x1dc
github.com/pingcap/tidb/server.(*clientConn).Close(0xc0274d5800)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:341 +0x89
github.com/pingcap/tidb/server.(*Server).kickIdleConnection(0xc001e7ac00)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:872 +0x1de
github.com/pingcap/tidb/server.(*Server).GracefulDown(0x0?, {0x4fb0ba0, 0xc000120000}, 0x3ebce60?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:840 +0xf8
main.cleanup(0xc001e7ac00?, {0x4fda650, 0xc000754910}, 0x0?, 0x0?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:824 +0x5a
main.main.func1(0x0?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:225 +0x6f
github.com/pingcap/tidb/util/signal.SetupSignalHandler.func2()
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/signal/signal_posix.go:55 +0x1e5
created by github.com/pingcap/tidb/util/signal.SetupSignalHandler
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/signal/signal_posix.go:52 +0x19f
```

[full goroutine.txt](https://github.com/pingcap/tidb/files/10837469/goroutine.txt)

### 4. What is your TiDB version? (Required)

83e55ee662e143ee30b611d52a154c3fc18ec5cf

**Comment by fubinzh** [comment]
This issue still seen with latest master. [tidb.panic.txt](https://github.com/pingcap/tidb/files/14798026/tidb.panic.txt)


Release Version: v8.0.0-alpha-663-g8d9e67b
Edition: Community
Git Commit Hash: 8d9e67b37dea759db0980aeddf4da967bf93e83e
Git Branch: HEAD
UTC Build Time: 2024-03-28 13:24:05
GoVersion: go1.21.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by bb7133** [comment]
Close it since I believe it has been fixed after some refactorings of shutdown logic and https://github.com/pingcap/tidb/pull/49073
