### ISSUE TITLE
import data to a TTL table with lightning will panic

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#42012]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

import data to a TTL table with lightning

### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x110 pc=0x10409fc68]

goroutine 349 [running]:
github.com/pingcap/tidb/table/tables.(*TableCommon).AddRecord(0x14000afaa20, {0x106253ca8, 0x140014e0100}, {0x14000e3c0e0, 0x2, 0x3}, {0x0, 0x0, 0x14000fb3118?})
        /Users/wangchao/Code/pingcap/tidb/table/tables/tables.go:934 +0x1798
github.com/pingcap/tidb/br/pkg/lightning/backend/kv.(*tableKVEncoder).Encode(0x1400100dd40, {0x14000b7f600?}, {0x1400016c480?, 0x2, 0x10}, 0x1, {0x14001138900, 0x3, 0x14000fb34b8?}, {0x102b945dc?, ...}, ...)
        /Users/wangchao/Code/pingcap/tidb/br/pkg/lightning/backend/kv/sql2kv.go:425 +0x89c
github.com/pingcap/tidb/br/pkg/lightning/importer.(*chunkProcessor).encodeLoop(0x14000673700, {0x1061ed1c8, 0x1400029c870}, 0xc?, 0x14001025300, {0x102b35654?}, {0x1061d4330, 0x1400100dd40}, 0x58?, 0x14000e3e820)
        /Users/wangchao/Code/pingcap/tidb/br/pkg/lightning/importer/chunk_process.go:314 +0xa58
github.com/pingcap/tidb/br/pkg/lightning/importer.(*chunkProcessor).process(0x14000673700, {0x1061ed1c8, 0x1400029c870}, 0x14001025300, 0x0, 0x14000673720, 0x14000673740, 0x14000e3e820)
        /Users/wangchao/Code/pingcap/tidb/br/pkg/lightning/importer/chunk_process.go:179 +0x4cc
github.com/pingcap/tidb/br/pkg/lightning/importer.(*TableImporter).preprocessEngine.func4(0x0?, 0x14000673700)
        /Users/wangchao/Code/pingcap/tidb/br/pkg/lightning/importer/table_import.go:704 +0x14c
created by github.com/pingcap/tidb/br/pkg/lightning/importer.(*TableImporter).preprocessEngine
        /Users/wangchao/Code/pingcap/tidb/br/pkg/lightning/importer/table_import.go:694 +0xb64
```

### 4. What is your TiDB version? (Required)

master and 6.6.0

**Comment by lcwangchao** [comment]
The bug is introduced by #41155 . When importing data, lightning is using a different `sessionctx.Context` without `TxnCtx` in it.
