### ISSUE TITLE
Unstable test TestColumnAdd

### ISSUE THREAD

**Issue by MyonKeminta** [pingcap/tidb#42429]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x47d1cd1]

goroutine 25373 [running]:
github.com/pingcap/tidb/ddl_test.checkAddPublic({0x5ba4120, 0xc004c6d710}, {0x0, 0x0}, {0x5b61b18?, 0xc000e63440?})
	ddl/column_change_test.go:318 +0x1b1
github.com/pingcap/tidb/ddl_test.TestColumnAdd.func1(0xc005034900)
	ddl/column_change_test.go:81 +0x226
github.com/pingcap/tidb/ddl/internal/callback.(*TestDDLCallback).OnJobUpdated(0xc005bf90e0, 0xc005034900?)
	ddl/internal/callback/callback.go:122 +0x1ea
github.com/pingcap/tidb/ddl.(*ddl).delivery2worker.func1()
	ddl/job_table.go:314 +0xdef
github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
	util/wait_group_wrapper.go:154 +0x6b
created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run
	util/wait_group_wrapper.go:152 +0x8d
```

### 4. What is your TiDB version? (Required)

master (8ba2035203f75a3b901e7e465aba01077993cef0)

**Comment by wjhuang2016** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/49827
