### ISSUE TITLE
invalid memory address in the TestColumnAdd

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#42600]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x6385cc2]
goroutine 27178 [running]:
github.com/pingcap/tidb/ddl_test.checkAddPublic({0x88564a0, 0xc0079b8360}, {0x0, 0x0}, {0x8813e98?, 0xc00802c900?})
	ddl/column_change_test.go:318 +0x1c2
github.com/pingcap/tidb/ddl_test.TestColumnAdd.func1(0xc005c59320)
	ddl/column_change_test.go:81 +0x27c
github.com/pingcap/tidb/ddl/internal/callback.(*TestDDLCallback).OnJobUpdated(0xc008189bc0, 0xc005c59320?)
	ddl/internal/callback/callback.go:122 +0x211
github.com/pingcap/tidb/ddl.(*ddl).delivery2worker.func1()
	ddl/job_table.go:314 +0x1162
github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
	util/wait_group_wrapper.go:154 +0x74
created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run
	util/wait_group_wrapper.go:152 +0xe5 
```

https://prow.hawkingrei.com/view/gs/prowpingcap/logs/tidb_race/1640171920198471680

**Comment by D3Hunter** [comment]
duplicate with https://github.com/pingcap/tidb/issues/42429
