### ISSUE TITLE
unstable test TestIndexMergeCoprGoroutinesLeak 

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#42681]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
make failpoint-enable
cd executor
go test -tags intest -run TestIndexMergeCoprGoroutinesLeak
```

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

```
--- FAIL: TestIndexMergeCoprGoroutinesLeak (0.82s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x475f071]

goroutine 40 [running]:
testing.tRunner.func1.2({0x4cd7ac0, 0x7bb85e0})
        /home/genius/project/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /home/genius/project/go/src/testing/testing.go:1529 +0x39f
panic({0x4cd7ac0, 0x7bb85e0})
        /home/genius/project/go/src/runtime/panic.go:884 +0x213
github.com/pingcap/tidb/executor_test.TestIndexMergeCoprGoroutinesLeak(0x18b2af9?)
        /home/genius/project/src/github.com/pingcap/tidb/executor/index_merge_reader_test.go:932 +0x291
testing.tRunner(0xc0005529c0, 0x54651b0)
        /home/genius/project/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /home/genius/project/go/src/testing/testing.go:1629 +0x3ea
exit status 2
FAIL    github.com/pingcap/tidb/executor        0.866s
```

### 4. What is your TiDB version? (Required)

master af62a5cd0ac6e913bcc6c869a3b15378aa7bd31f

**Comment by tiancaiamao** [comment]
can't reproduce

I remove tools/bin/failpoint-ctl and then `make failpoint-enable` again, the issue is gone.
