### ISSUE TITLE
panic on TestMetaTableRegion

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#42743]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/21065/pipeline

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]

	panic: runtime error: invalid memory address or nil pointer dereference [recovered]

	panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x57a2b1c]



goroutine 110763 [running]:

testing.tRunner.func1.2({0x6a31000, 0xa52cc80})

	GOROOT/src/testing/testing.go:1526 +0x372

testing.tRunner.func1()

	GOROOT/src/testing/testing.go:1529 +0x650

panic({0x6a31000, 0xa52cc80})

	GOROOT/src/runtime/panic.go:890 +0x263

github.com/pingcap/tidb/executor.(*ExecStmt).Exec.func1()

	executor/adapter.go:459 +0x90b

panic({0x6a31000, 0xa52cc80})

	GOROOT/src/runtime/panic.go:890 +0x263

github.com/pingcap/tidb/domain.(*Domain).getTimestampForSchemaVersionWithNonEmptyDiff(0xc025258d00, 0xc026fdcd68?, 0x7494583c5?)

	domain/domain.go:285 +0x13c

github.com/pingcap/tidb/domain.(*Domain).loadInfoSchema(0xc025258d00, 0x6f9cd2a?)

	domain/domain.go:207 +0xe5

github.com/pingcap/tidb/domain.(*Domain).Reload(0xc025258d00)

	domain/domain.go:551 +0x28d

github.com/pingcap/tidb/ddl.(*DefaultCallback).OnChanged(0xc02527e8d0, {0x0, 0x0})

	ddl/callback.go:130 +0xc9

github.com/pingcap/tidb/ddl.(*ddl).callHookOnChanged(0xc02534c080, 0xc025b24900, {0x0, 0x0})

	ddl/ddl.go:1186 +0x194

github.com/pingcap/tidb/ddl.(*ddl).CreateTableWithInfo(0xc02589d500?, {0x84e5150, 0xc02538e780}, {{0xc0256fa73b?, 0x0?}, {0xc0256fa74b?, 0x0?}}, 0x1a4af65?, {0xc025bb99b0, 0x1, ...})

	ddl/ddl_api.go:2552 +0x2fb

github.com/pingcap/tidb/ddl.(*ddl).CreateTable(0x84e5150?, {0x84e5150, 0xc02538e780}, 0xc01d44fee0)

	ddl/ddl_api.go:2391 +0x77a

github.com/pingcap/tidb/executor.(*DDLExec).executeCreateTable(0xc025bce580, 0xc025be4060?)

	executor/ddl.go:264 +0xd0

github.com/pingcap/tidb/executor.(*DDLExec).Next(0xc025bce580, {0x84746b0, 0xc025be4030}, 0x16?)

	executor/ddl.go:156 +0x5cc

github.com/pingcap/tidb/executor.Next({0x84746b0, 0xc025be4030}, {0x8477ba0, 0xc025bce580}, 0xc01d45bb80)

	executor/executor.go:326 +0x376

github.com/pingcap/tidb/executor.(*ExecStmt).next(0xc01d40af00, {0x84746b0, 0xc025be4030}, {0x8477ba0, 0xc025bce580}, 0x1?)

	executor/adapter.go:1199 +0x9e

github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc01d40af00, {0x84746b0, 0xc025be4030}, {0x8477ba0?, 0xc025bce580})

	executor/adapter.go:944 +0x57d

github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc01d40af00, {0x84746b0, 0xc025be4030}, {0x8477ba0, 0xc025bce580?}, 0x0)

	executor/adapter.go:769 +0x405

github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc01d40af00, {0x84746b0, 0xc025be4030})

	executor/adapter.go:564 +0x1167

github.com/pingcap/tidb/session.runStmt({0x84746b0, 0xc01d471c50}, 0xc02538e780, {0x8484f70, 0xc01d40af00?})

	session/session.go:2343 +0x702

github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc02538e780, {0x84746b0, 0xc01d471c50}, {0x848bda8?, 0xc01d44fee0?})

	session/session.go:2200 +0x12e7

github.com/pingcap/tidb/session.(*session).ExecuteInternal(0xc02538e780, {0x84746b0, 0xc01d471c50}, {0x71013bd, 0x903}, {0x0, 0x0, 0x0})

	session/session.go:1638 +0x366

github.com/pingcap/tidb/session.mustExecute({0x84ed6b8, 0xc02538e780}, {0x71013bd, 0x903}, {0x0, 0x0, 0x0})

	session/bootstrap.go:2705 +0x168

github.com/pingcap/tidb/session.doDDLWorks({0x84ed6b8, 0xc02538e780})

	session/bootstrap.go:2476 +0xf9

github.com/pingcap/tidb/session.bootstrap({0x84ed6b8, 0xc02538e780})

	session/bootstrap.go:615 +0x4da

github.com/pingcap/tidb/session.runInBootstrapSession({0x84a2c38, 0xc01db3a900}, 0x7145670)

	session/session.go:3492 +0x27e

github.com/pingcap/tidb/session.BootstrapSession({0x84a2c38, 0xc01db3a900})

	session/session.go:3272 +0x326

github.com/pingcap/tidb/testkit.bootstrap({0x84a5e40?, 0xc021824820}, {0x84a2c38?, 0xc01db3a900}, 0x0?)

	testkit/mockstore.go:85 +0x85

github.com/pingcap/tidb/testkit.CreateMockStoreAndDomain({0x84a5e40?, 0xc021824820}, {0x0, 0x0, 0x0})

	testkit/mockstore.go:70 +0xd1

github.com/pingcap/tidb/testkit.CreateMockStore({0x84a5e40, 0xc021824820}, {0x0, 0x0, 0x0})

	testkit/mockstore.go:62 +0x3b3

github.com/pingcap/tidb/session_test.TestMetaTableRegion(0x0?)

	session/session_test.go:72 +0xe5

testing.tRunner(0xc021824820, 0x7145b80)

	GOROOT/src/testing/testing.go:1576 +0x217

created by testing.(*T).Run

	GOROOT/src/testing/testing.go:1629 +0x806

--
```

**Comment by Defined2014** [comment]
Maybe same as https://github.com/pingcap/tidb/issues/42742

**Comment by xhebox** [comment]
/close
Duplicated of #42742
