### ISSUE TITLE
Panic triggered at core.(*expressionRewriter).toColumn (planner/core/expression_rewriter.go:1737)

### ISSUE THREAD

**Issue by JZuming** [pingcap/tidb#42958]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

**Setup the database:**

```
CREATE TABLE t2 (vkey int, pkey int);
CREATE TABLE t6 (pkey int, c23 int);
```

**Testcase**
```
select
  LAST_VALUE(case when (ref_0.vkey > (
                                  select
                                      ref_13.c23 as c0
                                    from
                                      t6 as ref_13
                                    order by c0 desc
                                     limit 1)
                          ) then 1 else 0 end
                        ) over (partition by ref_0.pkey) as c2
from
  t2 as ref_0;
```

### 2. What did you expect to see? (Required)

No panic.

### 3. What did you see instead (Required)

```
ERROR 1105 (HY000): runtime error: index out of range [1] with length 1
```
TiDB log:
```
[ERROR] [conn.go:736] ["connection running loop panic"] [conn=127] [lastSQL="select  
  LAST_VALUE(case when (ref_0.vkey > ( 
                                  select  
                                      ref_13.c23 as c0
                                    from 
                                      t6 as ref_13
                                    order by c0 desc
                                     limit 1)
                          ) then 1 else 0 end
            ) over (partition by ref_0.pkey) as c2
from 
  t2 as ref_0"] [err="runtime error: index out of range [1] with length 1"] [stack="goroutine 43055 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1()
    /root/tidb/server/conn.go:734 +0x8f
panic({0x34dd6c0, 0xc01278a480})
    /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/pingcap/tidb/planner/core.(*expressionRewriter).toColumn(0xc00fe8dba0, 0xc01260ed80)
    /root/tidb/planner/core/expression_rewriter.go:1737 +0xc7a
github.com/pingcap/tidb/planner/core.(*expressionRewriter).Leave(0xc00fe8dba0, {0x3b63a78?, 0xc01260ed80?})
    /root/tidb/planner/core/expression_rewriter.go:1050 +0x6f3
github.com/pingcap/parser/ast.(*ColumnName).Accept(0xc00fe8dba0?, {0x3b48dc0, 0xc00fe8dba0})
    /root/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210310110710-c7333a4927e6/ast/expressions.go:527 +0x65
github.com/pingcap/parser/ast.(*ColumnNameExpr).Accept(0xc000738500?, {0x3b48dc0, 0xc00fe8dba0})
    /root/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210310110710-c7333a4927e6/ast/expressions.go:589 +0x77
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode(0x50?, 0xc00fe8dba0, {0x3b71ee0?, 0xc000c2e3f0?}, 0x1)
    /root/tidb/planner/core/expression_rewriter.go:194 +0x129
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteWithPreprocess(0xc012d36d80, {0x3b59fa0?, 0xc01099ce70?}, {0x3b71ee0, 0xc000c2e3f0}, {0x3b838e0?, 0xc000738500?}, 0x0, 0x0, 0x1, ...)
    /root/tidb/planner/core/expression_rewriter.go:141 +0x173
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildProjection(0xc012d36d80, {0x3b59fa0, 0xc01099ce70}, {0x3b838e0, 0xc000738500?}, {0xc0008cc5e8, 0x1, 0x0?}, 0xc0158c9350?, 0x0, ...)
    /root/tidb/planner/core/logical_plan_builder.go:1234 +0x5d2
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect(0xc012d36d80, {0x3b59fa0, 0xc01099ce70}, 0xc011876400)
    /root/tidb/planner/core/logical_plan_builder.go:3446 +0xf45
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildResultSetNode(0xc0107eb130?, {0x3b59fa0?, 0xc01099ce70?}, {0x3b65410?, 0xc011876400?})
    /root/tidb/planner/core/logical_plan_builder.go:376 +0x1d0
github.com/pingcap/tidb/planner/core.(*expressionRewriter).buildSubquery(0xc00fe8dad0, {0x3b59fa0?, 0xc01099ce70?}, 0xc000c2e510?)
    /root/tidb/planner/core/expression_rewriter.go:324 +0x27d
github.com/pingcap/tidb/planner/core.(*expressionRewriter).handleScalarSubquery(0xc00fe8dad0, {0x3b59fa0, 0xc01099ce70}, 0xc000c2e360?)
    /root/tidb/planner/core/expression_rewriter.go:946 +0x4e
github.com/pingcap/tidb/planner/core.(*expressionRewriter).Enter(0xc00fe8dad0, {0x3b65848?, 0xc000c2e510?})
    /root/tidb/planner/core/expression_rewriter.go:391 +0x833
github.com/pingcap/parser/ast.(*SubqueryExpr).Accept(0xc00fe8dad0?, {0x3b48dc0, 0xc00fe8dad0})
    /root/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210310110710-c7333a4927e6/ast/expressions.go:384 +0x38
github.com/pingcap/parser/ast.(*BinaryOperationExpr).Accept(0xc00fe8dad0?, {0x3b48dc0, 0xc00fe8dad0})
    /root/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210310110710-c7333a4927e6/ast/expressions.go:212 +0xfa
github.com/pingcap/parser/ast.(*ParenthesesExpr).Accept(0xc00fe8dad0?, {0x3b48dc0, 0xc00fe8dad0})
    /root/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210310110710-c7333a4927e6/ast/expressions.go:988 +0x84
github.com/pingcap/parser/ast.(*WhenClause).Accept(0xc00fe8dad0?, {0x3b48dc0, 0xc00fe8dad0})
    /root/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210310110710-c7333a4927e6/ast/expressions.go:251 +0x7c
github.com/pingcap/parser/ast.(*CaseExpr).Accept(0xc012b5d340?, {0x3b48dc0, 0xc00fe8dad0})
    /root/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210310110710-c7333a4927e6/ast/expressions.go:340 +0x167
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode(0xc01099ce70?, 0xc00fe8dad0, {0x3b71e70?, 0xc015410420?}, 0x1)
    /root/tidb/planner/core/expression_rewriter.go:194 +0x129
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteWithPreprocess(0xc012d36d80, {0x3b59fa0?, 0xc01099ce70?}, {0x3b71e70, 0xc015410420}, {0x3b84290?, 0xc012b5d340?}, 0xc01099d1d0, 0x0, 0x1, ...)
    /root/tidb/planner/core/expression_rewriter.go:141 +0x173
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewrite(0xc01388c6d0?, "]
```

### 4. What is your TiDB version? (Required)

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.1.0-alpha-27-gf5ca27ef3
Edition: Community
Git Commit Hash: f5ca27ef326e94fb29b4ba35a5d59aa575f66880
Git Branch: master
UTC Build Time: 2023-03-23 13:57:53
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by AilinKid** [comment]
haven't reproduced it in master and https://github.com/pingcap/tidb/commit/f5ca27ef326e94fb29b4ba35a5d59aa575f66880

**Comment by JZuming** [comment]
Sorry for the false alarm. I checked it on another machine and it could not be reproduced. It seems I misconfigured something
