### ISSUE TITLE
unstable test TestMultiSchemaChangeAlterIndex

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#43231]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
    multi_schema_change_test.go:978: 

        	Error Trace:	ddl/multi_schema_change_test.go:978

        	            				ddl/internal/callback/callback.go:122

        	            				ddl/job_table.go:309

        	            				util/wait_group_wrapper.go:154

        	            				src/runtime/asm_amd64.s:1598

        	Error:      	Expected value not to be nil.

        	Test:       	TestMultiSchemaChangeAlterIndex

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x499fd06]


goroutine 316875 [running]:

github.com/pingcap/tidb/ddl_test.TestMultiSchemaChangeAlterIndex.func1(0xc0648ccdc0)

	ddl/multi_schema_change_test.go:980 +0x66

github.com/pingcap/tidb/ddl/internal/callback.(*TestDDLCallback).OnJobUpdated(0xc064f6a1e0, 0xc0648ccdc0?)

	ddl/internal/callback/callback.go:122 +0x1ea

github.com/pingcap/tidb/ddl.(*ddl).delivery2worker.func1()

	ddl/job_table.go:309 +0xdef

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x6b

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run

	util/wait_group_wrapper.go:152 +0x8d

--

Coverage runner: Not collecting coverage for failed test.

```

**Comment by hawkingrei** [comment]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/23275/pipeline
