### ISSUE TITLE
nil point panic in `session.session#TxnInfo()` method.

### ISSUE THREAD

**Issue by wuhuizuo** [pingcap/tidb#43829]
## Description

test failed in tispark [CI job](https://ci2.pingcap.net/blue/organizations/jenkins/tispark_ghpr_integration_test/detail/tispark_ghpr_integration_test/1428/pipeline/102/):

```log
[2023-05-15T08:42:18.237Z] [2023/05/15 16:41:38.033 +08:00] [INFO] [index_cop.go:230] ["[ddl-ingest] close cop-request sender pool"]
[2023-05-15T08:42:18.237Z] [2023/05/15 16:41:38.033 +08:00] [INFO] [index_cop.go:131] ["[ddl-ingest] start a cop-request task"] [id=1] [task="taskID: 1, physicalTableID: 225, range: [7480000000000000e15f72, 7480000000000000e15f73], jobID: 227"]
[2023-05-15T08:42:18.237Z] [2023/05/15 16:41:38.034 +08:00] [INFO] [backfilling_scheduler.go:478] ["[ddl-ingest] finish a cop-request task"] [id=1]
[2023-05-15T08:42:18.237Z] [2023/05/15 16:41:38.036 +08:00] [INFO] [backfilling.go:456] ["[ddl] backfill workers successfully processed"] [element=ID:1,TypeKey:_idx_] ["total added count"=0] ["start key"=]
[2023-05-15T08:42:18.237Z] [2023/05/15 16:41:38.036 +08:00] [INFO] [reorg.go:233] ["[ddl] run reorg job done"] ["handled rows"=0]
[2023-05-15T08:42:18.237Z] [2023/05/15 16:41:38.036 +08:00] [INFO] [domain.go:663] ["infoSyncerKeeper exited."]
[2023-05-15T08:42:18.237Z] [2023/05/15 16:41:38.036 +08:00] [INFO] [wait_group_wrapper.go:137] ["background process exited"] [source=domain] [process=infoSyncerKeeper]
[2023-05-15T08:42:18.237Z] [2023/05/15 16:41:38.036 +08:00] [INFO] [engine.go:121] ["[ddl-ingest] flush all writer and get closed engine"] ["job ID"=227] ["index ID"=1]
[2023-05-15T08:42:18.237Z] panic: runtime error: invalid memory address or nil pointer dereference
[2023-05-15T08:42:18.237Z] [signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x457b761]
[2023-05-15T08:42:18.237Z] 
[2023-05-15T08:42:18.237Z] goroutine 14160 [running]:
[2023-05-15T08:42:18.237Z] github.com/pingcap/tidb/session.(*session).TxnInfo(0xc0009d9180)
[2023-05-15T08:42:18.237Z] 	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/session/session.go:546 +0x141
[2023-05-15T08:42:18.237Z] github.com/pingcap/tidb/session.GetStartTSFromSession({0x506df20?, 0xc0009d9180?})
[2023-05-15T08:42:18.237Z] 	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/session/session.go:3814 +0xce
[2023-05-15T08:42:18.237Z] github.com/pingcap/tidb/server.(*Server).GetInternalSessionStartTSList(0xc0010527e0)
[2023-05-15T08:42:18.237Z] 	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/server/server.go:960 +0x20c
[2023-05-15T08:42:18.237Z] github.com/pingcap/tidb/domain/infosync.(*InfoSyncer).ReportMinStartTS(0xc001e765a0, {0x58f8fc8, 0xc00072f4a0})
[2023-05-15T08:42:18.237Z] 	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/domain/infosync/info.go:802 +0x82
[2023-05-15T08:42:18.237Z] github.com/pingcap/tidb/domain.(*Domain).infoSyncerKeeper(0xc00151d1e0)
[2023-05-15T08:42:18.237Z] 	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/domain/domain.go:671 +0x42a
[2023-05-15T08:42:18.237Z] github.com/pingcap/tidb/util.(*WaitGroupEnhancedWrapper).Run.func1()
[2023-05-15T08:42:18.237Z] 	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:96 +0x77
[2023-05-15T08:42:18.237Z] created by github.com/pingcap/tidb/util.(*WaitGroupEnhancedWrapper).Run
[2023-05-15T08:42:18.237Z] 	/home/jenkins/agent/workspace/build_tidb_multi_branch_master/go/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:91 +0xcc
```

detail log: 
- [tispark-CI-fail.log](https://github.com/pingcap/tidb/files/11476422/tispark-CI-fail.log)
- [tispark-ci-tidb.log](https://github.com/pingcap/tidb/files/11476501/tispark-ci-tidb.log)

## TiDB Version
- branch: master
- commit sha256: 6043234d98de5a87bd60d45e5f360060b34dd59b

## Information

It should judge the point before get the field from it.
Ref: https://github.com/pingcap/tidb/blob/6043234d98de5a87bd60d45e5f360060b34dd59b/session/session.go#L545-L546

**Comment by zimulala** [comment]
When running TiDB locally on a mac, kill TiDB by "ctrl+c" mostly has this problem.

**Comment by zimulala** [comment]
The possibility of panic caused by this PR(https://github.com/pingcap/tidb/pull/42897) is relatively greater
