### ISSUE TITLE
goleak from ttl

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#43855]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
[2023/05/16 11:21:48.999 +08:00] [INFO] [job_manager.go:369] ["failed to get TTL delay metrics"] [ttl-worker=job-manager] [error="context canceled"] [errorVerbose="context canceled\ngithub.com/pingcap/errors.AddStack\n\texternal/com_github_pingcap_errors/errors.go:174\ngithub.com/pingcap/errors.Trace\n\texternal/com_github_pingcap_errors/juju_adaptor.go:15\ngithub.com/pingcap/tidb/store/driver/error.ToTiDBErr\n\tstore/driver/error/error.go:186\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTaskOnce\n\tstore/copr/coprocessor.go:1189\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTask\n\tstore/copr/coprocessor.go:1105\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).run\n\tstore/copr/coprocessor.go:798\nruntime.goexit\n\tsrc/runtime/asm_amd64.s:1598"]

coverage: 15.0% of statements

goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 116744 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop on top of the stack:

goroutine 116744 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop(0xc034d6a7e0)

	ttl/ttlworker/scan.go:315 +0x19a

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc000f4f768?)

	ttl/ttlworker/worker.go:134 +0x85

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x6b

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run

	util/wait_group_wrapper.go:152 +0x8d


 Goroutine 116745 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop on top of the stack:

goroutine 116745 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop(0xc034d6a870)

	ttl/ttlworker/scan.go:315 +0x19a

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc005398f68?)

	ttl/ttlworker/worker.go:134 +0x85

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x6b

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run

	util/wait_group_wrapper.go:152 +0x8d


 Goroutine 116743 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop on top of the stack:

goroutine 116743 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop(0xc034d6a750)

	ttl/ttlworker/scan.go:315 +0x19a

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0x26c4dff?)

	ttl/ttlworker/worker.go:134 +0x85

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x6b

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run

	util/wait_group_wrapper.go:152 +0x8d


 Goroutine 116746 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop on top of the stack:

goroutine 116746 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*ttlScanWorker).loop(0xc034d6a900)

	ttl/ttlworker/scan.go:315 +0x19a

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0xc010d34f68?)

	ttl/ttlworker/worker.go:134 +0x85

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x6b

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run

	util/wait_group_wrapper.go:152 +0x8d


 Goroutine 116742 in state chan receive, with github.com/pingcap/tidb/ttl/client.(*mockClient).WatchCommand.func1 on top of the stack:

goroutine 116742 [chan receive]:

github.com/pingcap/tidb/ttl/client.(*mockClient).WatchCommand.func1()

	ttl/client/command.go:424 +0x5a

created by github.com/pingcap/tidb/ttl/client.(*mockClient).WatchCommand

	ttl/client/command.go:423 +0x30f


 Goroutine 116605 in state select, with github.com/pingcap/tidb/ttl/ttlworker.(*JobManager).jobLoop on top of the stack:

goroutine 116605 [select]:

github.com/pingcap/tidb/ttl/ttlworker.(*JobManager).jobLoop(0xc035d952c0)

	ttl/ttlworker/job_manager.go:171 +0x5b4

github.com/pingcap/tidb/ttl/ttlworker.(*baseWorker).loop(0x2a53b8b?)

	ttl/ttlworker/worker.go:134 +0x85

github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()

	util/wait_group_wrapper.go:154 +0x6b

created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run

	util/wait_group_wrapper.go:152 +0x8d

]

--

```

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/24548/pipeline/

**Comment by Defined2014** [comment]
Does it same as https://github.com/pingcap/tidb/issues/41490?
