### ISSUE TITLE
goleak TestPiTRCreateMultiColsIndex

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#44147]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
--- PASS: TestPiTRCreateMultiColsIndex (14.34s)

PASS

goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 1032712 in state select, with go.etcd.io/etcd/client/v3.(*Client).autoSync on top of the stack:

goroutine 1032712 [select]:

go.etcd.io/etcd/client/v3.(*Client).autoSync(0xc02f2381c0)

	external/io_etcd_go_etcd_client_v3/client.go:199 +0xc5

created by go.etcd.io/etcd/client/v3.newClient

	external/io_etcd_go_etcd_client_v3/client.go:444 +0xf7e


 Goroutine 1032618 in state sync.Cond.Wait, with sync.runtime_notifyListWait on top of the stack:

goroutine 1032618 [sync.Cond.Wait]:

sync.runtime_notifyListWait(0xc050a4e050, 0x4)

	GOROOT/src/runtime/sema.go:527 +0x14c

sync.(*Cond).Wait(0xc001a07f70?)

	GOROOT/src/sync/cond.go:70 +0x8c

google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc0324a6000)

	external/org_golang_google_grpc/internal/transport/http2_client.go:1700 +0x245

created by google.golang.org/grpc/internal/transport.newHTTP2Client

	external/org_golang_google_grpc/internal/transport/http2_client.go:384 +0x1dac


 Goroutine 1032713 in state select, with github.com/tikv/client-go/v2/internal/client.(*connMonitor).start on top of the stack:

goroutine 1032713 [select]:

github.com/tikv/client-go/v2/internal/client.(*connMonitor).start(0xc002022dc0)

	external/com_github_tikv_client_go_v2/internal/client/client.go:186 +0xd2

created by github.com/tikv/client-go/v2/internal/client.(*connMonitor).Start.func1

	external/com_github_tikv_client_go_v2/internal/client/client.go:166 +0x8e


 Goroutine 1244357 in state sync.Cond.Wait, 1 minutes, with sync.runtime_notifyListWait on top of the stack:

goroutine 1244357 [sync.Cond.Wait, 1 minutes]:

sync.runtime_notifyListWait(0xc0034c4d90, 0x3)

	GOROOT/src/runtime/sema.go:527 +0x14c

sync.(*Cond).Wait(0xc002f95770?)

	GOROOT/src/sync/cond.go:70 +0x8c

google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc02a1a0d80)

	external/org_golang_google_grpc/internal/transport/http2_client.go:1700 +0x245

created by google.golang.org/grpc/internal/transport.newHTTP2Client

	external/org_golang_google_grpc/internal/transport/http2_client.go:384 +0x1dac



```

**Comment by hawkingrei** [comment]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/21269/pipeline/

**Comment by BornChanger** [comment]
@hawkingrei as I know the problem is gone now. Please check.
