### ISSUE TITLE
[upgrading] get owner op failed led tidb can not start

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#44366]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy v7.1.0 cluster with tiup cluster
2. use sysbench prepare data
3. using tiup cluster upgrade the cluster to nightly 

### 2. What did you expect to see? (Required)
upgrade success
### 3. What did you see instead (Required)
ugrade failed
```log
[2023/06/02 16:35:24.772 +08:00] [WARN] [bootstrap.go:1188] ["[upgrading] get owner op failed"] [state=none] []
[2023/06/02 16:35:24.973 +08:00] [INFO] [manager.go:344] ["get owner"] ["owner info"="upgrade bootstrap"] ["owner key"=/tidb/ddl/fg/owner/db4887b356a3f6d] [ownerID=c4a4c6ff-e140-4248-9414-c80a1fa74703] [op=none]
[2023/06/02 16:35:24.973 +08:00] [FATAL] [bootstrap.go:1186] ["[upgrading] get owner op failed"] [state=none] [] [stack="github.com/pingcap/tidb/session.syncUpgradeState
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/bootstrap.go:1186
github.com/pingcap/tidb/session.upgrade
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/bootstrap.go:1125
github.com/pingcap/tidb/session.runInBootstrapSession
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:3540
github.com/pingcap/tidb/session.BootstrapSession
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:3317
main.createStoreAndDomain
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:347
main.main
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:241
runtime.main
	/usr/local/go/src/runtime/proc.go:250"]
```
### 4. What is your TiDB version? (Required)
```log
 ["Welcome to TiDB."] ["Release Version"=v7.1.0] [Edition=Community] ["Git Commit Hash"=635a4362235e8a3c0043542e629532e3c7bb2756]
["Welcome to TiDB."] ["Release Version"=v7.2.0-alpha] [Edition=Community] ["Git Commit Hash"=50fb9a77a9d6505f30f3fb13a801d650747c63ec]
```

**Comment by zimulala** [comment]
I checked this cluster. When we upgrade tidb-0, the tidb-1 and tidb-2 encountered a panic(like https://github.com/pingcap/tidb/issues/43829) . So the cluster hasn't a stable DDL owner.
Details:
tidb-0 upgrade failed because the owner was out of date.
tidb-1 and tidb-2 upgrade failed because their encountered `can't be paused: state [done] or schema state [public]` error(by design).

**Comment by zimulala** [comment]
tidb-1 and tidb-2 panic info(like https://github.com/pingcap/tidb/issues/43829):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x4917721]

goroutine 587 [running]:
github.com/pingcap/tidb/session.(*session).TxnInfo(0xc0027f7180)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:545 +0x141
github.com/pingcap/tidb/session.GetStartTSFromSession({0x546bfc0?, 0xc0027f7180?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:3822 +0xce
github.com/pingcap/tidb/server.(*Server).GetInternalSessionStartTSList(0xc0017c18c0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:960 +0x20c
github.com/pingcap/tidb/domain/infosync.(*InfoSyncer).ReportMinStartTS(0xc001a23590, {0x5d716a8, 0xc000dae840})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/domain/infosync/info.go:802 +0x82
github.com/pingcap/tidb/domain.(*Domain).infoSyncerKeeper(0xc000458000)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/domain/domain.go:671 +0x42a
github.com/pingcap/tidb/util.(*WaitGroupEnhancedWrapper).Run.func1()
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:96 +0x77
created by github.com/pingcap/tidb/util.(*WaitGroupEnhancedWrapper).Run
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/wait_group_wrapper.go:91 +0xcc
```

**Comment by zimulala** [comment]
https://github.com/pingcap/tidb/issues/43829 is closed
