### ISSUE TITLE
br restore report "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#44496]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

br restore data to cluster

### 2. What did you expect to see? (Required)
restore successfully
### 3. What did you see instead (Required)
```
61.25%Full Restore <------------------------------------------------..............................> 61.25%Full Restore <-----------------
------------------------------\\..............................> 61.38%Full Restore <-----------------------------------------------|......
........................> 61.38%panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation vio
lation code=0x1 addr=0x0 pc=0x3ab0210]\n\ngoroutine 1356 [running]:\[ngithub.com/pingcap/tidb/statistics/handle.(*Handle).SaveStatsToStorag](http://ngithub.com/pingcap/tidb/statistics/handle.(*Handle).SaveStatsToStorag)
e(0x0, 0x72, 0x989680, 0x0?, 0x0, 0xc00407d560, 0x1d12b8b?, 0x0?, 0x55a5020?, 0x1, ...)\n\t/home/jenkins/agent/workspace/build-common/go/s
rc/[github.com/pingcap/br/statistics/handle/handle.go:1555](http://github.com/pingcap/br/statistics/handle/handle.go:1555) +0x130\[ngithub.com/pingcap/tidb/statistics/handle.(*Handle).loadStatsFromJSON](http://ngithub.com/pingcap/tidb/statistics/handle.(*Handle).loadStatsFromJSON)(0x
c008d71a80?, 0xc008d71a68?, 0x4?, 0xc008d71a68?)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/statistics/han](http://github.com/pingcap/br/statistics/han)
dle/dump.go:382 +0x112\[ngithub.com/pingcap/tidb/statistics/handle.(*Handle).LoadStatsFromJSON](http://ngithub.com/pingcap/tidb/statistics/handle.(*Handle).LoadStatsFromJSON)(0xc00199a000?, {0x634b9c8, 0xc00a2b5f80}, 0x
c008647650)\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/statistics/handle/dump.go:347](http://github.com/pingcap/br/statistics/handle/dump.go:347) +0x14f\[ngithub.com/pi](http://ngithub.com/pi)
ngcap/tidb/br/pkg/restore.(*Client).updateMetaAndLoadStats(0xc000859b00, {0x6314db0, 0xc001118780}, 0xc002929f80)\n\t/home/jenkins/agent/w
orkspace/build-common/go/src/[github.com/pingcap/br/br/pkg/restore/client.go:1777](http://github.com/pingcap/br/br/pkg/restore/client.go:1777) +0x6c5\[ngithub.com/pingcap/tidb/br/pkg/restore.(*Client)](http://ngithub.com/pingcap/tidb/br/pkg/restore.(*Client)).
GoValidateChecksum.func1()\n\t/home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/br/br/pkg/restore/client.go:1626](http://github.com/pingcap/br/br/pkg/restore/client.go:1626) +0x68\
ncreated by [github.com/pingcap/tidb/br/pkg/restore.(*Client).GoValidateChecksum\n\t/home/jenkins/agent/workspace/build-common/go/src/githu](http://github.com/pingcap/tidb/br/pkg/restore.(*Client).GoValidateChecksum/n/t/home/jenkins/agent/workspace/build-common/go/src/githu)
[b.com/pingcap/br/br/pkg/restore/client.go:1624](http://b.com/pingcap/br/br/pkg/restore/client.go:1624) +0x185\n", "error": "command terminated with exit code 2"}
```
### 4. What is your TiDB version? (Required)
master

**Comment by seiya-annie** [comment]
[br.log.2023-06-07T18.00.35Z.gz](https://github.com/pingcap/tidb/files/11683193/br.log.2023-06-07T18.00.35Z.gz)
