### ISSUE TITLE
GOLEAK github.com/cockroachdb/pebble

### ISSUE THREAD

**Issue by xhebox** [pingcap/tidb#44826]
## Bug Report

```
   --- PASS: TestLoadRemote/TestLoadSQLDump (8.61s)

    --- PASS: TestLoadRemote/TestMaxWriteSpeed (27.48s)

    --- PASS: TestLoadRemote/TestMixedCompression (6.51s)

    --- PASS: TestLoadRemote/TestMultiValueIndex (4.49s)

    --- SKIP: TestLoadRemote/TestOperateRunningJob (0.00s)

    --- PASS: TestLoadRemote/TestOtherCharset (24.58s)

    --- PASS: TestLoadRemote/TestPreCheckCDCPiTRTasks (0.56s)

    --- PASS: TestLoadRemote/TestPreCheckTableNotEmpty (0.64s)

    --- PASS: TestLoadRemote/TestPreCheckTotalFileSize0 (0.57s)

    --- PASS: TestLoadRemote/TestRegisterTask (13.73s)

    --- PASS: TestLoadRemote/TestSameBehaviourDetachedOrNot (14.92s)

    --- PASS: TestLoadRemote/TestShowDetachedJob (10.44s)

    --- PASS: TestLoadRemote/TestShowJob (12.98s)

    --- SKIP: TestLoadRemote/TestSimpleShowLoadDataJobs (0.00s)

PASS

goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 274960 in state chan receive, 4 minutes, with github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1 on top of the stack:

goroutine 274960 [chan receive, 4 minutes]:

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x9669128, 0xc00ddd5200})

	external/com_github_cockroachdb_pebble/table_cache.go:175 +0x89

runtime/pprof.Do({0x96690b8, 0xc000232008}, {{0xc001213420?, 0x7186960?, 0xc006035a90?}}, 0xc002a07fa0)

	GOROOT/src/runtime/pprof/runtime.go:44 +0x123

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00d7dc000)

	external/com_github_cockroachdb_pebble/table_cache.go:174 +0x92

created by github.com/cockroachdb/pebble.(*tableCacheShard).init

	external/com_github_cockroachdb_pebble/table_cache.go:166 +0x4e7


 Goroutine 275019 in state sync.Cond.Wait, 4 minutes, with sync.runtime_notifyListWait on top of the stack:

goroutine 275019 [sync.Cond.Wait, 4 minutes]:

sync.runtime_notifyListWait(0xc0003334e0, 0x0)

	GOROOT/src/runtime/sema.go:527 +0x14c

sync.(*Cond).Wait(0xc0003334d0)

	GOROOT/src/sync/cond.go:70 +0xa5

github.com/cockroachdb/pebble/record.(*flusherCond).Wait(...)

	external/com_github_cockroachdb_pebble/record/log_writer.go:193

github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop(0xc000333400, {0xc03a8e1e68, 0x73e72a0})

	external/com_github_cockroachdb_pebble/record/log_writer.go:396 +0x695

runtime/pprof.Do({0x96690b8, 0xc000232008}, {{0xc001213320?, 0x0?, 0x1ba2f9a?}}, 0xc0029befc0)

	GOROOT/src/runtime/pprof/runtime.go:44 +0x123

github.com/cockroachdb/pebble/record.NewLogWriter.func2()

	external/com_github_cockroachdb_pebble/record/log_writer.go:314 +0x96

created by github.com/cockroachdb/pebble/record.NewLogWriter

	external/com_github_cockroachdb_pebble/record/log_writer.go:313 +0x5a5


 Goroutine 275018 in state select, with github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1 on top of the stack:

goroutine 275018 [select]:

github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()

	external/com_github_cockroachdb_pebble/vfs/disk_health.go:63 +0x189

created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker

	external/com_github_cockroachdb_pebble/vfs/disk_health.go:58 +0xaf


 Goroutine 275013 in state chan receive, 4 minutes, with github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1 on top of the stack:

goroutine 275013 [chan receive, 4 minutes]:

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x9669128, 0xc00ddd52c0})

	external/com_github_cockroachdb_pebble/table_cache.go:175 +0x89

runtime/pprof.Do({0x96690b8, 0xc000232008}, {{0xc001213420?, 0xc00df188c0?, 0x96de348?}}, 0xc00352cfa0)

	GOROOT/src/runtime/pprof/runtime.go:44 +0x123

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00d7dc500)

	external/com_github_cockroachdb_pebble/table_cache.go:174 +0x92

created by github.com/cockroachdb/pebble.(*tableCacheShard).init

	external/com_github_cockroachdb_pebble/table_cache.go:166 +0x4e7


 Goroutine 275012 in state chan receive, 4 minutes, with github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1 on top of the stack:

goroutine 275012 [chan receive, 4 minutes]:

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x9669128, 0xc00ddd5260})

	external/com_github_cockroachdb_pebble/table_cache.go:175 +0x89

runtime/pprof.Do({0x96690b8, 0xc000232008}, {{0xc001213420?, 0x1bda0c5?, 0x6918d6a?}}, 0xc040fd8fa0)

	GOROOT/src/runtime/pprof/runtime.go:44 +0x123

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00d7dc400)

	external/com_github_cockroachdb_pebble/table_cache.go:174 +0x92

created by github.com/cockroachdb/pebble.(*tableCacheShard).init

	external/com_github_cockroachdb_pebble/table_cache.go:166 +0x4e7


 Goroutine 275014 in state chan receive, 4 minutes, with github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1 on top of the stack:

goroutine 275014 [chan receive, 4 minutes]:

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x9669128, 0xc00ddd5320})

	external/com_github_cockroachdb_pebble/table_cache.go:175 +0x89

runtime/pprof.Do({0x96690b8, 0xc000232008}, {{0xc001213420?, 0xc00df0ea80?, 0xc00181fe98?}}, 0xc00181ffa0)

	GOROOT/src/runtime/pprof/runtime.go:44 +0x123

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00d7dc600)

	external/com_github_cockroachdb_pebble/table_cache.go:174 +0x92

created by github.com/cockroachdb/pebble.(*tableCacheShard).init

	external/com_github_cockroachdb_pebble/table_cache.go:166 +0x4e7


 Goroutine 275015 in state chan receive, 4 minutes, with github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1 on top of the stack:

goroutine 275015 [chan receive, 4 minutes]:

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x9669128, 0xc00da59e90})

	external/com_github_cockroachdb_pebble/table_cache.go:175 +0x89

runtime/pprof.Do({0x96690b8, 0xc000232008}, {{0xc001213420?, 0xc002eddfd0?, 0x6918f65?}}, 0xc002eddfa0)

	GOROOT/src/runtime/pprof/runtime.go:44 +0x123

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00d7dc700)

	external/com_github_cockroachdb_pebble/table_cache.go:174 +0x92

created by github.com/cockroachdb/pebble.(*tableCacheShard).init

	external/com_github_cockroachdb_pebble/table_cache.go:166 +0x4e7


 Goroutine 275016 in state select, with github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1 on top of the stack:

goroutine 275016 [select]:

github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()

	external/com_github_cockroachdb_pebble/vfs/disk_health.go:63 +0x189

created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker

	external/com_github_cockroachdb_pebble/vfs/disk_health.go:58 +0xaf


 Goroutine 275011 in state chan receive, 4 minutes, with github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1 on top of the stack:

goroutine 275011 [chan receive, 4 minutes]:

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x9669128, 0xc00dea6300})

	external/com_github_cockroachdb_pebble/table_cache.go:175 +0x89

runtime/pprof.Do({0x96690b8, 0xc000232008}, {{0xc001213420?, 0x1bda0c5?, 0x6918ceb?}}, 0xc0007c4fa0)

	GOROOT/src/runtime/pprof/runtime.go:44 +0x123

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00d7dc300)

	external/com_github_cockroachdb_pebble/table_cache.go:174 +0x92

created by github.com/cockroachdb/pebble.(*tableCacheShard).init

	external/com_github_cockroachdb_pebble/table_cache.go:166 +0x4e7


 Goroutine 275010 in state chan receive, 4 minutes, with github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1 on top of the stack:

goroutine 275010 [chan receive, 4 minutes]:

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x9669128, 0xc00dea6360})

	external/com_github_cockroachdb_pebble/table_cache.go:175 +0x89

runtime/pprof.Do({0x96690b8, 0xc000232008}, {{0xc001213420?, 0x0?, 0x0?}}, 0xc001661fa0)

	GOROOT/src/runtime/pprof/runtime.go:44 +0x123

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00d7dc200)

	external/com_github_cockroachdb_pebble/table_cache.go:174 +0x92

created by github.com/cockroachdb/pebble.(*tableCacheShard).init

	external/com_github_cockroachdb_pebble/table_cache.go:166 +0x4e7


 Goroutine 274961 in state chan receive, 4 minutes, with github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1 on top of the stack:

goroutine 274961 [chan receive, 4 minutes]:

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1({0x9669128, 0xc00dea63c0})

	external/com_github_cockroachdb_pebble/table_cache.go:175 +0x89

runtime/pprof.Do({0x96690b8, 0xc000232008}, {{0xc001213420?, 0x0?, 0x0?}}, 0xc00f4e4fa0)

	GOROOT/src/runtime/pprof/runtime.go:44 +0x123

github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc00d7dc100)

	external/com_github_cockroachdb_pebble/table_cache.go:174 +0x92

created by github.com/cockroachdb/pebble.(*tableCacheShard).init

	external/com_github_cockroachdb_pebble/table_cache.go:166 +0x4e7

]

================================================================================

```

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/23147/pipeline

**Comment by lance6716** [comment]
The test hierarchy is changed, we can't know which test causes this problem
