### ISSUE TITLE
unstable test TestRenameTableIntermediateState

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#44948]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
     table_test.go:560: 
        	Error Trace:	ddl/table_test.go:560
        	            				ddl/util/callback/callback.go:124
        	            				ddl/job_table.go:449
        	            				util/wait_group_wrapper.go:154
        	            				src/runtime/asm_amd64.s:1598
        	Error:      	Expected value not to be nil.
        	Test:       	TestRenameTableIntermediateState
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x839a89f]
goroutine 573593 [running]:
github.com/pingcap/tidb/ddl_test.TestRenameTableIntermediateState.func1(0xc017fce840?)
	ddl/table_test.go:561 +0xff
github.com/pingcap/tidb/ddl/util/callback.(*TestDDLCallback).OnJobUpdated(0xc01e561b20, 0xc017fce840?)
	ddl/util/callback/callback.go:124 +0x1ea
github.com/pingcap/tidb/ddl.(*ddl).delivery2worker.func1()
	ddl/job_table.go:449 +0xdef
github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run.func1()
	util/wait_group_wrapper.go:154 +0x6b
created by github.com/pingcap/tidb/util.(*WaitGroupWrapper).Run
	util/wait_group_wrapper.go:152 +0x8d
-- 
```

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/44947/tiprow_fast_test/1673232837370712064

**Comment by hawkingrei** [comment]
https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/48792/tiprow_fast_test/1727530829061558272#1:build-log.txt%3A7701

See it again.

**Comment by hawkingrei** [comment]
See it again

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/50306/tiprow_fast_test/1745329975055093760#1:build-log.txt%3A7979
