### ISSUE TITLE
`fatal error: concurrent map read and map write` from `Config.Labels`

### ISSUE THREAD

**Issue by gengliqi** [pingcap/tidb#45561]
## Bug Report

```
fatal error: concurrent map read and map write

 goroutine 513 [running]:
 github.com/pingcap/tidb/config.(*Config).GetTiKVConfig(...)
 	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/config/config.go:312
 github.com/pingcap/tidb/sessionctx/variable.glob..func188({0xc04ef57a40?, 0xc001c01800?}, 0xc04e8fdcae?, {0xc04e8fdcae?, 0x2?})
 	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/sessionctx/variable/sysvar.go:1026 +0x33e
 github.com/pingcap/tidb/domain.(*Domain).rebuildSysVarCache(0xc000cefe00, {0x5025338, 0xc0008e2c80})
 	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/domain/sysvar_cache.go:147 +0x71e
 github.com/pingcap/tidb/domain.(*Domain).LoadSysVarCacheLoop.func1()
 	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/domain/domain.go:1415 +0x1ff
 created by github.com/pingcap/tidb/domain.(*Domain).LoadSysVarCacheLoop
 	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/domain/domain.go:1376 +0x172
```

https://github.com/pingcap/tidb/blob/b4183e1dc9bb01fb81d3aa79ca4b5b74387c6c2a/server/http_handler.go#L2221-L2231

The code above wants to update `Labels` in `Config`. It copies the global config first and then changes the `Labels` in the copy.
However, the `Labels` is a `map[string]string` so the copy is shallow, which causes this data race.

**Comment by gengliqi** [comment]
/affects-6.3 /affects-6.4 /affects-6.5 /affects-6.6 /affects-7.0 /affects-7.1 /affects-7.2

**Comment by gengliqi** [comment]
/affects-6.5 /affects-7.1 /affects-7.2
