### ISSUE TITLE
goleak createBackoffFn.newBackoffFn.func2  from tikv/client-go

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#46432]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 100953 in state select, with github.com/tikv/client-go/v2/internal/retry.(*Config).createBackoffFn.newBackoffFn.func2 on top of the stack:

goroutine 100953 [select]:

github.com/tikv/client-go/v2/internal/retry.(*Config).createBackoffFn.newBackoffFn.func2({0x5fcd028, 0x8d5bac0}, 0xffffffffffffffff)

	external/com_github_tikv_client_go_v2/internal/retry/config.go:183 +0x4ea

github.com/tikv/client-go/v2/internal/retry.(*Backoffer).BackoffWithCfgAndMaxSleep(0xc0284623f0, 0xc0005eb560, 0x5247d00?, {0x5f9ee40, 0xc034e30d68})

	external/com_github_tikv_client_go_v2/internal/retry/backoff.go:188 +0x5b3

github.com/tikv/client-go/v2/internal/retry.(*Backoffer).Backoff(0xc0284623f0, 0xc0005eb560, {0x5f9ee40, 0xc034e30d68})

	external/com_github_tikv_client_go_v2/internal/retry/backoff.go:122 +0x251

github.com/tikv/client-go/v2/tikv.(*KVStore).getTimestampWithRetry(0xc015956c00, 0xc0284623f0, {0x56666f7, 0x6})

	external/com_github_tikv_client_go_v2/tikv/kv.go:426 +0x42b

github.com/tikv/client-go/v2/tikv.(*KVStore).GetTimestampWithRetry(0xc0117bdbc0?, 0xc0117bdb30?, {0x56666f7?, 0x0?})

	external/com_github_tikv_client_go_v2/tikv/kv.go:401 +0x18

github.com/tikv/client-go/v2/txnkv/transaction.keepAlive(0xc0193c8540, 0xc0194443c0, {0xc019700024, 0x13, 0x13}, 0xc01944c3c0)

	external/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1170 +0x2ab

created by github.com/tikv/client-go/v2/txnkv/transaction.(*ttlManager).run in goroutine 98619

	external/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1130 +0x1c6

]

--

```

**Comment by hawkingrei** [comment]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/27346/pipeline

**Comment by hawkingrei** [comment]
I don't see it again.

**Comment by hawkingrei** [comment]
```
PASS

goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 114456 in state select, with github.com/tikv/client-go/v2/internal/retry.(*Config).createBackoffFn.newBackoffFn.func2 on top of the stack:

goroutine 114456 [select]:

github.com/tikv/client-go/v2/internal/retry.(*Config).createBackoffFn.newBackoffFn.func2({0x93569f8, 0xd2c6dc0}, 0xffffffffffffffff)

	external/com_github_tikv_client_go_v2/internal/retry/config.go:183 +0x5f5

github.com/tikv/client-go/v2/internal/retry.(*Backoffer).BackoffWithCfgAndMaxSleep(0xc03194cb40, 0xc000affd40, 0x18?, {0x9327a00, 0xc030221320})

	external/com_github_tikv_client_go_v2/internal/retry/backoff.go:188 +0xa24

github.com/tikv/client-go/v2/internal/retry.(*Backoffer).Backoff(0xc03194cb40, 0xc000affd40, {0x9327a00, 0xc030221320})

	external/com_github_tikv_client_go_v2/internal/retry/backoff.go:122 +0x2d5

github.com/tikv/client-go/v2/tikv.(*KVStore).getTimestampWithRetry(0xc009850c00, 0xc03194cb40, {0x7928407, 0x6})

	external/com_github_tikv_client_go_v2/tikv/kv.go:426 +0x5fd

github.com/tikv/client-go/v2/tikv.(*KVStore).GetTimestampWithRetry(0xc021fdbba0?, 0xc021fdb9f8?, {0x7928407, 0x6})

	external/com_github_tikv_client_go_v2/tikv/kv.go:401 +0x45

github.com/tikv/client-go/v2/txnkv/transaction.keepAlive(0xc0132bbdc0, 0xc018888c00, {0xc00620c024, 0x13, 0x13}, 0xc006207540)

	external/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1170 +0x612

created by github.com/tikv/client-go/v2/txnkv/transaction.(*ttlManager).run in goroutine 111643

	external/com_github_tikv_client_go_v2/txnkv/transaction/2pc.go:1130 +0x2e6

]

--

Coverage runner: Not collecting coverage for failed test
```

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/28772/pipeline


It happened again.
