### ISSUE TITLE
goleak github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#46682]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
coverage: 82.8% of statements

goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 2206831 in state select, with github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1 on top of the stack:

goroutine 2206831 [select]:

github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()

	external/com_github_cockroachdb_pebble/vfs/disk_health.go:63 +0xcb

created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 2206746

	external/com_github_cockroachdb_pebble/vfs/disk_health.go:58 +0x58


]

--

```

**Comment by hawkingrei** [comment]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/28174/pipeline
