### ISSUE TITLE
local backend: cleanup takes a long time to finish

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#47145]
## Enhancement

when cleanup, we're waiting on the compaction lock of pebble, for over 31m(cleanup finished in 35m)

maybe disable compaction completely by

```
	// DisableAutomaticCompactions dictates whether automatic compactions are
	// scheduled or not. The default is false (enabled). This option is only used
	// externally when running a manual compaction, and internally for tests.
	DisableAutomaticCompactions bool
```

```
goroutine 2344006 [sync.Cond.Wait, 31 minutes]:
sync.runtime_notifyListWait(0xc01cb87478, 0x0)
	/usr/local/go/src/runtime/sema.go:527 +0x159
sync.(*Cond).Wait(0xc02cc113e0?)
	/usr/local/go/src/sync/cond.go:70 +0x85
github.com/cockroachdb/pebble.(*DB).Close(0xc01cb87200)
	/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220415182917-06c9d3be25b3/db.go:1141 +0x245
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Engine).Close(0xc02ccc2dc0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/br/pkg/lightning/backend/local/engine.go:171 +0x21e
github.com/pingcap/tidb/br/pkg/lightning/backend/local.(*Backend).CleanupEngine(0xc0056c9a00, {0x6080998, 0xc006298280}, {0x84, 0x8d, 0x16, 0xa9, 0x51, 0x4f, 0x53, ...})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/br/pkg/lightning/backend/local/local.go:1750 +0xcf
github.com/pingcap/tidb/br/pkg/lightning/backend.(*ClosedEngine).Cleanup(0xc042a30cf0, {0x6080998, 0xc006298280})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/br/pkg/lightning/backend/backend.go:383 +0x7f
github.com/pingcap/tidb/executor/importer.(*TableImporter).ImportAndCleanup(0xc0084feb60, {0x6080998, 0xc006298280}, 0xc042a30cf0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/importer/table_import.go:489 +0xf1
github.com/pingcap/tidb/disttask/importinto.(*importStepExecutor).OnFinished(0xc009f09f80, {0x6080998, 0xc006298280}, 0xc02c9626e0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/disttask/importinto/scheduler.go:202 +0x4b0
github.com/pingcap/tidb/disttask/framework/scheduler.(*BaseScheduler).onSubtaskFinished(0xc008fc0e80, {0x6080998, 0xc006298280}, {0x60862a0, 0xc009f09f80}, 0xc02c9626e0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/disttask/framework/scheduler/scheduler.go:286 +0x59
github.com/pingcap/tidb/disttask/framework/scheduler.(*BaseScheduler).runSubtask(0xc008fc0e80, {0x6080998, 0xc006298280}, {0x60862a0, 0xc009f09f80}, 0xc02c9626e0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/disttask/framework/scheduler/scheduler.go:281 +0x165
github.com/pingcap/tidb/disttask/framework/scheduler.(*BaseScheduler).run(0xc008fc0e80, {0x6080960, 0xc0da7137a0}, 0xc0b4fd6f20)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/disttask/framework/scheduler/scheduler.go:205 +0x90c
github.com/pingcap/tidb/disttask/framework/scheduler.(*BaseScheduler).Run(0xc008fc0e80, {0x6080960?, 0xc0da7137a0?}, 0xc0b4fd6f20)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/disttask/framework/scheduler/scheduler.go:116 +0x99
github.com/pingcap/tidb/disttask/importinto.(*importScheduler).Run(0xc03fe84400, {0x6080998, 0xc006298230}, 0xc0b4fd6f20)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/disttask/importinto/scheduler.go:364 +0x10d
github.com/pingcap/tidb/disttask/framework/scheduler.(*Manager).onRunnableTask(0xc0016a87e0, {0x6080998, 0xc004310230}, 0xc008d222c0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/disttask/framework/scheduler/manager.go:310 +0x5ca
github.com/pingcap/tidb/disttask/framework/scheduler.(*Manager).onRunnableTasks.func1()
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/disttask/framework/scheduler/manager.go:197 +0x2d
github.com/pingcap/tidb/resourcemanager/pool/spool.(*Pool).run.func1()
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/resourcemanager/pool/spool/spool.go:145 +0x4d
created by github.com/pingcap/tidb/resourcemanager/pool/spool.(*Pool).run in goroutine 1811
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/resourcemanager/pool/spool/spool.go:137 +0x73

```

**Comment by D3Hunter** [comment]
cc @lance6716

**Comment by lance6716** [comment]
maybe it's the same problem as https://github.com/pingcap/tidb/issues/46978
I see pebble compaction costs a lot of CPU in that issue. will take a look later
