### ISSUE TITLE
br is blocken on the grpc waitonHeader when concurrency is set to large number(2048)

### ISSUE THREAD

**Issue by Leavrth** [pingcap/tidb#47246]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. run br with concurrency 2048 to do snapshot restore

### 2. What did you expect to see? (Required)
success to do snapshot restore
### 3. What did you see instead (Required)
blocken on the grpc `waitOnHeader`

```
goroutine 555735 [select, 53 minutes]:
google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader()
    /go/pkg/mod/google.golang.org/grpc@v1.51.0/internal/transport/transport.go:328 +0x7c

```
### 4. What is your TiDB version? (Required)
master, v6.5

**Comment by Leavrth** [comment]
The log restore is also blocken here. Different from snapshot restore, it's actually stuck waiting to receive the response from raftstore. However, the raft message is rejected by followers due to `reject memory threshold`.

**Comment by Leavrth** [comment]
We found that the speed of downloading backup files are too small when there are many download task at the same time in the test external storage.

**Comment by WangLe1321** [comment]
We also encountered this problem during backup process on tidbcloud. It blocked more than 1 day. 

```
goroutine 22381 [select, 1505 minutes]:
google.golang.org/grpc/internal/transport.(*Stream).waitOnHeader(0xc0033abb00)
	/go/pkg/mod/google.golang.org/grpc@v1.54.0/internal/transport/transport.go:331 +0x7c
google.golang.org/grpc/internal/transport.(*Stream).RecvCompress(...)
	/go/pkg/mod/google.golang.org/grpc@v1.54.0/internal/transport/transport.go:346
google.golang.org/grpc.(*csAttempt).recvMsg(0xc003745e10, {0x58082a0?, 0xc0033c6580}, 0xa1a?)
	/go/pkg/mod/google.golang.org/grpc@v1.54.0/stream.go:1058 +0xc5
google.golang.org/grpc.(*clientStream).RecvMsg.func1(0x5?)
	/go/pkg/mod/google.golang.org/grpc@v1.54.0/stream.go:909 +0x25
google.golang.org/grpc.(*clientStream).withRetry(0xc0033ab8c0, 0xc0030e3748, 0xc0030e3718)
	/go/pkg/mod/google.golang.org/grpc@v1.54.0/stream.go:760 +0x144
google.golang.org/grpc.(*clientStream).RecvMsg(0xc0033ab8c0, {0x58082a0?, 0xc0033c6580?})
	/go/pkg/mod/google.golang.org/grpc@v1.54.0/stream.go:908 +0x131
github.com/pingcap/kvproto/pkg/brpb.(*backupBackupClient).Recv(0xc00361a0e0)
	/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20230523065550-8b641fa69bf3/pkg/brpb/brpb.pb.go:3412 +0x4c
github.com/pingcap/tidb/br/pkg/backup.doSendBackup({0x6244578, 0xc003424f60}, {0x62264b8, 0xc002b58690}, {0x65b7489f59050a4c, {0xc0022a8870, 0x13, 0x13}, {0xc0022a8888, 0x14, ...}, ...}, ...)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/backup/client.go:1347 +0x1b9
github.com/pingcap/tidb/br/pkg/backup.SendBackup({0x6244578, 0xc003424f60}, 0x4, {0x62264b8, _}, {0x65b7489f59050a4c, {0xc0022a8870, 0x13, 0x13}, {0xc0022a8888, ...}, ...}, ...)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/backup/client.go:1396 +0x525
github.com/pingcap/tidb/br/pkg/backup.(*pushDown).pushBackup.func2()
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/backup/push.go:94 +0x153
created by github.com/pingcap/tidb/br/pkg/backup.(*pushDown).pushBackup
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/backup/push.go:92 +0x88c
```
