### ISSUE TITLE
goleak  github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#47491]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
--- PASS: TestPiTRCreateMultiColsIndex (8.06s)

PASS

coverage: 82.8% of statements

goleak: Errors on successful test run: found unexpected goroutines:

[Goroutine 2456813 in state select, with github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1 on top of the stack:

goroutine 2456813 [select]:

github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()

	external/com_github_cockroachdb_pebble/vfs/disk_health.go:63 +0xcb

created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker in goroutine 2456695

	external/com_github_cockroachdb_pebble/vfs/disk_health.go:58 +0x58


]

```

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/30788/pipeline

**Comment by lance6716** [comment]
seems https://github.com/pingcap/tidb/issues/46682 is not fixed

**Comment by wuhuizuo** [comment]
We hit this again on `pingcap/tidb` **release-7.1** in the same job as the original report (`ghpr_check2`, real-TiKV matrix). Adding current details.

### Environment
- Job: `pingcap/tidb/release-7.1/ghpr_check2` (new staging Jenkins)
- Failing matrix cell: `run_real_tikv_tests.sh bazel_addindextest`
- Test target: `//tests/realtikvtest/addindextest:addindextest_test`
- Builds (both reproducible): [ghpr_check2 #9](https://do.pingcap.net/jenkins-staging/job/pingcap/job/tidb/job/release-7.1/job/ghpr_check2/9), [ghpr_check2 #10](https://do.pingcap.net/jenkins-staging/job/pingcap/job/tidb/job/release-7.1/job/ghpr_check2/10)
- Go toolchain: pod image `go12520260122` (Go 1.25), linux/amd64

### Symptom
All test cases pass; only the final `goleak` check fails:

```
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 2343349 in state select, with github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1 on top of the stack:
goroutine 2343349 [select]:
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1()
	external/com_github_cockroachdb_pebble/vfs/disk_health.go:63 +0xe5
created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker
	external/com_github_cockroachdb_pebble/vfs/disk_health.go:58 +0x5d
 Goroutine 2343350 in state sync.Cond.Wait, 4 minutes, with sync.runtime_notifyListWait on top of the stack:
goroutine 2343350 [sync.Cond.Wait, 4 minutes]:
sync.runtime_notifyListWait(0xc0835114e0, 0x0)
	GOROOT/src/runtime/sema.go:527 +0x14c
sync.(*Cond).Wait(0x4f2c060?)
	GOROOT/src/sync/cond.go:70 +0x8c
github.com/cockroachdb/pebble/record.(*flusherCond).Wait(...)
	external/com_github_cockroachdb_pebble/record/log_writer.go:193
github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop(0xc083511400, {0x4f2c060, 0x89f8e60})
	external/com_github_cockroachdb_pebble/record/log_writer.go:396 +0x479
...
]

Test cases: finished with 48 passing and 0 failing out of 48 test cases
make: *** [Makefile:506: bazel_addindextest] Error 3
```

So it is purely the goroutine-leak check at `TestMain` exit; the DDL add-index cases themselves all pass. The leaked goroutines are 2× `pebble/vfs.(*diskHealthCheckingFile).startTicker` plus 1× `pebble/record.(*LogWriter).flushLoop` (waiting 4 minutes).

### Notes / current state
- Same class of leak as #66946 (`TestImportInto` real-TiKV).
- `master`'s `tests/realtikvtest/testkit.go` goleak ignore list does **not** cover these pebble goroutines, so it is not stabilized upstream (the list only adds grpc `CallbackSerializer`, `opencensus` view worker, client-go backoff, `resolveFlushedLocks`, etc.).
- The only attempted fix, #46685 (close `duplicateDB` on error halfway), is master-only and — per the comment below — does not fully fix it; release-7.1 still has the pre-#46685 code in `br/pkg/lightning/backend/local/local.go`.
- `tests/realtikvtest/addindextest` on release-7.1 has no dedicated leak fix; the package was heavily refactored on master.

Happy to help test a fix on release-7.1 if someone points at the intended approach (e.g. closing the ingest/duplicate pebble DB before `TestMain` exits, or a targeted `goleak.IgnoreAnyFunction`).
