### ISSUE TITLE
Goroutine leak when memory exceed quota

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#48007]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
run command: 

tiup playground v7.4.0  (or nightly)
tiup bench tpch prepare --db test --threads 5

run sql:
```
use test;
set @@tidb_mem_quota_query=128;
-- run tpch query11 many times
select ps_partkey, sum(ps_supplycost * ps_availqty) as value from partsupp, supplier, nation where ps_suppkey = s_suppkey and s_nationkey = n_nationkey and n_name = 'MOZAMBIQUE' group by ps_partkey having sum(ps_supplycost * ps_availqty) > ( select sum(ps_supplycost * ps_availqty) * 0.0001000000 from partsupp, supplier, nation where ps_suppkey = s_suppkey and s_nationkey = n_nationkey and n_name = 'MOZAMBIQUE' ) order by value desc;
```

### 2. What did you expect to see? (Required)

No goroutine leak.

### 3. What did you see instead (Required)
See http://127.0.0.1:10080/debug/pprof/goroutine?debug=2 and find some goroutines leak.
```
goroutine 156428 [select, 7 minutes]:
github.com/pingcap/tidb/store/copr.(*copIteratorWorker).sendToRespCh(0xc037115b20?, 0xc0373b73b0?, 0xc0164bba40?, 0xc0?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1003 +0xa6
github.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleCopResponse(0xc037115b20, 0xc03ab0a378, 0xc0371a5320, 0xc0373b73b0, {0xc0360cb8c0, 0x156, 0x156}, 0xc030369a18?, 0xc03718d5e0, 0xc0164bba40, ...)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1442 +0x776
github.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleCopPagingResult(0xc037115b20, 0x0?, 0x2?, 0xc0373b73b0, {0xc0360cb8c0?, 0xc0373889c0?, 0x0?}, 0x0?, 0xc03718d5e0, 0xc0164bba40, ...)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1342 +0x59
github.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTaskOnce(0xc037115b20, 0xc03ab0a378, 0xc03718d5e0, 0xc0164bba40?)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1275 +0x10ec
github.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTask(0xc037115b20, {0x60b3de0, 0xc036c752f0}, 0xc00347ac58?, 0xc0164bba40)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1130 +0x18e
github.com/pingcap/tidb/store/copr.(*copIteratorWorker).run(0xc037115b20, {0x60b3de0, 0xc036c752f0})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:817 +0xc5
created by github.com/pingcap/tidb/store/copr.(*copIterator).open in goroutine 150517
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:861 +0x9b
```

### 4. What is your TiDB version? (Required)
master, v7.4.0

**Comment by zanmato1984** [comment]
This is very corner case, so adjusting the severity to major.

**Comment by MimeLyc** [comment]
update
