### ISSUE TITLE
flaky test TestMergeIterSwitchMode

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#48223]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
 --- FAIL: TestMergeIterSwitchMode (9.57s)
panic: runtime error: makeslice: len out of range [recovered]
	panic: runtime error: makeslice: len out of range
goroutine 108 [running]:
testing.tRunner.func1.2({0x42ac00, 0xe69dc0})
	GOROOT/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1548 +0x397
panic({0x42ac00?, 0xe69dc0?})
	GOROOT/src/runtime/panic.go:914 +0x21f
github.com/pingcap/tidb/br/pkg/lightning/backend/external.(*byteReader).readNBytes(0xc000ed4000, 0x56884590091540f1)
	br/pkg/lightning/backend/external/byte_reader.go:209 +0x125
github.com/pingcap/tidb/br/pkg/lightning/backend/external.(*kvReader).nextKV(0xc006de6018)
	br/pkg/lightning/backend/external/kv_reader.go:59 +0xe5
github.com/pingcap/tidb/br/pkg/lightning/backend/external.kvReaderProxy.next({{0xc004c4c217?, 0xc003424b10?}, 0xc006de6018?})
	br/pkg/lightning/backend/external/iter.go:336 +0x2e
github.com/pingcap/tidb/br/pkg/lightning/backend/external.(*mergeIter[...]).next(0xeb2240)
	br/pkg/lightning/backend/external/iter.go:277 +0x29a
github.com/pingcap/tidb/br/pkg/lightning/backend/external.(*MergeKVIter).Next(...)
	br/pkg/lightning/backend/external/iter.go:405
github.com/pingcap/tidb/br/pkg/lightning/backend/external.testMergeIterSwitchMode(0xc000f376c0?, 0xc000867f28)
	br/pkg/lightning/backend/external/iter_test.go:323 +0x4f8
github.com/pingcap/tidb/br/pkg/lightning/backend/external.TestMergeIterSwitchMode(0xc000f376c0)
	br/pkg/lightning/backend/external/iter_test.go:275 +0x1a7
testing.tRunner(0xc000f376c0, 0x947518)
	GOROOT/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	GOROOT/src/testing/testing.go:1648 +0x3ad
-- 
```

**Comment by hawkingrei** [comment]
https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/48202/tiprow_fast_test/1719963557371580416
