### ISSUE TITLE
OOM in the ClearOutdatedHistoryStats

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#48431]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![img_v3_0250_170a3ec3-60f0-4818-867d-95b5574e1c8g](https://github.com/pingcap/tidb/assets/3427324/e39b198a-02a4-472e-aec1-6be47b9c96ee)

```
goroutine 1464 [chan receive]:
[github.com/pingcap/tidb/pkg/executor.(*IndexLookUpExecutor).getResultTask(0xc1b9227180)](http://github.com/pingcap/tidb/pkg/executor.(*IndexLookUpExecutor).getResultTask(0xc1b9227180))
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/distsql.go:904](http://github.com/pingcap/tidb/pkg/executor/distsql.go:904) +0x105
[github.com/pingcap/tidb/pkg/executor.(*IndexLookUpExecutor).Next](http://github.com/pingcap/tidb/pkg/executor.(*IndexLookUpExecutor).Next)(0xc1b9227180, {0x62f3c50?, 0xc0d1bac840?}, 0xc159e0ccd0)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/distsql.go:867](http://github.com/pingcap/tidb/pkg/executor/distsql.go:867) +0xd5
[github.com/pingcap/tidb/pkg/executor/internal/exec.Next](http://github.com/pingcap/tidb/pkg/executor/internal/exec.Next)({0x62f3c50, 0xc0d1bac840}, {0x6309910, 0xc1b9227180}, 0xc159e0ccd0)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:278](http://github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:278) +0x2ba
[github.com/pingcap/tidb/pkg/executor.(*DeleteExec).deleteSingleTableByChunk](http://github.com/pingcap/tidb/pkg/executor.(*DeleteExec).deleteSingleTableByChunk)(0xc05a5cab40, {0x62f3c50, 0xc0d1bac840})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/delete.go:113](http://github.com/pingcap/tidb/pkg/executor/delete.go:113) +0x665
[github.com/pingcap/tidb/pkg/executor.(*DeleteExec).Next](http://github.com/pingcap/tidb/pkg/executor.(*DeleteExec).Next)(0x62f3c50?, {0x62f3c50?, 0xc0d1bac840?}, 0x1?)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/delete.go:61](http://github.com/pingcap/tidb/pkg/executor/delete.go:61) +0x65
[github.com/pingcap/tidb/pkg/executor/internal/exec.Next](http://github.com/pingcap/tidb/pkg/executor/internal/exec.Next)({0x62f3c50, 0xc0d1bac840}, {0x630a830, 0xc05a5cab40}, 0xc159e0cb90)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:278](http://github.com/pingcap/tidb/pkg/executor/internal/exec/executor.go:278) +0x2ba
[github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next](http://github.com/pingcap/tidb/pkg/executor.(*ExecStmt).next)(0xc071e7ce10, {0x62f3c50, 0xc0d1bac840}, {0x630a830, 0xc05a5cab40}, 0x0?)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/adapter.go:1226](http://github.com/pingcap/tidb/pkg/executor/adapter.go:1226) +0x6e
[github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelayExecutor](http://github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelayExecutor)(0xc071e7ce10, {0x62f3c50?, 0xc0d1bac840?}, {0x630a830?, 0xc05a5cab40})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/adapter.go:971](http://github.com/pingcap/tidb/pkg/executor/adapter.go:971) +0x396
[github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay](http://github.com/pingcap/tidb/pkg/executor.(*ExecStmt).handleNoDelay)(0xc071e7ce10, {0x62f3c50, 0xc0d1bac840}, {0x630a830?, 0xc05a5cab40?}, 0x0)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/adapter.go:797](http://github.com/pingcap/tidb/pkg/executor/adapter.go:797) +0x252
[github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec](http://github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec)(0xc071e7ce10, {0x62f3c50, 0xc0d1bac840})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/executor/adapter.go:578](http://github.com/pingcap/tidb/pkg/executor/adapter.go:578) +0xda5
[github.com/pingcap/tidb/pkg/session.runStmt](http://github.com/pingcap/tidb/pkg/session.runStmt)({0x62f3c50?, 0xc000ea0270?}, 0xc0669d4780, {0x6303700, 0xc071e7ce10?})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/session/session.go:2421](http://github.com/pingcap/tidb/pkg/session/session.go:2421) +0x422
[github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt](http://github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt)(0xc0669d4780, {0x62f3c50?, 0xc000ea0270?}, {0x6308298?, 0xc08967b040?})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/session/session.go:2271](http://github.com/pingcap/tidb/pkg/session/session.go:2271) +0x109b
[github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal](http://github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal)(0xc0669d4780, {0x62f3c50, 0xc000ea0270}, {0x5a9c7be, 0x6b}, {0xc01eb7c7e0, 0x1, 0x1})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/session/session.go:1645](http://github.com/pingcap/tidb/pkg/session/session.go:1645) +0x23e
[github.com/pingcap/tidb/pkg/statistics/handle/util.Exec](http://github.com/pingcap/tidb/pkg/statistics/handle/util.Exec)({0x636c1d8?, 0xc0669d4780?}, {0x5a9c7be, 0x6b}, {0xc01eb7c7e0, 0x1, 0x1})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/util/util.go:203](http://github.com/pingcap/tidb/pkg/statistics/handle/util/util.go:203) +0x8c
[github.com/pingcap/tidb/pkg/statistics/handle/storage.ClearOutdatedHistoryStats](http://github.com/pingcap/tidb/pkg/statistics/handle/storage.ClearOutdatedHistoryStats)({0x636c1d8, 0xc0669d4780})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:191](http://github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:191) +0x39e
[github.com/pingcap/tidb/pkg/statistics/handle/storage.GCStats](http://github.com/pingcap/tidb/pkg/statistics/handle/storage.GCStats)({0x636c1d8, 0xc0669d4780}, {0x6375170?, 0xc067418a00}, {0x63304f0, 0xc0061b4200}, 0xa7a358200)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:119](http://github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:119) +0x59f
[github.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsGCImpl).GCStats.func1](http://github.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsGCImpl).GCStats.func1)({0x636c1d8?, 0xc0669d4780?})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:57](http://github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:57) +0x34
[github.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx](http://github.com/pingcap/tidb/pkg/statistics/handle/util.CallWithSCtx)({0x62cf7d0, 0xc0014060f0}, 0xc065cabb00, {0x0, 0x0, 0xc065cabb28?})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/util/util.go:110](http://github.com/pingcap/tidb/pkg/statistics/handle/util/util.go:110) +0x194
[github.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsGCImpl).GCStats](http://github.com/pingcap/tidb/pkg/statistics/handle/storage.(*statsGCImpl).GCStats)(0xc047dc6ef0, {0x63304f0, 0xc0061b4200}, 0xa7a358200)
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:56](http://github.com/pingcap/tidb/pkg/statistics/handle/storage/gc.go:56) +0x96
[github.com/pingcap/tidb/pkg/domain.(*Domain).updateStatsWorker](http://github.com/pingcap/tidb/pkg/domain.(*Domain).updateStatsWorker)(0xc001436000, {0x0?, 0x0?}, {0x63159c0?, 0xc0676cd900?})
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/domain/domain.go:2438](http://github.com/pingcap/tidb/pkg/domain/domain.go:2438) +0x7f9
[github.com/pingcap/tidb/pkg/domain.(*Domain).UpdateTableStatsLoop.func3()](http://github.com/pingcap/tidb/pkg/domain.(*Domain).UpdateTableStatsLoop.func3())
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/domain/domain.go:2257](http://github.com/pingcap/tidb/pkg/domain/domain.go:2257) +0x27
[github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1()](http://github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1())
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:96](http://github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:96) +0x6c
created by [github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run](http://github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run) in goroutine 1
    /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:91](http://github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:91) +0xbd
```

**Comment by MimeLyc** [comment]
update
