### ISSUE TITLE
Auto_id_cache goroutine leak

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#48843]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t1 (a int not null auto_increment,b int, primary key (a)) engine=myisam auto_increment=3 auto_id_cache 1;
insert into t1 values (1,1),(NULL,3),(NULL,4);
drop table t1;
```

Create table stmt leaks some goroutines.
Insert stmt also leaks some goroutines.

### 2. What did you expect to see? (Required)
No goroutine leak.

### 3. What did you see instead (Required)

```
goroutine 343 [select, 13 minutes]:
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0xc000f4c920, {0x63424e8, 0xc000f1adc0})
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/internal/grpcsync/callback_serializer.go:83 +0x112
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 1
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/internal/grpcsync/callback_serializer.go:55 +0x129

goroutine 344 [select, 13 minutes]:
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0xc000f4ca00, {0x63424e8, 0xc000f1b040})
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/internal/grpcsync/callback_serializer.go:83 +0x112
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 1
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/internal/grpcsync/callback_serializer.go:55 +0x129

goroutine 345 [select, 13 minutes]:
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0xc000f4ca60, {0x63424e8, 0xc000f1b090})
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/internal/grpcsync/callback_serializer.go:83 +0x112
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 1
	/go/pkg/mod/google.golang.org/grpc@v1.59.0/internal/grpcsync/callback_serializer.go:55 +0x129
```

### 4. What is your TiDB version? (Required)
master

**Comment by tiancaiamao** [comment]
Fixed by https://github.com/pingcap/tidb/pull/48870
Duplicated with https://github.com/pingcap/tidb/issues/48869
