### ISSUE TITLE
goleveldb failed at CI test.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#49]
It happens randomly.

full log is at https://travis-ci.org/pingcap/tidb/jobs/79117789

```
2015/09/07 12:54:47 kv.go:121: [debug] Begin txn:103
2015/09/07 12:54:47 kv.go:121: [debug] Begin txn:104
2015/09/07 12:54:47 txn.go:155: [debug] set key:1, txn:104
2015/09/07 12:54:47 txn.go:155: [debug] set key:1, txn:103
2015/09/07 12:54:47 txn.go:266: [info] commit txn 104
2015/09/07 12:54:47 txn.go:266: [info] commit txn 104
panic: runtime error: index out of range
goroutine 115 [running]:
github.com/syndtr/goleveldb/leveldb/memdb.(*dbIter).Next(0xc208084880, 0xc208084800)
	/home/travis/gopath/src/github.com/pingcap/tidb/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/memdb/memdb.go:129 +0x187
github.com/pingcap/tidb/store/localstore.(*dbTxn).each(0xc208096900, 0xc20a7aedb8, 0x0, 0x0)
	github.com/pingcap/tidb/store/localstore/_test/_obj_test/txn.go:201 +0x158
github.com/pingcap/tidb/store/localstore.(*dbTxn).doCommit(0xc208096900, 0x0, 0x0)
	github.com/pingcap/tidb/store/localstore/_test/_obj_test/txn.go:248 +0x405
github.com/pingcap/tidb/store/localstore.(*dbTxn).Commit(0xc208096900, 0x0, 0x0)
	github.com/pingcap/tidb/store/localstore/_test/_obj_test/txn.go:273 +0x1ba
github.com/pingcap/tidb/store/localstore.func·005()
	/home/travis/gopath/src/github.com/pingcap/tidb/store/localstore/kv_test.go:471 +0x234
created by github.com/pingcap/tidb/store/localstore.(*testKVSuite).TestConditionIfEqual
	/home/travis/gopath/src/github.com/pingcap/tidb/store/localstore/kv_test.go:475 +0x512
```

**Comment by qiuyesuifeng** [comment]
see #50
