### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yibin87** [pingcap/tidb#49413]
## Bug Report
Commit: 9bf043bae08bd536c145980371285208d10e1c11

Records log from loki of regression tests, no more call stack found:

2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763101655+08:00 stderr F \t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x145"} |  
-- | -- | --
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763099252+08:00 stderr F created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 726849"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763096328+08:00 stderr F \t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x86"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763093616+08:00 stderr F google.golang.org/grpc.(*Server).serveStreams.func1.1()"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763090569+08:00 stderr F \t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1741 +0xbfb"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763087609+08:00 stderr F google.golang.org/grpc.(*Server).handleStream(0xc0033e7680, {0x63a2600, 0xc006f7d380}, 0xc01fe42ea0)"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763084691+08:00 stderr F \t/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1637 +0x1348"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763079198+08:00 stderr F google.golang.org/grpc.(*Server).processStreamingRPC(0xc0033e7680, {0x6382b80, 0xc006afdc80}, {0x63a2600, 0xc006f7d380}, 0xc01fe42ea0, 0xc002970d50, 0x8b07a00, 0x0)"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763074446+08:00 stderr F \t/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20231122054644-fb0f5c2a0a10/pkg/tikvpb/tikvpb.pb.go:3404 +0x91"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763068952+08:00 stderr F github.com/pingcap/kvproto/pkg/tikvpb._Tikv_BatchRaft_Handler({0x596bdc0?, 0xc002970c30}, {0x638b1e8?, 0xc00ee7fd10})"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763057775+08:00 stderr F \t<autogenerated>:1 +0x29"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763054843+08:00 stderr F github.com/pingcap/tidb/pkg/server.(*rpcServer).BatchRaft(0xc0011bbad8?, {0x639eca0?, 0xc00bc8ab30?})"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.76305091+08:00 stderr F goroutine 726885 [running]:"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763047567+08:00 stderr F "} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763043641+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4e51be9]"} |  
  |   | 2023-12-12 12:40:54 | {"namespace":"e2e-htap-misc-tps-5130986-1-753","pod":"tc-tidb-0","container":"tidb","log":"2023-12-12T12:40:54.763008807+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference"} |

**Comment by yibin87** [comment]
It seemed unexpected "BatchRaft" rpc request is sent to tidb server, and tidb rpc server doesn't implement it, then cause this panic.

**Comment by yibin87** [comment]
server.(*rpcServer).KvPrewrite is detected to be sent to tidb http server also.

**Comment by cfzjywxk** [comment]
Is the mockstore being used in tests?

**Comment by yibin87** [comment]
> Is the mockstore being used in tests?

No, tikv is used
