### ISSUE TITLE
panic in the TestAlterAddConstraintStateChange3

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#49825]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
panic: runtime error: index out of range [0] with length 0
goroutine 80540 [running]:
github.com/pingcap/tidb/pkg/ddl_test.TestAlterAddConstraintStateChange3.func1(0xc011fc5e00)
	pkg/ddl/constraint_test.go:235 +0x5af
github.com/pingcap/tidb/pkg/ddl/util/callback.(*TestDDLCallback).OnJobUpdated(0xc013e23e30, 0xc011fc5e00?)
	pkg/ddl/util/callback/callback.go:124 +0x1dd
github.com/pingcap/tidb/pkg/ddl.(*ddl).delivery2worker.func1()
	pkg/ddl/job_table.go:439 +0x171b
github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
	pkg/util/wait_group_wrapper.go:157 +0x87
created by github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run in goroutine 79460
	pkg/util/wait_group_wrapper.go:155 +0xe5 
```

**Comment by hawkingrei** [comment]
https://tiprow.hawkingrei.com/view/gs/pingcapprow/logs/tidb_data_race/1739835333379362816#1:build-log.txt%3A6221
