### ISSUE TITLE
`TestManagerDispatchLoop` test will panic by `make ut`

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#49962]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2e1882d]

goroutine 16483 [running]:
github.com/pingcap/tidb/pkg/disttask/framework/scheduler.(*Manager).startScheduler(0xc0078cb050, 0xc0052a40d0, {0x0, 0x0})
    /home/jasonmo/tidb/pkg/disttask/framework/scheduler/scheduler_manager.go:267 +0x20d
github.com/pingcap/tidb/pkg/disttask/framework/scheduler.(*Manager).scheduleTaskLoop(0xc0078cb050)
    /home/jasonmo/tidb/pkg/disttask/framework/scheduler/scheduler_manager.go:219 +0xf70
github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
    /home/jasonmo/tidb/pkg/util/wait_group_wrapper.go:157 +0x4f
created by github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run in goroutine 14415
    /home/jasonmo/tidb/pkg/util/wait_group_wrapper.go:155 +0x73
make: *** [Makefile:133: ut] Error 1
```

**Comment by D3Hunter** [comment]
root cause duplicate with https://github.com/pingcap/tidb/issues/49869
