### ISSUE TITLE
[Randgen] Panic on optimizer_subquery_portable.yy

### ISSUE THREAD

**Issue by sokoow** [pingcap/tidb#4997]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
- download randgen https://launchpad.net/randgen
- build TIDB 1.0.1 (1.1.0 doesn't build sucessfully)
- run desired test: ```./gentest.pl --dsn dbi:mysql:host=127.0.0.1:port=4000:user=root:database=test --grammar=conf/optimizer_subquery_portable.yy --gendata --thread=1```

2. What did you expect to see?
Test passing

3. What did you see instead?
TIDB panic with :

```
panic: runtime error: index out of range

goroutine 8713 [running]:
github.com/pingcap/tidb/expression.(*Column).Eval(0xc420686ea0, 0xc4215d4160, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/pingcap/tidb/expression/column.go:197 +0x99
github.com/pingcap/tidb/expression.EvalBool(0xc420ffc250, 0x1, 0x1, 0xc4215d4160, 0x3, 0x3, 0x18ac880, 0xc421ef2780, 0x0, 0xc4222ba000, ...)
        /go/src/github.com/pingcap/tidb/expression/expression.go:103 +0xac
github.com/pingcap/tidb/executor.(*HashJoinExec).constructMatchedRows(0xc42172a900, 0xc42236eb40, 0xc422762a80, 0x2, 0x2, 0x2, 0x18ac880, 0xc421ef2780, 0x1, 0x0)
        /go/src/github.com/pingcap/tidb/executor/join.go:388 +0x3fb
github.com/pingcap/tidb/executor.(*HashJoinExec).joinOneBigRow(0xc42172a900, 0xc42236eb40, 0xc422762a80, 0x2, 0x2, 0xc420eb9530, 0xc421b8d140)
        /go/src/github.com/pingcap/tidb/executor/join.go:347 +0x3e1
github.com/pingcap/tidb/executor.(*HashJoinExec).runJoinWorker(0xc42172a900, 0x3)
        /go/src/github.com/pingcap/tidb/executor/join.go:316 +0x2a9
created by github.com/pingcap/tidb/executor.(*HashJoinExec).prepare
        /go/src/github.com/pingcap/tidb/executor/join.go:250 +0x52a
```

4. What version of TiDB are you using (`tidb-server -V`)?
1.0.1

**Comment by shenli** [comment]
@sokoow Thanks! We will fix it soon.

**Comment by XuHuaiyu** [comment]
``` sql
drop table if exists t1;
drop table if exists t2;


CREATE TABLE `t1` (
  `pk` int(11) NOT NULL AUTO_INCREMENT primary key,
  `a` int(11) DEFAULT NULL,
  `b` date DEFAULT NULL,
  `c` varchar(1) DEFAULT NULL,
  KEY `a` (`a`),
  KEY `b` (`b`),
  KEY `c` (`c`,`a`)
) ;

CREATE TABLE `t2` (
  `pk` int(11) NOT NULL AUTO_INCREMENT primary key,
  `a` int(11) DEFAULT NULL,
  `b` date DEFAULT NULL,
  `c` varchar(1) DEFAULT NULL,
  KEY `a` (`a`),
  KEY `b` (`b`),
  KEY `c` (`c`,`a`)
) ;

insert into t1 value(1,1,"2000-11-11", null);

SELECT  table2 . `b` AS field2 

FROM 

( 
  t1 AS table1 

  LEFT OUTER JOIN 

  (  SELECT   tmp_t2 . * FROM ( t2 AS tmp_t1 RIGHT  JOIN t1 AS tmp_t2 ON (tmp_t2 . `a` = tmp_t1 . `a`))) AS table2 

  ON (table2 . `c` = table1 . `c`  ) 

) 

```
This case can reproduce the bug.
