### ISSUE TITLE
panic in the br/pkg/backup/prepare_snap.(*prepareStream).convertToEvent

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#50751]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e0dc3a]
goroutine 87 [running]:
github.com/pingcap/tidb/br/pkg/backup/prepare_snap.(*prepareStream).convertToEvent(0xc000554140, 0x0)
	br/pkg/backup/prepare_snap/stream.go:188 +0x5a
github.com/pingcap/tidb/br/pkg/backup/prepare_snap.(*prepareStream).onResponse(0xc000554140, {0x3202bc0, 0xc0002fe550}, {{0x0?, 0x0?}, 0x0?})
	br/pkg/backup/prepare_snap/stream.go:107 +0x1bd
github.com/pingcap/tidb/br/pkg/backup/prepare_snap.(*prepareStream).clientLoop(0xc000554140, {0x3202bc0, 0xc0002fe550}, 0x1bf08eb000)
	br/pkg/backup/prepare_snap/stream.go:152 +0x2c9
github.com/pingcap/tidb/br/pkg/backup/prepare_snap.(*prepareStream).GoLeaseLoop.func1()
	br/pkg/backup/prepare_snap/stream.go:97 +0x55
golang.org/x/sync/errgroup.(*Group).Go.func1()
	external/org_golang_x_sync/errgroup/errgroup.go:78 +0x98
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 69
	external/org_golang_x_sync/errgroup/errgroup.go:75 +0x125 
```

https://tiprow.hawkingrei.com/view/gs/pingcapprow/logs/tidb_data_race/1750748952065478656#1:build-log.txt%3A1070

**Comment by BornChanger** [comment]
please close it since the problem does not appear now.
