### ISSUE TITLE
TiDB server panic when executing builtin function 'bit_xor'

### ISSUE THREAD

**Issue by spongedu** [pingcap/tidb#5077]
1. What did you do?
```sql
tidb> create table t ( a int);
Query OK, 0 rows affected (0.00 sec)

tidb> select bit_xor(a) from t;
```

2. What did you expect to see?
```sql
+------------+
| bit_xor(a) |
+------------+
|          0 |
+------------+
1 row in set (0.01 sec)
```

3. What did you see instead?
```sql
tidb> select bit_xor(a) from t;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
See tidb-server's log, found:
```
2017/11/13 10:30:30.063 conn.go:390: [error] lastCmd select bit_xor(a) from t, runtime error: invalid memory address or nil pointer dereference, goroutine 27 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc420198160)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/server/conn.go:388 +0xfd
panic(0x1c31040, 0x26f86b0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/plan.(*planBuilder).buildAggregation(0xc4201a9600, 0x2526820, 0xc4201a96b0, 0xc4203051f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x100ec68, ...)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/plan/logical_plan_builder.go:109 +0x973
github.com/pingcap/tidb/plan.(*planBuilder).buildSelect(0xc4201a9600, 0xc420c341e0, 0x0, 0x0)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/plan/logical_plan_builder.go:1496 +0xc72
github.com/pingcap/tidb/plan.(*planBuilder).build(0xc4201a9600, 0x2502520, 0xc420c341e0, 0x0, 0xc4209f9620)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/plan/planbuilder.go:188 +0x5a3
github.com/pingcap/tidb/plan.Optimize(0x2520680, 0xc420a8e6e0, 0x2502520, 0xc420c341e0, 0x250dbc0, 0xc420f4af60, 0x2769200, 0x0, 0x0, 0xd)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/plan/optimizer.go:67 +0x12f
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc42097d96e, 0x2520680, 0xc420a8e6e0, 0x25064e0, 0xc420c341e0, 0x0, 0x0, 0x0)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/executor/compiler.go:44 +0x1a5
github.com/pingcap/tidb.(*session).Execute(0xc420a8e6e0, 0x2af4270, 0xc4209f9500, 0xc4202ab721, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/session.go:761 +0xa6b
github.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc420bd63f0, 0x2af4270, 0xc4209f9500, 0xc4202ab721, 0x18, 0xc42097dc68, 0x1029f49, 0xc4209d63f0, 0xc42097dc88, 0x20)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/server/driver_tidb.go:195 +0x7c
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc420198160, 0x2af4270, 0xc4209f9500, 0xc4202ab721, 0x18, 0x0, 0x0)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/server/conn.go:735 +0x8d
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc420198160, 0xc4202ab721, 0x19, 0x19, 0x0, 0x0)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/server/conn.go:524 +0x505
github.com/pingcap/tidb/server.(*clientConn).Run(0xc420198160)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/server/conn.go:411 +0x18a
github.com/pingcap/tidb/server.(*Server).onConn(0xc420b4c540, 0x250baa0, 0xc42000c738)
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/server/server.go:298 +0x144
created by github.com/pingcap/tidb/server.(*Server).Run
        /Users/duchuan.dc/go/src/github.com/pingcap/tidb/server/server.go:244 +0x76

```

4. What version of TiDB are you using (`tidb-server -V`)?
$ ./bin/tidb-server -V
Release Version: v1.1.0-alpha-113-g7903c5c21
Git Commit Hash: 7903c5c211e4f1addc1b4730ecfce2ebd15cde76
Git Commit Branch: master
UTC Build Time:  2017-11-13 02:23:20

**Comment by shenli** [comment]
@spongedu Thanks for your feedback!

**Comment by spongedu** [comment]
see `expression/aggregation/aggregation.go`:
```go
 82 // NewAggFunction creates a new Aggregation.
 83 func NewAggFunction(funcType string, funcArgs []expression.Expression, distinct bool) Aggregation {
 84     switch tp := strings.ToLower(funcType); tp {
 85     case ast.AggFuncSum:
 86         return &sumFunction{aggFunction: newAggFunc(tp, funcArgs, distinct)}
 87     case ast.AggFuncCount:
 88         return &countFunction{aggFunction: newAggFunc(tp, funcArgs, distinct)}
 89     case ast.AggFuncAvg:
 90         return &avgFunction{aggFunction: newAggFunc(tp, funcArgs, distinct)}
 91     case ast.AggFuncGroupConcat:
 92         return &concatFunction{aggFunction: newAggFunc(tp, funcArgs, distinct)}
 93     case ast.AggFuncMax:
 94         return &maxMinFunction{aggFunction: newAggFunc(tp, funcArgs, distinct), isMax: true}
 95     case ast.AggFuncMin:
 96         return &maxMinFunction{aggFunction: newAggFunc(tp, funcArgs, distinct), isMax: false}
 97     case ast.AggFuncFirstRow:
 98         return &firstRowFunction{aggFunction: newAggFunc(tp, funcArgs, distinct)}
 99     }
100     return nil
101 }
```

`BIT_XOR` seems not supported yet.

**Comment by zz-jason** [comment]
@spongedu Seems we can throw an error in `NewAggFunction` when aggregation function is not supported, can you help us to do it?

**Comment by spongedu** [comment]
@zz-jason yep. Will do it.

**Comment by zz-jason** [comment]
@spongedu  OK, thanks !
