### ISSUE TITLE
Panic in the TestVerifyChecksum

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#51951]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7df2d15]
goroutine 33670 [running]:
github.com/pingcap/tidb/pkg/distsql.(*selectResult).Close(0xc009ae8380)
	pkg/distsql/select_result.go:610 +0x175
github.com/pingcap/tidb/pkg/executor.(*ChecksumTableExec).handleChecksumRequest.func1()
	pkg/executor/checksum.go:159 +0x29
github.com/pingcap/tidb/pkg/executor.(*ChecksumTableExec).handleChecksumRequest(0xc0063f8960, 0xc008f6aa80?)
	pkg/executor/checksum.go:170 +0x3e5
github.com/pingcap/tidb/pkg/executor.(*ChecksumTableExec).checksumWorker(0xc00a23cc40?, 0xc0000324d0?, 0xc007bb6fb0?)
	pkg/executor/checksum.go:144 +0xa7
created by github.com/pingcap/tidb/pkg/executor.(*ChecksumTableExec).Open in goroutine 223
	pkg/executor/checksum.go:64 +0x105
================================================================================
```

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/51916/fast_test_tiprow/1770373340058357760#1:build-log.txt%3A2591

**Comment by D3Hunter** [comment]
same root cause as this https://github.com/pingcap/tidb/issues/51928
