### ISSUE TITLE
tidb-server crashes with concurrent map writes when dropRegionFromCache

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#5203]
https://github.com/pingcap/tidb/blob/191de50646f394865a7a8edf4c8b6ecb40ab3841/store/tikv/region_cache.go#L322

```
fatal error: concurrent map writes

goroutine 97560 [running]:
runtime.throw(0x11b1a58, 0x15)
        /usr/local/go1.9.2/src/runtime/panic.go:605 +0x95 fp=0xc4243d1590 sp=0xc4243d1570 pc=0x42bce5
runtime.mapdelete(0x1010300, 0xc42044a1b0, 0xc4243d1640)
        /usr/local/go1.9.2/src/runtime/hashmap.go:704 +0x2f9 fp=0xc4243d15f0 sp=0xc4243d1590 pc=0x409449
github.com/pingcap/tidb/store/tikv.(*RegionCache).dropRegionFromCache(0xc420452060, 0x140738, 0x23, 0x8)
        /go/src/github.com/pingcap/tidb/store/tikv/region_cache.go:322 +0x193 fp=0xc4243d1680 sp=0xc4243d15f0 pc=0xec2f93
github.com/pingcap/tidb/store/tikv.(*RegionCache).getCachedRegion(0xc420452060, 0x140738, 0x23, 0x8, 0x7f3f92a59001)
        /go/src/github.com/pingcap/tidb/store/tikv/region_cache.go:285 +0x14f fp=0xc4243d16f0 sp=0xc4243d1680 pc=0xec2b2f
github.com/pingcap/tidb/store/tikv.(*RegionCache).searchCachedRegion(0xc420452060, 0xc421c7ff60, 0x13, 0x1b, 0xbd1e1b)
        /go/src/github.com/pingcap/tidb/store/tikv/region_cache.go:299 +0x144 fp=0xc4243d1748 sp=0xc4243d16f0 pc=0xec2cb4
github.com/pingcap/tidb/store/tikv.(*RegionCache).LocateKey(0xc420452060, 0xc4243d1b48, 0xc421c7ff60, 0x13, 0x1b, 0x0, 0x0, 0x0)
        /go/src/github.com/pingcap/tidb/store/tikv/region_cache.go:138 +0xaa fp=0xc4243d1848 sp=0xc4243d1748 pc=0xec109a
github.com/pingcap/tidb/store/tikv.buildCopTasks(0xc4243d1b48, 0xc420452060, 0xc4268a7860, 0x0, 0x18e0000, 0xc421226080, 0x456db0, 0x7f3f92a5a458, 0xa)
        /go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:247 +0x765 fp=0xc4243d1ab0 sp=0xc4243d1848 pc=0xeb7dc5
github.com/pingcap/tidb/store/tikv.(*CopClient).Send(0xc420319a40, 0x7f3f92979120, 0xc42178ac80, 0xc422238f00, 0xc42712cc30, 0x946d84)
        /go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:102 +0x164 fp=0xc4243d1bb0 sp=0xc4243d1ab0 pc=0xeb6eb4
github.com/pingcap/tidb/distsql.SelectDAG(0x7f3f92979120, 0xc42178ac80, 0x18ce900, 0xc420319a40, 0xc422238f00, 0xc421818000, 0x8, 0x8, 0x1b1f720, 0x0, ...)
        /go/src/github.com/pingcap/tidb/distsql/distsql.go:276 +0xdc fp=0xc4243d1c40 sp=0xc4243d1bb0 pc=0xcb08cc
github.com/pingcap/tidb/executor.(*dataReaderBuilder).buildTableReaderFromHandles(0xc42788fba0, 0x7f3f92979120, 0xc42178ac80, 0xc421de9520, 0xc4289b7400, 0x6f, 0x80, 0xc420678cf0, 0xc42178a2c0, 0x0, ...)
        /go/src/github.com/pingcap/tidb/executor/builder.go:1165 +0x30b fp=0xc4243d1d40 sp=0xc4243d1c40 pc=0xd6479b
github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).executeTask(0xc4210b9b00, 0xc4223eabe0, 0x7f3f92979120, 0xc42178ac80)
        /go/src/github.com/pingcap/tidb/executor/distsql.go:724 +0x1d9 fp=0xc4243d1ea8 sp=0xc4243d1d40 pc=0xd70839
github.com/pingcap/tidb/executor.(*tableWorker).pickAndExecTask(0xc4210b9be0, 0xc4210b9b00, 0xc422538720, 0x7f3f92979120, 0xc42178ac80, 0xc426b12180)
        /go/src/github.com/pingcap/tidb/executor/distsql.go:671 +0x61 fp=0xc4243d1f68 sp=0xc4243d1ea8 pc=0xd700c1
github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startTableWorker.func1(0xc4210b9be0, 0xc4210b9b00, 0xc422538720, 0x7f3f92979120, 0xc42178ac80, 0xc426b12180, 0xc421307da0)
        /go/src/github.com/pingcap/tidb/executor/distsql.go:653 +0x5d fp=0xc4243d1fa8 sp=0xc4243d1f68 pc=0xdb5fdd
runtime.goexit()
        /usr/local/go1.9.2/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4243d1fb0 sp=0xc4243d1fa8 pc=0x45cbd1
created by github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startTableWorker
        /go/src/github.com/pingcap/tidb/executor/distsql.go:652 +0xfb
```

Release Version: v1.1.0-alpha-149-g191de50
Git Commit Hash: 191de50646f394865a7a8edf4c8b6ecb40ab3841
Git Commit Branch: master
UTC Build Time:  2017-11-23 08:37:10

**Comment by disksing** [comment]
Hi @Darren , could you send us the full output when panic?

**Comment by Darren** [comment]
@disksing 

here's full log:
[concurrent_map_write.log](https://github.com/pingcap/tidb/files/1498591/concurrent_map_write.log)

**Comment by disksing** [comment]
@Darren Thanks for your feedback. I'm fixing it :)

**Comment by shenli** [comment]
Cause by https://github.com/pingcap/tidb/pull/5171
