### ISSUE TITLE
aggregation return wrong field value if using `in` operation in where condition

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#5255]
one query in our tidb-server aborted, 
ERROR 2013 (HY000): Lost connection to MySQL server during query 

This is the test case:

```sql
CREATE TABLE `w` (
  `did` int(11) NOT NULL,
  `day` date NOT NULL,
  `hour` smallint(6) NOT NULL,
  `cid` bigint(20) NOT NULL,
  `pv` int(11) NOT NULL,
  `uv` int(11) NOT NULL,
  PRIMARY KEY (`did`,`day`,`hour`,`cid`)
);

 CREATE TABLE `n` (
  `id` int(11) NOT NULL,
  `name` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id`)
);


insert into w values( 13145 , '2017-11-29' , 0 , 798975615876285 ,  3 ,  3 );
insert into w values( 13145 , '2017-11-29' , 0 , 798975615876317 , 40 , 26 );
insert into w values( 13145 , '2017-11-29' , 0 , 798851061825665 ,  2 ,  2 );
insert into w values( 13145 , '2017-11-29' , 0 , 798975615878295 ,  3 ,  3 );
insert into w values( 13145 , '2017-11-29' , 0 , 798975615878552 ,  4 ,  4 );
insert into w values( 13145 , '2017-11-29' , 0 , 798975615874824 ,  2 ,  2 );
insert into w values( 13145 , '2017-11-29' , 0 , 798657788297451 ,  5 ,  5 );
insert into w values( 13145 , '2017-11-29' , 0 , 798851061822941 ,  5 ,  3 );
insert into w values( 13145 , '2017-11-29' , 0 , 798657788297428 ,  7 ,  7 );
insert into w values( 13145 , '2017-11-29' , 0 , 798975615876441 ,  3 ,  2 );


insert into n values (13145, '客户1');
insert into n values (23345, '客户2');
select sum(pv) as  pv from w join n on n.id=w.did where day = '2017-11-29' and did in (13145)  group by did order by  pv desc,id;
select did, day, sum(pv) as  pv, sum(uv) as  uv from w join n on n.id=w.did where day = '2017-11-29' and id in (13145)  group by did order by  pv desc,id;

```

1. This  value returned  seems like day value instead of  the result of sum(pv) 
```sql
mysql> select sum(pv) as  pv from w join n on n.id=w.did where day = '2017-11-29' and did in (13145)  group by did order by  pv desc,id;
+-----------+
| pv        |
+-----------+
| 201711290 |
+-----------+
```

2. use `=` instead of `in` operator , the result is correct: 
```sql
mysql> select sum(pv) as  pv from w join n on n.id=w.did where day = '2017-11-29' and did = 13145  group by did order by  pv desc,id;
+-----------+
| pv        |
+-----------+
| 74        |
+-----------+
```

3. this sql causes panic:
```sql
select did, day, sum(pv) as  pv, sum(uv) as  uv from w join n on n.id=w.did where day = '2017-11-29' and id in (13145)  group by did order by  pv desc,id;
```
here is trace from tidb-server's log

```
interface conversion: interface {} is nil, not types.Time, goroutine 7297 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc437216790)
        /go/src/github.com/pingcap/tidb/server/conn.go:389 +0xfd
panic(0x103a580, 0xc4373f4080)
        /usr/local/go1.9.2/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/types.(*Datum).GetMysqlTime(...)
        /go/src/github.com/pingcap/tidb/types/datum.go:299
github.com/pingcap/tidb/types.DatumRow.GetTime(...)
        /go/src/github.com/pingcap/tidb/types/row.go:118
github.com/pingcap/tidb/types.(*DatumRow).GetTime(0xc429064dc0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        <autogenerated>:1 +0x1bb
github.com/pingcap/tidb/server.dumpTextRow(0xc42234f800, 0x6, 0x400, 0xc4373f4040, 0x7, 0x8, 0x190e6c0, 0xc429064dc0, 0xc421fb55c0, 0x1, ...)
        /go/src/github.com/pingcap/tidb/server/util.go:311 +0x68e
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc437216790, 0x7fc437c13160, 0xc433c896b0, 0x18f53c0, 0xc433bda4b0, 0xc421fb0000, 0x0, 0x0)
        /go/src/github.com/pingcap/tidb/server/conn.go:831 +0x53a
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc437216790, 0x7fc437c13160, 0xc433c896b0, 0xc4335d16c1, 0x1a0, 0x0, 0x0)
        /go/src/github.com/pingcap/tidb/server/conn.go:748 +0x115
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc437216790, 0xc4335d16c1, 0x1a1, 0x1a1, 0x0, 0x0)
        /go/src/github.com/pingcap/tidb/server/conn.go:530 +0x511
github.com/pingcap/tidb/server.(*clientConn).Run(0xc437216790)
        /go/src/github.com/pingcap/tidb/server/conn.go:412 +0x18a
github.com/pingcap/tidb/server.(*Server).onConn(0xc4210480c0, 0x18f7fa0, 0xc4334fa930)
        /go/src/github.com/pingcap/tidb/server/server.go:315 +0x144
created by github.com/pingcap/tidb/server.(*Server).Run
        /go/src/github.com/pingcap/tidb/server/server.go:261 +0x496
```
Release Version: v1.1.0-alpha-180-g69c9e4e-dirty
Git Commit Hash: 69c9e4efe4a63bb3a9e073a2ef8b26e07c032e74
Git Branch: master
UTC Build Time: 2017-11-28 04:54:55

**Comment by shenli** [comment]
@Darren Thanks!
@zz-jason @XuHuaiyu PTAL

**Comment by Darren** [comment]
@shenli @zz-jason @XuHuaiyu 

I have prepared a simplest test case which is reproducible on a bare tidb-server (no tikv needed)

**Comment by shenli** [comment]
@Darren Cool!

**Comment by XuHuaiyu** [comment]
PTAL @winoros

**Comment by winoros** [comment]
Hello, you can try the current master, let me know if there's still bug exists.

**Comment by Darren** [comment]
@winoros 

I've tested  lastest master and I have got the right result!  well done.

But the query on tidb is slower than MySQL: 1 min 31.12 sec  vs  0.95 sec, but that maybe not related with this bug, I'll open another if I can create a test case.

**Comment by winoros** [comment]
Ok, thanks.
