### ISSUE TITLE
TiDB panics on topsql

### ISSUE THREAD

**Issue by CbcWestwolf** [pingcap/tidb#52670]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

TiDB runs normally

### 3. What did you see instead (Required)

TiDB panics and the stack is :

```
2024-04-17 10:29:16	
panic: runtime error: invalid memory address or nil pointer dereference
2024-04-17 10:29:16	
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e4b618]
2024-04-17 10:29:16	
2024-04-17 10:29:16	
goroutine 82607435825 [running]:
2024-04-17 10:29:16	
google.golang.org/grpc/internal/status.(*Error).Error(0x44130e5238?)
2024-04-17 10:29:16	
	/go/pkg/mod/google.golang.org/grpc@v1.51.0/internal/status/status.go:150 +0x18
2024-04-17 10:29:16	
github.com/pingcap/log.(*textEncoder).encodeError(0x4425facfc0, {{0x4a20322, 0x5}, 0x1a, 0x0, {0x0, 0x0}, {0x455f3a0, 0x0}})
2024-04-17 10:29:16	
	/go/pkg/mod/github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/zap_text_encoder.go:647 +0x68
2024-04-17 10:29:16	
github.com/pingcap/log.(*textEncoder).addFields(0x4425facfc0, {0x4425facf80?, 0x1, 0x68?})
2024-04-17 10:29:16	
	/go/pkg/mod/github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/zap_text_encoder.go:636 +0x288
2024-04-17 10:29:16	
github.com/pingcap/log.(*textEncoder).EncodeEntry(0x40000ffd40, {0x1, {0xc17feadf124f3391, 0x1e14dbe038d210, 0x7a0ed80}, {0x0, 0x0}, {0x4b108ed, 0x3b}, {0x1, ...}, ...}, ...)
2024-04-17 10:29:16	
	/go/pkg/mod/github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/zap_text_encoder.go:466 +0xb10
2024-04-17 10:29:16	
github.com/pingcap/log.(*TextIOCore).Write(0x40012dc540, {0x1, {0xc17feadf124f3391, 0x1e14dbe038d210, 0x7a0ed80}, {0x0, 0x0}, {0x4b108ed, 0x3b}, {0x1, ...}, ...}, ...)
2024-04-17 10:29:16	
	/go/pkg/mod/github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/zap_text_core.go:64 +0x5c
2024-04-17 10:29:16	
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x434d989c70, {0x4425facf80, 0x1, 0x1})
2024-04-17 10:29:16	
	/go/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:255 +0x158
2024-04-17 10:29:16	
go.uber.org/zap.(*Logger).Warn(0x47ea740?, {0x4b108ed?, 0x43dbee4990?}, {0x4425facf80, 0x1, 0x1})
2024-04-17 10:29:16	
	/go/pkg/mod/go.uber.org/zap@v1.23.0/logger.go:221 +0x54
2024-04-17 10:29:16	
github.com/pingcap/tidb/util/topsql/reporter.(*pubSubDataSink).run(0x4439f7f300)
2024-04-17 10:29:16	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/topsql/reporter/pubsub.go:136 +0x43c
2024-04-17 10:29:16	
github.com/pingcap/tidb/util/topsql/reporter.(*TopSQLPubSubService).Subscribe(0x40013dcfc0, 0x474e720?, {0x52c3610?, 0x427cede050?})
2024-04-17 10:29:16	
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/topsql/reporter/pubsub.go:51 +0x80
2024-04-17 10:29:16	
github.com/pingcap/tipb/go-tipb._TopSQLPubSub_Subscribe_Handler({0x4426ac0?, 0x40013dcfc0}, {0x52bb2d0, 0x4463179880})
2024-04-17 10:29:16	
	/go/pkg/mod/github.com/pingcap/tipb@v0.0.0-20221123081521-2fb828910813/go-tipb/topsql_agent.pb.go:685 +0xc0
2024-04-17 10:29:16	
google.golang.org/grpc.(*Server).processStreamingRPC(0x400210ba40, {0x52ccc80, 0x42464f1a00}, 0x442f1d4900, 0x400192c930, 0x720a060, 0x0)
2024-04-17 10:29:16	
	/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1629 +0xf44
2024-04-17 10:29:16	
google.golang.org/grpc.(*Server).handleStream(0x400210ba40, {0x52ccc80, 0x42464f1a00}, 0x442f1d4900, 0x0)
2024-04-17 10:29:16	
	/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1717 +0x818
2024-04-17 10:29:16	
google.golang.org/grpc.(*Server).serveStreams.func1.2()
2024-04-17 10:29:16	
	/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x84
2024-04-17 10:29:16	
created by google.golang.org/grpc.(*Server).serveStreams.func1
2024-04-17 10:29:16	
	/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x294
2024-04-17 10:29:19	
start tidb-server ...
```

It is quite strange to panic on a logging line.

![img_v3_02a1_70891fcb-5a3f-4500-96f1-fcf23f61e82g](https://github.com/pingcap/tidb/assets/18588254/d8a00069-6a88-4154-b368-df93743ec592)

### 4. What is your TiDB version? (Required)

v6.5.7

**Comment by YangKeao** [comment]
Is it related to https://github.com/pingcap/tidb/issues/51301? The backtrace looks similar :thinking:

**Comment by CbcWestwolf** [comment]
@YangKeao Yes, we can close it 😃
