### ISSUE TITLE
infoschema_v2: concurrent map read and map write

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tidb#52684]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
start tidb with tidb_schema_cache_size=1024, create table

### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
```
root@tidb1:/home/tidb/deploy/tidb-4000/log# head -n 500 tidb_stderr.log 
fatal error: concurrent map iteration and map write

goroutine 809 [running]:
reflect.mapiternext(0x582e4e0?)
        /usr/local/go/src/runtime/map.go:1397 +0x13
reflect.Value.MapKeys({0x5635640?, 0xc0026cbea8?, 0xc002b20060?})
        /usr/local/go/src/reflect/value.go:1803 +0x10d
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5635640?, 0xc0026cbea8?, 0x10?}, 0x57202a0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:114 +0x22c
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x597e740?, 0xc0026cbe80?, 0xc000de7b80?}, 0x1d1554b?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x597e800?, 0xc0026cbe80?, 0xc00287bfc0?}, 0xc002a98af0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5a4b2c0?, 0xc0026cbe80?, 0xc0026cbe80?}, 0x543a580?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x58c8640?, 0xc0026d9308?, 0xc0023fb4e0?}, 0x57a35a0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5bad640?, 0xc0026d92d0?, 0xc0026d92d0?}, 0x543a580?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5b6c440?, 0xc0026f2990?, 0x0?}, 0x1d149c8?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5cf60e0?, 0xc0026f2900?, 0xc0026f2900?}, 0x1d019cd?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5c20da0?, 0xc0026f2900?, 0xc002a9cc90?}, 0x56f53c0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5948d20?, 0xc002209da0?, 0xc002b0c1a0?}, 0x57202a0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:141 +0x154
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5bcb000?, 0xc002209b80?, 0xc002209b80?}, 0x1d149c8?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5b2b6c0?, 0xc002a9cc90?, 0x0?}, 0x1d019cd?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x59dfca0?, 0xc002a9cc90?, 0xc002a9cc90?}, 0x56f53c0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x599c980?, 0xc002a9cc90?, 0xc0026f1bf0?}, 0x57202a0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x57a35a0?, 0xc002194260?, 0xc002194260?}, 0x1d52829?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:141 +0x154
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5410820?, 0xc008ad8180?, 0xc0026f1c50?}, 0x0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:53 +0x7d3
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5829e40?, 0xc008ad8180?, 0xc008ad8180?}, 0xc00376c400?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x55e4c20?, 0xc008ad8180?, 0xc0026f1c20?}, 0x1d149c8?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x56bb100?, 0xc0026e7d98?, 0x8?}, 0x57202a0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:141 +0x154
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x59dfbc0?, 0xc0026e7d80?, 0xc0026e7d80?}, 0x1d149c8?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x57d6ce0?, 0xc002b0e2c8?, 0xc002654160?}, 0xc00067bd40?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5c1f0c0?, 0xc002b0e000?, 0xc002b0e000?}, 0x543a4c0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5c1f360?, 0xc00202ff10?, 0xc0015cddb0?}, 0x1d149c8?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x576d9a0?, 0xc00202ff10?, 0xc00202ff10?}, 0xc00292c750?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x585e400?, 0xc00202ff10?, 0xc0026cbd00?}, 0x543a280?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x57e3940?, 0xc0028792b0?, 0x1d0bdfd?}, 0x7f46debf6d28?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:141 +0x154
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x574f0a0?, 0xc0028792b0?, 0xc0028792b0?}, 0x57202a0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5853d20?, 0xc0028792b0?, 0x1644?}, 0x192f?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x57e3940?, 0xc002a9cd20?, 0x8?}, 0x57202a0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:141 +0x154
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x58129c0?, 0xc002a9cd20?, 0xc002a9cd20?}, 0x0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x593fde0?, 0xc002a9cd20?, 0xc000510000?}, 0xc002846600?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5812920?, 0xc0026eba40?, 0xc0001d8040?}, 0x0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:141 +0x154
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5cf9c40?, 0xc0026eba40?, 0xc0026eba40?}, 0xc0022d9080?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5ceb260?, 0xc00287b7c0?, 0x9915200?}, 0x0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x58a9500?, 0xc00287b7c0?, 0xc00287b7c0?}, 0x7f46940225e0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x574ec20?, 0xc00c350a10?, 0xc00e642000?}, 0x57202a0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5ab5740?, 0xc00c3509f0?, 0xc00c3509f0?}, 0x100?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5aa5c80?, 0xc00c3509f0?, 0xc00c350a20?}, 0x57202a0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x58a9380?, 0xc010178e90?, 0xc010178e80?}, 0xc0015cef38?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:141 +0x154
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x53ed8a0?, 0xc01059dda8?, 0xc00e642000?}, 0xc0077f05a0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:53 +0x7d3
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5965600?, 0xc01059dda0?, 0x1d149c8?}, 0x1644?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5bd9dc0?, 0xc01059dce0?, 0xc01059dce0?}, 0xc00c9c80c0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5ca2840?, 0xc01059dce0?, 0xe?}, 0xc00fc3c4e0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:93 +0x352
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5a13980?, 0xc00c9c8110?, 0x1d2183c?}, 0x994af60?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:141 +0x154
github.com/pingcap/tidb/pkg/infoschema/internal.sizeOf({0x5a105a0?, 0xc00c9c8100?, 0x7fffffffffffffff?}, 0x0?)
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:64 +0x65a
github.com/pingcap/tidb/pkg/infoschema/internal.Sizeof({0x55f7700, 0xc00c9c8100})
        /home/gmhdbjd/code/tidb/pkg/infoschema/internal/sizer.go:28 +0x11e
github.com/pingcap/tidb/pkg/infoschema.(*entry[...]).Size(0xc005c14900)
        /home/gmhdbjd/code/tidb/pkg/infoschema/sieve.go:36 +0x28
github.com/pingcap/tidb/pkg/infoschema.(*Sieve[...]).Set(0x6804f80, {0x1ce, 0x15d}, {0x67c0030, 0xc01059dce0?})
        /home/gmhdbjd/code/tidb/pkg/infoschema/sieve.go:96 +0x1d6
github.com/pingcap/tidb/pkg/infoschema.(*infoschemaV2).TableByID(0xc00535c008, 0x1ce)
        /home/gmhdbjd/code/tidb/pkg/infoschema/infoschema_v2.go:310 +0x24a
github.com/pingcap/tidb/pkg/infoschema.(*infoschemaV2).SchemaTables(0xc00535c008, {{0xc00d639020?, 0x1644?}, {0xc00d639024?, 0xc0015cf9e0?}})
        /home/gmhdbjd/code/tidb/pkg/infoschema/infoschema_v2.go:544 +0x385
github.com/pingcap/tidb/pkg/statistics/handle/util.buildPartitionID2TableID({0x67cce90, 0xc00535c008})
        /home/gmhdbjd/code/tidb/pkg/statistics/handle/util/table_info.go:63 +0xa7
github.com/pingcap/tidb/pkg/statistics/handle/util.(*tableInfoGetterImpl).TableInfoByID(0xc001e90bd0, {0x67cce90, 0xc00535c008}, 0xc0015cfa01?)
        /home/gmhdbjd/code/tidb/pkg/statistics/handle/util/table_info.go:52 +0xc5
github.com/pingcap/tidb/pkg/statistics/handle/cache.(*StatsCacheImpl).Update(0xc000426c00, {0x67cce90, 0xc00535c008})
        /home/gmhdbjd/code/tidb/pkg/statistics/handle/cache/statscache.go:92 +0x344
github.com/pingcap/tidb/pkg/domain.(*Domain).loadStatsWorker(0xc002aa6000)
        /home/gmhdbjd/code/tidb/pkg/domain/domain.go:2330 +0x1cd
github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run.func1()
        /home/gmhdbjd/code/tidb/pkg/util/wait_group_wrapper.go:99 +0x6c
created by github.com/pingcap/tidb/pkg/util.(*WaitGroupEnhancedWrapper).Run in goroutine 1
        /home/gmhdbjd/code/tidb/pkg/util/wait_group_wrapper.go:94 +0xbd
```
### 4. What is your TiDB version? (Required)
nightly

**Comment by GMHDBJD** [comment]
close via https://github.com/pingcap/tidb/pull/52423

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/50959
