### ISSUE TITLE
flaky test in the flashback_test

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#53158]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
panic: region 40 is in flashback progress, FlashbackStartTS is 449658828228919302



goroutine 175816 [running]:

github.com/pingcap/tidb/pkg/infoschema.(*infoschemaV2).SchemaTables(0xc018854c00, {{0xc01fb590fc?, 0xc007625680?}, {0xc01fb5910c?, 0xc021880180?}})

	pkg/infoschema/infoschema_v2.go:600 +0x512

github.com/pingcap/tidb/pkg/ddl.(*ddl).refreshTiFlashTicker(0xc0207c50e0, {0xa070590, 0xc007625680}, 0xc021880180)

	pkg/ddl/ddl_tiflash_api.go:455 +0x623

github.com/pingcap/tidb/pkg/ddl.(*ddl).PollTiFlashRoutine(0xc0207c50e0)

	pkg/ddl/ddl_tiflash_api.go:588 +0x9c5

github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()

	pkg/util/wait_group_wrapper.go:157 +0x9e

created by github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run in goroutine 175139

	pkg/util/wait_group_wrapper.go:155 +0xf1

```

**Comment by Defined2014** [comment]
Caused by https://github.com/pingcap/tidb/pull/52896, PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
Only affect master branch

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/50959
