### ISSUE TITLE
close of closed channel for UnionExec

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#5327]
Please answer these questions before submitting your issue. Thanks!
PTAL @zz-jason 

1. What did you do?
```
./gentest.pl --dsn dbi:mysql:host=127.0.0.1:port=4000:user=root:database=test --grammar=conf/optimizer_subquery.yy --gendata --thread=1
```

``` sql
SELECT     ( SELECT   MIN(  SUBQUERY1_t2 . `pk` ) AS SUBQUERY1_field1 FROM ( C AS SUBQUERY1_t1 INNER JOIN D AS SUBQUERY1_t2 ON (SUBQUERY1_t2 . `col_varchar_key` = SUBQUERY1_t1 . `col_varchar_key`  ) ) WHERE SUBQUERY1_t1 . `col_varchar_key` <= table1 . `col_varchar_key` AND SUBQUERY1_t2 . `col_varchar_key` >= SUBQUERY1_t1 . `col_varchar_nokey` ) AS field1 , COUNT(  table1 . `col_int_nokey` ) AS field2 , COUNT(  table2 . `pk` ) AS field3 , table1 . `col_date_key` AS field4 , table1 . `col_varchar_nokey` AS field5 , table1 . `col_varchar_nokey` AS field6 FROM ( (  SELECT   SUBQUERY2_t1 . * FROM ( C AS SUBQUERY2_t1 STRAIGHT_JOIN C AS SUBQUERY2_t2 ON (SUBQUERY2_t2 . `col_int_key` = SUBQUERY2_t1 . `pk`  ) )  ) AS table1 STRAIGHT_JOIN ( ( (  SELECT   SUBQUERY3_t2 . * FROM ( C AS SUBQUERY3_t1 INNER JOIN B AS SUBQUERY3_t2 ON (SUBQUERY3_t2 . `col_int_key` = SUBQUERY3_t1 . `col_int_key`  ) ) WHERE ( SUBQUERY3_t2 . `col_varchar_key` = 'j' OR SUBQUERY3_t2 . `pk` >= 5 ) ) AS table2 STRAIGHT_JOIN C AS table3 ON (table3 . `col_int_key` = table2 . `col_int_nokey`  ) ) ) ON (table3 . `col_varchar_key` = table2 . `col_varchar_nokey`  ) ) WHERE (  table1 . `col_varchar_key` <= ALL ( SELECT 'o' UNION DISTINCT SELECT 'h' ) ) AND table1 . `col_varchar_key` = 'l' OR table2 . `col_varchar_key` <> 'k'  GROUP BY field1, field4, field5, field6;
```

[createtable.txt](https://github.com/pingcap/tidb/files/1534394/createtable.txt)

2. What did you expect to see?

no error occurred

3. What did you see instead?

`MySQL console will not raise an error, TiDB log does.`

```
close of closed channel, goroutine 9718 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc421186000)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:389 +0xfd
panic(0x1c46420, 0x1ecd040)
	/Users/xuhuaiyu/.gvm/gos/go1.9/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/executor.(*UnionExec).Close(0xc4211d8d00, 0xc421719850, 0x19a7254)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor.go:1089 +0x63
github.com/pingcap/tidb/executor.(*HashAggExec).Close(0xc420f064d0, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/aggregate.go:49 +0x8a
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc4208884e0, 0x1bdae60, 0x2553501)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor.go:124 +0x73
github.com/pingcap/tidb/executor.(*HashJoinExec).Close(0xc4208884e0, 0xbb, 0x4000)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/join.go:75 +0x6f
github.com/pingcap/tidb/executor.(*HashAggExec).Close(0xc420f068f0, 0xc42143c318, 0xc4217199a0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/aggregate.go:49 +0x8a
github.com/pingcap/tidb/executor.(*NestedLoopJoinExec).Close(0xc421448900, 0xbb, 0x4000)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/join.go:478 +0x90
github.com/pingcap/tidb/executor.(*ApplyJoinExec).Close(0xc42066a320, 0x1156bc3, 0xc42094a0b2)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/join.go:804 +0x34
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc420927f80, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor.go:124 +0x73
github.com/pingcap/tidb/executor.(*SortExec).Close(0xc4210a83c0, 0xc4206349c0, 0xc42114e009)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/sort.go:62 +0x6d
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc4211a6080, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/executor.go:124 +0x73
github.com/pingcap/tidb/executor.(*recordSet).Close(0xc421ce4cc0, 0x3, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/executor/adapter.go:123 +0x38
github.com/pingcap/tidb/server.(*tidbResultSet).Close(0xc420827500, 0x0, 0xc4206349c8)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/driver_tidb.go:310 +0x33
github.com/pingcap/tidb/server.(ResultSet).Close-fm(0x1e24f40, 0xc421719b18)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:792 +0x2f
github.com/pingcap/tidb/terror.Call(0xc421719bc8)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/terror/terror.go:333 +0x2b
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc421186000, 0x2b39230, 0xc42085ae40, 0x2534980, 0xc420827500, 0xc420810000, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:848 +0x4d7
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc421186000, 0x2b39230, 0xc42085ae40, 0xc420990d81, 0x406, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:748 +0x115
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc421186000, 0xc420990d81, 0x407, 0x407, 0x0, 0x0)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:530 +0x511
github.com/pingcap/tidb/server.(*clientConn).Run(0xc421186000)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/conn.go:412 +0x18a
github.com/pingcap/tidb/server.(*Server).onConn(0xc4203bff20, 0x2537560, 0xc420e80060)
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/server.go:315 +0x144
created by github.com/pingcap/tidb/server.(*Server).Run
	/Users/xuhuaiyu/Development/GOPATH/src/github.com/pingcap/tidb/server/server.go:261 +0x496

```

4. What version of TiDB are you using (`tidb-server -V`)?
githash: 38f794d875ef64ac68a81ac2d8109d3690bcaf74

**Comment by zz-jason** [comment]
query sql is:
```sql
SELECT ( SELECT MIN(SUBQUERY1_t2.`pk`) AS SUBQUERY1_field1 FROM ( C AS SUBQUERY1_t1 INNER JOIN D AS SUBQUERY1_t2 ON (SUBQUERY1_t2.`col_varchar_key` = SUBQUERY1_t1.`col_varchar_key`)) WHERE SUBQUERY1_t1.`col_varchar_key` <= table1.`col_varchar_key` AND SUBQUERY1_t2.`col_varchar_key` >= SUBQUERY1_t1. `col_varchar_nokey`) AS field1, COUNT(table1.`col_int_nokey`) AS field2, COUNT(table2.`pk`) AS field3, table1.`col_date_key` AS field4, table1.`col_varchar_nokey` AS field5, table1.`col_varchar_nokey` AS field6 FROM ( (SELECT SUBQUERY2_t1.* FROM ( C AS SUBQUERY2_t1 STRAIGHT_JOIN C AS SUBQUERY2_t2 ON (SUBQUERY2_t2.   `col_int_key` = SUBQUERY2_t1.`pk`))) AS table1 STRAIGHT_JOIN ( ( (  SELECT   SUBQUERY3_t2 . * FROM ( C AS SUBQUERY3_t1 INNER JOIN B AS SUBQUERY3_t2 ON (SUBQUERY3_t2 . `col_int_key` = SUBQUERY3_t1 . `col_int_key`  ) ) WHERE ( SUBQUERY3_t2 . `col_varchar_key` = 'j' OR SUBQUERY3_t2 . `pk` >= 5 ) ) AS table2             STRAIGHT_JOIN C AS table3 ON (table3 . `col_int_key` = table2 . `col_int_nokey`  ) ) ) ON (table3 . `col_varchar_key` = table2 . `col_varchar_nokey`  ) ) WHERE (  table1 . `col_varchar_key` <= ALL ( SELECT 'o' UNION DISTINCT SELECT 'h' ) ) AND table1 . `col_varchar_key` = 'l' OR table2 . `col_varchar_key` <> 'k'     GROUP BY field1, field4, field5, field6;
```


first close:
```txt
goroutine 248 [running]:
runtime/debug.Stack(0x0, 0xc42011f598, 0xc4202d4298)
        /Users/JiaFang/jianzhang.zj/opt/goroot/src/runtime/debug/stack.go:24 +0xa7                                                                                                                                                                                                                                            runtime/debug.PrintStack()                                                                                                                                                                                                                                                                                                            /Users/JiaFang/jianzhang.zj/opt/goroot/src/runtime/debug/stack.go:16 +0x22
github.com/pingcap/tidb/executor.(*UnionExec).Close(0xc4206f6000, 0x102a608, 0xc4205d3da0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/executor.go:1090 +0x58
github.com/pingcap/tidb/executor.(*HashAggExec).Close(0xc42056a9a0, 0xc42011f658, 0x19a7724)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/aggregate.go:49 +0x8a
github.com/pingcap/tidb/executor.(*HashAggExec).Close(0xc42056ab00, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/aggregate.go:49 +0x8a
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc4204e84e0, 0x1bdb400, 0x2554361)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/executor.go:125 +0x73
github.com/pingcap/tidb/executor.(*HashJoinExec).Close(0xc4204e84e0, 0x4, 0x27864c0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/join.go:75 +0x6f
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc4206ca300, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/executor.go:125 +0x73
github.com/pingcap/tidb/executor.(*HashAggExec).Close(0xc42056abb0, 0x2d784a8, 0xc4205129f0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/aggregate.go:49 +0x8a
github.com/pingcap/tidb/executor.(*NestedLoopJoinExec).fetchBigRow(0xc420734120, 0x2d784a8, 0xc4205129f0, 0xc420026670, 0xc420026600, 0xc4202fc0e0, 0xd, 0xc4202ee070, 0xc42011f8b0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/join.go:497 +0x2b8
github.com/pingcap/tidb/executor.(*ApplyJoinExec).Next(0xc4206d8320, 0x2d784a8, 0xc4205129f0, 0xc4206d9720, 0x2534120, 0xc42041e700, 0x0, 0x1)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/join.go:822 +0x245
github.com/pingcap/tidb/executor.(*ProjectionExec).Next(0xc4206ca380, 0x2d784a8, 0xc4205129f0, 0x0, 0xc42011fb00, 0x1010897, 0x3, 0xc42075c300)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/executor.go:497 +0x76
github.com/pingcap/tidb/executor.(*recordSet).Next(0xc4205140c0, 0x2d784a8, 0xc4205129f0, 0xc42011fb08, 0x1b12e83, 0xc4205140c0, 0xc42011fb00)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/adapter.go:77 +0x63
github.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc4205526f0, 0x2d784a8, 0xc4205129f0, 0xc42011fbe0, 0x1b120e0, 0x1cab5a0, 0xc4205526f0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/driver_tidb.go:294 +0x47
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc420766630, 0x2d784a8, 0xc4205129f0, 0x2535980, 0xc4205526f0, 0xc4202e0000, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:807 +0x100
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc420766630, 0x2d784a8, 0xc4205129f0, 0xc42030c581, 0x579, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:748 +0x115
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc420766630, 0xc42030c581, 0x57a, 0x57a, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:530 +0x511
github.com/pingcap/tidb/server.(*clientConn).Run(0xc420766630)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:412 +0x18a
github.com/pingcap/tidb/server.(*Server).onConn(0xc4204aab40, 0x2538560, 0xc4204948e0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/server.go:315 +0x144
created by github.com/pingcap/tidb/server.(*Server).Run
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/server.go:261 +0x496
```

second close:
```txt
goroutine 248 [running]:
runtime/debug.Stack(0x0, 0xc42011f7c0, 0xc4202d4298)
        /Users/JiaFang/jianzhang.zj/opt/goroot/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /Users/JiaFang/jianzhang.zj/opt/goroot/src/runtime/debug/stack.go:16 +0x22
github.com/pingcap/tidb/executor.(*UnionExec).Close(0xc4206f6000, 0xc42075c300, 0xc4205d3da0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/executor.go:1090 +0x58
github.com/pingcap/tidb/executor.(*HashAggExec).Close(0xc42056a9a0, 0xc42011f880, 0x19a7724)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/aggregate.go:49 +0x8a
github.com/pingcap/tidb/executor.(*HashAggExec).Close(0xc42056ab00, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/aggregate.go:49 +0x8a
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc4204e84e0, 0x1bdb400, 0x2554361)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/executor.go:125 +0x73
github.com/pingcap/tidb/executor.(*HashJoinExec).Close(0xc4204e84e0, 0xc421e3612b, 0xc42062a000)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/join.go:75 +0x6f
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc4206ca300, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/executor.go:125 +0x73
github.com/pingcap/tidb/executor.(*HashAggExec).Close(0xc42056abb0, 0x11105ed, 0xc42060ca80)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/aggregate.go:49 +0x8a
github.com/pingcap/tidb/executor.(*NestedLoopJoinExec).Close(0xc420734120, 0x13d, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/join.go:478 +0x90
github.com/pingcap/tidb/executor.(*ApplyJoinExec).Close(0xc4206d8320, 0xc420491ec0, 0xc42062a009)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/join.go:804 +0x34
github.com/pingcap/tidb/executor.(*baseExecutor).Close(0xc4206ca380, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/executor.go:125 +0x73
github.com/pingcap/tidb/executor.(*recordSet).Close(0xc4205140c0, 0x3, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/adapter.go:123 +0x38
github.com/pingcap/tidb/server.(*tidbResultSet).Close(0xc4205526f0, 0x0, 0xc420491ec8)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/driver_tidb.go:310 +0x33
github.com/pingcap/tidb/server.(ResultSet).Close-fm(0x1e252c8, 0xc42011fb18)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:792 +0x2f
github.com/pingcap/tidb/terror.Call(0xc42011fbc8)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/terror/terror.go:333 +0x2b
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc420766630, 0x2d784a8, 0xc4205129f0, 0x2535980, 0xc4205526f0, 0xc4202e0000, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:848 +0x4d7
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc420766630, 0x2d784a8, 0xc4205129f0, 0xc42030c581, 0x579, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:748 +0x115
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc420766630, 0xc42030c581, 0x57a, 0x57a, 0x0, 0x0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:530 +0x511
github.com/pingcap/tidb/server.(*clientConn).Run(0xc420766630)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:412 +0x18a
github.com/pingcap/tidb/server.(*Server).onConn(0xc4204aab40, 0x2538560, 0xc4204948e0)
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/server.go:315 +0x144
created by github.com/pingcap/tidb/server.(*Server).Run
        /Users/JiaFang/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/server.go:261 +0x496
```

**Comment by zz-jason** [comment]
the problem is:

474 // Close implements Executor interface.
475 func (e *NestedLoopJoinExec) Close() error {
476     e.resultRows = nil
477     e.innerRows = nil
478     return e.BigExec.Close()
479 }
480
481 // Open implements Executor Open interface.
482 func (e *NestedLoopJoinExec) Open(goCtx goctx.Context) error {
483     e.cursor = 0
484     e.prepared = false
485     e.resultRows = e.resultRows[:0]
486     e.innerRows = e.innerRows[:0]
487     return errors.Trace(e.BigExec.Open(goCtx))
488 }
489
490 func (e *NestedLoopJoinExec) fetchBigRow(goCtx goctx.Context) (Row, bool, error) {
491     for {
492         bigRow, err := e.BigExec.Next(goCtx)
493         if err != nil {
494             return nil, false, errors.Trace(err)
495         }
496         if bigRow == nil {
497             return nil, false, e.BigExec.Close()
498         }
499
500         matched, err := expression.EvalBool(e.BigFilter, bigRow, e.ctx)
501         if err != nil {
502             return nil, false, errors.Trace(err)
503         }
504         if matched {
505             return bigRow, true, nil
506         } else if e.outer {
507             return bigRow, false, nil
508         }
509     }
510 }

here in `fetchBigRow`, `NestedLoopJoinExec` will close `BigExec` when it is no more data. It will close `BigExec` again in its `Close()` function.

to fix this issue, we should remove the close operation in `fetchBigRow`

**Comment by zz-jason** [comment]
the problem exists in `HashSemiJoinExec`, too.
