### ISSUE TITLE
batch client panic when close

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#53727]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```log
```
RunBrBackup: cmd start at 2024-05-30 14:49:31
cmd failed at 2024-05-30 14:58:32
stdout:
Detail BR log in /tmp/br.log.2024-05-30T06.49.31Z 
panic: close of closed channel

goroutine 2822 [running]:
[github.com/tikv/client-go/v2/internal/client.(*batchConn).Close(...)](http://github.com/tikv/client-go/v2/internal/client.(*batchConn).Close(...))
        /root/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client_batch.go:769](http://github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client_batch.go:769)
[github.com/tikv/client-go/v2/internal/client.(*connArray).Close(0xc0004bb560)](http://github.com/tikv/client-go/v2/internal/client.(*connArray).Close(0xc0004bb560))
        /root/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:330](http://github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:330) +0xf6
[github.com/tikv/client-go/v2/internal/client.(*RPCClient).CloseAddr](http://github.com/tikv/client-go/v2/internal/client.(*RPCClient).CloseAddr)(0xc0007e3680, {0xc000f7e7d0, 0x44})
        /root/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:797](http://github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:797) +0x1e5
[github.com/tikv/client-go/v2/internal/client.(*RPCClient).recycleIdleConnArray(0xc0007e3680)](http://github.com/tikv/client-go/v2/internal/client.(*RPCClient).recycleIdleConnArray(0xc0007e3680))
        /root/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client_batch.go:835](http://github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client_batch.go:835) +0x1f7
created by [github.com/tikv/client-go/v2/internal/client.(*RPCClient).sendRequest](http://github.com/tikv/client-go/v2/internal/client.(*RPCClient).sendRequest) in goroutine 2821
        /root/go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:587](http://github.com/tikv/client-go/v2@v2.0.8-0.20240528025037-f41b068bf706/internal/client/client.go:587) +0x34b
```
```

### 4. What is your TiDB version? (Required)

release-7.5: 84e292668495cba54fc5a7a157b7e0519c4267e4

**Comment by crazycs520** [comment]
duplicate with #54848
