### ISSUE TITLE
infoschema v2 panic: [tikv:9005]Region is unavailable

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#54508]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When I'm testing 1M tables for infoschema v2
TiKV seems OOM
Then I see this panic log in tidb   (gotoutine panic, not the tidb-server process panic). The log is still annoying

### 2. What did you expect to see? (Required)

no panic log

### 3. What did you see instead (Required)

```
2024/07/08 23:58:51 http: panic serving 192.168.0.26:51956: [tikv:9005]Region is unavailable
goroutine 4910570 [running]:
net/http.(*conn).serve.func1()
        /home/genius/project/go/src/net/http/server.go:1868 +0xb9
panic({0x5cda280?, 0xc000b28de0?})
        /home/genius/project/go/src/runtime/panic.go:920 +0x270
github.com/pingcap/tidb/pkg/infoschema.(*infoschemaV2).SchemaTableInfos(0xc313303920, {{0xc2581f20e4?, 0x619e1fd?}, {0xc2581f20e4?, 0xc10f4fdb00?}})
        /home/genius/project/src/github.com/pingcap/tidb/pkg/infoschema/infoschema_v2.go:554 +0x392
github.com/pingcap/tidb/pkg/server/handler/tikvhandler.SchemaHandler.ServeHTTP({0xc0b22bc5a0?}, {0x6c48270, 0xc03a6abc00}, 0xc280ab33b0?)
        /home/genius/project/src/github.com/pingcap/tidb/pkg/server/handler/tikvhandler/tikv_handler.go:990 +0x29e
github.com/gorilla/mux.(*Router).ServeHTTP(0xc08fbf86c0, {0x6c48270, 0xc03a6abc00}, 0xc10adaea00)
        /home/genius/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1c5
net/http.(*ServeMux).ServeHTTP(0x204d308?, {0x6c48270, 0xc03a6abc00}, 0xc10adaea00)
        /home/genius/project/go/src/net/http/server.go:2514 +0x142
github.com/pingcap/tidb/pkg/server/internal/util.CorsHandler.ServeHTTP({{0x6c2ab40?, 0xc09c6f9500?}, 0xc0016d7200?}, {0x6c48270?, 0xc03a6abc00?}, 0xc324aaf340?)
        /home/genius/project/src/github.com/pingcap/tidb/pkg/server/internal/util/util.go:219 +0x219
net/http.serverHandler.ServeHTTP({0xc280ab2fc0?}, {0x6c48270?, 0xc03a6abc00?}, 0x6?)
        /home/genius/project/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc1e863c360, {0x6c5e3a8, 0xc097ba40f0})
        /home/genius/project/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 879
        /home/genius/project/go/src/net/http/server.go:3086 +0x5cb
```

**Comment by tiancaiamao** [comment]
Ref #50959

**Comment by tiancaiamao** [comment]
Partly closed by https://github.com/pingcap/tidb/pull/54664
