### ISSUE TITLE
Limit decimal type precision size.

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#5529]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `a` decimal(100,4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin

INSERT INTO `test` VALUES (1, 172878.6201);
```

2. What did you expect to see?

```
mysql> CREATE TABLE `test` (
    ->   `id` int(11) NOT NULL AUTO_INCREMENT,
    ->   `a` decimal(100,4) DEFAULT NULL,
    ->   PRIMARY KEY (`id`),
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
ERROR 1426 (42000): Too-big precision 100 specified for 'a'. Maximum is 65.
```

3. What did you see instead?

```
mysql> CREATE TABLE `test` (
    ->   `id` int(11) NOT NULL AUTO_INCREMENT,
    ->   `a` decimal(100,4) DEFAULT NULL,
    ->   PRIMARY KEY (`id`),
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO `test` VALUES (1, 172878.6201);
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

TiDB log:

```
should not happen, precision 100, frac 4 [types:1]Bad Number, goroutine 131 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc4205a1a00, 0xc420cd1e0f)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/server/conn.go:408 +0x10e
panic(0x1c60520, 0xc4205dd320)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/util/codec.EncodeDecimal(0xc4205f7830, 0x1f, 0x23, 0x6400040008, 0x0, 0x0, 0x0, 0x0, 0x1e22500, 0xc4205f7770, ...)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/util/codec/decimal.go:34 +0x3c0
github.com/pingcap/tidb/util/codec.encode(0xc4205f7830, 0x1c, 0x23, 0xc4205f8240, 0xa, 0xa, 0x199a3c0000000000, 0x0, 0x0, 0x0, ...)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/util/codec/codec.go:99 +0x6d3
github.com/pingcap/tidb/util/codec.EncodeValue(0x0, 0x0, 0x0, 0xc4205f8240, 0xa, 0xa, 0x0, 0x28893e0, 0x1, 0x1c6, ...)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/util/codec/codec.go:172 +0x74
github.com/pingcap/tidb/tablecodec.EncodeRow(0xc420772160, 0x5, 0x6, 0xc4205f7800, 0x5, 0x6, 0x28893e0, 0xc420770d60, 0x0, 0x0, ...)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/tablecodec/tablecodec.go:190 +0x509
github.com/pingcap/tidb/table/tables.(*Table).AddRecord(0xc420623790, 0x2645800, 0xc4205af200, 0xc420772000, 0x6, 0x6, 0x0, 0x0, 0xc420772000, 0x6)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/table/tables/tables.go:362 +0xae4
github.com/pingcap/tidb/executor.(*InsertExec).exec(0xc420751800, 0x2c76b08, 0xc420751530, 0xc4207704c0, 0x1, 0x1, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/executor/write.go:861 +0x1c5
github.com/pingcap/tidb/executor.(*InsertExec).NextChunk(0xc420751800, 0x2c76b08, 0xc420751530, 0xc4207704a0, 0x262db20, 0xc420751800)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/executor/write.go:939 +0x157
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc42076c500, 0x2c76b08, 0xc420751530, 0x262db20, 0xc420751800, 0x2645800, 0xc4205af200, 0x2cb97f0, 0xc4205af200, 0x0, ...)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/executor/adapter.go:282 +0x2da
github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc42076c500, 0x2c76b08, 0xc420751530, 0x0, 0x0, 0x0, 0x0)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/executor/adapter.go:241 +0x54d
github.com/pingcap/tidb.runStmt(0x2c76b08, 0xc420751530, 0x2645800, 0xc4205af200, 0x262ae20, 0xc42076c500, 0x0, 0x0, 0x0, 0x0)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/tidb.go:163 +0x23a
github.com/pingcap/tidb.(*session).executeStatement(0xc4205af200, 0x2c76b08, 0xc420751530, 0x2, 0x2629100, 0xc420253680, 0x262ae20, 0xc42076c500, 0x0, 0x0, ...)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/session.go:675 +0x1b5
github.com/pingcap/tidb.(*session).Execute(0xc4205af200, 0x2c76b08, 0xc420751530, 0xc420740071, 0x6a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/wink/go_dir/src/github.com/pingcap/tidb/session.go:763 +0xc15
github.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc420543a70, 0x2cb56a0, 0xc42076e280, 0xc420740071, 0x6a, 0xc420cd1c48, 0x1029ef9, 0xc420590cb0, 0xc420cd1c68, 0x20)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v1.1.0-alpha-355-gf8177996
Git Commit Hash: f8177996e7d35be0f25fa7417b391f5b92b50f9e
Git Branch: master
UTC Build Time: 2017-12-29 01:10:30 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by winkyao** [comment]
ref https://dev.mysql.com/doc/refman/5.7/en/precision-math-decimal-characteristics.html

**Comment by winkyao** [comment]
The declaration syntax for a DECIMAL column is DECIMAL(M,D). The ranges of values for the arguments are as follows:

* M is the maximum number of digits (the precision). It has a range of 1 to 65.

* D is the number of digits to the right of the decimal point (the scale). It has a range of 0 to 30 and must be no larger than M.
