### ISSUE TITLE
coprocessor err: other error: unknown error StringError("offset 18446744073709551615 overflow, should be less than 2

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#5570]
steps to reproduce:

``` sql
CREATE TABLE `n` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
);

insert into n values (1),(2),(3);

analyze table n;

CREATE TABLE `v` (
  `p` int NOT NULL,
  `n` int NOT NULL,
  `v` int NOT NULL,
  `i` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`p`,`i`,`n`,`v`),
  KEY `n` (`n`)
);

insert into v values (1,1,1,1);

analyze table v;

select n.id from v join n on n.id = v.n where p=1 and n.id in (select n from v where p=1);
```

```
2018/01/07 11:12:09.741 column.go:339: [error] Can't find column test.v1.p1 in schema Column: [,] Unique key: []
2018/01/07 11:12:09.831 coprocessor.go:613: [warning] coprocessor err: other error: unknown error StringError("offset 18446744073709551615 overflow, should be less than 2")
2018/01/07 11:12:09.832 coprocessor.go:613: [warning] coprocessor err: other error: unknown error StringError("offset 18446744073709551615 overflow, should be less than 2")
2018/01/07 11:12:09.842 coprocessor.go:613: [warning] coprocessor err: other error: unknown error StringError("offset 18446744073709551615 overflow, should be less than 2")
2018/01/07 11:12:09.843 conn.go:470: [warning] [1] dispatch error:
id:1, addr:192.168.20.8:42504 status:2, collation:utf8_general_ci, user:root
/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:612: other error: unknown error StringError("offset 18446744073709551615 overflow, should be less than 2")
/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:614: 
/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:515: 
/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:495: 
/go/src/github.com/pingcap/tidb/distsql/distsql.go:108: 
/go/src/github.com/pingcap/tidb/distsql/distsql.go:178: 
/go/src/github.com/pingcap/tidb/distsql/distsql.go:159: 
/go/src/github.com/pingcap/tidb/executor/distsql.go:179: 
/go/src/github.com/pingcap/tidb/executor/distsql.go:624: 
/go/src/github.com/pingcap/tidb/executor/distsql.go:862: 
/go/src/github.com/pingcap/tidb/executor/distsql.go:837: 
/go/src/github.com/pingcap/tidb/executor/new_index_lookup_join.go:493: 
/go/src/github.com/pingcap/tidb/executor/new_index_lookup_join.go:387: 
/go/src/github.com/pingcap/tidb/executor/new_index_lookup_join.go:369: 
/go/src/github.com/pingcap/tidb/executor/new_index_lookup_join.go:267: 
/go/src/github.com/pingcap/tidb/executor/new_index_lookup_join.go:230: 
/go/src/github.com/pingcap/tidb/executor/new_index_lookup_join.go:181: 
/go/src/github.com/pingcap/tidb/executor/sort.go:497: 
/go/src/github.com/pingcap/tidb/executor/sort.go:471: 
/go/src/github.com/pingcap/tidb/executor/executor.go:639: 
/go/src/github.com/pingcap/tidb/executor/adapter.go:106: 
/go/src/github.com/pingcap/tidb/server/conn.go:938: 
/go/src/github.com/pingcap/tidb/server/conn.go:863: 
/go/src/github.com/pingcap/tidb/server/conn.go:824: 
```
v1.0.5 is OK,  ecbd60c3fffd76ed46613da0be89ead4bda7e06c shows this error.
After bisecting, c7b13ef1af3250c20546ed21965054a4d66b731c is the commit that introduces this error.

```
c7b13ef1af3250c20546ed21965054a4d66b731c is the first bad commit
commit c7b13ef1af3250c20546ed21965054a4d66b731c
Author: Han Fei <hanfei19910905@gmail.com>
Date:   Fri Jan 5 23:47:33 2018 +0800

    plan: refine code. (#5565)

:040000 040000 90488ffce0adc511ddce8b7db3523c0e23f85da4 1b2cc53cc471bb392e454685e6ae1f0b504a568d M      plan
```
 
@hanfei1991  mind take a look?
  

Tikv version used:
```
TiKV 
Release Version:   1.0.1
Git Commit Hash:   1de37670ee601deba5d88609dcd7d848de2a11e3
Git Commit Branch: master
UTC Build Time:    2018-01-06 03:16:59
Rust Version:      1.24.0-nightly (b98fd524e 2018-01-05)
```

**Comment by zhexuany** [comment]
Thanks for report this error and already gave a lot of details which can help us narrow down problem. I checked source code and found that this error is originally from `other_error` at coprocessor side. In general, there are three different error types: timeout, server is busy, and error during computation such as encode/decode error or wrong request format. I will talk with @hanfei1991  for more details. 

Again, thanks for detail report.

**Comment by zhexuany** [comment]
@Darren I am trying to reproduce this error, it is great if you can attach schema and query here. I will be really appreciated this.

**Comment by Darren** [comment]
@zhexuany 
I have added an simple test case in original report.
The test case runs on mock tikv will panic:

```
2018/01/08 12:56:11.582 column.go:316: [error] Can't find column test.v.p in schema Column: [,] Unique key: []
panic: runtime error: index out of range

goroutine 46082 [running]:
github.com/pingcap/tidb/expression.PBToExpr(0xc424a02420, 0xc420a01140, 0x2, 0x2, 0xc424a024e0, 0x2, 0x0, 0x0, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/expression/distsql_builtin.go:550 +0xf12
github.com/pingcap/tidb/expression.PBToExpr(0xc424a023c0, 0xc420a01140, 0x2, 0x2, 0xc424a024e0, 0x1, 0x2, 0xc423b69188, 0x1)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/expression/distsql_builtin.go:586 +0x47d
github.com/pingcap/tidb/store/tikv/mocktikv.convertToExprs(0xc424a024e0, 0xc420a01140, 0x2, 0x2, 0xc46642a9c8, 0x1, 0x1, 0xc423b69188, 0x1, 0x1, ...)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/mocktikv/executor.go:573 +0x103
github.com/pingcap/tidb/store/tikv/mocktikv.(*rpcHandler).buildSelection(0xc44a363b90, 0xc46215dbf0, 0xc424a02360, 0x0, 0x40, 0x1d850e0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/mocktikv/cop_handler_dag.go:225 +0x1b3
github.com/pingcap/tidb/store/tikv/mocktikv.(*rpcHandler).buildExec(0xc44a363b90, 0xc46215dbf0, 0xc424a02360, 0x264a6e0, 0xc44a363c20, 0x0, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/mocktikv/cop_handler_dag.go:140 +0x166
github.com/pingcap/tidb/store/tikv/mocktikv.(*rpcHandler).buildDAG(0xc44a363b90, 0xc46215dbf0, 0xc420a01110, 0x2, 0x2, 0x0, 0x0, 0x0, 0x1c72960)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/mocktikv/cop_handler_dag.go:160 +0xad
github.com/pingcap/tidb/store/tikv/mocktikv.(*rpcHandler).buildDAGExecutor(0xc44a363b90, 0xc420f0a2c0, 0x0, 0x1, 0xc4666d20c9, 0xc4666d20e0, 0x26457e0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/mocktikv/cop_handler_dag.go:111 +0x38c
github.com/pingcap/tidb/store/tikv/mocktikv.(*rpcHandler).handleCopDAGRequest(0xc44a363b90, 0xc420f0a2c0, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/mocktikv/cop_handler_dag.go:56 +0xed
github.com/pingcap/tidb/store/tikv/mocktikv.(*RPCClient).SendReq(0xc4200d8420, 0x2e86cb8, 0xc424a02180, 0xc4202d63d0, 0x6, 0xc4546aa5b0, 0xc43c098a20, 0xc4202d63d0, 0xc420f0a2c0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/mocktikv/rpc.go:612 +0x1b3a
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).sendReqToRegion(0xc42d699be8, 0xc424a02120, 0xc420f0a300, 0xc4546aa5b0, 0xdf8475800, 0x0, 0x0, 0x0, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/region_request.go:110 +0x139
github.com/pingcap/tidb/store/tikv.(*RegionRequestSender).SendReq(0xc42d699be8, 0xc424a02120, 0xc4546aa5b0, 0x26, 0x0, 0x1, 0xdf8475800, 0x1ec3978, 0xc4321c6d00, 0xc420054000)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/region_request.go:78 +0xe2
github.com/pingcap/tidb/store/tikv.(*copIterator).handleTaskOnce(0xc424f053e0, 0xc424a02120, 0xc426e17e00, 0xc424f05440, 0x33d41e8, 0x0, 0xc440054d80, 0x28ad1a0, 0x2c356c8)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:555 +0x247
github.com/pingcap/tidb/store/tikv.(*copIterator).handleTask(0xc424f053e0, 0xc424a02120, 0xc426e17e00, 0xc424f05440)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:513 +0xb1
github.com/pingcap/tidb/store/tikv.(*copIterator).work(0xc424f053e0, 0x2e86d30, 0xc4321c6d00, 0xc424f054a0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:382 +0x217
github.com/pingcap/tidb/store/tikv.(*copIterator).run.func1()
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:413 +0xa3
github.com/pingcap/tidb/util/goroutine_pool.(*goroutine).workLoop(0xc44c3f6560, 0xc4202e81c0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/util/goroutine_pool/gp.go:115 +0x17b
created by github.com/pingcap/tidb/util/goroutine_pool.(*Pool).alloc
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/util/goroutine_pool/gp.go:90 +0x97

```

use tidb commit  136462d76adcf3420c24be47fd0c137ff867ed99
