### ISSUE TITLE
TiDB Crash for nil pointer dereference tableInfo return by TableByID

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#55806]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x534371a]

goroutine 3936 [running]:
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec.func1()
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:487 +0x508
panic({0x5beb6c0?, 0x99e8cf0?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/pingcap/tidb/pkg/executor.buildNoRangeIndexLookUpReader(0xc0dd7e2850, 0xc0dd7e9b80)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/builder.go:4036 +0xa7a
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildIndexLookUpReader(0xc0dd7e2850, 0xc0dd7e9b80)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/builder.go:4048 +0xc5
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build(0xc0dd7e2850, {0x6e07400?, 0xc0dd7e9b80?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/builder.go:295 +0xa92
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildTopN(0xc0dd7e2850, 0xc0da4f6e00)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/builder.go:2409 +0x72
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build(0x7000?, {0x6e08a00?, 0xc0da4f6e00?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/builder.go:253 +0x7ed
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).buildProjection(0xc0dd7e2850, 0xc0dd7c62a0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/builder.go:2017 +0x72
github.com/pingcap/tidb/pkg/executor.(*executorBuilder).build(0xc0dd7e2850, {0x6e07100?, 0xc0dd7c62a0?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/builder.go:277 +0x96d
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).buildExecutor(0xc01a4dda40)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:1215 +0x1b9
github.com/pingcap/tidb/pkg/executor.(*ExecStmt).Exec(0xc01a4dda40, {0x6dde288, 0xc0de0688d0})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/adapter.go:558 +0x7af
github.com/pingcap/tidb/pkg/session.runStmt({0x6dde2c0?, 0xc003d71270?}, 0xc01085bb80, {0x6dee790?, 0xc01a4dda40})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2284 +0x31e
github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt(0xc01085bb80, {0x6dde2c0?, 0xc003d71270?}, {0x6df5f28, 0xc0dd7de480?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2145 +0x110a
github.com/pingcap/tidb/pkg/session.(*session).ExecuteInternal(0xc01085bb80, {0x6dde2c0, 0xc003d71270}, {0x64aeb60, 0xee}, {0xc0dd7e2380, 0x7, 0x7})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:1518 +0x23e
github.com/pingcap/tidb/pkg/util/sqlexec.ExecSQL({0x6dde2c0, 0xc003d71270}, {0x6dc78e0?, 0xc01085bb80?}, {0x64aeb60?, 0x1ed30da?}, {0xc0dd7e2380?, 0x6daaaa0?, 0xc03da09b00?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/util/sqlexec/restricted_sql_executor.go:252 +0x8c
github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).ExecuteSQLWithNewSession.func1({0x6e6af78?, 0xc01085bb80?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/storage/task_table.go:178 +0xbc
github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).WithNewSession(0xc002fd4640, 0xc03da09bc0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/storage/task_table.go:142 +0xd7
github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).ExecuteSQLWithNewSession(0x1ed6185?, {0x6dde2c0?, 0xc003d71270?}, {0x64aeb60?, 0x613a880?}, {0xc0dd7e2380?, 0x7f9262393dd0?, 0x7f9308b93108?})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/storage/task_table.go:177 +0xc5
github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).GetTopUnfinishedTasks(0xa5722a0?, {0x6dde2c0, 0xc003d71270})
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/storage/task_table.go:237 +0x11a
github.com/pingcap/tidb/pkg/disttask/framework/scheduler.(*Manager).getSchedulableTasks(0xc00403d5c0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/scheduler/scheduler_manager.go:232 +0x42
github.com/pingcap/tidb/pkg/disttask/framework/scheduler.(*Manager).scheduleTaskLoop(0xc00403d5c0)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/disttask/framework/scheduler/scheduler_manager.go:219 +0x2cc
github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run.func1()
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:157 +0x4f
created by github.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).Run in goroutine 3408
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:155 +0x73
```
### 4. What is your TiDB version? (Required)

Release Version: v8.4.0-alpha
Edition: Community
Git Commit Hash: a5698cc4cf40bd699cc767f5c665e6af93be2474
Git Branch: heads/refs/tags/v8.4.0-alpha
UTC Build Time: 2024-09-02 11:50:18
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by windtalker** [comment]
I think it is a planner's bug? change the label to planner.

**Comment by hawkingrei** [comment]
maybe relation with https://github.com/pingcap/tidb/pull/55730.

Please test again.

**Comment by tiancaiamao** [comment]
> I think it is a planner's bug? change the label to planner.

@windtalker no, not a planner bug.  It's introduced by the infoschema v2 and I'm still investigating.

**Comment by tiancaiamao** [comment]
closed by https://github.com/pingcap/tidb/pull/55856

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/50959
