### ISSUE TITLE
tidb-server panicked while executing some sql with plan-cache enabled

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#5663]
1. What did you do?

```toml
# config file:  test.toml
[plan-cache]
enabled = true
capacity = 2560
shards = 256
```

```bash
#start tidb-server with this config file:
bin/tidb-server --config test.toml
```

```sql
use test;
drop table t1;
create table t1 (i int unsigned, primary key(i));
insert into t1 values (1),(2),(3);
select group_concat(i) from t1 where i > 1;    
select group_concat(i) from t1 where i > 1; 
```

2. What did you expect to see?
should not panic

3. What did you see instead?

first select OK, second select panicked.

```
2018/01/17 10:27:24.097 conn.go:410: [error] lastCmd select group_concat(i) from t1 where i > 1, runtime error: index out of range, goroutine 171 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc420650340, 0xc42011de0f)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/server/conn.go:408 +0x10e
panic(0x1cdbe20, 0x2867530)
        /Users/darren/.local/go1.9.2/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/util/chunk.Row.GetString(...)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/util/chunk/chunk.go:513
github.com/pingcap/tidb/util/chunk.(*Row).GetString(0xc420196dd0, 0x0, 0x147e600, 0x13ea493)
        <autogenerated>:1 +0x126
github.com/pingcap/tidb/expression.(*Column).EvalString(0xc420359c70, 0x2672940, 0xc420196dd0, 0xc4203436e0, 0x1043447, 0x40, 0x1dcf4c0, 0x1004401, 0xc420051c40)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/expression/column.go:242 +0x30e
github.com/pingcap/tidb/expression/aggregation.(*concatFunction).initSeparator(0xc420304540, 0xc4203436e0, 0x2672940, 0xc420196dd0, 0x0, 0x1)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/expression/aggregation/concat.go:41 +0x73
github.com/pingcap/tidb/expression/aggregation.(*concatFunction).Update(0xc420304540, 0xc420343aa0, 0xc4203436e0, 0x2672940, 0xc420196dd0, 0x0, 0xc4202d601c)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/expression/aggregation/concat.go:57 +0x630
github.com/pingcap/tidb/executor.(*StreamAggExec).consumeOneGroup(0xc4200aa640, 0x2ca8810, 0xc4205a8f80, 0xc4203046c0, 0x0, 0x1)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/executor/aggregate.go:356 +0xfb
github.com/pingcap/tidb/executor.(*StreamAggExec).NextChunk(0xc4200aa640, 0x2ca8810, 0xc4205a8f80, 0xc4203046c0, 0x1, 0x1)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/executor/aggregate.go:333 +0x84
github.com/pingcap/tidb/executor.(*recordSet).NextChunk(0xc420343b00, 0x2ca8810, 0xc4205a8f80, 0xc4203046c0, 0xc420343b00, 0xc4203046c0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/executor/adapter.go:103 +0x56
github.com/pingcap/tidb/server.(*tidbResultSet).NextChunk(0xc4202dfe30, 0x2ca8810, 0xc4205a8f80, 0xc4203046c0, 0x4, 0x400)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/server/driver_tidb.go:307 +0x51
github.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc420650340, 0x2ca8810, 0xc4205a8f80, 0x2659c00, 0xc4202dfe30, 0x0, 0xc4202dfe30, 0x1)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/server/conn.go:936 +0x3ef
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc420650340, 0x2ca8810, 0xc4205a8f80, 0x2659c00, 0xc4202dfe30, 0xc4202c0000, 0x0, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/server/conn.go:861 +0x668
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc420650340, 0x2ca8810, 0xc4205a8f80, 0xc4202d4bd1, 0x2a, 0x0, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/server/conn.go:810 +0x115
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc420650340, 0xc4202d4bd1, 0x2b, 0x2b, 0x0, 0x0)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/server/conn.go:592 +0x595
github.com/pingcap/tidb/server.(*clientConn).Run(0xc420650340)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/server/conn.go:452 +0x1b8
github.com/pingcap/tidb/server.(*Server).onConn(0xc420343c80, 0x265c900, 0xc4202be6f8)
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/server/server.go:316 +0x144
created by github.com/pingcap/tidb/server.(*Server).Run
        /Users/darren/Sources/go/src/github.com/pingcap/tidb/server/server.go:262 +0x496

2018/01/17 10:27:24.097 server.go:298: [info] [1] close connection
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

commit: 90d653c8caaee4119844b562a69c93ccf1a2db2a
```
Release Version: v1.1.0-alpha-444-g90d653c8
Git Commit Hash: 90d653c8caaee4119844b562a69c93ccf1a2db2a
Git Branch: master
UTC Build Time: 2018-01-17 02:00:15
```

**Comment by zz-jason** [comment]
@Darren Thanks for your feed back! I'll take a look at it.

**Comment by zz-jason** [comment]
the plan of this query:
```sql
TiDB(localhost) > desc select group_concat(i) from t1 where i > 1;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    5
Current database: test

+----------------+-------------+----------------+------+--------------------------------------------+-------+
| id             | parents     | children       | task | operator info                              | count |
+----------------+-------------+----------------+------+--------------------------------------------+-------+
| TableScan_15   |             |                | cop  | table:t1, range:(1,+inf], keep order:false | 0     |
| TableReader_16 | StreamAgg_9 |                | root | data:TableScan_15                          | 0     |
| StreamAgg_9    |             | TableReader_16 | root | , funcs:group_concat(test.t1.i, ,)         | 1     |
+----------------+-------------+----------------+------+--------------------------------------------+-------+
3 rows in set (0.00 sec)
```

**Comment by zz-jason** [comment]
in file **expression/aggregation/concat.go**:

```go
 39 func (cf *concatFunction) initSeparator(sc *stmtctx.StatementContext, row types.Row) error {
 40     sepArg := cf.Args[len(cf.Args)-1]
 41     sep, isNull, err := sepArg.EvalString(row, sc)
 42     if err != nil {
 43         return errors.Trace(err)
 44     }
 45     if isNull {
 46         return errors.Errorf("Invalid separator argument.")
 47     }
 48     cf.separator = sep
 49     cf.Args = cf.Args[:len(cf.Args)-1]
 50     return nil
 51 }
```

in line 49, `cf.Args` should not be modified during execution.

**Comment by zz-jason** [comment]
@winkyao PTAL
