### ISSUE TITLE
Floating Point Arithmetic Behavior Differences Between Unistore and TiKV

### ISSUE THREAD

**Issue by r33s3n6** [pingcap/tidb#57655]
### 1. Minimal reproduce step (Required)
```sql
create table t1 (c1 double);
insert into t1 (c1) values (24.5), (25), (18);

SELECT
  c1,
  (c1 - 129) & 55 as w1
FROM t1 ORDER BY w1 asc
limit 2
;
```

### 2. What did you expect to see? (Required)
with unistore:
```
mysql> SELECT
    ->   c1,
    ->   (c1 - 129) & 55 as w1
    -> FROM t1 ORDER BY w1 asc
    -> limit 2
    -> ;
+------+------+
| c1   | w1   |
+------+------+
| 24.5 |   16 |
|   25 |   16 |
+------+------+
2 rows in set (0.01 sec)
```

### 3. What did you see instead (Required)
with tikv
```
mysql> SELECT
    ->   c1,
    ->   (c1 - 129) & 55 as w1
    -> FROM t1 ORDER BY w1 asc
    -> limit 2
    -> ;
+------+------+
| c1   | w1   |
+------+------+
|   25 |   16 |
|   18 |   17 |
+------+------+
2 rows in set (0.01 sec)
```
Actually, if execute it without LIMIT, it is correct:
```
mysql> SELECT
    ->   c1,
    ->   (c1 - 129) & 55 as w1
    -> FROM t1 ORDER BY w1 asc;
+------+------+
| c1   | w1   |
+------+------+
| 24.5 |   16 |
|   25 |   16 |
|   18 |   17 |
+------+------+
3 rows in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)
```
Release Version: v8.5.0-alpha-184-g1c059a1216
Edition: Community
Git Commit Hash: 1c059a1216db711e2cb56ea9f3d1ad8c23db6327
Git Branch: HEAD
UTC Build Time: 2024-11-21 04:56:22
GoVersion: go1.23.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

topology:
distributed.yaml:
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

tidb_servers:
  - host: 10.0.2.81

pd_servers:
  - host: 10.0.2.82

tikv_servers:
  - host: 10.0.2.83
```

### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned vulnerabilities in TiDB that may lead to database logic error.

**Comment by yibin87** [comment]
The root cause is the bit comparation behaviors are different in tidb and other stores.
```
Last login: Fri Jun 14 11:14:32 on ttys000
yibinhu@yibindeMacBook-Pro ~ % tmux new -s dev                             























yibinhu@yibindeMacBook-Pro ~ % 
                                                                                                                                                                       


                                     
yibinhu@yibindeMacBook-Pro ~ % 
                                                                                                                                                                       

                                     
yibinhu@yibindeMacBook-Pro ~ % 
                                                                                                                                                                       
                                     
yibinhu@yibindeMacBook-Pro ~ % 
                                                                                                                                                                                                            
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ %                        
[dev] 0:zsh* 1:zsh  2:zsh  3:zsh  4:vim- 5:zsh  6:zsh  7:zsh                                "TiUP Playground: UGfZ" 13:03 27- 6-24    "TiUP Playground: UGfZ" 11:08 27- 6-24
  [恢复于2024年6月28日 09:23:08]
Last login: Fri Jun 28 09:23:01 on console
yibinhu@yibindeMacBook-Pro ~ % tiup playground nightly --db.binpath ~/Documents/work/dev/tidb_repos/tidb_dev/bin/tidb-server
tiup is checking updates for component playground ...
A new version of playground is available:
   The latest version:         v1.15.2
   Local installed version:    v1.12.3
   Update current component:   tiup update playground
   Update all components:      tiup update --all

Starting component `playground`: /Users/yibinhu/.tiup/components/playground/v1.12.3/tiup-playground nightly --db.binpath /Users/yibinhu/Documents/work/dev/tidb_repos/tidb_dev/bin/tidb-server
Using the version nightly for version constraint "nightly".

If you'd like to use a TiDB version other than nightly, cancel and retry with the following arguments:
	Specify version manually:   tiup playground <version>
	Specify version range:      tiup playground ^5
	The nightly version:        tiup playground nightly

Start pd instance:v8.2.0-alpha-nightly
Start tikv instance:v8.2.0-alpha-nightly
Start tidb instance:v8.2.0-alpha-nightly
Waiting for tidb instances ready
127.0.0.1:4000 ... Done
component grafana version v8.2.0-alpha-nightly is already installed
Start tiflash instance:v8.2.0-alpha-nightly
Waiting for tiflash instances ready
127.0.0.1:3930 ... Done

🎉 TiDB Playground Cluster is started, enjoy!

Connect TiDB:   mysql --comments --host 127.0.0.1 --port 4000 -u root
TiDB Dashboard: http://127.0.0.1:2379/dashboard
Grafana:        http://127.0.0.1:3000









^CPlayground receive signal:  interrupt
Wait tiflash(4286) to quit...
Wait grafana(4285) to quit...
Wait prometheus(4282) to quit...
Wait ng-monitoring(4283) to quit...
Got signal interrupt (Component: playground ; PID: 4254)
Grafana quit
tikv quit
tiflash quit
Wait tidb(4257) to quit...
prometheus quit
pd quit
ng-monitoring quit
^CForce prometheus(4282) to quit...
Got signal interrupt (Component: playground ; PID: 4254)
Force tiflash(4286) to quit...
Force tidb(4257) to quit...
Force grafana(4285) to quit...
Force ng-monitoring(4283) to quit...
tidb quit
Force tikv(4256) to quit...
Force pd(4255) to quit...
^CGot signal interrupt (Component: playground ; PID: 4254)
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % tmux new -s dev                                                                              

runtime.gopark(0x36f3b98, 0x40007f6a68, 0x400024170e, 0x3)
        /usr/local/go/src/runtime/proc.go:304 +0xd0 fp=0x4000098ed0 sp=0x4000098eb0 pc=0x13e45e8
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310 
runtime.chanrecv(0x40007f6a10, 0x4000098fb8, 0x1, 0x1410101)
        /usr/local/go/src/runtime/chan.go:524 +0x27c fp=0x4000098f60 sp=0x4000098ed0 pc=0x13b9404
runtime.chanrecv2(0x40007f6a10, 0x4000098fb8, 0x0)
        /usr/local/go/src/runtime/chan.go:411 +0x28 fp=0x4000098f90 sp=0x4000098f60 pc=0x13b9170
gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0x40009a0ea0)
        /root/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:379 +0x50 fp=0x4000098fd0 sp=0x4000098f90 pc=0x16bf818
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1128 +0x4 fp=0x4000098fd0 sp=0x4000098fd0 pc=0x1411cac
created by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1
        /root/go/pkg/mod/gopkg.in/natefinch/lumberjack.v2@v2.0.0/lumberjack.go:390 +0x78

goroutine 399 [chan receive]:
runtime.gopark(0x36f3b98, 0x40002414f8, 0x40004e170e, 0x3)
        /usr/local/go/src/runtime/proc.go:304 +0xd0 fp=0x40004ebdf0 sp=0x40004ebdd0 pc=0x13e45e8
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:310
runtime.chanrecv(0x40002414a0, 0x0, 0x7a6ecf8528c301, 0x4000240101)
        /usr/local/go/src/runtime/chan.go:524 +0x27c fp=0x40004ebe80 sp=0x40004ebdf0 pc=0x13b9404
runtime.chanrecv1(0x40002414a0, 0x0)
        /usr/local/go/src/runtime/chan.go:406 +0x28 fp=0x40004ebeb0 sp=0x40004ebe80 pc=0x13b9130
github.com/pingcap/tidb/util/systimemon.StartMonitor(0x36f3f10, 0x36f3310, 0x4000427810)
        /home/jenkins/workspace/optimization-build-tidb-linux-arm/go/src/github.com/pingcap/tidb/util/systimemon/systime_mon.go:31 +0x11c fp=0x40004ebfc0 sp=0x40004ebeb0 pc=0x2ebe604
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1128 +0x4 fp=0x40004ebfc0 sp=0x40004ebfc0 pc=0x1411cac
created by main.setupMetrics
        /home/jenkins/workspace/optimization-build-tidb-linux-arm/go/src/github.com/pingcap/tidb/tidb-server/main.go:674 +0xf4

goroutine 400 [select, 8322 minutes]:
runtime.gopark(0x36f3bd8, 0x0, 0x1809, 0x1)
        /usr/local/go/src/runtime/proc.go:304 +0xd0 fp=0x40004ecd70 sp=0x40004ecd50 pc=0x13e45e8
runtime.selectgo(0x40004ecf18, 0x40004eced8, 0x2, 0x2, 0x0)
        /usr/local/go/src/runtime/select.go:313 +0xa8c fp=0x40004ece90 sp=0x40004ecd70 pc=0x13f47a4
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0x4000803680)
        /root/go/pkg/mod/google.golang.org/grpc@v1.27.1/balancer_conn_wrappers.go:69 +0x90 fp=0x40004ecfd0 sp=0x40004ece90 pc=0x18890f8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1128 +0x4 fp=0x40004ecfd0 sp=0x40004ecfd0 pc=0x1411cac
created by google.golang.org/grpc.newCCBalancerWrapper
        /root/go/pkg/mod/google.golang.org/grpc@v1.27.1/bala
-- INSERT -- 
[dev] 0:zsh  1:vim* 2:zsh  3:zsh  4:zsh-                                                                                          "yibindeMacBook-Pro.lo" 10:56 02- 7-242424
  [恢复于2024年7月2日 10:57:40]
Last login: Fri Jun 28 09:23:07 on ttys000
Restored session: 2024年 7月 2日 星期二 10时56分25秒 CST
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % tmux a -t new                                                                                
can't find session: new
yibinhu@yibindeMacBook-Pro ~ % tmux a -t dev

^CGot signal interrupt (Component: playground ; PID: 55436)
Playground receive signal:  interrupt
Wait prometheus(55443) to quit...
Wait grafana(55447) to quit...
Wait ng-monitoring(55444) to quit...
Wait tiflash(55448) to quit...
Grafana quit
tiflash quit
Wait tidb(55439) to quit...
prometheus quit
pd quit
ng-monitoring quit
^CForce grafana(55447) to quit...
Got signal interrupt (Component: playground ; PID: 55436)
Force tiflash(55448) to quit...
Force tidb(55439) to quit...
Force ng-monitoring(55444) to quit...
Force prometheus(55443) to quit...
tikv quit
^CGot signal interrupt (Component: playground ; PID: 55436)
^CGot signal interrupt (Component: playground ; PID: 55436)
tidb quit
Force tikv(55438) to quit...
Force pd(55437) to quit...


yibinhu@yibindeMacBook-Pro ~ % 
                                                                                                                                  
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % /Users/yibinhu/.tiup/data/UHMYWer/tidb-0/
[dev] 0:zsh* 1:zsh  2:zsh- 3:zsh  4:zsh  5:zsh                                            "TiUP Playground: UHMY" 09:20 03- 7-2424 18:16 02- 7-24
  [恢复于2024年7月3日 09:23:09]
Last login: Wed Jul  3 09:23:03 on console
yibinhu@yibindeMacBook-Pro ~ % tmux new -s dev                                                                              



yibinhu@yibindeMacBook-Pro ~ % 
                                                                                                                                                                           

yibinhu@yibindeMacBook-Pro ~ % 
                                                                                                                                                                           
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % tiup playground nightly                                                                      
tiup is checking updates for component playground ...timeout(2s)!
Starting component `playground`: /Users/yibinhu/.tiup/components/playground/v1.12.3/tiup-playground nightly
Using the version nightly for version constraint "nightly".

If you'd like to use a TiDB version other than nightly, cancel and retry with the following arguments:
        Specify version manually:   tiup playground <version>
        Specify version range:      tiup playground ^5
        The nightly version:        tiup playground nightly

Start pd instance:v8.2.0-alpha-nightly
Start tikv instance:v8.2.0-alpha-nightly
Start tidb instance:v8.2.0-alpha-nightly
Waiting for tidb instances ready
127.0.0.1:4000 ... Done
component grafana version v8.2.0-alpha-nightly is already installed
Start tiflash instance:v8.2.0-alpha-nightly
Waiting for tiflash instances ready
127.0.0.1:3930 ... Done

🎉 TiDB Playground Cluster is started, enjoy!

Connect TiDB:   mysql --comments --host 127.0.0.1 --port 4000 -u root
TiDB Dashboard: http://127.0.0.1:2379/dashboard
Grafana:        http://127.0.0.1:3000

[dev] 0:tiup* 1:mysql  2:vim- 3:zsh  4:zsh                                                  "TiUP Playground: UHX0" 13:20 04- 7-24   "TiUP Playground: UHSO" 10:02 04- 7-244
  [恢复于2024年7月5日 09:09:21]
Last login: Fri Jul  5 09:09:11 on console
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ %                                                                                              
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % vim .gitconfig 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % tmux new -s dev                                                                              

mysql> show variables like '%projection%';
+-------------------------------+-------+
| Variable_name                 | Value |
+-------------------------------+-------+
| tidb_opt_projection_push_down | ON    |
| tidb_projection_concurrency   | -1    |
+-------------------------------+-------+
2 rows in set (0.01 sec)

mysql> 
mysql> 
mysql> 
mysql> 
mysql> 
mysql> 
mysql> quit
Bye
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % tiup bench tpch prepare -T 3 --sf 5                    
tiup is checking updates for component bench ...
Starting component `bench`: /Users/yibinhu/.tiup/components/bench/v1.12.0/tiup-bench tpch prepare -T 3 --sf 5
creating nation
creating region
creating part
creating supplier
creating partsupp
creating customer
creating orders
creating lineitem
generating nation table
generate nation table done
generating region table
generate region table done
generating customers table
generate customers table done
generating suppliers table
generate suppliers table done
generating part/partsupplier tables
generate part/partsupplier tables done
generating orders/lineitem tables

[dev] 0:tiup- 1:tiup* 2:zsh  3:zsh  4:zsh  5:zsh  6:zsh  7:zsh  8:zsh                                                                 "yibindeMacBook-Pro.lo" 10:36 26- 7-24
  [恢复于2024年10月8日 09:12:14]
Last login: Tue Oct  1 04:53:55 on console
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % tmux new -s dev                     

PAGER set to 'cat > /tmp/log.txt'
mysql> select tidb_decode_binary_plan("vQXgCrgFCghVcGRhdGVfNBL+BAoLU2VsZWN0aW9uXzcSxgMKC1BvaW50X0dldF82IdS/EcrorTBAKQAAAQJ48D8wATgBQAFKNgo0Cg5waGhzX2xvZ2luX25ldxITdA0N8EllbnRyYW5jZV81NhoNCgdQUklNQVJZEgJpZFoUdGltZToxLjY1bXMsIGxvb3BzOjNiugJHZXQ6e251bV9ycGM6MiwgdG90YWxfdAktEDU0bXN9ERQccHJvY2Vzc18FSSAgMzIwLjLCtXMRHgx3YWl0DRsQMTIwLjQJGxhpa3Zfd2FsDVEMIDUwNwUYOHNjYW5fZGV0YWlsOiB7dAVzEV8Ya2V5czogMhFYLhcAJF9zaXplOiAzNzcRHgktNDMsIGdldF9zbmFwc2hvEYcIMzYuCW6Ycm9ja3NkYjoge2RlbGV0ZV9za2lwcGVkX2NvdW50OiA4LCBrZXlfOhYATDEsIGJsb2NrOiB7Y2FjaGVfaGl0ETIYMjR9fX1w/xEBBAF4EQoE/wEtuSQzQCnGi+dh07+SLbkQUmplcSg2uAEALkq3ATQuZW5hYmxlZCwgMSksIJYzAEB0ZW5hbnRubywgIlRBQ08iKTntADg57QwycPQNHahBTRBSA04vQRUtBDc3GS1AMXDQMXj///////////8BGAE=");
1 row in set (0.00 sec)

mysql> show variables like "%statements%";
4 rows in set (0.00 sec)

mysql> pager 
Default pager wasn't set, using stdout.
mysql> show variables like "%statements%";
+--------------------------------------------------------+-------+
| Variable_name                                          | Value |
+--------------------------------------------------------+-------+
| log_slow_admin_statements                              | OFF   |
| log_slow_slave_statements                              | OFF   |
| performance_schema_events_statements_history_long_size | 10000 |
| performance_schema_events_statements_history_size      | 10    |
+--------------------------------------------------------+-------+
4 rows in set (0.01 sec)

mysql> show variables like "%persiste%";
+--------------------------------------+-------+
| Variable_name                        | Value |
+--------------------------------------+-------+
| innodb_stats_persistent              | ON    |
| innodb_stats_persistent_sample_pages | 20    |
| tidb_stmt_summary_enable_persistent  | OFF   |
+--------------------------------------+-------+
3 rows in set (0.01 sec)

mysql> 
[dev] 0:tiup  1:mysql* 2:zsh- 3:zsh  4:zsh  5:zsh  6:zsh  7:zsh  8:zsh                    "yibindeMacBook-Pro.lo" 19:07 16-11-24
  [恢复于2024年11月18日 09:22:40]
Last login: Mon Nov 18 09:22:22 on console
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % tmux new -s dev

Date:   Thu Oct 10 18:36:33 2024 +0800

    lightning: skip non-unique index when detect duplicate KV (#56541)
    
    close pingcap/tidb#53669

commit 22aa14af1579142943f6643291f0cc04570b393b
Author: Yiding Cui <winoros@gmail.com>
Date:   Thu Oct 10 17:35:08 2024 +0800

    testkit: unify the behavior for methods `MustXXXX` (#56534)

commit 329af0908a1bbb26977e979701cf0bad5ba8577d
Author: Yuanjia Zhang <zhangyuanjia@pingcap.com>
Date:   Thu Oct 10 16:30:55 2024 +0800

    planner: add TPCC as a test case for index advisor (#56528)
    
    ref pingcap/tidb#12303

commit 728f1308edef16882a6c6ebd649a5bc9566c0692
Author: Weizhen Wang <wangweizhen@pingcap.com>
Date:   Thu Oct 10 15:57:24 2024 +0800
yibinhu@yibindeMacBook-Pro tidb % 
yibinhu@yibindeMacBook-Pro tidb % 
yibinhu@yibindeMacBook-Pro tidb % 
yibinhu@yibindeMacBook-Pro tidb % 
yibinhu@yibindeMacBook-Pro tidb % 
yibinhu@yibindeMacBook-Pro tidb % make
CGO_ENABLED=1  GO111MODULE=on go build -tags codes  -ldflags '-X "github.com/pingcap/tidb/pkg/parser/mysql.TiDBReleaseVersion=v8.4.0-alpha-411-gd26c06e747" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBBuildTS=2024-11-18 09:52:17" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitHash=d26c06e7476ed28162c60105beb2af9ba1345e6c" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitBranch=distinct_time_totTime" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBEdition=Community" ' -o bin/tidb-server ./cmd/tidb-server
Build TiDB Server successfully!
yibinhu@yibindeMacBook-Pro tidb % 
[dev] 0:tiup  1:mysql- 2:vim  3:mysql  4:zsh  5:zsh*                                      "yibindeMacBook-Pro.lo" 20:29 18-11-24
  [恢复于2024年11月19日 09:16:51]
Last login: Mon Nov 18 20:37:52 on console
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % tmux new -s dev                     

CREATE TABLE `bairong_apply_loan_str_v2` (
  `id` bigint(20) NOT NULL /*T![auto_rand] AUTO_RANDOM(5) */ COMMENT '主键编号',
  `uid` varchar(36) NOT NULL COMMENT '用户uid',
  `data_id` varchar(36) NOT NULL COMMENT '数据采集标识',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '数据创建时间',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据最后更新时间',
  `code` varchar(500) DEFAULT NULL COMMENT 'code',
  `swift_number` varchar(500) DEFAULT NULL COMMENT 'swift_number',
  `flag_applyloanstr` varchar(500) DEFAULT NULL COMMENT 'flag_applyloanstr',
  `als_d7_id_pdl_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_pdl_allnum',
  `als_d7_id_pdl_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_pdl_orgnum',
  `als_d7_id_caon_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_caon_allnum',
  `als_d7_id_caon_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_caon_orgnum',
  `als_d7_id_rel_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_rel_allnum',
  `als_d7_id_rel_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_rel_orgnum',
  `als_d7_id_caoff_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_caoff_allnum',
  `als_d7_id_caoff_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_caoff_orgnum',
  `als_d7_id_cooff_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_cooff_allnum',
  `als_d7_id_cooff_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_cooff_orgnum',
  `als_d7_id_af_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_af_allnum',
  `als_d7_id_af_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_af_orgnum',
  `als_d7_id_coon_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_coon_allnum',
  `als_d7_id_coon_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_coon_orgnum',
  `als_d7_id_oth_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_oth_allnum',
  `als_d7_id_oth_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_oth_orgnum',
  `als_d7_id_bank_selfnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_bank_selfnum',
  `als_d7_id_bank_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_bank_allnum',
  `als_d7_id_bank_tra_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_bank_tra_allnum',
  `als_d7_id_bank_ret_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_bank_ret_allnum',
  `als_d7_id_bank_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_bank_orgnum',
  `als_d7_id_bank_tra_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_bank_tra_orgnum',
  `als_d7_id_bank_ret_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_bank_ret_orgnum',
  `als_d7_id_bank_week_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_bank_week_allnum',
  `als_d7_id_bank_week_orgnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_bank_week_orgnum',
  `als_d7_id_bank_night_allnum` varchar(500) DEFAULT NULL COMMENT 'als_d7_id_bank_night_allnum',
"table.sql" [noeol] 834L, 78385B
[dev] 0:tiup  1:mysql  2:vim* 3:zsh- 4:zsh  5:zsh  6:zsh  7:zsh  8:zsh  9:zsh             "yibindeMacBook-Pro.lo" 12:16 22-11-244    "yibindeMacBook-Pro.lo" 10:56 20-11-244
  [恢复于2024年11月25日 09:14:36]
Last login: Mon Nov 25 09:14:20 on console
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % 
yibinhu@yibindeMacBook-Pro ~ % tmux new -s dev                     

+----------------------------------+---------+-----------+---------------+-----------------------------------------------------------------------------------+
| id                               | estRows | task      | access object | operator info                                                                     |
+----------------------------------+---------+-----------+---------------+-----------------------------------------------------------------------------------+
| Projection_6                     | 3.00    | root      |               | test.t1.c1, bitand(cast(minus(test.t1.c1, 129), bigint(20) BINARY), 55)->Column#3 |
| └─Projection_13                  | 3.00    | root      |               | test.t1.c1                                                                        |
|   └─TopN_7                       | 3.00    | root      |               | Column#4, offset:0, count:3                                                       |
|     └─Projection_14              | 3.00    | root      |               | test.t1.c1, bitand(cast(minus(test.t1.c1, 129), bigint(20) BINARY), 55)->Column#4 |
|       └─TableReader_12           | 3.00    | root      |               | data:TopN_11                                                                      |
|         └─TopN_11                | 3.00    | cop[tikv] |               | bitand(cast(minus(test.t1.c1, 129), bigint(20) BINARY), 55), offset:0, count:3    |
|           └─TableFullScan_10     | 3.00    | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                    |
+----------------------------------+---------+-----------+---------------+-----------------------------------------------------------------------------------+
```



So the 
```
mysql> select /*+ READ_FROM_STORAGE(tiflash[t1]) */ (c1 - 129) & 55, (c2- 129) & 55,  ((c1 - 129) & 55) > ((c2- 129) & 55) from t1;
+-----------------+----------------+--------------------------------------+
| (c1 - 129) & 55 | (c2- 129) & 55 | ((c1 - 129) & 55) > ((c2- 129) & 55) |
+-----------------+----------------+--------------------------------------+
|              23 |             16 |                                    1 |
+-----------------+----------------+--------------------------------------+
1 row in set (0.02 sec)

mysql> select /*+ READ_FROM_STORAGE(tikv[t1]) */ (c1 - 129) & 55, (c2- 129) & 55,  ((c1 - 129) & 55) > ((c2- 129) & 55) from t1;
+-----------------+----------------+--------------------------------------+
| (c1 - 129) & 55 | (c2- 129) & 55 | ((c1 - 129) & 55) > ((c2- 129) & 55) |
+-----------------+----------------+--------------------------------------+
|              16 |             16 |                                    0 |
+-----------------+----------------+--------------------------------------+
1 row in set (0.00 sec)
```

**Comment by wshwsh12** [comment]
This issue arises because TiDB and TiKV implement floating-point rounding differently: TiDB uses 'round to even,' while TiKV uses 'round away from zero.'
For example:
```
tidb> create table t(a double);
Query OK, 0 rows affected (0.09 sec)

tidb> insert into t values (-2.5);
Query OK, 1 row affected (0.02 sec)

tidb> select a, cast(a as signed) from t where cast(a as signed) = -2;
Empty set (0.01 sec)

tidb> select a, cast(a as signed) from t where cast(a as signed) = -3;
+------+-------------------+
| a    | cast(a as signed) |
+------+-------------------+
| -2.5 |                -2 |
+------+-------------------+
1 row in set (0.00 sec)
```

Code in tidb: 
https://github.com/pingcap/tidb/blob/9812d85d0d259547cf1dae88abbc7c406c56f935/pkg/types/helper.go#L26-L32

Code in tikv:
https://github.com/tikv/tikv/blob/0659fcc574901dbce94b5ddf6d03d04b539f40f0/components/tidb_query_datatype/src/codec/convert.rs#L292
