### ISSUE TITLE
tidb restart with "fatal error: concurrent map iteration and map write" when run tpcc

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#58074]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run tpcc

### 2. What did you expect to see? (Required)
no fatal error

### 3. What did you see instead (Required)
tidb restart with fatal error when run tpcc
![Image](https://github.com/user-attachments/assets/180215de-9cde-40b0-ae05-a0830241e170)
![Image](https://github.com/user-attachments/assets/48a2e392-fd5d-4882-bc08-6dbdd8b0df40)

```

{"log":"2024-12-09T13:11:39.878008724+08:00 stderr F 	/workspace/source/tidb/pkg/server/conn.go:1147 +0x528","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.878002583+08:00 stderr F github.com/pingcap/tidb/pkg/server.(*clientConn).Run(0xc024a001a0, {0x70dc508, 0xc0167b4000})","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877993054+08:00 stderr F 	/workspace/source/tidb/pkg/server/conn.go:1405 +0x12bb","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877960248+08:00 stderr F github.com/pingcap/tidb/pkg/server.(*clientConn).dispatch(0xc024a001a0, {0x70dc508, 0xc0167b4000}, {0xc0504e0e10, 0x2a, 0x2a})","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877951015+08:00 stderr F 	/workspace/source/tidb/pkg/server/conn_stmt.go:225 +0xb29","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.87794405+08:00 stderr F github.com/pingcap/tidb/pkg/server.(*clientConn).handleStmtExecute(0xc024a001a0, {0x70dc540, 0xc0505efdb0}, {0xc0504e0e11, 0x29, 0x29})","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877937595+08:00 stderr F 	/workspace/source/tidb/pkg/server/conn_stmt.go:234 +0x1d0","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877929812+08:00 stderr F github.com/pingcap/tidb/pkg/server.(*clientConn).executePlanCacheStmt(0xc024a001a0, {0x70dc540, 0xc0505efdb0}, {0x64f03a0, 0xc00439af80}, {0xc08249f260, 0x3, 0x3}, 0x0)","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877909872+08:00 stderr F 	/workspace/source/tidb/pkg/server/conn_stmt.go:306 +0x587","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877900654+08:00 stderr F github.com/pingcap/tidb/pkg/server.(*clientConn).executePreparedStmtAndWriteResult(0xc024a001a0, {0x70dc508, 0xc0505ec3c0}, {0x71175b0, 0xc00439af80}, {0xc08249f260, 0x3, 0x3}, 0x0)","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877874674+08:00 stderr F 	/workspace/source/tidb/pkg/server/driver_tidb.go:291 +0x97","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877867831+08:00 stderr F github.com/pingcap/tidb/pkg/server.(*TiDBContext).ExecuteStmt(0xc017d58888, {0x70dc508, 0xc0505ec3c0}, {0x70f7fe8, 0xc0500d9cc0})","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877855233+08:00 stderr F 	/workspace/source/tidb/pkg/session/session.go:2099 +0x85a","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877848488+08:00 stderr F github.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt(0xc00e762908, {0x70dc508?, 0xc0505ec3c0?}, {0x70f7fe8, 0xc0500d9cc0})","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877841297+08:00 stderr F 	/workspace/source/tidb/pkg/executor/compiler.go:101 +0x41c","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877828726+08:00 stderr F github.com/pingcap/tidb/pkg/executor.(*Compiler).Compile(0xc01fafafa8, {0x70dc508?, 0xc0505ec3c0?}, {0x70f7fe8, 0xc0500d9cc0})","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877816175+08:00 stderr F 	/workspace/source/tidb/pkg/planner/optimize.go:170 +0x39e","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877808724+08:00 stderr F github.com/pingcap/tidb/pkg/planner.Optimize({0x70dc508, 0xc0505ec3c0}, {0x7174f00, 0xc00e762908}, 0xc0505e0e28, {0x7131950, 0xc04c620b70})","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877799172+08:00 stderr F 	/workspace/source/tidb/pkg/planner/optimize.go:552 +0x367","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877782322+08:00 stderr F github.com/pingcap/tidb/pkg/planner.OptimizeExecStmt({0x70dc508, 0xc0505ec3c0}, {0x7174f00, 0xc00e762908}, 0xc0505e0e28, {0x7131950, 0xc04c620b70})","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.87777552+08:00 stderr F 	/workspace/source/tidb/pkg/planner/core/plan_cache.go:216 +0x1c5","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.87776453+08:00 stderr F github.com/pingcap/tidb/pkg/planner/core.GetPlanFromPlanCache({0x70dc508, 0xc0505ec3c0}, {0x7174f00, 0xc00e762908}, 0x0, {0x7131950, 0xc04c620b70}, 0xc008362600, {0xc0505ec420, 0x3, ...})","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877757313+08:00 stderr F 	/workspace/source/tidb/pkg/planner/core/plan_cache_utils.go:389 +0x1bf8","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877738594+08:00 stderr F github.com/pingcap/tidb/pkg/planner/core.NewPlanCacheKey({0x7174f00, 0xc00e762908}, 0xc008362600)","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877723385+08:00 stderr F 	/workspace/source/tidb/pkg/planner/core/logical_plan_builder.go:4172 +0x23c","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877720656+08:00 stderr F github.com/pingcap/tidb/pkg/planner/core.getLatestVersionFromStatsTable({0x7174f00, 0xc00e762908}, 0xc005490c40, 0x7a)","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877718171+08:00 stderr F 	/workspace/source/tidb/pkg/statistics/table.go:316","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877715189+08:00 stderr F github.com/pingcap/tidb/pkg/statistics.(*HistColl).ForEachColumnImmutable(...)","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877710512+08:00 stderr F goroutine 1719050 [running]:","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} 
{"log":"2024-12-09T13:11:39.877702419+08:00 stderr F ","pod":"tc-tidb-1","container":"tidb","namespace":"e2e-oltp-tpcc-large-func-tps-7696246-1-31"} "2024-12-09T13:11:39.874605343+08:00 stderr F fatal error: concurrent map iteration and map write" 
```

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v8.5.0-alpha-299-g56c07d07a7
Edition: Community
Git Commit Hash: 56c07d07a705c163a57c0565370837ca2585bda8
Git Branch: HEAD
UTC Build Time: 2024-12-08 08:54:55
GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-12-09T10:28:33.311+0800

**Comment by Defined2014** [comment]
Maybe dup with https://github.com/pingcap/tidb/issues/57958
