### ISSUE TITLE
fatal error: sync: unlock of unlocked mutex (v8.5.0 stmtctx.go:803)

### ISSUE THREAD

**Issue by chibiegg** [pingcap/tidb#58600]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I'm sorry, but I'm not sure how to reproduce the issue. It occurs sporadically on multiple running TiDB processes.

### 3. What did you see instead (Required)

fatal error on https://github.com/pingcap/tidb/blob/d13e52ed6e22cc5789bed7c64c861578cd2ed55b/pkg/sessionctx/stmtctx/stmtctx.go#L800-L804 .

These errors always occur on the same line.

```
fatal error: sync: unlock of unlocked mutex

goroutine 322590843 [running]:
sync.fatal({0x67ac522?, 0x0?})
	/usr/local/go/src/runtime/panic.go:1031 +0x18
sync.(*Mutex).unlockSlow(0xc0414d09c8, 0xffffffff)
	/usr/local/go/src/sync/mutex.go:231 +0x35
sync.(*Mutex).Unlock(...)
	/usr/local/go/src/sync/mutex.go:225
github.com/pingcap/tidb/pkg/sessionctx/stmtctx.(*StatementContext).AffectedRows(0xa6f0580?)
	/workspace/source/tidb/pkg/sessionctx/stmtctx/stmtctx.go:803 +0x9e
github.com/pingcap/tidb/pkg/util.(*ProcessInfo).ToRow(0xc040ae1860, 0xc003726ee0)
	/workspace/source/tidb/pkg/util/processinfo.go:152 +0x87
github.com/pingcap/tidb/pkg/executor.(*memtableRetriever).setDataForProcessList(0xc084d3a8c0, {0x7114e40, 0xc06e015208})
	/workspace/source/tidb/pkg/executor/infoschema_reader.go:1843 +0x25a
github.com/pingcap/tidb/pkg/executor.(*memtableRetriever).setDataForClusterProcessList(0xc084d3a8c0, {0x7114e40, 0xc06e015208})
	/workspace/source/tidb/pkg/executor/infoschema_reader.go:1816 +0x26
github.com/pingcap/tidb/pkg/executor.(*memtableRetriever).retrieve(0xc084d3a8c0, {0x707dc08, 0xc07adb7c20}, {0x7114e40, 0xc06e015208})
	/workspace/source/tidb/pkg/executor/infoschema_reader.go:179 +0xef3
github.com/pingcap/tidb/pkg/executor.(*MemTableReaderExec).Next(0xc0c5628300, {0x707dc08, 0xc07adb7c20}, 0xc040a6d090)
	/workspace/source/tidb/pkg/executor/memtable_reader.go:136 +0x29c
github.com/pingcap/tidb/pkg/executor/internal/exec.Next({0x707dc08, 0xc07adb7c20}, {0x70b4620, 0xc0c5628300}, 0xc040a6d090)
	/workspace/source/tidb/pkg/executor/internal/exec/executor.go:456 +0x29f
github.com/pingcap/tidb/pkg/executor.(*SelectionExec).Next(0xc040a55080, {0x707dc08, 0xc07adb7c20}, 0xc040a6d0e0)
	/workspace/source/tidb/pkg/executor/select.go:721 +0xeb
github.com/pingcap/tidb/pkg/executor/internal/exec.Next({0x707dc08, 0xc07adb7c20}, {0x70b47d0, 0xc040a55080}, 0xc040a6d0e0)
	/workspace/source/tidb/pkg/executor/internal/exec/executor.go:456 +0x29f
github.com/pingcap/tidb/pkg/executor.(*CoprocessorDAGHandler).HandleRequest(0xc019f318b8, {0x707dc08?, 0xc07adb7770?}, 0xc040a56480)
	/workspace/source/tidb/pkg/executor/coprocessor.go:90 +0x356
github.com/pingcap/tidb/pkg/server.(*rpcServer).handleCopRequest(0xc003655b90, {0x707dc08, 0xc07adb7770}, 0xc040a56480)
	/workspace/source/tidb/pkg/server/rpc_server.go:216 +0x215
github.com/pingcap/tidb/pkg/server.(*rpcServer).Coprocessor(0xc003655b90, {0x707dc08, 0xc07adb7770}, 0xc040a56480)
	/workspace/source/tidb/pkg/server/rpc_server.go:105 +0x96
github.com/pingcap/kvproto/pkg/tikvpb._Tikv_Coprocessor_Handler({0x6700b60, 0xc003655b90}, {0x707dc08, 0xc07adb7770}, 0xc057e61400, 0x0)
	/root/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20240924080114-4a3e17f5e62d/pkg/tikvpb/tikvpb.pb.go:3526 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc003eff000, {0x707dc08, 0xc07adb76e0}, {0x70a1f40, 0xc018578180}, 0xc040a5f9e0, 0xc003655d10, 0x9f0d6d0, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc003eff000, {0x70a1f40, 0xc018578180}, 0xc040a5f9e0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x7f
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 1510
	/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x125
```

### 4. What is your TiDB version? (Required)

```
Release Version: v8.5.0
Edition: Community
Git Commit Hash: d13e52ed6e22cc5789bed7c64c861578cd2ed55b
Git Branch: HEAD
UTC Build Time: 2024-12-18 02:26:06
GoVersion: go1.23.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

**Comment by tiancaiamao** [comment]
Should be triggered by some query on information_schema.xxx tables, and that query lead to tidb coprocessor request ...
The trigger conditiion may similiar to this one https://github.com/pingcap/tidb/issues/57798#issuecomment-2515043843

**Comment by Defined2014** [comment]
Seems we need add `RefCountOfStmtCtx` before use it.

**Comment by Defined2014** [comment]
I think it same as https://github.com/pingcap/tidb/pull/57799 metioned. We didn't check `StatementContext` is still using or not before reset it.

**Comment by chibiegg** [comment]
I think I'm starting to understand this a bit.

Are you suggesting that StatementContext is being duplicated outside the package while still containing mu?

If that's the case, would it be enough to modify the code (similarly to #57986 ) so that at the beginning of the function, we store the pointer to the mutex in a local variable and then use that?

**Comment by Defined2014** [comment]
You mean #57799? I think it's a workaround way. But we need modify a lots functions, such like `SetAffectedRows`, `FoundRows` and so on.

**Comment by chibiegg** [comment]
Sorry, It's TYPO. `(similarly to #57799 )` is collect.

I will try to modify all functions in stmtctx.go .

**Comment by chibiegg** [comment]
I’ve committed my changes and opened PR #58629.
Does this match what you had in mind?

This is my first contribution, so please let me know if there are any issues or anything I need to fix.
I’ve already taken care of tasks like signing the CLA.

**Comment by chibiegg** [comment]
I’d like to gain a deeper understanding of this issue.

As a workaround, I’ve store a pointer of the Mutex to ensure that the target mutex cannot be replaced.

However, I believe the real cause is that StatementContext itself is being overwritten by some operation, like duplication—am I correct in thinking this?
If so, it might be better to fix the usage of StatementContext that occurs outside of the stmtctx package.

That said, I don’t currently have enough knowledge to make that judgment on my own 😢 .

**Comment by Defined2014** [comment]
> I’d like to gain a deeper understanding of this issue.
> 
> As a workaround, I’ve store a pointer of the Mutex to ensure that the target mutex cannot be replaced.
> 
> However, I believe the real cause is that StatementContext itself is being overwritten by some operation, like duplication—am I correct in thinking this? If so, it might be better to fix the usage of StatementContext that occurs outside of the stmtctx package.
> 
> That said, I don’t currently have enough knowledge to make that judgment on my own 😢 .

I think you understand it correctly. So I think the better way to fix this issue is to add `RefCountOfStmtCtx` before use StmtCtx. And the ref count will block reset.

**Comment by chibiegg** [comment]
I see.
Thank you for your explanation and responding to the pull request.

**Comment by chibiegg** [comment]
I see where mu is being replaced.
In StatementContext.Reset() ([lines 469–479](https://github.com/pingcap/tidb/blob/bb689713cccd800450e67690382096fd8c504d7d/pkg/sessionctx/stmtctx/stmtctx.go#L469-L479)), a new Mutex object is assigned.

What if we lock the old Mutex before it gets replaced?

```
        mu := &sc.mu
	mu.Lock()
	cacheMu := &sc.stmtCache.mu
	cacheMu.Lock()
	*sc = StatementContext{
		ctxID:               contextutil.GenContextID(),
		CTEStorageMap:       sc.CTEStorageMap,
		LockTableIDs:        sc.LockTableIDs,
		TableStats:          sc.TableStats,
		MDLRelatedTableIDs:  sc.MDLRelatedTableIDs,
		TblInfo2UnionScan:   sc.TblInfo2UnionScan,
		WarnHandler:         sc.WarnHandler,
		ExtraWarnHandler:    sc.ExtraWarnHandler,
		IndexUsageCollector: sc.IndexUsageCollector,
	}
        mu.Unlock()
        cacheMu.Unlock()
```

**Comment by Defined2014** [comment]
> I see where mu is being replaced. In StatementContext.Reset() ([lines 469–479](https://github.com/pingcap/tidb/blob/bb689713cccd800450e67690382096fd8c504d7d/pkg/sessionctx/stmtctx/stmtctx.go#L469-L479)), a new Mutex object is assigned.
> 
> What if we lock the old Mutex before it gets replaced?
> 
> ```
>         mu := &sc.mu
> 	mu.Lock()
> 	cacheMu := &sc.stmtCache.mu
> 	cacheMu.Lock()
> 	*sc = StatementContext{
> 		ctxID:               contextutil.GenContextID(),
> 		CTEStorageMap:       sc.CTEStorageMap,
> 		LockTableIDs:        sc.LockTableIDs,
> 		TableStats:          sc.TableStats,
> 		MDLRelatedTableIDs:  sc.MDLRelatedTableIDs,
> 		TblInfo2UnionScan:   sc.TblInfo2UnionScan,
> 		WarnHandler:         sc.WarnHandler,
> 		ExtraWarnHandler:    sc.ExtraWarnHandler,
> 		IndexUsageCollector: sc.IndexUsageCollector,
> 	}
>         mu.Unlock()
>         cacheMu.Unlock()
> ```

I think it will block the groutine for a while and influence the SQL execution.

**Comment by chibiegg** [comment]
I’m also concerned about the performance impact. Should we go ahead with the workaround in the commit, or is there a more appropriate method? What would be the best approach here?

**Comment by Defined2014** [comment]
I have a patch to fix this issue, but I haven't submitted a PR because I haven't found a way to reproduce the panic and can't 100% guarantee the effectiveness of the patch.

```diff
diff --git a/pkg/executor/infoschema_reader.go b/pkg/executor/infoschema_reader.go
index 206ebb52fb..e203886e58 100644
--- a/pkg/executor/infoschema_reader.go
+++ b/pkg/executor/infoschema_reader.go
@@ -1839,7 +1839,11 @@ func (e *memtableRetriever) setDataForProcessList(ctx sessionctx.Context) {
                        continue
                }

+               if pi.StmtCtx != nil && pi.RefCountOfStmtCtx != nil && !pi.RefCountOfStmtCtx.TryIncrease() {
+                       continue
+               }
                rows := pi.ToRow(ctx.GetSessionVars().StmtCtx.TimeZone())
+               pi.RefCountOfStmtCtx.Decrease()
                record := types.MakeDatums(rows...)
                records = append(records, record)
        }
```

**Comment by chibiegg** [comment]
I see! So the StatementContext is only reset in InitStatementContext(), and that is also checked by RefCountOfStmtCtx.

https://github.com/pingcap/tidb/blob/de2b7ac04189d61c84cd19bff893ce69b76dbc46/pkg/sessionctx/variable/session.go#L1836-L1848

In other words, rather than acquiring the mutex lock within Reset(), we can properly handle this by appropriately managing RefCountOfStmtCtx in the code that calls functions like AffectedRows(). Is that correct?

**Comment by Defined2014** [comment]
I think so. But we couldn't get RefCountOfStmtCtx  in `AffectedRows()`

**Comment by chibiegg** [comment]
Based on what I’ve seen, in my environment, every occurrence of the panic happened during calls originating from setDataForProcessList (infoschema_reader.go:1843).

I’ll try running the patch you provided on my local environment.

If it works, should we skip the previously committed workaround and only introduce the handling of RefCountOfStmtCtx?
Or is it better to keep both changes?

**Comment by Defined2014** [comment]
I think it is enough to keep `RefCountOfStmtCtx`. But I will let other colleagues review this PR and ask for their opinions

**Comment by chibiegg** [comment]
I wish you a happy New Year.
Thank you for providing guidance despite it being year-end.

Since last night, I’ve deployed a binary that includes the patch referencing `RefCountOfStmtCtx` and have started monitoring it.

I’ll keep observing it for a while.

**Comment by chibiegg** [comment]
I’ve been running with the patch applied for about six days now, and I haven’t encountered any panics so far.

I’ll update the PR commit and push it shortly.
I’ll revert the existing fix and commit the changes that reference RefCountOfStmtCtx as suggested.

**Comment by tiancaiamao** [comment]
The race condition looks like this one https://github.com/pingcap/tidb/issues/57798#issuecomment-2515043843
The race there is query on the "information_schema.tidb_trx" table

And here it looks like "information_schema.CLUSTER_PROCESSLIST"

**Comment by YangKeao** [comment]
Ref https://github.com/pingcap/tidb/pull/54488. This bug affects only 8.5 (for LTS release).
