### ISSUE TITLE
TiDB failed, and then cannot be started

### ISSUE THREAD

**Issue by lerencao** [pingcap/tidb#5879]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

After I do `analyze table mysql.stats_histogram`, I lost the connection to TiDB。
Then the supervisor cannot start it again.

The panic log:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcf8fb1]

goroutine 535 [running]:
github.com/pingcap/tidb/statistics.(*SessionStatsCollector).StoreQueryFeedback(0x0, 0x118fe80, 0xc4204e91d0)
        /home/appweb/.go/src/github.com/pingcap/tidb/statistics/update.go:110 +0xa1
github.com/pingcap/tidb.(*session).StoreQueryFeedback(0xc420af4000, 0x118fe80, 0xc4204e91d0)
        /home/appweb/.go/src/github.com/pingcap/tidb/session.go:221 +0x46
github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startIndexWorker.func1(0x7f820ccfc668, 0xc420b4cde0, 0xc420b4ce70, 0x1ad1200, 0xc42035b9e0, 0xc420f563c0, 0xc420ad8c60)
        /home/appweb/.go/src/github.com/pingcap/tidb/executor/distsql.go:671 +0x142
created by github.com/pingcap/tidb/executor.(*IndexLookUpExecutor).startIndexWorker
        /home/appweb/.go/src/github.com/pingcap/tidb/executor/distsql.go:663 +0x418
```
The starting log:

```
2018/02/13 15:25:42.202 printer.go:36: [info] Welcome to TiDB.
2018/02/13 15:25:42.202 printer.go:37: [info] Release Version:
2018/02/13 15:25:42.202 printer.go:38: [info] Git Commit Hash: d9e16e104fe6eee78efdd02f2a21827838c688b8
2018/02/13 15:25:42.202 printer.go:39: [info] Git Branch: HEAD
2018/02/13 15:25:42.202 printer.go:40: [info] UTC Build Time:  2018-02-13 07:20:01
2018/02/13 15:25:42.202 printer.go:41: [info] GoVersion:  go version go1.9.3 linux/amd64
2018/02/13 15:25:42.203 printer.go:46: [info] Config: [xxxx]
2018/02/13 15:25:42.203 tidb.go:292: [info] new store
2018/02/13 15:25:42.203 client.go:114: [info] [pd] create pd client with endpoints xxx
2018/02/13 15:25:42.206 client.go:212: [info] [pd] leader switches to: , previous:
2018/02/13 15:25:42.206 client.go:133: [info] [pd] init cluster id 6495581505552091655
2018/02/13 15:25:42.210 tidb.go:64: [info] store tikv-6495581505552091655 new domain, ddl lease 10s, stats lease 3000000000
2018/02/13 15:25:42.211 ddl.go:286: [info] [ddl] start delRangeManager OK, with emulator: false
2018/02/13 15:25:42.228 ddl.go:294: [info] [ddl] start DDL:65368bc3-3842-488e-90a5-08c51f369d2f
2018/02/13 15:25:42.353 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 181, in 27.688498ms
2018/02/13 15:25:42.370 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/02/13 15:25:42.399 gc_worker.go:131: [info] [gc worker] 586383849ec0001 start.
2018/02/13 15:25:42.406 simple.go:134: [info] [0] execute rollback statement
2018/02/13 15:25:42.406 txn.go:201: [info] [kv] Rollback txn 398067431478394888
2018/02/13 15:25:42.406 server.go:188: [warning] Secure connection is NOT ENABLED
2018/02/13 15:25:42.407 server.go:156: [info] Server is running MySQL Protocol at [0.0.0.0:4000]
2018/02/13 15:25:42.407 main.go:201: [info] start Prometheus push client with server addr 172.16.48.193:9091 and interval 10s
2018/02/13 15:25:42.407 systime_mon.go:24: [info] start system time monitor
2018/02/13 15:25:42.408 http_status.go:70: [info] Listening on :10800 for status and metrics report.
2018/02/13 15:25:42.454 domain.go:641: [info] [stats] init stats info takes 54.749524ms
```

I found that the `SessionStatsCollector` was nil, before `s.Lock()` was called.

Sorry, cannot provide more infos.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

commit id: `d9e16e104fe6eee78efdd02f2a21827838c688b8`

**Comment by shenli** [comment]
@lerencao Thanks for your feedback!
@lamxTyler PTAL

**Comment by lerencao** [comment]
Thx for the quick fix!

**Comment by shenli** [comment]
@lerencao You are welcome!

**Comment by lamxTyler** [comment]
@lerencao You can try the lastest mater now.
