### ISSUE TITLE
MySQL JDBC connections severed, single tidb node.

### ISSUE THREAD

**Issue by sprooose** [pingcap/tidb#6109]
**1. What did you do?**

We are trialling our application on TiDB. It is java application with a relational repository that we run transactions against.
The application uses a JDBC connection pool and runs very generic SQL against the repository database (as we support other RDBMs as well). Connections from the pool are held open, and reused by different parts of the code. The connections are closed and recreated every hour or so.

In this case we are running the application on the same physical server as a single node TiDB instance.
When running our application these connections are severed randomly. We see these errors in our application:

```
YF:2018-03-20 10:37:23:ERROR (DBAction:error) - Error occured selecting data: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
 	The last packet successfully received from the server was 1 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
 	com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
 	
 	The last packet successfully received from the server was 1 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
 		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 		at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
 		at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1121)
 		at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3670)
 		at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3559)
 		at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4110)
 		at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
 		at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
```

Our Java application is the only application connecting to TiDB.. However, the pool does open multiple connections to the TiDB for concurrent actions.

**2. What did you expect to see?**

Transactional Integrity and no disconnected connections.

**3. What did you see instead?**

The dropped JDBC connections seem to correlate with transaction conflicts in the TiDB logs..

`2018/03/21 12:50:00.049 session.go:340: [warning] [168] retryable error: [try again later]: tikv restarts txn: Txn(Mvcc(WriteConflict { start_ts: 398887865493487617, conflict_ts: 398887904867516422, key: [116, 128, 0, 0, 0, 0, 0, 1, 255, 219, 95, 114, 128, 0, 0, 0, 0, 255, 0, 0, 8, 0, 0, 0, 0, 0, 250], primary: [116, 128, 0, 0, 0, 0, 0, 1, 219, 95, 114, 128, 0, 0, 0, 0, 0, 0, 8] })), txn: {<nil> <nil> 0xc423463b40 map[] [] <nil>}`

Does this error drop JDBC connections?
Does the "Try Again Later" message mean that the application is supposed to reattempt the transaction? Or does TiDB reattempt to run this transaction itself?

(Our legacy application can not be modified to reattempt failed transactions... this is why TiDB was chosen as a possible candidate as we assumed a similar transaction experience to MySQL) 

**4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?**

Binary install on physical hardware.

Release Version:  v2.0.0-rc.1-66-gdaa866c
Git Commit Hash:  daa866cdd48e4c0f0d1969bc9238e727a87c6813
Git Commit Branch:  master
UTC Build Time:  2018-03-18 01:11:47
GoVersion:  go version go1.10 linux/amd64
TiKV Min Version:  1.1.0-dev.2

**Comment by lamxTyler** [comment]
@sprooose "Try Again Later" means tidb will reattempt to run it. 
Is there any panic info in TiDB log?

**Comment by sprooose** [comment]
Oh, yes @lamxTyler, there is a panic... here it is:

```
2018/03/22 08:49:35.879 conn.go:420: [error] lastCmd SELECT DISTINCT p.IpPerson, rc.IpParent,
   rc.RltshpTypeCode, p.FirstName, p.MiddleInitial, p.LastName, r.RoleCode, p.Status, 
   c.EmailLeft, c.EmailRight
FROM Person p, IpRltshp rp, IpRltshp rc, StaffMemberRole r, IpClass c
WHERE rp.IpParent = 1
AND (
   (
      rp.IpParent = rp.IpChild
      AND rp.RltshpTypeCode = 'ORGHIRCHY'
   ) OR (
      rp.IpParent != rp.IpChild
      AND rp.RltshpTypeCode = 'CUSTOMER'
   )
)
AND rp.StartDate <= '2018-03-22'
AND rp.EndDate > '2018-03-22'
AND rp.IpChild = rc.IpParent
AND rc.IpParent = 1
AND rc.IpChild = p.IpPerson
AND rc.RltshpTypeCode = 'STAFFMEMBER'
AND rc.StartDate <= '2018-03-22'
AND rc.EndDate > '2018-03-22'
AND r.IpAccessOrg = rp.IpParent
AND r.IpEmployer = rp.IpParent
AND r.IpEmployee = p.IpPerson
AND r.StartDate <= '2018-03-22'
AND r.EndDate > '2018-03-22'
AND c.IpId = p.IpPerson
AND c.StartDate <= '2018-03-22'
AND c.EndDate > '2018-03-22'
AND p.Status != 'INACTIVE'
AND p.Status != 'INACTIVEWITHEMAIL'
ORDER BY 5, 4
, runtime error: invalid memory address or nil pointer dereference, goroutine 888816 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc422368ea0, 0xc4223c1e0f)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:418 +0x10e
panic(0x1061da0, 0x1c1e580)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/pingcap/tidb/expression.(*Constant).Equal(0xc421e35dc0, 0x0, 0x0, 0x132f3c0, 0xc421e35dc0, 0xc421e35c00)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/constant.go:303 +0xae
github.com/pingcap/tidb/expression.(*baseBuiltinFunc).equal(0xc421ed4240, 0x1328380, 0xc421ed4240, 0xc421e35c00)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/builtin.go:207 +0xe0
github.com/pingcap/tidb/expression.(*ScalarFunction).Equal(0xc420a77270, 0x0, 0x0, 0x132f540, 0xc420a77270, 0xc4211b6e01)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/scalar_function.go:164 +0xb9
github.com/pingcap/tidb/expression.(*baseBuiltinFunc).equal(0xc421ed4280, 0x1328400, 0xc421ed4280, 0xc4216cf500)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/builtin.go:207 +0xe0
github.com/pingcap/tidb/expression.(*ScalarFunction).Equal(0xc420a772c0, 0x132f240, 0xc422368f70, 0x132f540, 0xc420a772c0, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/scalar_function.go:164 +0xb9
github.com/pingcap/tidb/statistics.getMaskAndRanges(0x132f240, 0xc422368f70, 0xc421203620, 0x3, 0x3, 0x2, 0xc421e16d80, 0x3, 0x3, 0xc4218da9a0, ...)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/statistics/selectivity.go:169 +0x240
github.com/pingcap/tidb/statistics.(*Table).Selectivity(0xc420be0140, 0x132f240, 0xc422368f70, 0xc421203620, 0x3, 0x3, 0x2, 0x0, 0x411da7)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/statistics/selectivity.go:116 +0x76d
github.com/pingcap/tidb/plan.(*DataSource).getStatsByFilter(0xc420f9a5a0, 0xc421203620, 0x3, 0x3, 0xc4211b6df0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/plan/stats.go:96 +0x25c
github.com/pingcap/tidb/plan.(*PhysicalIndexScan).addPushedDownSelection(0xc422518640, 0xc4212037d0, 0xc420f9a5a0, 0x7fefffffffffffff)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/plan/physical_plan_builder.go:431 +0x179
github.com/pingcap/tidb/plan.(*DataSource).convertToIndexScan(0xc420f9a5a0, 0xc420a76dc0, 0xc4202c7a00, 0xc4218da640, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/plan/physical_plan_builder.go:389 +0x869
github.com/pingcap/tidb/plan.(*DataSource).convert2PhysicalPlan(0xc420f9a5a0, 0xc420a76dc0, 0xc420a76dc0, 0xc4218da420, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/plan/physical_plan_builder.go:219 +0x1aa
github.com/pingcap/tidb/plan.(*baseLogicalPlan).getBestTask(0xc42213c908, 0x1317880, 0x1c1f770, 0x132da80, 0xc42482ea20, 0xc424337c80, 0x20, 0x2, 0xc4223c10e0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/plan/physical_plan_builder.go:106 +0x125
github.com/pingcap/tidb/plan.(*baseLogicalPlan).convert2PhysicalPlan(0xc42213c908, 0xc420a76be0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/plan/physical_plan_builder.go:94 +0x116
github.com/pingcap/tidb/plan.(*baseLogicalPlan).getBestTask(0xc42213ca88, 0x1317880, 0x1c1f770, 0x132da80, 0xc42482e7e0, 0xc424337b60, 0x20, 0x2, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/plan/physical_plan_builder.go:106 +0x125
github.com/pingcap/tidb/plan.(*baseLogicalPlan).convert2PhysicalPlan(0xc42213ca88, 0xc420a769b0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/plan/physical_plan_builder.go:94 +0x116
github.com/pingcap/tidb/plan.(*baseLogicalPlan).getBestTask(0xc42213cc08, 0x1317880, 0x1c1f770, 0x132da80, 0xc42482e5a0, 0x1317880, 0x1c1f770, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/gi

```

**Comment by lamxTyler** [comment]
@sprooose Could you provide the related table schema so we can reproduce this?

**Comment by sprooose** [comment]
Here is the table schema:

```
CREATE TABLE `IpClass` (
  `IpId` int(11) DEFAULT NULL,
  `EmailLeft` varchar(200) DEFAULT NULL,
  `EmailRight` varchar(200) DEFAULT NULL,
  `Password` varchar(256) DEFAULT NULL,
  `CRC` varchar(256) DEFAULT NULL,
  `PasswordExpired` tinyint(1) DEFAULT NULL,
  `StartDate` date DEFAULT NULL,
  `EndDate` date DEFAULT NULL,
  `AccessAttempts` int(11) DEFAULT NULL,
  KEY `xfkIpClass` (`IpId`),
  KEY `xckIpClass` (`EndDate`,`EmailLeft`,`EmailRight`),
  KEY `xpkIpClass` (`EmailRight`,`EmailLeft`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `IpRltshp` (
  `IpParent` int(11) DEFAULT NULL,
  `IpChild` int(11) DEFAULT NULL,
  `RltshpTypeCode` varchar(40) DEFAULT NULL,
  `StartDate` date DEFAULT NULL,
  `EndDate` date DEFAULT NULL,
  `EndReasonCode` varchar(40) DEFAULT NULL,
  `InternalReferenceId` varchar(256) DEFAULT NULL,
  `PrivacyLevelCode` varchar(40) DEFAULT NULL,
  `RltshpLevelCode` varchar(40) DEFAULT NULL,
  `DefReHireCode` varchar(40) DEFAULT NULL,
  KEY `xckIpRltshp` (`IpChild`,`RltshpTypeCode`,`EndDate`),
  KEY `xpkIpRltshp` (`IpParent`,`IpChild`,`RltshpTypeCode`,`EndDate`),
  KEY `xskIpRltshp` (`IpChild`),
  KEY `xzkIpRltshp` (`IpParent`,`InternalReferenceId`(128),`StartDate`,`EndDate`),
  KEY `xfkIpRltshp` (`IpParent`,`RltshpTypeCode`,`EndDate`),
  KEY `xxkIpRltshp` (`IpChild`,`IpParent`,`RltshpTypeCode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `Person` (
  `IpPerson` int(11) DEFAULT NULL,
  `LastName` varchar(256) DEFAULT NULL,
  `FirstName` varchar(256) DEFAULT NULL,
  `MiddleInitial` varchar(40) DEFAULT NULL,
  `Gender` varchar(40) DEFAULT NULL,
  `DateOfBirth` date DEFAULT NULL,
  `Soundex` varchar(40) DEFAULT NULL,
  `SalutationCode` varchar(40) DEFAULT NULL,
  `FullName` varchar(256) DEFAULT NULL,
  `PreferredName` varchar(256) DEFAULT NULL,
  `PreferredLanguageCode` varchar(40) DEFAULT NULL,
  `ExposureLevelCode` varchar(40) DEFAULT NULL,
  `PrivacyLevelCode` varchar(40) DEFAULT NULL,
  `PreferredContactMethodCode` varchar(40) DEFAULT NULL,
  `PrivateKeyId` varchar(40) DEFAULT NULL,
  `PrivateURL` varchar(256) DEFAULT NULL,
  `ResumeLastUpdate` date DEFAULT NULL,
  `LocalTimeZoneCode` varchar(40) DEFAULT NULL,
  `ResumeLastCrunch` date DEFAULT NULL,
  `ResumeWorkStartDate` date DEFAULT NULL,
  `ProfileLastUpdate` date DEFAULT NULL,
  `Status` varchar(40) DEFAULT NULL,
  KEY `xpkPerson` (`IpPerson`),
  KEY `xtkPerson` (`LastName`(64),`FirstName`(64),`Gender`,`DateOfBirth`),
  KEY `xskPerson` (`Soundex`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `StaffMemberRole` (
  `IpEmployee` int(11) DEFAULT NULL,
  `IpEmployer` int(11) DEFAULT NULL,
  `RoleCode` varchar(40) DEFAULT NULL,
  `StartDate` date DEFAULT NULL,
  `EndDate` date DEFAULT NULL,
  `IpAccessOrg` int(11) DEFAULT NULL,
  KEY `xfkStaffMemberRole` (`IpEmployee`,`RoleCode`),
  KEY `xxkStaffMemberRole` (`IpAccessOrg`,`RoleCode`,`EndDate`,`StartDate`),
  KEY `xpkStaffMemberRole` (`IpEmployer`,`RoleCode`),
  KEY `xskStaffMemberRole` (`IpEmployer`,`IpEmployee`,`RoleCode`,`EndDate`,`StartDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

**Comment by winkyao** [comment]
@sprooose Thanks, we'll look into this.

**Comment by sprooose** [comment]
Turns out that in this instance, each of these tables only had 1 row each... Here is the data:

```
INSERT INTO IpClass (IpId,EmailLeft,EmailRight,Password,CRC,PasswordExpired,StartDate,EndDate,AccessAttempts) VALUES 
(5,'admin','fasf.com.au','mEgW/TKWIoduFJB2NCZObzMun7M=','4120855952',0,'2018-03-18','9999-12-31',0)
;

INSERT INTO IpRltshp (IpParent,IpChild,RltshpTypeCode,StartDate,EndDate,EndReasonCode,InternalReferenceId,PrivacyLevelCode,RltshpLevelCode,DefReHireCode) VALUES 
(1,1,'ORGHIRCHY','2001-01-01','9999-12-31',NULL,NULL,NULL,NULL,NULL)
,(1,2,'SystemAdministrator','2001-01-01','9999-12-31',NULL,NULL,NULL,NULL,NULL)
,(1,5,'STAFFMEMBER','2001-01-01','9999-12-31',NULL,NULL,'4',NULL,NULL)
;

INSERT INTO Person (IpPerson,LastName,FirstName,MiddleInitial,Gender,DateOfBirth,Soundex,SalutationCode,FullName,PreferredName,PreferredLanguageCode,ExposureLevelCode,PrivacyLevelCode,PreferredContactMethodCode,PrivateKeyId,PrivateURL,ResumeLastUpdate,LocalTimeZoneCode,ResumeLastCrunch,ResumeWorkStartDate,ProfileLastUpdate,Status) VALUES 
(5,'Administrator','System','','',NULL,'ATMN SSTM','','System Administrator','System Administrator','EN','PRIVATE','4','EMAIL',NULL,NULL,NULL,'AUSTRALIA/SYDNEY',NULL,NULL,NULL,'ACTIVE')
;

INSERT INTO StaffMemberRole (IpEmployee,IpEmployer,RoleCode,StartDate,EndDate,IpAccessOrg) VALUES 
(5,1,'ADMIN','2005-05-04','9999-12-31',1)
;






```

**Comment by winkyao** [comment]
@XuHuaiyu @zz-jason PTAL
