### ISSUE TITLE
Panic when upgrade TiDB to 2.0.0

### ISSUE THREAD

**Issue by lerencao** [pingcap/tidb#6464]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
After upgrading TiKV, panic occurred when upgrade TiDB.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xcff0a1]

goroutine 276 [running]:
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).logTimeCopTask(0xc421c372f0, 0x159702ea, 0xc4213da5c0, 0xc420865020, 0xc4203d6210)
        /data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:665 +0x1d1
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleTaskOnce(0xc421c372f0, 0xc420865020, 0xc4213da5c0, 0xc420864ea0, 0x3, 0x48, 0x58, 0xc420865020, 0x0)
        /data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:638 +0x54a
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).handleTask(0xc421c372f0, 0xc420865020, 0xc4213da5c0, 0xc420864ea0)
        /data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:591 +0xb4
github.com/pingcap/tidb/store/tikv.(*copIteratorWorker).run(0xc421c372f0, 0x7ff9133fc7b0, 0xc421c36ff0)
        /data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:427 +0x1d4
github.com/pingcap/tidb/store/tikv.(*copIterator).open.func1()
        /data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:455 +0x3c
github.com/pingcap/tidb/util/goroutine_pool.(*goroutine).workLoop(0xc4207d8760, 0xc420301bc0)
        /data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/util/goroutine_pool/gp.go:115 +0x171
created by github.com/pingcap/tidb/util/goroutine_pool.(*Pool).alloc
        /data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/util/goroutine_pool/gp.go:90 +0x97
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xcff0a1]
```

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version:  v2.0.0
Git Commit Hash:  637e130e6a9ba2e54e158131c0466233db39a60e
Git Commit Branch:  HEAD
UTC Build Time:  2018-05-04 03:51:55
GoVersion:  go version go1.10 linux/amd64
TiKV Min Version:  2.0.0-rc.4.1
```

**Comment by lerencao** [comment]
It's happened only once. supervise restart the process, and it didn't happen again.

**Comment by coocood** [comment]
@lerencao 
Which version did you upgrade from?

**Comment by lerencao** [comment]
@coocood 

TiDB:

```
$  ./backup/tidb-server.12119.2018-05-04\@14\:30\:25~ -V
Release Version:  v2.0.0-rc.3
Git Commit Hash:  861103b4ae70d49fab81cebeaae0576cbbaccd55
Git Commit Branch:  HEAD
UTC Build Time:  2018-03-23 02:28:53
GoVersion:  go version go1.10 linux/amd64
TiKV Min Version:  1.1.0-dev.2
```

TiKV: 
```
$ ./tikv/backup/tikv-server.17654.2018-05-04\@13\:53\:21~ -V
TiKV
Release Version:   2.0.0-rc.3
Git Commit Hash:   8e78e3db1b5f10eabff31df25dfa111bb72a4241
Git Commit Branch: HEAD
UTC Build Time:    2018-03-23 02:29:59
Rust Version:      1.25.0-nightly (73ac5d6a8 2018-01-11)
```

**Comment by coocood** [comment]
@lerencao 
This panic should only happen when `enable-streaming` is true, did you enabled it?
You can run `select @@tidb_config` to get the config info.

**Comment by lerencao** [comment]
Yes, It's enabled

**Comment by tiancaiamao** [comment]
Thanks for your feedback.
We'll fix it soon, you can disable `enable-streaming` to avoid this problem.
@lerencao

**Comment by lerencao** [comment]
@tiancaiamao @coocood Thanks. 
Please feedback on this issue when the fix comes out. ^^

**Comment by coocood** [comment]
Thank you for your report, the PR is sent.
https://github.com/pingcap/tidb/pull/6467

**Comment by lerencao** [comment]
That's awesome.

**Comment by coocood** [comment]
fixed by https://github.com/pingcap/tidb/pull/6467
