### ISSUE TITLE
When the field list of the select statement contains the Enum type, the client will report an error

### ISSUE THREAD

**Issue by mz1999** [pingcap/tidb#6910]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

When I use Server Prepared Statements, that is set `useServerPrepStmts=true`, if the select statement's field list contains the `Enum` type, the client will report an error.

```
CREATE TABLE shirts (
    name VARCHAR(40),
    size ENUM('small', 'medium', 'large')
);

INSERT INTO shirts (name, size) VALUES ('dress shirt','large'), ('t-shirt','medium'),('polo shirt','small');

mysql> desc shirts;
+-------+--------------------------------+------+------+---------+-------+
| Field | Type                           | Null | Key  | Default | Extra |
+-------+--------------------------------+------+------+---------+-------+
| name  | varchar(40)                    | YES  |      | NULL    |       |
| size  | enum('small','medium','large') | YES  |      | NULL    |       |
+-------+--------------------------------+------+------+---------+-------+
```
Java Code snippet：

```
    String DB_URL = "jdbc:mysql://xxx.xxx.xxxx.xxx:4000/test";
    Properties info = new Properties();
    info.setProperty("user", "root");
    info.setProperty("password", "");
    info.setProperty("useServerPrepStmts", "true");
    Connection conn = DriverManager.getConnection(DB_URL, info);

    String sql = "SELECT name, size FROM shirts WHERE name = ?";

    PreparedStatement preparedStatement = conn.prepareStatement(sql);
    preparedStatement.setString(1, "t-shirt");
    ResultSet resultSet = preparedStatement.executeQuery();

    while (resultSet.next()) {
        String name = resultSet.getString("name");
        String size = resultSet.getString("size");
        System.out.println(name + ", " + size );
    }
```
MySQL Connector/J version：

```
<dependency>
     <groupId>mysql</groupId>
     <artifactId>mysql-connector-java</artifactId>
     <version>6.0.6</version>
</dependency>
```

2. What did you expect to see?

I expect the TiDB to return the correct query result.

3. What did you see instead?

The client reported the following error message:

```
Exception in thread "main" java.sql.SQLException: Unknown type '247' in column '1' of '2' in binary-encoded result set.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1299)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:701)
	at com.mysql.cj.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1923)
	at com.apusic.test.CursorExample.main(CursorExample.java:27)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

----------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.0-alpha-75-g41f8ac195
Git Commit Hash: 41f8ac19523386d0eb6ca871397f49f834958169
Git Branch: master
UTC Build Time: 2018-06-26 07:08:04
GoVersion: go version go1.10.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e |
+------------------------------------------------------------------------------------

**Comment by tiancaiamao** [comment]
Thanks for your report. @mz1999 
Could you also provide the TiDB log, is there any `[error]` in it?

**Comment by mz1999** [comment]
There is no error message in the TiDB server side log.

```
2018/06/27 08:41:28.751 server.go:310: [info] [con:3] new connection 172.20.225.10:55513
2018/06/27 08:41:28.838 set.go:181: [info] [con:3] set system variable character_set_results = NULL
2018/06/27 08:41:28.842 set.go:181: [info] [con:3] set system variable autocommit = 1
2018/06/27 08:41:29.356 server.go:312: [info] [con:3] close connection
```

**Comment by zz-jason** [comment]
Guess the column type info we returned is not correct. How about starting the MySQL client with “—column-type-into” and do the same query on both MySQL and TiDB.

**Comment by mz1999** [comment]
Using MySQL client with '--column-type-info' to query TiDB

```
mysql> SELECT name, size FROM shirts WHERE size = 'medium';
Field   1:  `name`
Catalog:    `def`
Database:   `test`
Table:      `shirts`
Org_table:  `shirts`
Type:       VAR_STRING
Collation:  utf8_general_ci (33)
Length:     160
Max_length: 7
Decimals:   0
Flags:      

Field   2:  `size`
Catalog:    `def`
Database:   `test`
Table:      `shirts`
Org_table:  `shirts`
Type:       ENUM
Collation:  utf8_general_ci (33)
Length:     0
Max_length: 6
Decimals:   0
Flags:      


+---------+--------+
| name    | size   |
+---------+--------+
| t-shirt | medium |
+---------+--------+
1 row in set (0.00 sec)
```

The same query is executed on MySQL

```
mysql> SELECT name, size FROM shirts WHERE size = 'medium';
Field   1:  `name`
Catalog:    `def`
Database:   `test`
Table:      `shirts`
Org_table:  `shirts`
Type:       VAR_STRING
Collation:  utf8_general_ci (33)
Length:     120
Max_length: 7
Decimals:   0
Flags:      

Field   2:  `size`
Catalog:    `def`
Database:   `test`
Table:      `shirts`
Org_table:  `shirts`
Type:       STRING
Collation:  utf8_general_ci (33)
Length:     21
Max_length: 6
Decimals:   0
Flags:      ENUM 


+---------+--------+
| name    | size   |
+---------+--------+
| t-shirt | medium |
+---------+--------+
1 row in set (0.00 sec)
```

**Note**:  Client doesn't encounter errors without using Server Prepared Statements

**Comment by zz-jason** [comment]
The `Type` value that TiDB returned for field `size` is `Type:       ENUM`, while MySQL returned the `Type:       STRING`. In TiDB, [the byte value for `ENUM` type is `0xf7`](https://github.com/pingcap/tidb/blob/master/mysql/type.go#L39), which is `247`. And the error message is: **"Exception in thread "main" java.sql.SQLException: Unknown type '247' in column '1' of '2' in binary-encoded result set."**.

I guess this is the root cause.

**Comment by tiancaiamao** [comment]
@lysu  Do you have any idea for this issue?

**Comment by lysu** [comment]
ok, I will investigate and fix it later, I feel @zz-jason 's comment maybe be the root cause too.
