### ISSUE TITLE
Support the `init_vector` argument for builtin function `AES_ENCRYPT`/`AES_DECRYPT`

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#7300]
The MySQL document about builtin function `AES_ENCRYPT`/`AES_DECRYPT`:
- `AES_ENCRYPT`: https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_aes-encrypt
- `AES_DECRYPT`: https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_aes-decrypt

The function signature can be simplified as:
```
AES_ENCRYPT(str,key_str[,init_vector])
AES_DECRYPT(crypt_str,key_str[,init_vector])
```

Currently, TiDB can only handle the first two arguments:
```sql
TiDB(localhost:4000) > select AES_ENCRYPT("a", "b");
+-----------------------+
| AES_ENCRYPT("a", "b") |
+-----------------------+
| T<q\(Ll.IN         |
+-----------------------+
1 row in set (0.00 sec)

TiDB(localhost:4000) > select AES_DECRYPT("a", "b");
+-----------------------+
| AES_DECRYPT("a", "b") |
+-----------------------+
| NULL                  |
+-----------------------+
1 row in set (0.00 sec)
```

If we pass the third argument, TiDB panics:
```sql
TiDB(localhost:4000) > select AES_ENCRYPT("a", "b", "c");
ERROR 2013 (HY000): Lost connection to MySQL server during query

TiDB(localhost:4000) > select AES_DECRYPT("a", "b", "c");
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

And the panic stack is:
```
2018/08/07 16:39:46.059 conn.go:427: [error] lastCmd select AES_DECRYPT("a", "b", "c"), unexpected length of args and argTps, goroutine 11721 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc43df65c70, 0xc43c981dff)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/server/conn.go:425 +0x10e
panic(0x1cfdda0, 0x203e450)
        /Users/jianzhang.zj/opt/goroot/src/runtime/panic.go:505 +0x229
github.com/pingcap/tidb/expression.newBaseBuiltinFuncWithTp(0x207d7a0, 0xc4403d8b60, 0xc43fc5e4e0, 0x3, 0x3, 0x3, 0xc43c980eae, 0x2, 0x2, 0x0, ...)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/expression/builtin.go:64 +0xa91
github.com/pingcap/tidb/expression.(*aesDecryptFunctionClass).getFunction(0xc4202d3ba0, 0x207d7a0, 0xc4403d8b60, 0xc43fc5e4e0, 0x3, 0x3, 0x4, 0x3, 0x40, 0x1e741a0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/expression/builtin_encryption.go:84 +0xef
github.com/pingcap/tidb/expression.NewFunction(0x207d7a0, 0xc4403d8b60, 0xc43f460090, 0xb, 0xc432fca048, 0xc438892600, 0x3, 0x4, 0x1e31260, 0xc438892600, ...)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/expression/scalar_function.go:87 +0x20b
github.com/pingcap/tidb/plan.(*expressionRewriter).funcCallToExpression(0xc43ca4a280, 0xc432fca000)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/expression_rewriter.go:1198 +0x174
github.com/pingcap/tidb/plan.(*expressionRewriter).Leave(0xc43ca4a280, 0x204fb60, 0xc432fca000, 0x2067920, 0xc43b7ba210, 0x1ab3a01)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/expression_rewriter.go:745 +0x86a
github.com/pingcap/tidb/ast.(*FuncCallExpr).Accept(0xc432fca000, 0x204b260, 0xc43ca4a280, 0x1a3e29b, 0x207d4a0, 0xc43ca4a200)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/ast/functions.go:363 +0x1bf
github.com/pingcap/tidb/plan.(*planBuilder).rewriteExprNode(0xc43b7ba2c0, 0xc43ca4a280, 0x2067220, 0xc432fca000, 0xc43c981201, 0x1010559, 0xc438892580, 0x40, 0x38, 0x1e06660, ...)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/expression_rewriter.go:133 +0x54
github.com/pingcap/tidb/plan.(*planBuilder).rewriteWithPreprocess(0xc43b7ba2c0, 0x2067220, 0xc432fca000, 0x207d4a0, 0xc43ca4a200, 0x0, 0x1ed2501, 0x0, 0x0, 0x0, ...)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/expression_rewriter.go:105 +0x12b
github.com/pingcap/tidb/plan.(*planBuilder).rewrite(0xc43b7ba2c0, 0x2067220, 0xc432fca000, 0x207d4a0, 0xc43ca4a200, 0x0, 0x1, 0x0, 0x0, 0x0, ...)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/expression_rewriter.go:81 +0x96
github.com/pingcap/tidb/plan.(*planBuilder).buildProjection(0xc43b7ba2c0, 0x207d4a0, 0xc43ca4a200, 0xc435b78088, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, ...)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/logical_plan_builder.go:562 +0x219
github.com/pingcap/tidb/plan.(*planBuilder).buildSelect(0xc43b7ba2c0, 0xc43b8b4000, 0x207d4a0, 0xc43ca4a200, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/logical_plan_builder.go:1656 +0x35d
github.com/pingcap/tidb/plan.(*planBuilder).build(0xc43b7ba2c0, 0x2050420, 0xc43b8b4000, 0xc43b8b4000, 0x0, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/planbuilder.go:153 +0x702
github.com/pingcap/tidb/plan.Optimize(0x207d7a0, 0xc4403d8b60, 0x2050420, 0xc43b8b4000, 0x2067aa0, 0xc422698120, 0x2aa5000, 0x0, 0x0, 0x21)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/plan/optimizer.go:73 +0x15f
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc43c9819f8, 0x2f4a338, 0xc43fc5e2a0, 0x205a2e0, 0xc43b8b4000, 0x0, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/executor/compiler.go:48 +0x1de
github.com/pingcap/tidb/session.(*session).execute(0xc4403d8b60, 0x2f4a338, 0xc43fc5e2a0, 0xc433002001, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/session/session.go:807 +0x675
github.com/pingcap/tidb/session.(*session).Execute(0xc4403d8b60, 0x2ee8b58, 0xc438892500, 0xc433002001, 0x21, 0x1, 0x0, 0x0, 0xc420857bb0, 0x10d2af0)
        /Users/jianzhang.zj/opt/gopath/src/github.com/pingcap/tidb/session/session.go:765 +0x69
github.com/pingcap/t
2018/08/07 16:39:46.059 server.go:316: [info] con:4 close connection
```

**Comment by mccxj** [comment]
https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html#function_aes-decrypt
The  block_encryption_mode system variable controls the mode for block-based encryption algorithms.

I try to add ECB/CBC modes with 128/192/256-bit key length for AES function. New PR is coming soon.
