### ISSUE TITLE
oltp-bench cannot successfully load data into tidb when SF=50

### ISSUE THREAD

**Issue by LiYuming** [pingcap/tidb#9010]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Evaluating the TPC-C performance of TiDB with oltp-bench (https://github.com/oltpbenchmark/oltpbench).

2. What did you expect to see?

The test database can be loaded successfully~

3. What did you see instead?

When SF=10 and SF=20, test database can be successfully loaded into tidb.
But when SF =50, there are some errors reported during the data loading, and it's reproducible.
Performance evaluation cannot be performed because the test database is half-baked.

The error is as follows:
java.sql.BatchUpdateException: statement count 5001 exceeds the transaction limitation, autocommit = false
        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2054)
        at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1467)
        at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader.loadOrders(TPCCLoader.java:661)
        at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader$2.load(TPCCLoader.java:120)
        at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
        at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: statement count 5001 exceeds the transaction limitation, autocommit = false
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2006)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

release-2.1

**Comment by LiYuming** [comment]
For MySQL and PostgreSQL, it's ok when SF = 50.

**Comment by LiYuming** [comment]
I get the solution from https://github.com/pingcap/tidb/issues/6042~

**Comment by jackysp** [comment]
Hi @LiYuming 
If you're using TiDB master branch, add `sessionVariables=tidb_batch_commit=1` after the jdbc DSN, it will automatically split the large transaction in batch. It is useful when loading data.
