### ISSUE TITLE
Panicked when using `explain analyze`

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#9484]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

run TPC-H Q10 using `explain analyze`.

2. What did you expect to see?

return result.

3. What did you see instead?

```log
runtime error: index out of range, goroutine 1015 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc0069bb110)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:534 +0x10a
panic(0x1b10da0, 0x2cc0860)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/pingcap/tidb/server.(*clientConn).writeResultset.func1(0x0, 0x1efc300, 0xc009382460, 0xc000259bd0, 0xc0069bb110)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1086 +0x32f
panic(0x1b10da0, 0x2cc0860)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/pingcap/tidb/util/chunk.(*column).isNull(...)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/util/chunk/column.go:71
github.com/pingcap/tidb/util/chunk.Row.IsNull(...)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/util/chunk/row.go:223
github.com/pingcap/tidb/server.dumpTextRow(0xc0089e1400, 0x31, 0x400, 0xc04ffb45c0, 0x5, 0x8, 0xc00937ff80, 0x10, 0xc0089e1400, 0xb3, ...)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/util.go:285 +0x1047
github.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc0069bb110, 0x1ef1820, 0xc008f4e100, 0x1efc300, 0xc009382460, 0xc00000fb00, 0xc0069bb110, 0xc008f03440)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1158 +0x2cd
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc0069bb110, 0x1ef1820, 0xc008f4e100, 0x1efc300, 0xc009382460, 0xc000003400, 0x0, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1099 +0x1bc
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc0069bb110, 0x1ef1820, 0xc008f4e100, 0xc008f50001, 0x254, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1016 +0x124
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc0069bb110, 0xc008f50001, 0x255, 0x255, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:745 +0x59a
github.com/pingcap/tidb/server.(*clientConn).Run(0xc0069bb110)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:582 +0x205
github.com/pingcap/tidb/server.(*Server).onConn(0xc00718a1c0, 0x1efeb20, 0xc0004f6a60)
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/server.go:405 +0x224
created by github.com/pingcap/tidb/server.(*Server).Run
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/server.go:331 +0x595
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master 9afbda98d0c52a964c4a920bc259e7b5b25bc7a4

**Comment by qw4990** [comment]
After testing, this problem has been resolved.
