### ISSUE TITLE
Crash selecting from information_schema.processlist

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb#9836]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

SELECT * FROM information_schema.processlist;

2. What did you expect to see?

A list of processes.

3. What did you see instead?

```
MySQL [test]> SELECT * FROM information_schema.processlist;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

```
[2019/03/20 13:17:53.164 -07:00] [ERROR] [conn.go:537] ["connection running loop panic"] [conn=2] [lastCmd="SELECT * FROM information_schema.processlist"] [err="\"invalid memory address or nil pointer dereference\""] [stack="goroutine 191 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x5564940, 0xc00a0c4780, 0xc0006e49c0)
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:535 +0x112
panic(0x50e3c20, 0x64b54a0)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522 +0x1b5
github.com/pingcap/tidb/server.(*clientConn).writeResultset.func1(0x0, 0x55754a0, 0xc00a16a640, 0xc00a2097c8, 0x5564880, 0xc00a171700, 0xc0006e49c0)
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:1101 +0x5a9
panic(0x50e3c20, 0x64b54a0)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522 +0x1b5
github.com/pingcap/tidb/util/chunk.(*column).isNull(...)
	/Users/kolbe/Devel/git/pingcap/tidb/util/chunk/column.go:71
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendPartialRow(0xc00a210060, 0x0, 0xc00a210000, 0x0)
	/Users/kolbe/Devel/git/pingcap/tidb/util/chunk/chunk.go:313 +0xca
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendRow(...)
	/Users/kolbe/Devel/git/pingcap/tidb/util/chunk/chunk.go:305
github.com/pingcap/tidb/util/chunk.(*List).AppendRow(0xc00a15f960, 0xc00a210000, 0x0, 0x8)
	/Users/kolbe/Devel/git/pingcap/tidb/util/chunk/list.go:88 +0x13d
github.com/pingcap/tidb/executor.(*TableScanExec).nextChunk4InfoSchema.func1(0x0, 0xc00076afc0, 0x8, 0x8, 0xc00a171d80, 0x8, 0x8, 0x1, 0x1, 0x0)
	/Users/kolbe/Devel/git/pingcap/tidb/executor/executor.go:1030 +0x92
github.com/pingcap/tidb/infoschema.(*infoschemaTable).IterRecords(0xc0003edd00, 0x559bfa0, 0xc00066a700, 0x0, 0x0, 0x0, 0xc00a171d80, 0x8, 0x8, 0xc0006578a0, ...)
	/Users/kolbe/Devel/git/pingcap/tidb/infoschema/tables.go:1595 +0x122
github.com/pingcap/tidb/executor.(*TableScanExec).nextChunk4InfoSchema(0xc00a024410, 0x5564880, 0xc00a171700, 0xc00a017fb0, 0x1, 0x1)
	/Users/kolbe/Devel/git/pingcap/tidb/executor/executor.go:1028 +0x3da
github.com/pingcap/tidb/executor.(*TableScanExec).Next(0xc00a024410, 0x5564880, 0xc00a171700, 0xc0006f8680, 0x0, 0x0)
	/Users/kolbe/Devel/git/pingcap/tidb/executor/executor.go:999 +0xf7
github.com/pingcap/tidb/executor.(*recordSet).Next(0xc00a16a5f0, 0x5564880, 0xc00a171700, 0xc0006f8680, 0x0, 0x0)
	/Users/kolbe/Devel/git/pingcap/tidb/executor/adapter.go:106 +0xc0
github.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc00a16a640, 0x5564880, 0xc00a171700, 0xc0006f8680, 0x4, 0x400)
	/Users/kolbe/Devel/git/pingcap/tidb/server/driver_tidb.go:365 +0x51
github.com/pingcap/tidb/server.(*clientConn).writeChunks(0xc0006e49c0, 0x5564880, 0xc00a171700, 0x55754a0, 0xc00a16a640, 0xc000009700, 0x5564880, 0xc00a171700)
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:1150 +0x359
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc0006e49c0, 0x5564880, 0xc00a171700, 0x55754a0, 0xc00a16a640, 0xc00000e500, 0x0, 0x0, 0x0)
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:1114 +0x1e7
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc0006e49c0, 0x5564880, 0xc00a171700, 0xc00a176601, 0x2c, 0x0, 0x0)
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:1031 +0x124
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc0006e49c0, 0x5564940, 0xc00a0c4780, 0xc00a176601, 0x2d, 0x2d, 0x0, 0x0)
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:752 +0x5b8
github.com/pingcap/tidb/server.(*clientConn).Run(0xc0006e49c0, 0x5564940, 0xc00a0c4780)
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:588 +0x258
github.com/pingcap/tidb/server.(*Server).onConn(0xc00073c540, 0x557b200, 0xc0006da4e8)
	/Users/kolbe/Devel/git/pingcap/tidb/server/server.go:408 +0x400
created by github.com/pingcap/tidb/server.(*Server).Run
	/Users/kolbe/Devel/git/pingcap/tidb/server/server.go:333 +0x50e
"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:537
runtime.gopanic
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522
github.com/pingcap/tidb/server.(*clientConn).writeResultset.func1
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:1101
runtime.gopanic
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522
runtime.panicmem
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:82
runtime.sigpanic
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/signal_unix.go:390
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendPartialRow
	/Users/kolbe/Devel/git/pingcap/tidb/util/chunk/chunk.go:313
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendPartialRow
	/Users/kolbe/Devel/git/pingcap/tidb/util/chunk/chunk.go:313
github.com/pingcap/tidb/util/chunk.(*Chunk).AppendRow
	/Users/kolbe/Devel/git/pingcap/tidb/util/chunk/chunk.go:305
github.com/pingcap/tidb/util/chunk.(*List).AppendRow
	/Users/kolbe/Devel/git/pingcap/tidb/util/chunk/list.go:88
github.com/pingcap/tidb/executor.(*TableScanExec).nextChunk4InfoSchema.func1
	/Users/kolbe/Devel/git/pingcap/tidb/executor/executor.go:1030
github.com/pingcap/tidb/infoschema.(*infoschemaTable).IterRecords
	/Users/kolbe/Devel/git/pingcap/tidb/infoschema/tables.go:1595
github.com/pingcap/tidb/executor.(*TableScanExec).nextChunk4InfoSchema
	/Users/kolbe/Devel/git/pingcap/tidb/executor/executor.go:1028
github.com/pingcap/tidb/executor.(*TableScanExec).Next
	/Users/kolbe/Devel/git/pingcap/tidb/executor/executor.go:999
github.com/pingcap/tidb/executor.(*recordSet).Next
	/Users/kolbe/Devel/git/pingcap/tidb/executor/adapter.go:106
github.com/pingcap/tidb/server.(*tidbResultSet).Next
	/Users/kolbe/Devel/git/pingcap/tidb/server/driver_tidb.go:365
github.com/pingcap/tidb/server.(*clientConn).writeChunks
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:1150
github.com/pingcap/tidb/server.(*clientConn).writeResultset
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:1114
github.com/pingcap/tidb/server.(*clientConn).handleQuery
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:1031
github.com/pingcap/tidb/server.(*clientConn).dispatch
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:752
github.com/pingcap/tidb/server.(*clientConn).Run
	/Users/kolbe/Devel/git/pingcap/tidb/server/conn.go:588
github.com/pingcap/tidb/server.(*Server).onConn
	/Users/kolbe/Devel/git/pingcap/tidb/server/server.go:408"]
```

tidb_version(): Release Version: v3.0.0-beta-248-g915b12c96
Git Commit Hash: 915b12c9686bd32f944ce13c616efae7e46993d9
Git Branch: master
UTC Build Time: 2019-03-20 08:17:16
GoVersion: go version go1.12.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by kolbe** [comment]
@jackysp @morgo suggested I Cc you on this issue.

**Comment by kolbe** [comment]
Cannot repeat in release-2.1:

```
MySQL [test]> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.6-dirty
Git Commit Hash: 66e639e8e127f71662f37287eb984dd84d169cba
Git Branch: release-2.1
UTC Build Time: 2019-03-20 08:31:49
GoVersion: go version go1.12.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.001 sec)

MySQL [test]> SELECT * FROM information_schema.processlist;
+------+------+-----------+------+---------+------+-------+----------------------------------------------+
| ID   | USER | HOST      | DB   | COMMAND | TIME | STATE | Info                                         |
+------+------+-----------+------+---------+------+-------+----------------------------------------------+
|    1 | root | 127.0.0.1 | test | Query   |    0 | 2     | SELECT * FROM information_schema.processlist |
+------+------+-----------+------+---------+------+-------+----------------------------------------------+
1 row in set (0.001 sec)
```

**Comment by jackysp** [comment]
Hi @kolbe , thanks for your report!
PTAL @tiancaiamao .
