### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by cppmule** [pingcap/tidb#990]
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java -ea -Didea.launcher.port=7533 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA 14.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA 14.app/Contents/plugins/junit/lib/junit-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/tmp/classes/test/waimai100_backend:/Users/cppmule/idea-workspace/waimai100_backend/trunk/tmp/classes/production/waimai100_backend:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/jjwt-0.4.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/asm-5.0.3.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/cglib-3.1.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/guava-18.0.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/ognl-2.6.9.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/okio-1.3.0.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/dozer-5.3.2.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/httpmime-4.5.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/jsr305-1.3.9.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/okhttp-2.3.0.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/fluent-hc-4.5.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/httpclient-4.5.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/httpcore-4.4.1.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/hamcrest-all-1.3.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/mockito-all-1.9.5.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/pingpp-java-2.1.1.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/assertj-core-3.2.0.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/jackson-core-2.4.2.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/unitils-core-3.4.2.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/bcprov-jdk15on-1.51.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/qiniu-java-sdk-7.0.3.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/weixin-java-mp-1.3.1.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/commons-httpclient-3.1.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/jackson-databind-2.4.2.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/weixin-java-common-1.3.1.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/lib/jackson-annotations-2.4.0.jar:/Users/cppmule/dev-tools/play-1.3.1/modules/docviewer/lib/play-docviewer.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/mockito-0.1/lib/play-mockito.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/mockito-0.1/lib/mockito-all-1.9.1-SNAPSHOT.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/ant-1.7.0.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/play-spring.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/jsr166-1.7.0.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/jopt-simple-3.0.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/ant-launcher-1.7.0.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/spring-aop-3.1.1.RELEASE.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/spring-asm-3.1.1.RELEASE.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/spring-core-3.1.1.RELEASE.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/spring-beans-3.1.1.RELEASE.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/spring-context-3.1.1.RELEASE.jar:/Users/cppmule/idea-workspace/waimai100_backend/trunk/modules/spring-1.0.3/lib/spring-expression-3.1.1.RELEASE.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/ivy-2.4.0.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/oval-1.84.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/c3p0-0.9.5.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/gson-2.3.1.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/h2-1.4.185.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/jamon-2.81.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/jj-imaging.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/jj-textile.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/junit-4.12.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/mail-1.4.7.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/antlr-2.7.7.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/dom4j-1.6.1.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/jaxen-1.1.6.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/jj-wikitext.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/log4j-1.2.17.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/asm-all-5.0.3.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/ezmorph-1.0.6.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/joda-time-2.7.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/jregex-1.2_01.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/xstream-1.4.7.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/commons-io-2.4.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/postgresql-9.0.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/snakeyaml-1.15.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/cglib-nodep-3.1.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/jsr107cache-1.0.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/xmlpull-1.1.3.1.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/activation-1.1.1.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/commons-lang-2.6.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/groovy-all-2.3.9.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/javax.inject-1.0.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/jj-simplecaptcha.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/slf4j-api-1.7.10.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/bcprov-jdk15-1.45.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/hamcrest-core-1.3.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/netty-3.9.4.Final.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/commons-codec-1.10.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/commons-email-1.3.3.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/commons-logging-1.2.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/ehcache-core-2.6.11.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/javassist-3.19.0-GA.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/spymemcached-2.11.7.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/slf4j-log4j12-1.7.10.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/signpost-core-1.2.1.2.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/jboss-logging-3.1.0.GA.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/commons-beanutils-1.8.3.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/validation-api-1.0.0.GA.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/async-http-client-1.8.14.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/commons-fileupload-1.3.1.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/commons-javaflow-1590792.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/commons-collections-3.2.1.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/mchange-commons-java-0.2.9.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/hibernate-c3p0-4.2.15.Final.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/hibernate-core-4.2.15.Final.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/mysql-connector-java-5.1.35.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/c3p0-oracle-thin-extras-0.9.5.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/geronimo-servlet_2.5_spec-1.2.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/hibernate-validator-4.1.0.Final.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/hibernate-jpa-2.0-api-1.0.1.Final.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/hibernate-entitymanager-4.2.15.Final.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/hibernate-commons-annotations-4.0.2.Final.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/jboss-transaction-api_1.1_spec-1.0.1.Final.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/org.eclipse.jdt.core-3.10.0.v20140604-1726.jar:/Users/cppmule/dev-tools/play-1.3.1/framework/play-1.3.1.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 models.FoodOrderTest
13:54:58,194 INFO  ~ Starting /Users/cppmule/idea-workspace/waimai100_backend/trunk/.
:: loading settings :: url = jar:file:/Users/cppmule/dev-tools/play-1.3.1/framework/lib/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
13:54:59,015 INFO  ~ Module spring is available (/Users/cppmule/idea-workspace/waimai100_backend/trunk/./modules/spring-1.0.3)
13:54:59,016 INFO  ~ Module mockito is available (/Users/cppmule/idea-workspace/waimai100_backend/trunk/./modules/mockito-0.1)
13:55:00,999 WARN  ~ You're running Play! in DEV mode
13:55:19,770 ERROR ~ Database [default] Cannot connected to the database : An attempt by a client to checkout a Connection has timed out.
java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at play.db.DBPlugin.onApplicationStart(DBPlugin.java:183)
	at play.plugins.PluginCollection.onApplicationStart(PluginCollection.java:515)
	at play.Play.start(Play.java:537)
	at play.test.PlayJUnitRunner.<init>(PlayJUnitRunner.java:38)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.mchange.v2.resourcepool.TimeoutException: A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@29896529 -- timeout at awaitAvailable()
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1461)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:639)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:549)
	... 14 more

play.exceptions.DatabaseException: Cannot connected to the database[default], An attempt by a client to checkout a Connection has timed out.
	at play.db.DBPlugin.onApplicationStart(DBPlugin.java:200)
	at play.plugins.PluginCollection.onApplicationStart(PluginCollection.java:515)
	at play.Play.start(Play.java:537)
	at play.test.PlayJUnitRunner.<init>(PlayJUnitRunner.java:38)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
	at play.db.DBPlugin.onApplicationStart(DBPlugin.java:183)
	at play.plugins.PluginCollection.onApplicationStart(PluginCollection.java:515)
	at play.Play.start(Play.java:537)
	at play.test.PlayJUnitRunner.<init>(PlayJUnitRunner.java:38)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	... 1 more
Caused by: com.mchange.v2.resourcepool.TimeoutException: A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@29896529 -- timeout at awaitAvailable()
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1461)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:639)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:549)
	... 14 more

Process finished with exit code 255

**Comment by coocood** [comment]
This issue doesn't have enough information to address.
