### ISSUE TITLE
Data truncation: BIT value is out of range in '(1)'

### ISSUE THREAD

**Issue by powqabc** [pingcap/tidb#9997]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
tidb从2.0.11升级到2.1.6后。mysql表中有个字段类型是bit(1)，然后通过otter同步到tidb表是报错，**nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: BIT value is out of range in '(1)'。**  
只要存在bit(1)类型字段的表都报错了，具体的报错信息如下：
pid:1141 nid:91 exception:setl:com.alibaba.otter.node.etl.load.exception.LoadException: java.util.concurrent.ExecutionException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: com.alibaba.otter.node.etl.load.exception.LoadException: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [insert into `tidb_creditcloud`.`collection_ai_apply_info`(`partner_code` , `app_name` , `collection_id` , `task_id` , `invoke_mode` , `login_id` , `status` , `collection_params` , `gmt_create` , `customer_name` , `phone_num` , `id_number` , `due_amount` , `unique_identifier` , `risk_level` , `primary_code` , `remove_status` , `auto_result` , `apply_decreased_flow` , `overdue_day` , `collection_type` , `repair_decreased_flow` , `pre_decreased_flow` , `whether_test` , `challenge_uuid` , `id`) values (? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ? , ?) on duplicate key update `partner_code`=values(`partner_code`) , `app_name`=values(`app_name`) , `collection_id`=values(`collection_id`) , `task_id`=values(`task_id`) , `invoke_mode`=values(`invoke_mode`) , `login_id`=values(`login_id`) , `status`=values(`status`) , `collection_params`=values(`collection_params`) , `gmt_create`=values(`gmt_create`) , `customer_name`=values(`customer_name`) , `phone_num`=values(`phone_num`) , `id_number`=values(`id_number`) , `due_amount`=values(`due_amount`) , `unique_identifier`=values(`unique_identifier`) , `risk_level`=values(`risk_level`) , `primary_code`=values(`primary_code`) , `remove_status`=values(`remove_status`) , `auto_result`=values(`auto_result`) , `apply_decreased_flow`=values(`apply_decreased_flow`) , `overdue_day`=values(`overdue_day`) , `collection_type`=values(`collection_type`) , `repair_decreased_flow`=values(`repair_decreased_flow`) , `pre_decreased_flow`=values(`pre_decreased_flow`) , `whether_test`=values(`whether_test`) , `challenge_uuid`=values(`challenge_uuid`) , `id`=values(`id`)]; Data truncation: BIT value is out of range in '(1)'; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: BIT value is out of range in '(1)'
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:603)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:812)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:868)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker$2.doInTransaction(DbLoadAction.java:650)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.doCall(DbLoadAction.java:642)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$DbLoadWorker.call(DbLoadAction.java:570)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doTwoPhase(DbLoadAction.java:487)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.doLoad(DbLoadAction.java:279)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction.load(DbLoadAction.java:165)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$FastClassByCGLIB$$d932a4cb.invoke()
at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:191)
at org.springframework.aop.framework.Cglib2AopProxy$DynamicAdvisedInterceptor.intercept(Cglib2AopProxy.java:618)
at com.alibaba.otter.node.etl.load.loader.db.DbLoadAction$$EnhancerByCGLIB$$80fd23c2.load()
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:198)
at com.alibaba.otter.node.etl.load.loader.db.DataBatchLoader$2.call(DataBatchLoader.java:189)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: BIT value is out of range in '(1)'
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3974)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:818)
at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:1)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:587)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
5.7.25-TiDB-v2.1.6

**Comment by shenli** [comment]
@powqabc Could you tell us how to reproduce this issue?

**Comment by powqabc** [comment]
不知道怎么复现

**Comment by jackysp** [comment]
Is there more detailed information now? If not, I will close the issue first. Please feel free to reopen it when you need it. @powqabc
